### ISSUE TITLE
error in compile makefile

### ISSUE THREAD

**Issue by pahlevan** [crosstool-ng/crosstool-ng#1004]
crosstool-NG version: 1.23.0.418-d590
host OS : mint 19 (x64)

**[ALL  ]    /home/pahlevan/toolchain/bin/.build/x86_64-unknown-linux-gnu/src/make/glob/glob.c:1367: undefined reference to `__alloca'**

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2227574/build.log)
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/2227578/config.zip)

**Comment by stilor** [comment]
Need to backport to make 4.2.1 (and possibly earlier releases)
http://git.savannah.gnu.org/cgit/make.git/commit/?id=48c8a116a914a325a0497721f5d8b58d5bba34d4

and likely:
http://git.savannah.gnu.org/cgit/make.git/commit/?id=193f1e81edd6b1b56b0eb0ff8aa4b41c7b4257b4
