### ISSUE TITLE
Problem With building Based on armv6-nommu-linux-uclibcgnueabi

### ISSUE THREAD

**Issue by sebastianpszczolka** [crosstool-ng/crosstool-ng#1009]
I tried build toolchain for cortexm-3, uclibc-ng, no-mmu, pthread, architecture level armv7-m.
 I have strange error during assembly.
libc/sysdeps/linux/arm/setcontext.S:63: Error: LR and PC should not both be in register list -- `ldmia r14,{r14,pc}'
Machine:  Debian 9.0
Crosstol: 1.23.0
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/2261728/config.zip)
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/2261729/build.zip)
Thank for help

**Comment by stilor** [comment]
Explained in this commit's message: https://github.com/crosstool-ng/crosstool-ng/commit/57679b5e610e488cc6c25b259331cb25d412c771

**Comment by cpackham** [comment]
Might have reappeared as #1397
