### ISSUE TITLE
Build failed in step 'Installing binutils for host'

### ISSUE THREAD

**Issue by Krymancer** [crosstool-ng/crosstool-ng#1010]
crosstool-NG version: 1.23.0
host OS and its version: Debian 9.4 stretch, kernel x86_64 Linux 4.9.0-6-amd64
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/2285131/build.log.txt)
)

I configured Linux with the ct-ng arm-cortex_a8-linux-gnueabi, k Linux kernel version (4.4.59), gcc version (6.3.0) command and got this error:

[INFO] ====================================================== ==================
[INFO] Installing binutils for host
[DEBUG] Entering '/home/junior/Embarcados/toolchain/.build/arm-cortex_a8-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[EXTRA] Configuring binutils
[DEBUG] Extra config passed: '--enable-ld = yes --enable-gold = no --enable-plugins --with-pkgversion = crosstool-NG crosstool-ng-1.23.0 --disable-multilib - disable-sim --disable-gdb --disable-nls'
[DEBUG] ==> Executing: 'CC_FOR_BUILD = x86_64-build_pc-linux-gnu-gcc' 'CFLAGS_FOR_BUILD =' 'CFLAGS = -O2 -g -pipe -I / home / junior / Embarcados / toolchain / .build / / linux-gnueabi / buildtools / include '' CXXFLAGS = -O2 -g -pipe -I / home / junior / Embedded / toolchain / .build / arm-cortex_a8-linux-gnueabi / buildtools / include '' LDFLAGS = -L /home/junior/Embarcados/toolchain/.build/arm-cortex_a8-linux-gnueabi/buildtools/lib '' / bin / bash '' /home/junior/Embarcados/toolchain/.build/src/binutils-2.26/configure linux-gnu '' --host = x86_64-build_pc-linux-gnu '' --target = arm-cortex_a8-linux-gnueabi '' --prefix = Linux '' --build = x86_64-build_pc- disable-werror '' --enable-ld = yes '' --enable-gold = no '' --enable-plugins '' --with-pkgversion = crosstool-NG crosstool-ng-1.23.0 '' - disable-multilib '' --disable-yes '' --disable-gdb '' --disable-nls '' --with-float = soft '' --with-sysroot = Linux / arm-cortex_a8-linux-gnueabi / sysroot '
[ERROR] configure: error: expected an absolute directory name for --prefix: Linux
[ERROR]
[ERROR] >>
[ERROR] >> Build failed in step 'Installing binutils for host'
[ERROR] >> called in step '(top-level)'
[ERROR] >>
[ERROR] >> Error happened in: CT_DoExecLog [scripts / functions @ 338]
[ERROR] >> called from: do_binutils_backend [scripts/build/binutils/binutils.sh@201]
[ERROR] >> called from: do_binutils_for_host [scripts/build/binutils/binutils.sh@97]
[ERROR] >> called from: main [scripts / crosstool-NG.sh@653]
[ERROR] >>
[ERROR] >> For more info on this error, look at the file: 'build.log'
[ERROR] >> There is a list of known issues, some with workarounds, in:
[ERROR] >> '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.23.0/B - Known issues.txt'
[ERROR] >>
[ERROR] >> If you feel this is a bug in crosstool-NG, report it at:
[ERROR] >> https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR] >>
[ERROR] >> Make sure your report includes all the information pertinent to this issue.
[ERROR] >> Read the bug reporting guidelines here:
[ERROR] >> http://crosstool-ng.github.io/support/
[ERROR]
[ERROR] (elapsed: 13: 31.59)

**Comment by stilor** [comment]
Well, as the error message states - you configured a relative path for CT_PREFIX_DIR and an absolute path is needed.

Crosstool-NG should reject this much earlier, though. I'll make a fix.
