### ISSUE TITLE
Cannot build arm64 bare-metal toolchain

### ISSUE THREAD

**Issue by DrewSingletary** [crosstool-ng/crosstool-ng#1011]
Crosstool-NG version: 1.23.0
Host OS: OS X High Sierra
Config: [configuration.txt](https://github.com/crosstool-ng/crosstool-ng/files/2292174/configuration.txt)
Build log: [build.log](https://github.com/crosstool-ng/crosstool-ng/files/2292175/build.log)

I am getting the same error as issue #745, where binutils will not build  Was there a resolution to this issue?  

I have successfully built the aarch64-unknown-linux-gnueabi toolchain, and used it to compile the Linux kernel, but I have tried many times to get the bare-metal version built, but I am unable.

I attempted to build with the binutils extra config of --target=aarch64-unknown-elf, and this was the resulting config and log.

[failedConfig.txt](https://github.com/crosstool-ng/crosstool-ng/files/2292177/failedConfig.txt)
[failedBuild.log](https://github.com/crosstool-ng/crosstool-ng/files/2292178/failedBuild.log)

Any advice on how to build such a toolchain?

**Comment by stilor** [comment]
See the commit referenced in #745: it was resolved by making the `ARCH_ARM_EABI` option only depend on 32-bit ARM selection. Without this option, `scripts/build/arch/arm.sh` does not change `-elf` into `eabi` in the target tuple.
