### ISSUE TITLE
Zlib error under curl

### ISSUE THREAD

**Issue by red0bear** [crosstool-ng/crosstool-ng#1017]
hi there. Im using last version of your software from github

I'm trying to compile curl from github with zlib but it give this error:  arm-unknown-linux-gnueabi/buildtools/lib/libz.a: error adding symbols: File format not recognized

**Comment by red0bear** [comment]
i found another bizarre error ..... i was trying to link some stuffs but
i was expecting looking in this path:
 .build/arm-unknown-linux-gnueabi/buildtools/lib
but i got this:
.build/arm-unknown-linux-gnueabi/buildtools/lib/gcc/arm-unknown-linux-gnueabi/8.1.0/../../../../arm-unknown-linux-gnueabi/bin/ld.bfd

the ld.bfd in repective dir is arm-unknown-linux-gnueab-ld.bfd  not only ld.bfd

**Comment by stilor** [comment]
hard to say anything without the logs or commands that you tried.

**Comment by red0bear** [comment]
Well ... i just say something goes wrong in path ... and it try look in another path ... not in what i beleive it is.

**Comment by stilor** [comment]
Probably. But I am not going to spend any time trying to guess what it is. There is a reason we have issue submission guidelines - that you chose not to follow.

**Comment by red0bear** [comment]
@stilor What ? Man ... i just build ct-ng in standart mode ... and try build a standalone curl. This build for curl inst go during build for ct-ng.

**Comment by stilor** [comment]
Stop wasting my time. Go and read http://crosstool-ng.github.io/support/ before you make another comment.
