### ISSUE TITLE
How to bootstrap the the ct-ng tool build out of tree?

### ISSUE THREAD

**Issue by cirosantilli** [crosstool-ng/crosstool-ng#1021]
I am a perfectionist and I want to keep my source tree clean and pristine!

I can now do almost everything out of tree, except for the `./bootstrap`. This works but adds some in-tree files:

```
mkdir tmp
./bootstrap
cd tmp
../configure --enable-local
make -j`nproc`
```

However, if I try to do the `./bootstrap` from inside `tmp/` to keep if out of tree as well:

```
cd tmp
../bootstrap
```

it fails with:

```
INFO  :: *** Generating package version descriptions
../bootstrap: line 611: cd: packages: No such file or directory
INFO  :: Master packages:
../bootstrap: line 626: maintainer/package-versions: No such file or directory
INFO  :: *** Generating menu/choice selections
INFO  :: Generating arch.in (choice)
ERROR :: Template 'maintainer/kconfig-choice.template' not found
```

Is there a way?

**Comment by stilor** [comment]
Running bootstrap is considered a maintainer's task (i.e., the released tarball would already have the configure and the generated kconfig fragments). Therefore, it is expected to generate this stuff in the source directory.
