### ISSUE TITLE
How to use the built dynamic loader and dynamic libraries on a native x86 build without passing any extra -Wl options?

### ISSUE THREAD

**Issue by cirosantilli** [crosstool-ng/crosstool-ng#1030]
ctng a6580b8e8b55345a5a342b5bd96e42c83e640ac5 on Ubuntu 18.04 host.

```
export CT_PREFIX="$(pwd)/.build/install"
./ct-ng x86_64-unknown-linux-gnu
env -u LD_LIBRARY_PATH time ./ct-ng build -j`nproc`
```

Now, if I build a hello world example with:

```
glibc_install="$(pwd)/.build/install/x86_64-unknown-linux-gnu"
PATH="${PATH}:${glibc_install}/bin" \
  x86_64-unknown-linux-gnu-gcc \
  -v \
  -o main.out \
  main.c \
;
ldd ./main.out
```

I observe that the host packaged dynamic linker and libraries are used:

```
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f82214a7000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8221ab7000)
```

instead of the ones which I've just built, which is what I'd want.

If however I force it by adding the command line options:

```
  -Wl,--dynamic-linker="${glibc_install}/x86_64-unknown-linux-gnu/sysroot/lib/ld-linux-x86-64.so.2" \
  -Wl,--rpath="${glibc_install}/x86_64-unknown-linux-gnu/sysroot/lib" \
```

then is picks up the linker and libraries that I want.

Is there a way to build my toolchain so that I don't need to pass those options around all the time? Why isn't that the default behavior?

**Comment by stilor** [comment]
Of course it is using the host's linker and libraries. The purpose of **cross** compilation is to build a binary that will run in a *different* environment than the machine it is compiled upon. Generally speaking, the target architecture may not be even compatible with the host - you cannot run, say, MIPS binaries on x86 host. Instead, it is expected that these libraries (and dynamic linker) make their way somehow onto the target machine - where they'll reside at their normal locations, such as `/lib/libc.so.6` and so on.

You may not even be able to run the GCC that you just built on the machine you built it on! Read about what a "canadian cross" build is.

For such limited-compatibility setups where the host and the target share the architecture, it may be possible to do a `chroot` into the environment where the "sysroot" is copied and run. Beware though, it is not officially supported - as even different kernel version selected for the target may break such setup.

If you need to check what libraries a given binary depends on, you can use a shell script (xldd, optionally installed by crosstool-NG) that provides a similar output for a cross-development environment.

**Comment by cirosantilli** [comment]
> Of course it is using the host's linker and libraries. The purpose of **cross** compilation is to build a binary that will run in a _different_ environment than the machine it is compiled upon. Generally speaking, the target architecture may not be even compatible with the host - you cannot run, say, MIPS binaries on x86 host. Instead, it is expected that these libraries (and dynamic linker) make their way somehow onto the target machine - where they'll reside at their normal locations, such as `/lib/libc.so.6` and so on.
> 
> You may not even be able to run the GCC that you just built on the machine you built it on! Read about what a "canadian cross" build is.
> 

Thanks for confirming that it is not a supported use case.

I do understand that the normal use case for cross compilation is to run the executable on the target using root filesystem installed stuff.

I'm just trying this out because the GCC toolchain build system is terrible, and you have the best GCC compilation setup out there, which could be really valuable for people who want to develop GCC toolchain components or have multiple toolchains installed on host to run stuff on host.

Do you know if GCC has any configuration flags to set a custom dynamic loader / rpath by default, even if not exposed through ctng?

> For such limited-compatibility setups where the host and the target share the architecture, it may be possible to do a `chroot` into the environment where the "sysroot" is copied and run. Beware though, it is not officially supported - as even different kernel version selected for the target may break such setup.
> 

Does `CT_LINUX_3_2_or_later` imply that any host kernel newer than that would work? What other incompatibilities could there be?

> If you need to check what libraries a given binary depends on, you can use a shell script (xldd, optionally installed by crosstool-NG) that provides a similar output for a cross-development environment.

I'll give that a try.

**Comment by stilor** [comment]
> Do you know if GCC has any configuration flags to set a custom dynamic loader / rpath by default, even if not exposed through ctng?

Short of editing the spec file fragments, I can't think of another way of configuring this default.

> Does CT_LINUX_3_2_or_later imply that any host kernel newer than that would work? What other incompatibilities could there be?

These symbols are just for specifying the version dependencies between the packages. What I meant is that a target configuration with a newer kernel version may result in glibc detecting some kernel interfaces and trying to use them - which would fail if the library is then loaded on an older kernel.

> `chroot` is a possibility, but it is too inconvenient for normal use. Do you see anything specifically that would break by just using ...

No, so long as you know the target kernel to be compatible with the build machine's (typically, it means the target kernel version should be set to less than or equal to the build machine's kernel version).

**Comment by hongyi-zhao** [comment]
> Of course it is using the host's linker and libraries. The purpose of **cross** compilation is to build a binary that will run in a _different_ environment than the machine it is compiled upon. Generally speaking, the target architecture may not be even compatible with the host - you cannot run, say, MIPS binaries on x86 host. Instead, it is expected that these libraries (and dynamic linker) make their way somehow onto the target machine - where they'll reside at their normal locations, such as `/lib/libc.so.6` and so on.
> 
> You may not even be able to run the GCC that you just built on the machine you built it on! Read about what a "canadian cross" build is.
> 
> For such limited-compatibility setups where the host and the target share the architecture, it may be possible to do a `chroot` into the environment where the "sysroot" is copied and run. Beware though, it is not officially supported - as even different kernel version selected for the target may break such setup.
> 
> If you need to check what libraries a given binary depends on, you can use a shell script (xldd, optionally installed by crosstool-NG) that provides a similar output for a cross-development environment.

I tried to compile with the following steps:

```
./bootstrap 
./configure --enable-local
make 
```

But I cannot find the xldd gernerated by the make at all?

Any hints?
Regards

**Comment by stefanct** [comment]
It would still be nice if this would be supported. Even if creating cross compilers is the main use case for ct-ng it is also useful to generate different build chains on/for the host system (as an alternative to install containers).
