### ISSUE TITLE
error running ./bootstrap after cloning

### ISSUE THREAD

**Issue by edadma** [crosstool-ng/crosstool-ng#1034]
crosstool-NG version: 1.23.0
OS and its version: Linux Mint 19 (based on Ubuntu 18.04)

these were the last 5 lines of output

```
INFO  :: *** Gathering the list of data files to install
INFO  :: *** Running autoreconf
Can't exec "aclocal": No such file or directory at /usr/share/autoconf/Autom4te/FileUtils.pm line 326.
autoreconf: failed to run aclocal: No such file or directory
INFO  :: *** Done!
```

the solution was to install `automake` - should be added to the list of required packages for Ubuntu in the section "Setting up host OS" in the docs.

**Comment by stilor** [comment]
Fixed. Next time there's an issue with the docs, please submit an issue/pull request against our docs repository: https://github.com/crosstool-ng/crosstool-ng.github.io
