### ISSUE TITLE
Request: Add custom string for glibc version

### ISSUE THREAD

**Issue by oblique** [crosstool-ng/crosstool-ng#1059]
I'm creating a toolchain that needs to have glibc 2.11, I use glibc's git repository for this.
I'm getting the following error on `./configure` of gcc 6.4.0:

```
[ERROR]    checking for target glibc version... configure: error: option --with-glibc-version requires a version number M.N
```

Since gcc needs to have a real version number, one solution is to a way to define your own custom value  that will be passed to `--with-glibc-version`.

**Comment by stilor** [comment]
Duplicate of #1031
