### ISSUE TITLE
./configure, error when searching for ncurses/menu.h and menu.h, build stops

### ISSUE THREAD

**Issue by bdashore3** [crosstool-ng/crosstool-ng#1068]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/
). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

Version: source (Github) 1.23.0
Host OS: Mac OS
Packages: All dependencies required when running brew install crosstool-ng
Config: Configure file generated through ./bootstrap attached as configurelog.txt
[configurelog.txt](https://github.com/crosstool-ng/crosstool-ng/files/2512272/configurelog.txt)

build.log: Terminal log is attached configure.txt
[configure.txt](https://github.com/crosstool-ng/crosstool-ng/files/2512271/configure.txt)

When I run ./configure on my OS when building from source, I always get this error even though I have ncurses installed
`checking for Curses Menu library with menu.h... no
checking for Curses Menu library with ncurses/menu.h... no
configure: error: menu library not found`

I'm not sure if it's the ./bootstrap because it shows when running autoreconf
`configure.ac:245: warning: macro 'AM_GNU_GETTEXT' not found in library
configure.ac:246: warning: macro 'AM_GNU_GETTEXT_VERSION' not found in library
`

**Comment by stilor** [comment]
Can you try current `master`? The home-grown curses&friends detection has been replaced with the module from autoconf-archive since 1.23.0 release.

**Comment by bdashore3** [comment]
I typed 
`git clone https://github.com/crosstool-ng/crosstool-ng -b master`
and the same thing happened

**Comment by roolebo** [comment]
@bdashore3 please try:
`brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/3e1324e48e09f66cde68f495596a576bd8dc416e/Formula/crosstool-ng.rb --HEAD`

A PR for that has been sent to homebrew: https://github.com/Homebrew/homebrew-core/pull/33961

**Comment by stilor** [comment]
@roolebo Does it mean I can close this issue?

**Comment by roolebo** [comment]
@stilor I think so. With regards to ncurses and gettext location on mac. `CPPFLAGS` should be set to point to ncurses and gettext from homebrew, then configure will be able to find it:
```
ncurses is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

If you need to have ncurses first in your PATH run:
  echo 'export PATH="/usr/local/opt/ncurses/bin:$PATH"' >> ~/.zshrc

For compilers to find ncurses you may need to set:
  export LDFLAGS="-L/usr/local/opt/ncurses/lib"
  export CPPFLAGS="-I/usr/local/opt/ncurses/include"

For pkg-config to find ncurses you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/ncurses/lib/pkgconfig"
```

```
gettext is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.zshrc

For compilers to find gettext you may need to set:
  export LDFLAGS="-L/usr/local/opt/gettext/lib"
  export CPPFLAGS="-I/usr/local/opt/gettext/include"
```

**Comment by bdashore3** [comment]
I'll close it, It worked properly for me
