### ISSUE TITLE
Documentation: missing prerequsites - autoconf, awk?

### ISSUE THREAD

**Issue by TM1234** [crosstool-ng/crosstool-ng#1071]
I followed the ubuntu prerequisite instructions here on Ubuntu 16.04 (admittedly the desktop rather than server version mentioned here):

https://crosstool-ng.github.io/docs/os-setup/

but ./bootstrap failed with:

```
INFO  :: *** Gathering the list of data files to install
INFO  :: *** Running autoreconf
./bootstrap: line 774: autoreconf: command not found
INFO  :: *** Done!
```
Once I installed autoconf it succeeded.
So should this:

```
apt-get install gcc gperf bison flex texinfo help2man make libncurses5-dev \
	python-dev libtool-bin
```
be 
```
apt-get install gcc gperf bison flex texinfo help2man make libncurses5-dev \
	python-dev libtool-bin autoconf
```

And ditto for other OSs if applicable?

**Comment by stilor** [comment]
Yes, they both should. But rather than updating the docs with individual packages, I am currently setting up these reference host OS as Docker containers in `testing/docker`. I will update the docs to refer to the `Dockerfile`s for setup instructions once all these OSes have their respective configurations.

**Comment by stilor** [comment]
No. I have some experience with Docker, but haven't used Vagrant myself. From a quick glance at Vagrant's website, it wasn't clear if it also allows to run FreeBSD/Windows as a guest in the container, or if it only supports FreeBSD/Windows as a host. If it can run non-Linux guests on Linux, using Vagrant would make sense.

**Comment by TM1234** [comment]
Well Vagrant supports a variety of VM tools with Oracle VirtualBox being a common choice and VirtualBox supports most or all Linux/Windows OSs as hosts and guests. If you want further info/advice I can have a colleague who is much better acquainted with Vagrant than I am post here or elsewhere with further advice/suggestions when he's back from vacation next week?

**Comment by stilor** [comment]
Docs are updated to point to Dockerfiles for the lists of packages.

**Comment by TM1234** [comment]
> Docs are updated to point to Dockerfiles for the lists of packages.

Can you clarify where this is? I can't see anything about docker here for example:

https://crosstool-ng.github.io/docs/install/
https://crosstool-ng.github.io/docs/os-setup/

And the docs still omit autoconf and awk for Ubuntu that I mentioned above.

**Comment by stilor** [comment]
Oops, forgot to push/create PR:
https://github.com/crosstool-ng/crosstool-ng.github.io/pull/28
