### ISSUE TITLE
MacOs trying to setup ct-ng error "Building make"

### ISSUE THREAD

**Issue by georgesovon** [crosstool-ng/crosstool-ng#1076]
This is crosstool-NG version crosstool-ng-1.23.0

MacOs 10.14
Darwin Georgess-MBP-2 18.0.0 Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64 x86_64

Following guide https://medium.com/coinmonks/setup-gcc-8-1-cross-compiler-toolchain-for-raspberry-pi-3-on-macos-high-sierra-cb3fc8b6443e

Step:
ct-ng companion_tools_for_build+

Attached build.log
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2525790/build.log)

Any help is welcome.

**Comment by bdashore3** [comment]
Use automake v1.15.1 instead of 1.15, 1.15 is broken when compiling toolchains

**Comment by georgesovon** [comment]
Thank you for your reply:
I looked that the automake directory:
drwxr-xr-x  5 georges  staff  160 29 Oct 13:19 1.11.6
drwxr-xr-x  5 georges  staff  160 29 Oct 13:19 1.14.1
drwxr-xr-x  4 georges  staff  128 29 Oct 13:19 1.15.1
drwxr-xr-x  4 georges  staff  128 29 Oct 13:19 1.16.1
-rw-r--r--  1 georges  staff  189 29 Oct 13:19 package.desc
Georgess-MacBook-Pro-2:automake georges$ pwd
/Volumes/xtool-build-env/packages/automake
It does not look as it I am using v1.15, or have a copy.

In case you mean the one on the Mac it is:
automake 1.16.1_1 is already installed and up-to-date

Is it possible that v.16.1 is broken ?

Thank you for your time.

**Comment by bdashore3** [comment]
If you followed the guide, you should have downloaded the packages folder from this github, then put it inside your case sensitive disk image. The .config file provided on the guide makes sure you use these packages (provided your image is names xtool-build-env). Ct-ng will use the local packages specified instead of using the system packages

**Comment by georgesovon** [comment]
Again I must thank you for your response. I am sorry, but I must be missing something here.
I can see that the guide is a little out of date, but I did try to use the latest items from the repository.
I am using a case sensitive disc image. I have downloaded crosstool-ng/1.23.0_2. I had not updated the .config file, so I have now made several attempts to do so. The following lines:
CT_CONFIGURE_has_automake_1_16_1_or_newer=y
CT_AUTOMAKE_V_1_16_1=y
CT_AUTOMAKE_VERSION="1.16.1"
I have tried 1.15.1 and 1.16.1 but I get the same error when building.

I have then tried changing the GCC in the config. (I could not see 8.1.0 anywhere?), but updated the following:
CT_CC_GCC_VERSION="8.2.0"
CT_CC_GCC_V_8_2_0=y
But these changes were from much earlier versions.
In all cases I still get:
[EXTRA]    Building make
[ERROR]    make[2]: *** [/Volumes/xtool-build-env/.build/src/make-4.2.1/aclocal.m4] Error 127

Best regards

**Comment by georgesovon** [comment]
Given the number of changes I have made and the number of build attempts, I thought it best to try a new build in a fresh environment. So, having deleted the Volume, and started fresh, and applying the automake, and gcc changes first, I rebuilt. It still fails on make, but now I have a different issue.

[INFO ]  Installing make for build
[EXTRA]    Configuring make
[EXTRA]    Building make
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[4]: *** [make] Error 1
[ERROR]    make[3]: *** [all-recursive] Error 1
[ERROR]    make[2]: *** [all] Error 2

I've attached the log file.
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2537940/build.log)

**Comment by georgesovon** [comment]
Given the number of changes I have made and the number of build attempts, I thought it best to try a new build in a fresh environment. So, having deleted the Volume, and started fresh, and applying the automake, and gcc changes first, I rebuilt. It still fails on make, but now I have a different issue.

[INFO ]  Installing make for build
[EXTRA]    Configuring make
[EXTRA]    Building make
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[4]: *** [make] Error 1
[ERROR]    make[3]: *** [all-recursive] Error 1
[ERROR]    make[2]: *** [all] Error 2

I've attached the log file.
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2537940/build.log)

**Comment by georgesovon** [comment]
Again thank you for your replies and for your time.
I have resolved the problem I was working on by using a virtual machine and a pre-build cross compiler. I can see that toolchain-ng is a very powerful tool, but more than I needed at this time.
I suspect the problem was user error on my part, or something with MacOs. Either way if I need to try again in the future I will do so from a Linux platform.
Best regards

**Comment by Luffy4321** [comment]
I have the same problem.
Do you have some solutions with MacOs？

**Comment by stilor** [comment]
No, I don't have any solutions for macOS, sorry. I explained it here:

http://crosstool-ng.github.io/2018/11/26/macos.html

If you have *exactly* the same error as posted above in the build.log - it looks like an issue with the build tools on macOS (CoreFoundation is a system library provided by macOS - so if clang complains there's something wrong with it - there's nothing ct-ng can do about it). But I am not macOS expert - so with any macOS questions, you'd have to hope that some fellow macOS user comes to your aid.

**Comment by troian** [comment]
@stilor fyi
https://medium.com/@twister.mr/installing-macos-to-virtualbox-1fcc5cf22801

**Comment by stilor** [comment]
@troian Yes, I saw this or a similar setup guide before. The problem is not technical feasibility; the problem is the legality of such installation. Somewhere during the install macOS presents a dialog that, as far as I remember, requires me to assert that either (a) I am installing this on a physical Apple hardware or (b) I am installing it in an emulator, but I own Apple hardware compatible with this OS - MacBook or desktop. Neither applies to me.

**Comment by troian** [comment]
@stilor I'm still trying to workaround environment :)
Can it be an option? https://docs.travis-ci.com/user/reference/osx/

**Comment by stilor** [comment]
It would've been workable - even though quite inconvenient [1] if TravisCI hadn't limited the runtime of a job. I've disabled running Travis CI on commits in crosstool-NG for that exact reason.

[1] Inconvenient because it leaves logs as the only way of debugging; normally, I can go inside the build directory of a failing component and attempt to tweak the commands, re-run configure with different options, etc. Having to start each build from scratch would increase the round-trip time for checking each minor tweak from 10s to 1h :(

**Comment by stilor** [comment]
I think it boils down to a very straightforward condition: if there are macOS X users of crosstool-NG, one of them should step up a a co-maintainer - and debug/post fixes for macOS-specific issues. Until then, sorry, I don't have spare time to waste on jumping through the hoops with my feet tied, figuratively speaking.

**Comment by troian** [comment]
Well, I can try to contribute with one minor note. I'm not autoconf fun thus if it's suitable for you to help sometimes over it's issue picks

**Comment by stilor** [comment]
Thanks for the offer. Re autoconf - I think crosstool-NG itself currently builds on macOS, and even when it doesn't - it is an easy thing to debug. Unfortunately, about half of the issues I've seen in the past on macOS were in some component (gcc/glibc/binutils/...) detecting something incorrectly during configure, so the "fixing the issues" part often involves digging into the configure scripts.

Other than that, even a status of `ct-ng build-all` on macOS and, in case of any failures, bisection, would help. I am going to tag 1.24.0-rc2 tonight, so you might want to use that as a starting point (-rc1 had some samples broken).
