### ISSUE TITLE
"Put the license information" fails

### ISSUE THREAD

**Issue by roolebo** [crosstool-ng/crosstool-ng#1091]
I'm having an issue related to #1084:
```
[INFO ]  Restoring state at step 'finish', as requested.
[INFO ]  =================================================================
[INFO ]  Finalizing the toolchain's directory
[INFO ]    Stripping all toolchain executables
[EXTRA]    Installing the populate helper
[EXTRA]    Installing a cross-ldd helper
[EXTRA]    Creating toolchain aliases
[EXTRA]    Removing installed documentation
[EXTRA]    Collect license information from: /Volumes/ldev/powerpc64le-unknown-linux-gnu-build/.build/powerpc64le-unknown-linux-gnu/src
[EXTRA]    Put the license information to: /Volumes/ldev/x-tools/powerpc64le-unknown-linux-gnu/share/licenses
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Finalizing the toolchain's directory'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@374]
[ERROR]  >>        called from: CT_InstallCopyingInformation[scripts/functions@2428]
[ERROR]  >>        called from: do_finish[scripts/build/internals.sh@148]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@688]


Current command:
   'cp' '-av' '/Volumes/ldev/powerpc64le-unknown-linux-gnu-build/licenses.d' '/Volumes/ldev/x-tools/powerpc64le-unknown-linux-gnu/share/licenses/crosstool-ng/'
exited with error code: 1
Please fix it up and finish by exiting the shell with one of these values:
    1  fixed, continue with next build command
    2  repeat this build command
    3  abort build

ct-ng:/Volumes/ldev/powerpc64le-unknown-linux-gnu-build> echo $CT_PREFIX_DIR

ct-ng:/Volumes/ldev/powerpc64le-unknown-linux-gnu-build> echo $CT_TOP_DIR
/Volumes/ldev/powerpc64le-unknown-linux-gnu-build

ct-ng:/Volumes/ldev/powerpc64le-unknown-linux-gnu-build> echo $CT_PREFIX
/Volumes/ldev/x-tools

ct-ng:/Volumes/ldev/powerpc64le-unknown-linux-gnu-build> exit 3
exit
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 97:17.00)
[02:30] / gmake[1]: *** [/usr/local/bin/ct-ng:235: build] Error 1
gmake: *** [/usr/local/bin/ct-ng:287: finish] Error 2
```
I'm running `ct-ng build` with `CT_PREFIX` set to a directory on case sensitive filesystem: `/Volumes/ldev/x-tools`. `.config` is `powerpc64le-unknown-linux-gnu` plus ct-ng debugging.

`CT_TOP_DIR` contains path to the directory where I have `.config` and where I start `ct-ng build`. So I'm not sure if https://github.com/crosstool-ng/crosstool-ng/pull/1084/commits/aec70d53102fcd5f468dc8439a25010254166c22#diff-f4677383f012769a82f4885f7d508cb6R2422 should work at all. Also, the files in `licenses.d` are not added to `Automake.am`.

- [x] crosstool-NG version:
1.23.0.523-61687
- [x] host OS and its version
Darwin Kernel Version 18.2.0
- [x] [.config](https://github.com/crosstool-ng/crosstool-ng/files/2566721/config.txt)
- [x] [build.log.xz](https://github.com/crosstool-ng/crosstool-ng/files/2566728/build.log.xz.txt)

**Comment by stilor** [comment]
Reproduced. Will fix later tonight.

**Comment by patrickdepinguin** [comment]
I think there is still an issue related to this: when making a release with maintainer/create-release.sh, the LICENSE file does not appear to be part of the release. So when the license copying does the following:

```
    # Also add crosstool's information
    for licfile in ${CT_LIB_DIR}/{COPYING*,LICENSE*,licenses.d}; do
        dstdir="${CT_PREFIX_DIR}/share/licenses/crosstool-ng"
        mkdir -p "${dstdir}"
        CT_DoExecLog ALL cp -av "${licfile}" "${dstdir}/"
    done
```
the 'LICENSE*' glob will enter the loop verbatim, causing a failure at the cp step ('LICENSE*' does not exist).
Adding following line inside the for loop solves the problem, but maybe you rather intend the LICENSE file to be part of the release.
```
        [ -e "$licfile" ] || continue
```

**Comment by stilor** [comment]
Reopening to verify later.

**Comment by stilor** [comment]
What did you do with the tarball produced by maintainer/create-release.sh? Did you run `./configure --enable-local && make`, or did you install it into some location (i.e. `./configure && make && make install`)? The latter should work (it creates LICENSE symlink as part of `make install`); but the former may indeed fail.

**Comment by patrickdepinguin** [comment]
I indeed am using --enable-local.
