### ISSUE TITLE
Problem building ct-ng with soft floating point

### ISSUE THREAD

**Issue by MarcinOrlowski** [crosstool-ng/crosstool-ng#1107]
I am trying to build ct-ng for PPC. I downloaded recent `v1.23.0.543-951afda` from GitHub, tweaked config slightly (config file attached) with soft Floating Point math. But I am unable to complete the building as it fails during linking with tons of similar looking messages like:

```
[PATH]/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/../../../../powerpc-unknown-linux-gnu/bin/ld: [PATH]/config/.build/powerpc-unknown-linux-gnu/src/gcc/libgcc/config/rs6000/ibm-ldouble.c:301: 
      undefined reference to `__gedf2'
[PATH]/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/../../../../powerpc-unknown-linux-gnu/bin/ld: [PATH]/config/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/libgcc.a(ibm-ldouble.o): 
      in function `__gcc_stoq':
[PATH]/.build/powerpc-unknown-linux-gnu/src/gcc/libgcc/config/rs6000/ibm-ldouble.c:310: 
      undefined reference to `__extendsfdf2'
[PATH]/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/../../../../powerpc-unknown-linux-gnu/bin/ld: [PATH]/config/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/libgcc.a(ibm-ldouble.o): 
      in function `__gcc_qtos':
[PATH]/.build/powerpc-unknown-linux-gnu/src/gcc/libgcc/config/rs6000/ibm-ldouble.c:324: 
      undefined reference to `__truncdfsf2'
[PATH]/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/../../../../powerpc-unknown-linux-gnu/bin/ld: [PATH]/config/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/libgcc.a(ibm-ldouble.o):
       in function `__gcc_qtoi':
[PATH]/.build/powerpc-unknown-linux-gnu/src/gcc/libgcc/config/rs6000/ibm-ldouble.c:338: 
      undefined reference to `__adddf3'
[PATH]/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/../../../../powerpc-unknown-linux-gnu/bin/ld: [PATH]/config/.build/powerpc-unknown-linux-gnu/src/gcc/libgcc/config/rs6000/ibm-ldouble.c:339: 
      undefined reference to `__fixdfsi'
[PATH]/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/../../../../powerpc-unknown-linux-gnu/bin/ld: [PATH]/config/.build/powerpc-unknown-linux-gnu/buildtools/lib/gcc/powerpc-unknown-linux-gnu/8.2.0/libgcc.a(ibm-ldouble.o): 
      in function `__gcc_qtou':
[PATH]/.build/powerpc-unknown-linux-gnu/src/gcc/libgcc/config/rs6000/ibm-ldouble.c:346: 
      undefined reference to `__adddf3'
```
I inspected `build.log` (attached) trying to get some hints -> is this message (`uses hard float` vs `uses soft float`) related:
```
...powerpc-unknown-linux-gnu/bin/ld: .../.build/powerpc-unknown-linux-gnu/build/
build-libc-final/multilib/libc_pic.os uses hard float, ...unknown-linux-gnu/8.2.0/
libgcc.a(ibm-ldouble.o) uses soft float
```

Appreciate any hints or feedback.

Attachements:
 * [config.zip](https://github.com/crosstool-ng/crosstool-ng/files/2646347/config.zip)
 * [build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/2646346/build.log.zip)

**Comment by stilor** [comment]
Actually, there's a third issue: glibc-2.23 detects that `-fstack-protector-strong` is supported and tries to enable it in certain parts of the build - e.g. in libresolv.so - which then fails to build. This has been reported on glibc mailing list, so this is not an issue in crosstool-NG. It hasn't been fixed until glibc-2.25 and the patch is too expansive to backport.

I'll try to make older glibc's ignore compiler's support for `-fstack-protector` and friends and see if it helps instead. I then plan the fixes for non-multilib CFLAGS passing and for glibc's abuse of `-fstack-protector` to go into 1.24 (hence, tagged this issue). The other issue (which precludes building a multilib version of you configuration) will probably have to wait until after 1.24. I am fairly sure it is an issue in GCC, but will need to confirm that.
