### ISSUE TITLE
ar fails to automatically find LTO plugin

### ISSUE THREAD

**Issue by deece** [crosstool-ng/crosstool-ng#1113]
# Description
When attempting to link LTO enabled objects into a library, ar cannot automatically find the LTO plugin.
```
$ $HOME/src/1wire/toolchain/x-tool/arm-none-eabi/bin/arm-none-eabi-ar -r  "libOneWireSlave.a" @"objects.list"
/home/adsilva/src/1wire/toolchain/x-tool/arm-none-eabi/bin/arm-none-eabi-ar: DS2408.o: plugin needed to handle lto object
/home/adsilva/src/1wire/toolchain/x-tool/arm-none-eabi/bin/arm-none-eabi-ar: FirmwareUpdater.o: plugin needed to handle lto object
/home/adsilva/src/1wire/toolchain/x-tool/arm-none-eabi/bin/arm-none-eabi-ar: OneWireSlave.o: plugin needed to handle lto object
/home/adsilva/src/1wire/toolchain/x-tool/arm-none-eabi/bin/arm-none-eabi-ar: RGBWController.o: plugin needed to handle lto object
/home/adsilva/src/1wire/toolchain/x-tool/arm-none-eabi/bin/arm-none-eabi-ar: SoftDevice.o: plugin needed to handle lto object
```

Manually specifying the path to the plugin works:
```
$ arm-none-eabi-ar -r --plugin=$HOME/src/1wire/toolchain/x-tool/arm-none-eabi/libexec/gcc/arm-none-eabi/8.2.0/liblto_plugin.so "libOneWireSlave.a" @"objects.list"
```

# Report info
crosstool-ng commit 951afda5088f202eead14e3ae281f234b160af0b
crosstool-NG version 1.23.0.543-951afda
Host is Linux (Fedora 29)

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/2661753/config.txt)
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/2661755/build.zip)

**Comment by stilor** [comment]
It should work if you use `arm-none-eabi-gcc-ar` instead (it automatically adds the required `--plugin` stanza). But the fix for direct invocation of `ar` seems simple enough, just a symlink back to liblto_plugin.so from a bfd-plugins directory. I'll add it.

**Comment by deece** [comment]
@stilor Thankyou for the quick response :)

**Comment by stilor** [comment]
I still want to add that symlink; reopening :)
