### ISSUE TITLE
Trying to Build sample: aarch64-unknown-linux-android: Internal ct-ng error: 'BIONIC' not defined, please report a bug

### ISSUE THREAD

**Issue by Eliminater74** [crosstool-ng/crosstool-ng#1116]
INFO ]  Retrieving needed toolchain components' tarballs
[WARN ]    Ambiguous ref master at git://sourceware.org/git/binutils-gdb.git, using best match (refs/heads/master)
[EXTRA]    Retrieving 'binutils-git-0a59decb'
[EXTRA]    Checking out 'binutils-git-0a59decb' (git git://sourceware.org/git/binutils-gdb.git)
[ERROR]    Internal ct-ng error: 'BIONIC' not defined, please report a bug
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@485]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2015]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2128]
[ERROR]  >>        called from: bionic_get[scripts/build/libc.sh@7]
[ERROR]  >>        called from: do_libc_get[scripts/build/libc.sh@18]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@637]

building sample: aarch64-unknown-linux-gnu <-- works
but building sample: aarch64-unknown-linux-android <-- errors out with the above mentioned.

Also using Master branch,  1.22 gave me:

In file included from zconf.tab.c:218:
zconf.hash.c:167:1: error: conflicting types for 'kconf_id_lookup'
 kconf_id_lookup (register const char *str, register size_t len)
 ^~~~~~~~~~~~~~~
zconf.hash.c:34:31: note: previous declaration of 'kconf_id_lookup' was here
 static const struct kconf_id *kconf_id_lookup(register const char *str, register unsigned int len);
                               ^~~~~~~~~~~~~~~
make[2]: *** [Makefile:89: zconf.tab.o] Error 1
make[1]: *** [Makefile:167: build-lib-kconfig] Error 2
make: *** [Makefile:127: build] Error 2

When trying to build it.

**Comment by stilor** [comment]
Thanks, reproduced.
