### ISSUE TITLE
make tries to compile ct-ng for ARM on an x86_64 machine

### ISSUE THREAD

**Issue by ParzivalWolfram** [crosstool-ng/crosstool-ng#1118]
- Report crosstool-NG version: N/A (build fails)
- Report host OS and its version: uname -a output: `Linux keter-collecter 4.19.6-200.fc28.x86_64 #1 SMP Sun Dec 2 18:03:32 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
- Attach `.config` (unless the issue is not related to any configuration): N/A (build fails)
- Attach `build.log` (unless crosstool-NG fails before the build starts): N/A (we're building crosstool-ng, not a toolchain)

bootstrap runs fine, configure runs fine, but make outputs the following:
```
bash-4.4# make
/usr/bin/gmake  all-recursive
gmake[1]: Entering directory '/home/parzival/crosstool-ng'
Making all in kconfig
gmake[2]: Entering directory '/home/parzival/crosstool-ng/kconfig'
bison -y -l -b zconf -p zconf  -ozconf.c zconf.y
bison: /opt/armv6-eabihf--glibc--bleeding-edge-2018.02-1/share/bison/m4sugar/m4sugar.m4: cannot open: No such file or directory
gmake[2]: *** [Makefile:845: zconf.c] Error 1
gmake[2]: Leaving directory '/home/parzival/crosstool-ng/kconfig'
gmake[1]: *** [Makefile:2769: all-recursive] Error 1
gmake[1]: Leaving directory '/home/parzival/crosstool-ng'
make: *** [Makefile:2516: all] Error 2
```
Not entirely sure what the hell it's doing, since we're building crosstool-ng on an x86_64 machine and it's to run on the same machine. No other info can be provided as no other info is given by make.

**Comment by stilor** [comment]
Your $PATH seems to point to some /opt directory - apparently, it invokes bison from /opt/armv6-eabihf-whatever. But even then I have no idea why bison would try to read m4sugar.m4; it is certainly not included from zconf.y.

Would be nice if you listed your Linux distribution rather than the host name, and for issues like this, config.log might be helpful. But ultimately, something is really screwed in your environment.

**Comment by ParzivalWolfram** [comment]
My env being boned is not surprising, as even stock Fedora 28 packages have
been self-calling, broken, etc. in their freshly-yum/dnf-installed state,
but everything always breaks every time for me when doing build-from-source
things (even when I don't change anything and the source is "stable") so
driving devs insane is sadly something I do often.

**Comment by ParzivalWolfram** [comment]
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/2695981/config.log)

Here's this by the way.

**Comment by ParzivalWolfram** [comment]
Yup. Me not having bison is what broke it. It's just my stupidity.

Closed.
