### ISSUE TITLE
Add toolchain-ng version string to saved config file

### ISSUE THREAD

**Issue by MarcinOrlowski** [crosstool-ng/crosstool-ng#1120]
It would be extremely useful to have crosstool-ng version string added to saved `.config` file, i.e. in file preamble, as comment.

**Comment by stilor** [comment]
It already does. E.g., on master:
```
#
# Automatically generated file; DO NOT EDIT.
# crosstool-NG 1.23.0.580-eb72b4e Configuration
#
```
