### ISSUE TITLE
New configuration is not used when starting build from a specific step

### ISSUE THREAD

**Issue by claudiusaiz** [crosstool-ng/crosstool-ng#1125]
When modifying the configuration, then restarting the build from a specific step that is affected by that configuration, the new configuration is not taken into account.
This can be reproduced on any config, but for simplicity I'll use a sample one:

```
$ ct-ng x86_64-unknown-linux-gnu
$ ct-ng menuconfig
--> enable "Paths and misc options -> Debug crosstool-NG -> Save intermediate steps"
$ ct-ng build
$ ct-ng menuconfig
--> add some compile flags: "C compiler -> Core gcc extra config -> CFLAGS="-fno-sync-libcalls"
$ ct-ng cc_core_pass_1+
```
Looking at build.log, I can see that the new flags are not taken into consideration.

Versions:
```
$ ct-ng version
This is crosstool-NG version 1.23.0.577-de48268
$ cat /etc/issue 
Arch Linux \r (\l)
$ uname -srvmo
Linux 4.19.4-arch1-1-ARCH #1 SMP PREEMPT Fri Nov 23 09:06:58 UTC 2018 x86_64 GNU/Linux
```

**Comment by stilor** [comment]
First, when I followed your example, ct-ng erred out:
```
[ERROR]  The configuration file has changed between two runs
```
Second, as you may have concluded from the above message, you are not expected to change the configuration file in the middle of the build. ct-ng computes some internal data from the configuration that is not going to be re-evaluated when you change .config.
