### ISSUE TITLE
Build fails on Alpine 3.8 - libintl not linked

### ISSUE THREAD

**Issue by tomkcook** [crosstool-ng/crosstool-ng#1132]
I'm building the `HEAD` version of crosstool-ng in an Alpine 3.8 docker container on Ubuntu 18.04.  The dockerfile is attached.  The build fails with undefined references to `libintl_gettext`.  This can be worked around by running `configure` as `LIBS=-lintl ./configure --prefix=/usr` (the prefix is not relevant).

To reproduce on Ubuntu 18.04 with docker-ce installed:

* Place the attached dockerfile in <dir>
* `cd <dir>`
* `docker build -f Dockerfile.txt -t my_crosstool_container .`

[Dockerfile.txt](https://github.com/crosstool-ng/crosstool-ng/files/2831969/Dockerfile.txt)

**Comment by stilor** [comment]
Should be fixed by the just-merged #1133, can you check?

**Comment by stilor** [comment]
Builds with in alpine:3.8 docker image.
