### ISSUE TITLE
./ct-ng build error, fails installing ncurses [MACOS sierra]

### ISSUE THREAD

**Issue by gundam132** [crosstool-ng/crosstool-ng#1137]
Hello, im having trouble building ct-ng. Error comes when it tries to install ncurses. OS is Mac Sierra 10.12.
 
Error says:

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2857351/build.log)
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/2857352/config.log)

[INFO ]  Installing ncurses for build
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[2]: *** [toe] Error 1
[ERROR]    make[2]: *** [tabs] Error 1
[ERROR]    make[2]: *** [clear] Error 1
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing ncurses for build'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@216]
[ERROR]  >>        called from: do_ncurses_backend[scripts/build/companion_libs/220-ncurses.sh@151]
[ERROR]  >>        called from: do_ncurses_for_build[scripts/build/companion_libs/220-ncurses.sh@35]
[ERROR]  >>        called from: do_companion_libs_for_build[scripts/build/companion_libs.sh@29]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 1:02.00)
[01:02] / make: *** [build] Error 1

**Comment by stilor** [comment]
http://crosstool-ng.github.io/2018/11/26/macos.html
