### ISSUE TITLE
default doc example doesn't work properly

### ISSUE THREAD

**Issue by rojaster** [crosstool-ng/crosstool-ng#1149]
- Report crosstool-NG version : This is crosstool-NG version **crosstool-ng-1.23.0**
- Report host OS and its version: **Ubuntu 18.04.1 LTS**
- Attach `.config` (unless the issue is not related to any configuration): [config.log](https://github.com/crosstool-ng/crosstool-ng/files/2901753/config.log)
- Attach `build.log` (unless crosstool-NG fails before the build starts): [build.log](https://github.com/crosstool-ng/crosstool-ng/files/2901743/build.log)

I went through basic steps in the documentation and got some error related to the unreachable host

:

```
 --2019-02-25 17:20:50--  http://www.mr511.de/software//libelf-0.8.13
[ALL  ]    Resolving www.mr511.de (www.mr511.de)... 80.67.16.8, 2a00:1158:0:100::14
[ALL  ]    Connecting to www.mr511.de (www.mr511.de)|80.67.16.8|:80... connected.
[ALL  ]    HTTP request sent, awaiting response... 302 Found
[ALL  ]    Location: http://leere.seite/software//libelf-0.8.13 [following]
[ALL  ]    --2019-02-25 17:20:50--  http://leere.seite/software//libelf-0.8.13
[ALL  ]    Resolving leere.seite (leere.seite)... failed: Name or service not known.
[ALL  ]    wget: unable to resolve host address 'leere.seite'
```

**Comment by stilor** [comment]
Not a problem with crosstool-NG: the maintainer(s) of libelf need to fix their downloads which seem unaccessible at this moment.

**Comment by surinoel** [comment]
I have a same problem now. By any chance, Has the site server problem been resolved?
