### ISSUE TITLE
Question about GCC 8.3 and PowerPC SPE

### ISSUE THREAD

**Issue by Floessie** [crosstool-ng/crosstool-ng#1152]
Hi Alexey,

Now that 8.3 is out and supported by CTNG I've built a toolchain for `powerpc-e500v2-linux-gnuspe` which went very well. Now when cross-building the kernel it fails with:

```
powerpc-e500v2-linux-gnuspe-gcc: error: unrecognized argument in option '-mcpu=powerpc'
powerpc-e500v2-linux-gnuspe-gcc: note: valid arguments to '-mcpu=' are: 8540 8548 native
```

This seems a bit odd, as the [documentation](https://gcc.gnu.org/onlinedocs/gcc/RS_002f6000-and-PowerPC-Options.html) still states `powerpc` as a valid option.

The previously built 7.3 toolchain gives this:
```
powerpc-e500v2-linux-gnuspe-gcc: error: unrecognized argument in option '-mcpu=?'
powerpc-e500v2-linux-gnuspe-gcc: note: valid arguments to '-mcpu=' are: 401 403 405 405fp 440 440fp 464 464fp 476 476fp 505 601 602 603 603e 604 604e 620 630 740 7400 7450 750 801 821 823 8540 8548 860 970 G3 G4 G5 a2 cell e300c2 e300c3 e500mc e500mc64 e5500 e6500 ec603e native power3 power4 power5 power5+ power6 power6x power7 power8 power9 powerpc powerpc64 powerpc64le rs64 titan
```

Is that a fallout from the SPE obsolescence in GCC 8 (and now its removal from 9)? How can I restore the previous long list of supported CPUs?

Best,
Flössie

**Comment by bhundven** [comment]
https://gcc.gnu.org/gcc-8/changes.html

```
Support for the powerpc*-*-*spe* target ports which have been recently unmaintained and untested in GCC has been declared obsolete in GCC 8 as announced here. Unless there is activity to revive them, the next release of GCC will have their sources permanently removed.
```

**Comment by bhundven** [comment]
I'm guessing that gcc-8.3 prematurely introduced these removals.

**Comment by stilor** [comment]
No, GCC started treating "PowerPC" and "PowerPC SPE" as two different architectures some time ago. You're looking here: https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/RS_002f6000-and-PowerPC-Options.html
While you should be looking here: https://gcc.gnu.org/onlinedocs/gcc-8.3.0/gcc/PowerPC-SPE-Options.html

**Comment by stilor** [comment]
But actually, the docs for 8.3.0 say that `-mcpu=powerpc` should be a valid choice even for PowerPC-SPE architecture. It doesn't list it as a valid choice though:
```
Set architecture type, register usage, and instruction scheduling parameters for machine type cpu_type. Supported values for cpu_type are ‘8540’, ‘8548’, and ‘native’.

-mcpu=powerpc specifies pure 32-bit PowerPC (either endian), with an appropriate, generic processor model assumed for scheduling purposes.
```
I am not sure if that mention of `-mcpu=powerpc` is a cut-an-paste error when they were separating PowerPC and PowerPC-SPE, or if it was indeed intended to be accepted - but isn't. You'll have to take it to the GCC developers - but I doubt you'll see a lot of progress on any issue submitted against a dying port.

**Comment by Floessie** [comment]
Hi Bryan and Alexey,

@bhundven 
> https://gcc.gnu.org/gcc-8/changes.html

That's what I meant by "SPE obsolescence". I know that GCC 8 will likely be the last incarnation for SPE. The only one still interested in this port is John Paul Adrian Glaubitz (@glaubitz):

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81084

@stilor 
> No, GCC started treating "PowerPC" and "PowerPC SPE" as two different architectures some time ago.

Yep, that seems to be the reason for the reduced `-mcpu` list. I checked Debian's `powerpcspe` cross GCC 8.2 and it spits out exactly the same short list.

> I am not sure if that mention of -mcpu=powerpc is a cut-an-paste error when they were separating PowerPC and PowerPC-SPE, or if it was indeed intended to be accepted - but isn't. You'll have to take it to the GCC developers - but I doubt you'll see a lot of progress on any issue submitted against a dying port.

I assume it's c'n'p, too. Though it's a dying port, our hardware is still going strong. I guess we can continue using GCC 8 for a long time but there will sure be the time when we'll use C++ features it doesn't provide. If Clang hasn't picked up SPE by then (:wink:), we can still fall back to soft FPU.

> I can definitely see that the powerpc is not a valid choice in the sources - see gcc/config/powerpcspe/powerpcspe-tables.opt.

Thanks for digging so deeply into it. :+1: 

To those coming here because of a failing Linux kernel cross-compilation with GCC 8 and PowerPC SPE: Debian has a patch which solves the problem.

https://salsa.debian.org/kernel-team/linux/blob/master/debian/patches/bugfix/powerpc/powerpc-fix-mcpu-options-for-spe-only-compiler.patch

HTH,
Flössie

**Comment by glaubitz** [comment]
Just as a heads-up: There have been many improvements in LLVM regarding PowerPCSPE thanks to the work of Justin Hibbits. LLVM works so well now that even Rust can be used on PowerPCSPE.

As for gcc, Andrew Jenner is working on the PowerPCSPE backend out of tree and he is planning to bring it back once it's back in shape.

If you have more questions, we're hanging around in #debian-ports on OFTC.

**Comment by stilor** [comment]
Looks like supporting clang in crosstool-NG becomes more and more attractive. In addition to this, recent android-ndk releases dropped support for gcc.

**Comment by pali** [comment]
Linux kernel is _now_ receiving patches to not pass gcc flag `-mcpu=powerpc` when compiling for e500 cores. Instead it will pass `-mcpu=8540` together with `-mno-spe` and `-mspe=no` flags to ensure that gcc will compile kernel optimized for e500 cores but without using floating point SPE instructions.

When SPE is disabled then flags `-mcpu=8540` and `-mcpu=8548` do same thing.

gcc powerpc spe port really does not support `-mcpu=powerpc` flag and gcc 8.x powerpc spe documentation contains some wrong information.
