### ISSUE TITLE
Companion tools (specifically 'make') do not appear to be used

### ISSUE THREAD

**Issue by RyanVT** [crosstool-ng/crosstool-ng#1157]
crosstool-ng-1.24.0-rc2
Kubunu 14.04.03  3.13.0-67-generic

1) I upgraded a 1.23.0 configuration file
2) Further upgraded gcc/glibc/etc
3) Attempted build & ">>  Build failed in step 'Building for multilib 1/1: '''"
4) Inspecting build.log & saw the earlier error:  "*** These critical programs are missing or too old: make" ( installed version of make = 3.81 )
5) Went back into crosstool-ng configuration and selected companion tool 'make' as well as others.  Companion tool version of make is 4.2.1
6) Restarted build and the error persists.
7) Futher examination shows make 4.2.1 was built in a directory called 'build-make-build' and appears to have been installed into a directory 'buildtools/bin'.  So there is a 'good' version of make available, we're just using the 'wrong' one.(?).

For giggles, I pre-pended my PATH to look in .../'buildtools/bin' first, but that resulted in no joy at all.  Either the check of the make version is going directly to /usr/bin, or I mucked up the PATH modification.

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2933580/build.log)

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/2933586/config.txt)

**Comment by stilor** [comment]
As mentioned in #1135, the fix for this issue is on my branch already: https://github.com/stilor/crosstool-ng/tree/docker-fixes

It still doesn't completely support older systems (such as CentOS6) - it then breaks when trying to build the GDB, but should be ok for building the glibc.
