### ISSUE TITLE
reinstating multiple versions of the same package

### ISSUE THREAD

**Issue by artynet** [crosstool-ng/crosstool-ng#1158]
crosstool-NG version : latest trunk
host OS : ubuntu 18.04 LTS

I'd like to reinstate the use of multiple versions for a same series of a given package (i.e. binutils 2.25 and point release 2.25.1). Can you give me some pointers about the modifications to apply to the base code ?

Thanks in advance

**Comment by stilor** [comment]
Check the `relevantpattern` specification in package.desc. This determines which part of the version is considered for unique identification of the version; for binutils that patterns results in the same version string for both "2.25" and "2.25.1" inputs.

The syntax is somewhat obscure, resulting from the limitations of shell's string matching. It is a space-separated list of patterns (first one matched is applied). Each pattern consists of two parts separated by `|` (vertical bar); the version string is matched against the concatenation of both parts, before and after the bar, and the first part is the "relevant" part.

I know, regexps would've been easier. I want to eventually rewrite `boostrap` in Python to speed it up - with that, regexps would come naturally.

**Comment by artynet** [comment]
It seems that just removing the `relevantpattern` entry in every group of packages affected did the trick ! Thank you very much for your help as usual !

Best, Arturo
