### ISSUE TITLE
Already login as root in docker and "You must NOT be root to run crosstool-NG"

### ISSUE THREAD

**Issue by kuvaldini** [crosstool-ng/crosstool-ng#1160]
- crosstool-NG version **latest master**
- host: **docker run ubuntu:latest** 

```
# ct-ng build
[ERROR]  You must NOT be root to run crosstool-NG
[00:00] / /opt/cross/arm-linux-gnueabihf/bin/ct-ng:261: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by stilor** [comment]
`ct-ng` refuses to run as root for a reason. I understand you're in a docker container so you don't care much about an accidental breakage; for this usecase, there's an option that bypasses the check (under 'misc options').

**Comment by kuvaldini** [comment]
:)
Sorry I was tired and by-passsed **NOT**
