### ISSUE TITLE
libelf-0.8.13 cannot be downloaded

### ISSUE THREAD

**Issue by lewisou** [crosstool-ng/crosstool-ng#1165]
### ct-ng build failed
- crosstool-ng-1.24.0-rc2
- Ubuntu 18.04

ct-ng build failed because libelf-0.8.13 couldn't be downloaded.
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2976213/build.log)

**Comment by stilor** [comment]
Should be resolved by #1151.

However, there is not much crosstool-NG can do here: the server that is no longer in service was the *OFFICIAL* download location for that package. The other mirror has only one (latest) release.

I guess we need to check possible alternative implementations of libelf.
