### ISSUE TITLE
menuconfig not showing properly on ArchLinux

### ISSUE THREAD

**Issue by artynet** [crosstool-ng/crosstool-ng#1175]
Setup :
- Latest commit of the code trunk 
- ArchLinux x64 latest

Hello @stilor,

while using crosstools-ng on ArchLinux I experience this issue with the menuconfig selector :

![CROSSTOOLS : ct-ng — Konsole_003](https://user-images.githubusercontent.com/175003/55398006-cce35400-5547-11e9-9f63-2636d0f3d61e.jpg)

basically, all the mark boxes are disappeared ! The strange fact is that I am able to run any other menuconfig (i.e. like the kernel one) without any problem.

Can you help me out ? Thanks in advance

**Comment by stilor** [comment]
ArchLinux has a strange console color scheme that results in this issue with the kconfig. A workaround is to either use `ct-ng nconfig`, or add `export MENUCONFIG_COLOR=mono` to your profile.
