### ISSUE TITLE
Build failed in step 'Installing m4 for build'

### ISSUE THREAD

**Issue by MostafaI** [crosstool-ng/crosstool-ng#1180]
- crosstool-NG 1.24.0
- host OS Mac OS Mojave 10.14.4 , Using HomeBrew
I'm not sure If my configuration for "./ct-ng menuconfig" is correct though. Should I do anything specifically to let it use brew ?

Here is the error. 
`[ERROR]  >>  Build failed in step 'Installing m4 for build'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_m4_backend[scripts/build/companion_tools/100-m4.sh@69]
[ERROR]  >>        called from: do_companion_tools_m4_for_build[scripts/build/companion_tools/100-m4.sh@18]
[ERROR]  >>        called from: do_companion_tools_for_build[scripts/build/companion_tools.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
`

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3050928/build.log)

[config_file.txt](https://github.com/crosstool-ng/crosstool-ng/files/3050929/config_file.txt)

**Comment by stilor** [comment]
http://crosstool-ng.github.io/2018/11/26/macos.html
