### ISSUE TITLE
Build fails at "debug" something with python-config

### ISSUE THREAD

**Issue by RonnyReporter** [crosstool-ng/crosstool-ng#1181]
Building the debug section fails on something about python-config. I tried creating symlinks to python2 versions as described in the only answer [here](https://stackoverflow.com/questions/16974572/crosstool-ng-python-error). But it didn't fix it. I'm using a standard Ubuntu 18.04 installation. 

Attached build.log is from running "RESTART=debug ./ct-ng build" -- all previous steps went without a hitch.

- crosstool-NG version: Current git master
- host OS and its version: Ubuntu 18.04 server

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3063554/config.txt)
[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/3063563/build.log.gz)

**Comment by stilor** [comment]
Looks like your python installation is broken or incomplete. Note that GDB wants python3, not python2. Check that you have the `python3-dev` package installed.

**Comment by RonnyReporter** [comment]
Thank you so much. That did the trick.

I feel kind of stupid now because I did manually install python-dev 😅

> [INFO ]  Restoring state at step 'debug', as requested.
> [INFO ]  =================================================================
> [INFO ]  Installing cross-gdb
> [EXTRA]    Configuring cross gdb
> [EXTRA]    Building cross gdb
> [EXTRA]    Installing cross gdb
> [EXTRA]    Installing '.gdbinit' template
> [INFO ]  Installing cross-gdb: done in 382.54s (at 06:41)
> [INFO ]  =================================================================
> [INFO ]  Installing native gdb
