### ISSUE TITLE
Build failed in step 'Installing pass-2 core C gcc compiler'

### ISSUE THREAD

**Issue by tacticalmelonfarmer** [crosstool-ng/crosstool-ng#1187]
Host is 64bit ubuntu 18.04
Target is aarch64-unknown-elf

===================================
Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[ERROR]    make[1]: *** [configure-gcc] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-2 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@626]
[ERROR]  >>        called from: do_cc_core_pass_2[scripts/build/cc/gcc.sh@259]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 17:01.68)
[17:05] / /opt/ct-ng/bin/ct-ng:261: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by stilor** [comment]
[ERROR] >> Make sure your report includes all the information pertinent to this issue.
[ERROR] >> Read the bug reporting guidelines here:
[ERROR] >> http://crosstool-ng.github.io/support/
