### ISSUE TITLE
PPC64LE host with x86_64-unknown-linux-gnu target build fails

### ISSUE THREAD

**Issue by grubles** [crosstool-ng/crosstool-ng#1195]
- Report crosstool-NG version
1.24.0.6-afaf7b9

- Report host OS and its version
Ubuntu Bionic 18.04.2 PPC64LE
 
- Attach `.config` (unless the issue is not related to any configuration)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3192573/config.txt)

- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3192577/build.log)

**Comment by cpackham** [comment]
Looks like the same problem as #1217

**Comment by stilor** [comment]
#1233 (which fixed the issue in #1217) merged, this should be fixed as well.
