### ISSUE TITLE
Ask about LDFLAGS questions

### ISSUE THREAD

**Issue by yjd** [crosstool-ng/crosstool-ng#1207]
kernel：4.18.0-21-generic
OS：Ubuntu 18.04.2 LTS
Compile arm-unknown-linux-uclibcgnueabi with crosstool-ng-crosstool-ng-1.24.0.tar.
Configuration：
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/3290259/config.zip)

Compile parted-3.2.tar.xz source code
use
> LDFLAGS="-L/aaa/libuuid-1.0.3/install/lib -luuid" CFLAGS="-I/aaa/libuuid-1.0.3/install/include" ./configure --prefix=`pwd`/install --host=arm-linux --disable-device-mapper CC=arm-unknown-linux-uclibcgnueabi-gcc

Append parameter -luuid, it is not supported, error is reported

> checking for arm-linux-gcc... /aaa/ng/arm/.build/arm-unknown-linux-uclibcgnueabi/buildtools/bin/arm-unknown-linux-uclibcgnueabi-gcc
checking whether the C compiler works... no
configure: error: in `/aaa/parted-3.2':
configure: error: C compiler cannot create executables

Parted needs to be appended with -luuid to compile successfully.
Ubuntu comes with arm-linux-gnueabi-gcc support delivery -luuid, can be successfully compiled.
Is there any way to solve this problem, ths!

**Comment by fidomax** [comment]
You have to build libuuid from util-linux package first. https://mirrors.edge.kernel.org/pub/linux/utils/util-linux/

**Comment by yjd** [comment]
Thanks, the problem is to pass this -l parameter, specifying the uuid directory.
Directory Structure:
> .
├── include
│   └── uuid
│       └── uuid.h
└── lib
    ├── libuuid.a
    ├── libuuid.la
    ├── libuuid.so
    ├── libuuid.so.1
    ├── libuuid.so.1.0.0
    └── pkgconfig
        └── uuid.pc

4 directories, 7 files

I use libuuid-1.0.3.tar.gz
I also tested the util-linux package just now, and the generated structure is the same as libuuid-1.0.3.tar.gz. There is a uuid directory. So the same mistake.

Cannot compile with LDFLAGS="-L/aaa/libuuid-1.0.3/install/lib/ -luuid".
Use LDFLAGS="-L/aaa/libuuid-1.0.3/install/lib/" to start compiling. But it will be wrong, less -luuid.
In the end, the following error will occur and all tasks cannot be completed.

> checking whether to use NLS... no
checking for uuid_generate in -luuid... no

If I use the toolchain that comes with ubuntu: arm-linux-gnueabi-gcc-7
Support usage LDFLAGS="-L/aaa/libuuid-1.0.3/install/lib/ -luuid"
, pass -i and -l two parameters, can compile successfully.

I don't know where the problem is, crosstool-ng can't pass two parameters.

**Comment by fidomax** [comment]
Try to put libuuid into crosstool-ng generated toolchain sysroot. Put it all into sysroot/usr dir.

**Comment by yjd** [comment]
Thanks! let me try

**Comment by yjd** [comment]
test:
Debian official source cross compilation tool, Linaro Toolchain, arm-2014.05-29-arm-none-linux-gnueabi-i686-pc-linux-gnu.tar.bz2.
Use LDFLAGS="-L/aaa/libuuid-1.0.3/install/lib/ -luuid" with the -luuid parameter.
All compiled successfully.
Crosstool-ng built by myself, does not support passing -l parameters, I don't know why

**Comment by yjd** [comment]
I have time to reinstall a new Ubuntu and test it again.

**Comment by yjd** [comment]
Modify configure and comment out the -luuid checksum. Force assignment variables. Bypassing this error and successfully compiling. It is also a method.

![2019-06-20_211832](https://user-images.githubusercontent.com/6856740/59852649-d4c1d000-93a1-11e9-9129-80b88f72c55e.png)
