### ISSUE TITLE
Documentation points to non-existing file

### ISSUE THREAD

**Issue by buzzy** [crosstool-ng/crosstool-ng#1208]
Documentation here:
https://crosstool-ng.github.io/docs/internals/

States that there is a "./scripts/addToolVersion.sh" to add Linux kernel options.
I do not find it.

**Comment by cpackham** [comment]
That was moved to maintainer/patch-renumber.sh in commit 3906acc00779 which was then deleted in commit 2a1935f3a I think all of the required functionality is now in ./maintainer/manage-packages.sh.

crosstool-ng/crosstool-ng.github.io could use an update

**Comment by cpackham** [comment]
I've submitted https://github.com/crosstool-ng/crosstool-ng.github.io/pull/33

**Comment by cpackham** [comment]
Fixed in https://github.com/crosstool-ng/crosstool-ng.github.io/pull/33
