### ISSUE TITLE
crosstool-ng build issue

### ISSUE THREAD

**Issue by Shenobet** [crosstool-ng/crosstool-ng#1209]
i am new to use crosstool-ng and got stuck when i run the ./ct-ng build for building the x86_64-pc-linux-gnu. i hope some one will assist me solve the problem.

### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
       GNU Make 4.1
       Built for x86_64-pc-linux-gnu
- Report host OS and its version
       Ubuntu 16.04.5 LTS
- Attach `.config` (unless the issue is not related to any configuration)

- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by cpackham** [comment]
Hi,

Could you give a better description of the problem you are having?

Please have a read through http://crosstool-ng.github.io/docs/ particularly http://crosstool-ng.github.io/docs/install/, http://crosstool-ng.github.io/docs/configuration/ and http://crosstool-ng.github.io/docs/build/

**Comment by cpackham** [comment]
No additional info was supplied. Closing issue.
