### ISSUE TITLE
ct-ng build make missing or too old

### ISSUE THREAD

**Issue by zrtYouyou** [crosstool-ng/crosstool-ng#1210]
Hi all,

I think I have a bug on crosstool-engine 1.24.0.

What I'm trying to achieve : 
build the default toolchain for powerpc-unknown-linux-gnu on a CentOS 7 machine :
`Linux crosscompile 3.10.0-957.21.2.el7.x86_64 #1 SMP Wed Jun 5 14:26:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux`

What is happening :
`ct-gn build` command fail

After the fail, `build.log` contain the following :

> [CFG  ]      checking version of gnumake... 3.82, bad

Confirmed with my installed version of make : `/usr/bin/gmake -v` returns :

> GNU Make 3.82

But `.config` contains the following :

> CT_CONFIGURE_has_make_3_81_or_newer=y

I think there is a problem here.
I already successfully build the following toolchain : `aarch64-unknown-linux-android` and it works fine.

Feel free to ask me if there's a missing detail or if you need more information.

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3313525/build.log)
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/3313526/config.log)

**Comment by cpackham** [comment]
Your problem is actually the GNU libc version you've requested. Per https://www.sourceware.org/ml/libc-alpha/2018-08/msg00003.html GNU make 4.0 or newer is required for GNU libc 2.28 (and presumably any of the newer releases).
