### ISSUE TITLE
Is it possible to build crosstools with existing sysroot?

### ISSUE THREAD

**Issue by IKukhta** [crosstool-ng/crosstool-ng#1211]
I need to build crosstools for RHEL4 system with gcc 8.3.0. Both linux kernel version (2.4-9.1.103) and glibc version (2.3.4) is not supported in crosstool-ng.

But I think existing rhel4 sysroot could be used for building toolchain. I have an example of similar framework based on crosstool (legacy, not ng) that do exactly that.

Here is steps to build toolchain for rhel4:

* companion_tools_for_build
* companion_libs_for_build
* binutils_for_build
* companion_tools_for_host
* companion_libs_for_host
* binutils_for_host
* cc_core_pass_1
* _kernel_headers_ - **skip**
* _libc_start_files_ - **skip**
* cc_core_pass_2
* _libc_main_ - **skip**
* cc_for_build
* cc_for_host
* _libc_post_cc_ - **skip**
* companion_libs_for_target
* binutils_for_target
* debug
* test_suite
* finish

Is it somehow possible to force crosstool-ng use existing sys-root and so skip all related steps?

**Comment by stilor** [comment]
I'd note that since you skipping all the sysroot-related bootstrapping, you could just as well skip the "cc_core_pass_1"/"cc_core_pass_2" steps as well - all they do is to produce a minimally viable compiler with whatever stuff we happen to have in sysroot at the beginning of that step.

No such support exists in ct-ng, though, at this time.

**Comment by IKukhta** [comment]
I am able to build cross and cross canadian for rhel4 sysroot with slightly modified ct-ng code, may be it is possible to integrate changes into main repository, if so it would be another libc variant and baremetal kernel. 
Now my hack is destructive but you can see it here: https://github.com/IKukhta/crosstool-ng/commit/9ca5b9ebd277fcc2c6c93f9938bebd2d28da3770
