### ISSUE TITLE
PGP Key not found

### ISSUE THREAD

**Issue by ravenpride** [crosstool-ng/crosstool-ng#1212]
Hello,

in the [documentation](https://http://crosstool-ng.github.io/docs/install/#download-tarball) there are listed two PGP keys which should be used to validate a downloaded tar archive. Both PGP keys are not found when querying pgp.surfnet.nl.

Could you please have a look at it and maybe re-publish your keys?

Thank you in advance!

**Comment by stilor** [comment]
Apparently, you no longer need to put `http://` before the keyserver. This worked for me:

```
aneyman@yehat:~$ gpg --keyserver pgp.surfnet.nl --recv-keys 35B871D1 11D618A4
gpg: key 7848649B11D618A4: 6 signatures not checked due to missing keys
gpg: key 7848649B11D618A4: "Alexey Neyman <stilor@att.net>" not changed
gpg: key CAD7C8FC35B871D1: public key "Bryan Hundven <bryanhundven@gmail.com>" imported
gpg: Total number processed: 2
gpg:               imported: 1
gpg:              unchanged: 1
```

The key is obviously there: http://pgp.surfnet.nl/pks/lookup?search=0x11d618a4&fingerprint=on&op=index

I'll update the docs.

**Comment by ravenpride** [comment]
Ok, thank you for your reply!

**Comment by schnerring** [comment]
The key server has been offline for quite some time now. How can I obtain the keys?
