### ISSUE TITLE
Build failed in Ubuntu 18.04 Message: Build failed in step 'Installing binutils for host'

### ISSUE THREAD

**Issue by bjrobertshen** [crosstool-ng/crosstool-ng#1218]
crosstool-NG version: 1.24.0
host version: Linux 4.15.0-54-generic #58-Ubuntu SMP Mon Jun 24 10:55:24 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3392612/build.log)

got this error:
[INFO ]  Saving state to restart at step 'binutils_for_host'...
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    make[2]: *** [configure-ld] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@206]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@70]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 1:30.49)
[01:30] / ct-ng:261: recipe for target 'build' failed
make: *** [build] Error 2

**Comment by cpackham** [comment]
From the build.log I think the relevant error is
```
[ALL  ]    *** ld does not support target alphaev4-unknown-elf
[ALL  ]    *** see ld/configure.tgt for supported targets
```

So maybe try some of the different options for ld.

**Comment by Qitas** [comment]
same to you

**Comment by Kottoz** [comment]
In Paths and misc options, disable Render the toolchain read-only
or open .config file and comment (CT_PREFIX_DIR_RO)

**Comment by taha1998-Gitshit** [comment]
i disabled Render the tool-chain read-only and still get the same error

**Comment by CR-IdanMor** [comment]
got same problem , I've tried to disable Render the toolchain read-only , but still got same error msg. 
someone know how to sole it ? @TahaMohsenZeidy @bjrobertshen

**Comment by mavaneerden** [comment]
For anyone finding this still: I forgot to change the target architecture in the `menuconfig`.  When I changed it to my desired architecture, it worked.
