### ISSUE TITLE
configure: error: Required tool not found: libtool [SOLVED]

### ISSUE THREAD

**Issue by rypz79** [crosstool-ng/crosstool-ng#1219]
- Report crosstool-NG version: 1.24.0
- Report host OS and its version: Kubuntu 19.04 
- Attach `.config` (unless the issue is not related to any configuration): N/A
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/3418921/config.log)
- Attach `build.log` (unless crosstool-NG fails before the build starts): N/A
```
roey@HP-SpectreX360-13:~/crosstool-ng$ ./configure --enable-local
...
checking for libtool... 
checking for GNU libtool >= 2.4... no
configure: error: Required tool not found: libtool
roey@HP-SpectreX360-13:~/crosstool-ng$ sudo apt install libtool
[sudo] password for roey: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtool is already the newest version (2.4.6-10).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by rypz79** [comment]
`sudo apt install libtool-bin libtool-doc`

**Comment by hoangnm31** [comment]
thanks a lot
