### ISSUE TITLE
Compile aarch64-unknown-linux-android failed

### ISSUE THREAD

**Issue by qqjackson** [crosstool-ng/crosstool-ng#1222]
version of crosstool-NG is 1.24.0.6-afaf7b9
this version of host system is Ubuntu16.04 x86_64
When I changed the version of gcc to 4.9.4 and changed the version of ISL to 0.15,  it will have the following compilation error. The attachment contains the corresponding build.log and config file
-----------------------------------------------------------------------------------------------------------------
[ALL  ]    /home/qujianyun/x-tools/aarch64-unknown-linux-android/aarch64-unknown-linux-android/bin/ld: cannot find crti.o: ?????????
[ALL  ]    /home/qujianyun/x-tools/aarch64-unknown-linux-android/aarch64-unknown-linux-android/bin/ld: cannot find crtn.o: ?????????
[ERROR]    collect2: error: ld returned 1 exit status
[ALL  ]    Makefile:937: recipe for target 'libgcc_s.so' failed
[ERROR]    make[3]: *** [libgcc_s.so] Error 1
[ALL  ]    make[3]: Leaving directory '/home/qujianyun/ct-ng/.build/aarch64-unknown-linux-android/build/build-cc-gcc-final/aarch64-unknown-linux-android/libgcc'
[ALL  ]    Makefile:10201: recipe for target 'all-target-libgcc' failed
[ERROR]    make[2]: *** [all-target-libgcc] Error 2
[ALL  ]    make[2]: Leaving directory '/home/qujianyun/ct-ng/.build/aarch64-unknown-linux-android/build/build-cc-gcc-final'
[ALL  ]    Makefile:861: recipe for target 'all' failed
[ERROR]    make[1]: *** [all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/qujianyun/ct-ng/.build/aarch64-unknown-linux-android/build/build-cc-gcc-final'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/gcc.sh@1176]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc/gcc.sh@858]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
-------------------------------------------------------------------------------------------------------------------------
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3457338/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3457340/config.txt)

**Comment by cpackham** [comment]
We've dropped support for android/bionic so this is no-longer relevant
