### ISSUE TITLE
python support ?

### ISSUE THREAD

**Issue by jiapei100** [crosstool-ng/crosstool-ng#1235]
It looks Python is **NOT** supported by crosstool-ng yet? I've got **python-dev libpython-dev** installed **ALREADY**.

- crosstool-NG version:
should be >= crosstool-ng-1.24.0

```console
longervision-GT72-6QE% ct-ng --version
GNU Make 4.2.1
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

- host OS and its version:
```cosole
longervision-GT72-6QE% uname -a
Linux longervision-GT72-6QE 5.0.0-27-generic #28-Ubuntu SMP Tue Aug 20 19:53:07 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

- `.config`
Had **python** configured as EXPERIMENTAL

- `build.log`
```console
[CFG  ]    The following requested languages could not be built: python
[CFG  ]    Supported languages are: c,brig,c,c++,fortran,go,lto,objc,obj-c++
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/gcc.sh@1148]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc/gcc.sh@858]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
```

Anyway, looking forward to Python support.

Cheers
Pei

**Comment by mingwandroid** [comment]
> I've got python-dev libpython-dev installed

Crosstool NG prefers to build everything from source. In fact for gdb target this is essential.

> Anyway, looking forward to Python support

Without significant effort from yourself (or others interested in it) this is unlikely to happen.

**Comment by cpackham** [comment]
@jiapei100 python is an interpreted language (ok technically it's just-in-time compiled) so crosstool-NG isn't going to support it directly. Just like ct-ng is not going to support JavaScript.

It can however produce a C compiler that will let you cross-compile a python run-time/interpreter for your desired arcihtecture (this would most likely be the official CPython but mircopython is also available for embedded targets).

**Comment by bhundven** [comment]
The complicated part here is that if we supported a native compiler, I could see us supporting python, but only for that configuration.

Personally, I would suggest that we remove the experimental python support in crosstool-ng, and leave creating a "targeted gdb w/python support" up to tools like yacto, buildroot, ptxdist, etc (which for the most part, these tools allow custom external compilers like crosstool-ng)... And in that case, you'd want to be able to disable building gdb in crosstool-ng.

So either we support gdb w/python, and build python that may conflict with the distro building tools previously mentioned, or we should abandon this feature to stop the confusion.

**Comment by cpackham** [comment]
@bhundven now that gdb supports multiple architectures maybe ct-ng should concentrate on just creating a target gdbserver and let the distro worry about getting a gdb that supports talking to it. Or not support building gdb at all. Let the cross-build environment worry about that.

**Comment by bhundven** [comment]
You say it much better then I would have.

**Comment by bhundven** [comment]
... and I would go with option 2 of just leaving gdb up to the cross-build environment.

**Comment by bhundven** [comment]
I would say the same for any tool/library that we also build "for the target" that is not the (dependency of) libc or compiler

**Comment by cpackham** [comment]
The one downside of dropping gdb entirely would be users building for bare-metal. Chances are they don't need a target gdb since it needs an OS to run. But it is nice to say that crosstool-NG is the SDK for the bare-metal target. So I can still see an argument for compiling gdb (multiarch) for the host which we can enable/disable python support for if the host has the required python-dev packages.

**Comment by bhundven** [comment]
Yup, I was hoping the quotes around "for the target" would have implied that "for the host/build" would still be supported. But there I go making stupid assumptions :D

**Comment by mingwandroid** [comment]
Adding python wouldn't be that difficult, it's just work to be done IMHO.

**Comment by bhundven** [comment]
I'm on IRC, I'd like to discuss this more.

**Comment by mingwandroid** [comment]
Static linking is also possible here to avoid conflicts, modulo licensing concerns. Another way is to remove the exe.

**Comment by bhundven** [comment]
Static linking doesn't work for ArchLinux or MacOS
