### ISSUE TITLE
GDB reported as unavailable for RISC-V

### ISSUE THREAD

**Issue by TM1234** [crosstool-ng/crosstool-ng#1236]
Using:

CT-NG version 1.24.0 cloned from latest repo
Ubuntu 18.04 64 bit

If I do this:

1. Enable experimental features (because I want to target RISC-V)
2. Change target from alpha to riscv
3. Enable GDB and go into the GDB settings

it reports that there is no GDB available due to a conflicting configuration.

But if I do this:

1. Enable experimental features
2. Leave target = alpha
3. Enable GDB and go into the configuration - it shows the latest version available for alpha
4. Change target from alpha to riscv
5. Go back to the GDB configuration

it now no longer complains but shows the latest GDB version available for RISC-V and the subsequent build of the tools works fine.

If you need any more info from me about this please let me know.

Thanks

**Comment by cpackham** [comment]
When you say "it reports that there is no GDB available due to a conflicting configuration" where do you see this?

I've tried your reproduction on master and crosstool-ng-1.24.0 and don't see any errors (I killed the ct-ng build after it started because your report sounds like a config problem).

Could you give a more specific example to reproduced this (or post a .config that shows the problem).

**Comment by TM1234** [comment]
Thanks for the reply Chris and apologies for not being more specific. I see the message in the menuconfig GUI. It's late here now but tomorrow I will post more specific info including the verbatim message and config file. Thanks.

**Comment by TM1234** [comment]
Apologies for the delay in replying.
I actually could NOT reproduce the problem on my current setup but it might need a clean VM installation to do so.
And the post here on the RISC-V mailing list may be on the right track about why it happens:

https://groups.google.com/a/groups.riscv.org/d/msg/sw-dev/3qSVONuDcsA/vSYoL3MSAQAJ

I will close this issue for now and if/when I get a chance to reinvestigate then if I can reproduce it I will reopen it.

Thanks.
