### ISSUE TITLE
aarch64-linux-musl failed

### ISSUE THREAD

**Issue by x0r3d** [crosstool-ng/crosstool-ng#1241]
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3591893/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3591902/config.txt)

- ct-ng version 1.24.0.6-afaf7b9
- Debian 10 Buster

Failed on build pass-1 gcc

**Comment by cpackham** [comment]
Failing snippet is

```
[ALL  ]    This target does not support --with-tune.
[ALL  ]    Valid --with options are: abi cpu arch
[ERROR]    make[1]: *** [Makefile:3907: configure-gcc] Error 1
[ALL  ]    make[1]: Leaving directory '/home/x0r3d/ct/.build/aarch64-unknown-linux-musl/build/build-cc-gcc-core-pass-1'
```

**Comment by cpackham** [comment]
GCC 4.9.4 does not support --with-tune= for ARM. Later versions do.

If you update your config to set CT_ARCH_TUNE="" and CT_TARGET_CFLAGS="" it should work. Alternatively pick a newer GCC version.

**Comment by x0r3d** [comment]
I'm failed again, but on Arch Linux
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3612388/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3612390/config.txt)

**Comment by x0r3d** [comment]
Builded with this config
[config-true.txt](https://github.com/crosstool-ng/crosstool-ng/files/3612457/config-true.txt)
Closed.

**Comment by cpackham** [comment]
For the record (mostly because I'd written this before you got it working) the error in the config.log for musl was 

```
configure:3658: checking for suffix of object files
configure:3680:  /home/x-tool/.build/aarch64-x0r3d-linux-musl/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/home/x-tool/.build/aarch64-x0r3d-linux-musl/build/build-cc-gcc-core-pass-2/./gcc/ -B/home/x-tool/.build/aarch64-x0r3d-linux-musl/buildtools/aarch64-x0r3d-linux-musl
/bin/ -B/home/x-tool/.build/aarch64-x0r3d-linux-musl/buildtools/aarch64-x0r3d-linux-musl/lib/ -isystem /home/x-tool/.build/aarch64-x0r3d-linux-musl/buildtools/aarch64-x0r3d-linux-musl/include -isystem /home/x-tool/.build/aarch64-x0r3d-linux-musl/buildtools/aarch64-x0r3d-
linux-musl/sys-include    -c -mfpu=neon-fp-armv8 -mtune=cortex-a57.cortex-a53 -g -Os  conftest.c >&5
xgcc: error: unrecognized command line option '-mfpu=neon-fp-armv8'
configure:3684: $? = 1
```

Same as before leave `CT_TARGET_CFLAGS` unset.
