### ISSUE TITLE
Build for arm-unknown-linux-eabi failed: error: 'log2' is not a member of 'std'

### ISSUE THREAD

**Issue by allanxp4** [crosstool-ng/crosstool-ng#1249]
Crosstool-NG 1.24.0
Ubuntu 18.04 on Vargant
Build file: https://pastebin.com/uqVXcvk7
Build log: https://pastebin.com/gqsZL0jK

Both ct-ng build and ct-ng build.1 fails with the same error: 
error: 'log2' is not a member of 'std'.

Any help would be appreciated.
Thanks

**Comment by cpackham** [comment]
Your build.log is truncated. Could you attach the raw file to this issue.

I think I've reproduced the problem with your .config see [build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/3651841/build.log.gz)

My guess is that the new gdb doesn't like the old glibc (which provides libstdc++). Do you need to use that specific glibc version? If you're stuck with that you'll need to use an older gdb (or disable it).

**Comment by NiLuJe** [comment]
I usually workaround that in a pretty dirty way with a gdb patch by replacing the offending maths calls (I think there are a few others besides log2) by their plain C versions, not the ones in the std namespace.

**Comment by NiLuJe** [comment]
Now I'm no longer on mobile, the patch in question:

```diff
diff --git a/gdb/dwarf-index-write.c b/gdb/dwarf-index-write.c
index d2831461ca..03269cbefe 100644
--- a/gdb/dwarf-index-write.c
+++ b/gdb/dwarf-index-write.c
@@ -35,6 +35,7 @@
 
 #include <algorithm>
 #include <cmath>
+#include <math.h>
 #include <set>
 #include <unordered_map>
 #include <unordered_set>
@@ -705,7 +706,7 @@ public:
     gdb_assert (m_abbrev_table.empty ());
     const size_t name_count = m_name_to_value_set.size ();
     m_bucket_table.resize
-      (std::pow (2, std::ceil (std::log2 (name_count * 4 / 3))));
+      (std::pow (2, std::ceil (log2 (name_count * 4 / 3))));
     m_hash_table.reserve (name_count);
     m_name_table_string_offs.reserve (name_count);
     m_name_table_entry_offs.reserve (name_count);
```

**Comment by allanxp4** [comment]
Using 2.19 works for me now. 2.12 is what the device i'm targeting uses, but, happy to see a work around if I really needed 2.12.
