### ISSUE TITLE
Requires recent `make`

### ISSUE THREAD

**Issue by chronal-xnor** [crosstool-ng/crosstool-ng#1250]
*crosstool-NG version*: 1.24.0
*host OS*: Ubuntu 16.04, but I had configured an older `make` in order to build glibc 2.17 in a buildroot project
[crosstool-ng-config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3663900/crosstool-ng-config.txt)
[crosstool-ng-build.log](https://github.com/crosstool-ng/crosstool-ng/files/3663923/crosstool-ng-build.log)

With make 3.82 installed, which I had done in order to build glibc 2.17 elsewhere, the glibc build actually failed in `crosstool-ng` with the following (confusing) error:

```
[ALL  ]      make[2]: Entering directory `/zikomo3/crosstool-ng-build/.build/src/glibc-2.17'                                                                           
[ALL  ]      /zikomo3/crosstool-ng-build/.build/tools/bin/install -c -m 644 include/limits.h /usr/include/limits.h                                                     
[ALL  ]      /usr/bin/install: cannot remove '/usr/include/limits.h': Permission denied                                                                                
[ERROR]      make[2]: *** [/usr/include/limits.h] Error 1 
```

The problem was easily rectified by switching back to Ubuntu's stock `make` (4.1), but it took me a while to figure out what the real problem was. A check at the beginning of the build process would have made my life easier!

**Comment by bhundven** [comment]
I don't really have time right now, but https://github.com/crosstool-ng/crosstool-ng/blob/master/config/comp_tools/make.in#L3

...needs to change to:
```
## default y if !CONFIGURE_has_make_4_1_or_newer
```

**Comment by bhundven** [comment]
Ok, I guess I have time :D

**Comment by bhundven** [comment]
@cpackham Wanna review, and I'll merge after?
