### ISSUE TITLE
how to select gcc 9.2.0?

### ISSUE THREAD

**Issue by daggs1** [crosstool-ng/crosstool-ng#1252]
Greetings,

following the merge of pr #1223, I'm trying to enable gcc 9.2 for a x64 crosstool but I'm unable to find it, how can I do that?

thanks,
Dagg.

**Comment by cpackham** [comment]
I just tried the `x86_64-unknown-linux-gnu` sample and that selects gcc 9.2.0 as expected.

**Comment by daggs1** [comment]
can you paste the config here please?

**Comment by egtvedt** [comment]
@daggs1 remember to run ./bootstrap before menuconfig for new packages to be selectable.

**Comment by daggs1** [comment]
> @daggs1 remember to run ./bootstrap before menuconfig for new packages to be selectable.

yup, that what was missing. thanks!
