### ISSUE TITLE
Failed to retrieving needed toolchain components' tarballs

### ISSUE THREAD

**Issue by answerme123** [crosstool-ng/crosstool-ng#1264]
The version that I am using for crosstool-NG is 1.17.0
I am trying to set this up on Ubuntu, and perform cross compilation for a raspberry pi.

Here are the configurations I followed:

Paths and misc options
1. Try features marked as EXPERIMENTAL
2. In prefix directory indicate the directory where you want your toolchain. In this case: ${HOME}/toolchains/raspbian-toolchain-gcc-4.7.2-linux32

Target options
1. Target architecture: arm
2. Endianness: Little endian
3. Bitness: 32-bit
4. Floating point: hardware (FPU)

Toolchain options
1. Build static toolchain (Experimental)
2. Toolchain bug url: http://community.rti.com
3. Tuple's vendor string: raspbian
4. Tuple's alias: arm-linux-gnueabihf

Operating system
1. Target OS: Linux
2. You can also select the kernel version you run in your target. In this case, use 2.6.32.60.

C compiler
1. C compiler: gcc
2. gcc version: 4.7.2
3. In additional supported languages add C++

The problem I have is, ftp.kernel.org is terminated, so I can't download tarballs, therefore I tried to forbid download in menuconfig, and manually downloaded it to put it in home/src. But I am still getting the below message in the log file. Does anyone know how to fix this?
[INFO ]  Retrieving needed toolchain components' tarballs
[DEBUG]    Trying to retrieve an already downloaded copy of 'linux-2.6.32.60'
[DEBUG]    Trying '~/src/linux-2.6.32.60.tar.xz'
[DEBUG]    Trying '~/src/linux-2.6.32.60.tar.lzma'
[DEBUG]    Trying '~/src/linux-2.6.32.60.tar.bz2'
[DEBUG]    Trying '~/src/linux-2.6.32.60.tar.gz'
[DEBUG]    Trying '~/src/linux-2.6.32.60.tgz'
[DEBUG]    Trying '~/src/linux-2.6.32.60.tar'
[DEBUG]    Trying '~/src/linux-2.6.32.60'
[DEBUG]    Not allowed to download from the Internet, aborting linux-2.6.32.60 download
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_kernel_get[scripts/build/kernel/linux.sh@53]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@539]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/zhaojie/rticonnext/build_tools/crosstool-ng-1.17/share/doc/crosstool-ng/ct-ng.1.17.0/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 0:00.91)

If I disable forbid download, then this will show up:
linux-2.6.32.60.tmp-dl' 'http://ftp.kernel.org/pub/linux/kernel/v2.6/longterm/linux-2.6.32.60' 
[ALL  ]    --2019-10-17 11:56:36--  http://ftp.kernel.org/pub/linux/kernel/v2.6/longterm/linux-2.6.32.60
[ALL  ]    Resolving ftp.kernel.org (ftp.kernel.org)... failed: Name or service not known.
[ALL  ]    wget: unable to resolve host address 'ftp.kernel.org'
[DEBUG]    Not at this location: "http://ftp.kernel.org/pub/linux/kernel/v2.6/longterm/linux-2.6.32.60"
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_kernel_get[scripts/build/kernel/linux.sh@53]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@539]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/zhaojie/rticonnext/build_tools/crosstool-ng-1.17/share/doc/crosstool-ng/ct-ng.1.17.0/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 0:01.17)

Please leave a message if you have conquered this issue before. Thanks

**Comment by cpackham** [comment]
sorry crosstool-NG 1.17 is way to old. If you're having problems with 1.24 or the tip of master we'll look into it, otherwise I'm afraid you are on your own.

**Comment by YanhuiJessica** [comment]
ftp://ftp.kernel.org/ service is terminated on March 1, 2017
[Shutting down FTP services](https://www.kernel.org/shutting-down-ftp-services.html)
