### ISSUE TITLE
Update kconfig version

### ISSUE THREAD

**Issue by enunes** [crosstool-ng/crosstool-ng#127]
Update the kconfig version included in crosstool-ng.
From the commit logs apparently the last big update in the kconfig used by crosstool-ng was in 2011.

This is clearly just an enhancement because the current version works just fine.
The feature which I miss in the kconfig included in crosstool-ng is the option to jump to the config options when searching using 'menuconfig'.
It allows you to search for an option and then press 1-9 to jump to the menu containing that option, instead of having to look at the option location and then manually browse to the option after closing the search.
This was apparently added to the linux kernel in the major version v3.7.

It seems that a good reference is the kconfig management which is done by buildroot. In buildroot, the search feature is already present. From what I understood, buildroot keeps kconfig patches separately to allow easier tracking of the upstream kernel kconfig.

I gave it an initial look to check if it would be trivial to fix this and send a pull request, but apparently there are patches in the crosstool-ng kconfig so this probably must be done with some care.
I may eventually get back to this if noone else wants to, meanwhile I'll just keep it tracked here in case anyone else feels like picking this up.

**Comment by bhundven** [comment]
I had made a patch to update kconfig, and its sitting in patchwork. I need to update the patch and commit it.

**Comment by enunes** [comment]
@bhundven I see that kconfig to was updated to sync with 4.2 in pull request #161 , I think that this issue can be closed now? Thanks!

**Comment by bhundven** [comment]
@enunes Yup! Sorry it took me so long to get this done. So many things going on. :)
