### ISSUE TITLE
Canadian build of avr-gcc 9.2.0 on Ubuntu for Windows host fails in building gettext for host

### ISSUE THREAD

**Issue by majenkotech** [crosstool-ng/crosstool-ng#1272]
Building AVR-GCC 9.2.0 on a 64-bit Ubuntu machine to run on a Windows 64-bit machine (x86_64-w64-mingw32) fails while compiling gettext for the host.

```
[ERROR]    /extra/x-tools/build/HOST-x86_64-w64-mingw32/avr/src/gettext/gettext-tools/gnulib-tests/pthread_sigmask.c:34:1: error: expected identifier or '(' before numeric constant
[ERROR]    make[7]: *** [Makefile:5284: pthread_sigmask.o] Error 1
[ERROR]    make[7]: *** Waiting for unfinished jobs....
[ERROR]    make[6]: *** [Makefile:5320: all-recursive] Error 1
[ERROR]    make[5]: *** [Makefile:4044: all] Error 2
[ERROR]    make[4]: *** [Makefile:2173: all-recursive] Error 1
[ERROR]    make[3]: *** [Makefile:2041: all] Error 2
[ERROR]    make[2]: *** [Makefile:403: all-recursive] Error 1
[ERROR]    make[1]: *** [Makefile:359: all] Error 2
```
* CT-NG version: 1.24.0.37-3f461da
* Host OS: Ubuntu 19.04 "Disco"

* [build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/3780520/build.log.gz)
* [config.gz](https://github.com/crosstool-ng/crosstool-ng/files/3780519/config.gz)

**Comment by lhaley42** [comment]
I was able to correct this by editing the **pthread_sigmask.c** source, and then rerunning the **ct-ng build** step.  see attached files

[pthread_sigmask.c_old.txt](https://github.com/crosstool-ng/crosstool-ng/files/4032677/pthread_sigmask.c_old.txt)
[pthread_sigmask.c_new.txt](https://github.com/crosstool-ng/crosstool-ng/files/4032678/pthread_sigmask.c_new.txt)

 - it is just the movement of a #undef line.

diff pthread_sigmask.c_old pthread_sigmask.c_new
32a33
> #undef pthread_sigmask
35d35
< #undef pthread_sigmask

**Comment by Andykaban** [comment]
https://github.com/crosstool-ng/crosstool-ng/pull/1298
