### ISSUE TITLE
Build failed with Old Glibc (2.17) and new Binutils (2.32)

### ISSUE THREAD

**Issue by arpitjindal** [crosstool-ng/crosstool-ng#1278]
Hello

I'm getting build errors when I try to build the cross compiler with glibc-2.17 and binutils 2.32. I am getting `/tmp/ccaxN8sT.s: Error: '_obstack@GLIBC_2.2.5' can't be versioned to common symbol '_obstack_compat'` error. I did a quick google and it turns out that because of this [commit](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;h=a3aea05a66ec325ddd19b0c8dbe504958a295cd3) which was merged in binutils 2.29 is causing the problem. I couldn't found any information if it has been fixed or not. But maybe my search is wrong. 
I also found out this issue #1237 and it made me think if a patch is already being  provided and I'm doing something worng.

Following are the build config and attached logfile.

- crosstool-NG version: 1.24
- host OS and its version: Debian Bullseye 5.2.17-1
- [.config](https://www.dropbox.com/s/vpxtc9km99eoozy/.config?dl=0)
- [build.log](https://www.dropbox.com/s/33bqsijjr7t95t8/build.log?dl=0)

Thanks :)

**Comment by cpackham** [comment]
Hi,

Unfortunately dropbox doesn't want to show your attachments without signing your life away. Could you attach them directly to this issue (note you'll have to rename .config to config.txt to keep github happy).

**Comment by cpackham** [comment]
Also any particular reason for that combination of old glbc and new binutils?

**Comment by arpitjindal** [comment]
Hi @cpackham ,

You could download the file(s) without signing-in. But I would also attach it here. 
I can't use newer glibc than 2.17 as there are ABI change from 2.18. 
I haven't looked into the changelog of binutils. At the moment, I'm assuming there might be some bug fixes which could be beneficial. And I also want to see if I could build static toolchain with the newer binutils (using gold linker).

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/3949812/config.txt)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/3949813/build.log)

**Comment by arpitjindal** [comment]
Just tried with the newer version of binutils 2.34 and it seems to be no longer problem. I could build it again.
