### ISSUE TITLE
WSL debian-buster configure fails on whether stat takes GNU or BDS format... unknown

### ISSUE THREAD

**Issue by bbulkow** [crosstool-ng/crosstool-ng#1285]
Following the linux instructions for building at https://docs.espressif.com/projects/esp-idf/en/latest/get-started/linux-setup-scratch.html

did this clone on 12/21/19, and am doing a checkout of the esp-2019r2 branch, which should tell you the version correctly. Not sure how to get a version otherwise, since the configure 

git clone https://github.com/espressif/crosstool-NG.git
cd crosstool-NG
git checkout esp-2019r2
git submodule update --init
./bootstrap && ./configure --enable-local && make

Bootstrap succeeded, ./configure --enable-local did not.
Error is ....
checking for curl... curl                                                                             checking for stat... stat                                                                             checking whether stat takes GNU or BSD format... unknown                                              configure: error: cannot determine stat(1) format option      

Since configure did not succeed, so I am including config.log
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/3991682/config.log)

Host OS: WSL ( windows services for Linux ) , running Debian Buster ( 18.06 ) apt . This is running on a very recent version of Windows 10 ( slow ring )

Stat version:
crosstool-NG$ stat --version
stat (GNU coreutils) 8.28
Copyright (C) 2017 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Written by Michael Meskes.

**Comment by bbulkow** [comment]
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/3991684/config.log)

**Comment by cpackham** [comment]
Could you try the same on the master branch of
crosstool-ng/crosstool-ng.git there were a couple of changes that probably
haven't made it into expressif's fork.

**Comment by cpackham** [comment]
Also forgot to ask what file system you were using. The stat detection
relies on some features that aren't possible with FAT.

**Comment by bbulkow** [comment]
NTFS.

**Comment by bbulkow** [comment]
Yes! The issue is I'm on NTFS. When I run in the actual linux file system with WSL, it passes this check. ( With WSL, you've got different mounts. Because I want to edit my project files, I tend to do my work in NTFS so it's visible to Linux.

Is there anything you'd like regarding the 'stat' output to see if you can make it compatible? NTFS is a quite full featured file system, so expect stat to have all the things, if not necessarily in the same exact format.

**Comment by cpackham** [comment]
It should be possible to reproduce with ntfs on linux unless there's some
weird interaction with the stat syscall. Probably won't get a chance to
look at it until the new year.

You might be able to work around it with the right ac_cv_foo environment
variable.

**Comment by bbulkow** [comment]
Yeah, likely but maybe not, as you say. 

I'm working around it by simply doing the compile on a linux partition. WSL allows transparent access to mounts that are linux (probably ext4, haven't looked under that rock yet) and managed by WSL, as well as NTFS mounts which are available everywhere, so I am just building under /home where all the mounts are Linux.

By the way, the instructions were a bit unclear about python3 support. It seems that 'python' aka python2 is required, by simply trying python3 as "python" and failing. My build is going nicely now .
