### ISSUE TITLE
http://crosstool-ng.org/ is down

### ISSUE THREAD

**Issue by silme** [crosstool-ng/crosstool-ng#1299]
The [download site](http://crosstool-ng.org/download/crosstool-ng/) appears to be down.

**Comment by cpackham** [comment]
Hmm, seems to be parked. The content is available at http://crosstool-ng.github.io/ and the downloads can be grabbed from https://github.com/crosstool-ng/crosstool-ng/releases but that's not exactly convenient.

**Comment by stilor** [comment]
I am not owner of the domain, that still belongs to @yann-morin-1998 ...

**Comment by stilor** [comment]
And downloads from GitHub are "incomplete", in a sense that this is just the tagged version of the sources - it doesn't have the `configure`, `Makefile.in` and other bits pre-generated.

**Comment by cpackham** [comment]
Yann is still active on buildroot. I'll try and make contact.

**Comment by yann-morin-1998** [comment]
Domains have been renewed now, and are resolving again.
