### ISSUE TITLE
autoconf seems broken on Ubuntu18 

### ISSUE THREAD

**Issue by MarcKarasek** [crosstool-ng/crosstool-ng#1300]
From master:
When I try to run autoconf to create the ./configure it throws this error:

configure.ac:20: error: possibly undefined macro: AM_INIT_AUTOMAKE
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
configure.ac:23: error: possibly undefined macro: AM_MAINTAINER_MODE
configure.ac:49: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:92: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:109: error: possibly undefined macro: AC_MSG_RESULT
configure.ac:289: error: possibly undefined macro: AM_GNU_GETTEXT
configure.ac:290: error: possibly undefined macro: AM_GNU_GETTEXT_VERSION
configure.ac:344: error: possibly undefined macro: AM_COND_IF

**Comment by mkettn** [comment]
try running `./bootstrap` instead of just `autoconf`

**Comment by cpackham** [comment]
@mkettn is correct. Don't invoke `autoconf` directly use `./bootstrap` instead.
