### ISSUE TITLE
no usable python found at /usr/bin/python3

### ISSUE THREAD

**Issue by Mossop** [crosstool-ng/crosstool-ng#1308]
crosstool-NG version 1.24.0
host OS: x86_64-apple-darwin19.3.0 (OSX 10.15.3)

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/4220992/config.txt)
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/4220995/build.log.txt)

Attempting to build for `x86_64-linux-gnu`. I have built `arm-linux-gnueabihf` successfully on this host. Executing `/usr/bin/python3` seems to work fine outside of the build but for some reason it fails here. I can't find any useful output like an error message.

I've read over the OS setup page and made sure all the required packages were installed via homebrew and my source and target disks are case sensitive.

#872 suggests you need to install python header files. `python3-config --includes` lists `/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/include/python3.7m` as the include directory and that does seem to contain the headers.

**Comment by kubasejdak** [comment]
I have fixed that on my macOS by setting python (installed via Homebrew) path in `Debug facilities /gdb / Python binary to use`. Hope it helps.

**Comment by 0xFF1E071F** [comment]
> I have fixed that on my macOS by setting python (installed via Homebrew) path in `Debug facilities /gdb / Python binary to use`. Hope it helps.

can you explain more?
How did you set python path for python3?

**Comment by kubasejdak** [comment]
The highlighted part of my previous comment shows the submenu of `ct-ng menuconfig` command. It has to be called before the actual build.

**Comment by bluePain** [comment]
> The highlighted part of my previous comment shows the submenu of `ct-ng menuconfig` command. It has to be called before the actual build.

It's going to be redundant but can you please explain a bit more? Because I tried setting it to both `/usr/bin/python3` and `/usr/bin/python2` but none have worked.

**Comment by dvptr** [comment]
On macOS 11.0.1, it didn't accept /usr/bin/python3 either, bit bluePain's solution was perfect, so I was able to build it. Thank You!

**Comment by roolebo** [comment]
Here's the failed test in `config.log` of build-cross-gdb:
```
configure:10319: checking whether to use python
configure:10321: result: /usr/bin/python3
configure:10519: checking for python
configure:10537: aarch64-build_apple-darwin20.3.0-gcc -o conftest -O2 -g -pipe -I/Volumes/ldev/ct-ng-build/.build/aarch64-unknown-linux-gnu/buildtools/include -Qunused-arguments -fno-common -I/Volumes/ldev/ct-ng-build/.build/aarch64-unknown-linux-gnu/buildtools/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8 -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8  -L/Volumes/ldev/ct-ng-build/.build/aarch64-unknown-linux-gnu/buildtools/lib -framework CoreFoundation conftest.c -L/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/config-3.8-darwin -lpython3.8 -ldl -lSystem -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation Python3.framework/Versions/3.8/Python3 -lncurses -lm  >&5
clang: error: no such file or directory: 'Python3.framework/Versions/3.8/Python3'
configure:10537: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME ""
| #define PACKAGE_TARNAME ""
| #define PACKAGE_VERSION ""
| #define PACKAGE_STRING ""
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL ""
| #define STDC_HEADERS 1
| #define HAVE_SYS_TYPES_H 1
| #define HAVE_SYS_STAT_H 1
| #define HAVE_STDLIB_H 1
| #define HAVE_STRING_H 1
| #define HAVE_MEMORY_H 1
| #define HAVE_STRINGS_H 1
| #define HAVE_INTTYPES_H 1
| #define HAVE_STDINT_H 1
| #define HAVE_UNISTD_H 1
| #define __EXTENSIONS__ 1
| #define _ALL_SOURCE 1
| #define _GNU_SOURCE 1
| #define _POSIX_PTHREAD_SEMANTICS 1
| #define _TANDEM_SOURCE 1
| #define HAVE_DLFCN_H 1
| #define HAVE_CXX11 1
| #define PACKAGE "gdb"
| #define DEBUGDIR "/Volumes/ldev/x-tools/aarch64-unknown-linux-gnu/lib/debug"
| #define DEBUGDIR_RELOCATABLE 1
| #define BINDIR "/Volumes/ldev/x-tools/aarch64-unknown-linux-gnu/bin"
| #define GDB_DATADIR "/Volumes/ldev/x-tools/aarch64-unknown-linux-gnu/share/gdb"
| #define GDB_DATADIR_RELOCATABLE 1
| #define AUTO_LOAD_DIR "$debugdir:$datadir/auto-load"
| #define AUTO_LOAD_SAFE_PATH "$debugdir:$datadir/auto-load"
| #define DEFAULT_BFD_ARCH bfd_aarch64_arch
| #define DEFAULT_BFD_VEC aarch64_elf64_le_vec
| #define HAVE_MONSTARTUP 1
| #define PKGVERSION "(crosstool-NG UNKNOWN) "
| #define REPORT_BUGS_TO "<http://www.gnu.org/software/gdb/bugs/>"
| #define HAVE_LIBM 1
| #define HAVE_ICONV 1
| #define ICONV_CONST 
| #define SIZEOF_UNSIGNED_LONG_LONG 8
| #define SIZEOF_UNSIGNED_LONG 8
| #define SIZEOF_UNSIGNED___INT128 16
| #define JIT_READER_DIR "/Volumes/ldev/x-tools/aarch64-unknown-linux-gnu/lib/gdb"
| #define JIT_READER_DIR_RELOCATABLE 1
| #define HAVE_LIBEXPAT 1
| #define HAVE_XML_STOPPARSER 1
| #define HAVE_LIBMPFR 1
| /* end confdefs.h.  */
| #include "Python.h"
| int
| main ()
| {
| Py_Initialize ();
|   ;
|   return 0;
| }
configure:10547: result: no
configure:10637: error: no usable python found at /usr/bin/python3

```

**Comment by cpackham** [comment]
@roolebo one thing that sticks out `clang: error: no such file or directory: 'Python3.framework/Versions/3.8/Python3`. I think this is in your CFLAGS. I don't really do macOS stuff so not sure if there should be something there or if the case is messed up (Python3 vs python3) or something else

**Comment by Mugetsu94** [comment]
I had the same problem on openSUSE Leap 15.2 and the solve was installing python3-devel package

**Comment by cpackham** [comment]
It all boils down to the same thing. You need the required prerequisites (for crosstool-ng and the packages that it builds based on the configuration used).

Actually listing all of the prerequisites out is a little tricky. The best I can do is point you at is the setup for the github [macOS runners](https://github.com/actions/virtual-environments/blob/main/images/macos/macos-10.15-Readme.md) and the extra packages we install as part of the [CI build](https://github.com/crosstool-ng/crosstool-ng/blob/40af982ad1dd3fabdc61aa2457b5be5fff59ca02/.github/workflows/continuous-integration-workflow.yml#L110). Similar for Linux [runner](https://github.com/actions/virtual-environments/blob/main/images/linux/Ubuntu1804-README.md), [extras](https://github.com/crosstool-ng/crosstool-ng/blob/40af982ad1dd3fabdc61aa2457b5be5fff59ca02/.github/workflows/continuous-integration-workflow.yml#L105)

**Comment by roolebo** [comment]
> @roolebo one thing that sticks out `clang: error: no such file or directory: 'Python3.framework/Versions/3.8/Python3`. I think this is in your CFLAGS. I don't really do macOS stuff so not sure if there should be something there or if the case is messed up (Python3 vs python3) or something else

Yeah. I planned to help out with this one, just trying to find a bit of time to make it work out of box :) crosstool-ng 1.24 worked fine on macOS for a while. If it's possible could you please reopen the issue? (either way if I come up with a fix or someone else it could be referenced)

**Comment by cpackham** [comment]
OK re-opened.

**Comment by roolebo** [comment]
There're a few aspects of the issue. The first one is that Apple doesn't recommend to use `python3` bundled with the OS as outlined in [macOS Catalina 10.15 Release Notes](https://developer.apple.com/documentation/macos-release-notes/macos-catalina-10_15-release-notes):
> Scripting Language Runtimes
> Deprecations
>
> Scripting language runtimes such as Python, Ruby, and Perl are included in macOS for compatibility with legacy software. Future versions of macOS won’t include scripting language runtimes by default, and might require you to install additional packages. If your software depends on scripting languages, it’s recommended that you bundle the runtime within the app. (49764202)
>
> Use of Python 2.7 isn’t recommended as this version is included in macOS for compatibility with legacy software. Future versions of macOS won’t include Python 2.7. Instead, it’s recommended that you run python3 from within Terminal. (51097165)

As a consequence, homebrew formulae of `crosstool-ng` should be modified to rely on homebrew build of `python3`.

The second one is that gdb ships [dated](https://sourceware.org/git/?p=binutils-gdb.git;a=blob;f=gdb/python/python-config.py;hb=HEAD) copy of `python-config.py` from python2.7. Their version of `python-config.py` doesn't have [bunch of fixes](https://github.com/python/cpython/commits/master/Misc/python-config.in) from cpython (e.g.  a fix for [the issue](https://bugs.python.org/issue36508)). That's why `python-config.py` from gdb produces command line with garbage even on the latest python3 from homebrew:
```
$ /opt/homebrew/bin/python3 python/python-config.py --ldflags
-L/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -lpython3.9 -ldl -framework CoreFoundation -Wl,-stack_size,1000000 -framework CoreFoundation /opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/Python
```

Unlike normal `python3-config --ldflags' from homebrew:
```
$ /opt/homebrew/bin/python3-config --ldflags
-L/opt/homebrew/opt/python@3.9/Frameworks/Python.framework/Versions/3.9/lib/python3.9/config-3.9-darwin -ldl -framework CoreFoundation
```
or legacy python2 from Apple:
```
$ /usr/bin/python-config --ldflags
-L/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/config -lpython2.7 -ldl -framework CoreFoundation
```
Note, there's no `python3-config` in /usr/bin on macOS.

On GDB side, I think a proper fix would be to use `<PYTHON>-config` related to the one passed to GDB's configure via `--with-python=<PYTHON>`.

**Comment by roolebo** [comment]
@cpackham python3 from homebrew helps to build cross gdb, however `.gdbinit` cannot be generated by ct-ng:
```
[EXTRA]    Installing cross gdb
[EXTRA]    Installing '.gdbinit' template
[02:06] / sed: can't read /opt/homebrew/Cellar/crosstool-ng/HEAD-5b0e012_1/share/crosstool-ng/scripts/build/debug/gdbinit.in: No such file or directory
[ERROR]
```

The only place where .gdbinit.in can be found is the toolchain source files:
```
./.build/src/binutils-2.35.1/gas/gdbinit.in
./.build/src/gcc-10.2.0/gcc/gdbinit.in
./.build/src/gdb-9.2/sim/common/gdbinit.in
```

**Comment by roolebo** [comment]
Ah, the gdbinit.in is part of crostool-ng but it's not installed.

**Comment by roolebo** [comment]
@cpackham I think we can close the issue now. crosstool-ng from homebrew doesn't have the issue and I was able to compile a few toolchains, each in less than 30 minutes on M1. Thanks!

**Comment by cpackham** [comment]
@roolebo thanks for the thorough investigation. I had no idea crosstool-ng was in homebrew.

**Comment by mffseal** [comment]
I solved this problem by installing `sudo apt install python-dev-is-python3`. (Ubuntu server 2204)

**Comment by zechenbit** [comment]
> I solved this problem by installing `sudo apt install python-dev-is-python3`. (Ubuntu server 2204)

Thanks. This works for me. (Linux Mint 21)

**Comment by xlla** [comment]
> [@cpackham](https://github.com/cpackham) I think we can close the issue now. crosstool-ng from homebrew doesn't have the issue anymore and I was able to compile a few toolchains, each in less than 30 minutes on M1. Thanks!

hi @roolebo, I have encounter same problem while create toolchain for raspberrypi using crosstool-ng 1.26 from homebrew on macos 10.13.
here is the error log
<pre>
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross gdb
[EXTRA]    Building cross gdb
[ERROR]    configure: error: no usable python found at python2.7
[ERROR]    make[3]: *** [Makefile:11448: configure-gdb] Error 1
[ERROR]    make[2]: *** [Makefile:1005: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
[ERROR]  >>        called from: do_gdb_backend[scripts/build/debug/300-gdb.sh@351]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@80]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
</pre> 

CT_GDB_CROSS_PYTHON_BINARY is empty inside .config.

I have tried pass another version python by
CT_GDB_CROSS_PYTHON_BINARY=python3.9 ct-ng debug+
got same errors.

I have tried manual create link to /usr/local/bin/python2.7 inside build folder .build/tools/bin/, 
ln -s /usr/local/bin/python2.7 python
got same errors.

I have tried modify the .build/armv8-rpi3-linux-gnueabihf/src/gdb/gdb/python/python-config.py
comment out some statements relate to LINKFORSHARED
got same errors and python-config.py was restored to origin
