### ISSUE TITLE
Support for GCC 10 possible?

### ISSUE THREAD

**Issue by graysky2** [crosstool-ng/crosstool-ng#1335]
Is support for [gcc 10](https://gcc.gnu.org/gcc-10/) planned?  @egtvedt - I noticed you sent https://github.com/crosstool-ng/crosstool-ng/pull/1320 to add support for gcc 9.3.0, what does it look like for supporting gcc 10.x?

EDIT: Interestingly, I modified my `.config` to use gcc v10.1 and successfully built the toolchain using .  [Here](https://github.com/graysky2/crosstool-ng_for_distcc/blob/29aac58d5b894dc0187676edc57f5959243c7e43/config) is the config I used.

**Comment by graysky2** [comment]
@egtvedt - I noticed you sent a PR to add support for gcc 9.3.0, what does it look like for supporting gcc 10.x?

**Comment by egtvedt** [comment]
@graysky2 AFAICT adding support for GCC 10 should be straightforward. It is not something I can prioritise testing, but I can add an initial pull request if that helps people.

Also, I only test on 32-bit/64-bit ARM and 64-bit x86, hence perhaps somebody could give my pull request a spin later next week?

I do not have merge permissions, I just create a patch and request a pull :)

**Comment by graysky2** [comment]
@egtvedt - That is excellent.  Again, just using the config I mentioned above ended in what I believe is a functional toolchain based on gcc 10.1.0.

**Comment by cpackham** [comment]
#1368 has been merged to master so we should be able to close this issue. I'll give it a couple of days and close it unless someone else beats me to it.

**Comment by graysky2** [comment]
@cpackham - Yes, it works, safe to close in my opinion.  Thanks!
