### ISSUE TITLE
 zlib: download failed

### ISSUE THREAD

**Issue by yadhukp** [crosstool-ng/crosstool-ng#1337]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- crosstool-ng-1.24.0
-host:ubuntu 16.04
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/4605523/build.log)

**Comment by cpackham** [comment]
Ah sourceforge strikes again. In the master branch we've added https://www.zlib.net/ as a mirror because of reoccurring issues like this.

Having said that it looks like the sourceforge URL is back up (at least for me) so if you try again now it might just work.

Another hint is to use `ct-ng source` before you would run `ct-ng build` which will do all the downloading first. At least then you'll see the issues up-front.

**Comment by evaneight** [comment]
issue still exists, is there any way i can work around this?

thank you


ALL  ]    HTTP request sent, awaiting response... 302 Found
[ALL  ]    Location: https://nav.dl.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz [following]
[ALL  ]    --2021-04-20 10:32:21--  https://nav.dl.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz
[ALL  ]    Resolving nav.dl.sourceforge.net (nav.dl.sourceforge.net)... failed: Connection timed out.
[ALL  ]    wget: unable to resolve host address 'nav.dl.sourceforge.net'
[DEBUG]    ==> Return status 4
[DEBUG]    Not at this location: "http://downloads.sourceforge.net/project/libpng/zlib/1.2.11/zlib-1.2.11.tar.gz"
[DEBUG]    Trying 'https://www.zlib.net//zlib-1.2.11.tar.gz'
[DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/parallels/crosstool-ng/.build/tarballs/zlib-1.2.11.tar.gz.tmp-dl' 'https://www.zlib.net//zlib-1.2.11.tar.gz'
[ALL  ]    --2021-04-20 10:32:31--  https://www.zlib.net//zlib-1.2.11.tar.gz
[ALL  ]    Resolving www.zlib.net (www.zlib.net)... failed: Connection timed out.
[ALL  ]    wget: unable to resolve host address 'www.zlib.net'
[DEBUG]    ==> Return status 4
[DEBUG]    Not at this location: "https://www.zlib.net//zlib-1.2.11.tar.gz"
[ERROR]    zlib: download failed

**Comment by evaneight** [comment]
After re running ct-ng with different params, the build got a bit further, but it is now failing here?

Any ideas?

[DEBUG]    Package iterator: set patch_order='global'
[DEBUG]    Package iterator: run CT_DoFetch 
[DEBUG]    Testing '-n isl'
[EXTRA]    Retrieving 'isl-0.22'
[DEBUG]    Trying 'http://isl.gforge.inria.fr/isl-0.22.tar.xz'
[DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/parallels/crosstool-ng/.build/tarballs/isl-0.22.tar.xz.tmp-dl' 'http://isl.gforge.inria.fr/isl-0.22.tar.xz'
[ALL  ]    --2021-04-20 11:07:45--  http://isl.gforge.inria.fr/isl-0.22.tar.xz
[ALL  ]    Resolving isl.gforge.inria.fr (isl.gforge.inria.fr)... failed: Connection timed out.
[ALL  ]    wget: unable to resolve host address 'isl.gforge.inria.fr'
[DEBUG]    ==> Return status 4
[DEBUG]    Not at this location: "http://isl.gforge.inria.fr/isl-0.22.tar.xz"
[DEBUG]    Trying 'http://isl.gforge.inria.fr/isl-0.22.tar.bz2'
[DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/parallels/crosstool-ng/.build/tarballs/isl-0.22.tar.bz2.tmp-dl' 'http://isl.gforge.inria.fr/isl-0.22.tar.bz2'
[ALL  ]    --2021-04-20 11:07:55--  http://isl.gforge.inria.fr/isl-0.22.tar.bz2
[ALL  ]    Resolving isl.gforge.inria.fr (isl.gforge.inria.fr)... failed: Connection timed out.
[ALL  ]    wget: unable to resolve host address 'isl.gforge.inria.fr'
[DEBUG]    ==> Return status 4
[DEBUG]    Not at this location: "http://isl.gforge.inria.fr/isl-0.22.tar.bz2"
[DEBUG]    Trying 'http://isl.gforge.inria.fr/isl-0.22.tar.gz'
[DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/parallels/crosstool-ng/.build/tarballs/isl-0.22.tar.gz.tmp-dl' 'http://isl.gforge.inria.fr/isl-0.22.tar.gz'
[ALL  ]    --2021-04-20 11:08:05--  http://isl.gforge.inria.fr/isl-0.22.tar.gz
[ALL  ]    Resolving isl.gforge.inria.fr (isl.gforge.inria.fr)... failed: Connection timed out.
[ALL  ]    wget: unable to resolve host address 'isl.gforge.inria.fr'
[DEBUG]    ==> Return status 4
[DEBUG]    Not at this location: "http://isl.gforge.inria.fr/isl-0.22.tar.gz"
[ERROR]    isl: download failed

**Comment by evaneight** [comment]
thats using master branch btw - :)

**Comment by doubleopinter** [comment]
I just ran into this issue myself

**Comment by drhax9908** [comment]
I ran into this issue as well, can you look into it? While i was using the master branch, I also had a cloog download error

**Comment by cpackham** [comment]
@doubleopinter @drhax9908 which issue? zlib and isl should now have updated mirrors. cloog seems OK at the moment

**Comment by thirstyone** [comment]
[DEBUG]    ==> Executing: 'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/Volumes/case-sensitive/esp-open-sdk/crosstool-NG/.build/tarballs/isl-0.14.tar.tmp-dl' 'http://isl.gforge.inria.fr/isl-0.14.tar' 
[ALL  ]    --2022-01-19 01:13:35--  http://isl.gforge.inria.fr/isl-0.14.tar
[ALL  ]    Resolving isl.gforge.inria.fr (isl.gforge.inria.fr)... 128.93.193.15
[ALL  ]    Connecting to isl.gforge.inria.fr (isl.gforge.inria.fr)|128.93.193.15|:80... failed: Operation timed out.
[ALL  ]    Retrying.

**Comment by QBos07** [comment]
Same thing use the latest master branch for the updated urls. Then it should work.

**Comment by evaneight** [comment]
i dont understand your reply
 

Sent: Tuesday, January 18, 2022 at 10:23 PM

**Comment by cpackham** [comment]
Miscellaneous download issues. Some due to the isl/expat url changes others appear to be temporary outages.

**Comment by ektmf7890** [comment]
I struggled from the same issue. I downloaded the tarball of the zlib version I need from [here](https://zlib.net/fossils/) and placed the tarball file at the path ".build/tarballs". This solution worked for me.

**Comment by Danno5060** [comment]
@ettmf7890,

That worked for me.Thanks.

**Comment by Danno5060** [comment]
@ektmf7890, 

That worked for me. 

Maybe better yet, put the zlib tarball in ~/src. ct-ng downloads the sources into that directory and creates symbolic links to these files in ".build/tarballs". This having to do this again if you need to do a distclean.

**Comment by kidram666** [comment]
ZLIB.IO18164326
