### ISSUE TITLE
Backspace key does not work in the configuration menu.

### ISSUE THREAD

**Issue by Davester47** [crosstool-ng/crosstool-ng#1339]
When trying to edit any string value with either `ct-ng menuconfig` or `ct-ng nconfig` in QTerminal, the backspace key does not work. In `nconfig` an error about an unrecognized keypress appears at the top left. All other keys work fine.

As far as I know the bug affects all terminals that use 0x08 as the keycode for backspace. QTerminal does. KConfig in the Linux kernel already has been patched to fix this very problem. PR #1334 also fixes this issue.

This bug affects the latest version of crosstool-ng and is not specific to any .config.

**Comment by cpackham** [comment]
Should have been resolved by #1430
