### ISSUE TITLE
arm-cortex_a8-linux-gnueabi can't build binutils

### ISSUE THREAD

**Issue by jcyesc** [crosstool-ng/crosstool-ng#1340]
-  git checkout crosstool-ng-1.23.0
- Linux 4.15.0-72-generic #81~16.04.1-Ubuntu SMP Tue Nov 26 16:34:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

[config.log](https://github.com/crosstool-ng/crosstool-ng/files/4642734/config.log)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/4642747/build.log)

 =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    g++: internal compiler error: Killed (program cc1plus)
[ERROR]    make[5]: *** [object.o] Error 4
[ERROR]    make[5]: *** Waiting for unfinished jobs....
[ERROR]    make[4]: *** [all-recursive] Error 1
[ERROR]    make[3]: *** [all] Error 2
[ERROR]    make[2]: *** [all-gold] Error 2
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@226]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@97]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]

**Comment by cpackham** [comment]
crosstool-ng-1.23.0 is pretty old. Closing for now. Feel free to re-open if this can be reproduced with 1.25.0 or master
