### ISSUE TITLE
Toolchain: ERROR

### ISSUE THREAD

**Issue by aptem334** [crosstool-ng/crosstool-ng#1350]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
[ERROR]    gmp: download failed
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@485]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2063]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2033]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2134]
[ERROR]  >>        called from: do_gmp_get[scripts/build/companion_libs/100-gmp.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@631]
[ERROR]  >>
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 0:09.04)
[00:10] / ct-ng:236: recipe for target 'build' failed
make: *** [build] Error 1
/------------------------------------------------------------------------------/
[ERROR]    gmp: download failed
[00:24] / ct-ng:236: recipe for target 'build' failed
make: *** [build] Error 1
[ERROR]    gmp: download failed
[00:10] / ct-ng:236: recipe for target 'build' failed
/------------------------------------------------------------------------------/

**Comment by guigarma** [comment]
This issue provides little to no information about the actual problem. Even tough the text clearly points how to handle this kind of errors...

For what arch? Build log? Did you tried disabling EXPERIMENTAL features?

**Comment by cpackham** [comment]
I agree. Based on the limited output provided there was an error downloading the gmp package which would be from either https://gmplib.org/download/gmp, https://gmplib.org/download/gmp/archive or any mirror you've configured. Both those are currently accessible for me.

As those sites are https there is also the possibility that wget/curl on your system is rejecting the connection due to expired/invalid certs. You could check connectivity with `wget https://gmplib.org/download/gmp/gmp-6.2.0.tar.xz`

If you do have intermittent internet access (or simply want to disconnect) you can use the command `ct-ng source` to perform all the downloading for a given configuration first.

**Comment by cpackham** [comment]
Closing. Appears to be a temporary outage on gmplib.org
