### ISSUE TITLE
./ct-ng list-samples get error 

### ISSUE THREAD

**Issue by QuocTranHoangThien** [crosstool-ng/crosstool-ng#1358]
Hi everyone. I use command ./ct-ng list-samples and get this 

Status  Sample name

*** Error during writing of the configuration.

/usr/software/crosstool-ng/samples/samples.mk:78: recipe for target 'list-aarch64-rpi3-linux-gnu' failed
make: *** [list-aarch64-rpi3-linux-gnu] Error 1

similar to ./ct-ng arm-cortex_a8-linux-gnueabi get 

  CONF  arm-cortex_a8-linux-gnueabi

*** Error during writing of the configuration.

/usr/software/crosstool-ng/samples/samples.mk:142: recipe for target 'arm-cortex_a8-linux-gnueabi' failed
make: *** [arm-cortex_a8-linux-gnueabi] Error 1

Can any one help me please

**Comment by cpackham** [comment]
Is your current working directory (`$PWD`) writeable by your user? `ct-ng list-samples` shouldn't be writing anything but the second example looks as though it's tried to write out a `.config` and failed

**Comment by cpackham** [comment]
No response. Closing
