### ISSUE TITLE
Toolchain does not get stripped

### ISSUE THREAD

**Issue by marijnvdwerf** [crosstool-ng/crosstool-ng#1359]
I'm building various arm-none-eabi GCC revisions using Github Actions, and I'm noticing that the binaries are quite big. They don't seem to be getting stripped, despite the strip step appearing in the progress output. The archives generated are around 400MB, when I then run `gstrip **` on my mac over the same files, around ~90MB remains.

Versions:
- crosstool-NG 1.24.0
- Ubuntu 18.04.4 LTS (Github Actions container `ubuntu-latest`)

**Defconfig**
```
CT_CONFIG_VERSION="3"
CT_ARCH_ARM=y
CT_TARGET_VENDOR="none"
CT_LOG_PROGRESS_BAR=n
CT_CC_GCC_EXTRA_CONFIG_ARRAY="--with-gnu-ld --with-gnu-as"
CT_OBSOLETE=y
CT_EXPERIMENTAL=y
CT_GCC_V_4_8=y
```

**.config**
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/4870431/config.txt)

**build.log**
[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/4870460/build.log.zip)

**Comment by NiLuJe** [comment]
This is *probably* #1244 (i.e., it's fixed in master).

**Comment by marijnvdwerf** [comment]
Great, using `master` fixed it! My tarballs are now ~30MB.
