### ISSUE TITLE
Debian 8 after configure --> make message 

### ISSUE THREAD

**Issue by nephaste** [crosstool-ng/crosstool-ng#137]
Hi

just installed Debian 8, after ./configure step

make 

Makefile:115: *** Recursion detected, bailing out.... Arrêt.
Makefile:120: recipe for target 'build' failed
make: *** [build] Error 2

used with crosstool-ng 1.16

thanks for your feedback

**Comment by bhundven** [comment]
Try a newer version of crosstool-ng.
