### ISSUE TITLE
can't load library 'libpthread.so.0' and can't load library 'libm.so.0'

### ISSUE THREAD

**Issue by 0xFF1E071F** [crosstool-ng/crosstool-ng#1370]
```
Crosstool version: crosstool-ng 1.24.0
$ ct-ng -v
GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
Operating System Host:
```
OS: Arch Linux x86_64
Kernel: 5.7.12-arch1-1
```
I have successfully installed `crosstool-ng` and i have successfully made arm-unknown-linux-uclibcgnueabi
```
$ ct-ng arm-unknown-linux-uclibcgnueabi
$ ct-ng build
[ SNIP ]
[INFO ]  =================================================================
[INFO ]  Finalizing the toolchain's directory
[INFO ]    Stripping all toolchain executables
[EXTRA]    Installing the populate helper
[EXTRA]    Installing a cross-ldd helper
[EXTRA]    Creating toolchain aliases
[EXTRA]    Removing installed documentation
[EXTRA]    Collect license information from: /home/user/Crosstool/.build/arm-unknown-linux-uclibcgnueabi/src
[EXTRA]    Put the license information to: /home/user/x-tools/arm-unknown-linux-uclibcgnueabi/share/licenses
[INFO ]  Finalizing the toolchain's directory: done in 8.17s (at 44:55)
[INFO ]  Build completed at 20200813.104230
[INFO ]  (elapsed: 44:54.11)
[INFO ]  Finishing installation (may take a few seconds)...
[44:55] / %    
```

I can run arm binaries with the help of qemu-arm.

My problem is `some binaries` wants `libpthread.so.0` and `libm.so.0`
Errors be like:
```
$ qemu-arm -L ~/x-tools/arm-unknown-linux-uclibcgnueabi/arm-unknown-linux-uclibcgnueabi/sysroot arm02.bin 
/home/user/arm02.bin: can't load library 'libm.so.0'
$ qemu-arm -L ~/x-tools/arm-unknown-linux-uclibcgnueabi/arm-unknown-linux-uclibcgnueabi/sysroot arm00.bin 
/home/user/arm00.bin: can't load library 'libpthread.so.0'
```

**Comment by cpackham** [comment]
A wild guess but could you try `-L ~/x-tools/arm-unknown-linux-uclibcgnueabi/arm-unknown-linux-uclibcgnueabi/sysroot/lib`. Alternatively statically linking the binaries in question would avoid the problem.

**Comment by 0xFF1E071F** [comment]
> A wild guess but could you try `-L ~/x-tools/arm-unknown-linux-uclibcgnueabi/arm-unknown-linux-uclibcgnueabi/sysroot/lib`. Alternatively statically linking the binaries in question would avoid the problem.

Unfortunately this doesn't fixed my problem.

So finally i entered `~/x-tools/arm-unknown-linux-uclibcgnueabi/arm-unknown-linux-uclibcgnueabi/sysroot/lib` directory and gave those commands from terminal:
```
$ ln -s libuClibc-1.0.32.so libpthread.so.0
$ ln -s libuClibc-1.0.32.so libm.so.0
```

Guess what happenned? It WORKED!

According to my searches when you compile uClibc, at the end it makes a big fat libuClibc-1.0.32.so(450K) file. And this includes libm and libpthread.

I don't know if this is a bug or feature but i fix my problem with symlinks.

Close #1370
