### ISSUE TITLE
Build failed in ubuntu 15.04; Message: Build failed in step 'Installing C library'

### ISSUE THREAD

**Issue by josancardenasm** [crosstool-ng/crosstool-ng#139]
Hello. i have this error message when i'm building the toolchain:
What i'm doing wrong?

```
[ALL  ]      STRIP -x -R .note -R .comment lib/libthread_db.a
[ALL  ]      AR cr lib/libdl.a
[ALL  ]      AR cr lib/libpthread.a
[ALL  ]      STRIP -x -R .note -R .comment lib/libdl.a
[ALL  ]      STRIP -X --strip-debug -R .note -R .comment libpthread/nptl/libpthread_so.a
[ALL  ]      LD ld-uClibc-0.9.33.2.so
[ALL  ]      AR cr lib/librt.a
[ALL  ]      STRIP -x -R .note -R .comment lib/librt.a
[ALL  ]      STRIP -x -R .note -R .comment lib/libpthread.a
[ALL  ]      STRIP -x -R .note -R .comment lib/libc.a
[ALL  ]      AR cr libc/libc_so.a
[ALL  ]      STRIP -x -R .note -R .comment libc/libc_so.a
[ALL  ]    make[2]: 'lib/ld-uClibc.so' is up to date.
[ALL  ]      LD libuClibc-0.9.33.2.so
[ALL  ]      LD libdl-0.9.33.2.so
[ALL  ]      LD libcrypt-0.9.33.2.so
[ALL  ]      LD libm-0.9.33.2.so
[ALL  ]      LD libnsl-0.9.33.2.so
[ALL  ]      LD libresolv-0.9.33.2.so
[ALL  ]      LD libutil-0.9.33.2.so
[ALL  ]      LD libpthread-0.9.33.2.so
[ALL  ]      LD libthread_db-0.9.33.2.so
[ALL  ]      LD librt-0.9.33.2.so
[ALL  ]    librt/librt_so.a(rt-unwind-resume.oS): In function `_Unwind_Resume':
[ALL  ]    rt-unwind-resume.c:(.text+0x3c): undefined reference to `libgcc_s_resume'
[ERROR]    collect2: error: ld returned 1 exit status
[ALL  ]    librt/Makefile.in:61: recipe for target 'lib/librt.so' failed
[ERROR]    make[1]: *** [lib/librt.so] Error 1
[ALL  ]    make[1]: Leaving directory '/home/goonie/crosstool-ng/.build/arm-unknown-linux-uclibcgnueabi/build/build-libc'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_libc[scripts/build/libc/uClibc.sh@200]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 41:18.13)
```

**Comment by josancardenasm** [comment]
The problem was solved with crosstool-ng 1.20.0. I was building the sample arm-unknown-uclibceabi.

**Comment by bhundven** [comment]
@josancardenasm Issue is solved? If you're still having an issue, please reopen this issue.

**Comment by josancardenasm** [comment]
i still have this issue with the lastest version of crosstool-ng but i can build the same sample of the toolchain with crosstool-ng 1.20.0. I dont know if i should close the issue.

**Comment by bhundven** [comment]
@josancardenasm Latest release version or the latest clone of the git repository? There is a big difference (and I honestly, should cut a release).

**Comment by josancardenasm** [comment]
lastest clone of the git repository

**Comment by bhundven** [comment]
Ok. Could you post a link to your config and build log?

**Comment by josancardenasm** [comment]
https://www.dropbox.com/s/iuxvow6ewliaw1u/.config?dl=0

https://www.dropbox.com/s/dcbxkrccidp76qp/build.log?dl=0

**Comment by bhundven** [comment]
Hrm, uClibc... I'm actually working on adding uClibc-ng as we speak (type...).
Let me finish getting that in, and I'll have you test before I commit uClibc-ng support.

**Comment by josancardenasm** [comment]
Thank you very much! :smiley:

**Comment by pkoretic** [comment]
I have the same problem for the sh4-unknown-linux-gnu
1.21.0 or git doesn't work for glibc or uclibc
using 1.20 works for both
should I open a new issue with details or should I also wait for your patch  @bhundven?

**Comment by Frederick888** [comment]
I had the same [issue](https://github.com/crosstool-ng/crosstool-ng/issues/162) when building `gcc 5.2.0` with `eglibc 2.13`. crosstool-NG 1.20.0 didn't save me.

**Comment by bhundven** [comment]
@Frederick888 eglibc is no longer supported.

**Comment by bhundven** [comment]
This should be fix for arm on uclibc with #200. Please test and verify.

**Comment by bhundven** [comment]
@pkoretic AFAIU (I could be wrong...) SH4 is broken with GCC 5.x. There is supposedly a fix in gcc-6, but I haven't had time to look for the fix. As with #196, try using gcc-4.9.3.

**Comment by bhundven** [comment]
In general, if the reported architecture is not the architecture you are having problems with, please open a new bug. This bug was reported for arm and uclibc, and is fixed. I'm closing this issue.
