### ISSUE TITLE
Website Tips: use Github Actions to release tar.xz file

### ISSUE THREAD

**Issue by sky5454** [crosstool-ng/crosstool-ng#1394]
To visit the website `http://crosstool-ng.org/download/crosstool-ng/`  in China is too slow.

so I wonder if you can use Github Actions to release tar.xz file, which could improve download speed and save the bandwide of your website `crosstool-ng.org`.

**Comment by cpackham** [comment]
I'll look into it. The actual releases have some generated files and are PGP signed so might not be totally automate-able but there's no reason we can't add the artifacts.

**Comment by cpackham** [comment]
I've uploaded older releases 1.21.0 to 1.24.0 as well as the new 1.25.0 release.

Hopefully is sufficient for most needs. If there is a particular need for accessing an older release we can add it as requested.
