### ISSUE TITLE
glibc overwrites optimization flags (with "-O" in 2.32, "-O2" in older versions)

### ISSUE THREAD

**Issue by hwti** [crosstool-ng/crosstool-ng#1396]
Since bd0ea7ed, `CFLAGS` is set to an empty value, so there is no `-g -O2` from the configure.
But then glibc appends its `default_cflags` in Makeconfig, which overrides the ones from ct-ng which are in `CC`.

In glibc 2.32, it happens to be by mistake `-g -O`, instead of `-g -O2` previously (see https://sourceware.org/bugzilla/show_bug.cgi?id=26700).

If we ignore the glibc 2.32 issue, `-g -O2` is already what ct-ng gave.
But for example a `CT_GLIBC_EXTRA_CFLAGS="-Os"` would be overwritten by glibc.

So maybe `scripts/build/libc/glibc.sh` should set `extra_make_args+=( default_cflags= )`.

**Comment by egtvedt** [comment]
Let's see what glibc upstream states in the bug report, and patch our glibc depending on that. I suspect the glibc configuration script should switch from stable to release to match the version.h change.

**Comment by hwti** [comment]
Isn't the expected behavior leaving control of the optimization flags to ct-ng, with the `-g -O2` base but `CT_GLIBC_EXTRA_CFLAGS` after ?

When the flags where in `CFLAGS`, it prevented both configure and Makeconfig from adding their `-g -O2`. The switch to `CC` broke this, and it seems https://github.com/crosstool-ng/crosstool-ng/commit/bd0ea7ed21f140d4e911ff4a63693b54a455c349 was only a partial fix (maybe the build log wasn't checked).

**Comment by egtvedt** [comment]
I created a pull request for the patch from upstream at least, to restore our initial behaviour.

**Comment by egtvedt** [comment]
With the change above I now see '-g -O' and '-g -O2' when building, so I am still confused. However, IIRC having both -O and -O2 will produce -O2 optimised binaries, independent of order.

Please correct me if wrong.

**Comment by hwti** [comment]
Before the change, you should have `-g -O2 ... -g -O`.
After, it should be `-g -O2` twice.
Which source file did you check ?

`-O2 ... -O` is the same as `-O`, so the order is important.

**Comment by egtvedt** [comment]
I looked at the build.log output.

**Comment by egtvedt** [comment]
Done rebuilding, and now I have verified after my submitted patch, it will be `-g -O2` twice.

**Comment by egtvedt** [comment]
I think we want
```
diff --git a/scripts/build/libc/glibc.sh b/scripts/build/libc/glibc.sh
index 31fa067f..ba6e5482 100644
--- a/scripts/build/libc/glibc.sh
+++ b/scripts/build/libc/glibc.sh
@@ -314,6 +314,8 @@ glibc_backend_once()
             ;;
     esac

+    # Make sure glibc build system respects our provided CFLAGS.
+    extra_make_args+=( default_cflags= )
     extra_make_args+=( "BUILD_CFLAGS=${build_cflags}" )
     extra_make_args+=( "BUILD_CPPFLAGS=${build_cppflags}" )
     extra_make_args+=( "BUILD_LDFLAGS=${build_ldflags}" )
```

As you initially suggested to improve CFLAGS in glibc build system.

**Comment by egtvedt** [comment]
Pull request #1398 is merged, can we close this now?
