### ISSUE TITLE
Building C library fails due to LR & PC registers confliction

### ISSUE THREAD

**Issue by mahyar1284** [crosstool-ng/crosstool-ng#1397]
- crosstool-NG version: 1.24.0.167_e7da850
- host OS and its version: Ubuntu 20.04 LTS
- `.config`: [config.txt](https://github.com/crosstool-ng/crosstool-ng/files/5322947/config.txt)
- `build.log`: [build.log](https://github.com/crosstool-ng/crosstool-ng/files/5322948/build.log)
- Target: cortex-m7 (only supports thumb instruction-set and It's an MMU-less architecture)

[ERROR]      libc/sysdeps/linux/arm/setcontext.S:63: Error: LR and PC should not both be in register list -- `ldmia r14,{r14,pc}'
[ERROR]      make[2]: *** [Makerules:372: libc/sysdeps/linux/arm/setcontext.os] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'

**Comment by cpackham** [comment]
I wonder if this is a recent regression?

Some internet searching turned up this old-ish buildroot patch https://patchwork.ozlabs.org/project/buildroot/patch/CAEp4hJ0A0fdO66w_r0LB4hBhQVVOZYzy+60vLuidE7H4YZ3Tzg@mail.gmail.com/

**Comment by cpackham** [comment]
The problem appears to be UCLIBC_HAS_CONTEXT_FUNCS which is incompatible with thumb mode. Commit 57679b5 appears to try and fix this. But with the configuration provided uclibc ends up with this set.
