### ISSUE TITLE
ncurses inclusion without pkg-config broken (kconfig)

### ISSUE THREAD

**Issue by GitMensch** [crosstool-ng/crosstool-ng#1403]
configure does the correct thing:

> checking for working ncurses/curses.h... yes
checking for working ncurses.h... no
checking for Curses Panel library with panel.h... no
checking for Curses Panel library with ncurses/panel.h... yes
checking for Curses Menu library with menu.h... no
checking for Curses Menu library with ncurses/menu.h... yes

But kconfig directly includes curses.h and menu.h.

To fix this: either adjust kconfig to `#include "config.h"` and check the existing defines, including either with or without the sub-folder or only check for "curses.h + panel.h + menu.h" and if they don't exist output a hint that the user should include the directory manually via `CPPFLAGS="-Iwhatever/ncurses` - which is the workaround I've applied for my installation.

**Comment by cpackham** [comment]
Looks like this was caused by my attempts to update kconfig. I've got a reasonable idea for a fix
