### ISSUE TITLE
Make command doesn't work in repo

### ISSUE THREAD

**Issue by idoSinai** [crosstool-ng/crosstool-ng#1406]
Did:
git clone https://github.com/crosstool-ng/crosstool-ng
./bootstrap
./configure --enable-local
make

all worked until 'make' command then I received:
/usr/bin/make  all-recursive
make[1]: Entering directory '/home/ido/crosstool-ng'
Making all in kconfig
make[2]: Entering directory '/home/ido/crosstool-ng/kconfig'
yacc -l -b zconf -p zconf  -ozconf.c zconf.y
/bin/bash: yacc: command not found
make[2]: *** [Makefile:897: zconf.c] Error 127
make[2]: Leaving directory '/home/ido/crosstool-ng/kconfig'
make[1]: *** [Makefile:3055: all-recursive] Error 1
make[1]: Leaving directory '/home/ido/crosstool-ng'
make: *** [Makefile:2802: all] Error 2

**Comment by bhundven** [comment]
It says you're missing `yacc`.
