### ISSUE TITLE
Unknown configure options for lib ISL.

### ISSUE THREAD

**Issue by jasmin-j** [crosstool-ng/crosstool-ng#141]
Configure options --with-libgmp-prefix and --with-libgmpxx-prefix are no longer available in ISL 0.12.2.
Configure option --with-piplib=no is no longer available in ISL 0.14.
This is more a cosmetic thing, but I fixed it in my local copy.
I will add a branch to my repo on GitHub.

**Comment by jasmin-j** [comment]
Please find the fix for this issue on branch
   https://github.com/jasmin-j/crosstool-ng/tree/fix_141

**Comment by mingwandroid** [comment]
Thanks @jasmin-j 
Can you make a pull request for this? And add the "Signed-off-by: name <em@il.address>"
