### ISSUE TITLE
Incompatible use of specific foldername character @ with SED in libc/libelf

### ISSUE THREAD

**Issue by jaapvstr** [crosstool-ng/crosstool-ng#1420]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
1.24.0
- Report host OS and its version
Linux x86_64 4.14.x
- Attach `.config` (unless the issue is not related to any configuration) n/a
- Attach `build.log` (unless crosstool-NG fails before the build starts) - shared only the relevant portion below

While trying to build GCC-4.9.4 with glibc 2.19 (WITHOUT multilib), it crashed on gcc pass 2 due to unsafe use of SED.
The root cause is an incompatibility with a directory I installed crosstool-ng into. It had a-@ sign, which was also used in the sed:

_4-asustor-linux-gnu/build/build-libc-final/multilib/stamp.os /volume2/owncloud/data/xxxxxxxx@gmail.com/files/xxxx/crosstool-ng/bin/.build/x86_64-asustor-linux-gnu/build/build-libc-final/multilib/*/stamp.os |         LC_ALL=C        sed 's@^/volume2/owncloud/data/xxxxxxxxx@gmail.com/files/Apkg/crosstool-ng/bin/.build/x86_64-asustor-linux-gnu/build/build-libc-final/multilib/([^/]*)/stamp.os$@rtld-1'" +=$file@";;        */*.a)            echo rtld-${lib%%/*} += $file ;;      *) echo "Wasn't expecting $lib($file)" >&2; exit 1 ;;           esac;        done > /volume2/owncloud/data/xxxxxxxx@gmail.com/files/xxxx/crosstool-ng/bin/.build/x86_64-asustor-linux-gnu/build/build-libc-final/
multilib/elf/librtld.mkT
[ALL  ]      sed: -e expression #1, char 168: unknown option to `s'_

I'm now going for the workaround of installing it in a location without @, however it would be nice if the SED used to patch elf can be changed, so directories with @ are also supported.

I happen to have some dummy code that might come in handy for making sed safe, though have no idea what file this should be changed in:
pattern1='PATTERN TO MATCH'
safe_pattern1=$(printf '%s\n' "$pattern1" | sed 's/[[\.*^$/]/\\&/g')
pattern2="PATTERN TO REPLACE"
safe_pattern2=$(printf '%s\n' "$pattern2" | sed 's/[[\.*^$/]/\\&/g')
sed -i "s/${safe_pattern1}/${safe_pattern2}" /crosstool-ng/the/file/to/patch

**Comment by cpackham** [comment]
That sed invocation is from glibc, not something crosstool-ng is doing. Looking upstream the [problematic sed is still there](https://sourceware.org/git/?p=glibc.git;a=blob;f=elf/Makefile#l532). You might have better luck reporting the bug to the glibc maintainers.

**Comment by jaapvstr** [comment]
Thanks, that indeed seems to be the file the sed comes from. I've reported it upstream. Herebelow the related bug tracker:
https://sourceware.org/bugzilla/show_bug.cgi?id=26906

**Comment by cpackham** [comment]
Closing as this is an upstream issue.
