### ISSUE TITLE
Stop after downloading tarballs [feature request wishlist]

### ISSUE THREAD

**Issue by sjackman** [crosstool-ng/crosstool-ng#1421]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
`ed3a1ff4b938f12bcb9bbfdb90d4e3d933d28b2d`

- Report host OS and its version
Linux

- Attach `.config` (unless the issue is not related to any configuration)
NA

- Attach `build.log` (unless crosstool-NG fails before the build starts)
NA

I'd like to stop after downloading the tarballs `Retrieving needed toolchain components' tarballs`.
As a workaround I'm using `ct-ng +companion_tools_for_build` for now, but it takes about 5 minutes longer than just stopping after downloading.

**Comment by sjackman** [comment]
My use case is that I'm building and running `crosstool-ng` in a Docker container, and I'd like to download and cache the source tarballs outside of the Docker container, before running `crosstool-ng` build within the Docker container and feeding it the tarballs.

**Comment by jaapvstr** [comment]
Isn't that already available via the "ct-ng source" command ?

**Comment by cpackham** [comment]
Yep `ct-ng source` is what you want. You can even get a bit fancy and use a container with bind mounted volume to do the downloading and other containers to build the toolchain(s) we do something like this at $dayjob.

**Comment by sjackman** [comment]
Thank you! Sorry that I missed that.
