### ISSUE TITLE
Question: How to customize linux kernel version when create cross compile tool chain

### ISSUE THREAD

**Issue by newthis** [crosstool-ng/crosstool-ng#1427]
This is more of a help request than an issue. I have set up  other options for the .config file. However, I can not find 
the needed linux kernel version 4.1.17 when configuring the .config file. 
**I want to ask if there exists some way to define the kernel version in certain file?**

**Comment by egtvedt** [comment]
Adding a new kernel version is not straightforward, but it is not difficult to do locally.

First add the directory packages/linux/4.1.17
Then create the files version.desc and chksum within this directory.

The version.desc file is empty, while the chksum file contains hashes of the downloaded archive. See a different kernel version for syntax.

Now remember to run the top level script ./bootstrap, and you will now get the 4.1.17 version available as an option.

**Comment by newthis** [comment]
I have added an empty version.desc and a chksum file with the content:
md5 linux-4.1.17.tar.xz 4b0bd6b3775170ce0f76ef219ac279d8
sha1 linux-4.1.17.tar.xz d1bfbb51dd4cc0c2a8b9b5302e8e35f978f0be6f
sha256 linux-4.1.17.tar.xz 4b19988e252d4a954d86f9a5aa2d32e11e6131ad182f25b3a447d4b753909120
sha512 linux-4.1.17.tar.xz f25044a661a5357377ac63ea1c7748de91354ca924e2bd282d681796e3d0284fc63767f1ce8671f9d565690ea46bc7ac7bd1901f0f6e4c569d05e6d7e6cddd8d
md5 linux-4.1.17.tar.gz a626ff0bca02ac95668436c2117d12ab
sha1 linux-4.1.17.tar.gz 029ec98569a8621df9e13aa59707841a1bdcaac9
sha256 linux-4.1.17.tar.gz 9cc9d49929c8a28622ca131bafb6a7a9ac3db431ee29ffe9eded1e32858b1909
sha512 linux-4.1.17.tar.gz 17b93b9a3d73eb8892a8849148e248f7a4c800729dbb6ce67ffde2af2147e9679c99be35b9df52c0d1b6abda822487d278acbd1b142662026a4c967c49bc8523

under packages/linux/4.1.17.
However, when run ./bootstrap, the error occurs:
**ERROR :: linux: version 4.1.17 conflicts with version 4.1.49 (4.1 selector)**

**Comment by cpackham** [comment]
You don't have to add anything. Just set `CT_LINUX_SRC_CUSTOM=y` and `CT_LINUX_CUSTOM_LOCATION="http://cdn.kernel.org/pub/linux/kernel/v4.x/linux-4.1.17.tar.xz"` (or a local path if you have a copy already downloaded).

**Comment by newthis** [comment]
You mean directly add this to .config file? @cpackham

**Comment by cpackham** [comment]
I mean use `ct-ng menuconfig` to set those options.

**Comment by newthis** [comment]
Yeah, I tried a different version and found that 1.24.0-rc3 version does not contain this option , while 1.23.0 version contains this option.

**Comment by cpackham** [comment]
It's tucked away behind !EXPERIMENTAL

So you need to select `Paths and misc options  --->`, `Try features marked as EXPERIMENTAL`, back to `Operating System  --->`, `Target OS  --->` choose `linux`, `Source of linux   --->` choose `Custom location`, `Custom source location` should now be available. I think I incorrectly said this could be a URL but it does need to be a path to the tarball

**Comment by newthis** [comment]
I have found that in 1.24.0-rc3 version, thanks so much for your advice.
