### ISSUE TITLE
 arm-cortex_a8-linux-gnueabi can't build binutils if gold linker is allowed

### ISSUE THREAD

**Issue by argenet** [crosstool-ng/crosstool-ng#1440]
- Crosstool-NG version: `crosstool-ng-1.24.0`
- Host OS: `Linux detinets 5.9.14-arch1-1 #1 SMP PREEMPT Sat, 12 Dec 2020 14:37:12 +0000 x86_64 GNU/Linux`

The build fails if the `gold` linker is allowed along with `ld` when trying to build `binutils` for the host. `gold` fails to find the `std::string` class:
```
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    /home/user/toolchain/.build/arm-cortex_a8-linux-gnueabihf/src/binutils/gold/errors.h:87:50: error: 'string' in namespace 'std' does not name a type
```

If the configuration is changed to only allow the `ld` linker instead (Binary Utilities -> Linkers to enable (ld, gold) -> (X) ld), the build succeeds.
If the configuration is changed to only allow

**Comment by cpackham** [comment]
I believe this was fixed in #1356
