### ISSUE TITLE
Linux Header Install Error 127

### ISSUE THREAD

**Issue by 1Jo1** [crosstool-ng/crosstool-ng#1443]
- version master 4ae7ed0113910ff175b0c8e00df0ffb2b4ac8735
- Arch Linux Kernel version: 5.10.5-arch1-1
- config: `ct-ng arm-unknown-linux-gnueabi`

when I run `ct-ng build `I get error during the installing headers, an attempt was made to install linux-5.8.9 headers, which are slightly older and no longer supported
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/5792547/build.log)

Error:
```
Installing kernel headers
[EXTRA]    Installing kernel headers
[ERROR]    make[2]: *** [/home/jo/development/cross-compile/test/.build/src/linux-5.8.9/Makefile:1249: headers_install] Error 127
[ERROR]    make[1]: *** [Makefile:185: __sub-make] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing kernel headers'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_kernel_headers[scripts/build/kernel/linux.sh@64]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
[ERROR]  >>
```

**Comment by cpackham** [comment]
Newer kernel header builds require rsync you'll need to install that package. And I should get round to bumping the header versions.

**Comment by 1Jo1** [comment]
ok thanks I will try that :)
