### ISSUE TITLE
Bad sha512 digest for zlib

### ISSUE THREAD

**Issue by zerkerX** [crosstool-ng/crosstool-ng#1453]
The issue is pretty straightforward. I was attempting to use crosstool-ng today, and it did not get an expected checksum for zlib-1.2.11.tar.xz. See build.log for details.

I initially saw this on the released version 1.24, and also on the latest git version (crosstool-NG version 1.24.0.261_30316cd per version report). I am running on Debian testing, which is currently tracking the upcoming Bullseye/11.

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/5915402/build.log)

**Comment by cpackham** [comment]
Actually looks like sourceforge is having issues. At first I thought they were doing some shenanigans but when I fetch the file
```
$ sha512sum zlib-1.2.11.tar.xz
c7f9d4c715479421640e484b2834e0a6868844b1e4986513147e911e02f9af1ef8393d6f8196aca50880fcaa870e60a9b91bc429e30199280e31b8c37fb14b3e  zlib-1.2.11.tar.xz
$ file zlib-1.2.11.tar.xz
zlib-1.2.11.tar.xz: HTML document, ASCII text

$ cat zlib-1.2.11.tar.xz
<html><head>
<title>SourceForge</title>
<!-- <script src="/js/jquery.com/jquery-1.11.0.min.js"></script> -->
<script src="https://code.jquery.com/jquery-1.11.0.min.js"></script>
<script src="https://sourceforge.net/js/mirrors.js"></script>
<script src="/js/sf.js"></script>
<script>
var DR_loc = DR_parse_hash_url();
if (DR_loc) {
    DR_sf_main(DR_loc);
} else {
    window.location.href = 'https://sourceforge.net/home.html';
}
</script>
<meta name="description" content="Free, secure and fast downloads from the largest Open Source applications and software directory - SourceForge.net"/>
</head><body>
<noscript>
We're sorry -- the Sourceforge site is currently in Disaster Recovery mode.  Please check back later.
</noscript>
</body></html>
```

In the meantime https://www.zlib.net/zlib-1.2.11.tar.xz is up and serving the appropriate file.

**Comment by cpackham** [comment]
Sourceforge seems to be back working now. No obvious outage report from them.

**Comment by zerkerX** [comment]
Yeah, sorry for the nuisance report, but thanks for looking into it so promptly! I should have double-checked what I had actually ended up downloading. This request can be closed.
