### ISSUE TITLE
Newlib's "nano" libraries are missing "_nano" suffixes

### ISSUE THREAD

**Issue by abrodkin** [crosstool-ng/crosstool-ng#1458]
Thanks to https://github.com/crosstool-ng/crosstool-ng/pull/1447 we may now build & install Newlib libs optimized for size (AKA "nano" libraries) together with normal Newlib libs. But here in CT-NG we install "nano" libs to its own sysroot (`${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}` as opposed to normal libs put in `${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}`. And then if `--specs=nano.specs` is specified on the GCC's command line we use all the libs from "nano" sysroot, otherwise we use normally built libs.

And it's all fine until you try to link something with some existing `.specs` which do rename of `-lc` to `-lc_nano` that way, see https://www.sourceware.org/git/?p=newlib-cygwin.git;a=blob;f=libgloss/arm/elf-rdimon.specs:
```
*rdimon_libc:
%{!specs=nano.specs:-lc} %{specs=nano.specs:-lc_nano}

...

*link_gcc_c_sequence:
%(rdimon_link_gcc_c_sequence) --start-group %G %(rdimon_libc) %(rdimon_libgloss) --end-group
```
it won't work :)

```
$ arm-bare_newlib_cortex_m3_nommu-eabi-gcc test.c --specs=rdimon.specs

$ arm-bare_newlib_cortex_m3_nommu-eabi-gcc test.c --specs=rdimon.specs --specs=nano.specs
.../x-tools/arm-bare_newlib_cortex_m3_nommu-eabi/arm-bare_newlib_cortex_m3_nommu-eabi/bin/ld.real: cannot find -lc_nano
.../x-tools/arm-bare_newlib_cortex_m3_nommu-eabi/arm-bare_newlib_cortex_m3_nommu-eabi/bin/ld.real: cannot find -lrdimon_nano
collect2: error: ld returned 1 exit status
```

I think we only need to take care of `libc.a`, `libm.a`, `libg.a`, `libstdc++.a` & `libsupc++.a`.

I see 2 solutions here:
1. Create `*_nano.a` symlincs in "nano" sysroot so that LD is happy.
2. Copy (or install) selected "nano" libs to the normal sysroot (that's how Elf toolchains seems to be built historically).

**Comment by abrodkin** [comment]
I tried to go the first way with that simple change (note newlib builds multilibbed folder structure itself in 1 go, so then we have to iterate over all individual subfolders to create symlinks, thus use of `CT_IterateMultilibs`):
```diff
diff --git a/scripts/build/companion_libs/350-newlib_nano.sh b/scripts/build/companion_libs/350-newlib_nano.sh
index 00ea948d..de2179da 100644
--- a/scripts/build/companion_libs/350-newlib_nano.sh
+++ b/scripts/build/companion_libs/350-newlib_nano.sh
@@ -22,6 +22,19 @@ do_newlib_nano_extract() {
     CT_ExtractPatch NEWLIB_NANO
 }

+# Some architectures assume "nano" libs co-exist with normal ones
+# inthe same folder, though being suffixed with "_nano".
+do_nano_libc_symlinks() {
+    ln -s libc.a libc_nano.a
+    ln -s libm.a libm_nano.a
+    ln -s libg.a libg_nano.a
+}
+
+do_nano_libstdcxx_symlinks() {
+    ln -s libstdc++.a libstdc++_nano.a
+    ln -s libsupc++.a libsupc++_nano.a
+}
+
 #------------------------------------------------------------------------------
 # Build an additional target libstdc++ with "-Os" (optimise for speed) option
 # flag for libstdc++ "newlib_nano" variant.
@@ -59,6 +72,7 @@ do_cc_libstdcxx_newlib_nano()
         CT_DoStep INFO "Installing libstdc++ newlib-nano"
         CT_mkdir_pushd "${CT_BUILD_DIR}/build-cc-libstdcxx-newlib-nano"
         "${final_backend}" "${final_opts[@]}"
+        CT_IterateMultilibs do_nano_libstdcxx_symlinks ${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/lib/
         CT_Popd

         CT_EndStep
@@ -180,6 +194,8 @@ ENABLE_TARGET_OPTSPACE:target-optspace

 EOF

+    CT_IterateMultilibs do_nano_libc_symlinks ${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/lib/
+
     CT_Popd
     CT_EndStep

```

And it almost did the trick except for the fact libs were installed in a bit wrong location :)
It turned out `CT_IterateMultilibs` silently adds `_` (underscore) before the `multilib` folder here: https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/functions#L1600:
```bash
        # Brain-dead Cygwin hack: Cygwin cannot run a binary if there is a directory
        # component in the path that ends with a dot. Unfortunately, that's the case
        # for the default library name with GCC.
        dir_postfix=_${multi_dir//\//_}
        dir_postfix=${dir_postfix%_.}
```

I.e. that's what I see in the log:
```
[INFO ]  =================================================================
[INFO ]  Installing Newlib Nano library
[EXTRA]    Configuring Newlib Nano library
[EXTRA]    Building Newlib Nano C library
[EXTRA]    Installing Newlib Nano C library
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_em'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_em_mini'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_arcem'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_em4'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_em4_dmips'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_em4_fpus'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_em4_fpuda'
[INFO ]    Multilib iterator: call function 'do_nano_libc_symlinks' in '.../x-tools/arc-multilib-elf/newlib-nano/arc-multilib-elf/lib/_quarkse_em
```

I might be doing something silly here, but so far I didn't find any other elegant solution.
@cpackham @keith-packard any thoughts?

**Comment by keith-packard** [comment]
sorry, I don't have any idea how to work around this; deep ct magic...

**Comment by keith-packard** [comment]
Leaving the install the way it is now means you don't have to install the huge newlib version at all, which seems pretty useful.

**Comment by abrodkin** [comment]
@keith-packard could you please elaborate on this a bit more? I don't think I got your idea, sorry.

**Comment by keith-packard** [comment]
I haven't explored this in detail, but using the 'regular' newlib process to build and install the nano version should avoid any potential dependency on having the 'non-nano' version also installed.

**Comment by abrodkin** [comment]
Well, but if you need just "nano" version of Newlib, you may just configure "non-companion lib" Newlib so that it matches "nano" settings.

**Comment by keith-packard** [comment]
agreed. it would be good if both methods worked. Using the companion version ensures that you get the desired configuration without having to carefully adjust parameters.

**Comment by abrodkin** [comment]
Ok, then I'll send a PR with above implementation. Thanks for your input.
