### ISSUE TITLE
Unable to use a riscv64-unknown-elf after building it 

### ISSUE THREAD

**Issue by SaraNassef** [crosstool-ng/crosstool-ng#1460]
- Crosstool-NG version : 4.2.1
-Host OS and its version: Ubuntu 20.04.2 LTS

I've built riscv64-unknown-elf-toolchain to use it in building riscv-tools using the following commands:

git clone https://github.com/crosstool-ng/crosstool-ng
cd crosstool-ng
./bootstrap
./configure --prefix=/home/osboxes/Desktop/crosstool-ng/install
make
make install
export PATH="${PATH}:/home/osboxes/Desktop/crosstool-ng /install/bin“
ct-ng riscv64-unknown-elf
echo CT_PREFIX_DIR=/x-tools
echo CT_CC_GCC_USE_GRAPHITE=n >> .config
echo CT_ISL_NEEDED=n >> .config
echo CT_ISL=n >> .config
echo CT_MULTILIB=n >> .config
ct-ng build
export PATH="${PATH}:/x-tools/riscv64-unknown-elf/riscv64-unknown-elf/bin"

but when typing which riscv64-unknown-elf-gcc I don't get anything, am I missing something ?

Thanks in advance
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/6022754/build.log)

**Comment by cpackham** [comment]
> I've built riscv64-unknown-elf-toolchain to use it in building riscv-tools using the following commands:
> 
> git clone https://github.com/crosstool-ng/crosstool-ng
> cd crosstool-ng
> ./bootstrap
> ./configure --prefix=/home/osboxes/Desktop/crosstool-ng/install
> make
> make install
> export PATH="${PATH}:/home/osboxes/Desktop/crosstool-ng /install/bin“

I assume the space after crosstool-ng is just an artifact of pasting into a github issue

> ct-ng riscv64-unknown-elf
> echo CT_PREFIX_DIR=/x-tools

This won't do anything as it's missing the `>> .config`. But assuming you want the toolchain installed into a directory called "x-tools" in your home directory you shouldn't need to do anything here.
 
> echo CT_CC_GCC_USE_GRAPHITE=n >> .config
> echo CT_ISL_NEEDED=n >> .config
> echo CT_ISL=n >> .config
> echo CT_MULTILIB=n >> .config
> ct-ng build
> export PATH="${PATH}:/x-tools/riscv64-unknown-elf/riscv64-unknown-elf/bin"
> 
> but when typing which riscv64-unknown-elf-gcc I don't get anything, am I missing something ?

You're missing `${HOME}` this should be `export PATH="${PATH}:${HOME}/x-tools/riscv64-unknown-elf/riscv64-unknown-elf/bin`

But I don't think that's quite the full story as based on the build log you've supplied this has been built as root so the toolchain binaries are in `/root/x-tools/riscv64-unknown-elf/bin` generally you shouldn't need to build as root a regular unprivileged user is fine.

**Comment by SaraNassef** [comment]
I've tried `export PATH="${PATH}:${HOME}/x-tools/riscv64-unknown-elf/riscv64-unknown-elf/bin" ` and it worked. 
Thanks
