### ISSUE TITLE
GCC configuration "Use __cxa_atexit" is disabled with bare-metal configuration

### ISSUE THREAD

**Issue by jasmin-j** [crosstool-ng/crosstool-ng#147]
When the target OS is selected to bare-metal, the GCC configuration option "Use __cxa_atexit" is disabled. The mentioned GCC configuration should be enabled by the used libc, if it provides such a function.
I will add a branch to my repo on GitHub to implement the new feature.

**Comment by bhundven** [comment]
This change is merged. Closing. :)
