### ISSUE TITLE
Question: build arm64-unknown-linux-musl toolchain

### ISSUE THREAD

**Issue by daggs1-zz** [crosstool-ng/crosstool-ng#1472]
Greetings,

I wanted to know if there a way to build an aarch64-unknown-linux-musl toolchain but under the name arm64-unknown-linux-musl toolchain?
CT_ARCH_SUFFIX appends to the string not replaces.

ideas?

thanks

**Comment by cpackham** [comment]
CT_TARGET_ALIAS is probably the best way to achive this.

**Comment by cpackham** [comment]
Question was answered. Closing
