### ISSUE TITLE
Support building Bionic and other required android stuff from source

### ISSUE THREAD

**Issue by j123123** [crosstool-ng/crosstool-ng#1476]
Hello. I see there https://github.com/crosstool-ng/crosstool-ng/blob/364ed7aa96905920649d8be1455f136631f6cf5c/config/libc/bionic.in crosstools-ng just downloading some .zip file and extracting some ```.a``` archives from it:
```libc.a  libcompiler_rt-extras.a  libdl.a  libm.a  libstdc++.a  libz.a```
 But what about building all this things from scratch?

Last NDK which have gcc support is r17 (https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip) so you stuck on that version, that's not good.

https://android.googlesource.com/toolchain/gcc/+/refs/heads/ndk-release-r23 - here I see there are avaliable GCC whti ndk-r23 - but GCC is outdated

**Comment by j123123** [comment]
I tried to build bionic using AOSP source, using this instruction https://source.android.com/setup/build/initializing

```
$ repo init -u https://android.googlesource.com/platform/manifest -b android-security-9.0.0_r66
$ repo sync
$ lunch aosp_arm-eng
$ cd bionic/
$ mm
```
so I got this path with headers:
``out/soong/ndk/sysroot/usr/include/``

and some ``.a`` files in:
``out/target/product/generic/obj/STATIC_LIBRARIES/``

for example ``libc.a`` is at ``.../STATIC_LIBRARIES/libc_intermediates/libc.a``;
``libcompiler_rt-extras.a`` is at ``.../STATIC_LIBRARIES/libcompiler_rt-extras_intermediates/libcompiler_rt-extras.a``
``libstdc++.a`` is at ``.../STATIC_LIBRARIES/libstdc++_intermediates/libstdc++.a``

but ``libz.a`` is at ``out/soong/.intermediates/external/zlib/libz/android_arm_armv7-a-neon_core_static``
Maybe replace the compiler's calls from clang to gcc somehow?  Android build system uses pre-builded cross-compiler from ``prebuilts/clang/host/linux-x86/`` so it doesn't build cross-compiler from scratch

building NDK requires some docker image to meet the dependencies:
https://android.googlesource.com/platform/ndk/+/master/docs/Building.md

**Comment by gamecss** [comment]
+1

**Comment by gamecss** [comment]
+1

**Comment by gamecss** [comment]
+1
@cpackham

**Comment by cpackham** [comment]
@gamecss please feel free to do the work and submit a PR, that's how free/libre/opensource software works. Commenting with +1 is as useful as trying to solve an algebra equation by chewing bubble-gum.

**Comment by gamecss** [comment]
> @gamecss please feel free to do the work and submit a PR, that's how free/libre/opensource software works. Commenting with +1 is as useful as trying to solve an algebra equation by chewing bubble-gum.

https://android.googlesource.com/platform/bionic
is any method to using this source?

**Comment by gamecss** [comment]
> @gamecss please feel free to do the work and submit a PR, that's how free/libre/opensource software works. Commenting with +1 is as useful as trying to solve an algebra equation by chewing bubble-gum.

the repository is ready: [gamecss/crosstool-ng](https://github.com/gamecss/crosstool-ng)
but some wrong in step 'Installing final gcc compiler'
likely:
```
error: expected ',' or ';' before '__asm__'
error: conflicting types for 'ioctl'; have 'int(int,  unsigned int, ...)'
error: no include path in which to search for stdlib.h
```
Can you have a review?thanks

**Comment by cpackham** [comment]
We've elected to go the other way and drop support for bionic #1679. Realistically in order to support bionic work would need to be done in upstream GCC and no-one appears interested in doing that. There may be a future where ct-ng supports building llvm/clang in addition to GCC which would be a path forward for re-introducing support for bionic.

**Comment by cpackham** [comment]
I'm closing this now as we've dropped the existing support for bionic. I wouldn't object to someone submitting a PR for supporting bionic as a C library built from source but I'm not going to spend any time on it myself.
