### ISSUE TITLE
Cut new release (last release from 2019)

### ISSUE THREAD

**Issue by paulmenzel** [crosstool-ng/crosstool-ng#1477]
The last/current release 1.24.0 is from 2019. For projects depending on releases, it’d be great if a new release could be made. Just doing time based releases with no promises would help most of the projects.

**Comment by cpackham** [comment]
I have been thinking about cutting a release but I need to sort out some details first. I'd also really like to get some traction on the 2 pass gcc build (#808) and make that the big new feature.

**Comment by abrodkin** [comment]
@galak just FYI if you'd like something special to be included in the discussed release.

**Comment by Bensuperpc** [comment]
It would be a good idea to do a new version, GCC11 support would be perfect for dockcross ^^

**Comment by qhaas** [comment]
I have been using 1.24.0 since it is the latest tagged (a general rule I follow for most FOSS projects), is most of the community just using the head of master these days?

**Comment by bensuperpc** [comment]
> I have been using 1.24.0 since it is the latest tagged (a general rule I follow for most FOSS projects), is most of the community just using the head of master these days?

Some things are not available with this version, I am using the master branch for this reason, but not the last commit, to avoid some problems.
It's better to use a stable version but not too much choice on my projects :/

**Comment by benesch** [comment]
@cpackham, does #1625 move the needle here at all? The current stable release of crosstool-ng is broken out of the box since the isl tarballs moved. I know it wouldn't be a very exciting release without the 2-pass GCC build, but I'd personally take a functional stable release over an exciting one. :)

**Comment by paulmenzel** [comment]
For the record: https://github.com/crosstool-ng/crosstool-ng/releases/tag/crosstool-ng-1.25.0
