### ISSUE TITLE
Companion Newlib nano libs make built toolchain non-relocatable

### ISSUE THREAD

**Issue by abrodkin** [crosstool-ng/crosstool-ng#1491]
With https://github.com/crosstool-ng/crosstool-ng/pull/1447 we may now build & install Newlib (and in fact `libstdc++` as well) optimized by size along with the "normal" Newlib. But the way it is done now make toolchain non-usable if it was moved to another location, or we may call it non-relocatable.

That's because we hard-code paths in the top-level `nano.specs` that way:
```bash
    cat > "${CT_SYSROOT_DIR}/lib/nano.specs" <<EOF
%rename link	newlib_nano_link
%rename cpp	newlib_nano_cpp
%rename cc1plus	newlib_nano_cc1plus
*cpp:
-isystem ${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/include %(newlib_nano_cpp)
*cc1plus:
-idirafter ${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/include %(newlib_nano_cc1plus)  
*link:
-L${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/lib/%M -L${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/lib
EOF
```

Obviously `${CT_PREFIX_DIR}` & `${CT_TARGET}` get resolved in build-time and we get in the resulting `nano.specs` something like:
```
*cpp:
-isystem ...MY_CTNG_BUILD_LOCATION.../arc-multilib-elf32/newlib-nano/arc-multilib-elf/include %(newlib_nano_cpp)

*cc1plus:
-idirafter ...MY_CTNG_BUILD_LOCATION.../arc-multilib-elf32/newlib-nano/arc-multilib-elf/include %(newlib_nano_cc1plus)··

*link:
-L...MY_CTNG_BUILD_LOCATION.../arc-multilib-elf32/newlib-nano/arc-multilib-elf/lib/%M -L...MY_CTNG_BUILD_LOCATION.../arc-multilib-elf32/newlib-nano/arc-multilib-elf/lib
```

If we move toolchain, those paths become irrelevant and linker fails to find what's needed -> fail :(

If we want to keep Newlib's "nano" version separately the following hack with run-time path calculation seem to work.
Though I'm not sure if there're any side-effects we might get, so @keith-packard @cpackham your input here is very welcome!

```patch
diff --git a/scripts/build/companion_libs/350-newlib_nano.sh b/scripts/build/companion_libs/350-newlib_nano.sh
index 28992c0e..4cbfd71b 100644
--- a/scripts/build/companion_libs/350-newlib_nano.sh
+++ b/scripts/build/companion_libs/350-newlib_nano.sh
@@ -199,13 +199,13 @@ ENABLE_TARGET_OPTSPACE:target-optspace
 %rename cc1plus        newlib_nano_cc1plus

 *cpp:
--isystem ${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/include %(newlib_nano_cpp)
+-isystem %:getenv(GCC_EXEC_PREFIX ../../newlib-nano/${CT_TARGET}/include) %(newlib_nano_cpp)

 *cc1plus:
--idirafter ${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/include %(newlib_nano_cc1plus)
+-idirafter %:getenv(GCC_EXEC_PREFIX ../../newlib-nano/${CT_TARGET}/include) %(newlib_nano_cc1plus)

 *link:
--L${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/lib/%M -L${CT_PREFIX_DIR}/newlib-nano/${CT_TARGET}/lib
+-L%:getenv(GCC_EXEC_PREFIX ../../newlib-nano/${CT_TARGET}/lib/%M) -L%:getenv(GCC_EXEC_PREFIX ../../newlib-nano/${CT_TARGET}/lib)

 EOF
```

**Comment by stephanosio** [comment]
Should this be closed since #1495 was merged?

**Comment by abrodkin** [comment]
@stephanosio right, this one might be closed... though https://github.com/crosstool-ng/crosstool-ng/pull/1495 kinda "inverted" the problem: with it toolchain is not usable with nano-libs unless it is moved to another location.
The problem is `GCC_EXEC_PREFIX` is only defined if toolchain was moved from its build path :(

**Comment by stephanosio** [comment]
> The problem is `GCC_EXEC_PREFIX` is only defined if toolchain was moved from its build path

Could you elaborate?

Looking at the gcc source code, `GCC_EXEC_PREFIX` should always be defined:
https://github.com/gcc-mirror/gcc/blob/98d7f305d5081bc91c16b9d2b4d62196b86bca86/gcc/gcc.c#L4717-L4727

**Comment by badcf00d** [comment]
> The problem is `GCC_EXEC_PREFIX` is only defined if toolchain was moved from its build path :(

This does seem to be the case, if you try using these spec files with the toolchain still in it's build path you'll get a `fatal error: environment variable 'GCC_EXEC_PREFIX' not defined`.

Just renaming the directory fixes that error, so I guess that code in gcc fails, or is skipped or something if it's in the original build path.

**Comment by keith-packard** [comment]
Yup. I submitted a patch upstream to allow getenv to have another argument to be used as the default value when the variable was unset, thinking that this would be the 'safest' way to allow the use of getenv in specs files (you'd provide the configured exec_prefix as that default in this case). Haven't heard anything about my patch; maybe I'll go poke again.

**Comment by abrodkin** [comment]
> Yup. I submitted a patch upstream to allow getenv to have another argument to be used as the default value when the variable was unset, thinking that this would be the 'safest' way to allow the use of getenv in specs files (you'd provide the configured exec_prefix as that default in this case). Haven't heard anything about my patch; maybe I'll go poke again.

@keith-packard could you please share a reference to that patch so that it's linked here?

**Comment by keith-packard** [comment]
https://github.com/keith-packard/gcc/tree/getenv-default

**Comment by abrodkin** [comment]
Ok, for the record, here's the same patch in the GCC mailing list: https://gcc.gnu.org/pipermail/gcc-patches/2022-August/600452.html.

@keith-packard are you going to submit a PR for Crosstool-NG applying that patch for GCC while it's not yet accepted upstream?

**Comment by keith-packard** [comment]
> @keith-packard are you going to submit a PR for Crosstool-NG applying that patch for GCC while it's not yet accepted upstream?

Yeah, I had hoped that would land upstream after another round or two of review so ct-ng could use the 'real' solution.
