### ISSUE TITLE
Question: Can we disable progress animation?

### ISSUE THREAD

**Issue by Animeshz** [crosstool-ng/crosstool-ng#1497]
I'd like to build a toolchain in environment recording the output of build for future reference, and it doesn't support deletion/replacement of the line, and it seems it is polluting 300k+ lines of unnecessary repeating pattern.

![image](https://user-images.githubusercontent.com/26714676/115574442-40975b80-a2df-11eb-8fb0-2cc031580f04.png)

Is there any option to disable the animation?

**Comment by cpackham** [comment]
Yes unset CT_LOG_PROGRESS_BAR

**Comment by Animeshz** [comment]
Oh sorry for the stupid question then, but can I find any documentation related to available options that I can refer to in the web? I'm not able to find any docs even by typing `CT_LOG_PROGRESS_BAR` on the search bar 😅😅😅
