### ISSUE TITLE
crosstool 1.20.0 fails second stage gcc compile- segmentation fault

### ISSUE THREAD

**Issue by ahonkan** [crosstool-ng/crosstool-ng#15]
Hi

I'm getting segmentation fault when the tool is performing the second pass of core C compiler.  I used the tool to build arm-unknown-eabi and armv6-rpi-linux-gnueabi.  I cannot upload the log files, so I'll attach them as comments to this issue.

I'm running on Mac OSX Mavericks running VirtualBox 4.3.18 with
Linux ubuntu64 3.13.0-37-generic #64-Ubuntu SMP Mon Sep 22 21:28:38 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux

gcc -v 
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.8/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 4.8.2-19ubuntu1' --with-bugurl=file:///usr/share/doc/gcc-4.8/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.8 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.8 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-libmudflap --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.8-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.8-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.8.2 (Ubuntu 4.8.2-19ubuntu1)

**Comment by bhundven** [comment]
Not really much I can do with an internal compiler error (ICE).
One thing I'd try (but my macbook pro needs a new logic board) is to try getting the latest git clone of crosstool-ng and trying again. If you still have a problem, I'd probably start talking to the gcc-help <at> gcc.gnu.org mailing list about the internal compiler error.

**Comment by bhundven** [comment]
I'm closing this issue as a bug should be opened with the gcc folks.
If you find something in crosstool-ng that is causing this, please reopen this issue.
