### ISSUE TITLE
incompatibility between generated libz.a  with the rest

### ISSUE THREAD

**Issue by Freddie322** [crosstool-ng/crosstool-ng#1503]
Version 1.24.0
On an Raspberry Pi 4B running a 64-bit Ubuntu Server 20.04 LTS
The target is  Rapberry PI 3 32-bit  : armv7-rpi2-linux-gnueabi
With menuconfig l  choose to let the compiler decide for floating point.

Hello world works  but:
a) The libz.a and zlib.h are not installed on \~/x-tools/armv7-rpi2-linux-gnueabi
b)when I  find them on /Volumes/Data/pi/crosstool-ng/.build/armv7-rpi2-linux-gnueabi/buildtools/lib/libz.a
it gives:
ubuntu@ubuntu:\~/x-tools/armv7-rpi2-linux-gnueabi$ ./bin/armv7-rpi2-linux-gnueabi-nm /Volumes/Data/pi/crosstool-ng/.build/armv7-rpi2-linux-gnueabi/buildtools/lib/libz.a
./bin/armv7-rpi2-linux-gnueabi-nm: adler32.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: crc32.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: deflate.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: infback.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: inffast.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: inflate.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: inftrees.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: trees.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: zutil.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: compress.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: uncompr.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: gzclose.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: gzlib.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: gzread.o: file format not recognized
./bin/armv7-rpi2-linux-gnueabi-nm: gzwrite.o: file format not recognized

Someone has an idea what can I do  to fix this?
Thanks in  advanced
Fred
PS: before this I tried with armv7-rpi2-linux-gnueabihf with the same symptoms.

[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/6421106/build.log.zip) 
[config - copie.txt](https://github.com/crosstool-ng/crosstool-ng/files/6420305/config.-.copie.txt)

**Comment by cpackham** [comment]
`/Volumes/Data/pi/crosstool-ng/.build/armv7-rpi2-linux-gnueabi/buildtools/lib/libz.a` is natively compiled for the build host. You'll need to cross-compile zlib for your target and link against that.

**Comment by Freddie322** [comment]
Thank you for your reply, I just try to understand, can you tel me please cpackam, in this case what is the purpose of companion libraries? 
I tried four different targets, they have all companion libraries that I can add or remove by the menu, they are all built for local host?

**Comment by cpackham** [comment]
I agree it is a bit unintuitive. zlib in particular doesn't have the recipe for building for the target. Some others do (e.g. ncurses, libelf).

It looks like the companion libraries support is a bit incomplete. [The note in comp_libs.in](https://github.com/crosstool-ng/crosstool-ng/blob/0528a9d744cc95aac3df40d5a1666f0a1051cf5d/config/comp_libs.in#L24) lists some of the intentions but there's nothing actually implementing it.

It probably wouldn't be too hard to support building zlib for the target. Care to give it a try?

**Comment by Freddie322** [comment]
I used the crosstool for a few days only, I need to understand more about before adding something that works, I will try...
