### ISSUE TITLE
Hi there I am having an issue during gcc build

### ISSUE THREAD

**Issue by anupgp** [crosstool-ng/crosstool-ng#1514]
I am using branch/version esp-2020r3 for ESP32 build
>> lsb_release -a
LSB Version:    n/a
Distributor ID: openSUSE
Description:    openSUSE Leap 15.2
Release:        15.2
Codename:       n/a
>> uname -a
Linux pickachu 5.3.18-lp152.66-preempt #1 SMP PREEMPT Tue Mar 2 13:18:19 UTC 2021 (73933a3) x86_64 x86_64 x86_64 GNU/Linux

I also had issue with expat version, but that I fixed by changing the version number in expat.in

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/6516867/build.log)

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/6516881/config.txt)

### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by cpackham** [comment]
That's espressif's fork. You should report your issue at https://github.com/espressif/crosstool-NG/issues if you do have an issue on current master feel free to update this issue.

**Comment by FrederickDoering** [comment]
I think your build log indicates that you didn't define the endianness of your target.

**Comment by cpackham** [comment]
Bug should be reported to espressif. If you can reproduce it on master feel free to open a new issue.
