### ISSUE TITLE
[Question] Can I build a toolchain for arm on x86-64

### ISSUE THREAD

**Issue by msilletti** [crosstool-ng/crosstool-ng#1516]
### Issue submission guidelines
- Report crosstool-NG version, latest git
- Report host OS and its version, Ubuntu 21.04 64-bit Linux

I would like to build a toolchain for Raspberry Pi OS using my more powerful Intel desktop running Ubuntu 21.04 64-bit. Can I use a `.config` targeted at arm like `armv7-rpi2-linux-gnueabihf` and build on my x86-64 machine?

**Comment by graysky2** [comment]
Yes, your build host is what you want whatever target to run on.  It is expected that you will build armv7 on your x86-64 box.  If you build armv7 on the armv7 box, and copy that over the x86-64 box, it will throw exec format errors.
