### ISSUE TITLE
Tried building from source failed multiple times during the ./configure step

### ISSUE THREAD

**Issue by tbandtg** [crosstool-ng/crosstool-ng#1529]
checking for GNU libtool >= 2.4... no   Ubuntu 20.04
configure: error: Required tool not found: libtool

However; Libtool is installed.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libtool is already the newest version (2.4.6-14).
The following packages were automatically installed and are no longer required:
  linux-headers-5.8.0-43-generic linux-hwe-5.8-headers-5.8.0-43
  linux-image-5.8.0-43-generic linux-modules-5.8.0-43-generic
  linux-modules-extra-5.8.0-43-generic
Use 'sudo apt autoremove' to remove them.
0 upgraded, 0 newly installed, 0 to remove and 1 not upgraded.

**Comment by cpackham** [comment]
Could you attach your config.log and the output of `libtool --version`

**Comment by cpackham** [comment]
Actually I think the problem is you need to install `libtool-bin`. In debian/ubuntu the libtool binary is not in the `libtool` package (strange but true).

**Comment by tbandtg** [comment]
That was it thanks much!!
