### ISSUE TITLE
Need to use -fcommon flag for old versions of Glibc if using GCC11

### ISSUE THREAD

**Issue by nikkon-dev** [crosstool-ng/crosstool-ng#1535]
Starting from GCC10, GCC enables `-fno-common` by default, which breaks the build of old versions of GLibc (supposedly versions <2.30).

I was able to build Glibc 2.19 on ppc64le using GCC11 with the following flags: 
`CT_GLIBC_EXTRA_CFLAGS="-mcpu=power8 -fcommon -Wno-missing-attributes -Wno-array-bounds -Wno-array-parameter -Wno-stringop-overflow -Wno-maybe-uninitialized"`
On aarch64 and Glibc 2.27: 
`CT_GLIBC_EXTRA_CFLAGS="-fcommon -Wno-missing-attributes -Wno-array-bounds -Wno-array-parameter -Wno-stringop-overflow -Wno-maybe-uninitialized"`

All the `-Wno...` flags were obvious to add - GCC11 complained in an obvious way, but without `-fcommon`, the linker failed due to an unclear reason (some sections were duplicated, but that was not visible in the build.log itself).

I'd suggest enabling `-fcommon` by default for all GLibc versions older than 2.30 (or 2.29, need to double-check) and GCC versions >= 10.0.

I only tested GCC11 (as I skipped GCC10 entirely), but the default behavior was changed in GCC10, so I assume it's also affected.

* Crosstool-NG version tested: 5ab29fbf3e4e4dbd7
* HostOS: Ubuntu 20.04

**Comment by nikkon-dev** [comment]
@Floessie, could you check if my solution above solves your issues with building Glibc <2.30 on PowerPC?

**Comment by Floessie** [comment]
@nikkon-dev Good catch! :+1: I tested a `powerpc-e500v2-linux-gnu` build with GLIBC 2.29 (and Sun RPC) and GCC 11.1. It fails with the stock configuration but succeeds with `-fcommon`. I didn't build a rootfs, though, so the `scanf()` problem in [#1500](https://github.com/crosstool-ng/crosstool-ng/issues/1500#issuecomment-833296115) might be present, too.

**Comment by cpackham** [comment]
Yeah I tend to agree. Either we disallow older glibcs with gcc > 10 or as
you suggest add -fcommon. The latter is probably preferable. Care to give
it a go?

**Comment by cpackham** [comment]
Fixed by #1539

**Comment by Floessie** [comment]
@nikkon-dev @cpackham Thanks! Good job! :+1:
