### ISSUE TITLE
Error compiling binutils on Ubuntu docker host for Raspberry Pi Zero target

### ISSUE THREAD

**Issue by RogerDevil** [crosstool-ng/crosstool-ng#1536]
I think I'm having issue with my build system rather than crosstool-ng itself, but would really appreciate any help you could give.
I raised issue #1519 while trying to build the cross compile toolchain on a M1 MacBook Pro host. Since then, I've tried to install run Ubuntu in Docker, and use that as the host for building the toolchain instead. I managed to get a little further with this configuration, but so far, I have been unable to get beyond building binutils. Every time I tried re-running `ct-ng build`, the build process terminates at a slightly different spot in binutils. Below are logs from 2 such attempts

Try 1:
<img width="677" alt="Screenshot 2021-06-20 at 18 39 26" src="https://user-images.githubusercontent.com/84814727/122831722-36470d00-d2e2-11eb-9480-87bac48a255e.png">
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/6689665/build.log)

Try 2:
<img width="709" alt="Screenshot 2021-06-21 at 22 06 26" src="https://user-images.githubusercontent.com/84814727/122831908-78704e80-d2e2-11eb-9b2e-6cfe12a9ebab.png">
[build2.log](https://github.com/crosstool-ng/crosstool-ng/files/6689674/build2.log)

- crosstool-ng v1.24.0.373_5ab29fb (built from source)
- Ubuntu 20.04 in a Docker (v3.4.0) container acting as the host, running on macOS v11.4 Big Sur on a M1 Mac.
- Installed Ubuntu packages can be found from 
[Dockerfile.txt](https://github.com/crosstool-ng/crosstool-ng/files/6689689/Dockerfile.txt)
- Used build config for `armv6-unknown-linux-gnueabihf`

**Comment by RogerDevil** [comment]
Fixed it by increasing the amount of RAM available to the docker container.

**Comment by ProBackup-nl** [comment]
@RogerDevil Which amount of RAM was too little? And which amount of RAM was enough to build?
