### ISSUE TITLE
Build failed in step 'Extracting and patching toolchain components'

### ISSUE THREAD

**Issue by nyckmaia** [crosstool-ng/crosstool-ng#1540]
## Build failed in step 'Extracting and patching toolchain components'
Sumary:
```
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting linux-4.20.8
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: CT_Extract[scripts/functions@2187]
[ERROR]  >>        called from: CT_DoExtractPatch[scripts/functions@2275]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
[ERROR]  >>        called from: CT_ExtractPatch[scripts/functions@2399]
[ERROR]  >>        called from: do_kernel_extract[scripts/build/kernel/linux.sh@41]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@664]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 36:25.02)
[36:41] / make: *** [/usr/bin/ct-ng:261: build] Error 2
```

Obs.: I had to modify the `.config` file to be able to download the `expat` (the original `2.2.6` version give me a `404 - NOT FOUND` response). So I replaced the `2.2.6` download link to the newest `2.4.1` and now the `ct-ng build` get this package with success.

**CrossTool-Ng version:** 1.24.0 - Built for x86_64-pc-msys (I got it from `MSYS2`)
**Host OS:** Windows 10 x64
**Target/sample used:** arm-unknown-linux-gnueabi

Here are the 2 files attached:

[ct_log.txt](https://github.com/crosstool-ng/crosstool-ng/files/6711476/ct_log.txt)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/6711477/config.txt)

**Please, could you help me? How can I fix it?**

**Comment by nikkon-dev** [comment]
Hello,
The 1.24.0 version was released in 2019, and some packages have been deprecated/removed since then.
The easiest way would be to get and build ct-ng from the master branch.
Expat 2.2.6 was removed from upstream due to vulnerabilities, and you need to use 2.4.1 now.
Linux kernel should be 4.20.17 instead of 4.20.8.
I believe there are a bunch of other packages that were slightly updated or changed their upstream location (e.g., moved from Sourceforge to Github).

**Comment by nyckmaia** [comment]
Great! Thank you!
