### ISSUE TITLE
RE: libtool not being available for a required tool on Debian Buster for ./configure --

### ISSUE THREAD

**Issue by silver2row** [crosstool-ng/crosstool-ng#1541]
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short: configure: error: Required tool not found: libtool

    Reading package lists... Done
    Building dependency tree        
    Reading state information... Done
    libtool is already the newest version (2.4.6-9).
    0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.

- Report crosstool-NG version: Master
- Report host OS and its version: Debian Buster
- uname -a: 4.19.0-16-amd64 #1 SMP Debian 4.19.181-1

**Comment by cpackham** [comment]
See https://github.com/crosstool-ng/crosstool-ng/issues/1529

Short version is that the package is called 'libtool-bin' under debian (and
derivatives)

**Comment by silver2row** [comment]
Hello...thank you. libtool-bin. Okay. 

Seth
