### ISSUE TITLE
Building for multilib 1/1: ''  Configuring C library  configure: error:

### ISSUE THREAD

**Issue by xxinjiang** [crosstool-ng/crosstool-ng#1544]
**The verion of crosstool-ng used in my centOs 7 is 1.24.0,with all configure are default,and my used sample is cortex-a8.By default,after ct-ng build,all the retrived sources were no errors.But I also met the error,and I searched in the google found no describe and answer.I apriciate all you can give me some guidances.Fellow is the issue:**

[INFO ]  Installing pass-1 core C gcc compiler: done in 933.90s (at 28:19)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 23.24s (at 28:42)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[ERROR]      configure: error: 
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library headers & start files'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@263]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1586]
[ERROR]  >>        called from: glibc_backend[scripts/build/libc/glibc.sh@74]
[ERROR]  >>        called from: glibc_start_files[scripts/build/libc/glibc.sh@38]
[ERROR]  >>        called from: do_libc_start_files[scripts/build/libc.sh@28]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/

**Comment by nikkon-dev** [comment]
Hi, please attach the build.log. 
The console output is not enough to diagnose the issue.

**Comment by xxinjiang** [comment]
thank you !I will attach.

**Comment by xxinjiang** [comment]
> Hi, please attach the build.log.
> The console output is not enough to diagnose the issue.

Thanks!I an all appritiate with you for pointing me.I viewed the build.log,and found that my make version was old,so later I'll updating my make'version.And attach my trying's result.

**Comment by xxinjiang** [comment]
> Hi, please attach the build.log.
> The console output is not enough to diagnose the issue.

Thanks!I an all appritiate with you for pointing me.I viewed the build.log,and found that my make version was old,so later I'll updating my make'version.And attach my trying's result.

Thanks!I an all appritiate with you for pointing me.I viewed the build.log,and found that my make version was old,so later I'll updating my make'version.And attach my trying's result.
