### ISSUE TITLE
Cannot build gcc version 4.9.4 pass1 on arch linux 

### ISSUE THREAD

**Issue by rcatolino** [crosstool-ng/crosstool-ng#1549]
The c++ compiler on arch linux defaults to c++17 and fails to compile gcc 4.9.4
I eventually got my toolchain built by sneaking a `-std=gnu++11` in `buildtools/bin/x86_64-build_pc-linux-gnu-g++` but that's not a very satisfying solution.
Is there a way to force a specific standard for the build compiler ? I've tried to use `EXTRA_CFLAGS_FOR_BUILD=-std=gnu++11` for that purpose but these flags are also given to gcc, which then complains that it's not a valid option for C code.
 
- Report crosstool-NG version : 1.24.0
- Report host OS and its version : arch linux with gcc 11.1.0
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/6768372/config.

```
[INFO ]  Installing pass-1 core C gcc compiler
[ERROR]    /home/raph/toolchain/crosstool/.build/arm-unknown-linux-gnueabi/src/gcc/gcc/reload1.c:89:24: error: use of an operand of type 'bool' in 'operator++' is forbidden in C++17
[ERROR]    make[2]: *** [Makefile:1058: reload1.o] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [Makefile:3955: all-gcc] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@684]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc/gcc.sh@209]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 4:44.25)
[04:45] / make: *** [/usr/bin/ct-ng:261 : build] Erreur 2

```

**Comment by cpackham** [comment]
Currently there is no way of setting `CXXFLAGS` in a way that will help this situation. Internally we do pass `CXXFLAGS_FOR_BUILD` when building gcc but this is set to be the same as `CFLAGS_FOR_BUILD` so this could be done if someone wanted to contribute a PR to do so.
