### ISSUE TITLE
Building with bionic fails for api levels 21, 22 and 23 after 1.24

### ISSUE THREAD

**Issue by abraaocsantana** [crosstool-ng/crosstool-ng#1553]
I could build on 1.24 , but for some reason large file support is set for those Api Levels now.

I've submited a fix https://github.com/crosstool-ng/crosstool-ng/pull/1552

- crosstool-NG version : master @ 1.24.0.390_62e9db2
- host OS : Ubuntu 20.04.2 LTS

**Comment by cpackham** [comment]
Could you include the error you get. Even if you have a fix it'll help future searchers.

**Comment by abraaocsantana** [comment]
Hey @cpackham ! Sorry, I was rushing a lot this week nad totally forgot to include the error and explain the problem.

The relevant section of the log:

`[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/bits/basic_string.h:6545,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/string:55,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/stdexcept:39,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/system_error:41,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/bits/fs_fwd.h:35,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/filesystem:44,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/src/gcc/libstdc++-v3/src/c++17/fs_dir.cc:30,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/src/gcc/libstdc++-v3/src/c++17/cow-fs_dir.cc:26:
[ERROR]    /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/cstdio:107:11: error: 'fgetpos' has not been declared in '::'
[ALL  ]      107 |   using ::fgetpos;
[ALL  ]          |           ^~~~~~~
[ERROR]    /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/cstdio:117:11: error: 'fsetpos' has not been declared in '::'
[ALL  ]      117 |   using ::fsetpos;
[ALL  ]          |           ^~~~~~~
[ALL  ]    In file included from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/ext/string_conversions.h:43,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/bits/basic_string.h:6545,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/string:55,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/stdexcept:39,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/system_error:41,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/bits/fs_fwd.h:35,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/filesystem:44,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/src/gcc/libstdc++-v3/src/c++17/fs_dir.cc:30:
[ERROR]    /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/cstdio:107:11: error: 'fgetpos' has not been declared in '::'
[ALL  ]      107 |   using ::fgetpos;
[ALL  ]          |           ^~~~~~~
[ERROR]    /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/cstdio:117:11: error: 'fsetpos' has not been declared in '::'
[ALL  ]      117 |   using ::fsetpos;
[ALL  ]          |           ^~~~~~~
[ALL  ]    In file included from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/ext/string_conversions.h:43,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/bits/basic_string.h:6545,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/string:55,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/stdexcept:39,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/system_error:41,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/bits/fs_fwd.h:35,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/filesystem:44,
[ALL  ]                     from /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/src/gcc/libstdc++-v3/src/c++17/fs_ops.cc:32:
[ERROR]    /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/cstdio:107:11: error: 'fgetpos' has not been declared in '::'
[ALL  ]      107 |   using ::fgetpos;
[ALL  ]          |           ^~~~~~~
[ERROR]    /home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/include/cstdio:117:11: error: 'fsetpos' has not been declared in '::'
[ALL  ]      117 |   using ::fsetpos;
[ALL  ]          |           ^~~~~~~
[ERROR]    make[6]: *** [Makefile:570: cow-fs_dir.lo] Error 1
[ERROR]    make[6]: *** Waiting for unfinished jobs....
[ERROR]    make[6]: *** [Makefile:570: fs_dir.lo] Error 1
[ERROR]    make[6]: *** [Makefile:570: fs_ops.lo] Error 1
[ALL  ]    make[6]: Leaving directory '/home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/src/c++17'
[ERROR]    make[5]: *** [Makefile:731: all-recursive] Error 1
[ALL  ]    make[5]: Leaving directory '/home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3/src'
[ERROR]    make[4]: *** [Makefile:563: all-recursive] Error 1
[ALL  ]    make[4]: Leaving directory '/home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3'
[ERROR]    make[3]: *** [Makefile:488: all] Error 2
[ALL  ]    make[3]: Leaving directory '/home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final/arm-unknown-linux-androideabi/libstdc++-v3'
[ERROR]    make[2]: *** [Makefile:11349: all-target-libstdc++-v3] Error 2
[ALL  ]    make[2]: Leaving directory '/home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final'
[ERROR]    make[1]: *** [Makefile:960: all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/abraao.santana/zoop/crosstool-ng-worspace/rst1/.build/arm-unknown-linux-androideabi/build/build-cc-gcc-final'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/gcc.sh@1294]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc/gcc.sh@922]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@695]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 11:01.32)
`
This happens if you enable C++ , build with Bionic, and have Api Level < 24 . I guess this also happens only with NDK >= r15 (untested) , as through investigation the info I got was that ndks below r15 just ignored the problem.

The issue seems to be that Api Level < 24 doesn't have implementations for large files (64 bit) , so when _FILE_OFFSET_BITS is set to 64 and Api Level < 24 fgetpos, fsetpos, fseeko and ftello are not defined.

You can see that by going to android-ndk-rxxx/sysroot/usr/include/stdio.h and watching the condition when those symbols are defined also ( __USE_FILE_OFFSET64 is a internal var that is defined if _FILE_OFFSET_BITS is set to 64 ) 

It's a known issue, bionic docs asks to stop defining  _FILE_OFFSET_BITS to 64 if you get the issue when using anything above r15: https://android.googlesource.com/platform/bionic/+/master/docs/32-bit-abi.md 

Clang builds seem to get around this by using libandroid_support on those cases ( https://github.com/android/ndk/issues/480 ) which is not available when building the gnu std c++.

**Comment by cpackham** [comment]
We've elected to drop support for bionic https://github.com/crosstool-ng/crosstool-ng/pull/1679.
