### ISSUE TITLE
Build failed in step 'Installing binutils for host'

### ISSUE THREAD

**Issue by mohannadmaklad** [crosstool-ng/crosstool-ng#1557]
Crosstool-NG version 1.24.0
Host os : Ubuntu (Using windows 11 wsl)

log error : 

[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    /home/mohannad/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/src/binutils/gold/errors.h:87:50: error: 'string' in namespace 'std' does not name a type
[ERROR]    make[5]: *** [Makefile:1133: descriptors.o] Error 1
[ERROR]    make[5]: *** Waiting for unfinished jobs....
[ERROR]    /home/mohannad/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/src/binutils/gold/errors.h:87:50: error: 'string' in namespace 'std' does not name a type
[ERROR]    make[5]: *** [Makefile:1133: dirsearch.o] Error 1
[ERROR]    make[4]: *** [Makefile:1156: all-recursive] Error 1
[ERROR]    make[3]: *** [Makefile:896: all] Error 2
[ERROR]    make[2]: *** [Makefile:6045: all-gold] Error 2
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [Makefile:850: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@206]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@70]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@696]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/

**Comment by mohannadmaklad** [comment]
log file : 
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/6797546/build.log)

**Comment by cpackham** [comment]
I think the problem might be the default C++ standard used by wsl/ubuntu. This may have already been fixed by newer binuntils versions.

Could you try building from master

```
git clone https://github.com/crosstool-ng/crosstool-ng.git
cd crosstool-ng
./bootstrap
./configure
make ...
```

**Comment by mohannadmaklad** [comment]
> I think the problem might be the default C++ standard used by wsl/ubuntu. This may have already been fixed by newer binuntils versions.
> 
> Could you try building from master
> 
> ```
> git clone https://github.com/crosstool-ng/crosstool-ng.git
> cd crosstool-ng
> ./bootstrap
> ./configure
> make ...
> ```

Thanks @cpackham  , actually these are the steps that i followed in the first place but there were some problems with some tarballs that I had to download manually, now it completed binutils successfully.
