### ISSUE TITLE
Expat failed to download

### ISSUE THREAD

**Issue by TheBlueOompaLoompa** [crosstool-ng/crosstool-ng#1576]
Version: 1.24.0
Host OS: Artix Linux(Runit init) Kernel 5.13.8
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/6984183/config.txt)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/6984192/build.log)

Not at this location: "http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2"
[ERROR]    expat: download failed

**Comment by TheBlueOompaLoompa** [comment]
I just did a search, and it turns out they renamed the file to `expat-2.2.6-RENAMED-VULNERABLE-PLEASE-USE-2.4.1-INSTEAD.tar.bz2`. I understand the package is vulnerable to attack, but the purpose I am using this for permits the use of packages with vulnerabilities because the device I'm building for is a leapster explorer. If anyone knows how to fix this based on the information I have presented that would be helpful, but I think I will just manually edit the config so it uses version 2.4.1 of expat.

**Comment by cpackham** [comment]
See https://github.com/crosstool-ng/crosstool-ng/issues/1479
