### ISSUE TITLE
Dangling libzstd.so.1 in top-of-the-tree build with GCC11.2

### ISSUE THREAD

**Issue by 0x8000-0000** [crosstool-ng/crosstool-ng#1579]
Crosstool-Ng from master branch f322679392930d55fb8a50e7223f39d4bbaeaf3e
Host OS is Ubuntu 18.04 building for RHEL 7.

Building with GCC11.2, I get a libexec/gcc/x86_64-tng-linux-gnu/11.2.1/cc1 binary which links against libzstd.so.1, but this shared object is not present in the toolchain.

**Comment by 0x8000-0000** [comment]
Had to add this to build:

    CT_CC_GCC_EXTRA_CONFIG_ARRAY="--without-zstd"

**Comment by cpackham** [comment]
Looks like gcc's configure must have detected libzstd on the host and decided to use it. If you've still got the build output from the bad case could you attach `.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-final/gcc/config.log` to confirm.

As we don't ship zstd we should probably just say `--without-zstd` unconditionally.

**Comment by 0x8000-0000** [comment]
I don't have that specific log anymore but that is likely what happened.

**Comment by jdknight** [comment]
I got a log showing this state, if it helps: [build-cc-gcc-final/gcc/config.log](https://github.com/crosstool-ng/crosstool-ng/files/7007574/config.log)

(just posting as a reference; I'll be trying with the `--without-zstd` option later)

**Comment by cpackham** [comment]
I've posted a change I think will help with this. In the end I went with an option that will keep the current behavior (i.e. use zstd if it's found) but also allows support to be disabled if the extra dependency is unwanted.
