### ISSUE TITLE
downloading expat failed to download

### ISSUE THREAD

**Issue by 1000283** [crosstool-ng/crosstool-ng#1594]
- crosstool-NG version: at tag crosstool-ng-1.24.0
- Report host OS and its version: `Linux myvm-VirtualBox 4.15.0-129-generic #132~16.04.1-Ubuntu SMP Wed Dec 16 06:46:04 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Attach `.config` (unless the issue is not related to any configuration): nope
- Attach `build.log` (unless crosstool-NG fails before the build starts): this is the relevant bit:
```
1800 [DEBUG]    Testing '-n expat'
1801 [EXTRA]    Retrieving 'expat-2.2.6'
1802 [DEBUG]    Trying 'http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2'
1803 [DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/gesrest/dev/crosstool-ng/.build/tarballs/expat-2.2.6.tar.bz2.tmp-dl' 'http://downloads.so
1804 [ALL  ]    --2021-09-09 12:36:53--  http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2
1805 [ALL  ]    Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
1806 [ALL  ]    Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
1807 [ALL  ]    HTTP request sent, awaiting response... 404 Not Found
1808 [ALL  ]    2021-09-09 12:36:53 ERROR 404: Not Found.
1809 [ALL  ]
1810 [DEBUG]    ==> Return status 8
1811 [DEBUG]    Not at this location: "http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2"
1812 [ERROR]    expat: download failed
1813 [ERROR]
1814 [ERROR]  >>
1815 [ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
1816 [ERROR]  >>        called in step '(top-level)'
1817 [ERROR]  >>
1818 [ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
1819 [ERROR]  >>        called from: CT_DoFetch[scripts/functions@2103]
1820 [ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
1821 [ERROR]  >>        called from: CT_Fetch[scripts/functions@2174]
1822 [ERROR]  >>        called from: do_expat_get[scripts/build/companion_libs/210-expat.sh@12]
1823 [ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
1824 [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]
1825 [ERROR]  >>
1826 [ERROR]  >>  For more info on this error, look at the file: 'build.log'
1827 [ERROR]  >>  There is a list of known issues, some with workarounds, in:
1828 [ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
1829 [ERROR]  >>
1830 [ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
1831 [ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
1832 [ERROR]  >>
1833 [ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
1834 [ERROR]  >>  Read the bug reporting guidelines here:
1835 [ERROR]  >>      http://crosstool-ng.github.io/support/
1836 [ERROR]
1837 [ERROR]  (elapsed: 0:02.44)
```

```
$ wget http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2
--2021-09-09 12:46:15--  http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2
Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 204.68.111.105
Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|204.68.111.105|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2021-09-09 12:46:15 ERROR 404: Not Found.
```

If i try to follow [http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2](http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2) in a browser i get redirected to `https://sourceforge.net/projects/expat/files/`

In the [2.2.6 download page](https://sourceforge.net/projects/expat/files/expat/2.2.6/) there's a warning that this is a vulnerable version and 2.4.1 should be used.

The following link is valid: [http://downloads.sourceforge.net/project/expat/expat/2.4.1/expat-2.4.1.tar.bz2](http://downloads.sourceforge.net/project/expat/expat/2.4.1/expat-2.4.1.tar.bz2).

I see no option in `menuconfig` to provide a direct link for download, but i had seen it before, perhaps the current flags won't allow it. All i'm getting is release tarball, 2.4.1 (after screwing around with `config/versions/expat.in` and `packages/expat/package.desc`), but it's still trying to download 2.2.6.

I'm trying to create a toolchain for the RPi4 based on this [blog post](https://ilyas-hamadouche.medium.com/creating-a-cross-platform-toolchain-for-raspberry-pi-4-5c626d908b9d).

**Comment by 1000283** [comment]
I worked around by removing gdb from debug facilities, then i was able to remove expat.

**Comment by QBos07** [comment]
See #1479

**Comment by cpackham** [comment]
More detail on #1479, disabling gdb, manually downloading expat from the github mirror or using a custom version are all valid workarounds.
