### ISSUE TITLE
error about ct-ng build

### ISSUE THREAD

**Issue by muzhang111** [crosstool-ng/crosstool-ng#1597]
crosstool-NG version  crosstool-ng-1.18.0.tar.bz2
 host OS and its version  ubtune 20.04  x64

I don't know how to deal with this problem. Can you help me?
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/7152990/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/7152997/config.txt)

**Comment by QBos07** [comment]
Just install gcj or disable Java

**Comment by muzhang111** [comment]
Gcj doesn't seem to support downloading. Can you provide a download address

**Comment by QBos07** [comment]
Install GCJ using this
```
sudo apt install gcj 
```
Maybe you need this before
```
sudo apt update 
```

**Comment by QBos07** [comment]
Ps: GCJ is normally part of GCC

**Comment by muzhang111** [comment]
I followed your orders before  sudo apt install gcj   
However, the display cannot locate the package gcj

**Comment by cpackham** [comment]
ct-ng 1.18 is really just too old to support. If you have a problem on latest master or 1.24 then it might get looked at. Other than that sorry you are on your own.

**Comment by muzhang111** [comment]
thank you  I'll do something myself

**Comment by muzhang111** [comment]
![image](https://user-images.githubusercontent.com/37541924/133612542-ae529cd2-c351-4e01-9765-ff2fb0412d3d.png)
its ok

**Comment by QBos07** [comment]
> ![image](https://user-images.githubusercontent.com/37541924/133612542-ae529cd2-c351-4e01-9765-ff2fb0412d3d.png)
> 
> its ok

Now I'm interested how do you solve it?

**Comment by muzhang111** [comment]
Select the highest version of the compiler
