### ISSUE TITLE
sysroot does not contain symlinks to glibc libraries anymore

### ISSUE THREAD

**Issue by sla89** [crosstool-ng/crosstool-ng#1604]
Hello,

I have updated my toolchain from 

* gcc 8.4 to 11.2
* glibc 2.27 to 2.34
* binutils 2.30 to 2.37
* linux kernel has changed from 4.10 to 5.10

The target platform is x86 with 64 bit. 

The old toolchain was built using crosstool-ng 1.24 and now I am using 5f5a22f7a7307790ec571d0c5acf8790416964e6.
Building and running crosstool-ng is executed on a Ubuntu 20.04 x64 machine.

I am not building a multilib (`# CT_MULTILIB is not set`).

Previously with my gcc 8.4 toolchain I had the following files:

```
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libc-2.27.so
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libc.so.6 -> libc-2.27.so
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libcidn-2.27.so
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libcidn.so.1 -> libcidn-2.27.so
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libcrypt-2.27.so
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libcrypt.so.1 -> libcrypt-2.27.so
....
```

The sysroot folder was full of lib*-2.27.so files (e.g. the schema was also the same for libutil, libtr and libm, just to name a few more). In the initial build log I have found this for glibc:

```
mv -f /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc-2.27.so.new /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc-2.27.so
rm -f /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/ld-linux-x86-64.so.2
ln -s `../scripts/rellns-sh -p /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/ld-2.27.so /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/ld-linux-x86-64.so.2` /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/ld-linux-x86-64.so.2
/tmp/crosstool-ng/.build/tools/bin/install -c /tmp/crosstool-ng/.build/x86_64-pc-linux-gnu/build/build-libc-final/multilib/libc.so /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc-2.27.so.new
mv -f /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc-2.27.so.new /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc-2.27.so
rm -f /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc.so.6
ln -s `scripts/rellns-sh -p /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc-2.27.so /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc.so.6` /home/sla89/dev/toolchains/8.4.0/x86_64-pc-linux-gnu/sysroot/lib64/libc.so.6
```

After building the new toolchain with the versions described above the output only contains these files:

```
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libc.so.6
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libc_malloc_debug.so.0
x86_64-pc-linux-gnu/sysroot/lib/../lib64/libcrypt.so.1
```

I would have expected that, e.g. the `libc.so.6` is also a symlink to `libc-2.34.so` and `libc-2.34.so` is the real `.so` file. Also the build log just mentions this (e.g. for libc.so). 

```
rm -f /tmp/crosstool-ng/.build/x86_64-pc-linux-gnu/build/build-libc-final/multilib/libc.so.6.new
/bin/sh ../scripts/rellns-sh /tmp/crosstool-ng/.build/x86_64-pc-linux-gnu/build/build-libc-final/multilib/libc.so /tmp/crosstool-ng/.build/x86_64-pc-linux-gnu/build/build-libc-final/multilib/libc.so.6.new
mv -f /tmp/crosstool-ng/.build/x86_64-pc-linux-gnu/build/build-libc-final/multilib/libc.so.6.new /tmp/crosstool-ng/.build/x86_64-pc-linux-gnu/build/build-libc-final/multilib/libc.so.6
```

As far as I can see the glibc build already did not produce the `libc-2.34.so`. Is this new behaviour by intention or have I messed something up?

I am not sure if this is something that has changed in glibc or crosstool-ng is invoking the glibc build in a different way.

Thank you and with best regards,
Stefan

**Comment by cpackham** [comment]
It's a feature of GNU libc https://sourceware.org/pipermail/libc-announce/2021/000032.html

> * Previously, glibc installed its various shared objects under versioned
>   file names such as libc-2.33.so.  The ABI sonames (e.g., libc.so.6)
>   were provided as symbolic links.  Starting with glibc 2.34, the shared
>   objects are installed under their ABI sonames directly, without
>   symbolic links.  This increases compatibility with distribution
>   package managers that delete removed files late during the package
>   upgrade or downgrade process

They've also combined a number of libraries into the main C library so there's no separate .so file for them.

Is this causing any problem for you or just something you've noticed?

**Comment by sla89** [comment]
Thank you very much for the insight! 

It is something I have noticed because it makes some troubles in my environment. But I will adapt my environment to the new behaviour. :)
