### ISSUE TITLE
build failed while retrieving dependency libs

### ISSUE THREAD

**Issue by roman-rs** [crosstool-ng/crosstool-ng#1609]
crosstool-ng version:
wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.bz2 

host OS:
debian:10.9

.config:
attached

relevant build logs:
```
[EXTRA]    Retrieving 'mpfr-4.0.2'
[EXTRA]    Verifying SHA512 checksum for 'mpfr-4.0.2.tar.xz'
[EXTRA]    Retrieving 'isl-0.20'

[00:32] / 
[00:32] / 
[00:32] / 
[00:32] / 
[00:32] / 
[00:42] / 
[00:42] / 
[00:42] / 
[00:43] / 
[00:53] / 
[00:53] / 
[00:53] / 
[00:55] / 
[01:05] - 
[01:05] - 
[01:05] - 
[01:05] / 
[01:05] / 
[01:05] / 
[01:05] / 
[01:05] / 
[01:05] / 
[01:15] / 
[01:15] / 
[01:15] / 
[01:16] / 
[01:26] / 
[01:26] / 
[01:26] / 
[01:28] / 
[01:38] - 
[01:38] - 
[01:38] - 
[01:38] / 
[01:38] / 
[01:38] / 
[01:38] / 
[01:38] / 
[01:38] / 
[01:48] / 
[01:48] / 
[01:48] / 
[01:49] / 
[01:59] / 
[01:59] / 
[01:59] / 
[02:01] / 
[02:11] - 
[02:11] - 
[02:11] - 
[02:11] / 
[02:12] / 
[ERROR]    isl: download failed
[02:12] / 
[ERROR]  
[02:12] / 
[ERROR]  >>
[02:12] / 
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[02:12] / 
[ERROR]  >>        called in step '(top-level)'
[02:12] / 
[ERROR]  >>
[02:12] / 
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[02:12] / 
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2103]
[02:12] / 
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
[02:12] / 
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2174]
[02:12] / 
[ERROR]  >>        called from: do_isl_get[scripts/build/companion_libs/121-isl.sh@16]
[02:12] / 
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[02:12] / 
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]
[02:12] / 
[ERROR]  >>
[02:12] / 
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[02:12] / 
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[02:12] / 
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[02:12] / 
[ERROR]  >>
[02:12] / 
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[02:12] / 
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[02:12] / 
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[02:12] / 
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[02:12] / 
[ERROR]  >> preferably, a fix.
[02:12] / 
[ERROR]  >>
[02:12] / 
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[02:12] / 
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[02:12] / 
[ERROR]  >>
[02:12] / 
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[02:12] / 
[ERROR]  >>  Read the bug reporting guidelines here:
[02:12] / 
[ERROR]  >>      http://crosstool-ng.github.io/support/
[02:12] / 
[ERROR]  
[02:12] / 
[ERROR]  (elapsed: 2:11.36)
```

I clearly understand that the problem is not directly caused by crosstool-ng, but the build failed because of the dependency library.
But this makes any pipeline unreliable and very fragile.

The issue could be mitigated by
- adding a local mirror for the libs that may fail to download (or cache it somewhere at the crosstool-ng resources).
this approach would require extra space and extra logic (smth like "if the failed to download library, check if we have one in a cache, then use it"
- do not use ISL (?) questionable. most likely it's a required library, then move to another provider of the same lib or fine more stable mirror.

I found issues reported regarding zlib that is pretty much the same RC. if a dependency cannot be fulfilled, either need to find a way to drop it or find a way to have a more robust source for the depencency

**Comment by roman-rs** [comment]
now I'm using git://repo.or.cz/isl.git as a source for the ISL lib and everything works fine.
fortunately, ct-ng allows to customize lib source path and there is repo.or.cz predefined as an alternative to official ISL hosted at http://isl.gforge.inria.fr .

CT_COMP_LIBS_ISL=y
CT_COMP_LIBS_ISL_PKG_KSYM="ISL"
CT_ISL_DIR_NAME="isl"
CT_ISL_PKG_NAME="isl"
# CT_ISL_SRC_RELEASE is not set
CT_ISL_SRC_DEVEL=y
CT_ISL_DEVEL_VCS_git=y
# CT_ISL_DEVEL_VCS_svn is not set
# CT_ISL_DEVEL_VCS_hg is not set
# CT_ISL_DEVEL_VCS_cvs is not set
CT_ISL_DEVEL_VCS="git"
CT_ISL_DEVEL_URL="git://repo.or.cz/isl.git"
CT_ISL_DEVEL_BRANCH=""
CT_ISL_DEVEL_REVISION=""
CT_ISL_DEVEL_SUBDIR=""
CT_ISL_DEVEL_BOOTSTRAP="./autogen.sh"
# CT_ISL_SRC_CUSTOM is not set
CT_ISL_PATCH_GLOBAL=y
# CT_ISL_PATCH_BUNDLED is not set
# CT_ISL_PATCH_LOCAL is not set
# CT_ISL_PATCH_BUNDLED_LOCAL is not set
# CT_ISL_PATCH_LOCAL_BUNDLED is not set
# CT_ISL_PATCH_NONE is not set
CT_ISL_PATCH_ORDER="global"
CT_ISL_VERY_NEW=y
# CT_ISL_V_0_20 is not set
# CT_ISL_V_0_19 is not set
# CT_ISL_V_0_18 is not set
# CT_ISL_V_0_17 is not set
# CT_ISL_V_0_16 is not set
# CT_ISL_V_0_15 is not set
# CT_ISL_NO_VERSIONS is not set
CT_ISL_VERSION="new"
CT_ISL_MIRRORS="http://isl.gforge.inria.fr"
CT_ISL_ARCHIVE_FILENAME="@{pkg_name}-@{version}"
CT_ISL_ARCHIVE_DIRNAME="@{pkg_name}-@{version}"
CT_ISL_ARCHIVE_FORMATS=".tar.xz .tar.bz2 .tar.gz"
CT_ISL_SIGNATURE_FORMAT=""
CT_ISL_later_than_0_18=y
CT_ISL_0_18_or_later=y
CT_ISL_later_than_0_15=y
CT_ISL_0_15_or_later=y
CT_ISL_REQUIRE_0_15_or_later=y
CT_ISL_later_than_0_14=y
CT_ISL_0_14_or_later=y
CT_ISL_REQUIRE_0_14_or_later=y
CT_ISL_later_than_0_13=y
CT_ISL_0_13_or_later=y
CT_ISL_later_than_0_12=y
CT_ISL_0_12_or_later=y
CT_ISL_REQUIRE_0_12_or_later=y

**Comment by cpackham** [comment]
gforge.inria.fr appears to be down a classic case of https://xkcd.com/2347

I'm not aware of any official mirror but you could grab the tarball from the debian package https://deb.debian.org/debian/pool/main/i/isl/ (note debian renames the tarball to isl_0.20.orig.tar.xz but the checksum should still match).

As part of the crosstool-ng CI builds we fetch the tarballs once so you might be able to use https://github.com/crosstool-ng/crosstool-ng/suites/3904694249/artifacts/97548745 but isl has had a couple of version bumps since crosstool-ng-1.24.0.

**Comment by bensuperpc** [comment]
I also confirm this problem:

```
[DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/dockcross/crosstool/toolchain/.build/tarballs/isl-0.24.tar.gz.tmp-dl' 'http://isl.gforge.inria.fr/isl-0.24.tar.gz'
[ALL  ]    --2021-10-04 05:26:05--  http://isl.gforge.inria.fr/isl-0.24.tar.gz
[ALL  ]    Resolving isl.gforge.inria.fr (isl.gforge.inria.fr)... 128.93.193.15
[ALL  ]    Connecting to isl.gforge.inria.fr (isl.gforge.inria.fr)|128.93.193.15|:80... failed: Connection timed out.
[ALL  ]    Retrying.
[ALL  ]    
[ALL  ]    --2021-10-04 05:26:16--  (try: 2)  http://isl.gforge.inria.fr/isl-0.24.tar.gz
[ALL  ]    Connecting to isl.gforge.inria.fr (isl.gforge.inria.fr)|128.93.193.15|:80... failed: Connection timed out.
[ALL  ]    Retrying.
[ALL  ]    
[ALL  ]    --2021-10-04 05:26:28--  (try: 3)  http://isl.gforge.inria.fr/isl-0.24.tar.gz
[ALL  ]    Connecting to isl.gforge.inria.fr (isl.gforge.inria.fr)|128.93.193.15|:80... failed: Connection timed out.
[ALL  ]    Giving up.
[ALL  ]    
[DEBUG]    ==> Return status 4
[DEBUG]    Not at this location: "http://isl.gforge.inria.fr/isl-0.24.tar.gz"
Error:     isl: download failed
Error:   
Error:   >>
Error:   >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
Error:   >>        called in step '(top-level)'
Error:   >>
Error:   >>  Error happened in: CT_Abort[scripts/functions@487]
Error:   >>        called from: CT_DoFetch[scripts/functions@2130]
Error:   >>        called from: CT_PackageRun[scripts/functions@2090]
Error:   >>        called from: CT_Fetch[scripts/functions@2201]
Error:   >>        called from: do_isl_get[scripts/build/companion_libs/121-isl.sh@16]
Error:   >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
Error:   >>        called from: main[scripts/crosstool-NG.sh@649]
Error:   >>
Error:   >>  For more info on this error, look at the file: 'build.log'
Error:   >>  There is a list of known issues, some with workarounds, in:
Error:   >>      https://crosstool-ng.github.io/docs/known-issues/
Error:   >>
Error:   >>  If you feel this is a bug in crosstool-NG, report it at:
Error:   >>      https://github.com/crosstool-ng/crosstool-ng/issues/
Error:   >>
Error:   >>  Make sure your report includes all the information pertinent to this issue.
Error:   >>  Read the bug reporting guidelines here:
Error:   >>      http://crosstool-ng.github.io/support/
Error:   
Error:   (elapsed: 1:48.44)
+ exit 1
The command '/bin/sh -c mkdir /dockcross/crosstool && cd /dockcross/crosstool && /dockcross/install-crosstool-ng-toolchain.sh   -p "${XCC_PREFIX}"   -c "/dockcross/crosstool-ng.config"   -v "${CT_VERSION}" && rm -rf /dockcross/crosstool /dockcross/install-crosstool-ng-toolchain.sh' returned a non-zero code: 1
make: *** [Makefile:213: linux-arm64] Error 1
```

More info:
https://github.com/dockcross/dockcross/runs/3784572809?check_suite_focus=true#step:5:21698

**Comment by cpackham** [comment]
Here's a thread from the isl mailing list that explains what's going on

https://groups.google.com/g/isl-development/c/JGaMo2VUu_8

In short the package hosting is shutting down but there isn't an official
new upstream yet. Various distros have mirrors available.

**Comment by cschol** [comment]
Great. Thank you. Will there be an update for `crosstool-ng` to use one of those new mirrors?

**Comment by BtbN** [comment]
https://github.com/BtbN/FFmpeg-Builds/commit/cbb3adabf7bdae2e8956bdcda766a0815c54e768
That did the trick for me. Mirror only has 0.24, so if you need something older, you need to find a different mirror.

**Comment by cschol** [comment]
Another workaround is to (manually) download `isl-0.24.tar.xz` (for example from https://ftp.halifax.rwth-aachen.de/gentoo/distfiles) into the `CT_LOCAL_TARBALLS_DIR`, which is by default set to `$HOME/src`. That worked for me.

**Comment by rypz79** [comment]
> I change ISL mirror with `CT_ISL_MIRRORS="http://ftp.slackware.com/pub/slackware/slackware64-current/source/l/isl"` it works now.

Can you explain how you did it ?
TNX

**Comment by hardcobble** [comment]
> > I change ISL mirror with `CT_ISL_MIRRORS="http://ftp.slackware.com/pub/slackware/slackware64-current/source/l/isl"` it works now.
> 
> Can you explain how you did it ? TNX
Before running"bin/ct-ng build", Edit the ".config" file(hidden file) under Home/username/crosstool-ng.
Remove 
 CT_ISL_V_0_22=y
CT_ISL_VERSION="0.22"
CT_ISL_MIRRORS="http://isl.gforge.inria.fr"
Add
CT_ISL_V_0_24=y
CT_ISL_VERSION="0.24"
CT_ISL_MIRRORS="https://ftp.halifax.rwth-aachen.de/gentoo/distfiles".
I hope it will help you.
