### ISSUE TITLE
Fast-forward merge  on pull requests

### ISSUE THREAD

**Issue by temap** [crosstool-ng/crosstool-ng#1615]
Hi @cpackham,
Is it possible to change the merge strategy to fast-forward only to avoid merge commits?

The commit history will be clear and linear in this case.

More details here:
https://docs.github.com/en/github/collaborating-with-pull-requests/incorporating-changes-from-a-pull-request/about-pull-request-merges#rebase-and-merge-your-pull-request-commits

**Comment by cpackham** [comment]
Looks like no-one has complained. I've been merging PRs with the rebase-and-merge option for a while so closing this issue.
