### ISSUE TITLE
Error crosstool-NG

### ISSUE THREAD

**Issue by TuanMinh191** [crosstool-ng/crosstool-ng#1618]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
![Screenshot from 2021-10-19 16-15-35](https://user-images.githubusercontent.com/92785267/137880618-3b03dc6b-d21c-49fc-bb2b-2c04dd870b2b.png)

**Comment by GalaxyGorilla** [comment]
1. What's there before this log?
2. Please don't post pictures ...
