### ISSUE TITLE
ERROR ABOUT crosstool-ng-1.24.0

### ISSUE THREAD

**Issue by muzhang111** [crosstool-ng/crosstool-ng#1621]
crosstool-NG version crosstool-ng-1.24.0.tar.bz2
host OS and its version ubtune 20.04 x64

I don't know how to solve the above problems. Can you help me?

[makelog.txt](https://github.com/crosstool-ng/crosstool-ng/files/7385559/makelog.txt)
[Makefile.txt](https://github.com/crosstool-ng/crosstool-ng/files/7385565/Makefile.txt)

**Comment by QBos07** [comment]
I would try to install `bison` and `libtool` since `/usr/share/libtool` is the directory where `libtool` installs it's final libraries.
Then autodetect should work then.
PS: use the latest master, there some critical changes
