### ISSUE TITLE
Resolving download issues (e.g isl-0.20, expat-2.2.6)

### ISSUE THREAD

**Issue by cpackham** [crosstool-ng/crosstool-ng#1625]
## Introduction

This issue documents how to resolve download issues for packages which have moved hosting since crosstool-ng-1.24.0 was released (it will likely remain applicable to future versions as well). This is mainly being done so it can be referred to when duplicate issues are reported

## Example Error

```
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'isl-0.20'
[ERROR]    isl: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2103]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2174]
[ERROR]  >>        called from: do_isl_get[scripts/build/companion_libs/121-isl.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/manual/B_Known_issues.md'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 1:39.53)
[01:39] / make: *** [ct-ng:261: build] Error 1
```

## Fixes

1. Build from master
2. Modify config
3. Pre-downloaded source

### Build from master

The master branch of the crosstool-ng repo has been updated with the current URLs.

```
git clone https://github.com/crosstool-ng/crosstool-ng.git
cd crosstool-ng
./bootstrap
./configure
make
sudo make install
cd ~
ct-ng <sample-name>
ct-ng build
```

### Modify Config

At the time of writing isl now hosts it's source tarballs at https://libisl.sourceforge.io/. The un-renamed expat tarball is available at https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2. To use these new locations we need to configure custom locations for the affected components.

```
curl http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.bz2 | tar -xj
cd crosstool-ng-1.24.0
./configure
make
sudo make install
cd ~
ct-ng <sample-name>
sed -e 's|CT_ISL_MIRRORS=.*$|CT_ISL_MIRRORS="https://libisl.sourceforge.io"|' \
    -e 's|CT_EXPAT_MIRRORS=.*$|CT_EXPAT_MIRRORS="https://github.com/libexpat/libexpat/releases/download/R_2_2_6"|' \
    -i .config
ct-ng build
```

### Pre-download Source

By default crosstool-ng saves the downloaded sources in `~/src`. If the source is already there it won't download it again. We can make use of this by pre-downloading the moved tarballs.

```
mkdir -p ~/src
wget -P ~/src https://libisl.sourceforge.io/isl-0.20.tar.bz2
wget -P ~/src https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.6.tar.bz2
curl http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.24.0.tar.bz2 | tar -xj
cd crosstool-ng-1.24.0
./configure
make
sudo make install
cd ~
ct-ng <sample-name>
ct-ng build
```

**Comment by doubleopinter** [comment]
I ran into an error at
```Retrieving 'expat-2.4.1'```

**Comment by drhax9908** [comment]
can confirm this is an issue, I got it too, It affects pretty much ALL releases of crosstool-ng

**Comment by lnsriravichandran22** [comment]
Can you please what is the place holder <sample-name> meant for? I am stuck at the ct-ng <sample-name> command with Build from master option

**Comment by sametyazici** [comment]
> Can you please what is the place holder meant for? I am stuck at the 'ct-ng ' command with Build from master option

try bin/ct-ng

**Comment by jhgorse** [comment]
When [EXTRA] Retrieving 'component' fails, consider indicating to the user
1. what command with what url failed
2. where that url is set
3. how to modify the url

**Comment by cpackham** [comment]
Now that 1.25 is out with the updated URLs I think we can close this. I'll leave it pinned for a while longer so people will still be able to find it.

**Comment by silver2row** [comment]
Nice!

I really appreciate you guys/gals making the workaround for these errors!

Seth
