### ISSUE TITLE
menuconfig doesn't list glibc > 2.28

### ISSUE THREAD

**Issue by happyalu** [crosstool-ng/crosstool-ng#1631]
I'm using the latest master (25f6dae85e) of crosstool-ng; building it in docker, debian:11. 

Built with ./bootstrap; ./configure; make

When running `ct-ng menuconfig`, I'm able to see and select the latest versions of the linux kernel, binutils, gcc, but the glibc selection only lists 2.28 and older. 

What might I be doing wrong?

**Comment by cpackham** [comment]
Sounds like an unmet dependency or another package that requires 2.28 or older. I can't reproduce your issue when I try the same thing locally.

If you use kconfigs search function (run `ct-ng menuconfig` then press `/` and type `GLIBC_V_2_34` when prompted it should tell you the dependencies (they're mostly auto-generated) and their current selected status.

One trap that's easy to fall in is that it's easy to have a stale `.config` hanging around. Use `ct-ng distclean` to remove it (and the build output).

**Comment by cpackham** [comment]
Actually it could be your system is lacking make 4.0 (or we've failed to correctly detect it) which is required to build anything newer than glibc 2.28.

**Comment by happyalu** [comment]
thank you for the suggestions!

kconfig has this entry:

`... && !GLIBC_REQUIRE_2_29_or_older [=n] && !GLIBC_REQUIRE_older_than_2_29 [=y] && ...`

I'll try to figure out what might be setting the require-older-than-2.29 to y.

As for make 4.0: `GNU Make 4.2.1` seems to be installed, and config.status seems to have `S["KCONFIG_make_4_0_or_newer"]="def_bool y"` (not sure I'm looking at the right place)

**Comment by happyalu** [comment]
Found it:

```
config/libc/glibc.in:    select GLIBC_REQUIRE_older_than_2_29 if !CONFIGURE_has_python_3_4_or_newer
```

python3 was indeed not installed. Installing it fixed this.

Thanks so much for the kconfig suggestion :)

**Comment by TamNguyen1507** [comment]
What should I do if I want to select GLIBC 2.28, but it doesn't appear in menuconfig?

**Comment by TamNguyen1507** [comment]
Thanks for your reply @happyalu . As I understand it, does menuconfig show the GLIBC version based on the make version and Python version installed on my host PC?

**Comment by QBos07** [comment]
*build
Yes, what was there at time of configure of cart-ng
