### ISSUE TITLE
Bad sha512sum for mpc tarball from http://www.multiprecision.org/mpc/

### ISSUE THREAD

**Issue by billpriest** [crosstool-ng/crosstool-ng#1636]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version - master as of Tue Nov 23 07:44:18 PM UTC 2021
- Report host OS and its version - Pop!_OS 21.04
- Attach `.config` (unless the issue is not related to any configuration) - not related to .config
- Attach `build.log` (unless crosstool-NG fails before the build starts) - before build

So, the mpc-1.2.0.tar.gz from http://www.multiprecision.org/downloads generates sha512sum
1d998111ec35d10fe358a59e4dd0e6fc4e76b7c30a6af022aa271c7b6a15ac875f9ff6de47c66e89dbe9a42e8c32e08b2d140d759371c92e4e365e79d1a55aed
while the mpc-1.2.0.tar.gz from https://ftp.gnu.org/pub/pub/pub/gnu/mpc/ generates
84fa3338f51d369111456a63ad040256a1beb70699e21e2a932c779aa1c3bd08b201412c1659ecbb58403ea0548faacc35996d94f88f0639549269b7563c61b7

The file's sha512 from ftp.gnu.org matches the crosstool-ng/packages/mpc/1.2.0/chksum
sha1 mpc-1.2.0.tar.gz 0abdc94acab0c9bfdaa391347cdfd7bbdb1cf017
sha256 mpc-1.2.0.tar.gz e90f2d99553a9c19911abdb4305bf8217106a957e3994436428572c8dfe8fda6
sha512 mpc-1.2.0.tar.gz 84fa3338f51d369111456a63ad040256a1beb70699e21e2a932c779aa1c3bd08b201412c1659ecbb58403ea0548faacc35996d94f88f0639549269b7563c61b7

Using chrome I can download the file correctly; however, curl, wget, and firefox consistently download a "corrupted file" that is 835095 bytes vs. 840711 bytes for the uncorrupted file.

Maybe crosstool should use an alternate site for retrieving the binary for mpc as the method being used to download the file seems to be incompatible with the multiprecision.org site.  Additionally, the multiprecision.org site doesn't support https so it is inherently less secure.

**Comment by cpackham** [comment]
Just tried it now and I get the correct sha512

```
$ curl http://www.multiprecision.org/downloads/mpc-1.2.0.tar.gz >mpc-1.2.0.tar.gz.1
$ sha512sum mpc-1.2.0.tar.gz.1
84fa3338f51d369111456a63ad040256a1beb70699e21e2a932c779aa1c3bd08b201412c1659ecbb58403ea0548faacc35996d94f88f0639549269b7563c61b7  mpc-1.2.0.tar.gz.1
```

I notice multiprecision.org doesn't offer https so perhaps there is something going on between you and them. Are you able to see what difference there is between the two files? Is the first one even a tarball (sometimes you end up with a 404 page).

**Comment by billpriest** [comment]
according to file it is gzip compressed data
after gunzip it is still gzip compressed data, after 2nd gunzip (renaming file *.gz manually) file says tar archive.  tar tf seems happy with the file. Truly bizarre, no idea what is making it get gzip'ed twice.  Weird. Sorry for the noise.  I guess others could run into the problem.  I've worked around and am in process of building with newly created cross compiler.

Bill

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
