### ISSUE TITLE
Retrieving 'expat-2.2.9' expat: download failed

### ISSUE THREAD

**Issue by TERADOO** [crosstool-ng/crosstool-ng#1639]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

hello,I ran into an error while building a crosstool-ng development environment.
I tried to edit the file of 210_expat.sh, but it didn't solve the problem.
I got an error during the ct-ng build stage.

Referenced site:https://natsu-no-omoide.hatenablog.jp/entry/2020/01/1/232857

OS:debian11

Performing some trivial sanity checks
[WARN ]  Number of open files 1024 may not be sufficient to build the toolchain; increasing to 2048
[INFO ]  Build started 20211125.210947
[INFO ]  Building environment variables
[WARN ]  Directory '/home/terado/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = aarch64-rpi3-linux-uclibc
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.04s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'isl-0.22'
[EXTRA]    Verifying SHA512 checksum for 'isl-0.22.tar.xz'
[EXTRA]    Retrieving 'mpc-1.1.0'
[EXTRA]    Verifying SHA512 checksum for 'mpc-1.1.0.tar.gz'
[EXTRA]    Retrieving 'expat-2.2.9'
[ERROR]    expat: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2125]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2085]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2196]
[ERROR]  >>        called from: do_expat_get[scripts/build/companion_libs/210-expat.sh@12]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@647]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 0:06.36)
[00:07] / gmake: *** [/usr/local/bin/ct-ng:261: build] エラー 1

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/7602935/build.log)

**Comment by TommyMurphyTM1234** [comment]
Could it be related to this issue?

https://github.com/crosstool-ng/crosstool-ng/issues/1625

**Comment by TERADOO** [comment]
返信ありがとうございます。そうです。
この問題に関連していると思いますが、expat-2.2.6はダウンロードすることができました。
expatのフォルダには2.2.1と2.2.6が入っていました。
なぜか2.2.9がダウンロードできませんでした。

**Comment by TommyMurphyTM1234** [comment]
Google translation...

"thank you for your reply. that's right.
I think it's related to this issue, but expat-2.2.6 was able to download.
The expat folder contained 2.2.1 and 2.2.6.
However, for some reason 2.2.9 could not be downloaded."

**Comment by cpackham** [comment]
You've used the url `https://github.com/libexpat/libexpat/releases/download/R_2_2_6/expat-2.2.9.tar.gz` but you need to use `https://github.com/libexpat/libexpat/releases/download/R_2_2_9/expat-2.2.9.tar.gz`
