### ISSUE TITLE
macos x86_64-centos7-linux-gnu

### ISSUE THREAD

**Issue by 2854862159** [crosstool-ng/crosstool-ng#1653]
[ERROR]      ./../include/libc-symbols.h:485:26: error: '__EI__libc_intl_domainname' aliased to undefined symbol '__GI__libc_intl_domainname'
[ALL  ]        485 |   extern __typeof (name) __EI_##name       |                          ^~~~~
[ALL  ]      ./../include/libc-symbols.h:489:41: note: in expansion of macro '__hidden_ver1'
[ALL  ]        489 | #  define hidden_def(name)              __hidden_ver1(__GI_##name, name, name);
[ALL  ]            |                                         ^~~~~~~~~~~~~
[ALL  ]      ./../include/libc-symbols.h:490:41: note: in expansion of macro 'hidden_def'
[ALL  ]        490 | #  define hidden_data_def(name)         hidden_def(name)
[ALL  ]            |                                         ^~~~~~~~~~
[ALL  ]      ./../include/libc-symbols.h:551:37: note: in expansion of macro 'hidden_data_def'
[ALL  ]        551 | # define libc_hidden_data_def(name) hidden_data_def (name)
[ALL  ]            |                                     ^~~~~~~~~~~~~~~
[ALL  ]      SYS_libc.c:7:1: note: in expansion of macro 'libc_hidden_data_def'
[ALL  ]          7 | libc_hidden_data_def (_libc_intl_domainname)
[ALL  ]            | ^~~~~~~~~~~~~~~~~~~~
[ALL  ]      x86_64-centos7-linux-gnu-gcc  -g -O2 -fcommon -U_FORTIFY_SOURCE          -Wno-missing-attributes -Wno-array-bounds -Wno-array-parameter -Wno-stringop-overflow -Wno-maybe-uninitialized  global-locale.c -c -std=gnu99 -fgnu89-inline  -Wall -Winline -Wwrite-strings -fmerge-all-constants -frounding-math -Wstrict-prototypes   -fPIC     -I/usr/local/opt/gettext/include -DLOCALEDIR='"/usr/lib/locale"' -DLOCALE_ALIAS_PATH='"/usr/share/locale"' -Iprograms -I../include -I/Users/tooru/esp/ctng-volume/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib/locale -I/Users/tooru/esp/ctng-volume/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib -I../sysdeps/unix/sysv/linux/x86_64/64/nptl -I../sysdeps/unix/sysv/linux/x86_64/64 -I../nptl/sysdeps/unix/sysv/linux/x86_64 -I../nptl/sysdeps/unix/sysv/linux/x86 -I../sysdeps/unix/sysv/linux/x86 -I../sysdeps/unix/sysv/linux/x86_64 -I../sysdeps/unix/sysv/linux/wordsize-64 -I../nptl/sysdeps/unix/sysv/linux -I../nptl/sysdeps/pthread -I../sysdeps/pthread -I../sysdeps/unix/sysv/linux -I../sysdeps/gnu -I../sysdeps/unix/inet -I../nptl/sysdeps/unix/sysv -I../sysdeps/unix/sysv -I../sysdeps/unix/x86_64 -I../nptl/sysdeps/unix -I../sysdeps/unix -I../sysdeps/posix -I../nptl/sysdeps/x86_64/64 -I../sysdeps/x86_64/64 -I../sysdeps/x86_64/fpu/multiarch -I../sysdeps/x86_64/fpu -I../sysdeps/x86/fpu -I../sysdeps/x86_64/multiarch -I../nptl/sysdeps/x86_64 -I../sysdeps/x86_64 -I../sysdeps/x86 -I../sysdeps/ieee754/ldbl-96 -I../sysdeps/ieee754/dbl-64/wordsize-64 -I../sysdeps/ieee754/dbl-64 -I../sysdeps/ieee754/flt-32 -I../sysdeps/wordsize-64 -I../sysdeps/ieee754 -I../sysdeps/generic -I../nptl  -I.. -I../libio -I. -nostdinc -isystem /Volumes/ctng/build/x86/.build/x86_64-centos7-linux-gnu/buildtools/bin/../lib/gcc/x86_64-centos7-linux-gnu/11.2.0/include -isystem /Volumes/ctng/build/x86/.build/x86_64-centos7-linux-gnu/buildtools/bin/../lib/gcc/x86_64-centos7-linux-gnu/11.2.0/include-fixed -isystem /Users/tooru/esp/ctng-volume/x-tools/x86_64-centos7-linux-gnu/x86_64-centos7-linux-gnu/sysroot/usr/include -D_LIBC_REENTRANT -include ../include/libc-symbols.h  -DPIC -DSHARED     -o /Users/tooru/esp/ctng-volume/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib/locale/global-locale.os -MD -MP -MF /Users/tooru/esp/ctng-volume/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib/locale/global-locale.os.dt -MT /Users/tooru/esp/ctng-volume/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib/locale/global-locale.os
[ERROR]      make[3]: *** [../o-iterator.mk:9: /Users/tooru/esp/ctng-volume/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib/locale/SYS_libc.os] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ALL  ]      make[3]: Leaving directory '/Volumes/ctng/build/x86/.build/src/glibc-2.17/locale'
[ERROR]      make[2]: *** [Makefile:233: locale/subdir_lib] Error 2
[ALL  ]      make[2]: Leaving directory '/Volumes/ctng/build/x86/.build/src/glibc-2.17'
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ALL  ]      make[1]: Leaving directory '/Volumes/ctng/build/x86/.build/x86_64-centos7-linux-gnu/build/build-libc-final/multilib'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@404]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1608]
[ERROR]  >>        called from: glibc_backend[scripts/build/libc/glibc.sh@74]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@44]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 64:49.00)

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/7876397/config.txt)

**Comment by 2854862159** [comment]
I tried x86_64-centos7-linux-gnu and arm-unknown-linux-gnueabi but same result

**Comment by bhundven** [comment]
@2854862159 were you able to figure this out?

**Comment by 2854862159** [comment]
> @2854862159 were you able to figure this out?

It is because of the lack of dependent libraries. After I install the relevant libraries, I can solve the problem

**Comment by aijle** [comment]
Take the command to build 
SYS_libc.os which produced the error, cd to the directory 
($glibc_src/locale) in which that command was run, and run it manually 
with -save-temps added, then search for libintl.h in the SYS_libc.i file which will have 
been created (in the source directory), there must be something wrong within CPPFLAGS.
