### ISSUE TITLE
Enter to Select Submenus not work in arch linux x86_64

### ISSUE THREAD

**Issue by MOHAMED19OS** [crosstool-ng/crosstool-ng#1660]
*  CrossTool-NG version:
* version from github
`This is crosstool-NG version UNKNOWN

Copyright (C) 2008  Yann E. MORIN <yann.morin.1998@free.fr>
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.`

* Host OS details: 
 -  OS (Arch Linux)
 - `uname -r` -> `5.16.2-arch1-1`
- `uname -m` -> `x86_64`

the Issue: Entre to Select Submenus not work for any test or ant toolchain

**Comment by QBos07** [comment]
Did you mean Enter?

**Comment by MOHAMED19OS** [comment]
> Did you mean Enter?

yes menu Enter not work from Arch_Linux 
`KDE 5.90.0 / Plasma 5.23.5`

**Comment by cpackham** [comment]
I just tried an arch container and can't reproduce the problem

```
$ cat /etc/os-release 
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux-logo
```

**Comment by MOHAMED19OS** [comment]
@cpackham 
after install new arch all ok thnx
