### ISSUE TITLE
GDB 11.2 released

### ISSUE THREAD

**Issue by cpackham** [crosstool-ng/crosstool-ng#1664]
https://sourceware.org/pipermail/gdb-announce/2022/000130.html

Just creating this issue as a reminder to myself.  If someone feels like bringing this version in before I get to it go ahead.

May also want to look at  #1656 at the same time

**Comment by tttapa** [comment]
The upgrade to GDB 11.2 would be nice, as gdbserver 11.1 appears to be broken on AArch64. It fails with:
```text
.build/aarch64-linux-gnu/src/gdb/gdbserver/regcache.cc:257: A problem internal to GDBserver has been detected.
Unknown register tag_ctl requested
```
This appears to be fixed in 11.2, you can find Buildroot's backport here: https://github.com/buildroot/buildroot/commit/4353c716466fb8860dea265985829e9fae58e016

**Comment by egtvedt** [comment]
See pull request #1667.

**Comment by 0x8000-0000** [comment]
Still crashes when built with GCC 11.2 :(
