### ISSUE TITLE
GNU C Library 2.34+ sonames and softlinks.

### ISSUE THREAD

**Issue by milkylainen** [crosstool-ng/crosstool-ng#1668]
With the arrival of 2.34+ some structural things changed.
The decision to remove the generic name to soname softlink, breaks some toolchain handling in various environments.
As sonames and versions can change over architectures and time, building something reliable without kludge became a little bit more difficult.

The rationale behind this move was to help have a more atomic file behavior for package managers in distributions...

Previously you could ask gcc with --print-file-name for something.so and be given the full path and soname for the link time object,
without knowing the soname version. This is now gone as gcc doesn't give a useful answer on glibc sonames without a version. Atleast not for libraries without a fallback mechanism (like pthread).

I asked for a better rationale and/or a fallback mechanism for a transition period, but breaking structure that isn't desktop or server doesn't seem to generate much interest. Ie, embedded environments dealing with copying toolchain bits around.

How hard would it be to reintroduce the "old" library soname install structure?
Can such a patch be maintained by this project?

**Comment by cpackham** [comment]
I'm not sure I understand the issue exactly. I get the following behavior

```
$ powerpc-unknown-linux-gnu-gcc --version
powerpc-unknown-linux-gnu-gcc (crosstool-NG 1.24.0.507_1b3d45d) 11.2.0
$ powerpc-unknown-linux-gnu-gcc --print-file-name libc.so
/home/ctng/x-tools/powerpc-unknown-linux-gnu/powerpc-unknown-linux-gnu/sysroot/usr/lib/libc.so
```

Which seems consistent with my build machine
```
$ gcc --version
gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
$ gcc --print-file-name libc.so
/usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/libc.so
```
am I missing something?

That being said I'd be generally against maintaining patches that aren't back-ports of changes from upstream (yes I realize we already have many such patches).

**Comment by mirschkyn** [comment]
My bad. Let me clarify:
Cut from the glibc 2.34 NEWS.
"
* Previously, glibc installed its various shared objects under versioned
  file names such as libc-2.33.so.  The ABI sonames (e.g., libc.so.6)
  were provided as symbolic links.  Starting with glibc 2.34, the shared
  objects are installed under their ABI sonames directly, without
  symbolic links.  This increases compatibility with distribution
  package managers that delete removed files late during the package
  upgrade or downgrade process.
"

# Slackware, glibc-2.33
$ gcc --print-file-name libpthread.so
/usr/lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../lib64/libpthread.so
$ ls -la /usr/lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../lib64/libpthread.so
lrwxrwxrwx 1 root root 27 Jan 26 09:04 /usr/lib64/gcc/x86_64-slackware-linux/11.2.0/../../../../lib64/libpthread.so -> ../../lib64/libpthread.so.0

# Ubuntu 21.04, glibc-2.33
$ gcc --print-file-name libpthread.so
/usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libpthread.so
$ ls -la /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libpthread.so
lrwxrwxrwx 1 root root 37 mar 31  2021 /usr/lib/gcc/x86_64-linux-gnu/10/../../../x86_64-linux-gnu/libpthread.so -> /lib/x86_64-linux-gnu/libpthread.so.0

# Crosstool-ng, x86_64, gcc 11.2, glibc-2.34.
$ $ ./x86_64-secplatform-linux-gnu-gcc --print-file-name libpthread.so
libpthread.so
...

If you look in sysroot/lib64, the glibc installation does not contain the typical symlinks it used to have.
ie,
libsoname.so -> libsoname.so.soversion -> libsoname-releaseversion.so are now gone.

So, if something needs to copy an unknown toolchain the, rather comfortable method of asking what the link object path would be for a generic name (libpthread.so, and be precise about it, not just libpthread*, whatever that would mean) is now gone.

**Comment by cpackham** [comment]
I think in your specific example the problem is actually that libpthread.so
is no longer separate from libc.so. You'd get the same output from
libdoesnotexist.so

**Comment by mirschkyn** [comment]
Yes. But the empty libpthread.so.0 soname does still exist and can be optionally installed.
It is still needed if you intend to run your binaries that was linked with something where pthread.so was set as DT_NEEDED?

**Comment by cpackham** [comment]
Ah I get it now. I'm still of the opinion we shouldn't be intentionally diverging from upstream. But it's hypothetical at this point I'm not sure what such a diversion would look like.

**Comment by milkylainen** [comment]
I think we can close this.
It's still a nuisance for some embedded environments that has to deal with various toolchains of different age and structure.
It was a comfortable mechanism to use.
I tried letting glibc know of the embedded build environment use-case, but embedded has always been a bit of a deaf ear.
