### ISSUE TITLE
Footprint. Stripped toolchains

### ISSUE THREAD

**Issue by milkylainen** [crosstool-ng/crosstool-ng#1677]
I'd like to be able to reduce the size of a toolchain even more, without doing a manual cleanup.
Right now I have a few options:
-  Sans logs.
- Stripped executables.
- Not statically linking with libstdc++
- Glibc target-optspace (not recommended nowdays?).

Would like an option to strip the target toolchains completely.
Ie, add all libraries to the stripping.

User story behind the request is:
A modern non-stripped tar.gz _compressed_ standard Linux/glibc toolchain is 500M.
Moving a couple of toolchains to clean buildmachines every time I do these "clean" builds take a little bit longer than I'd like.
I can afford dropping debug as I seldom need libc debugs and I can generate two toolchain sets if I need too.
The common case with no need for debug symbols is the one I'd like to optimize a bit further.

**Comment by cpackham** [comment]
@milkylainen does #1761 help with this?
