### ISSUE TITLE
How to support combined binutils-gdb directories

### ISSUE THREAD

**Issue by jasmin-j** [crosstool-ng/crosstool-ng#169]
I just discovered the reason of my build errors.
Binutils 2.25.x doesn't support Cortex-M7 in gas.
I tracked it down to commit a715796ba188e7ca9eac6e613439b63fe50a677d (git://sourceware.org/git/binutils-gdb.git), for those who are curious.

This requires now the master branch of the binutils-gdb repository. But CT-NG currently expects binutils and gdb in two separate directories.
What is missing to support this are the following additional configure options to binutils:
  --disable-gdb, --disable-libdecnumber, --disable-readline --disable-sim
and to GDB:
  --disable-gas --disable-binutils --disable-ld --disable-gprof

With this additional options it should be possible to use the custom and custom location configuration
to build both binutils and GDB from the same directory, containing a recent GIT checkout.

To support the combined directory name "binutils-gdb" with CUSTOM_LOCATION_ROOT_DIR, it is required to add a configuration to tell CT-NG that a combined "binutils-gdb" tree is used. This is then used in binutils.sh and 300-gdb.sh to determine the package name for CT_GetCustom.

@bhundven, @yann-morin-1998:
Do you have another idea to support this in CT-NG?
Shall I prepare a patch to implement this?

@bhundven:
You mentioned a "checkout from repo" functionality in CT-NG. The above extensions might be useful for this, too.

**Comment by bhundven** [comment]
Let's tackle the "build from source control" change first.
I think there are some other features I want to propose as an "issue" so we can discuss re-organizing how packages are configured and built. I'll reference this issue in my proposal; in context.

**Comment by jasmin-j** [comment]
> Let's tackle the "build from source control" change first.
> I think there are some other features I want to propose as an "issue" so we can
> discuss re-organizing how packages are configured and built. I'll reference
> this issue in my proposal; in context.

I am using a git or svn tree and symbolic links with the names CG-NG expects. I am using the CUSTOM and CUSTOM_LOCATION(default) flags to achieve this.

If you thing about implementing the "build from source control", consider the binutils-gdb case, where binutils and gdb are using the same source tree.

Currently the patches aren't applied in a custom version. On one hand this seems logical. On the
other hand the required changes to build a cross compiler are not incorporated in the source tree
since years (e.g.: patches/binutils/2.25.1/* ).
I guess it would be needed to add a new flag "apply_patches" when CUSTOM is enabled.
Additionally it might be useful to add an exclude list for patches.
This new config options are useful for the "build from source control" function, too.

If you consider this as a useful extension, I will implement it.

**Comment by bhundven** [comment]
@jasmin-j I am currently tracking support for building components for version control in #219.
By referencing that issue in this ticket, it will remind me to add building binutils-gdb repo when I add the default upstream url.

For now I am closing this issue.
