### ISSUE TITLE
Failing to build a sample on Fedora 34

### ISSUE THREAD

**Issue by Mikerah** [crosstool-ng/crosstool-ng#1691]
I'm trying to compile and build the toolchain for MIPS64 using the sample configuration.
However, I get the following error:
```
[ERROR]    checking for suffix of object files... configure: error: in `/home/mikerah/Documents/HashCloak/Projects/work-dir/.build/mips64el-unknown-elf/build/build-cc-gcc-core/mips64el-unknown-elf/libgcc':
[ERROR]    configure: error: cannot compute suffix of object files: cannot compile
[ERROR]    make[1]: *** [Makefile:12721: configure-target-libgcc] Error 1
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@687]
[ERROR]  >>        called from: do_cc_core[scripts/build/cc/gcc.sh@210]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 1:41.88)
[01:42] / gmake: *** [/usr/local/bin/ct-ng:261: build] Error 2
```
I independently have gcc installed but that targets `x86_64` which is my host machine. That is a different version than what I need for MIPS.

### crosstool-NG version
```
This is crosstool-NG version 1.24.0.551_1e47ca1

Copyright (C) 2008  Yann E. MORIN <yann.morin.1998@free.fr>
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
```
### host OS and its version
Fedora 34 64-bit

### Config
`.config`: Using the `mips64-unknown-linux-gnu` sample provided by crosstool-NG

### Log file
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/8191686/build.log)

**Comment by cpackham** [comment]
Looks like you're actually building `mips64el-unknown-elf` is that what you intended? I tried building `mips64-unknown-linux-gnu` in a Fedora34 container and it build fine. As `mips64el-unknown-elf` is not a sample config I suspect something has gone wrong (or you're using a custom config).

Could you post the actual `.config` you ended up with (which may be different to the sample) and from the build.log there is a sign that libgcc's configure failed so posting `/home/mikerah/Documents/HashCloak/Projects/work-dir/.build/mips64el-unknown-elf/build/build-cc-gcc-core/mips64el-unknown-elf/libgcc/config.log` would also be helpful.

**Comment by Mikerah** [comment]
My intention wasn't to build `mips64el-unknown-elf`. That was another config that I set up through `make menuconfig`. I thought that calling the sample config `mips64-unknown-linux-gnu` would just use that config but it seems like it doesn't.

How can I remove the previously built config so that I can try to build the sample?

**Comment by cpackham** [comment]
`ct-ng distclean` or just `rm .config` will do the trick.

**Comment by Mikerah** [comment]
Now, I get the following error after running `ct-ng distclean`:
```
There is no existing .config file!
You need to either run 'menuconfig',
or configure an existing sample.
gmake: *** [/usr/local/bin/ct-ng:251: .config] Error 1
```

**Comment by cpackham** [comment]
Yes that's correct. `ct-ng distclean` removes the existing .config and any existing build output. So now you need to run `ct-ng mips64-unknown-linux-gnu` to load the sample then `ct-ng build` to build it.

**Comment by Mikerah** [comment]
It works now.

Thank you very much.
