### ISSUE TITLE
crosstool-ng-1.25.0_rc2:  Compilation error due to non case-sensitivity on Msys2/MinGW32

### ISSUE THREAD

**Issue by djipi** [crosstool-ng/crosstool-ng#1714]
crosstool-ng-1.25.0_rc2
Windows 10
Msys2/MinGW32

I have tried to dig the problem but was out of luck, any input(s) are welcome. Thanks.

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/8577393/build.log)

**Comment by modbw** [comment]
To build a gcc based toolchain you will need a case sensitive file system. Maybe [enabling it](https://docs.microsoft.com/en-us/windows/wsl/case-sensitivity#:~:text=The%20Windows%20file%20system%20supports,may%20differ%20only%20by%20case.) can solve your issue. Using a Linux machine (WSL, VM or native) to build gcc toolchains will always be a more painless experience even if a canadian cross configuration is required.

**Comment by djipi** [comment]
Thank you for the feedback and advice. I will give it a try.

**Comment by QBos07** [comment]
I recommend using a wsl cross build

**Comment by djipi** [comment]
Thank you again for your advices. I think we can close this issue now.
