### ISSUE TITLE
Build failure: Canadian, CT-NG 1.25.0_rc2, undefined reference to ZSTD_*

### ISSUE THREAD

**Issue by martin8947** [crosstool-ng/crosstool-ng#1718]
Canadian build fails when building static toolchain. Seems to be LTO related. Option to disable LTO is not available in the menuconfig when a static build is chosen.

- Crosstool-NG version: 1.25.0_rc2
- Host OS and its version: Arch 5.17.5-arch1-1
- .config:
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/8636131/config.txt)
- build.log:
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/8636120/build.log)

**Comment by cpackham** [comment]
Possibly similar to #1613
