### ISSUE TITLE
configure: error: Required tool not found: GNU bash >= 3.1

### ISSUE THREAD

**Issue by oniokiwi** [crosstool-ng/crosstool-ng#1723]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version -> Master branch of git repo
- Report host OS and its version -> Ubuntu mate 21.10 (5.13.0-40-generic), GNU bash, version 5.1.8(1)-release (x86_64-pc-linux-gnu)
- Attach `.config` (unless the issue is not related to any configuration)  -> not related to config
- Attach `build.log` (unless crosstool-NG fails before the build starts) -> Fails before the build starts

///////
checking for bzip2... bzip2
checking for xz... xz
checking for unzip... unzip
checking for help2man... help2man
checking for wget... wget
checking for curl... curl
checking for stat... stat
checking whether stat takes GNU or BSD format... GNU
checking whether to use getconf or sysctl to count CPUs... getconf _NPROCESSORS_ONLN
checking for gpatch... no
checking for patch... patch
checking for absolute path to patch... /usr/bin/patch
checking for bash... /usr/bin/bash
checking for GNU bash >= 3.1... no
configure: error: Required tool not found: GNU bash >= 3.1

**Comment by cpackham** [comment]
could you please attach the config.log created when you ran `./configure`

**Comment by oniokiwi** [comment]
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/8676345/config.log)

**Comment by cpackham** [comment]
Are you actually building off master or the 1.25 release? Configure disagrees

```
This file contains any messages produced by compilers while
running configure, to aid debugging if configure makes a mistake.

It was created by crosstool-NG configure 1.23.0.418-d590, which was
generated by GNU Autoconf 2.69.  Invocation command line was
```

This was fixed a while back in https://github.com/crosstool-ng/crosstool-ng/commit/b0151f5eb53c5bf70d39512a3d73e529be90bc0a

We'll be back here for bash 6 but I think your immediate problem can be fixed with a `git pull && ./bootstrap` or by using the 1.25 tarball

**Comment by oniokiwi** [comment]
I initially tried using the latest tag which I noticed was 1.25 and when that did not work I decided to try master.

**Comment by cpackham** [comment]
Main thing to remember when you're jumping around branches is to run './bootstrap' to re-generate some files (including the configure script). Also probably a good idea to run `git clean -fxd` when switching branches to clean out any cruft.

**Comment by oniokiwi** [comment]
git pull && ./bootstrap worked. Thanks

**Comment by oniokiwi** [comment]
Thanks for the recommendations I would remember that for next time.
