### ISSUE TITLE
Error when building DUMA on Manjaro: ISO C++17 does not allow dynamic exception specifications

### ISSUE THREAD

**Issue by nawordar** [crosstool-ng/crosstool-ng#1724]
- crosstool-NG version: 1.25.0.13_fd694dd
- Host OS: Manjaro 21.2.6
- Host kernel: 5.15.32-1-MANJARO
- [logs](https://github.com/crosstool-ng/crosstool-ng/files/8676353/logs.zip)

When building DUMA on Manjaro I get the following error:

```
[INFO ]  Installing D.U.M.A.
[EXTRA]    Copying sources
[EXTRA]    Building D.U.M.A
[ERROR]    testoperators.cpp:40:65: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:46:65: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:53:81: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:59:83: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:73:1: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:104:1: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:132:1: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    testoperators.cpp:160:1: error: ISO C++17 does not allow dynamic exception specifications
[ERROR]    make[2]: *** [GNUmakefile:592: testoperators.o] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing D.U.M.A.'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_debug_duma_build[scripts/build/debug/200-duma.sh@31]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 50:26.40)
[50:26] / make[1]: *** [/usr/bin/ct-ng:261: build] Error 2
make: *** [/usr/bin/ct-ng:265: build.1] Error 2
```
The config was generated using `ct-ng arm-unknown-linux-gnueabi`. I only changed the `CT_LOCAL_TARBALLS_DIR`, `CT_PREFIX_DIR` and `CT_EXTRA_CXXFLAGS_FOR_BUILD` variables.

**Comment by cpackham** [comment]
The version of duma shipped in ct-ng is kind of old so I'm not too surprised it causes a compiler defaulting to a new-ish C++ standard to balk. It is odd because none of our CI builds have shown the error

**Comment by nawordar** [comment]
Version of GCC on my system is 11.2.0. Is it possible to pass flags to GCC? I tried setting `CT_EXTRA_CXXFLAGS_FOR_BUILD`, but it didn't help. I think it applies only to building GCC.

**Comment by cpackham** [comment]
Unfortunately no. I think it could just be fixed with the right `-std=gnu11` option or by updating duma but both of those require some internal changes. As duma is optional you can just disable it and build the toolchain without it.

**Comment by cpackham** [comment]
Hmm I tried an ubuntu22.04 container which also has gcc-11.2.0 but that build duma fine. I'll see it there is a manjaro one.

**Comment by cpackham** [comment]
I don't know if https://github.com/crosstool-ng/crosstool-ng/pull/1728 will actually help but at least it gets us the latest version available.

I see upstream are in the process of moving to cmake so we might have to tweak our build script for the next version.

**Comment by nawordar** [comment]
I'm sorry, I forgot to tell that after building in a clean build directory everything worked fine. Thank you for your help, I really appreciate it.
