### ISSUE TITLE
Error building C library while generating toolchain for beaglebone black

### ISSUE THREAD

**Issue by oniokiwi** [crosstool-ng/crosstool-ng#1729]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build [starts)](url)

Hi I am trying to build tool-chain that would cross compile code for Beaglebone black board running the following

# TARGET
Linux 4.19.94-t-r42
Debian: 8.3.0-6
glibc: 2.28
binutils: 2.31.1

# HOST PC
Ubuntu Mate: 21.10 (Impish Indri) 64-bit
Linux 5.13.0-40-generic
crosstool-ng: 1.25.0

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/8693959/build.log)
[dotconfig.log](https://github.com/crosstool-ng/crosstool-ng/files/8693965/dotconfig.log)

Getting stuck at  "Building C library" any idea on how to get past this stage. I was able to use the default crosstool-ng settings to build tools that compiled the code fine for the arm-cortex_a8-linux-gnueabihf but unfortunately the generated code does not run on target complaining about glibc so I tried rebuilding toolchain with matching glibc and binutils versions

Regards
onio

**Comment by cpackham** [comment]
I think the problem is that newer GCC produces warnings (which are promoted to errors) for older glibcs. The fix is to deselect `CT_GLIBC_ENABLE_WERROR`.

I attempted to prevent this with  https://github.com/crosstool-ng/crosstool-ng/commit/7e211419738abcb6db7cfc18c0553da36a504a36 but I suspect that default logic will be defeated if you start with a sample (which defaults to  the latest gcc & glibc version) that will have `ENABLE_WERROR=y` then when you change glibc versions to match your target the `ENABLE_WERROR=y` sticks because Kconfig can't distinguish between a setting that was selected automatically and one that was selected manually.

**Comment by cpackham** [comment]
I think it might be possible to provide `ENABLE_WERROR=y` with some additional dependencies something like

```
config HAVE_GLIBC_WERROR
    depends on GCC_8_or_later && !GCC_9_or_later && GLIBC_2_27_or_later
    depends on GCC_9_or_later && !GCC_10_or_later && GLIBC_2_29_or_later
    depends on GCC_10_or_later && !GCC_11_or_later && GLIBC_2_31_or_later
    depends on GCC_11_or_later && GLIBC_2_34_or_later
    default y

config GLIBC_ENABLE_WERROR
    bool "Enable -Werror during the build"
    default y if HAVE_GLIBC_WERROR
```

Or possibly use an `imply` when selecting the GLIBC version (although those are all generated so it might be tricky to add).

**Comment by oniokiwi** [comment]
Hi Chris,

Disabling the following in the C-library menu
 
config GLIBC_ENABLE_WERROR
    bool "Enable -Werror during the build"
    default y if HAVE_GLIBC_WERROR

Made the crosstool-ng to complete the creation of the compiler. I was however unable to find the following using menuconfig

config HAVE_GLIBC_WERROR
    depends on GCC_8_or_later && !GCC_9_or_later && GLIBC_2_27_or_later
    depends on GCC_9_or_later && !GCC_10_or_later && GLIBC_2_29_or_later
    depends on GCC_10_or_later && !GCC_11_or_later && GLIBC_2_31_or_later
    depends on GCC_11_or_later && GLIBC_2_34_or_later
    default y

where can I find this settings?

Thanks
onio

**Comment by cpackham** [comment]
They don't exist (yet) that was my suggestion for how ct-ng might handle
enabling/disabling WERROR dynamically based on the gcc/glibc selection.
