### ISSUE TITLE
static assertion error on libsanitizer (mips64-unknown, n64 ABI)

### ISSUE THREAD

**Issue by bagasme** [crosstool-ng/crosstool-ng#1733]
crosstool-NG version: commit 3ac6f1791af77b682b1de4ad56157653aa566417
host OS: Debian 11 (gcc 10.2.0)
config: [config.gz](https://github.com/crosstool-ng/crosstool-ng/files/8697518/config.gz)
build log: [build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/8697551/build.log.gz)

Hi,

I'm trying to build mips64-unknown-linux-gnu cross compiler (GCC 11.3.0) with
libgomp and libsanitizer enabled. No experimental features are enabled.

At final gcc stage, I got static assertion error on libsanitizer:

```
[ALL  ]    In file included from /home/bagas/cross/workdir/mips64-unknown/.build/mips64-unknown-linux-gnu/src/gcc/libsanitizer/sanitizer_common/sanitizer_platform_limits_linux.cpp:21:
[ERROR]    /home/bagas/cross/workdir/mips64-unknown/.build/mips64-unknown-linux-gnu/src/gcc/libsanitizer/sanitizer_common/sanitizer_platform_limits_linux.cpp:75:38: error: static assertion failed
[ALL  ]       75 | COMPILER_CHECK(struct_kernel_stat_sz == sizeof(struct stat));
[ALL  ]          |                ~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~
[ALL  ]    /home/bagas/cross/workdir/mips64-unknown/.build/mips64-unknown-linux-gnu/src/gcc/libsanitizer/sanitizer_common/sanitizer_internal_defs.h:332:44: note: in definition of macro 'COMPILER_CHECK'
[ALL  ]      332 | #define COMPILER_CHECK(pred) static_assert(pred, "")
[ALL  ]          |                                            ^~~~
[ALL  ]    mv -f .deps/sanitizer_platform_limits_openbsd.Tpo .deps/sanitizer_platform_limits_openbsd.Plo
[ERROR]    make[5]: *** [Makefile:616: sanitizer_platform_limits_linux.lo] Error 1
```

**Comment by cpackham** [comment]
Hmm that does ring a bell. There's some discrepancy between the kernel's `struct stat` and the one in gcc. I've got a vague recollection we hit this at $dayjob.

**Comment by cpackham** [comment]
Looks like the kernel has `sizeof(struct stat) == 104` but libsanitizer ends up with  `struct_kernel_stat_sz == 216` (assuming I'm reading the code right).

**Comment by cpackham** [comment]
I've raised https://gcc.gnu.org/bugzilla/show_bug.cgi?id=105614 because I think it's an upstream gcc bug
