### ISSUE TITLE
ISL and Cloog headache

### ISSUE THREAD

**Issue by JustArchi** [crosstool-ng/crosstool-ng#174]
I'm building GCC 5.2.0.

```gcc.in``` specifies:
```
    select CLOOG_NEEDED if !CC_GCC_5_1_or_later
    select PPL_NEEDED if !CC_GCC_4_8_or_later
    select ISL_NEEDED if CC_GCC_4_8_or_later
```

So I have ```ISL_NEEDED``` set (only).

Now ```isl.in``` specifies that in order to use ```0.15``` ISL I need ```CLOOG_0_18_4_or_later``` set. However there is no ```CLOOG``` options available, because nothing defines ```CLOOG_NEEDED``` and by default crosstool-ng does not show any "optional" companion libraries, until they're needed. So there is no possible way to choose ISL 0.15 with GCC 5.2.0.

This is related to https://github.com/crosstool-ng/crosstool-ng/commit/218bea6f24fe3b49a54d14e26f7f0922aee2c0c8 when those dependencies were added.

**Comment by jasmin-j** [comment]
I will fix this.

**Comment by jasmin-j** [comment]
Can you check if commit ed647a79b0cc567e620bf32a82098705ba598087 fixes your problem.

**Comment by JustArchi** [comment]
Thanks @jasmin-j 

I'll check that later today.

**Comment by jasmin-j** [comment]
@JustArchi
> I'll check that later today.
Did it work as expected?

**Comment by JustArchi** [comment]
@jasmin-j 
In my case, yes. ISL 0.15 is available now for me, so thank you for that! :+1:
