### ISSUE TITLE
Why not have more ./configure after ./bootstrap?What is the alternative to that now?

### ISSUE THREAD

**Issue by neuberfran** [crosstool-ng/crosstool-ng#1767]
Hi,

I stay trying this:
https://nc-pin.com/index.php/2022/05/21/building-toolchain-for-risc-v-on-macos/

But, after ./bootstrap not appear ./configure. Why? How to solve?

Pls

**Comment by neuberfran** [comment]
Thanks,

You asked for more details: If you go back to the tutorial on the link you will see that the first thing is a brew command that I post the result of it below and I need you to analyze it to see if there is something wrong:

https://gist.github.com/neuberfran/16342a5f9e3eff1ad0c68f5df91431b4

**Comment by neuberfran** [comment]
@cpackham 

As you can see in the screen below, I got evolution and arrived at the configuration screen

But before **make** command in this(https://nc-pin.com/index.php/category/wch/ch32v-series/ch32v307/) and in this part: **cd ch32v307/EVT/EXAM/GPIO/GPIO_Toggle/User**

I have issue(in make command):

(base) iMac-2:User neuberfran$ **make**
riscv32-unknown-elf-gcc -march=rv32imac -mabi=ilp32 -msmall-data-limit=8 -mno-save-restore -Os -fmessage-length=0 -fsigned-char -ffunction-sections -fdata-sections -Wunused -Wuninitialized -MMD -I . -I ../../../SRC/Core -I ../../../SRC/Peripheral/inc -I ../../../SRC/Debug -o main.o -c main.c
make: riscv32-unknown-elf-gcc: No such file or directory
make: *** [main.o] Error 1
(base) iMac-2:User neuberfran$ pwd
/Users/neuberfran/ch32v307/EVT/EXAM/GPIO/GPIO_Toggle/User

![Captura de Tela 2022-06-28 às 19 09 05](https://user-images.githubusercontent.com/38701397/176312966-e73d26b4-5143-4fbe-9a4d-45598ff5f75c.png)

![before new issue](https://user-images.githubusercontent.com/38701397/176313045-62817d86-e666-4bcb-b1a5-445b412850a6.png)

**Comment by cpackham** [comment]
`riscv32-unknown-elf-gcc` is not in your `$PATH` so when make attempts to use it it cannot find the command.

You will need to add something like `export PATH=$HOME/x-tools/riscv32-unknown-elf/bin:$PATH` to your shell's environment.

**Comment by neuberfran** [comment]
@cpackham There was actually nothing in the following folder: /Users/neuberfran/csfs/x-tools/riscv32-unknown-elf/bin

**I retraced the steps:**

ct-ng riscv32-unknown-elf
ct-ng menuconfig
ct-ng build

From that tutorial and I was successful.
Thanks
