### ISSUE TITLE
Build fails installing binutils

### ISSUE THREAD

**Issue by Chris3960-TH** [crosstool-ng/crosstool-ng#1784]
crosstool-NG version: 1.24.0
host OS and its version: Ubuntu 22.04 LGS
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/9134363/build.log)
I'm unable to find the .config file. What is the path to it?

**Comment by bhundven** [comment]
The `.config` file is in the directory where you ran `ct-ng build` from.

**Comment by bhundven** [comment]
I would try newer 1.25.0: https://crosstool-ng.github.io/2022/05/07/release-1.25.0.html
If that is still an issue, try cloning down the git tree and try a build from the master branch.

**Comment by Chris3960-TH** [comment]
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/9135279/config.txt)
found the config file.
I'll try 1.25.0.

**Comment by bhundven** [comment]
I was able to build this config on the master branch without errors on Debian Sid/aarch64.
```
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = aarch64-unknown-linux-gnu
[EXTRA]      host   = aarch64-unknown-linux-gnu
[EXTRA]      target = arm-cortex_a8-linux-gnueabihf
```

**Comment by bhundven** [comment]
No problem!
