### ISSUE TITLE
Build failed in step 'Installing ncurses for build'

### ISSUE THREAD

**Issue by iboldurev** [crosstool-ng/crosstool-ng#1788]
Darwin Developers-MacBook-Pro.local 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 21:08:37 PDT 2022; root:xnu-8020.121.3~4/RELEASE_ARM64_T6000 arm64

crosstool-NG version 1.25.0.59_ee635cd

/Volumes/crosstool-ng ❯ ct-ng build                                                                                                       26s
[INFO ]  Performing some trivial sanity checks
[WARN ]  Number of open files 256 may not be sufficient to build the toolchain; increasing to 2048
[INFO ]  Build started 20220721.145428
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = aarch64-apple-darwin21.5.0
[EXTRA]      host   = aarch64-apple-darwin21.5.0
[EXTRA]      target = aarch64-rpi4-linux-gnu
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.00s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 0.00s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[INFO ]  Extracting and patching toolchain components: done in 1.00s (at 00:04)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for build
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[2]: *** [Makefile:259: clear] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [Makefile:120: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing ncurses for build'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_ncurses_backend[scripts/build/companion_libs/220-ncurses.sh@177]
[ERROR]  >>        called from: do_ncurses_for_build[scripts/build/companion_libs/220-ncurses.sh@32]
[ERROR]  >>        called from: do_companion_libs_for_build[scripts/build/companion_libs.sh@29]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 0:24.00)
[00:24] / gmake: *** [/usr/local/bin/ct-ng:261: build] Error 2

**Comment by cpackham** [comment]
Please attach build.log

**Comment by iwind** [comment]
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/13938282/build.log)

same issue:
~~~
...
[ALL  ]    x86_64-build_apple-darwin23.2.0-gcc -DHAVE_CONFIG_H -I../progs -I. -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs -I../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/include -D_DARWIN_C_SOURCE -DNDEBUG -O2 -g -Qunused-arguments -fno-common -Qunused-arguments -no-cpp-precomp -c /Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/tic.c -o ../objects/tic.o
[ALL  ]    x86_64-build_apple-darwin23.2.0-gcc -DHAVE_CONFIG_H -I../progs -I. -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs -I../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/include -D_DARWIN_C_SOURCE -DNDEBUG -O2 -g -Qunused-arguments -fno-common -Qunused-arguments -no-cpp-precomp -c /Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/transform.c -o ../objects/transform.o
[ALL  ]    x86_64-build_apple-darwin23.2.0-gcc -DHAVE_CONFIG_H -I../progs -I. -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs -I../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/include -D_DARWIN_C_SOURCE -DNDEBUG -O2 -g -Qunused-arguments -fno-common -Qunused-arguments -no-cpp-precomp -c /Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/tset.c -o ../objects/tset.o
[ALL  ]    x86_64-build_apple-darwin23.2.0-gcc ../objects/clear.o ../objects/clear_cmd.o ../objects/tty_settings.o -L../lib -L/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/lib   -framework CoreFoundation -Wl,-search_paths_first -DHAVE_CONFIG_H -I../progs -I. -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs -I../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/include -D_DARWIN_C_SOURCE -DNDEBUG -O2 -g -Qunused-arguments -fno-common -Qunused-arguments -no-cpp-precomp -lncurses    -o clear
[ALL  ]    x86_64-build_apple-darwin23.2.0-gcc -DHAVE_CONFIG_H -I../progs -I. -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs -I../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/include -D_DARWIN_C_SOURCE -DNDEBUG -O2 -g -Qunused-arguments -fno-common -Qunused-arguments -no-cpp-precomp -c /Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/dump_entry.c -o ../objects/dump_entry.o
[ALL  ]    x86_64-build_apple-darwin23.2.0-gcc -DHAVE_CONFIG_H -I../progs -I. -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs -I../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/../include -I/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/include -D_DARWIN_C_SOURCE -DNDEBUG -O2 -g -Qunused-arguments -fno-common -Qunused-arguments -no-cpp-precomp -c /Volumes/crosstool/.build/x86_64-unknown-linux-gnu/src/ncurses/progs/tput.c -o ../objects/tput.o
[ALL  ]    ld: warning: search path '/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/buildtools/lib' not found
[ALL  ]    ld: archive member '/' not a mach-o file in '/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/build/build-ncurses-build-x86_64-build_apple-darwin23.2.0/lib/libncurses.a'
[ERROR]    clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR]    make[2]: *** [Makefile:259: clear] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ALL  ]    make[2]: Leaving directory '/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/build/build-ncurses-build-x86_64-build_apple-darwin23.2.0/progs'
[ERROR]    make[1]: *** [Makefile:120: all] Error 2
[ALL  ]    make[1]: Leaving directory '/Volumes/crosstool/.build/x86_64-unknown-linux-gnu/build/build-ncurses-build-x86_64-build_apple-darwin23.2.0'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing ncurses for build'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
[ERROR]  >>        called from: do_ncurses_backend[scripts/build/companion_libs/220-ncurses.sh@177]
[ERROR]  >>        called from: do_ncurses_for_build[scripts/build/companion_libs/220-ncurses.sh@32]
[ERROR]  >>        called from: do_companion_libs_for_build[scripts/build/companion_libs.sh@29]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
...
~~~

**Comment by QBos07** [comment]
Maybe try `gcc` from homebrew or similar

**Comment by sufuk** [comment]
@iboldurev Any luck ?

**Comment by bhundven** [comment]
When you're exporting the path to binutils, put the PATH first!

For example, don't do:
```sh
export PATH="$(brew --prefix)/opt/binutils/bin:$PATH"
```
Do this:
```sh
export PATH="$PATH:$(brew --prefix)/opt/binutils/bin"
```

This is because MacOS builds need `/usr/bin/ar`, but MacOS doesn't provide `objcopy`, `objdump`, and `readelf`. So with the PATH setup that way, `configure` will find `/usr/bin/ar`, but will also find `$(brew --prefix)/opt/binutils/bin/objcopy`, `$(brew --prefix)/opt/binutils/bin/objdump`, and `$(brew --prefix)/opt/binutils/bin/readelf`.

Please test and confirm this fixes for you!

**Comment by bhundven** [comment]
@iwind @iboldurev @sufuk ^^
I'm closing this issue. Please re-open with more environment information if you are still having an issue after trying my suggestion.
