### ISSUE TITLE
error: variable has incomplete type 'struct stat64'

### ISSUE THREAD

**Issue by iboldurev** [crosstool-ng/crosstool-ng#1789]
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      rpc_main.c:329:17: error: variable has incomplete type 'struct stat64'
[ERROR]      rpc_main.c:331:7: error: implicit declaration of function 'stat64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
[ERROR]      rpc_main.c:1117:17: error: variable has incomplete type 'struct stat64'
[ERROR]      rpc_main.c:1120:9: error: implicit declaration of function 'stat64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
[ERROR]      make[3]: *** [Makefile:174: /Volumes/crosstool-ng/.build/armv8-rpi4-linux-gnueabihf/build/build-libc/multilib/sunrpc/cross-rpc_main.o] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ERROR]      make[2]: *** [Makefile:470: sunrpc/others] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2

**Comment by cpackham** [comment]
please attach build.log

**Comment by cpackham** [comment]
Looks like it's a problem on macos

https://trac.macports.org/ticket/62853
https://www.spinics.net/lists/dash/msg02117.html

Given the rpc stuff has been dropped from GNU libc it's unlikely to see a fix. To get a successful build you probably need to unset `CT_GLIBC_ENABLE_OBSOLETE_RPC`.

**Comment by iboldurev** [comment]
@cpackham Thx, fixed
