### ISSUE TITLE
Canadian build for bare-metal ARM fails.

### ISSUE THREAD

**Issue by jwatte** [crosstool-ng/crosstool-ng#18]
Using crosstool-ng from github master (after 1.20)

I want to build a version of GCC to run on the Raspberry Pi, and target the Teensy 3.1 (a Cortex-M4 without FPU.) My build machine is Linux amd64.

1) Configure and build cross from x64 to rpi -- works
2) Configure and build cross from x64 to teensy (bare metal, newlib, no long double or quadmath) -- works, after patching the "can't determine value of EOF" problem
3) Configure and build canadian from rpi to teensy -- compiler builds, but library fails with file not found from an #include_next <fenv.h>

Internet search says this is a "cygwin specific problem that requires a newer cygwin," but that's obviously not the problem in this case.

    [ALL  ]    mkdir -p ./arm-jwatte-eabi/bits/stdc++.h.gch
    [ALL  ]    arm-jwatte-eabi-c++     -x c++-header -nostdinc++ -g -Os -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/arm-jwatte-eabi -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include -I/usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/libsupc++ -I/opt/cross/rpi/include -O2 -g -std=gnu++0x /usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/include/precompiled/stdc++.h   -o arm-jwatte-eabi/bits/stdc++.h.gch/O2ggnu++0x.gch
    [ALL  ]    arm-jwatte-eabi-c++     -x c++-header -nostdinc++ -g -Os -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/arm-jwatte-eabi -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include -I/usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/libsupc++ -I/opt/cross/rpi/include -O2 -g /usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/include/precompiled/stdc++.h -o arm-jwatte-eabi/bits/stdc++.h.gch/O2g.gch
    [ALL  ]    In file included from /usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/cfenv:41:0,
    [ALL  ]                     from /usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/include/precompiled/stdc++.h:53:
    [ERROR]    /usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/fenv.h:36:24: fatal error: fenv.h: No such file or directory
    [ALL  ]     # include_next <fenv.h>
    [ALL  ]                            ^
    [ALL  ]    compilation terminated.
    [ERROR]    make[4]: *** [arm-jwatte-eabi/bits/stdc++.h.gch/O2ggnu++0x.gch] Error 1
    [ALL  ]    make[4]: *** Waiting for unfinished jobs....
    [ALL  ]    make[4]: Leaving directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include'
    [ERROR]    make[3]: *** [all-recursive] Error 1
    [ALL  ]    make[3]: Leaving directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3'
    [ERROR]    make[2]: *** [all] Error 2
    [ALL  ]    make[2]: Leaving directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3'
    [ERROR]    make[1]: *** [all-target-libstdc++-v3] Error 2
    [ALL  ]    make[1]: Leaving directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final'
    [ERROR]
    [ERROR]  >>
    [ERROR]  >>  Build failed in step 'Installing final compiler'
    [ERROR]  >>        called in step '(top-level)'
    [ERROR]  >>
    [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
    [ERROR]  >>        called from: do_cc_core_backend[scripts/build/cc/gcc.sh@486]
    [ERROR]  >>        called from: do_cc_for_host[scripts/build/cc/gcc.sh@598]
    [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
    [ERROR]  >>
    [ERROR]  >>  For more info on this error, look at the file: 'build.log'
    [ERROR]  >>  There is a list of known issues, some with workarounds, in:
    [ERROR]  >>      '/usr/local/share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
    [ERROR]
    [ERROR]  (elapsed: 42:22.64)

**Comment by jwatte** [comment]
#
    # Automatically generated make config: don't edit
    # crosstool-NG 1.20.0 Configuration
    # Thu Jan  1 10:15:34 2015
    #
    CT_CONFIGURE_has_make381=y
    CT_CONFIGURE_has_xz=y
    CT_CONFIGURE_has_svn=y
    CT_MODULES=y

    #
    # Paths and misc options
    #

    #
    # crosstool-NG behavior
    #
    # CT_OBSOLETE is not set
    CT_EXPERIMENTAL=y
    CT_EXPERIMENTAL_PATCHES=y
    # CT_ALLOW_BUILD_AS_ROOT is not set
    # CT_DEBUG_CT is not set

    #
    # Paths
    #
    CT_LOCAL_TARBALLS_DIR=""
    CT_CUSTOM_LOCATION_ROOT_DIR=""
    CT_WORK_DIR="${CT_TOP_DIR}/.build"
    CT_PREFIX_DIR="/opt/cross/rpi"
    CT_INSTALL_DIR="${CT_PREFIX_DIR}"
    # CT_RM_RF_PREFIX_DIR is not set
    CT_REMOVE_DOCS=y
    CT_INSTALL_DIR_RO=y
    # CT_STRIP_ALL_TOOLCHAIN_EXECUTABLES is not set

    #
    # Downloading
    #
    # CT_FORBID_DOWNLOAD is not set
    # CT_FORCE_DOWNLOAD is not set
    CT_CONNECT_TIMEOUT=10
    # CT_ONLY_DOWNLOAD is not set
    # CT_USE_MIRROR is not set

    #
    # Extracting
    #
    # CT_FORCE_EXTRACT is not set
    CT_OVERIDE_CONFIG_GUESS_SUB=y
    # CT_ONLY_EXTRACT is not set
    CT_PATCH_BUNDLED=y
    # CT_PATCH_LOCAL is not set
    # CT_PATCH_BUNDLED_LOCAL is not set
    # CT_PATCH_LOCAL_BUNDLED is not set
    # CT_PATCH_BUNDLED_FALLBACK_LOCAL is not set
    # CT_PATCH_LOCAL_FALLBACK_BUNDLED is not set
    # CT_PATCH_NONE is not set
    CT_PATCH_ORDER="bundled"

    #
    # Build behavior
    #
    CT_PARALLEL_JOBS=2
    CT_LOAD=""
    CT_USE_PIPES=y
    CT_EXTRA_CFLAGS_FOR_BUILD=""
    CT_EXTRA_LDFLAGS_FOR_BUILD=""
    CT_EXTRA_CFLAGS_FOR_HOST=""
    CT_EXTRA_LDFLAGS_FOR_HOST=""
    # CT_CONFIG_SHELL_SH is not set
    # CT_CONFIG_SHELL_ASH is not set
    CT_CONFIG_SHELL_BASH=y
    # CT_CONFIG_SHELL_CUSTOM is not set
    CT_CONFIG_SHELL="${bash}"

    #
    # Logging
    #
    # CT_LOG_ERROR is not set
    # CT_LOG_WARN is not set
    CT_LOG_INFO=y
    # CT_LOG_EXTRA is not set
    # CT_LOG_ALL is not set
    # CT_LOG_DEBUG is not set
    CT_LOG_LEVEL_MAX="INFO"
    # CT_LOG_SEE_TOOLS_WARN is not set
    CT_LOG_PROGRESS_BAR=y
    CT_LOG_TO_FILE=y
    CT_LOG_FILE_COMPRESS=y

    #
    # Target options
    #
    CT_ARCH="arm"
    CT_ARCH_SUPPORTS_BOTH_MMU=y
    CT_ARCH_SUPPORTS_BOTH_ENDIAN=y
    CT_ARCH_SUPPORTS_32=y
    CT_ARCH_SUPPORTS_64=y
    CT_ARCH_SUPPORTS_WITH_ARCH=y
    CT_ARCH_SUPPORTS_WITH_CPU=y
    CT_ARCH_SUPPORTS_WITH_TUNE=y
    CT_ARCH_SUPPORTS_WITH_FLOAT=y
    CT_ARCH_SUPPORTS_WITH_FPU=y
    CT_ARCH_SUPPORTS_SOFTFP=y
    CT_ARCH_DEFAULT_HAS_MMU=y
    CT_ARCH_DEFAULT_LE=y
    CT_ARCH_DEFAULT_32=y
    CT_ARCH_ARCH="armv7-m"
    CT_ARCH_CPU="cortex-m4"
    CT_ARCH_TUNE="cortex-m4"
    CT_ARCH_FPU=""
    # CT_ARCH_BE is not set
    CT_ARCH_LE=y
    CT_ARCH_32=y
    # CT_ARCH_64 is not set
    CT_ARCH_BITNESS=32
    # CT_ARCH_FLOAT_HW is not set
    CT_ARCH_FLOAT_SW=y
    CT_TARGET_CFLAGS=""
    CT_TARGET_LDFLAGS=""
    # CT_ARCH_alpha is not set
    CT_ARCH_arm=y
    # CT_ARCH_avr32 is not set
    # CT_ARCH_blackfin is not set
    # CT_ARCH_m68k is not set
    # CT_ARCH_microblaze is not set
    # CT_ARCH_mips is not set
    # CT_ARCH_powerpc is not set
    # CT_ARCH_s390 is not set
    # CT_ARCH_sh is not set
    # CT_ARCH_sparc is not set
    # CT_ARCH_x86 is not set
    CT_ARCH_alpha_AVAILABLE=y
    CT_ARCH_arm_AVAILABLE=y
    CT_ARCH_avr32_AVAILABLE=y
    CT_ARCH_blackfin_AVAILABLE=y
    CT_ARCH_m68k_AVAILABLE=y
    CT_ARCH_microblaze_AVAILABLE=y
    CT_ARCH_mips_AVAILABLE=y
    CT_ARCH_powerpc_AVAILABLE=y
    CT_ARCH_s390_AVAILABLE=y
    CT_ARCH_sh_AVAILABLE=y
    CT_ARCH_sparc_AVAILABLE=y
    CT_ARCH_x86_AVAILABLE=y
    CT_ARCH_SUFFIX=""

    #
    # Generic target options
    #
    # CT_MULTILIB is not set
    # CT_ARCH_USE_MMU is not set
    CT_ARCH_ENDIAN="little"

    #
    # Target optimisations
    #
    # CT_ARCH_FLOAT_AUTO is not set
    # CT_ARCH_FLOAT_SOFTFP is not set
    CT_ARCH_FLOAT="soft"

    #
    # arm other options
    #
    CT_ARCH_ARM_MODE="thumb"
    # CT_ARCH_ARM_MODE_ARM is not set
    CT_ARCH_ARM_MODE_THUMB=y
    # CT_ARCH_ARM_INTERWORKING is not set
    CT_ARCH_ARM_EABI_FORCE=y
    CT_ARCH_ARM_EABI=y

    #
    # Toolchain options
    #

    #
    # General toolchain options
    #
    CT_FORCE_SYSROOT=y
    CT_USE_SYSROOT=y
    CT_SYSROOT_NAME="sysroot"
    CT_SYSROOT_DIR_PREFIX=""
    CT_WANTS_STATIC_LINK=y
    CT_STATIC_TOOLCHAIN=y
    CT_TOOLCHAIN_PKGVERSION="x64 to teensy"
    CT_TOOLCHAIN_BUGURL=""

    #
    # Tuple completion and aliasing
    #
    CT_TARGET_VENDOR="jwatte"
    CT_TARGET_ALIAS_SED_EXPR=""
    CT_TARGET_ALIAS=""

    #
    # Toolchain type
    #
    # CT_NATIVE is not set
    # CT_CROSS is not set
    # CT_CROSS_NATIVE is not set
    CT_CANADIAN=y
    CT_TOOLCHAIN_TYPE="canadian"

    #
    # Build system
    #
    CT_BUILD=""
    CT_BUILD_PREFIX=""
    CT_BUILD_SUFFIX=""

    #
    # Host system
    #
    CT_HOST="arm-jwatte-linux-gnueabihf"
    CT_HOST_PREFIX="/opt/cross/rpi/bin/arm-jwatte-linux-gnueabihf-"
    CT_HOST_SUFFIX=""

    #
    # Misc options
    #
    # CT_TOOLCHAIN_ENABLE_NLS is not set

    #
    # Operating System
    #
    CT_BARE_METAL=y
    CT_KERNEL="bare-metal"
    CT_KERNEL_bare_metal=y
    # CT_KERNEL_linux is not set
    CT_KERNEL_bare_metal_AVAILABLE=y
    CT_KERNEL_linux_AVAILABLE=y
    CT_KERNEL_windows_AVAILABLE=y

    #
    # Common kernel options
    #

    #
    # Binary utilities
    #
    CT_ARCH_BINFMT_ELF=y
    # CT_ARCH_BINFMT_FLAT is not set
    # CT_ARCH_BINFMT_FDPIC is not set
    CT_BINUTILS="binutils"
    CT_BINUTILS_binutils=y

    #
    # GNU binutils
    #
    CT_BINUTILS_V_2_24=y
    # CT_BINUTILS_V_2_23_2 is not set
    # CT_BINUTILS_V_2_23_1 is not set
    # CT_BINUTILS_V_2_22 is not set
    # CT_BINUTILS_V_2_21_53 is not set
    # CT_BINUTILS_V_2_21_1a is not set
    # CT_BINUTILS_V_2_20_1a is not set
    # CT_BINUTILS_V_2_19_1a is not set
    # CT_BINUTILS_V_2_18a is not set
    # CT_BINUTILS_CUSTOM is not set
    CT_BINUTILS_VERSION="2.24"
    CT_BINUTILS_2_24_or_later=y
    CT_BINUTILS_2_23_or_later=y
    CT_BINUTILS_2_22_or_later=y
    CT_BINUTILS_2_21_or_later=y
    CT_BINUTILS_2_20_or_later=y
    CT_BINUTILS_2_19_or_later=y
    CT_BINUTILS_2_18_or_later=y
    CT_BINUTILS_HAS_HASH_STYLE=y
    CT_BINUTILS_HAS_GOLD=y
    CT_BINUTILS_GOLD_SUPPORTS_ARCH=y
    CT_BINUTILS_HAS_PLUGINS=y
    CT_BINUTILS_HAS_PKGVERSION_BUGURL=y
    CT_BINUTILS_LINKER_LD=y
    # CT_BINUTILS_LINKER_GOLD is not set
    # CT_BINUTILS_LINKER_LD_GOLD is not set
    # CT_BINUTILS_LINKER_GOLD_LD is not set
    CT_BINUTILS_LINKERS_LIST="ld"
    CT_BINUTILS_LINKER_DEFAULT="bfd"
    CT_BINUTILS_EXTRA_CONFIG_ARRAY=""

    #
    # binutils other options
    #

    #
    # C-library
    #
    CT_LIBC="newlib"
    CT_LIBC_VERSION="2.1.0"
    CT_LIBC_newlib=y
    # CT_LIBC_none is not set
    CT_LIBC_eglibc_AVAILABLE=y
    CT_THREADS="none"
    CT_LIBC_glibc_AVAILABLE=y
    CT_LIBC_mingw_AVAILABLE=y
    CT_LIBC_musl_AVAILABLE=y
    CT_LIBC_newlib_AVAILABLE=y
    CT_LIBC_NEWLIB_V_2_1_0=y
    # CT_LIBC_NEWLIB_V_2_0_0 is not set
    # CT_LIBC_NEWLIB_V_1_20_0 is not set
    # CT_LIBC_NEWLIB_V_1_19_0 is not set
    # CT_LIBC_NEWLIB_V_1_18_0 is not set
    # CT_LIBC_NEWLIB_V_1_17_0 is not set
    # CT_LIBC_NEWLIB_CUSTOM is not set

    #
    # Architecture specific options
    #
    CT_LIBC_none_AVAILABLE=y
    CT_LIBC_uClibc_AVAILABLE=y
    CT_LIBC_SUPPORT_THREADS_NONE=y

    #
    # Common C library options
    #
    CT_THREADS_NONE=y

    #
    # newlib other options
    #
    # CT_LIBC_NEWLIB_IO_C99FMT is not set
    # CT_LIBC_NEWLIB_IO_LL is not set
    # CT_LIBC_NEWLIB_IO_FLOAT is not set
    CT_LIBC_NEWLIB_DISABLE_SUPPLIED_SYSCALLS=y
    CT_LIBC_NEWLIB_ENABLE_TARGET_OPTSPACE=y
    CT_LIBC_NEWLIB_EXTRA_CONFIG_ARRAY=""

    #
    # C compiler
    #
    CT_CC="gcc"
    CT_CC_VERSION="linaro-4.8-2014.04"
    CT_CC_CORE_PASSES_NEEDED=y
    CT_CC_CORE_PASS_1_NEEDED=y
    CT_CC_CORE_PASS_2_NEEDED=y
    CT_CC_gcc=y
    CT_CC_GCC_SHOW_LINARO=y
    # CT_CC_V_4_9_2 is not set
    # CT_CC_V_4_9_1 is not set
    # CT_CC_V_4_9_0 is not set
    CT_CC_V_linaro_4_8=y
    # CT_CC_V_4_8_3 is not set
    # CT_CC_V_4_8_2 is not set
    # CT_CC_V_4_8_1 is not set
    # CT_CC_V_4_8_0 is not set
    # CT_CC_V_linaro_4_7 is not set
    # CT_CC_V_4_7_4 is not set
    # CT_CC_V_4_7_3 is not set
    # CT_CC_V_4_7_2 is not set
    # CT_CC_V_4_7_1 is not set
    # CT_CC_V_4_7_0 is not set
    # CT_CC_V_linaro_4_6 is not set
    # CT_CC_V_4_6_4 is not set
    # CT_CC_V_4_6_3 is not set
    # CT_CC_V_4_6_2 is not set
    # CT_CC_V_4_6_1 is not set
    # CT_CC_V_4_6_0 is not set
    # CT_CC_V_linaro_4_5 is not set
    # CT_CC_V_4_5_3 is not set
    # CT_CC_V_4_5_2 is not set
    # CT_CC_V_4_5_1 is not set
    # CT_CC_V_4_5_0 is not set
    # CT_CC_V_linaro_4_4 is not set
    # CT_CC_V_4_4_7 is not set
    # CT_CC_V_4_4_6 is not set
    # CT_CC_V_4_4_5 is not set
    # CT_CC_V_4_4_4 is not set
    # CT_CC_V_4_4_3 is not set
    # CT_CC_V_4_4_2 is not set
    # CT_CC_V_4_4_1 is not set
    # CT_CC_V_4_4_0 is not set
    # CT_CC_V_4_3_6 is not set
    # CT_CC_V_4_3_5 is not set
    # CT_CC_V_4_3_4 is not set
    # CT_CC_V_4_3_3 is not set
    # CT_CC_V_4_3_2 is not set
    # CT_CC_V_4_3_1 is not set
    # CT_CC_V_4_2_4 is not set
    # CT_CC_V_4_2_2 is not set
    # CT_CC_CUSTOM is not set
    CT_CC_GCC_4_2_or_later=y
    CT_CC_GCC_4_3_or_later=y
    CT_CC_GCC_4_4_or_later=y
    CT_CC_GCC_4_5_or_later=y
    CT_CC_GCC_4_6_or_later=y
    CT_CC_GCC_4_7_or_later=y
    CT_CC_GCC_4_8=y
    CT_CC_GCC_4_8_or_later=y
    CT_CC_GCC_HAS_GRAPHITE=y
    CT_CC_GCC_USE_GRAPHITE=y
    CT_CC_GCC_HAS_LTO=y
    CT_CC_GCC_USE_LTO=y
    CT_CC_GCC_HAS_PKGVERSION_BUGURL=y
    CT_CC_GCC_HAS_BUILD_ID=y
    CT_CC_GCC_HAS_LNK_HASH_STYLE=y
    CT_CC_GCC_USE_GMP_MPFR=y
    CT_CC_GCC_USE_MPC=y
    CT_CC_GCC_HAS_LIBQUADMATH=y
    CT_CC_GCC_HAS_LIBSANITIZER=y
    # CT_CC_LANG_FORTRAN is not set
    CT_CC_SUPPORT_CXX=y
    CT_CC_SUPPORT_FORTRAN=y
    CT_CC_SUPPORT_JAVA=y
    CT_CC_SUPPORT_ADA=y
    CT_CC_SUPPORT_OBJC=y
    CT_CC_SUPPORT_OBJCXX=y
    CT_CC_SUPPORT_GOLANG=y

    #
    # Additional supported languages:
    #
    CT_CC_LANG_CXX=y

    #
    # gcc other options
    #
    CT_CC_ENABLE_CXX_FLAGS=""
    CT_CC_CORE_EXTRA_CONFIG_ARRAY=""
    CT_CC_EXTRA_CONFIG_ARRAY=""
    CT_CC_STATIC_LIBSTDCXX=y
    # CT_CC_GCC_SYSTEM_ZLIB is not set

    #
    # Optimisation features
    #

    #
    # Settings for libraries running on target
    #
    CT_CC_GCC_ENABLE_TARGET_OPTSPACE=y
    # CT_CC_GCC_LIBMUDFLAP is not set
    # CT_CC_GCC_LIBGOMP is not set
    # CT_CC_GCC_LIBSSP is not set
    # CT_CC_GCC_LIBQUADMATH is not set

    #
    # Misc. obscure options.
    #
    # CT_CC_GCC_DISABLE_PCH is not set
    # CT_CC_GCC_LDBL_128 is not set
    CT_CC_GCC_BUILD_ID=y
    CT_CC_GCC_LNK_HASH_STYLE_DEFAULT=y
    # CT_CC_GCC_LNK_HASH_STYLE_SYSV is not set
    # CT_CC_GCC_LNK_HASH_STYLE_GNU is not set
    # CT_CC_GCC_LNK_HASH_STYLE_BOTH is not set
    CT_CC_GCC_LNK_HASH_STYLE=""
    # CT_CC_GCC_DEC_FLOAT_AUTO is not set
    # CT_CC_GCC_DEC_FLOAT_BID is not set
    # CT_CC_GCC_DEC_FLOAT_DPD is not set
    CT_CC_GCC_DEC_FLOATS_NO=y
    CT_CC_GCC_DEC_FLOATS="no"

    #
    # Debug facilities
    #
    # CT_DEBUG_dmalloc is not set
    # CT_DEBUG_duma is not set
    # CT_DEBUG_gdb is not set
    # CT_DEBUG_ltrace is not set
    # CT_DEBUG_strace is not set

    #
    # Companion libraries
    #
    CT_COMPLIBS_NEEDED=y
    CT_GMP_NEEDED=y
    CT_MPFR_NEEDED=y
    CT_ISL_NEEDED=y
    CT_CLOOG_NEEDED=y
    CT_MPC_NEEDED=y
    CT_COMPLIBS=y
    CT_GMP=y
    CT_MPFR=y
    CT_ISL=y
    CT_CLOOG=y
    CT_MPC=y
    CT_GMP_V_6_0_0=y
    # CT_GMP_V_5_1_3 is not set
    # CT_GMP_V_5_1_1 is not set
    # CT_GMP_V_5_0_2 is not set
    # CT_GMP_V_5_0_1 is not set
    # CT_GMP_V_4_3_2 is not set
    # CT_GMP_V_4_3_1 is not set
    # CT_GMP_V_4_3_0 is not set
    CT_GMP_VERSION="6.0.0a"
    CT_MPFR_V_3_1_2=y
    # CT_MPFR_V_3_1_0 is not set
    # CT_MPFR_V_3_0_1 is not set
    # CT_MPFR_V_3_0_0 is not set
    # CT_MPFR_V_2_4_2 is not set
    # CT_MPFR_V_2_4_1 is not set
    # CT_MPFR_V_2_4_0 is not set
    CT_MPFR_VERSION="3.1.2"
    CT_ISL_V_0_12_2=y
    # CT_ISL_V_0_11_1 is not set
    CT_ISL_VERSION="0.12.2"
    CT_CLOOG_V_0_18_1=y
    # CT_CLOOG_V_0_18_0 is not set
    CT_CLOOG_VERSION="0.18.1"
    CT_CLOOG_0_18_or_later=y
    CT_MPC_V_1_0_2=y
    # CT_MPC_V_1_0_1 is not set
    # CT_MPC_V_1_0 is not set
    # CT_MPC_V_0_9 is not set
    # CT_MPC_V_0_8_2 is not set
    # CT_MPC_V_0_8_1 is not set
    # CT_MPC_V_0_7 is not set
    CT_MPC_VERSION="1.0.2"

    #
    # Companion libraries common options
    #
    # CT_COMPLIBS_CHECK is not set

    #
    # Companion tools
    #

    #
    # READ HELP before you say 'Y' below !!!
    #
    # CT_COMP_TOOLS is not set

    #
    # Test suite
    #
    # CT_TEST_SUITE_GCC is not set

**Comment by jwatte** [comment]
The patch I use to get around the EOF problem:


    diff --git a/scripts/build/cc/gcc.sh b/scripts/build/cc/gcc.sh
    index 632bc8c..b6c4948 100644
    --- a/scripts/build/cc/gcc.sh
    +++ b/scripts/build/cc/gcc.sh
    @@ -218,7 +218,7 @@ do_cc_core_backend() {
                 extra_config+=("--enable-threads=no")
                 extra_config+=("--disable-shared")
                 extra_user_config=( "${CT_CC_EXTRA_CONFIG_ARRAY[@]}" )
    -            copy_headers=n
    +            copy_headers=y
                 ;;
             *)
                 CT_Abort "Internal Error: 'mode' must be one of: 'static', 'shared' or 'baremetal', not '${mode:-(empty)}'"
    @@ -227,8 +227,13 @@ do_cc_core_backend() {

         if [ "${CT_CC_GCC_HAS_PKGVERSION_BUGURL}" = "y" ]; then
             # Bare metal delivers the core compiler as final compiler, so add version info and bugurl
    -        extra_config+=("--with-pkgversion=${CT_PKGVERSION}")
    -        [ -n "${CT_TOOLCHAIN_BUGURL}" ] && extra_config+=("--with-bugurl=${CT_TOOLCHAIN_BUGURL}")
    +        if [ "${mode}" = "baremetal" ]; then
    +            CT_DoLog DEBUG "Copying headers from newlib source to install area of bootstrap gcc, so it can build libstdc++"
    +            CT_DoExecLog ALL cp -a "${CT_SRC_DIR}/newlib-${CT_LIBC_VERSION}/newlib/libc/include/." "${prefix}/${CT_TARGET}/include"
    +        else
    +            CT_DoLog DEBUG "Copying headers to install area of bootstrap gcc, so it can build libgcc2"
    +            CT_DoExecLog ALL cp -a "${CT_HEADERS_DIR}" "${prefix}/${CT_TARGET}/include"
    +        fi
         fi

         if [ "${copy_headers}" = "y" ]; then

**Comment by bhundven** [comment]
@jwatte Could you try the patch above from @davidholsgrove and confirm?

Happy New Year's!

-Bryan

**Comment by jwatte** [comment]
The first half of that was logically equal to the patch for gcc I had applied.
The second half for newlib was new -- I'm testing that now.

**Comment by jwatte** [comment]
Nope, same problem with those patches applied :-(
Note that the same target build works when building cross, rather than Canadian. Don't know what that's about.
Also, it's trying to #include another fenv.h (presumably from the system,) which doesn't actually exist, as it's bare-metal.


    [ALL  ]    make[3]: Entering directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3'
    [ALL  ]    Making all in include
    [ALL  ]    make[4]: Entering directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include'
    [ALL  ]    mkdir -p ./arm-jwatte-eabi/bits/stdc++.h.gch
    [ALL  ]    mkdir -p ./arm-jwatte-eabi/bits/stdc++.h.gch
    [ALL  ]    arm-jwatte-eabi-c++     -x c++-header -nostdinc++ -g -Os -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/arm-jwatte-eabi -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include -I/usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/libsupc++ -I/opt/cross/rpi/include -O2 -g -std=gnu++0x /usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/include/precompiled/stdc++.h   -o arm-jwatte-eabi/bits/stdc++.h.gch/O2ggnu++0x.gch
    [ALL  ]    arm-jwatte-eabi-c++     -x c++-header -nostdinc++ -g -Os -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/arm-jwatte-eabi -I/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include -I/usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/libsupc++ -I/opt/cross/rpi/include -O2 -g /usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/include/precompiled/stdc++.h -o arm-jwatte-eabi/bits/stdc++.h.gch/O2g.gch
    [ALL  ]    In file included from /usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/cfenv:41:0,
    [ALL  ]                     from /usr/local/src/cross-source-target/rpi-teensy/.build/src/gcc-linaro-4.8-2014.04/libstdc++-v3/include/precompiled/stdc++.h:53:
    [ERROR]    /usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include/fenv.h:36:24: fatal error: fenv.h: No such file or directory
    [ALL  ]     # include_next <fenv.h>
    [ALL  ]                            ^
    [ALL  ]    compilation terminated.
    [ERROR]    make[4]: *** [arm-jwatte-eabi/bits/stdc++.h.gch/O2ggnu++0x.gch] Error 1
    [ALL  ]    make[4]: *** Waiting for unfinished jobs....
    [ALL  ]    make[4]: Leaving directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3/include'
    [ERROR]    make[3]: *** [all-recursive] Error 1
    [ALL  ]    make[3]: Leaving directory `/usr/local/src/cross-source-target/rpi-teensy/.build/arm-jwatte-eabi/build/build-cc-final/arm-jwatte-eabi/libstdc++-v3'

**Comment by davidholsgrove** [comment]
Hi Jon,
Have you tried disabling precompiled headers in your config?

https://github.com/crosstool-ng/crosstool-ng/blob/master/config/cc/gcc.in.2#L173-182

From what I remember I hit a similar bug to yours 2 years ago which prompted those patches in my pull request (https://www.cygwin.com/ml/crossgcc/2012-10/msg00109.html), but cant recall if it was exactly the same...

thanks,
David

**Comment by jwatte** [comment]
I did, but that was before the other patch. Let me try that again.

Jw

**Comment by jwatte** [comment]
I made it work as follows:
# Apply the above patch
# Build both cross and canadian tools without PCH
# Build the cross and canadian tools into the same prefix directory
Step 3 was required, else some header files were not found.
Thus, it's not "working as it should," but perhaps it's "somewhat limping along..."
The binary produced on amd64 does execute on Raspberry Pi, and generates what seems like valid cortex-m4 output, although I have other runtime library problems that make it not yet possible for me to actually test the end result.

**Comment by bhundven** [comment]
Which ```above``` patch? The one you supplied or the one from @davidholsgrove ?

**Comment by jwatte** [comment]
The one from @davidholsgrove
