### ISSUE TITLE
How to compile cross tool link based on aarch64 architecture and musl Library？

### ISSUE THREAD

**Issue by skychengzhixing** [crosstool-ng/crosstool-ng#1804]
hi，friends：
I want to compile cross tool link based on aarch64 architecture and musl Library，but I don't know how to configure for it？
I use the following command to view：
ct-ng list-samples  
As a result, the default configuration appears to have only x_ 86 is a tool chain about musl？

How to compile a tool chain similar to aarch64-Linux-musl?
How to select the version of musl for compiling tool chain？

I look forward to your reply！

**Comment by bhundven** [comment]
This is not an issue with crosstool-ng.  I would suggest starting a thread on crossgcc@sourceware.org, which is a great place to discuss cross-compilers.
