### ISSUE TITLE
Incorrect symlink paths of files in lib64

### ISSUE THREAD

**Issue by arpitjindal** [crosstool-ng/crosstool-ng#1807]
Crosstool-ng: 1.25.0, 1.24.0
Host OS: Debian Testing(Bookwork)

Hello, 

Recently, I observed that the paths of files(libs) in lib64 directory (top level and not the one in sysroot, for eg. `x86_64-unknown-linux-gnu/lib64/`), are having incorrect symlink paths. For eg. the following files:

```
lrwxrwxrwx 1 jindal jindal  85 Aug 19 17:54 libasan.a -> /../../../../../../../../../../../../x86_64-unknown-linux-gnu/sysroot/lib64/libasan.a
lrwxrwxrwx 1 jindal jindal  93 Aug 19 17:54 libasan_preinit.o -> /../../../../../../../../../../../../x86_64-unknown-linux-gnu/sysroot/lib64/libasan_preinit.o
lrwxrwxrwx 1 jindal jindal  86 Aug 19 17:54 libasan.so -> /../../../../../../../../../../../../x86_64-unknown-linux-gnu/sysroot/lib64/libasan.so
lrwxrwxrwx 1 jindal jindal  88 Aug 19 17:54 libasan.so.6 -> /../../../../../../../../../../../../x86_64-unknown-linux-gnu/sysroot/lib64/libasan.so.6
```

This is only the problem when in .config, following is the value for prefix dir:
`CT_PREFIX_DIR="${CT_TOP_DIR}/../x-tools/${CT_TARGET}"`

If the above is an absolute path, then it creates correct symlinks.

Let me know if you need .config. The above issue should be easily reproducible. I built for intel x86_64 target.

[.config](https://teamviewer-my.sharepoint.com/:u:/p/arpit_jindal/EV55xk4K1QVOjgvDXPa14n0BHPZV4zLxuyqBqR_ROJ58vA?e=jhjBNn)
[build.log](https://teamviewer-my.sharepoint.com/:u:/p/arpit_jindal/Ebn5zOwhLDBOtsWO5Gsvy-oBTIJunJfTm6Pf4A4T_wgc3Q?e=H1FmIj)

Best regards
Arpit Jindal

**Comment by bhundven** [comment]
I would just attach the build.log and the config

**Comment by arpitjindal** [comment]
Done. Attached in the original post.

**Comment by bhundven** [comment]
Either Chris or I will take a look tomorrow. I have an idea to fox it.

**Comment by bhundven** [comment]
@cpackham Yea, just convert it to an absolute path.

**Comment by cpackham** [comment]
Hmm it gets stranger. It looks like we should be sanitizing `CT_PREFIX_DIR` in [crosstool-NG.sh](https://github.com/crosstool-ng/crosstool-ng/blob/3020aca6bb00e1d0a1cef3ab6d28b578c7df6520/scripts/crosstool-NG.sh#L75) so by the time we get to the code in gcc.sh it should have been resolved to an absolute path.
