### ISSUE TITLE
Not Show All version for Linux In Arch Linux LTS

### ISSUE THREAD

**Issue by MOHAMED19OS** [crosstool-ng/crosstool-ng#1808]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- crosstool-NG version:
- the least version in GitHub
`GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
`

- host OS and its version:
`Arch Linux x86_64 - 5.15.62-1-lts   KDE:  Plasma 5.25.4`

The problem is that it does not show the latest version of Linux

![Kazam_screenshot_00000](https://user-images.githubusercontent.com/47327706/186128275-3122fd9c-147b-4882-b0f9-ce06d79e4eff.png)

tested in Ubuntu LTS in kernel 5.15.50 and all work OK

**Comment by cpackham** [comment]
Those newer versions require rsync to be installed on the build machine

**Comment by MOHAMED19OS** [comment]
@cpackham 
thanks All, OK Now
