### ISSUE TITLE
Issue getting C Library to compile on Mac M1

### ISSUE THREAD

**Issue by xianrecords2015** [crosstool-ng/crosstool-ng#1814]
I am using 1.25.0.77_3020aca Crosstool

When I run ct-ng build, I get an error at the Installing C Library stage:

rpc_main.c:329:17: error: variable has incomplete type 'struct stat64'

Any idea how to fix it ?

**Comment by TommyMurphyTM1234** [comment]
You probably need to post more info as per the guidelines...

> ### Issue submission guidelines
> See [detailed guidelines](http://crosstool-ng.github.io/support/)
> In short:
> - Report crosstool-NG version
> - Report host OS and its version
> - Attach `.config` (unless the issue is not related to any configuration)
> - Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by TommyMurphyTM1234** [comment]
Same problem as reported here perhaps?

https://github.com/crosstool-ng/crosstool-ng/issues/1789

**Comment by xianrecords2015** [comment]
Yes that is the same issue. Was able to get further in the compilation but got the following error during cross-gdb

Error no usable python found in /usr/bin/python3

I have both python and python3 installed on my system

**Comment by TommyMurphyTM1234** [comment]
> got the following error during cross-gdb
> 
> Error no usable python found in /usr/bin/python3

Do you mean when CT-NG is building the cross gdb or when you're running the CT-NG generated gdb?

If the former, then you'll probably need to provide more info as per the aforementioned posting guidelines.

**Comment by xianrecords2015** [comment]
Yes it seems to be the same issue:

How do I change the /gdb/python/python-config.py and comment out these two lines:

 if getvar('LINKFORSHARED') is not None:
  libs.extend(getvar('LINKFORSHARED').split())

and re-run the ct-ng build without having everything to re-run. (It takes 40mns to get to that step) 

Also if I restart ct-ng build it overwrite the python-config.py

Thanks

**Comment by TommyMurphyTM1234** [comment]
I thought that https://github.com/crosstool-ng/crosstool-ng/issues/1308 explained how to fix or work around the issue?

**Comment by xianrecords2015** [comment]
It does show what to do with the python-config.py but as I was stating above, that file gets overwritten every time you run ct-ng build.

So my questions are:

- Can you run ct-ng build from the step that failed instead of the beginning ?
- How can I avoid the python-config.py to be overwritten ?

These were not explained in the #1308 

Thanks

**Comment by TommyMurphyTM1234** [comment]
If you know the build step at which you need to stop and make changes then maybe this will help?

https://crosstool-ng.github.io/docs/build/

**Comment by bhundven** [comment]
Please try again with latest git

**Comment by xianrecords2015** [comment]
It works now. Thanks a lot
