### ISSUE TITLE
CT_CC_GCC_ENABLE_DEFAULT_PIE incompatible with old libc

### ISSUE THREAD

**Issue by calebzulawski** [crosstool-ng/crosstool-ng#1819]
This occurs on master (try building x86_64-centos7-linux-gnu).

New versions of glibc add `-fno-pie` in the makefile, but old versions of glibc are unaware of this flag.  I think it might be acceptable to unconditionally add `-fno-pie` when building glibc.

**Comment by cpackham** [comment]
Any idea which version this came in with? It should be easy enough to make CT_CC_GCC_ENABLE_DEFAULT_PIE dependent on a particular glibc version

**Comment by TommyMurphyTM1234** [comment]
Hi @cpackham - is this the commit that introduced it?

* https://github.com/crosstool-ng/crosstool-ng/commit/a9f77be56f9707eb83cffa461e48de9e3025dc5e

**Comment by cpackham** [comment]
Yep that's the one. Looks like glibc 2.17 and glibc 2.19 aren't happy with DEFAULT_PIE but glibc 2.23 and newer are fine. I do wonder if there is something that can be done to decide when default PIE can be enabled but it got overly complicated when I tried to come up with something, perhaps the best approach is to update those samples to unset the option
