### ISSUE TITLE
rtld.c:854: Error: operand type mismatch for `movq'

### ISSUE THREAD

**Issue by ddumont** [crosstool-ng/crosstool-ng#1825]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version: git revision c803bb71f65be256152d55f30897f057f1618acc
- Report host OS and its version RHEL 9
- Attach `.config` (unless the issue is not related to any configuration) 
[dot-config.txt](https://github.com/crosstool-ng/crosstool-ng/files/9561363/dot-config.txt)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/9561359/build.log)

**Comment by dixyes** [comment]
it's a glibc problem, 2.17 just wont build on newer gcc

try this (put it to `packages/glibc/2.17/0070-movq-fix.patch` or `$PREFIX/share/crosstool-ng/packages/glibc/2.17/0070-movq-fix.patch` if you have installed ct-ng):
```diff
--- a/nptl/sysdeps/x86_64/tls.h 2023-02-21 12:21:03.447289149 +0800
+++ b/nptl/sysdeps/x86_64/tls.h 2023-02-21 12:26:16.244966019 +0800
@@ -263,8 +263,11 @@
              4 or 8.  */                                                     \
           abort ();                                                          \
                                                                              \
+        /* Since movq takes a signed 32-bit immediate or a register source   \
+           operand, use "er" constraint for 32-bit signed integer constant   \
+           or register.  */                                                  \
         asm volatile ("movq %q0,%%fs:%P1" :                                  \
-                      : IMM_MODE ((uint64_t) cast_to_integer (value)),       \
+                       : "er" ((uint64_t) cast_to_integer (value)),          \
                         "i" (offsetof (struct pthread, member)));            \
        }})

@@ -288,8 +291,11 @@
              4 or 8.  */                                                     \
           abort ();                                                          \
                                                                              \
+        /* Since movq takes a signed 32-bit immediate or a register source   \
+           operand, use "er" constraint for 32-bit signed integer constant   \
+           or register.  */                                                  \
         asm volatile ("movq %q0,%%fs:%P1(,%q2,8)" :                          \
-                      : IMM_MODE ((uint64_t) cast_to_integer (value)),       \
+                      : "er" ((uint64_t) cast_to_integer (value)),           \
                         "i" (offsetof (struct pthread, member[0])),          \
                         "r" (idx));                                          \
        }})
```

related: https://github.com/bminor/glibc/commit/b1ec623ed50bb8c7b9b6333fa350c3866dbde87f

building this old glibc also needs disable `CT_CC_GCC_ENABLE_DEFAULT_PIE` (`C compiler` -> `Enable Position Independent Executable as default`), see #1196

**Comment by honeway** [comment]
> it's a glibc problem, 2.17 just wont build on newer gcc
> 
> try this (put it to `packages/glibc/2.17/0070-movq-fix.patch` or `$PREFIX/share/crosstool-ng/packages/glibc/2.17/0070-movq-fix.patch` if you have installed ct-ng):
> 
> ```diff
> --- a/nptl/sysdeps/x86_64/tls.h 2023-02-21 12:21:03.447289149 +0800
> +++ b/nptl/sysdeps/x86_64/tls.h 2023-02-21 12:26:16.244966019 +0800
> @@ -263,8 +263,11 @@
>               4 or 8.  */                                                     \
>            abort ();                                                          \
>                                                                               \
> +        /* Since movq takes a signed 32-bit immediate or a register source   \
> +           operand, use "er" constraint for 32-bit signed integer constant   \
> +           or register.  */                                                  \
>          asm volatile ("movq %q0,%%fs:%P1" :                                  \
> -                      : IMM_MODE ((uint64_t) cast_to_integer (value)),       \
> +                       : "er" ((uint64_t) cast_to_integer (value)),          \
>                          "i" (offsetof (struct pthread, member)));            \
>         }})
> 
> @@ -288,8 +291,11 @@
>               4 or 8.  */                                                     \
>            abort ();                                                          \
>                                                                               \
> +        /* Since movq takes a signed 32-bit immediate or a register source   \
> +           operand, use "er" constraint for 32-bit signed integer constant   \
> +           or register.  */                                                  \
>          asm volatile ("movq %q0,%%fs:%P1(,%q2,8)" :                          \
> -                      : IMM_MODE ((uint64_t) cast_to_integer (value)),       \
> +                      : "er" ((uint64_t) cast_to_integer (value)),           \
>                          "i" (offsetof (struct pthread, member[0])),          \
>                          "r" (idx));                                          \
>         }})
> ```
> 
> related: [bminor/glibc@b1ec623](https://github.com/bminor/glibc/commit/b1ec623ed50bb8c7b9b6333fa350c3866dbde87f)
> 
> building this old glibc also needs disable `CT_CC_GCC_ENABLE_DEFAULT_PIE` (`C compiler` -> `Enable Position Independent Executable as default`), see #1196

I tried the patch. But the issue still exists. How to known whether the patch is applied?

**Comment by misterBart** [comment]
Bumped into the same problem today.
Therefore I cloned from git the master branch, but the problem also exists there.
My changes to preset `x86_64-unknown-linux-gnu`:

- Linux 6.2.12
- binutils 2.38
- glibc 2.17
- gcc 12.3 and disabled `Optimize gcc libs for size`

N.B. Options `Build and install locales` and `Enable Position Independent Executable as default` are disabled. So that does not seems to solve the problem in this issue.
Attached my config and a trimmed build.log (original build.log was too big for github.com).
Problem does not exist with glibc 2.19.
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/13413721/config.txt)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/13413723/build.log)

**Comment by honeway** [comment]
I fixed the issue on my side by changing the source code according to the patch instead of using patch file. And disable the mentioned PIE.

**Comment by cpackham** [comment]
If someone wants to go ahead and submit that as a proper patch for crosstool-ng to carry that'd be great. Ideally as a backport of the upstream glibc fix.
