### ISSUE TITLE
Can't use VFP registers for armhf

### ISSUE THREAD

**Issue by bverhagen** [crosstool-ng/crosstool-ng#1826]
Crosstool-ng version: 1.24.0
Host OS: Ubuntu Bionic
Target OS: Debian stretch (armhf)
Config: see attachment (renamed to .config.txt so Github accepts it): [arm-debianstretch-linux-gnueabihf.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/9568002/arm-debianstretch-linux-gnueabihf.config.txt)
Build log: not attached. The build succeeds successfully.

I am cross-building to a armv7a target with VFP floating point registers.
Once I compile a binary using mostly the 'default' settings (using `-march=armv7-a+fp`), it seems the resulting object files are not using VFP registers. Hence, I get an error when linking with proprietary libraries that do use these registers. When I add `-mfpu=vfp -mfloat-abi=hard`, I get: 

```
/opt/sysroot/armhf/usr/include/gnu/stubs.h:10:11: fatal error: gnu/stubs-hard.h: No such file or directory
 # include <gnu/stubs-hard.h>
           ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

I know that `libc6-dev` provides this for my target, but as far as I understand the process, it is crosstool-ng that should provide the right headers and development files for this and _not_ `libc6-dev`. In fact, I explicitly exclude libc6-dev from being installed in order to be able to properly compile (which makes sense, as that one is associated with the target system compiler, not the crosstool-ng toolchain).

I am out of ideas on where to further look to resolve this issue. Do I overlook something in the config?

**Comment by cpackham** [comment]
The first thing I'd suggest trying is just set `  CT_ARCH_FLOAT="hard"` and leave `CT_ARCH_FPU`/`CT_TARGET_CFLAGS` as their defaults (empty). Then try the different options as per https://gcc.gnu.org/onlinedocs/gcc-12.2.0/gcc/ARM-Options.html#ARM-Options

**Comment by bverhagen** [comment]
@cpackham : I tried before with having only set `CT_ARCH_FLOAT="hard"` and that had the exact same problem.

Your link to the ARM options do mention a couple of different vfp modes (e.g. `-march=armv7-a+vfpv3`), so I'll retry with these.

**Comment by igorpupkinable** [comment]
The following may also help:
https://wiki.debian.org/ArmHardFloatPort/VfpComparison#FPU
