### ISSUE TITLE
crosstool-ng-1.25.0 build fails on cygwin for aarch-none-linux-gnu，please help me    = =。

### ISSUE THREAD

**Issue by alfred-lijun** [crosstool-ng/crosstool-ng#1837]
crosstool-NG version 1.25.0
Host : window10  cygwin
gcc：8.4.0
glibc：2.29

very depressed，final step failed  = =。

[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    /tmp/ccnHq02g.s:27: Error: selected processor does not support `casalb w3,w2,[x0]'

[ERROR]    make[5]: *** [Makefile:801: cas_1_1_.lo] Error 1
[ERROR]    make[5]: *** Waiting for unfinished jobs....

[ERROR]    /tmp/ccjN78EQ.s:21: Error: selected processor does not support `swpalb w1,w1,[x0]'

[ERROR]    make[5]: *** [Makefile:801: exch_1_1_.lo] Error 1
[ERROR]    make[4]: *** [Makefile:524: all-recursive] Error 1
[ERROR]    make[3]: *** [Makefile:360: all] Error 2
[ERROR]    make[2]: *** [Makefile:14311: all-target-libatomic] Error 2
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [Makefile:910: all] Error 2

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/9800379/config.txt)
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/9818459/build.zip)

**Comment by TommyMurphyTM1234** [comment]
You didn't attach the build log.

**Comment by alfred-lijun** [comment]
i have append another message, please help

**Comment by alfred-lijun** [comment]
i have fixed this problem，  add c flags “--disable-libatomic”

**Comment by k930520** [comment]
> i have fixed this problem， add c flags “--disable-libatomic”

I have the same problem, how add c flags “--disable-libatomic”
