### ISSUE TITLE
Support for original `uclibc`

### ISSUE THREAD

**Issue by CuckooEXE** [crosstool-ng/crosstool-ng#1839]
- crosstool-ng version 1.24.0

Hi! I'm looking to use `crosstool-ng` with the `cross-rs/cross` repository (cross-compiling Rust and Rust crates using `crosstool-ng`). My specific target platform is `mipsel-unknown-linux-uclibc`, however, the library on the target platform is `libuClibc-0.9.33.2.so`. I believe this means that the platform uses the _original_ `uClibc` rather than `uClibc-ng`, as `uClibc-ng` versions only go back to 1.0.0. I looked around in the `crosstool-ng` configuration for `uClibc` to see if I can get it to download the original `uClibc` instead of the next-generation, but I'm not getting very far with it. It all looks very specific to `uClibc-ng`.

Is compiling with the original `uClibc` still possible, and if so, what do I need to change?

**Comment by TommyMurphyTM1234** [comment]
Is anything here of any help?

* https://crosstool-ng.github.io/docs/caveats-features/

**Comment by cpackham** [comment]
Short answer is no. The original uclibc is no longer supported. The upstream project has been obsoleted by uclibc-ng so I don't see ct-ng adding it back.

When this kind of thing comes up I usually suggest static linking so you can use a different libc. With rust I think static linking with musl-libc was the default so I'd suggest sticking with that.

**Comment by CuckooEXE** [comment]
Ah I gotcha. Thank you for your help, I appreciate it!
