### ISSUE TITLE
reference to undefined variable 'archive_formats'

### ISSUE THREAD

**Issue by lion10** [crosstool-ng/crosstool-ng#1841]
- version: 1.24.0.88-c969be1
- OS: ubunut 5.15.0-48-generic
- when running ./bootstrap, this error raised
 ERROR :: maintainer/kconfig-versions.template:346: reference to undefined variable 'archive_formats'
 and this file can not be modified on it.
 Any suggestion?!
![Screenshot from 2022-10-25 15-34-43](https://user-images.githubusercontent.com/31984164/197701142-56524d73-0990-41c6-82b4-c0b8f60e9f4f.png)

**Comment by TommyMurphyTM1234** [comment]
Are you sure that you installed all pre-requisites for CT-NG?
https://github.com/crosstool-ng/crosstool-ng/blob/master/testing/docker/ubuntu22.04/Dockerfile

**Comment by lion10** [comment]
@TommyMurphyTM1234  I installed these libraries, and still the problem is not solved...

**Comment by TommyMurphyTM1234** [comment]
What if you use the latest release or even clone from the head of the repo? Why 1.24?

https://github.com/crosstool-ng/crosstool-ng/releases

**Comment by lion10** [comment]
@TommyMurphyTM1234 Thank you, I just reinstalled it again, and this problem fixed
