### ISSUE TITLE
configure: error: Need linker with .init_array/.fini_array support.

### ISSUE THREAD

**Issue by nephaste** [crosstool-ng/crosstool-ng#1845]
crosstool-NG version : latest git 1.25.0.95_7622b49
Ubuntu 20.04 x64 (in LXD container)

libc 2.19 / Kernel 5.010.60 / gcc 12.2
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/9909101/config.txt)
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/9909107/build.zip)

While previsous version was creating fine the toolchain, I updated to latest git ct-ng , i am now stuck in this error , i have no clue how to solve it,

thanks for your help

![2022-11-01_11-41-24](https://user-images.githubusercontent.com/3392684/199216554-3ee03681-4bcf-47aa-ab70-adf248420e7e.jpg)

**Comment by cpackham** [comment]
Did you run `ct-ng upgradeconfig` on your existing configuration?

**Comment by nephaste** [comment]
Hi thanks for the reply, it brings no change, same error

[logandconfig.zip](https://github.com/crosstool-ng/crosstool-ng/files/9917807/logandconfig.zip)

![image](https://user-images.githubusercontent.com/3392684/199434029-daffdf7f-0f41-4b0d-a698-9f0f9b9fd2b5.png)

![image](https://user-images.githubusercontent.com/3392684/199434113-907ed286-05fb-4b61-92ad-ea0743f57e57.png)

**Comment by TommyMurphyTM1234** [comment]
Did you heed this message?

> NOTE: Your configuration includes features marked EXPERIMENTAL.
> [ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
> [ERROR]  >> any experimental features. Otherwise, you'll need to debug it
> [ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
> [ERROR]  >> preferably, a fix.

**Comment by nephaste** [comment]
it is just to be able to run as root... with another user and option experimental feature disable problem is the same

![image](https://user-images.githubusercontent.com/3392684/199966581-4a6f5121-8bb4-438f-934c-8bd5be391514.png)

**Comment by cpackham** [comment]
This is reproducible on master (as of today) with the supplied config (run through `ct-ng upgradeconfig`). The actual error from libc's config.log is
```
configure:5858: x86_64-QNAP_FW501_GCC12-linux-gnu-gcc  -g -O2 -fcommon -U_FORTIFY_SOURCE          -Wno-missing-attributes -Wno-array-bounds -Wno-array-parameter -Wno-stringop-overflow -Wno-maybe-uninitialized -lpthread     -o conftest
                       conftest.c -static -nostartfiles -nostdlib
                       1>&5
/home/ctng/crosstool-ng/.build/x86_64-QNAP_FW501_GCC12-linux-gnu/buildtools/lib/gcc/x86_64-QNAP_FW501_GCC12-linux-gnu/12.3.0/../../../../x86_64-QNAP_FW501_GCC12-linux-gnu/bin/ld: cannot find -lpthread: No such file or directory
collect2: error: ld returned 1 exit status
configure:5861: $? = 1
configure:5874: result: no
configure:5877: error: Need linker with .init_array/.fini_array support.
```
The `-lpthread` is coming through because the config has `CT_GLIBC_EXTRA_CFLAGS` set. Fixing that the versions being used in this config seem to have an issue with PIE so that also needs disabling by un-setting `CT_CC_GCC_ENABLE_DEFAULT_PIE`. After that the build succeeds.
