### ISSUE TITLE
expat: bump from v2.4.1 to v2.5.0

### ISSUE THREAD

**Issue by cfriedt** [crosstool-ng/crosstool-ng#1856]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version: `crosstool-ng-1.25.0`
- Report host OS and its version: CentOS Stream 8

Was trying to build the Zephyr SDK from scratch, which was branched from `crosstool-ng-1.25.0`, and encountered this error:
```
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'expat-2.4.1'
[EXTRA]    Verifying SHA512 checksum for 'expat-2.4.1.tar.xz'
[ERROR]    Bad sha512 digest for expat-2.4.1.tar.xz: 718584400ea918a761a8e58e9caf9cfea7ece76a3d40dad7ff2666a759c4d10ca454e4632277b791d6344c61c24a0a00eae8a2523888a92aa17f72c11e05aa3e, expect 9dc760dbf701f75e55c4479d81417622f8c750d8473498458a382a4c2932a2976a059cb3589f88855188e5173ec7868d285c4601428e0ca625df7a59cf975191
[ERROR]    Digest verification failed; removing the download
```
Investigating the sourceforge mirror, it still seems to be maintained, but it was quite obvious that they had obsoleted v2.4.1 due to security vulnerabilities, suggesting that users upgrade to v2.4.7, which was released in March, 2022.

https://sourceforge.net/projects/expat/files/expat/2.4.1/

The v2.5.0 release is slightly more recent and addresses *additional* security vulnerabilities, so I thought it made sense to make the latest version available in crosstool-ng.

**Comment by cpackham** [comment]
Hmm. Odd that it didn't move on to the github mirror.
