### ISSUE TITLE
Cosmetic improvements for powerpc-e500v2-linux-gnuspe/crosstool.config

### ISSUE THREAD

**Issue by pali** [crosstool-ng/crosstool-ng#1867]
https://github.com/crosstool-ng/crosstool-ng/blob/master/samples/powerpc-e500v2-linux-gnuspe/crosstool.config

Format of `--enable-e500_double` gcc option is valid but strange. Canonical form is `--enable-e500-double`. Underscore in option names works just because autoconf/configure.ac replaces dashes by underscores. So I would suggest to rename `--enable-e500_double` to `--enable-e500-double`.

Specifying `-Wa,-me500x2` also works but is misleading. e500**x**2 refers to old Motorola naming which refers to e500 core with SP APU. The old e500**x**1 naming was probably not widely used and referred to e500 cores without SP APU support which was planned for MPC5500 products and released under e200 name. e500**x**2 was released under e500 and at the time only single floating point SPE was part of SP APU. Hence e500**x**2 here refers to e500**v**1 as double floating point was introduced later in e500**v**2. GNU LD does not distinguish between e500v1 and e500v2. It has just one common `-me500` flag for both e500v1 and e500v2 (`-me500x2` is just alias for `-me500`). So I would suggest to rename `-Wa,-me500x2` to `-Wa,-me500` because powerpc-e500v2-linux-gnuspe compiles for e500v2 and not older e500(v1).

CC: @cpackham

**Comment by cpackham** [comment]
Does `--enable-e500x2` or `--with-e500x2` do anything?

**Comment by pali** [comment]
Those are passed to binutils ./configure script? I was trying to find some information but seems that crosstool-ng is the only source of these flags. Next I compiled binutils two times, once with `--enable-spe=yes --enable-e500x2 --with-e500x2` flags and once without them. And both builds produces exactly same binaries. Therefore these flags seems to do nothing.

**Comment by pali** [comment]
Anyway, if you want to simplify target gcc flags then you can omit `-mfloat-gprs=double` flag when gcc is compiled with default cpu set to 8548.

I wrote some detailed information here: https://lists.buildroot.org/pipermail/buildroot/2022-December/656949.html

**Comment by pali** [comment]
And... gcc automatically pass `-me500` to _GNU as_ when gcc was invoked by `-mcpu=8548` or by `-mcpu=8540`.

**Comment by pali** [comment]
You let there `--enable-spe=yes`. So have you figured out that it does something? I would like to know it.

**Comment by pali** [comment]
Any information about `--enable-spe=yes` flag? Because my tests did not show any difference.
