### ISSUE TITLE
Build failed: aarch64 and armv7 with Linux-6.1.1, Glibc-2.32

### ISSUE THREAD

**Issue by rumas84** [crosstool-ng/crosstool-ng#1878]
CT_VERSION="1.25.0.117_66ac9e6"
Ubuntu-20.04.5
Linux-6.1.1, gcc-12.2.0, Glibc-2.32

> EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = aarch64-linux-gnu
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.23s (at 00:03)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 0.93s (at 00:04)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting autoconf-2.71
[EXTRA]    Patching autoconf-2.71
[EXTRA]    Extracting automake-1.16.1
[EXTRA]    Patching automake-1.16.1
[EXTRA]    Extracting linux-6.1.1
[EXTRA]    Patching linux-6.1.1
[EXTRA]    Extracting zlib-1.2.13
[EXTRA]    Patching zlib-1.2.13
[EXTRA]    Extracting gmp-6.2.1
[EXTRA]    Patching gmp-6.2.1
[EXTRA]    Extracting mpfr-4.1.0
[EXTRA]    Patching mpfr-4.1.0
[EXTRA]    Extracting isl-0.24
[EXTRA]    Patching isl-0.24
[EXTRA]    Extracting mpc-1.2.1
[EXTRA]    Patching mpc-1.2.1
[EXTRA]    Extracting ncurses-6.2
[EXTRA]    Patching ncurses-6.2
[EXTRA]    Extracting libiconv-1.16
[EXTRA]    Patching libiconv-1.16
[EXTRA]    Extracting gettext-0.21
[EXTRA]    Patching gettext-0.21
[EXTRA]    Extracting binutils-2.39
[EXTRA]    Patching binutils-2.39
[EXTRA]    Extracting gcc-12.2.0
[EXTRA]    Patching gcc-12.2.0
[EXTRA]    Extracting glibc-2.32
[EXTRA]    Patching glibc-2.32
[INFO ]  Extracting and patching toolchain components: done in 195.33s (at 03:19)
[INFO ]  =================================================================
[INFO ]  Installing autoconf for build
[EXTRA]    Configuring autoconf
[EXTRA]    Building autoconf
[EXTRA]    Installing autoconf
[INFO ]  Installing autoconf for build: done in 5.21s (at 03:25)
[INFO ]  =================================================================
[INFO ]  Installing automake for build
[EXTRA]    Configuring automake
[EXTRA]    Building automake
[EXTRA]    Installing automake
[INFO ]  Installing automake for build: done in 8.84s (at 03:34)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for build
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for build: done in 48.81s (at 04:22)
[INFO ]  =================================================================
[INFO ]  Installing zlib for host
[EXTRA]    Configuring zlib
[EXTRA]    Building zlib
[EXTRA]    Installing zlib
[INFO ]  Installing zlib for host: done in 4.09s (at 04:27)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 74.82s (at 05:41)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 40.32s (at 06:22)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[EXTRA]    Configuring ISL
[EXTRA]    Building ISL
[EXTRA]    Installing ISL
[INFO ]  Installing ISL for host: done in 98.34s (at 08:00)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 12.56s (at 08:13)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for host
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
**[ERROR]    cat: write error: Broken pipe**
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for host: done in 39.30s (at 08:52)
[INFO ]  =================================================================
[INFO ]  Installing libiconv for host
[EXTRA]    Skipping (included in GNU C library)
[INFO ]  Installing libiconv for host: done in 0.01s (at 08:52)
[INFO ]  =================================================================
[INFO ]  Installing gettext for host
[EXTRA]    Skipping (included in GNU C library)
[INFO ]  Installing gettext for host: done in 0.01s (at 08:52)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[EXTRA]    Installing ld wrapper
[INFO ]  Installing binutils for host: done in 752.10s (at 21:24)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[INFO ]  Installing kernel headers: done in 59.00s (at 22:24)
[INFO ]  =================================================================
[INFO ]  Installing core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]       '' --> lib (gcc)   lib64 (os)
[INFO ]  Installing core C gcc compiler: done in 2648.28s (at 66:32)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      make[3]: *** Cannot open jobserver /tmp/GMfifo22440r: No such file or directory.  Stop.
[ERROR]      make[2]: *** [Makefile:470: csu/subdir_lib] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@264]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1607]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@26]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 67:04.16)
[67:05] / make: *** [/home/b084s/crosscompile/bin/ct-ng:261: build] Error 2

**Comment by cpackham** [comment]
This is a bug in glibc's Makefile exposed by newer versions of GNU Make.
There is a patch for the newest glibc that needs backporting (it might
apply cleanly I haven't tried).

**Comment by rumas84** [comment]
> This is a bug in glibc's Makefile exposed by newer versions of GNU Make.

yes, i updated "make" to the latest version 4.4 (https://ftp.gnu.org/gnu/make/)
...???
;

**Comment by TommyMurphyTM1234** [comment]
> > This is a bug in glibc's Makefile exposed by newer versions of GNU Make.
> 
> yes, i updated "make" to the latest version 4.4 (https://ftp.gnu.org/gnu/make/) ...??? ;

I think that @cpackham means that you need to update or patch the glibc `Makefile`? You'll probably need to look at the glibc repository and change log.

**Comment by cpackham** [comment]
On Fri, 6 Jan 2023, 11:44 AM Tommy Murphy, ***@***.***> wrote:

> This is a bug in glibc's Makefile exposed by newer versions of GNU Make.
>
> yes, i updated "make" to the latest version 4.4 (
> https://ftp.gnu.org/gnu/make/) ...??? ;
>
> I think that @cpackham <https://github.com/cpackham> means that you need
> to update or patch the glibc Makefile? You'll probably need to look at
> the glibc repository and change log.
>
> We already have the required patch for glibc 2.36 it just needs
backporting to the other versions. I haven't had time to do it myself so if
someone else could do it that would be great otherwise I'll get to it
eventually.

**Comment by TommyMurphyTM1234** [comment]
@cpackham - sorry, I probably misunderstood originally. I guess that you mean that there's a fix available for the __crosstool-NG__ `Makefile` for `glibc` - __not__ for the upstream/main `glibc` `Makefile`, as I originally assumed?

This?

* https://github.com/crosstool-ng/crosstool-ng/pull/1861

**Comment by cpackham** [comment]
On Fri, 6 Jan 2023, 9:57 PM Tommy Murphy, ***@***.***> wrote:

> @cpackham <https://github.com/cpackham> - sorry, I probably misunderstood
> originally. I guess that you mean that there's a fix available for the
> *crosstool-NG* Makefile for glibc - *not* for the upstream/main glibc
> Makefile, as I originally assumed?
>
> This?
>
>    - #1861 <https://github.com/crosstool-ng/crosstool-ng/pull/1861>
>
>
Yes that's the fix. Just needs applying to the older versions.

**Comment by jsueprez** [comment]
Hello guys.. just a simple question.. I'm getting the same error with Glibc, How can I apply this patch to the Crosstool-ng?

**Comment by TommyMurphyTM1234** [comment]
> Hello guys.. just a simple question.. I'm getting the same error with Glibc, How can I apply this patch to the Crosstool-ng?

Clone and build the latest CT-NG sources which include @cpackham's earlier patch?

**Comment by jsueprez** [comment]
> 

Thanks Tommy, The only difference from my case is that I could not build the crosstool on my mac, I had to get it from homebrew.. 

I have add manually the [Patch file"0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch"](https://github.com/crosstool-ng/crosstool-ng/pull/1861/commits/02d43da96f9d66d5fa7612590f8debdc71fca74b) to /opt/homebrew/Cellar/crosstool-ng/1.25.0/share/crosstool-ng/packages/glibc/2.31/ here. 

But still get the same error...

My  build.log
[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/10424832/build.log.zip)

`ct-ng --version
GNU Make 4.4
Built for aarch64-apple-darwin22.1.0`

[copy.config.zip](https://github.com/crosstool-ng/crosstool-ng/files/10424864/copy.config.zip)

**Comment by cpackham** [comment]
If you haven't figured it out yet. For an existing ct-ng installation (installed via brew or a distro package). You want to get the patch file for the desired glibc version and save it to your local patches directory and then tell ct-ng where that directory is by setting `CT_LOCAL_PATCH_DIR`. e.g. for glibc-2.32
```
mkdir -p ~/patches/glibc/2.32
curl -L https://github.com/crosstool-ng/crosstool-ng/raw/master/packages/glibc/2.32/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch >~/patches/glibc/2.32/0003-Makerules-fix-MAKEFLAGS-assignment-for-upcoming-make.patch
ct-ng menuconfig
# navigate to "Extracting" menu, select  "Bundled, then local" and set "Local patch directory" to $HOME/patches
```

**Comment by rumas84** [comment]
Hello, 
still just one problem with sh4, i can't build SH4 Toolchain.

CT_VERSION="1.25.0.122_aa6cc4d"
Ubuntu-22.04.1
Linux-6.1.2, gcc-12.2.0, Glibc-2.25
`INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      collect2: error: ld returned 1 exit status
[ERROR]      make[3]: *** [../Makerules:582: /home/b084s/work-dir/.build/sh4-linux-gnu/build/build-libc/multilib/nptl/libpthread.so] Error 1
[ERROR]      make[2]: *** [Makefile:215: nptl/others] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@264]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1607]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@26]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 42:26.35)
[42:27] / gmake: *** [/home/b084s/crosscompile/bin/ct-ng:261: build] Error 2`

**Comment by TommyMurphyTM1234** [comment]
What does `build.log` contain?

**Comment by TommyMurphyTM1234** [comment]
So, it looks like this `assert` fails for some reason?

* https://github.com/bminor/binutils-gdb/blob/6cb7f6d92e4508274fab69c7acbbb961fc45dc70/bfd/elf32-sh.c#L2491
