### ISSUE TITLE
MUSL execinfo.h is missing

### ISSUE THREAD

**Issue by clauderobi** [crosstool-ng/crosstool-ng#1894]
I successfully created a tool chain, using 1.25.0 that targets system that uses the MUSL (on X86) library. The most notorious is Alpine Linux.

However, one of the open source library I am using uses execinfo.h, which is not part of the MUSL libc library.

I guess this is it a the fringe of OS, tool chain and C library responsibility.... I am wondering what is the most canonical way of handling this. Any suggestion?

**Comment by bhundven** [comment]
Alpine linux... :sigh:

Yea, so execinfo.h is a musl-libc thing... not specific to crosstool-ng. I suggest just installing libexecinfo.

**Comment by clauderobi** [comment]
Well, installing libexecinfo on the target won't help cross compiling for the said target...

**Comment by bhundven** [comment]
Oh, hrm.

**Comment by BenjaminBeichler** [comment]
Sorry for interrupting here, but why you use crosstool-ng and not simply build your software in a alpine docker container? Since I guess you do not target a different ISA like ARM, that is easier.

Nonetheless, for targeting other architectures the problem persists ;-)

**Comment by clauderobi** [comment]
I do target ARM, and also Windows. So my CI/CD is entirely integrated and running on Linux.

I also target naked containers as well, which is why I also want to have a fully static binary (not necessarily for all targets but for cases that make senses, particularly as sidecars for Kubenetes). My hope is that musl allows me to be fully static (where needed), the same way golang people claims...)
________________________________

**Comment by BenjaminBeichler** [comment]
Okay, that was not totally clear from you first post. Then of you really need some tackling with crosstool-ng. Good luck with static c-binaries, I keep fighting with them in some special projects ... maybe you find this handy: https://justine.lol/cosmopolitan/ (but I think only for x86)

**Comment by clauderobi** [comment]
Thank for the good luck. I do too have a special project at hand...

I only have 1 remaining library to compile (getdns), which complains about missing pthread. But this for tomorrow....

**Comment by bhundven** [comment]
@clauderobi Could you attach your .config and build.log. I just need this to repro the problem to make sure I make the correct change.

**Comment by clauderobi** [comment]
Sure, do you want me to put verbatim here? The log is 18MB...

For the time being, I was able to compile my project using an external libexecinfo.h 

But I bumped the musl version to 1.2.3 before of the lack of pthread_getname_np in earlier version

**Comment by cpackham** [comment]
Just create a tarball/zip of the two files and attach them here (it's not immediately obvious but you can drop files from your file browser onto github comments).

**Comment by clauderobi** [comment]
[muls-execinfo-issue.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/10747961/muls-execinfo-issue.tar.gz)

Here you go. You are right, I would not naturally do this with a large file.....

**Comment by wdlkmpx** [comment]
The alpine/void folks usually patch out stuff that doesn't work with musl, and many of the patches have already been upstreamed, execinfo.h is used to get a backtrace without gdb (or something like that), so it's not really needed for programs to work

You may need to compile and install
https://github.com/ianlancetaylor/libbacktrace

and pass `-lbacktrace` as a linker flag or something.. the lib may be a bit buggy though

Perhaps you should patch the source code. i.e: compile execinfo.h stuff only if `__GLIBC__` is defined.

```c
#ifdef __GLIBC__
#include <execinfo.h>
#endif

...
#ifdef __GLIBC__
backtrace(...)
#endif
```
Of course stdio.h must be included first

**Comment by clauderobi** [comment]
It is my opinion that the various C libraries should agree on what is standard and what is not. It should not be up to the programs to find out and adjust what was arbitrarily decided by each and every C library implementation. Except for things that are marked as optional. I know it is a dream tough...

There is this minimal execinfo lib: https://github.com/mikroskeem/libexecinfo
Its makefile needs to be tweaked a little for crosscompiling but otherwise it works.

It is a third party open source library (g3log), which uses execinfo.h for reporting the backtrace on violations so I can not change it. But adding libexec above does work. I know this because I did get some SIGSEGV to test it out!! ;-)

**Comment by wdlkmpx** [comment]
execinfo.h can also be just a header file with static functions... so there's no need to use linker flags... that's what I currently use

You can also find a couple of repos with some missing headers that increase compatibility with glibc

There are several libraries created to deal with glibc compatibility, there is also a lib to make musl somewhat binary compatible with glibc at runtime (shared libs)

But there's not a big lib to make musl at least 95% source compatible with glibc, that requires unifying several projects, I think I'm gonna do that, since I do compile many apps and libs, and musl is a "problem"

**Comment by cpackham** [comment]
So is there anything to do for this? MUSL doesn't have execinfo.h (it also doesn't have a lot of other things glibc has, which is kind of the point). This isn't really something crosstool-ng is going to be able to do anything about (one might argue that we should carry on of the alternatives mentioned above as a companion lib but I'd resist that fairly strongly). So other than a useful discussion about how MUSL != glibc which might help out future internet searchers (hi from the past) is there anything to be done here?
