### ISSUE TITLE
Testing package revision values?

### ISSUE THREAD

**Issue by keith-packard** [crosstool-ng/crosstool-ng#1898]
This is only 'kinda' an issue with crosstool-ng...

I'm planning an upcoming picolibc release that will include wchar_t support. To take advantage of that in crosstool-ng, the flags used to build libstdc++ need to change, removing `--disable-wchar_t`.

My question is if there is some way to detect that picolibc has this support by looking at the revision number (third digit) in the package, or if the only way to do this requires a change in the minor version (second digit). If the latter, then I'll label the next picolibc release '1.9' instead of '1.8.1', but as there are very few changes in the library otherwise, it doesn't really seem to merit a minor version bump like this.

**Comment by cpackham** [comment]
It should be possible either way. You just need to add a milestone and
adjust the relevant_pattern if you want to handle matching a revision.

**Comment by keith-packard** [comment]
thanks, this pattern appears to work, but I have to admit I'm still a bit fuzzy on how relevantize is supposed to work.

```
milestones='1.4 1.5 1.6 1.7 1.8 1.8.1'
relevantpattern='1.[4-7]|. 1.8.*|.'
```
