### ISSUE TITLE
Build failed during 'Installing C library'

### ISSUE THREAD

**Issue by GrubbyHalo** [crosstool-ng/crosstool-ng#1899]
I'm building on Arch Linux and regardless  of whether I use a custom or Released tarball for glibc I always end up getting an error:
`*** Cannot open jobserver /tmp/GMfifo926147r: No such file or directory.  Stop.`

[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/10805664/build.log.gz)
[config.gz](https://github.com/crosstool-ng/crosstool-ng/files/10805689/config.gz)

**Comment by cpackham** [comment]
That's a known issue with glibc and the latest GNU make. Either build from
ct-ng's master branch or grab the glibc patch and add it to your local
patches.

**Comment by GrubbyHalo** [comment]
> That's a known issue with glibc and the latest GNU make. Either build from
ct-ng's master branch or grab the glibc patch and add it to your local
patches.

Any idea where this issue is referenced and where I might find a patch ? I've tried the patches in the packages directory but to no avail.

**Comment by cpackham** [comment]
Hopefully this helps

https://github.com/crosstool-ng/crosstool-ng/issues/1878#issuecomment-1408157998

You'll need to adjust it for your glibc version and note that the name of the patch file changes as the older glibc versions have more bundled patches.

**Comment by retaildynamics-za** [comment]
> That's a known issue with glibc and the latest GNU make. Either build from
ct-ng's master branch or grab the glibc patch and add it to your local
patches.

It seems it doesn't matter what patches I apply and what version of cross-tools-ng I use the build for glibc always chokes with the above error. My dev machine unfortunately has the latest gnu make on it and I am loathe to downgrade... Oh well I guess I'll have to wait for the bug in GNU make to get fixed and compile on the target for now.
