### ISSUE TITLE
Enabling pie by default breaks many toolchains

### ISSUE THREAD

**Issue by keith-packard** [crosstool-ng/crosstool-ng#1900]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version: master (190b8392da5f0e51d3a116d14bf3391231c93798)
- Report host OS and its version: Debian unstable
- samples/arm-none-eabi (among others)

Commit a9f77be56f9707eb83cffa461e48de9e3025dc5e added a new configuration option, `CC_GCC_ENABLE_DEFAULT_PIE`, which controls the selection of the gcc `--enbable-default-pie` build flag. When enabled (as it is by default), gcc compiles all code in position independent executable form, which often places additional relocation information to be used by the operating system when loading the file. On a system without an operating system capable of doing this, the resulting executables fail to either link or run, depending on the sophistication of the link script used.

In the interest of backwards compatibility with existing crosstool-ng users, it seems like having this new option default to the old behavior would have been a safer choice.

**Comment by cpackham** [comment]
I'm tempted to say that we should have it `default y if LINUX` but you're right about the behaviour change for existing users. I see you've got a change in your PR for this. I'll take a look

**Comment by keith-packard** [comment]
Oh, that's actually a mistake in that PR -- I didn't intend to "fix" this issue silently, but I had been using that patch in my series for testing. Lemme update the series to skip that patch and push a separate PR that addresses only that change.
