### ISSUE TITLE
Rename `x86_64-pc-linux-gnu,arm-picolibc-eabi` to `x86_64-unknown-linux-gnu,arm-picolibc-eabi` and change `CT_HOST` in config

### ISSUE THREAD

**Issue by jbglaw** [crosstool-ng/crosstool-ng#1909]
With current git HEAD (9a08601c1a90c108a4d7188566c1a9cac13350f6), the `x86_64-pc-linux-gnu,arm-picolibc-eabi` Canadian Cross sample configuration does not build. The required precursor toolchain, `x86_64-pc-linux-gnu`, isn't available, though a proper sample configuration (`x86_64-unknown-linux-gnu`) would be available.

So I suggest to rename `x86_64-pc-linux-gnu,arm-picolibc-eabi` to `x86_64-unknown-linux-gnu,arm-picolibc-eabi` and change the `CT_HOST` value for this Canadian Cross target accordingly. By just changing CT_HOST, it does build for me.

This showed up on my testing setup (cf. http://toolchain.lug-owl.de/#news-2023-03-03-1), which showed that almost all configurations work out of the box. Just four won't build ad hoc, with this one being trivial to fix. Good job!

**Comment by cpackham** [comment]
Sounds reasonable to me. @keith-packard any thoughts?

**Comment by keith-packard** [comment]
None at all; I've never used Canadian Cross configurations.

**Comment by cpackham** [comment]
Ah right it was @jnohlgard that added the picolibc canadian config. We could do the rename but it would be pretty much the same as a non-canadian build (at least assuming the build machine is x86 linux). So I'm a bit caught between fixing it or removing it.

**Comment by jbglaw** [comment]
As there are few Canadian Cross configurations, I'd suggest to keep (reinstate) it. Right now, all mass-compilation on my side takes place in x86_64 based Debian "unstable" containers, but I'm probably diversifying that. This would make it a real Canadian Cross. (But before that, I'll implement NetBSD install tests for various machines, on real metal or in simulators.)

**Comment by jnohlgard** [comment]
the x86_64-pc-linux-gnu comes from the triple used by the Fedora toolchain. I don't mind if you change it to whatever suits the CI system, but I agree that it is useful to have the CI run at least one Canadian configuration, just to exercise that code path. There are several special cases in the compiler and libstdc++ scripts around if the build is a canadian or a native build.

**Comment by jbglaw** [comment]
Oh, so if the `-pc-` part actually exists somewhere (like in the Ubuntu setup), let's just keep it like that and rename the precursor toolchain instead? Or add it a second time, with `-pc-` instead of `-unknown-`?

In the end, the only thing that would be nice is that there *is* a toolchain definition available for whatever is mentioned in the CT_HOST config option of a Canadian Cross configuration. It's only the picolibc configuration where it's not matching properly, with the possibility of changing one or the other to match.

**Comment by cpackham** [comment]
I thought about renaming the first toolchain but decided that would
conflict with the distro installed toolchain which we should probably avoid.

**Comment by jnohlgard** [comment]
Actually, my mistake, the -pc-linux-gnu toolchain was not from Red Hat/Fedora, that one is named x86_64-redhat-linux-gcc. I can't remember anymore why I started using -pc-linux-gnu.

**Comment by jnohlgard** [comment]
The GCC documentation does give x86_64-pc-linux-gnu as an example of a host triple though so maybe that was where I got it from.

**Comment by jbglaw** [comment]
Thanks a lot!
