### ISSUE TITLE
Add strace 6.2 

### ISSUE THREAD

**Issue by cpackham** [crosstool-ng/crosstool-ng#1915]
https://lists.strace.io/pipermail/strace-devel/2023-February/011172.html

**Comment by bhundven** [comment]
So, should we pin the selected Linux X.Y version to force strace X.Y version... well, back to 4.13?

**Comment by cpackham** [comment]
strace is kept backwards compatible so kernel versions shouldn't matter (that's why I dropped the interim versions).
