### ISSUE TITLE
NOT A ISSUE JUST QUESTION

### ISSUE THREAD

**Issue by sufuk** [crosstool-ng/crosstool-ng#1921]
What is the latest version of crosstool-ng which "can" be used for gcc 4.2.3 I tried very old releases, I even see 4.2.2 and 4.2.4 together but I cannot find the version for gcc 4.2.3 please help.

Regards..
Sufuk

**Comment by cpackham** [comment]
gcc-4.2.3 was last supported in crosstool-ng-1.22.0~35 (a.k.a. 55d8497f). But you'll be facing an up hill battle to get it working (packages having moved, stuff generally not working on a modern build machine). It's probably a better use of your time to get your target platform updated to use a newer toolchain.

**Comment by sufuk** [comment]
> gcc-4.2.3 was last supported in crosstool-ng-1.22.0~35 (a.k.a. [55d8497](https://github.com/crosstool-ng/crosstool-ng/commit/55d8497fea996b070d8e7f6f6898e99e9981337a)). But you'll be facing an up hill battle to get it working (packages having moved, stuff generally not working on a modern build machine). It's probably a better use of your time to get your target platform updated to use a newer toolchain.

Hmm I will try that version unfortunately I cannot have the option to update the target platform because I am not the platform owner, But I'll try and keep you updated.

Thank you...

**Comment by bhundven** [comment]
In the future for general questions, there is a mailing list that we watch: https://sourceware.org/pipermail/crossgcc/
