### ISSUE TITLE
Build failed in "cortex-a55 + gcc 9.3 + glibc2.31 + CT_MULTILIB disable"

### ISSUE THREAD

**Issue by Allen4096** [crosstool-ng/crosstool-ng#1925]
Other settings remain unchanged, only the following settings are modified.
(1)cortex-a53 + gcc  9.3  + glibc 2.31 + kernel 5.4.124 + CT_MULTILIB **disable**， build PASS
(2)cortex-a55 + gcc  9.3  + glibc 2.31 + kernel 5.4.124 + CT_MULTILIB **disable**， build FAILED
(3)cortex-a55 + gcc  9.3  + glibc 2.31 + kernel 5.4.124 + CT_MULTILIB **enable**， build PASS
(4)cortex-a55 + gcc 11.3 + glibc 2.35 + kernel 5.4.124 + CT_MULTILIB **disable**， build PASS

PS: the `#2` is what I need, `#1`, `#3` and `#4` just for troublehshooting.

The error log for `#2` failure as follows
---------------
[INFO ]  =================================================================
[INFO ]  Installing core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing core C gcc compiler: done in 449.86s (at 16:26)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[ERROR]      configure: error: working alias attribute support required
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@215]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1608]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@40]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 16:27.81)
[16:29] / gmake[1]: *** [/usr/local/bin/ct-ng:261: build] Error 1
gmake: *** [/usr/local/bin/ct-ng:265: build.4] Error 2

Any suggestion? Thanks.

**Comment by bhundven** [comment]
Please attach your `build.log` and `.config`.

**Comment by Allen4096** [comment]
.build/arm-CSC-linux-gnueabihf/build/build-libc/multilib/config.log says
------------------------------------------------------------------------------
configure:2606: $? = 0
     104 configure:2595: arm-CSC-linux-gnueabihf-gcc  -g -O2 -U_FORTIFY_SOURCE     -mcpu=cortex-a55  -mfpu=neon -mhard-float    -V >&5
     105 arm-CSC-linux-gnueabihf-gcc: error: unrecognized command line option '-V'
     106 arm-CSC-linux-gnueabihf-gcc: fatal error: no input files
     107 compilation terminated.
     108 configure:2606: $? = 1
     109 configure:2595: arm-CSC-linux-gnueabihf-gcc  -g -O2 -U_FORTIFY_SOURCE     -mcpu=cortex-a55  -mfpu=neon -mhard-float    -qversion >&5
     110 arm-CSC-linux-gnueabihf-gcc: error: unrecognized command line option '-qversion'; did you mean '--version'?
     111 arm-CSC-linux-gnueabihf-gcc: fatal error: no input files
     112 compilation terminated.
     113 configure:2606: $? = 1
     114 configure:2611: checking for suffix of object files
     115 configure:2633: arm-CSC-linux-gnueabihf-gcc  -g -O2 -U_FORTIFY_SOURCE     -mcpu=cortex-a55  -mfpu=neon -mhard-float    -c   conftest.c >&5
     116 cc1: warning: switch '-mcpu=cortex-a55' conflicts with '-march=armv8.2-a' switch
     
     configure:3915: arm-CSC-linux-gnueabihf-gcc  -g -O2 -U_FORTIFY_SOURCE     -mcpu=cortex-a55  -mfpu=neon -mhard-float     -fno-unwind-tables  -Werror -fstack-protector -xc /dev/              null -S -o /dev/null
     307 cc1: error: switch '-mcpu=cortex-a55' conflicts with '-march=armv8.2-a' switch [-Werror]
     308 cc1: all warnings being treated as errors

**Comment by Allen4096** [comment]
I also noticed the following warning.
[CFG  ]      checking for sysdeps preconfigure fragments... aarch64 alpha arc arm cc1: warning: switch '-mcpu=cortex-a55' conflicts with '-march=armv8.2-a' switch
[CFG  ]      configure: WARNING: arm/preconfigure: Did not find ARM architecture type; using default

**Comment by cpackham** [comment]
I can reproduce this on latest master. It does seem a bit odd that it's complaining about `march=armv8.2-a`. Maybe instead of setting `ARCH_CPU` try setting `ARCH_TUNE`

**Comment by Allen4096** [comment]
Thanks @cpackham @bhundven 

Usually, in crosstool ng menuconfig, we configure the CPU information, and then the gcc code parses out the correct tune and arch.
I also tried specifying the CPU as cortex-a75 and saw the same error. It seems that on armv8.2-a series cpu, it doesn't work.
[https://en.wikipedia.org/wiki/ARM_Cortex-A55#:~:text=The%20Cortex%2DA55%20serves%20as,improved%20relative%20to%20the%20A53.](url)
PS:
1) GCC11.3+ Cortex-a55, there is no conflict.
2) But GCC 8.x/9.x/10.x + Cortex-a55,  I see the same problem.

In .build/src/gcc-9.3.0/gcc/config/arm/arm-cpus.in
--------------------------------------------------------
      548 begin arch armv8.2-a
      549  tune for cortex-a53
      550  tune flags CO_PROC
      551  base 8A
      552  profile A
      553  isa ARMv8_2a
      554  option simd add FP_ARMv8 NEON
      555  option fp16 add fp16 FP_ARMv8 NEON
      556  option fp16fml add fp16fml fp16 FP_ARMv8 NEON
      557  option crypto add FP_ARMv8 CRYPTO
      558  option nocrypto remove ALL_CRYPTO
      559  option nofp remove ALL_FP
      560  option dotprod add FP_ARMv8 DOTPROD
      561  option sb add sb
      562  option predres add predres
      563 end arch armv8.2-a
--------------------------------------------------------
Since cortex-a55 is a member of armv8.2-a, finally I took the following workaround.
#CT_ARCH_CPU="cortex-a55"
CT_ARCH_ARCH="armv8.2-a"
