### ISSUE TITLE
Build failed at stage : " Installing ncurses for host "

### ISSUE THREAD

**Issue by Maxime-Vulliens** [crosstool-ng/crosstool-ng#1926]
Hello,
I 'm trying to build a riscv64 toolchain on a linux (Ubuntu) virtual machine for a Windows target.
I'am having this issue while compiling ncurses for host and I'm stuck with it. 

Here is the error : 
[INFO ]  Installing ncurses for host
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[ERROR]    _690671.c:964:15: error: expected ')' before 'int'
[ERROR]    make[3]: *** [Makefile:1005: ../objects/lib_gen.o] Error 1
[ERROR]    make[2]: *** [Makefile:119: all] Error 2
[ERROR]   | 
[ERROR]  >> 
[ERROR]  >>  Build failed in step 'Installing ncurses for host'
[ERROR]  >>        called in step '(top-level)'

ct-ng version : 1.25.0.149_1b0c227
Ubuntu version :  Ubuntu 22.04.2 LTS
Virtual box version : 7.06 r155176 (Qt5.15.2)
Host : Windows 10 Pro

config and log file attached. (.config rename in config.txt)

Thank you in advance for helping.

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/10999067/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/10999073/config.txt)

**Comment by cpackham** [comment]
I just tried this in a debian linux container and was able to complete the build. ` _690671.c` is a bit of a weird filename that's not something that is present when I build.

FYI people have reported success using WSL instead of needing to fire up a full VM which might save you a bit of hassle with builds.

**Comment by Maxime-Vulliens** [comment]
Thank you for the answer and good to know we can use WSL, a lot more convenient to use.

Which version of debian are you using ? 
And how do you manage to install ncurses when configuring crosstool-ng, are you using libncurses5-dev ?

**Comment by cpackham** [comment]
Happens to be bookworm-slim. libncurses*-dev shouldn't matter as crosstool-ng is building ncurses itself. There is something odd in your setup as `_690671.c` is just not a filename that is part of the ncurses source.

**Comment by Maxime-Vulliens** [comment]
I may have miss something, or doing something wrong. This is the list of command used that result in this error :
    1  sudo apt-get update
    2  sudo apt-get upgrade
    3  sudo apt-get install build-essential libtool libtool-bin 
    4  sudo apt-get install -y gcc g++ gperf bison flex texinfo help2man make libncurses5-dev  python3-dev autoconf automake libtool libtool-bin gawk wget bzip2 xz-utils unzip patch libstdc++6 rsync git mingw-w64 meson ninja-build
    5  cd Documents/
    6  git clone https://github.com/crosstool-ng/crosstool-ng
    7  cd crosstool-ng/
   17  ./bootstrap 
   18  ./configure --prefix=/opt/ct-ng
   19  make
   20  sudo make install
   21  export PATH=/opt/ct-ng/bin:$PATH
   24  mkdir x86
   25  cd x86/
   36  ct-ng x86_64-w64-mingw32
   37  ct-ng build
   38  cd ..
   40  mkdir rv64
   43  cd /opt/ct-ng/share/crosstool-ng/samples/
   46  sudo cp riscv64-unknown-elf x86_64-w64-mingw32,riscv64-unknown-elf -r
   47  cd x86_64-w64-mingw32,riscv64-unknown-elf/
   49  sudo gedit crosstool.config  & => (Add CT_CANADIAN=y and CT_HOST="x86_64-w64-mingw32")
   51  cd /home/max/Documents/rv64/
   52  ct-ng x86_64-w64-mingw32,riscv64-unknown-elf
   53  ct-ng build
  
for the line 4, the list of packet install come from crosstool-ng documentation, on page "Setting up host OS" it refers some docker file with a list of packet needed to build/install crosstool-ng. I use the one for Ubuntu 22.04. Here is the link : 
https://github.com/crosstool-ng/crosstool-ng/blob/master/testing/docker/ubuntu22.04/Dockerfile  .

What am I doing wrong ?
