### ISSUE TITLE
Build fails if rsync is not installed

### ISSUE THREAD

**Issue by bbonev** [crosstool-ng/crosstool-ng#1940]
The build fails on "Installing kernel headers" if rsync is not installed.
The configure script reports "checking for rsync... no"

configure should fail in this condition.

I am not sure if this should be considered a bug, if not please close it.

- Report crosstool-NG version: 1.25.0
- Report host OS and its version: Devuan daedalus ppc64el (not relevant)
- Attach `.config` (the issue is not related to any configuration)
- Attach `build.log` (not relevant)

**Comment by cpackham** [comment]
f441a6bf0d attempts to deal with this. rsync was added as a dependency for Linux 5.3 so that is the condition that is enforced. You haven't attached a build.log or .config so I can't tell what you were trying to do or if the code that is supposed to handle this did so correctly.

**Comment by bbonev** [comment]
Ah, OK. I am using much newer kernel than 5.3, but instead of manually configuring I copy the configuration file from another machine. Looks like in this way the check is skipped and in case for some reason the new machine is not consistent with the old one, it goes undetected. It is not possible to fix configure because it does not have the config yet, and there are valid configurations that will not require rsync. Is it a good idea to run this and the other similar checks just at the start of the build step?

**Comment by cpackham** [comment]
Yeah the configure time check is less than ideal. It doesn't deal with
rsync being added after ctng is built or the case that you've identified.
It's the best I've been able to come up with.

Ideally the kernel headers build would have its own check for the tools it
needs and bail early if they're not present rather than failing towards the
end with an obscure message.
