### ISSUE TITLE
Narowing Conversion Error Building binutils

### ISSUE THREAD

**Issue by joejjs** [crosstool-ng/crosstool-ng#1942]
Build of crosstools-ng 1.25.0 failing on Bullseye 6.1.21-v8+ 64 bit on a rapsberry pi 4 - 
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/11343875/config.txt)
building binutils (seems to be during the 32 bit build).  narrowing Conversion error unsigned int to int regarding references to GNU_PROPERTY_X86_ISA_1_USED,GNU_PROPERTY_X86_ISA_1_NEEDED,GNU_PROPERTY_X86_FEATURE_1_AND. Seems to be defined in elfcpp.

config attached.

build.log:

[ALL  ]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/symtab.h: In constructor 'gold::Symbol::Symbol()':
[
[ALL  ]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc: In instantiation of 'void {anonymous}::Target_x86_64<size>::record_gnu_property(int, int, size_t, const unsigned char*, const gold::Object*) [with int size = 64; size_t = long unsigned int]':
[ALL  ]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1310:3:   required from here
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1590:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_LOPROC' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1590 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1591:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1591 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1592:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1592 |     case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1611:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_LOPROC' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1611 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1614:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1614 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1617:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1617 |     case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
[ALL  ]          |     ^~~~
[ALL  ]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc: In instantiation of 'void {anonymous}::Target_x86_64<size>::record_gnu_property(int, int, size_t, const unsigned char*, const gold::Object*) [with int size = 32; size_t = long unsigned int]':
[ALL  ]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1310:3:   required from here
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1590:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_LOPROC' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1590 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1591:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1591 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1592:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1592 |     case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1611:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_LOPROC' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1611 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_USED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1614:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1614 |     case elfcpp::GNU_PROPERTY_X86_ISA_1_NEEDED:
[ALL  ]          |     ^~~~
[ERROR]    /home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/src/binutils/gold/x86_64.cc:1617:5: error: narrowing conversion of 'elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND' from 'unsigned int' to 'int' [-Wnarrowing]
[ALL  ]     1617 |     case elfcpp::GNU_PROPERTY_X86_FEATURE_1_AND:
[ALL  ]          |     ^~~~
[ERROR]    make[5]: *** [Makefile:1123: x86_64.o] Error 1
[ERROR]    make[5]: *** Waiting for unfinished jobs....
[ALL  ]    mv -f .deps/symtab.Tpo .deps/symtab.Po
[ALL  ]    mv -f .deps/i386.Tpo .deps/i386.Po
[ALL  ]    mv -f .deps/main.Tpo .deps/main.Po
[ALL  ]    mv -f .deps/dwp.Tpo .deps/dwp.Po
[ALL  ]    make[5]: Leaving directory '/home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/build/build-binutils-host-aarch64-build_unknown-linux-gnu/gold'
[ERROR]    make[4]: *** [Makefile:1146: all-recursive] Error 1
[ALL  ]    make[4]: Leaving directory '/home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/build/build-binutils-host-aarch64-build_unknown-linux-gnu/gold'
[ERROR]    make[3]: *** [Makefile:886: all] Error 2
[ALL  ]    make[3]: Leaving directory '/home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/build/build-binutils-host-aarch64-build_unknown-linux-gnu/gold'
[ERROR]    make[2]: *** [Makefile:6045: all-gold] Error 2
[ALL  ]    make[2]: Leaving directory '/home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/build/build-binutils-host-aarch64-build_unknown-linux-gnu'
[ERROR]    make[1]: *** [Makefile:850: all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/pi/mame_raspberrypi_cross_compile/build/ctng_rpi2_buster_armhf/.build/armv7-rpi2-linux-gnueabihf/build/build-binutils-host-aarch64-build_unknown-linux-gnu'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@212]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@70]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 19:40.70)

### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by joejjs** [comment]
Please close as I did more searching and this is a known issue - not sure if its solved though

**Comment by j-d-salinger** [comment]
You can close it yourself!
