### ISSUE TITLE
Indefinite hang building stdio-common OSX M1 -> armv8-rpi3-linux-gnueabihf with GLIBC 2.31 or older

### ISSUE THREAD

**Issue by cjappl** [crosstool-ng/crosstool-ng#1944]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
```bash
> ct-ng --version
GNU Make 4.4.1
Built for aarch64-apple-darwin21.6.0
Copyright (C) 1988-2023 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```
- Report host OS and its version

```bash
> sw_vers
ProductName:    macOS
ProductVersion: 12.6.4
BuildVersion:   21G526
```

- Attach `.config` (unless the issue is not related to any configuration)
https://drive.google.com/file/d/10k8o2Rp0xsTTrAiF2Ls7RDFZTnwK6jHL/view?usp=share_link

- Attach `build.log` (unless crosstool-NG fails before the build starts)
https://drive.google.com/file/d/1o3HwgedFDstyrqSdv-6-KRASvhM3VqzS/view?usp=share_link

Problem:
I am attempting to generate crosstols on OSX M1 for raspberry pi. Everything seems to be going well, until about 20 minutes in, the step is:

```
> ct-ng build.1
...
[INFO ]  Saving state to restart at step 'libc_main'...
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
```

build.log gets to:
```
[ALL  ]      make[4]: Entering directory '/Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.build/src/glibc-git-c9e58ae2/stdlib'
[ALL  ]      make[4]: Nothing to be done for 'others'.
[ALL  ]      make[4]: Leaving directory '/Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.build/src/glibc-git-c9e58ae2/stdlib'
[ALL  ]      make  subdir=stdio-common -C stdio-common ..=../ others
[ALL  ]      make[4]: Entering directory '/Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.build/src/glibc-git-c9e58ae2/stdio-common'
```

And then it hangs indefinitely (have tried for 12 hours, and no movement).

Open to trying anything to unblock

I have tried
- Different glibc versions, and download steps
- Different threads/concurrent jobs

**Comment by cpackham** [comment]
According to [this rather helpful comment](https://github.com/crosstool-ng/crosstool-ng/issues/1932#issuecomment-1528139734) it's an incompatibility between older glibc versions and newer GNU make versions.

Two workarounds I can suggest (without having tried either). 
- Ask ct-ng to build GNU make for you and select GNU Make 4.3
- Try using `ct-ng build.1` to disable parallel building

**Comment by 2electron-mc** [comment]
HI all,
I got the same issues, but in a different configuration.
I tried to build toolchain x86_64-pc-linux -> armv7-rpi2-linux-gnueabihf with GLIBC 2.31 and the process was running for several hours without any updates.

` ./ct-ng --version`

` GNU Make 4.3
Built for x86_64-pc-linux-gnu
Copyright (C) 1988-2020 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
`

These are last lines written inside my Build.log file

> [ALL  ]      make[3]: Leaving directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/math'
[ALL  ]      make  subdir=setjmp -C setjmp ..=../ others
[ALL  ]      make[3]: Entering directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/setjmp'
[ALL  ]      make[3]: Nothing to be done for 'others'.
[ALL  ]      make[3]: Leaving directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/setjmp'
[ALL  ]      make  subdir=signal -C signal ..=../ others
[ALL  ]      make[3]: Entering directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/signal'
[ALL  ]      make[3]: Nothing to be done for 'others'.
[ALL  ]      make[3]: Leaving directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/signal'
[ALL  ]      make  subdir=stdlib -C stdlib ..=../ others
[ALL  ]      make[3]: Entering directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/stdlib'
[ALL  ]      make[3]: Nothing to be done for 'others'.
[ALL  ]      make[3]: Leaving directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/stdlib'
[ALL  ]      make  subdir=stdio-common -C stdio-common ..=../ others
[ALL  ]      make[3]: Entering directory '/home/debian_mc/Projects/crosstool-ng/.build/src/glibc-2.31/stdio-common'


[Current configuration](https://gist.github.com/2electron-mc/1bd5305b71564cc6c3d9e20a314dd067)

**Comment by cjappl** [comment]
@2electron-mc can you confirm the problem goes away if you change the `glibc` version?

@cpackham thanks for that, trying that out now. That does sound super similar to my problem! Going to try your suggestions and will report back

**Comment by cjappl** [comment]
OK, great news in that I can confirm that 

> Ask ct-ng to build GNU make for you and select GNU Make 4.3

Does fix the indefinite hang problem!

I am running into another problem now, which is:

```
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      rpc_main.c:329:17: error: variable has incomplete type 'struct stat64'
[ERROR]      rpc_main.c:331:7: error: implicit declaration of function 'stat64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
[ERROR]      rpc_main.c:1117:17: error: variable has incomplete type 'struct stat64'
[ERROR]      rpc_main.c:1120:9: error: implicit declaration of function 'stat64' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
[ERROR]      make[4]: *** [Makefile:174: /Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.build/armv8-rpi3-linux-gnueabihf/build/build-lib
c/multilib/sunrpc/cross-rpc_main.o] Error 1
[ERROR]      make[3]: *** [Makefile:470: sunrpc/others] Error 2
[ERROR]      make[2]: *** [Makefile:9: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: glibc_backend_once[scripts/build/libc/glibc.sh@274]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1608]
[ERROR]  >>        called from: glibc_main[scripts/build/libc/glibc.sh@40]
[ERROR]  >>        called from: do_libc_main[scripts/build/libc.sh@33]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@697]


Current command:
   'make' '-j1' '-l' 'CXX=' 'default_cflags=' 'BUILD_CFLAGS=-O2 -g -I/Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.build/armv8-rpi3-lin
ux-gnueabihf/buildtools/include   -Qunused-arguments -fno-common' 'BUILD_CPPFLAGS= -I/Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.buil
d/armv8-rpi3-linux-gnueabihf/buildtools/include/' 'BUILD_LDFLAGS=-L/Volumes/xtool-build-env/crosstools_workspace/x-tools/armv8-rpi3-linux-gnueabihf/.build/armv8-rpi3-linux
-gnueabihf/buildtools/lib   -framework CoreFoundation -lintl -liconv' 'all'
exited with error code: 2
Please fix it up and finish by exiting the shell with one of these values:
    1  fixed, continue with next build command
    2  repeat this build command
    3  abort build
```

I am going to try to troubleshoot for a bit, but this has fixed the hang, at least! I will close this ticket shortly, hopefully with a full resolution to the build for any future people

**Comment by 2electron-mc** [comment]
@cjappl  yes, i can confirm, i tried to change GLIBC version (i used 2.32) and this issue doesn't happen.

**Comment by cjappl** [comment]
Eureka!!

The solution described above, plus the solution for #1789 I am able to build an older version than 2.32!!



In summary, the essential steps:
- Ask ct-ng to build GNU make for you and select GNU Make 4.3
    - Fixes the hang
- Disabling `CT_GLIBC_ENABLE_OBSOLETE_RPC` (#1789 ) fixed the later issue.

I can then build.

That recipe is found here, for any future people:
https://gist.github.com/cjappl/1d3ff98711dbd5d626afdd59ae809e46


Closing this as complete. Thanks for the help @cpackham - very much appreciated

**Comment by 2electron-mc** [comment]
@cpackham in my situation, i just used GNU make 4.3 when i encountered the issue.
 In my case, i built toolchain from Ubuntu 22.04, not in OSX, but the problem was the same as @cjappl .
 Should i try to use an older GNU make version (e.g 4.2) ?
