### ISSUE TITLE
pgp.surfnet.nl appears to be having issues

### ISSUE THREAD

**Issue by bweir** [crosstool-ng/crosstool-ng#1945]
Hi there, FYI, pgp.surfnet.nl seems to be having issues. Attempting to retrieve the key yields the following:

```console
$ gpg --keyserver pgp.surfnet.nl --recv-keys 35B871D1 11D618A4
gpg: keyserver receive failed: No data
```

If you [visit the site directly](https://pgp.surfnet.nl/), attempting to retrieve the key yields `Internal Server Error`.

My [crosstool-ng container](https://gitlab.com/brettops/containers/crosstool-ng) builds have been broken all day as a result. =)

Not sure if there is an alternative key server. I'll just modify the build to check the sha256sum for now, but I thought you'd want to know.

**Comment by cpackham** [comment]
Seems to be back now.

**Comment by bweir** [comment]
Oh, thanks for the heads up. I added it back in, looks good!
