### ISSUE TITLE
Deal with old glibc + new GNU make incompatiblities

### ISSUE THREAD

**Issue by cpackham** [crosstool-ng/crosstool-ng#1946]
Users have been reporting the build hanging. Finally between #1944 and #1932 it's been identified that older glibc (<=2.31) has a problem with newer GNU Make (>=4.4). The workaround of having ct-ng build and use GNU Make 4.3 in the case seems to work. 

I expect that the problem will become more frequent as GNU Make 4.4 is rolled out in more distros and users update their systems. It would be good to codify the workaround such that if GNU Make 4.4 or newer is detected at configure time ct-ng automagically selects COMP_TOOLS_MAKE and GNU Make 4.3 when attempting to build one of these older glibcs.

**Comment by rumas84** [comment]
Hello,
i observed something with new make-**4.4.x**
Ubuntu-22.04.2, gcc-12.1.0
##
1) i install make-4.4.x on Ubuntu and **build** CT-NG from the master repo
then build a toolchain, we will get all problems stated before.

2) i re-install make-4.3 and build CT-NG from the master repo and before build
a new toolchain i update to make-4.4.x then build a toolchain with success.

For me the old glibc is not the problem 
but something is missing(headers, flags, ...etc..) when we build CT-NG from the master repo 
And make-4.4.x installed on the distro
...???
