### ISSUE TITLE
Question: Applying a patch automatically to gcc

### ISSUE THREAD

**Issue by cjappl** [crosstool-ng/crosstool-ng#1947]
Hi,

Question I couldn't find the answer to in the documentation.

As outlined in [ this comment ](https://github.com/crosstool-ng/crosstool-ng/issues/1783#issuecomment-1536839362), there is a patch that I want applied to gcc. 

The way I did it was:
1. Halt in the debugger after failure
2. track down the file, apply the patch
3. re-run the failed `make` command
4. `exit 1` to continue

Is there a way to apply a patch automatically during the `gcc` portion of the process?

Thanks for the help.

**Comment by cpackham** [comment]
Basically you want to select `CT_PATCH_BUNDLED_LOCAL` ("Paths and misc options" -> "Patches origin") and set `CT_LOCAL_PATCH_DIR` ("Local patch directory") to where you have your patches (e.g. `${HOME}/src/patches`). In that directory you need to create a hierarchy of packages and versions that you want to patch (e.g. ` ${HOME}/src/patches/gcc/12.2.0/0010-my-patch-for-gcc.patch`)

**Comment by cjappl** [comment]
Fantastic, thanks.

I will close this now and comment with any findings for future readers. Appreciate the help.
