### ISSUE TITLE
"ct-ng build" fails due to "missing separator"

### ISSUE THREAD

**Issue by bbbH8TR** [crosstool-ng/crosstool-ng#1955]
Hello Crosstool-NG Team,

The problem faced is that "ct-ng build" fails at 'multilib' stage due to "make [...] *** missing separator.  Stop."

As I do not know which Makefile is referenced for the multilib stage, I do not know where to look for problematic whitespace separator; ie, TABS versus SPACES.

Error line in build.log:
[ALL  ]      /home/beagledev/DEV/crosstool-ng/.build/arm-cortex_a8-linux-gnueabihf/build/build-libc/multilib/configparms:1: *** missing separator.  Stop.

Development system:
1) crosstool-NG version 1.25.0.168_2282a97
2) Linux debian 5.10.0-22-amd64 (Debian 5.10.178-3)

**crosstool-ng$ ct-ng --jobs=8 build**

3) config       (Attached; renamed config.txt for uploading purposes)
4) build.log   (Attached; compressed and renamed build_log.zip for uploading purposes)

**crosstool-ng$ ct-ng build.1**

5) build.log.1   (Attached; compressed and renamed build_log_1.zip for uploading purposes)

Are there any Makefile suggestions that you could recommend?

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/11468348/config.txt)
[build_log.zip](https://github.com/crosstool-ng/crosstool-ng/files/11468351/build_log.zip)
[build_log_1.zip](https://github.com/crosstool-ng/crosstool-ng/files/11468353/build_log_1.zip)

**Comment by cpackham** [comment]
The problem appears to be `CT_GLIBC_CONFIGPARMS="--enable-obsolete-rpc"` in your config the rpc code was dropped from glibc some time ago. Whatever vestiges of this remain seem to upset the build.

**Comment by bbbH8TR** [comment]
Hurray !!!  

The --enable-obsolete-rpc was deleted from 'extra config"  inside menuconfig. 
(Page 22 of "Mastering Embedded Linux Programming" by Chris Simmonds)

And, after that, issuing the "./ct-ng --jobs=8 build" finished successfully without errors. 

Thank you cpackham :-)
