### ISSUE TITLE
`configure` doesn't check if `yacc` is missing

### ISSUE THREAD

**Issue by illwieckz** [crosstool-ng/crosstool-ng#1961]
- crosstool-NG version: `1.25.0` from tarball
- host OS and its version: Debian Linux 10 Buster

`./configure` doesn't check if `yacc` is missing and succeeds while it's missing, but then `make` will fail.

It's better if `configure` can tell `yacc` is missing before discovering it with a build failure. The `configure` script already does it does for `gawk`, `makeinfo` and others.

```
crosstool-ng-1.25.0 $ ./configure
[no error]

crosstool-ng-1.25.0 $ make -j32
/usr/bin/make  all-recursive
make[1]: Entering directory 'crosstool-ng-1.25.0'
Making all in kconfig
make[2]: Entering directory 'crosstool-ng-1.25.0/kconfig'
  LEX      lexer.lex.c
  YACC     parser.tab.c
/bin/bash: yacc: command not found
make[2]: *** [Makefile:1040: parser.tab.c] Error 127
make[2]: *** Waiting for unfinished jobs....
make[2]: Leaving directory 'crosstool-ng-1.25.0/kconfig'
make[1]: *** [Makefile:2485: all-recursive] Error 1
make[1]: Leaving directory 'crosstool-ng-1.25.0'
make: *** [Makefile:2232: all] Error 2
```

**Comment by cpackham** [comment]
I think a3e3d734a7d1 should have fixed this and 52e28795840 may have improved things further. Could you try building from the tip of master?

**Comment by illwieckz** [comment]
Right, `master` properly reports the missing! Thanks. I had not noticed that latest release is already 1 year old!

Is there a new release planned soon? I also seen that libjpeg-turbo only enables NEON on arm64 starting with GCC12 and current ct-ng release doesn't allow to build something more recent than GCC 11! So a new release would be greatly appreciated!

**Comment by cpackham** [comment]
I kind of intended to have ct-ng releases trailing GCC releases. Given that GCC13 was just released then I think a ct-ng release soon-ish is appropriate. The blockers that I'm aware of are failure to build uclibc with GCC13 as well as some failures reported for the arm-none-eabi sample.
