### ISSUE TITLE
The download folder says latest release is `1.23.0` but it is `1.25.0`

### ISSUE THREAD

**Issue by illwieckz** [crosstool-ng/crosstool-ng#1963]
Not a bug in the repository itself, but in this download folder:

- http://crosstool-ng.org/download/crosstool-ng/

This download folder has a file named `00-LATEST-is-1.23.0`, while the latest release is `1.25.0`.

Also the file has a 10 years old date, which looks weird.

I guess doing something like that would avoid any misleading:

```sh
rm 00-LATEST-is-1.23.0
touch -r crosstool-ng-1.25.0.tar.xz 00-LATEST-is-1.25.0
```

**Comment by cpackham** [comment]
Should be sorted now
