### ISSUE TITLE
What is the correct tuple for arm64/Jetson?

### ISSUE THREAD

**Issue by w3sip** [crosstool-ng/crosstool-ng#1967]
A toolchain that was generated previously, and is currently in use and works, was generated with ct-ng 1.23.0, and used the tuple `aarch64-unknown-linux-gnueabi`. 
I'm trying to generate a toolchain with ct-ng 1.25.0, and the tuple above causes it to immediately fail. Using `aarch64-unknown-linux-gnu` seems to work in a sense that toolchain creation proceeds -- but will it generate a compatible toolchain for Jetson?

**Comment by bhundven** [comment]
I would suggest trying the latest crosstool-ng master git branch for your issue with 1.25.0, and report back.
I would also suggest looking at the bootlin toolchain source (found here: https://developer.nvidia.com/embedded/jetson-linux) to see how it is configured. If you are able to build a toolchain for jetson, and have working bootloader, kernel, and system binaries... post your .config! I'd love to add it to our samples!

**Comment by cpackham** [comment]
`aarch64-unknown-linux-gnu should` be correct the eabi suffix only ever applied to the 32 bit toolchains. This was cleaned up in 1029dcf91ae
