### ISSUE TITLE
zstd won't install

### ISSUE THREAD

**Issue by 7dog123** [crosstool-ng/crosstool-ng#1974]
host OS: ``` CYGWIN_NT-6.1-7601 ```
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/11628297/build.log)

**Comment by cpackham** [comment]
Relevant snippet is
```
[DEBUG]    ==> Executing:  'make' '-C' '/home/Administrator/arm/crosstool-ng/.build/arm-none-eabi/src/zstd/lib' 'install-static' 'install-includes' 'BUILD_DIR=/home/Administrator/arm/crosstool-ng/.build/arm-none-eabi/build/build-zstd-host-x86_64-build_pc-cygwin' 'PREFIX=/home/Administrator/arm/crosstool-ng/.build/arm-none-eabi/buildtools'
[ALL  ]    make[1]: Entering directory '/home/Administrator/arm/crosstool-ng/.build/src/zstd-1.5.5/lib'
[ERROR]    make[1]: *** No rule to make target 'install-static'.  Stop.
[ALL  ]    make[1]: Leaving directory '/home/Administrator/arm/crosstool-ng/.build/src/zstd-1.5.5/lib'
[ERROR]  
```

Looking at the zstd source there is an `install-static` target in lib/Makefile so I'm not sure why it's not finding it

**Comment by 7dog123** [comment]
It only happened on Cygwin as far as I'm aware of with every arch of compiler that requires zstd.

**Comment by cpackham** [comment]
Maybe it's a problem with the version of make shipped in cygwin. Try
enabling Comp Tools Make

**Comment by 7dog123** [comment]
just tried it and it came up with the same thing ```*** No rule to make target 'install-static'.  Stop.```

**Comment by ip-arch** [comment]
This may be happened with interpretation of .PHONY
I move it in the Makefile and the zstd compile proceed.

[zstd.patch](https://github.com/crosstool-ng/crosstool-ng/files/11646065/zstd.patch)

**Comment by 7dog123** [comment]
@ip-arch I did a test on the patch it didn't show the error but it didn't install the static library nor the includes.

the test I did was.

Downloaded the tarball, extracted the tarball, build it with ```make  libzstd.a BUILD_DIR="${PWD}" CFLAGS="-O2 -g -I~/arm/crosstool-ng/.build/arm-none-eabi/uildtools/include" LDFLAGS="-L~/arm/crosstool-ng/.build/arm-none-eabi/uildtools/lib"``` then tried to install it with ```make install-static install-includes BUILD_DIR="${PWD}" PREFIX="~/arm/zstd"``` it didn't show the error but it didn't install it into the directory.

but I used [zstd-1.5.5-cygwin-build.patch](https://cygwin.com/cgit/cygwin-packages/zstd/tree/zstd-1.5.5-cygwin-build.patch) specifically lines 19 and 20 the cygwin patch and it installed without errors.

**Comment by cpackham** [comment]
So it looks like this is an upstream bug in zstd (or a deliberate decision to support only some specific unixes). I'm happy for ct-ng to carry extra patches that are backports of upstream fixes but I don't want ct-ng to be carrying changes that aren't upstream.

As a first step could you report the issue to https://github.com/facebook/zstd you could even propose cygwins patch as a solution but the zstd folks may have a better one.

We could alternatively have ct-ng disable zstd on cygwin but that seems a little drastic.

**Comment by QBos07** [comment]
Opened upstream issue: https://github.com/facebook/zstd/issues/3691

**Comment by QBos07** [comment]
Opened upstream pr facebook/zstd#3720

**Comment by CuttySark1869** [comment]
This issue is marked resolved but I still met the same error. Am I configuring anything wrong? I seleted zstd 1.5.5 and use tarball as the source.

**Comment by QBos07** [comment]
https://GitHub.com/facebook/zstd/4076
