### ISSUE TITLE
strace 6.3, wrong patch.

### ISSUE THREAD

**Issue by goodmenzy** [crosstool-ng/crosstool-ng#1978]
in commit d659700d688968fdc2c45a51cffcdd5ea00bbb0e, the patch is introduced. 
but it is wrong! 
packages/strace/6.3/0000-configure-do-not-take-the-SUBLEVEL-part-of-the-kerne.patch 
give fixup of the configure.ac, but also fix the autoconf generated configure!

the configure check whether to use the bundled kernel headers. Your patch break the C-langure syntax, so the testing always gives the "yes" answer.

you should change the configure.ac, and run autoreconf to re-create the configure script, and then create the patch.

Yes, I'm sure!

**Comment by cpackham** [comment]
Yes I see the problem. I did a poor job of hand editing the patch.

**Comment by goodmenzy** [comment]
linux_version_code  macro will be expanded as a number 394240
it is just a result of the following: sed '/^#define LINUX_VERSION_CODE /!d;s///;q' bundled/linux/include/uapi/linux/version.h

change configure by hand is OK:
line 6305:   #define USE_OS_HEADERS ((LINUX_VERSION_CODE >> 8) > (394240 >> 8) ? 1 : -1)
