### ISSUE TITLE
tircore support

### ISSUE THREAD

**Issue by allen-c** [crosstool-ng/crosstool-ng#1984]
Is there a plan to support infineon tricore target?

**Comment by cpackham** [comment]
No plans to add this target. From the quick search I did looks like it depends on some vendor patches for an ancient GCC version.

I don't really want crosstool-ng to be carrying a bunch of non-upstream patches (backports are fine however) so the first step would be to get those patches updated against a newer GCC and accepted upstream.

**Comment by cpackham** [comment]
Closing this issue for now.
