### ISSUE TITLE
Ncurses 6.2 failure to build Canadian cross Linux->Windows->m68k

### ISSUE THREAD

**Issue by c-grant** [crosstool-ng/crosstool-ng#1999]
Attempting to build m68k-unknown-elf which I stated with from the samples.
I added GDB support which pulls in ncurses. 6.2 (and 6.1) seem to have the same issue.
Sample builds fine without gdb.

crosstool-NG version: 1.25.0
OS & version: Ubuntu 22.04.1 LTS

Files:
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12209943/build.log)
[m68k.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/12209945/m68k.config.txt)

Compilers

[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-w64-mingw32
[EXTRA]      target = m68k-unknown-elf

error message is

[ALL  ]    In file included from /home/vboxuser/CT-NG_1.25.0/m68k/.build/HOST-x86_64-w64-mingw32/m68k-unknown-elf/src/ncurses/ncurses/curses.priv.h:338,
[ALL  ]                     from ../ncurses/lib_gen.c:20:
[ERROR]    _326634.c:964:15: error: expected ')' before 'int'
[ALL  ]    ../include/curses.h:1719:56: note: in definition of macro 'mouse_trafo'
[ALL  ]     1719 | #define mouse_trafo(y,x,to_screen) wmouse_trafo(stdscr,y,x,to_screen)
[ALL  ]          |                                                        ^
[ERROR]    make[2]: *** [Makefile:1005: ../objects/lib_gen.o] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ALL  ]    make[2]: Leaving directory '/home/vboxuser/CT-NG_1.25.0/m68k/.build/HOST-x86_64-w64-mingw32/m68k-unknown-elf/build/build-ncurses-host-x86_64-host_w64-mingw32/ncurses'
[ERROR]    make[1]: *** [Makefile:119: all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/vboxuser/CT-NG_1.25.0/m68k/.build/HOST-x86_64-w64-mingw32/m68k-unknown-elf/build/build-ncurses-host-x86_64-host_w64-mingw32'

**Comment by KirillSmirnov** [comment]
Should be fixed in PR #2000

**Comment by c-grant** [comment]
I pulled the 6.2 patch ad added it to my 1.25 packages folder. I can confirm it made it past this stage

**Comment by cpackham** [comment]
Appears to be resolved thanks @KirillSmirnov, @c-grant. Closing.
