### ISSUE TITLE
configure: error: no usable python found at... Using Python 3.6.13

### ISSUE THREAD

**Issue by ajklg** [crosstool-ng/crosstool-ng#2009]
I am trying to to build the [hero project](https://github.com/pulp-platform/hero) from the pulp-platform, which utilizes crosstool-ng to create its toolchains. When I get to the step where I run "make tc-hrv-olinux" to build the RISC-V linux toolchain, I eventually receive these error messages when building the cross gdb

[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross gdb
[EXTRA]    Building cross gdb
[ERROR]    configure: error: no usable python found at /home/miniconda3/envs/herovenv/bin/python3.6
[ERROR]    make[3]: *** [Makefile:9097: configure-gdb] Error 1
[ERROR]    make[2]: *** [Makefile:850: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@376]
[ERROR]  >>        called from: do_gdb_backend[scripts/build/debug/300-gdb.sh@281]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@59]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@693]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 17:58.06)
[17:59] / gmake[1]: *** [/home/hero/install/bin/ct-ng:261: build] Error 2
gmake[1]: Leaving directory '/home/hero/output/tc-hrv-olinux'
make: *** [Makefile:84: tc-hrv-olinux] Error 2

According to a previous issue ([872](https://github.com/crosstool-ng/crosstool-ng/issues/872)), this could be remedied by installing the python-dev package to get the python header files. However, I am using a conda virtual environment, which is supposed to have the equivalent of the dev package preinstalled, and seems to already include the header file for the environment at /home/miniconda3/envs/herovenv/include/python3.6m/Python.h. Would installing the dev package still fix this issue? I would have to figure out a workaround for installing it since I do not have root access due to me running this on a virtual machine where I do not have any admin privileges.

**Comment by cpackham** [comment]
It'll be the way gdb is detecting python. If you were building gdb manually you'd say `--with-python=/home/miniconda3/envs/herovenv`.

The simplest workaround be to change the toolchain config to disable gdb by unsetting `CT_GDB_CROSS` (you can always build it manually later). You might get some mileage out of changing `CT_GDB_CROSS_PYTHON` , `CT_GDB_CROSS_PYTHON_BINARY` or `CT_GDB_CROSS_EXTRA_CONFIG_ARRAY`

**Comment by ajklg** [comment]
Thanks for the reply. This is my first experience crosstool-ng, and because it was included in the hero project's files, I'm not sure where everything is regarding it. What's the name of the config file where I can unset `CT_GDB_CROSS`?

**Comment by cpackham** [comment]
That's a question for the hero project. From what I can see it's probably `hero/toolchain/hrv-olinux.config` but if you're able to invoke `ct-ng menuconfig` you can search for those options.

**Comment by ajklg** [comment]
Yep that seemed to do it. I disabled `CT_DEBUG_GDB` in `hero/toolchain/hrv-olinux.config` and the toolchains built successfully. Thanks!
