### ISSUE TITLE
Libsanitizer fails on gcc 13.2 with aarch64-unknown-linux-gnu

### ISSUE THREAD

**Issue by fduxvtech** [crosstool-ng/crosstool-ng#2010]
Setup:
- crosstool-NG version: UNKNOW, currently working on master branch
- Ubuntu 20.04, docker
- config = aarch64-unknown-linux-gnu with libsanitizer enabled

The build fails with the following error:

```bash
[ERROR]    /home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/gcc/libsanitizer/sanitizer_common/sanitizer_platform_limits_posix.cpp:180:10: fatal error: crypt.h: No such file or directory
[ALL  ]      180 | #include <crypt.h>
[ALL  ]          |          ^~~~~~~~~
[ALL  ]    compilation terminated.
```

I did install libcrypt-dev and find `crypt.h` is located in the following:
```bash
$ locate crypt.h | grep /crypt.h
/home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/binutils/zlib/contrib/minizip/crypt.h
/home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/gcc/zlib/contrib/minizip/crypt.h
/home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/gdb/zlib/contrib/minizip/crypt.h
/home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/glibc/crypt/crypt.h
/home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/glibc/include/crypt.h
/home/coder/cross/gcc-13/.build/aarch64-unknown-linux-gnu/src/zlib/contrib/minizip/crypt.h
/usr/include/crypt.h`
```

The build log is too big to be attached, but I can extrapolate something if needed;

**Comment by cpackham** [comment]
Looks like GCC dropped the offending code recently. Unfortunately it's in a rather large sync for libsanitizer so it might be tricky to backport

**Comment by fduxvtech** [comment]
For what it is worth I'm able to compile both cross-native and canadian with [the PR](https://github.com/crosstool-ng/crosstool-ng/pull/2011)

Thanks for the quick fix

**Comment by milkylainen** [comment]
I think a equivalent to RPC, like GLIBC_HAS_OBSOLETE_CRYPT can come in handy.
Some envs are going to be in limbo while replacing crypt with some drop in library.
A suggested option here is libxcrypt, but older build envs bumping toolchain might be caught in this limbo.

So such a knob will visualize the "was always there" breakage and with some instructive help, probably avoid further questions.
