### ISSUE TITLE
Possible to choose glibc<2.26 with binutils>=2.34?

### ISSUE THREAD

**Issue by misterBart** [crosstool-ng/crosstool-ng#2014]
_My goal_: Target as much client systems as possible, i.e. try to build my software with a glibc as old as possible.
_Challenge_: The software to be build requires architectural extensions `-march=armv8.2-a+i8mm` and `-march=armv8.2-a+bf16`. I noticed this is supported in gcc>=9 and in the assembler of binutils>=2.24.
_Problem_: When I select binutils 2.24 in Crosstool, I can only choose glibc>=2.26.
_Question_: Is there a way to overcome my challenge with a lower glibc than 2.26?

Host OS: Ubuntu 23.04. Using master branch of Crosstool. Working with preset `aarch64-unknown-linux-gnu`.

**Comment by cpackham** [comment]
We dropped binutils 2.24 a couple of years ago are you sure you're actually using master?

Currently the oldest binutils you can select is 2.26.1. With this I'm able to select glibc as old as 2.17 (the oldest we support). No idea if that'll actually produce a working toolchain.

**Comment by misterBart** [comment]
I'm slapping my hand to my forehead. I meant binutils **2.34**.
		
Binutils is set by default to 2.40.
But when I set glibc to 2.19, then binutils is automatically changed to binutils 2.29.1. 
I cannot change binutils to a higher version as long as glibc is set to 2.19 (see attached screenshot).
Only when I set glibc to 2.26 or higher, then I can set binutils to a higher version than 2.29.1.
So my question is: Is it possible to choose glibc<2.26 and binutils>=2.34?
![menuconfig-binutils](https://github.com/crosstool-ng/crosstool-ng/assets/54583863/dec2f466-980b-4011-82af-e24d3e4ffe19)

**Comment by cpackham** [comment]
Ah right. That restriction comes from commit 36bb675a ("More fixes after the upgrades:") based on the commit message it appears that newer binutils are not compatible with older glibc for aarch64. I'm not aware of anymore detail than that.
