### ISSUE TITLE
binutils 2.41 is out

### ISSUE THREAD

**Issue by cpackham** [crosstool-ng/crosstool-ng#2018]
https://sourceware.org/pipermail/binutils/2023-July/128719.html

Although there is a report of a [performance regression](https://sourceware.org/pipermail/binutils/2023-August/128823.html).

**Comment by egtvedt** [comment]
> https://sourceware.org/pipermail/binutils/2023-July/128719.html
> 
> Although there is a report of a [performance regression](https://sourceware.org/pipermail/binutils/2023-August/128823.html).

I noticed the perfomance regression, but though it would be better to have latest available compared to increased linker time.

**Comment by QBos07** [comment]
LD already fixed

**Comment by egtvedt** [comment]
> LD already fixed

Is it a specific commit? A series?

Can you point to it in the 2.41 release branch at https://sourceware.org/git/?p=binutils-gdb.git;a=shortlog;h=refs/heads/binutils-2_41-branch ?

**Comment by QBos07** [comment]
[This Patch](https://sourceware.org/bugzilla/attachment.cgi?id=15046) was in the bugtracker

**Comment by egtvedt** [comment]
The main issue for adding binutils 2.41 is that from build test https://github.com/crosstool-ng/crosstool-ng/pull/2025 the configuration armv6-nommu-linux-uclibcgnueabi failed to build.

But thanks for sharing the patch fixing the cygwin performance, that is one step.

I can't see anything in upstream release branch to address that problem.

**Comment by QBos07** [comment]
Btw that butracker said 2.42 as a milestone, so this may not get fixed in this release ever. But I don't have a problem with porting this patch since it isn't some extra work for us.

**Comment by cpackham** [comment]
Closed via #2025
