### ISSUE TITLE
MPFR build fails on linux host with glibc 2.37

### ISSUE THREAD

**Issue by zagura** [crosstool-ng/crosstool-ng#2029]
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12565732/build.log)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12565734/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/12565735/config.txt)
- Report crosstool-NG version: `crosstool-NG version 1.26.0_rc1.2_cf25b4e` current master as of 1.09.2023: cf25b4edb096c9b815daa202968c15906b8047e5
- Report host OS and its version: Gentoo:
  * Linux kernel 6.5.1-gentoo
  * glibc: ldd (Gentoo 2.37-r3 (patchset 5)) 2.37
  * binutils: GNU ld (Gentoo 2.40 p5) 2.40.0
  * gcc: gcc (Gentoo Hardened 12.3.1_p20230526 p2) 12.3.1 20230526
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

Build fails on test phase when building MPFR for host. Test failed: tsprintf. As per release page for MPFR (https://www.mpfr.org/mpfr-4.2.0/#fixed), I hit their bug on glibc 2.37, it has been fixed with proper patch or 4.2.1 version.

**Comment by cpackham** [comment]
Hmm, I'd been putting off the mpfr update but it sounds like we'll need to
do it

**Comment by cpackham** [comment]
Should be fixed via #2031
