### ISSUE TITLE
mpc digest errors

### ISSUE THREAD

**Issue by neildavis** [crosstool-ng/crosstool-ng#2034]
Not directly `crosstool-ng` related, but I've noticed something odd in my GitHub Actions (GHA) workflows that generate toolchains tonight and wondered if anyone here has any insight or would know what's going on here?

For reference:
GHA Host OS:  Ubuntu 22.04.3 LTS
crsootool-ng version 1.25.0

Everything was working fine until I suddenly started getting sha512 digest errors for `mpc-1.2.1.tar.gz`:
```
Error:     Bad sha512 digest for mpc-1.2.1.tar.gz: 1d49395f678b65ca37230ce7a7b215bcdf607fd3cc21bc9b26949bc79fee0994a0cc77032d6e0e7b7840e4108e81af9d92d878eb1a06fa523bdd426b74f1c44f, expect 3279f813ab37f47fdcc800e4ac5f306417d07f539593ca715876e43e04896e1d5bceccfb288ef2908a3f24b760747d0dbd0392a24b9b341bc3e12082e5c836ee
Error:     Digest verification failed; removing the download
Error:     mpc: download failed
```

After searching I found similar report in #1630 and followed the logic from @cpackham by trying to download on my PC and I get:
```
$ curl http://www.multiprecision.org/downloads/mpc-1.2.1.tar.gz
<html>
<head><title>302 Found</title></head>
<body>
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

Then I checked the `whois` record for the domain and found it's been updated tonight at  2023-09-14 20:00:27 UTC (https://www.whois.com/whois/multiprecision.org) and now the homepage is for a French cloud/vps hosting company (OVHcloud) and has no HTTPS support, and all links to pages on the domain from search engines fail.

Did the domain lapse?

**Comment by cpackham** [comment]
Looks like the site is down at the moment.

**Comment by neildavis** [comment]
Thanks @cpackham 
Do you know if OVH is their regular registrar/hosting provider, or if they're migrating or something? I was initially concerned the domain had been hijacked given the whois update tonight. I'm new to crosstool-ng and tool chain building in general so haven't any prior experience of mpc/gmp.

**Comment by cpackham** [comment]
I don't really know that much about mpc either.

I hope our CI builds didn't hammer it. If anyone has any insight on making use of githubs artifact caching that'd probably help.

In terms of getting stuff working you can probably grab the tarball you need from https://github.com/crosstool-ng/crosstool-ng/suites/16108195855/artifacts/921210344 but if you have a CI system of your own then that won't be much help if the site is down.

**Comment by neildavis** [comment]
[multiprecission.org](https://www.multiprecision.org/) seems to be back up and feeding the correct tarballs now so closing this,

**Comment by QBos07** [comment]
>If anyone has any insight on making use of githubs artifact caching that'd probably help.

I'll try to do something about this.
