### ISSUE TITLE
Stuck in building glibc-2.31

### ISSUE THREAD

**Issue by dimich-dmb** [crosstool-ng/crosstool-ng#2035]
crosstool-ng: 1.25.0
OS: Arch Linux 

I tried to build crosstool for ARM Linux with gcc-11.2.0 and glibc-2.31.
`ct-ng build` stuck in `Building C library`. For first time more than 6 hours passed before i interrupted it.
`make` process consumes about 100% CPU. `inotifywait` displays continious access to the same set of files in `.build/arm-unknown-linux-gnueabi/build/build-libc/multilib` in infinite loop (output attached).

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/12630998/config.txt)
[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/12631267/build.log.gz)
[inotifywait.txt.gz](https://github.com/crosstool-ng/crosstool-ng/files/12631310/inotifywait.txt.gz)

**Comment by cpackham** [comment]
This is a known issue with newer versions of GNU make and older versions of
GNU libc. There is a workaround in crosstool-ng 1.26-rc1 or master.

**Comment by dimich-dmb** [comment]
Indeed. Closing as duplicate of #1990.
