### ISSUE TITLE
Build glibc with m68k

### ISSUE THREAD

**Issue by antoyo** [crosstool-ng/crosstool-ng#2040]
crosstool-NG version: crosstool.ng.1.26.0.rc2.0-1
host OS and its version: ArtixLinux
[.config](https://github.com/crosstool-ng/crosstool-ng/files/12704984/crosstool_config.txt)

Hi.
I'd like to build a m68k toolchain with glibc, but the only choices I have for the C library are musl and uClibc-ng.
How can I choos glibc instead?
Thanks.

**Comment by cpackham** [comment]
Selecting glibc depends on `ARCH_USE_MMU` which is not the case for m68k. It does look like [m68k is supported by glibc](https://sourceware.org/git/?p=glibc.git;a=blob_plain;f=README;hb=HEAD) so maybe the ct-ng view of the work hasn't kept up.

**Comment by cpackham** [comment]
#2042 will probably do what you want (and might fix #1844) but it's missed the cut-off for the 1.26.0 release
