### ISSUE TITLE
Can't build toolchain for rpi 4

### ISSUE THREAD

**Issue by abderrahimAMZ** [crosstool-ng/crosstool-ng#2045]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by abderrahimAMZ** [comment]
Hi there, i took the already set rpi 3 toolchain setup, i modified the vendor to rpi 4, cpu to a72 to match that of rpi 4.
this is the error message:
>>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2103]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2063]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2174]
[ERROR]  >>        called from: do_isl_get[scripts/build/companion_libs/121-isl.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]

**Comment by QBos07** [comment]
This error message only show the internal trace.
Please upload `build.log`, `.config` and even more inportant to this error the output of `ct-ng version`.

**Comment by abderrahimAMZ** [comment]
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12838397/build.log)
[
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/12838408/config.txt)
ct-ng version : 1.24.0

**Comment by QBos07** [comment]
Probably best fix for you is to upgrade ct-ng to 1.26

Am 07.10.2023 um 19:47 schrieb Abderrahim Amzaourou ***@***.******@***.***>>:


build.log<https://github.com/crosstool-ng/crosstool-ng/files/12838397/build.log>
[
config.txt<https://github.com/crosstool-ng/crosstool-ng/files/12838408/config.txt>
ct-ng version : 1.24.0

**Comment by abderrahimAMZ** [comment]
Hi! i tried it! i get errors after 20 minutes build, here is the build.log and .config:
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/12908031/build.log)
[config_crosstool.txt](https://github.com/crosstool-ng/crosstool-ng/files/12908041/config_crosstool.txt)

**Comment by modbw** [comment]
build.log says that you need python3 to build your cross-gdb. Maybe try to disable CT_GDB_CROSS_PYTHON

**Comment by abderrahimAMZ** [comment]
thank you modbw, it worked!
