### ISSUE TITLE
path.sh not generated correctly under MSYS2

### ISSUE THREAD

**Issue by c-grant** [crosstool-ng/crosstool-ng#2047]
- crosstools-ng 1.26.0 or cf6b174
- OS Win 11 22H22
- "MSYS2 MSYS" prompt from msys2

paths.sh has no path for python and causes an error during build (missing /usr/bin). Manually adding it allows the build to continue.

contents of path.sh

export install="/usr/bin/install -c"
export bash="/usr/bin/bash"
export bison="/usr/bin/bison"
export awk="/usr/bin/gawk"
export grep="/usr/bin/grep"
export gmake="/usr/bin/make"
export gnumake="/usr/bin/make"
export make="/usr/bin/make"
export python="python3.11"
export sed="/usr/bin/sed"
export libtool="/usr/bin/libtool"
export libtoolize="/usr/bin/libtoolize"
export objcopy="/usr/bin/objcopy"
export objdump="/usr/bin/objdump"
export readelf="/usr/bin/readelf"
export patch="/usr/bin/patch"
export md5sum="/usr/bin/md5sum"
export sha1sum="/usr/bin/sha1sum"
export sha256sum="/usr/bin/sha256sum"
export sha512sum="/usr/bin/sha512sum"

**Comment by c-grant** [comment]
Yes. If I edit 

export python="python3.11"

to be 

export python="/usr/bin/python3.11"

life is good. 

Also I can see in the configure log it finds it correctly at that path, but the variable use to populate path.sh does not contain the path.

**Comment by cpackham** [comment]
Any chance you can share the actual error that occurs. I can see why python is different in paths.sh but I'm not completely sure what problem it causes.

**Comment by c-grant** [comment]
Let me get a a from scratch environment get a log file. No error occurs when building crosstool-ng. The error occurs when doing ct-ng build on any configuration. I says it can't find python3.11 unless I edit path.sh to have the path.
