### ISSUE TITLE
gnatls not copied to build tools when Ada is specified

### ISSUE THREAD

**Issue by c-grant** [crosstool-ng/crosstool-ng#2048]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version : 1.26.0
- Report host OS and its version : Ubuntu 22.04
- Attach `.config` (unless the issue is not related to any configuration) : attached [my.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/13060806/my.config.txt)
- Attach `build.log` (unless crosstool-NG fails before the build starts) : attached [build_log.zip](https://github.com/crosstool-ng/crosstool-ng/files/13060812/build_log.zip)

When trying to executes the additional manual steps to attempt to build a compiler with the Ada language I get the following error

/usr/bin/bash: line 1: x86_64-host_w64-mingw32-gnatls: command not found

Looking in the folder for bintools/bin I noticed all the otherer required gnat executables were copied over.

**Comment by cpackham** [comment]
I think this is now resolved via #2049
