### ISSUE TITLE
Support for the HPPA architecture

### ISSUE THREAD

**Issue by antoyo** [crosstool-ng/crosstool-ng#2050]
Hi.
Could you please add support for the HPPA architecture?
Thanks.

**Comment by cpackham** [comment]
That's not really how open source software works. If hppa is your
particular itch then feel free to scratch it. Changes adding hppa would be
welcome.

The good news is hppa seems to be supported by binutils, glibc and gcc. So
adding should be quite doable.

The most recent architecture added was loongarch in
https://github.com/crosstool-ng/crosstool-ng/commit/e840986fa if your
looking for something to refer to. There's also
https://github.com/crosstool-ng/crosstool-ng/pull/1558 from the last drive
by request.

**Comment by danglin44** [comment]
Here's a first crack at adding hppa:
[hppa.patch](https://github.com/crosstool-ng/crosstool-ng/files/13127454/hppa.patch)

**Comment by danglin44** [comment]
Second crack (adds build script).
[hppa-v2.patch](https://github.com/crosstool-ng/crosstool-ng/files/13127609/hppa-v2.patch)

**Comment by danglin44** [comment]
Forget v2 patch.  v3 adds script.
[hppa-v3.patch](https://github.com/crosstool-ng/crosstool-ng/files/13127677/hppa-v3.patch)

**Comment by danglin44** [comment]
Do I need to setup a pull request to have hppa added?

Note crosstools-ng builds fine on debian-hppa.

**Comment by antoyo** [comment]
I just tried your patch.
I don't know if I did something wrong, but I cannot seem to choose glibc as the C library.
Is this supported by this patch?
Thanks a lot for working on this!

**Comment by cpackham** [comment]
A PR would help. I can handle patches too. I just haven't had a chance to
look at it yet.

**Comment by antoyo** [comment]
I'll confirm soon, but it seems it won't compile when choosing Linux as the OS.
It seems to be because it looks for `.build/src/linux-5.16.20/arch/hppa/Makefile` instead of `.build/src/linux-5.16.20/arch/parisc/Makefile`.

**Comment by danglin44** [comment]
This patch fixes the build error installing the linux headers.  We need to change the arch from "hppa" to "parisc".
[parisc-v1.patch](https://github.com/crosstool-ng/crosstool-ng/files/13193879/parisc-v1.patch)

I also updated config.guess and config.sub.  "uname -m" returns parisc64 when a 64-bit kernel is running and
parisc when a 32-bit kernel is running.  64-bit kernels support both 32 and 64-bit userpace.  For it, we want to
select either hppa or hppa64 depending on whether or not the build compiler defines __LP64__.  The hppa
machine selection causes the build compiler to generate by default PA 1.1 code.  PA 2.0 code can be selected
using either the "-march=2.0" or "-mpa-risc-2-0" options.  For 32-bit code, we want PA 1.1 code by default.  I removed
the bit that selects the code level by looking at /proc/cpuinfo as PA 1.1 code is compatible both PA 1.1 and PA 2.0
machines.
[parisc-config.patch](https://github.com/crosstool-ng/crosstool-ng/files/13193920/parisc-config.patch)

Tested by running "ct-ng build" with a PARISC linux target on hppa and x86_64 build/host machines.

**Comment by cpackham** [comment]
So I'm not sure whether we should call this "hppa" or "parisc".

Looks like the kernel toolchains[1] are called `hppa-linux` so we should at least make sure that whatever we generate is called that and probably any samples should follow suit. That doesn't necessarily mean we have to refer to it as "hppa" internally we already deal with arm vs aarch64.

In terms of the code posted so far it probably would be easier to deal with a pull request with proper commits (including a decent commit message and sign-off). It appears to be missing `ARCH_SUPPORTS_64` and we could do with a sample config or two.

[1] - https://cdn.kernel.org/pub/tools/crosstool/

**Comment by thesamesam** [comment]
wrt `ARCH_SUPPORTS_64` - just keep in mind it doesn't yet support 64-bit userland in glibc, although we hope to get there at some point (I'm not sure what it means in the context of crosstool-ng though).

In Gentoo, we call the arch `hppa`, and so does Debian. We both use a tuple beginning with `hppa*`. But the kernel and glibc arch is `parisc`.

**Comment by danglin44** [comment]
> So I'm not sure whether we should call this "hppa" or "parisc".
>
The Kane book says:
"Hewlett-Packard’s PA-RISC architecture was first introduced in 1986."

Different projects abbreviate this differently.  The linux kernel uses "parisc", gcc uses "pa" for its arch directories, glibc uses "hppa", etc.

"hppa" is used by the Debian and Gentoo projects.  There is no 64-bit hppa-linux architecture yet as 64-bit glibc port is not done.  There
are 64-bit ports for binutils and gcc.

Config.guess maps "parisc" to "hppa".  It should also map "parisc64" to "hppa64" as 64-bit kernel returns "parisc64".  We have to keep
the crosstool-ng naming consistent with the existing naming of the 64-bit binutils and gcc tools.

Using "parisc" for the architecture name in crosstool-ng was the simplest way to get this command right:
[DEBUG]    ==> Executing:  'make' '-C' '/home/dave/gnu/crosstool-ng/.build/hppa-unknown-linux-gnu/src/linux' 'BASH=/home/dave/gnu/crosstool-ng/.build/tools/bin/bash' 'HOSTCC=x86_64-build_pc-linux-gnu-gcc' 'CROSS_COMPILE=hppa-unknown-linux-gnu-' 'O=/home/dave/gnu/crosstool-ng/.build/hppa-unknown-linux-gnu/build/build-kernel-headers' 'ARCH=parisc' 'INSTALL_HDR_PATH=/home/dave/x-tools/hppa-unknown-linux-gnu/hppa-unknown-linux-gnu/sysroot/usr' 'V=0' 'headers_install'

Attached build config that I used.
>
> Looks like the kernel toolchains[1] are called |hppa-linux| so we should at least make sure that whatever we generate is called that and probably any samples should follow suit. That doesn't necessarily mean we have to refer to it as "hppa" internally we already deal with arm vs aarch64.
>
This is tool naming for x86_64 build:
dave@pad:~/x-tools/hppa-unknown-linux-gnu/bin$ ls
hppa-unknown-linux-gnu-addr2line hppa-unknown-linux-gnu-gcov-tool
hppa-unknown-linux-gnu-ar            hppa-unknown-linux-gnu-gprof
hppa-unknown-linux-gnu-as            hppa-unknown-linux-gnu-ld
hppa-unknown-linux-gnu-cc            hppa-unknown-linux-gnu-ld.bfd
hppa-unknown-linux-gnu-c++filt       hppa-unknown-linux-gnu-ldd
hppa-unknown-linux-gnu-cpp           hppa-unknown-linux-gnu-lto-dump
hppa-unknown-linux-gnu-ct-ng.config  hppa-unknown-linux-gnu-nm
hppa-unknown-linux-gnu-elfedit       hppa-unknown-linux-gnu-objcopy
hppa-unknown-linux-gnu-gcc           hppa-unknown-linux-gnu-objdump
hppa-unknown-linux-gnu-gcc-13.2.0    hppa-unknown-linux-gnu-populate
hppa-unknown-linux-gnu-gcc-ar        hppa-unknown-linux-gnu-ranlib
hppa-unknown-linux-gnu-gcc-nm        hppa-unknown-linux-gnu-readelf
hppa-unknown-linux-gnu-gcc-ranlib    hppa-unknown-linux-gnu-size
hppa-unknown-linux-gnu-gcov          hppa-unknown-linux-gnu-strings
hppa-unknown-linux-gnu-gcov-dump     hppa-unknown-linux-gnu-strip

This is tool naming for Debian hppa64 cross tools:
dave@mx3210:~$ ls /usr/bin/hppa64*
/usr/bin/hppa64-linux-gnu-addr2line /usr/bin/hppa64-linux-gnu-gcc-ar-5
/usr/bin/hppa64-linux-gnu-ar /usr/bin/hppa64-linux-gnu-gcc-ar-6
/usr/bin/hppa64-linux-gnu-as /usr/bin/hppa64-linux-gnu-gcc-ar-9
/usr/bin/hppa64-linux-gnu-c++filt /usr/bin/hppa64-linux-gnu-gcc-nm
/usr/bin/hppa64-linux-gnu-cpp /usr/bin/hppa64-linux-gnu-gcc-nm-11
/usr/bin/hppa64-linux-gnu-cpp-11 /usr/bin/hppa64-linux-gnu-gcc-nm-12

We could try to drop the "unknown" manufacturer from the crosstool names as it doesn't provide any useful information.

> In terms of the code posted so far it probably would be easier to deal with a pull request with proper commits (including a decent commit message and sign-off). It appears to be missing |ARCH_SUPPORTS_64| and we could do with a sample config or two.
>
I intentionally omitted ARCH_SUPPORTS_64 as 64-bit glibc port is missing.  Would it be useful without glibc?

Once things finalize, I could send email with commit message and signoff.  If archive is needed for pull, I will ask Helge Deller to set it up as he has
archives for other projects setup on internet. 
[config-hppa-unknown-linux-gnu.txt](https://github.com/crosstool-ng/crosstool-ng/files/13198751/config-hppa-unknown-linux-gnu.txt)

**Comment by antoyo** [comment]
I confirm I can build a gcc for hppa with the 2 parics patches. Thanks a lot!

**Comment by danglin44** [comment]
Add support for 32 and 64-bit PA-RISC linux build targets.

Note: The 64-bit target lacks a glibc port and doesn't build.  Also, there is no uclibc support.

Signed-off-by: John David Anglin [<dave.anglin@bell.net>](mailto:dave.anglin@bell.net)
---
[parisc-v2.patch](https://github.com/crosstool-ng/crosstool-ng/files/13321011/parisc-v2.patch)

**Comment by danglin44** [comment]
Map parisc64 to hppa64 in config.sub.

Debian and Gentoo use hppa/hppa64 for the PA-RISC ports.  These are the proper CPU designations for configuring most packages.

Signed-off-by: John David Anglin [<dave.anglin@bell.net>](mailto:dave.anglin@bell.net)
---
[config-sub.patch](https://github.com/crosstool-ng/crosstool-ng/files/13321159/config-sub.patch)

**Comment by danglin44** [comment]
Adjust GUESS tuple for PA-RISC linux.

64-bit kernels can support running both 32 and 64-bit user code.  Select hppa-unknown-linux-$LIBC or hppa64-unknown-linux-$LIBC depending on whether compiler defines __LP64__ or not.

Always select hppa-unknown-linux-$LIBC with 32-bit kernel.  This will generate 32-bit PA 1.1 code.  If PA 2.0 code is desired, user can use a compiler option to select it.

Signed-off-by: John David Anglin [<dave.anglin@bell.net>](mailto:dave.anglin@bell.net)
---
[config-guess.patch](https://github.com/crosstool-ng/crosstool-ng/files/13321345/config-guess.patch)

**Comment by cpackham** [comment]
Closed via #2067. It would be good if someone that has an interest in this architecture could look at the C++ and uclibc support.
