### ISSUE TITLE
Error during the build process

### ISSUE THREAD

**Issue by Bajjounada** [crosstool-ng/crosstool-ng#2054]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

[config.log](https://github.com/crosstool-ng/crosstool-ng/files/13196511/config.log)

file:///home/nada/Embedded_linux/cross_compiler/crosstool-ng/build.log

**Comment by Bajjounada** [comment]
this is the error 

[EXTRA]    Configuring cross gdb
[EXTRA]    Building cross gdb
[ERROR]    configure: error: no usable python found at python3.10
[ERROR]    make[2]: *** [Makefile:11448: configure-gdb] Error 1
[ERROR]    make[1]: *** [Makefile:1005: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
[ERROR]  >>        called from: do_gdb_backend[scripts/build/debug/300-gdb.sh@357]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@80]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@707]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 56:41.43)
[56:42] / gmake: *** [/usr/local/bin/ct-ng:261: build] Error 2

**Comment by cpackham** [comment]
You're missing the python-dev package for your system. You can either
install it or disable python support for gdb.

**Comment by Bajjounada** [comment]
Thank you cpackam it worked

**Comment by AshkanRamezani** [comment]
does it mean that i should open menuconfig (with command ./ct-ng menuconfig) on cross tool-ng then inactive gdb or its something else?! could you please explain more?!

also i use these command to solve the same problem bit i didnt woorked!
sudo apt-get update
sudo apt-get install python-dev

**Comment by QBos07** [comment]
Please make a new issue and upload your configuration.
