### ISSUE TITLE
error happened in: CT_DoExecLog[scripts/functions@377]

### ISSUE THREAD

**Issue by SatNaingTun** [crosstool-ng/crosstool-ng#2059]
crosstool-NG version 1.26.0.22_daf19e1
host OS:Ubuntu 22.04.3 LTS
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/13263506/config.log)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/13263508/build.log)

ERROR]  >>  Build failed in step 'Installing core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@377]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/gcc.sh@711]
[ERROR]  >>        called from: do_cc_core[scripts/build/cc/gcc.sh@212]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@708]
[ERROR]  >>

**Comment by QBos07** [comment]
You ran out of disk space for the final link

**Comment by SatNaingTun** [comment]
Thank You. I solve the storage problem and I can build ct-ng.
