### ISSUE TITLE
Option to build target executables as static

### ISSUE THREAD

**Issue by QBos07** [crosstool-ng/crosstool-ng#2060]
Would it make sense to add an option to link target executables like gdbserver static? `CT_SHARED_LIBS=n` just add `--disable-shared` to the libararies configure. glibc breaks with that option and someone may want the shared libs but only nativ gdb staticly.

**Comment by cpackham** [comment]
We do already have `GDB_NATIVE_STATIC` which will help for the native gdb/gdbserver. There's a few other native tools like strace that we might like to extend this to but the existing option seems to cover the common use-case.

**Comment by QBos07** [comment]
Didn't saw the option. Was marked as experimental.
