### ISSUE TITLE
Crosstool-NG failing to download the "zlib-1.2.12"

### ISSUE THREAD

**Issue by Bajjounada** [crosstool-ng/crosstool-ng#2063]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
 file:///home/nada/Downloads/build.log
file:///home/nada/Downloads/config.log
User
./ct-ng menuconfig
  CONF  menuconfig
configuration written to .config

* End of the configuration.
* Execute 'ct-ng build' to start the build or try 'ct-ng help'.

houda@houda-HP-EliteBook-840-G5:~/Embedded_linux/cross_compiler/crosstool-ng$ ./ct-ng build
[INFO ]  Performing some trivial sanity checks
[WARN ]  Number of open files 1024 may not be sufficient to build the toolchain; increasing to 2048
[INFO ]  Build started 20231106.154636
[INFO ]  Building environment variables
[WARN ]  Directory '/home/houda/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = aarch64-unknown-linux-gnu
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.10s (at 00:02)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'linux-5.16.9'
[EXTRA]    Verifying SHA512 checksum for 'linux-5.16.9.tar.xz'
[EXTRA]    Retrieving 'zlib-1.2.12'
[ERROR]    zlib: download failed
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@487]
[ERROR]  >>        called from: CT_DoFetch[scripts/functions@2130]
[ERROR]  >>        called from: CT_PackageRun[scripts/functions@2090]
[ERROR]  >>        called from: CT_Fetch[scripts/functions@2201]
[ERROR]  >>        called from: do_zlib_get[scripts/build/companion_libs/050-zlib.sh@16]
[ERROR]  >>        called from: do_companion_libs_get[scripts/build/companion_libs.sh@15]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@649]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 2:32.75)
[02:33] / make: * [ct-ng:261: build] Error 1
houda@houda-HP-EliteBook-840-G5:~/Embedded_linux/cross_compiler/crosstool-ng$

**Comment by QBos07** [comment]
See #1832
