### ISSUE TITLE
Build failure in libbacktrace.

### ISSUE THREAD

**Issue by patlefort** [crosstool-ng/crosstool-ng#2069]
Version: 1.26.0
OS: Arch Linux (x86-64)
Building GCC 13.2.0 for `aarch64` with static toolchain.

```
[ALL  ]    checking for aarch64-unknown-elf-gcc... /home/elrick/Temp/crosstool-build/aarch64-unknown-elf/build/build-cc-gcc-final/./gcc/xgcc -B/home/elrick/Temp/crosstool-build/aarch64-unknown-elf/build/build-cc-gcc-final/./gcc/ -B/home/elrick/Software/x-tools/aarch64-unknown-elf/aarch64-unknown-elf/bin/ -B/home/elrick/Software/x-tools/aarch64-unknown-elf/aarch64-unknown-elf/lib/ -isystem /home/elrick/Software/x-tools/aarch64-unknown-elf/aarch64-unknown-elf/include -isystem /home/elrick/Software/x-tools/aarch64-unknown-elf/aarch64-unknown-elf/sys-include
[ALL  ]    no
[ERROR]    configure: error: in `/home/elrick/Temp/crosstool-build/aarch64-unknown-elf/build/build-cc-gcc-final/aarch64-unknown-elf/libbacktrace':
[ERROR]    configure: error: C compiler cannot create executables
[ALL  ]    See `config.log' for more details
[ERROR]    make[2]: *** [Makefile:13667: configure-target-libbacktrace] Error 1
```

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/13380472/build.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/13380478/config.txt)

**Comment by cpackham** [comment]
Would you be able to grab the config.log from
/home/elrick/Temp/crosstool-build/aarch64-unknown-elf/build/build-cc-gcc-final/aarch64-unknown-elf/libbacktrace
as well

**Comment by patlefort** [comment]
libbacktrace log: [config.log](https://github.com/crosstool-ng/crosstool-ng/files/13383247/config.log)

**Comment by QBos07** [comment]
Instresting, newlib is asking for some minimal os funktions to make an executable.
Autoconfigure not disinguhsing between libs and exes is kinda common to cause problems (See #1555 for example).

**Comment by cpackham** [comment]
@patlefort are you intentionally choosing the bare-metal aarch64 toolchain (`aarch64-unknown-elf`) instead of something like `aarch64-unknown-linux-gnu`? If it's intentional then I suspect you will need to add `--specs=nosys.specs` somewhere for libbacktrace to be happy without an OS.

**Comment by patlefort** [comment]
No, I configured it via menuconfig and didn't touch anything regarding that last `-elf` part.

**Comment by patlefort** [comment]
It compile fine after selecting linux as the target OS. I didn't know bare-metal was a thing, I assumed it would default to linux.
