### ISSUE TITLE
Build error messages (in C library) with `aarch64-unknown-linux-gnu` + glibc 2.17 + gcc 12.3

### ISSUE THREAD

**Issue by misterBart** [crosstool-ng/crosstool-ng#2070]
I am using preset `aarch64-unknown-linux-gnu` with the following changes:

- Linux 6.2.12
- glibc 2.17
- gcc 12.3 and disabled 'Optimize gcc libs for size'

This gives me the following build error message:
```
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      /home/personac/crosstool-ng_build_toolchain/.build/aarch64-unknown-linux-gnu/buildtools/lib/gcc/aarch64-unknown-linux-gnu/12.3.0/../../../../aarch64-unknown-linux-gnu/bin/ld.bfd: Dwarf Error: Can't find .debug_ranges section.
[EXTRA]      Installing C library
[INFO ]    Building for multilib 1/1: '': done in 142.07s (at 14:34)
[INFO ]  Installing C library: done in 142.15s (at 14:34)
```

Yet the build process is not aborted, I obtain the toolchain. Still, the error message makes me uneasy whether this toolchain is stable or not. Can anyone say something about this?

My issue is probably the same issue as mentioned in https://github.com/crosstool-ng/crosstool-ng/issues/1546 and https://gcc.gnu.org/bugzilla/show_bug.cgi?id=100725
The latter URL mentions you need binutils >= 2.35 for gcc >= 11. Yet preset `aarch64-unknown-linux-gnu` + glibc 2.17 forces me to binutils 2.29.1 or lower.

Solution: `C library > extra traget CFLAGS > -gdwarf-4`
Is this a decent (or the only?) solution?

Crosstool version: git master branch (1.26.0.25_032b3a0, cloned at 20 November 2023)
Host OS: Ubuntu Linux 23.04 (WSL)
[build-aarch64-glibc2.17-gcc12.3.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/13425519/build-aarch64-glibc2.17-gcc12.3.log.zip)
[config-aarch64-glibc2.17-gcc12.3.txt](https://github.com/crosstool-ng/crosstool-ng/files/13425522/config-aarch64-glibc2.17-gcc12.3.txt)

**Comment by cpackham** [comment]
Yeah the extra CFLAGS thing is about the best solution (or use a newer
glibc). The toolchain will still work (aside from a bunch of extra
messages) but you may hit problems if you ever want to load the binaries
into a debugger.

**Comment by misterBart** [comment]
Clear. Thanks for info.
