### ISSUE TITLE
-mhard-float and -mfloat-abi=hard common denominator

### ISSUE THREAD

**Issue by igorpupkinable** [crosstool-ng/crosstool-ng#2072]
Which `-mfloat-abi` is `-mhard-float` option equivalent to for ARM CPUs: softfp or hard?

Unfortunately I could not figure this out from source code.
I have two devices and two toolchains provided by manufacturer. First one is crosstool-ng with `-mhard-float` set. Second one is GCC with `-mfloat-abi=hard` set.
Are these options equivalent?

**Comment by cpackham** [comment]
From reading https://gcc.gnu.org/onlinedocs/gcc-13.2.0/gcc/ARM-Options.html I suspect you probably want `-mfloat-abi=hard`

I'm not sure how your manufacturer can have a toolchain with `-mhard-float` as ARM doesn't appear to support that.

**Comment by igorpupkinable** [comment]
> I'm not sure how your manufacturer can have a toolchain with `-mhard-float` as ARM doesn't appear to support that.

Well, it is in the [ARM architecture code](https://github.com/crosstool-ng/crosstool-ng/blob/cd0d14697dfaf6ab688ea6dd465cecaf888f6e36/scripts/build/arch/arm.sh#L116).

Your suspicion seems to be the right one. I've taken an alternative approach by checking ELF headers on a device with crosstool-ng and `-mfloat-abi` setting, e.g.
```bash
$ readelf -h /lib/libc.so.6 | grep Flags
  Flags: 0x5000400, Version5 EABI, hard-float ABI
$ readelf -A /lib/libpth.so | grep VFP
  Tag_FP_arch: VFPv3-D16
  Tag_ABI_VFP_args: VFP registers
```

Most of shared objects and executables were compiled with VFP registers on that device, so this proves to me that crosstool-ng's `-mhard-float` settings is equivalent to GCC's `-mfloat-abi=hard`

Ref; https://stackoverflow.com/questions/20555594/how-can-i-know-if-an-arm-library-is-using-hardfp
