### ISSUE TITLE
zlib 1.2.13 upstream link changed

### ISSUE THREAD

**Issue by danmons** [crosstool-ng/crosstool-ng#2075]
The zlib website has removed version 1.2.13 from their standard download location, replacing it with 1.3.  This is causing builds to break if they search for the tar.gz file from the upstream URL. 

Potentially changing the URL in `crosstool-ng/packages/zlib/package.desc` from `https://www.zlib.net/` to `https://www.zlib.net/fossils/` will fix this breaking on each update (it broke during the update from 1.2.12 to 1.2.13 as well, as per #1832 ), as the current stable version also lives in that location, as well as legacy versions. (Worked for me locally as a test).

**Comment by cpackham** [comment]
sigh. Yeah I think maybe going with the `fossils` link is better. I had been avoiding it because they only mirror the gz files so there's not xz file and more worryingly no GPG signature that can be verified.

**Comment by cpackham** [comment]
They are putting all the artifacts on the github repo so that might actually be a better alternative

**Comment by cpackham** [comment]
Actually I already did that in 82346dd7dfe7 did that logic not work for you?

**Comment by danmons** [comment]
> Actually I already did that in [82346dd](https://github.com/crosstool-ng/crosstool-ng/commit/82346dd7dfe7ed20dc8ec71e193c2d3b1930e22d) did that logic not work for you?

Ah yes, this did work.  Thank you.
