### ISSUE TITLE
Build failed in step 'Installing GMP for host'

### ISSUE THREAD

**Issue by ghinlon** [crosstool-ng/crosstool-ng#2091]
- Report crosstool-NG version
  git master
- Report host OS and its version
  Ubuntu 22.04.3 LTS \n \l
- Attach `.config` (unless the issue is not related to any configuration)
  `ct-ng aarch64-unknown-linux-gnu` with read-only unchecked.
- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/14016914/build.log)

**Comment by ghinlon** [comment]
What amount of memory is required?

**Comment by QBos07** [comment]
4G didn't worked for me but 16 or higher shoud be fine if youre not doing something else on the maschine.

**Comment by ghinlon** [comment]
> Could be that you run out of memory or disk space. There is just `Killed` in the log.

Thank you. I increased the memory from 8GB to 12GB, and the build was successful.
