### ISSUE TITLE
Glob support in Binutils is disabled even when creating host toolchain for Windows

### ISSUE THREAD

**Issue by mati865** [crosstool-ng/crosstool-ng#2094]
- Report crosstool-NG version
1.26.0
- Report host OS and its version
Build: Ubuntu 22.04 
Host: Windows
Target: Windows
It's cross-native build.

https://github.com/crosstool-ng/crosstool-ng/pull/1408 has disabled glob support in Binutils for all OS while it sounds like the intention was to do it only for glibc targets (that approach itself is questionable to me but I'll pass on it).
This causes real world issues when trying to use cross-native mingw-w64 based toolchain with Rust:
`C:/a/rust/rust/i686-w64-mingw32/bin/../lib/gcc/i686-w64-mingw32/13.2.0/../../../../i686-w64-mingw32/bin/ld.exe: cannot find C:\a\rust\rust\build\i686-pc-windows-gnu\stage2\lib\rustlib\i686-pc-windows-gnu\lib/liballoc-*.rlib: Invalid argument`
Testsuite rightfully expects the linker to handle globs so the tests fail.

**Comment by cpackham** [comment]
@abrodkin I'm kind of thinking of reverting 57f5909 any objection (hopefully accompanied by a better suggestion).

**Comment by abrodkin** [comment]
@cpackham go ahead with the revert. We need to move on and just use a more up-to-date environment.

**Comment by mati865** [comment]
I suggest trying what most of the projects wanting compatibility with older systems do: build using Docker/Podman with base image old enough to be compatible with wide range of the systems. Glibc is backwards compatible and libstdc++ is mostly backwards compatible.
