### ISSUE TITLE
Ignore error when setting `CT_SYS_USER`

### ISSUE THREAD

**Issue by fschoenm** [crosstool-ng/crosstool-ng#2104]
In [scripts/crosstool-NG.sh](https://github.com/crosstool-ng/crosstool-ng/blob/4d660cff7dfb055eb112d5ccb3f5c481aa797969/scripts/crosstool-NG.sh#L267), the scripts tries to set `CT_SYS_USER`. However, in my case (tried to run a build in Docker), the `id -un` command fails because the user ID is not known in my container. This is not necessarily required but crosstool fails to continue. It seems that `CT_SYS_USER` serves no real purpose other than logging the user name. 

I propose setting the value to "unknown" or anything really if the `id` call fails.

crosstool-NG version 1.26.0

**Comment by QBos07** [comment]
ct-ng checks if the build is run as root but I go with you here that we should have docker compatibility.
