### ISSUE TITLE
Build Failure - g++ fatal error

### ISSUE THREAD

**Issue by Xylopyrographer** [crosstool-ng/crosstool-ng#2107]
***Quick background:***

Built ct-ng using the following commands:
```
cd ~
rm -rf crosstool-ng
git clone https://github.com/crosstool-ng/crosstool-ng.git
cd crosstool-ng
git checkout crosstool-ng-1.26.0
./bootstrap
./configure --prefix=${PWD}
make
make install
```
While in the `crosstool-ng` directory, ran the build using:
```
bin/ct-ng arm-unknown-linux-gnueabi
bin/ct-ng menuconfig
bin/ct-ng build
```

That build failed. Repeated the attempt (while still in the `crosstool-ng` directory) using:

`bin/ct-ng build.1`

That build also failed.

Attaching the `.conf` file used in both attempts as well as the build logs for both attempts.
- File `build.log` is for the attempt using `build`.
- FIle `build.1.log` is for the attempt using `build.1`

**Q:** Should one run `ct-ng distclean` before attempting a rebuild?

FWIW, I've only been able to build one tool chain in about a dozen attempts.

***crosstool-NG version:*** 1.26.0

***Host OS and its version***
```
OS: Debian GNU/Linux 12 (bookworm) x86_64 
Host: Macmini7,1 1.0 
Kernel: 6.5.0-0.deb12.4-amd64 
Shell: zsh 5.9 
Resolution: 1920x1080 
DE: GNOME 43.9 
WM: Mutter 
WM Theme: Adwaita 
Theme: Adwaita-dark [GTK2/3] 
Icons: Adwaita [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-4260U (4) @ 2.700GHz 
GPU: Intel Haswell-ULT 
Memory: 1979MiB / 3789MiB 
```

[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/14186784/config.zip)
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/14186785/build.zip)
[build.1.zip](https://github.com/crosstool-ng/crosstool-ng/files/14186786/build.1.zip)

**Comment by cpackham** [comment]
Error message from the log is
```
[ALL  ]    {standard input}: Assembler messages:
[ALL  ]    {standard input}:318395: Warning: end of file not at end of a line; newline inserted
[ERROR]    {standard input}:319228: Error: invalid operands (*UND* and .gcc_except_table sections) for `-'
[ERROR]    g++: fatal error: Killed signal terminated program cc1plus
```
the re-run only seems to have the `g++: fatal error`

My initial gut reaction is that maybe you ran out of disk space and on the re-run the truncated file was already present hence straight to the error. As a bit of a guide we're configuring a 20GB case-sensitive volume for the macOS CI builds, most configurations probably won't need that much but I would suggest you make sure you have at least 15GB available.

**Comment by cpackham** [comment]
Also might be worth checking that the kernel's OOM killer isn't terminating things on you. That's also been known to cause odd failures.

**Comment by Xylopyrographer** [comment]
***Very much*** appreciate the reply.

The machine is a Mac mini, but it's running Debian Bookworm, so no macOS issues there.

Drive is a 1TB SSD, ext4 formatted with 950GB available so drive space shouldn't be an issue either.

Guess that leaves us with a potential OOM issue? The machine has (has only) 4GB RAM & is running GNOME/Mutter. I'm connecting via rdp.

I'll noodle for a bit on that...

Thanks again!

**Comment by Xylopyrographer** [comment]
@cpackham  - As you mentioned macOS, Could I ask about the status of crosstool-ng support for current macOS? (macOS 14 "Sonoma").

I went the dedicated Debian box route as it appears macOS support was dropped many years ago?

**Comment by cpackham** [comment]
macOS support has always been a bit problematic mainly because of the lack of access to it for those of us who actually work on crosstool-ng. I can spin up pretty much any Linux distro in a docker container. But when it comes to macOS or windows it's not easy for me to access. I'm happy to take macOS patches (provided they're well written and don't break others) but I can't offer any support myself.

It does sound like you might be be hitting the OOM. Starting a fresh build with `ct-ng build.1` might help (it will be a lot slower) but then even with single threaded building you could end up with a big link step eating all your RAM.

It could also be that your `/tmp` is running out of space if it's on a different partition (I've had that happen to me more than once).

**Comment by QBos07** [comment]
Had problems with 4GB of ram before. 8GB and up ran fine.

**Comment by Xylopyrographer** [comment]
> 
> It does sound like you might be be hitting the OOM. Starting a fresh build with `ct-ng build.1` might help (it will be a lot slower) but then even with single threaded building you could end up with a big link step eating all your RAM.
> 

Ran it again using...
```
cd ~/crosstool-ng
bin/ct-ng distclean
bin/ct-ng arm-unknown-linux-gnueabi
bin/ct-ng menuconfig
bin/ct-ng build.1
```
... and it built OK!

So, seems this can be chalked up to the machine needing a gob more RAM to run parallel processes (which sadly isn't an option on this puppy).

I'll build another tomorrow to confirm & if that works. close this issue.

Does leave the question: **Is it necessary or a best practice to do a `distclean` or `clean` every time before starting a new `menuconfig` and `build`?**

Appreciate the help.

**Comment by cpackham** [comment]
It kind of depends. If you're building different configs one after the
other then you shouldn't need the distclean. But if you're debugging
something having failed then you probably do want the clean or to use some
of the debugging options to save/resume steps.

**Comment by Xylopyrographer** [comment]
Can pretty much confirm this issue was caused by running on a machine with insufficient RAM (4GB) for the task.

Fired up a (much more modern) machine & redid the previously failed builds and they all built as expected.

Not sure if anything could be done within ct-ng before starting the build to warn about needed resources? Maybe:
- a check on available RAM beforehand?
- include in the docs minimum (or suggested) RAM?

Thanks ct-ng team for the very large effort to keep this working!
