### ISSUE TITLE
v1.26.0 fails to compile: Makefile errors

### ISSUE THREAD

**Issue by tcreek** [crosstool-ng/crosstool-ng#2109]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version: 1.26
- Report host OS and its version: Debian 11
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

I did notice a config issue of error: Required tool not found: libtool despite it being in the path. I had to end up using 
`LIBTOOL=/usr/bin ./configure --prefix=/opt/crosstool-ng` to get it to proceed.

After running make, I get the following:

```
gmake[1]: Entering directory '/usr/src/crosstool-ng-1.26.0'
Making all in kconfig
gmake[2]: Entering directory '/usr/src/crosstool-ng-1.26.0/kconfig'
/usr/bin/gmake  all-am
gmake[3]: Entering directory '/usr/src/crosstool-ng-1.26.0/kconfig'
  CCLD     conf
/bin/bash: line 1: /usr/bin: Is a directory
gmake[3]: *** [Makefile:559: conf] Error 126
gmake[3]: *** Waiting for unfinished jobs....
  CCLD     nconf
/bin/bash: line 1: /usr/bin: Is a directory
gmake[3]: *** [Makefile:585: nconf] Error 126
gmake[3]: Leaving directory '/usr/src/crosstool-ng-1.26.0/kconfig'
gmake[2]: *** [Makefile:474: all] Error 2
gmake[2]: Leaving directory '/usr/src/crosstool-ng-1.26.0/kconfig'
gmake[1]: *** [Makefile:2674: all-recursive] Error 1
gmake[1]: Leaving directory '/usr/src/crosstool-ng-1.26.0'
make: *** [Makefile:2421: all] Error 2
```

I have uploaded a config.log, but I am not finding a build log.

[config.log](https://github.com/crosstool-ng/crosstool-ng/files/14299528/config.log)

**Comment by cpackham** [comment]
Looks like you're missing the libtool-bin package (no idea why Debian has
it separated from the rest of libtool)

**Comment by tcreek** [comment]
Thank you kindly. Not only was the configure issue resolved, but also the compile.
