### ISSUE TITLE
build failed on mac for arm-unknown-linux-gnueabi

### ISSUE THREAD

**Issue by wangp27** [crosstool-ng/crosstool-ng#211]
Hi there,
I am trying to build that on mac, by using default GCC from Xcode, and brew the crosstool-ng.

[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:51:72: error: use of undeclared identifier 'do_not_use_isalnum_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:75:72: error: use of undeclared identifier 'do_not_use_iscntrl_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:83:72: error: use of undeclared identifier 'do_not_use_isdigit_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:91:72: error: use of undeclared identifier 'do_not_use_isgraph_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:99:72: error: use of undeclared identifier 'do_not_use_islower_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:107:72: error: use of undeclared identifier 'do_not_use_isprint_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:115:72: error: use of undeclared identifier 'do_not_use_ispunct_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:123:72: error: use of undeclared identifier 'do_not_use_isspace_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:131:72: error: use of undeclared identifier 'do_not_use_isupper_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:139:73: error: use of undeclared identifier 'do_not_use_isxdigit_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:147:72: error: use of undeclared identifier 'do_not_use_tolower_with_safe_ctype'
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cctype:155:72: error: use of undeclared identifier 'do_not_use_toupper_with_safe_ctype'
[ERROR]    make[5]: *** [binary.o] Error 1
[ERROR]    make[4]: *** [all-recursive] Error 1
[ERROR]    make[3]: *** [all] Error 2
[ERROR]    make[2]: *** [all-gold] Error 2
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@216]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@236]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@101]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/Cellar/crosstool-ng/1.21.0/share/doc/crosstool-ng/ct-ng.1.21.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 6:55.00)
[06:55] / make: *** [build] Error 1
I keep getting this errors
 From the build.log it seems doing the following command and goes wrong,
[ALL  ]    libtool: link: x86_64-build_apple-darwin15.0.0-gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -O2 -g -pipe -Wl,-no_pie -o readelf readelf.o version.o unwind-ia64.o dwarf.o elfcomm.o  ../libiberty/libiberty.a -lz
[ERROR]    make[1]: *** [all] Error 2

I am new to this, hope some people can help me with that, thank you.

**Comment by bhundven** [comment]
@mingwandroid Can you look at this one? Man I need my MacBook Pro fixed... *sigh*

**Comment by roolebo** [comment]
gold linker cannot be compiled... It can be disabled through menuconfig if it's not needed.

**Comment by mingwandroid** [comment]
I'm fixing these things today.

**Comment by bhundven** [comment]
@wangp27 Please clone the latest git master branch, and try this again. #283 has been merged.

**Comment by bhundven** [comment]
@roolebo It looks like gold linker can be enabled, it just needed a patch. ;)

**Comment by bhundven** [comment]
With the addition of #289, I'm going to consider this issue closed.
Please re-open if the issue still persists.
