### ISSUE TITLE
Publish the PGP key on website

### ISSUE THREAD

**Issue by breser** [crosstool-ng/crosstool-ng#212]
You're providing PGP signatures on the downloads.  That's great.  But in order to verify that signature you need a way to trust it.  One way is to try and use the PGP web of trust.  But that's not available to all users since they have to work their way into the web of trust.  A better option is to publish the key information in multiple places.  The project website, on github (in the repo), in an any announcement emails sent out, subject of your IRC server, personal web pages etc...  If someone can find the key in multiple places that all match and all say this is what they should expect from a crosstool-ng release, then they can be reasonably confident it's the right key.

**Comment by bhundven** [comment]
I know that my personal key ```35B871D1``` is published to the http://pgp.surfnet.nl/ server fingerpint: ```561E D9B6 2095 88ED 23C6  8329 CAD7 C8FC 35B8 71D1```

I'm sure that information is not currently posted, and I will make an effort to do so.

**Comment by breser** [comment]
Thanks.  I'd already pulled the key down from the key servers, I just didn't have a good way to validate it was the correct key.  So your posting here and ultimately updating the project to publish it elsewhere is what I'm looking for.

**Comment by bhundven** [comment]
@breser Yup, when I do the next release, I will update the website and the tarball. Thanks for reporting!

**Comment by bhundven** [comment]
@breser I have updated the wiki with the signature verification process.
I will update the documentation with #44.

**Comment by bhundven** [comment]
http://crosstool-ng.org/#using_a_released_version
