### ISSUE TITLE
ct-ng build command fails on my Linux Laptop

### ISSUE THREAD

**Issue by RizwanFazal** [crosstool-ng/crosstool-ng#2130]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version: Released 1.26.0
- Report host OS and its version: Ubuntu 22.04.3 LTS
- Attach `.config` (unless the issue is not related to any configuration)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/14649286/config.txt)

- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/14649213/build.log)

Hi,

I have been trying to build a cross tool-chain for my Raspberry Pi 4 Model B board using the released 1.26.0 version of the Crosstool-NG generator. When I execute the command 'ct-ng build', it gets stuck at some point and eventually build fails. The details can be found on the attached 'build.log' file. Looking forward for your kind help please. I will remain grateful for your humble support.

**Comment by QBos07** [comment]
You are failing the linux kernel download. Is your internet spotty?

**Comment by QBos07** [comment]
You could try to up the number of tries in the `wget` arguments ans/or add `--continue`.

**Comment by cpackham** [comment]
Another thing you can to is use the `ct-ng source` command which will do all the downloading first before starting the build.

**Comment by RizwanFazal** [comment]
Here is an update. Today I started it all over again the process of cloning, configuring and building the crosstool-ng. This time, it managed to download tarballs and reached at 'Installing final GCC' step where it took so much time and 'terminal' crashed.

I tried to build it (ct-ng build) two times. First time, the system was connected with internet but the second time, I kept the internet connection 'Off'. In both the situations, the terminal crashed at the same point, 'Installing final GCC'. Now what it is?? Below is my system hardware specifications. Is it the problem with my laptop system or something related to the 'crosstool-ng'?

RAM: 4.0 GiB
Processor: Intel® Core™ i3-4030U CPU @ 1.90GHz × 4
Graphics: Mesa Intel® HD Graphics 4400 (HSW GT2)

**Comment by QBos07** [comment]
Propably not enougth RAM. I can recomand 6GB+.

**Comment by RizwanFazal** [comment]
> Propably not enougth RAM. I can recomand 6GB+.

Are you sure it is because of RAM size?

Can you please recommend me few links from where I can get the 'Pre-built Binary Toolchain' for raspberry pi 4 board. It's been three days already that I couldn't get any success in building the tool-chain by myself. I am running out of time and hence wanna get it done asap. Waiting for your kind response..

**Comment by QBos07** [comment]
[Precompiled ct-ng toolchains (using docker)](https://github.com/tttapa/docker-arm-cross-toolchain)

**Comment by RizwanFazal** [comment]
> [Precompiled ct-ng toolchains (using docker)](https://github.com/tttapa/docker-arm-cross-toolchain)

Can I use these Pre-compiled tool-chains to build U-boot boot-loader, the Linux kernel and the Root Filesystem sources? Actually I'm building the system from scratch and will prepare all the necessary software components that I mentioned above to boot the kernel and mount the root filesystem. Thank you for your kind support.

**Comment by QBos07** [comment]
[ARM GNU Toolchain](https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads) (one of the `aarch64-none-elf` versions)
with option like `-march` (or `-mtune`) `=cortex-a72` (for the raspberry pi 4)

**Comment by QBos07** [comment]
shoud be `-march` not `-mcpu`

**Comment by RizwanFazal** [comment]
> shoud be `-march` not `-mcpu

While compiling the code either using 'aarch64-none-elf-gcc' or 'aarch64-none-elf-gcc -march=armv8-a' , I am getting the same problem. But, when I run the command, 'aarch64-none-elf-gcc --version', it successfully prints the version information.

Now my question is, Can we compile 'Hello World' C program using this 'aarch64-none-elf-gcc' command? because we are using a bare-metal compiler and may be it is not able to compile such user space programs. Please guide.

**Comment by RizwanFazal** [comment]
Here is the error I'm getting when I compile the code either way. 
[testProgramError.txt](https://github.com/crosstool-ng/crosstool-ng/files/14757774/testProgramError.txt)

**Comment by TommyMurphyTM1234** [comment]
> Now my question is, Can we compile 'Hello World' C program using this 'aarch64-none-elf-gcc' command? because we are using a bare-metal compiler and may be it is not able to compile such user space programs. Please guide.

What exactly do you mean by "such user space programs"?
If you want to compile Linux user space programs then you need a Linux and not a bare-metal toolchain.

**Comment by QBos07** [comment]
> Here is the error I'm getting when I compile the code either way. 
> 
> [testProgramError.txt](https://github.com/crosstool-ng/crosstool-ng/files/14757774/testProgramError.txt)
> 
> 

Yes, a bare metal compiler can't compile normal userspace programs. The error that you are getting is that the linker can't find some symbols that are usually defined by the os (it's a bit more complicated than this simplification) but since you are in a freestanding environment with bare metal you have to provide these functions by yourself.

The compiler is working your code isn't.

**Comment by TommyMurphyTM1234** [comment]
> I have a bare-metal toolchain (pre-compiled binaries) which I downloaded from the ARM website. I was trying to compile a traditional simple 'Hello World' C program and getting errors. So, that's why I was wondering if such bare-metal toolchain can compile such C programs. I am new to all this Linux tool-chain thing and don't have much idea about it, that's why asking.

I still don't know what you mean by "such C programs". But if you mean a Linux user space "hello world" program to run under Linux then - no - a bare-metal toolchain will not work for that - you need a Linux toolchain.

**Comment by RizwanFazal** [comment]
> > Here is the error I'm getting when I compile the code either way.
> > [testProgramError.txt](https://github.com/crosstool-ng/crosstool-ng/files/14757774/testProgramError.txt)
> 
> Yes, a bare metal compiler can't compile normal userspace programs. The error that you are getting is that the linker can't find some symbols that are usually defined by the os (it's a bit more complicated than this simplification) but since you are in a freestanding environment with bare metal you have to provide these functions by yourself.
> 
> The compiler is working your code isn't.

I have been trying to boot the raspberry pi 4 model B board with u-boot boot-loader. I guess the ARM GNU tool-chain, to my understanding, has successfully compiled the u-boot source code and generated the required files, including u-boot.bin image.

The u-boot.bin has file type (PCX image (image/vnd.zbrush.pcx)) and size (638.8 kB (638,848 bytes)) as per its properties. I am mentioning it for your review if it's the correct file type and size?

1. https://danmc.net/posts/raspberry-pi-4-b-u-boot/
2. https://hechao.li/2021/12/20/Boot-Raspberry-Pi-4-Using-uboot-and-Initramfs/
3. https://github.com/mhomran/u-boot-rpi3-b-plus

I have followed the above links to boot u-boot on the raspberry pi 4 but it didn't work in any case. Having copied all the required files into SD card and putting it in the RPi4 board, I couldn't get U-boot running. Need your assistance and guidance please.

**Comment by TommyMurphyTM1234** [comment]
> I have been trying to boot the raspberry pi 4 model B board with u-boot boot-loader. I guess the ARM GNU tool-chain, to my understanding, has successfully compiled the u-boot source code and generated the required files, including u-boot.bin image.
> 
> The u-boot.bin has file type (PCX image (image/vnd.zbrush.pcx)) and size (638.8 kB (638,848 bytes)) as per its properties. I am mentioning it for your review if it's the correct file type and size?
> 
> 1. https://danmc.net/posts/raspberry-pi-4-b-u-boot/
> 2. https://hechao.li/2021/12/20/Boot-Raspberry-Pi-4-Using-uboot-and-Initramfs/
> 3. https://github.com/mhomran/u-boot-rpi3-b-plus
> 
> I have followed the above links to boot u-boot on the raspberry pi 4 but it didn't work in any case. Having copied all the required files into SD card and putting it in the RPi4 board, I couldn't get U-boot running. Need your assistance and guidance please.

I'm pretty sure that this sort of stuff is covered in detail elswhere on some RPi forum and that the CT-NG Issue tracker isn't really the appropriate place to tease this stuff out?

**Comment by RizwanFazal** [comment]
> I still don't know what you mean by "such C programs". But if you mean a Linux user space "hello world" program to run on Linux then - no - a bare-metal toolchain will not work for that - you need a Linux toolchain. If you compile a "hello world" program with a bare-metal toolchain (to run on a bare-metal or lightweight [RT]OS system) then you will most likely need a suitable BSP (Board Support Package), HAL (Hardware Abstraction Layer) or other middleware that provides the necessary system call and library support to make stuff like `printf()` work appropriately. You should probably do some more research/reading about the differences between Linux and bare-metal environments and toolchains in order to undestand this stuff better.

Dear Tommy,

I am grateful for your prompt response. Yes I need to do some more research on those areas which you stated in your reply. Kindly share with me the links and Book titles suitable in this regard as per your experience. I have been programming Micro-Controllers in C/C++ languages and used the suitable compilers to run code on the bare metal hardware, you know what I mean. But, this time, I am dealing with Linux systems and therefore not very much confident about it's related matters. Looking forward for your kind support and cooperation. Thank you.

**Comment by RizwanFazal** [comment]
> I'm pretty sure that this sort of stuff is covered in detail elswhere on some RPi forum and that the CT-NG Issue tracker isn't really the appropriate place to tease this stuff out?

Yes, you are right. I will put it on RPi forum which is of course an appropriate place for guidance.
