### ISSUE TITLE
CT_Error function does not exist

### ISSUE THREAD

**Issue by Jappie3** [crosstool-ng/crosstool-ng#2141]
`scripts/functions` has a function call `CT_Error` on line 2506:

```bash
# Finally, load paths.sh. For --enable-local build, it is located in
# the current directory (CT_TOP_DIR) while the rest of the scripts are
# in the source directory (CT_LIB_DIR). For other setups, paths.sh
# is in CT_LIB_DIR.
if [ -r "${CT_LIB_DIR}/paths.sh" ]; then
    paths_sh_location="${CT_LIB_DIR}/paths.sh"
elif [ -r "${CT_TOP_DIR}/paths.sh" ]; then
    paths_sh_location="${CT_TOP_DIR}/paths.sh"
else
    CT_Error "Not found: paths.sh" # <----- here
fi
. "${paths_sh_location}"
```

However, that function is not declared anywhere - as far as I can see - and it's only used in that one place. The error only triggers when `paths.sh` does not exist, maybe that's why it flew under the radar for so long.

```bash
$> rg CT_Error
scripts/functions
2506:    CT_Error "Not found: paths.sh"
```

I'll be honest, I don't know much about the crosstool-ng internals and just stumbled upon this while experimenting with Zephyr (which uses crosstool-ng), so I could be missing something here.

**Comment by cpackham** [comment]
Should probably be `CT_Abort`
