### ISSUE TITLE
printf: write error: No space left on device

### ISSUE THREAD

**Issue by Ming-Y-ANG** [crosstool-ng/crosstool-ng#2142]
I encountered the following error when compiling(build at ubuntu18.04)：
![image](https://github.com/crosstool-ng/crosstool-ng/assets/48575506/b4da2285-ea4e-4eaa-be9e-44df9c51fd2c)

- Report crosstool-NG version 
crosstool-ng-1.26.0
- Attach `.config` (unless the issue is not related to any configuration)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/15026838/config.txt)

- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build_log.zip](https://github.com/crosstool-ng/crosstool-ng/files/15026857/build_log.zip)

**Comment by Ming-Y-ANG** [comment]
The problem is caused by insufficient disk space

**Comment by QBos07** [comment]
if you solved it yourself (looks like it) please close the issue
