### ISSUE TITLE
how to get rid of the full tuple so foo-bar-g++ becomes g++?

### ISSUE THREAD

**Issue by maveric2** [crosstool-ng/crosstool-ng#2162]
By default the GNU binaries have a prefix like arm-linaro-linux-gnueabihf-g++. Is there a way to remove this prefix so the compiler executable is named **g++**?
Or is there an option that links are created so that **g++** is a link to **arm-linaro-linux-gnueabihf-g++**?

Thanks for your support!

**Comment by cpackham** [comment]
Short answer is you don't.

The whole point of crosstool-ng is to produce a toolchain that generates
executables for a CPU architecture other than the one you are running on.

In most cases you probably already have a native toolchain that supplies
g++ and you certainly don't want to replace that with one that produces
executables that won't run.

When you actually do want to produce a cross built application you do so by
telling your build system to use the cross compiler e.g.

./configure --target=arm-linaro-linux-gnueabihf

Or

make CC=arm-linaro-linux-gnueabihf-gcc

Other build systems have similar mechanisms for specifying the compiler to
use.

**Comment by QBos07** [comment]
SED conversions should be able to take work of that but they f you wish so you can just do it by hand in a shell

**Comment by maveric2** [comment]
Thanks for your suggestions. As far as I could see the provided SED command field within the menuconfig does not allow to replace the '-' before the e.g. gcc, so this does not help. 
However I've used a bash script which does the job well and creates for each binary a link (ln -s arm-linaro-linux-gnueabihf-gcc gcc).
Thanks again...
