### ISSUE TITLE
Lates release key has expired

### ISSUE THREAD

**Issue by bertulli** [crosstool-ng/crosstool-ng#2166]
crosstool-NG version: `1.26.0`

Hi, thanks for your work. just a minor thing (I omit the various build information because it is cross-version): on the[ website documentation](https://crosstool-ng.github.io/docs/install/) it is said that

> Starting with 1.25.0, releases are signature with Chris Packham’s PGP key. The fingerprint is:
> `721B 0FB1 CDC8 318A EBB8  88B8 09F6 DD5F 1F30 EF2E`

but I just downloaded the latest release (1.26.0, as showed in the [Download page](https://crosstool-ng.github.io/download/)), and **the key is expired**:
```
$ gpg --keyserver pgp.surfnet.nl --recv-keys 721B0FB1CDC8318AEBB888B809F6DD5F1F30EF2E
gpg: key 09F6DD5F1F30EF2E: public key "Chris Packham <judge.packham@gmail.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1

$ gpg --verify crosstool-ng-1.26.0.tar.bz2.sig
gpg: assuming signed data in 'crosstool-ng-1.26.0.tar.bz2'
gpg: Signature made Sun Sep 24 04:32:54 2023 CEST
gpg:                using RSA key 721B0FB1CDC8318AEBB888B809F6DD5F1F30EF2E
gpg: Good signature from "Chris Packham <judge.packham@gmail.com>" [expired]
gpg: Note: This key has expired!
```

**Comment by cpackham** [comment]
Ah right. I'll look to get that sorted.

**Comment by cpackham** [comment]
Should be sorted now
