### ISSUE TITLE
Two pass gcc build

### ISSUE THREAD

**Issue by bhundven** [crosstool-ng/crosstool-ng#217]
To simplify the crosstool-ng build process, move from building gcc three times to two times.
This issue is opened to track the progress of this change.

**Comment by bhundven** [comment]
This is going to be delayed until 1.24

**Comment by bhundven** [comment]
@stilor Are you still planning to work on two pass builds? If not, lets close this.

**Comment by stilor** [comment]
Maybe eventually, so let's keep it open as a wishlist item. Not the highest priority though.

**Comment by patrakov** [comment]
Documentation (http://crosstool-ng.github.io/docs/toolchain-construction/) also needs to be changed. In fact, it gives misleading motivation for the three-pass build, so it would be nice to fix it even if the two-pass build is not implemented in the actual script.

**Comment by cpackham** [comment]
#808 duplicates this
