### ISSUE TITLE
Fix picolibc's .specs files for portability

### ISSUE THREAD

**Issue by mrv96** [crosstool-ng/crosstool-ng#2171]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
    - 1.26.0
- Report host OS and its version
    - Ubuntu 18.04
- Attach `.config` (unless the issue is not related to any configuration)
    - :x: 
- Attach `build.log` (unless crosstool-NG fails before the build starts)
    - :x: 

It would be great if https://github.com/crosstool-ng/crosstool-ng/commit/89273b59af94fa1a40991762c780f668a7f032ec#diff-e8617de7f25b204d36f49a3ddd5fad51da05aaf4737789b517bcf5bbca59450b can be done also for picolibc.

I do not open a PR because I'm not familiar with ct-ng from development side. I currently fix picolibc's specs file using:

```bash
sed -Ei "s#$PWD/+$CT_PREFIX/*([^;}]+)#%:getenv(GCC_EXEC_PREFIX ../../\1)#g" $(find "$CT_PREFIX" -type f -name "picolibc*.specs")
```

**Comment by Lapshin** [comment]
Hi @mrv96 !

I found this issue accidentally. There is already a fix to picolibc https://github.com/picolibc/picolibc/pull/795/commits/cf914a3a79578bc97d80c3d3a0090b2fab0eb834


You could try to upgrade picolibc or apply this patch to fix

**Comment by mrv96** [comment]
Hi, I tried to rebuild the toolchain using https://github.com/cpackham/crosstool-ng/commit/c29e30563faa81a5c88e024710a3394b332baf42, but picolibc.specs and picolibcpp.specs still contain hard-coded paths instead of using GCC_EXEC_PREFIX, hence they are still not portable.

**Comment by Lapshin** [comment]
@mrv96 , try to add picolibc configure options `-Dsysroot-install=true -Dsysroot-install-skip-checks=true`

**Comment by mrv96** [comment]
@Lapshin it works! Thank you.
