### ISSUE TITLE
Multilib support in Crosstool-NG

### ISSUE THREAD

**Issue by bhundven** [crosstool-ng/crosstool-ng#218]
This issue is open to track the progress of multilib support in Crosstool-NG.
The option for multilib support is already in config/..., but it is not supported.
#383 is the PR that will add support for multilib.

**Comment by bhundven** [comment]
@mingwandroid I've assigned this to you, but this is a group effort.
I would like to see the work going into #217 to be completed first so that the multilib support is simpler.

I would also like to see any work move to an official topic branch in the crosstool-ng tree so that we can all work on it.

**Comment by bhundven** [comment]
This ticket is now tracking #383 to completion.

**Comment by stilor** [comment]
#383 has been completed.
