### ISSUE TITLE
Add support for building components from version control

### ISSUE THREAD

**Issue by bhundven** [crosstool-ng/crosstool-ng#219]
This issue is opened to track adding support for building various components from version control.
Whether or not that is the upstream version control or a local repository is not the goal.

Currently I am looking at supporting the following version control systems:
- git
- svn
- mercurial
- bzr
- perforce
- cvs

Please update this ticket if your VCS is not listed.

**Comment by stilor** [comment]
Added. Supports CVS/SVN/Git/Mercurial; we don't have other types used by any of the packages we use - if one wants to add, say, perforce for use in private repo - PRs welcome.
