### ISSUE TITLE
Help with oldest supported ABI

### ISSUE THREAD

**Issue by Phreakyx** [crosstool-ng/crosstool-ng#2190]
Version: crosstool-NG master branch
Host OS and its version: Ubuntu 20.04 64 bit

Hello, I know that this is a strange case but I have an arm embedded device onto which I can upload apps using a statically linked stdc++ library using gcc 8.3.0. I need to upgrade the gcc toolchain to something newer and tried to compile using the option oldest supported ABI setting it to 2.15 as this is what is on the device but even with this option set when I build the app I can see that it is looking for 2.17 at its oldest. I guess that this has to do with the fact that these versions were removed from the packages for glibc but I really need a way to add support for this version. Not sure how I can make it work but since it was available in the older versions I am willing to make a custom build if needed just so I can add support to my toolchain for this.

Thank you in advance and sorry for any inconvenience.

**Comment by cpackham** [comment]
You could add glibc-2.15 back (you can probably find the commit that removed it and revert parts of that). But really what I usually suggest in these cases is to link your program statically then you can use the latest compiler/libc without issue.

**Comment by Phreakyx** [comment]
I have tried linking statically but I have a lot of issues with libc as a lot of dynamic libraries require a dynamic libc and it is becoming too much of a pain to deal with as well as the device has low flash memory so it would be better if I could dynamically link to its own system libraries that are already there. 

I found the last commit before the libraries get removed and checked out there. I am trying to build gcc 10.3 for a start but when I get to build the C library I get an error on the Install phase which is really odd. This has happened with other versions of glibc as well for example 2.23 gets the same error:

`[ALL  ]      mkdir /home/aleks/x-tools/HOST-x86_64-w64-mingw32/arm-none-linux-gnueabi/arm-none-linux-gnueabi/sysroot/usr/share/info
[ALL  ]      texi2any (XS parser): bug: parent hv not already set
[ALL  ]      
[ALL  ]      /home/aleks/Downloads/crosstool-ng-68088f65c66790c1a5920e67e7e34d9f77e5a20f/.build/HOST-x86_64-w64-mingw32/arm-none-linux-gnueabi/buildtools/bin/makeinfo: line 2: 2854879 
Aborted                 (core dumped) /usr/bin/makeinfo --force "${@}"
[ALL  ]      for file in libc.info*; do   /home/aleks/Downloads/crosstool-ng-68088f65c66790c1a5920e67e7e34d9f77e5a20f/.build/tools/bin/install -c -m 644 $file /home/aleks/x-tools/HOST-
x86_64-w64-mingw32/arm-none-linux-gnueabi/arm-none-linux-gnueabi/sysroot/usr/share/info/$file; done
[ALL  ]      /usr/bin/install: cannot stat 'libc.info*': No such file or directory
[ERROR]      make[3]: *** [Makefile:200: /home/aleks/x-tools/HOST-x86_64-w64-mingw32/arm-none-linux-gnueabi/arm-none-linux-gnueabi/sysroot/usr/share/info/libc.info] Error 1
`

Have you encountered this before and is there a fix for it?
What if I try to build a newer version but use oldest supported abi to 2.15 on this checked out version where glibc2.15 is present? 

Thanks again for the help.

**Comment by Phreakyx** [comment]
Here is my full build log https://drive.google.com/file/d/1YZqYPa5EQYDq6qtxFjGe-I66QSxFV_rc/view?usp=sharing
also the commit I checked out was this one: 68088f65c66790c1a5920e67e7e34d9f77e5a20f

**Comment by Phreakyx** [comment]
I managed to fix my issue somewhat. For information to anyone looking at this as well GCC 13 and newer support a minimum version of Glibc 2.17 and will not go lower than that. I even managed to build 13.3 using glibc 2.15 but it still did not work when loading the app in a glibc 2.15 device and crashed. So GCC 12.4 was my best bet on this.

What I did was download crosstool-ng 1.24 https://github.com/crosstool-ng/crosstool-ng/commit/68088f65c66790c1a5920e67e7e34d9f77e5a20f which still has all the old glibc versions(Not sure I need them).
Migrated the GCC versions from the main branch so that I get a choice of newer GCC versions.
Selected GCC 12.4, selected glibc 2.23, selected oldest supported ABI 2.15. Selected gdb 8.3.1.
Built using canadian cross since I need to build on windows for arm.
Now I have GCC 12.4 with glibc 2.23 which backwards supports devices with 2.15.
Works awesome.

**Comment by ErikTempelaarVO** [comment]
Found this issue because of the same error with texi2any and with the same goal as OP; a recent GCC with an older glibc.
Tried GCC 12.4 but that didn't help me.

Looked into the error message and found this:
https://lists.gnu.org/archive/html/bug-texinfo/2024-05/msg00000.html

Tried upgrading the texinfo package on my distro. With that the multilib step completes just fine.
