### ISSUE TITLE
GCC 12 error: undefined reference to ZSTD_*

### ISSUE THREAD

**Issue by tttapa** [crosstool-ng/crosstool-ng#2198]
When trying to build GCC 12, the _Installing core C gcc compiler_ step consistently fails with linker errors referencing libzstd functions:

```sh
x86_64-build_pc-linux-gnu-g++ -no-pie   -O2 -g -I/home/develop/.build/aarch64-unknown-linux-gnu/buildtools/include      -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE   -fno-exceptions -fno-rtti -fasynchronous-unwind-tables -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wmissing-format-attribute -Woverloaded-virtual -pedantic -Wno-long-long -Wno-variadic-macros -Wno-overlength-strings   -DHAVE_CONFIG_H -static-libstdc++ -static-libgcc -L/home/develop/.build/aarch64-unknown-linux-gnu/buildtools/lib   -o cc1 c/c-lang.o c-family/stub-objc.o attribs.o c/c-errors.o c/c-decl.o c/c-typeck.o c/c-convert.o c/c-aux-info.o c/c-objc-common.o c/c-parser.o c/c-fold.o c/gimple-parser.o c-family/c-common.o c-family/c-cppbuiltin.o c-family/c-dump.o c-family/c-format.o c-family/c-gimplify.o c-family/c-indentation.o c-family/c-lex.o c-family/c-omp.o c-family/c-opts.o c-family/c-pch.o c-family/c-ppoutput.o c-family/c-pragma.o c-family/c-pretty-print.o c-family/c-semantics.o c-family/c-ada-spec.o c-family/c-ubsan.o c-family/known-headers.o c-family/c-attribs.o c-family/c-warn.o c-family/c-spellcheck.o aarch64-c.o glibc-c.o   cc1-checksum.o libbackend.a main.o libcommon-target.a libcommon.a ../libcpp/libcpp.a ../libdecnumber/libdecnumber.a libcommon.a ../libcpp/libcpp.a   ../libbacktrace/.libs/libbacktrace.a ../libiberty/libiberty.a ../libdecnumber/libdecnumber.a  -L/home/develop/.build/aarch64-unknown-linux-gnu/buildtools/lib -lisl -L/home/develop/.build/aarch64-unknown-linux-gnu/buildtools/lib -L/home/develop/.build/aarch64-unknown-linux-gnu/buildtools/lib -L/home/develop/.build/aarch64-unknown-linux-gnu/buildtools/lib -lmpc -lmpfr -lgmp -rdynamic -ldl  -L./../zlib -lz 
lto-compress.o: In function `lto_compression_zstd':
/home/develop/.build/aarch64-unknown-linux-gnu/src/gcc/gcc/lto-compress.cc:135: undefined reference to `ZSTD_compressBound'
lto-compress.o: In function `lto_normalized_zstd_level':
/home/develop/.build/aarch64-unknown-linux-gnu/src/gcc/gcc/lto-compress.cc:120: undefined reference to `ZSTD_maxCLevel'
lto-compress.o: In function `lto_compression_zstd':
/home/develop/.build/aarch64-unknown-linux-gnu/src/gcc/gcc/lto-compress.cc:139: undefined reference to `ZSTD_compress'
[...]
```

The problem can be reproduced using the following very basic defconfig and Dockerfile:

**defconfig**
```sh
CT_CONFIG_VERSION="4"
# CT_LOG_PROGRESS_BAR is not set
CT_ARCH_ARM=y
CT_ARCH_CPU="cortex-m0plus"
CT_ARCH_ARM_MODE_THUMB=y
CT_GCC_V_12=y
```
**Dockerfile**
```Dockerfile
FROM ubuntu:bionic

# Install dependencies to build crosstool-ng and the toolchain
RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update -y && apt-get install -y \
        autoconf automake libtool-bin make texinfo help2man sudo file gawk patch g++ bison flex gperf libncurses5-dev python3-dev perl libthread-queue-perl ca-certificates wget git bzip2 xz-utils unzip rsync && \
    apt-get clean autoclean && apt-get autoremove -y && rm -rf /var/lib/apt/lists/*

# Build crosstool-ng
RUN git clone -b master --single-branch --depth 1 https://github.com/crosstool-ng/crosstool-ng.git
RUN cd crosstool-ng && \
    git show --summary && \
    ./bootstrap && \
    mkdir build && cd build && \
    ../configure --prefix=/usr/local && \
    make -j$(($(nproc) * 2)) && \
    make install && \
    cd .. && rm -rf build

# Add a user called `develop` and add them to the sudo group
RUN useradd -m develop && echo "develop:develop" | chpasswd && usermod -aG sudo develop
USER develop
WORKDIR /home/develop

# Build the toolchain
COPY --chown=develop:develop defconfig defconfig
RUN ct-ng defconfig
RUN ct-ng build || { cat build.log && false; } && rm -rf .build
```
(Place these two files in the same folder somewhere, and run `docker buildx build .` to reproduce.)

- crosstool-NG version: 901722d34b4eff6867a0c82ff375d7a27dce6a2b
- host OS: Ubuntu 18.04, x86-64
- [**.config**](https://github.com/user-attachments/files/16841259/config.txt)
- [**build.log**](https://github.com/user-attachments/files/16841558/build.log)

---

A sub-optimal work-around is to set `CT_CC_GCC_LTO_ZSTD=n`. This works for
normal builds, but not for Canadian builds, because there the intermediate
`build=CT_BUILD,host=CT_BUILD,target=CT_TARGET` compiler fails to link, and the
`CC_GCC_LTO_ZSTD` option does not affect this compiler, it only affects the
final `build=CT_BUILD,host=CT_HOST,target=CT_TARGET` compiler.

I've tried some other configs as well, which also fail, e.g.
```sh
CT_CONFIG_VERSION="4"
# CT_LOG_PROGRESS_BAR is not set
CT_ARCH_ARM=y
CT_ARCH_CPU="cortex-a53+crc+simd"
CT_ARCH_64=y
CT_TARGET_VENDOR="rpi3"
CT_KERNEL_LINUX=y
CT_GCC_V_12=y
```

**Comment by tttapa** [comment]
After some debugging, the issue seems to be that the `libzstd.a` library built by crosstool-NG requires pthreads. However, when checking if `-lzstd` works, GCC's configure script does not link against `-pthread`, resulting in the test failing, and hence `-lzstd` is not included in the GCC build flags.

```sh
configure:10608: x86_64-build_pc-linux-gnu-g++ -o conftest -g -I/home/develop/.build/arm-unknown-eabi/buildtools/include         -static-libstdc++ -static-libgcc -L/home/develop/.build/arm-unknown-eabi/buildtools/lib    conftest.cpp -lzstd   >&5
/home/develop/.build/arm-unknown-eabi/buildtools/lib/libzstd.a(pool.o): In function `POOL_join':
/home/develop/.build/src/zstd-1.5.6/lib//common/pool.c:176: undefined reference to `pthread_join'
/home/develop/.build/arm-unknown-eabi/buildtools/lib/libzstd.a(pool.o): In function `POOL_create_advanced':
/home/develop/.build/src/zstd-1.5.6/lib//common/pool.c:151: undefined reference to `pthread_create'
/home/develop/.build/arm-unknown-eabi/buildtools/lib/libzstd.a(pool.o): In function `POOL_resize_internal':
/home/develop/.build/src/zstd-1.5.6/lib//common/pool.c:232: undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
```
Versions of GCC after https://github.com/gcc-mirror/gcc/commit/b0248580b68d970788bb43ac3ab8fe3e21ef71be do not simply drop the `-lzstd` flag if this happens, but disable zstd support altogether, which is why the linker errors do not occur for more recent GCC versions. However, if I understand correctly, the resulting binaries are still “wrong” in the sense that they do not support zstd, even though zstd support was requested in the crosstool-NG config.

What would be the best place to address this issue? Should GCC's `configure.ac` be patched to include `-pthread`?
```patch
diff --git a/gcc/configure.ac b/gcc/configure.ac
index fec897c2c..5a043ba6e 100644
--- a/gcc/configure.ac
+++ b/gcc/configure.ac
@@ -1530,7 +1530,7 @@ fi
 # LTO can use zstd compression algorithm
 save_LIBS="$LIBS"
 LIBS=
-AC_SEARCH_LIBS(ZSTD_compress, zstd)
+AC_SEARCH_LIBS([ZSTD_compress], [zstd], [], [], [-pthread])
 ZSTD_LIB="$LIBS"
 LIBS="$save_LIBS"
 AC_SUBST(ZSTD_LIB)
 ```
Or should crosstool-NG perhaps forcibly set `ac_cv_search_ZSTD_compress=-lzstd`?

**Comment by QBos07** [comment]
Upstream should be the way to go here. Autocofigure errors sadly are not an anomaly here

**Comment by QBos07** [comment]
We can carry patches until they are upstream. If you need it now you can set extra configure args like you outlined.

IMO: The configure patch look's good

**Comment by tttapa** [comment]
The patch above is purely theoretical at the moment, I need to find some time to actually try it out.

**Comment by tttapa** [comment]
Just did some limited testing, and the following patch seems to fix the GCC build error:
```patch
diff --git a/gcc/configure b/gcc/configure
index f697874f2..634949de9 100755
--- a/gcc/configure
+++ b/gcc/configure
@@ -10603,7 +10603,7 @@ for ac_lib in '' zstd; do
     ac_res="none required"
   else
     ac_res=-l$ac_lib
-    LIBS="-l$ac_lib  $ac_func_search_save_LIBS"
+    LIBS="-l$ac_lib -pthread $ac_func_search_save_LIBS"
   fi
   if ac_fn_cxx_try_link "$LINENO"; then :
   ac_cv_search_ZSTD_compress=$ac_res
@@ -10630,7 +10630,7 @@ if test "$ac_res" != no; then :
 
 fi
 
-ZSTD_LIB="$LIBS"
+ZSTD_LIB="$LIBS -pthread"
 LIBS="$save_LIBS"
 
 fi
diff --git a/gcc/configure.ac b/gcc/configure.ac
index fec897c2c..bca80533e 100644
--- a/gcc/configure.ac
+++ b/gcc/configure.ac
@@ -1530,8 +1530,8 @@ fi
 # LTO can use zstd compression algorithm
 save_LIBS="$LIBS"
 LIBS=
-AC_SEARCH_LIBS(ZSTD_compress, zstd)
-ZSTD_LIB="$LIBS"
+AC_SEARCH_LIBS(ZSTD_compress, zstd,,, -pthread)
+ZSTD_LIB="$LIBS -pthread"
 LIBS="$save_LIBS"
 AC_SUBST(ZSTD_LIB)
 fi
```
I'll need to do something similar for newer GCC versions.

If built by crosstool-NG, `libzstd.a` will always be multi-threaded, so adding `-pthread` to `$ZSTD_LIB` unconditionally is fine, however, I'm not sure about the possible side effects of adding `-pthread` unnecessarily (when we upstream this patch). Is there a standard autotools pattern for something like this?

**Comment by QBos07** [comment]
[From the docs](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Libraries.html#Libraries): you can use other libraries for this

**Comment by cpackham** [comment]
Maybe for the sake of portability we should build the `nomt` zstd library.

**Comment by tttapa** [comment]
> [From the docs](https://www.gnu.org/software/autoconf/manual/autoconf-2.69/html_node/Libraries.html#Libraries): you can use other libraries for this

I'm already using _other-libraries_ in the patch above, but the problem is that it's unconditional (are there platforms where blindly adding `-pthread` to the flags might actually break the build?), and that it doesn't automatically add it to `$LIBS`.

I've experimented with a conditional approach: try `AC_SEARCH_LIBS` without `-pthread` first, and if that doesn't work, try again with `-pthread`, but this gets messy, because the cache variable only depends on the symbol name, and we would be searching for the same symbol twice in this approach.

**Comment by QBos07** [comment]
Welcome to autotools!

**Comment by Guanhuai04** [comment]
Perhaps it's problem with USE_SYSTEM_CURL option, I solved the problem by setting USE_SYSTEM_CURL to ON in CMakeLists.txt.
