### ISSUE TITLE
How can I build 1.26.0 for xtensa-esp32-elf?

### ISSUE THREAD

**Issue by leres** [crosstool-ng/crosstool-ng#2206]
I've been using crosstool-ng under FreeBSD for a number of years. When I built 1.22.0.g20200907 I used the crosstool.config in samples/xtensa-esp32-elf. Now I'm trying to build 1.26.0 but do not find the corresponding crosstool.config file. (I do see configs for xtensa-fsf-elf and xtensa-fsf-linux-uclibc but I'm not sure if they are right for my application.)

I downloaded [esp-13.2.0_20240530/xtensa-esp-elf-13.2.0_20240530-x86_64-linux-gnu.tar.xz](https://github.com/espressif/crosstool-NG/releases/download/esp-13.2.0_20240530/xtensa-esp-elf-13.2.0_20240530-x86_64-linux-gnu.tar.xz) on a test ubuntu system and see that it has the desired binaries, e.g. xtensa-esp32-elf-gcc-13.2.0. This shows me there must exist a crosstool.config for building the xtensa-esp32-elf toolchain.

How do I find the correct crosstool.config to build 1.26.0?

**Comment by QBos07** [comment]
There is a separate fork from extensia iirc for esps.

**Comment by leres** [comment]
> There is a separate fork from extensia iirc for esps.

Ha-ha, silly of me to end up here. But thanks for pointing me in the right direction!
