### ISSUE TITLE
Default 'arm-none-eabi' leads to fatal error while building picolibc's libstdc++

### ISSUE THREAD

**Issue by gaspacio** [crosstool-ng/crosstool-ng#2214]
I apologize in advance if any of the following information may appear as non-sense.

I can't complete the build of an arm-none-eabi toolchain because of an error that appears while installing picolibc. I also apparently can't change the version of picolibc from 1.8.8 nor disable its build entirely (through menuconfig).

Running ct-ng built from source from latest commit on master: https://github.com/crosstool-ng/crosstool-ng/commit/4d36f2700f183a8e768b453bbea94f726449fd20
Using default arm-none-eabi configuration (no edits):
[config.txt](https://github.com/user-attachments/files/17327386/config.txt)

```
# ct-ng --version
GNU Make 4.3
Built for x86_64-pc-linux-gnu
...
# uname -a
Linux c67d7efbe7c7 5.15.0-122-generic #132~20.04.1-Ubuntu SMP Fri Aug 30 15:50:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```
The environment is a Docker container deriving from ubuntu:22.04

My build.log appears to be too large for GitHub (~250MB), so I will only attach the error message (I'm willing to upload it using some other hosting service upon request):

[build_error.log](https://github.com/user-attachments/files/17327483/build_error.log)

**Comment by QBos07** [comment]
[config.txt](https://github.com/user-attachments/files/17333875/config.txt)
Here is a config without picolibc. I dont know what happend but the config wasn't correctly versioned aswell.

**Comment by gaspacio** [comment]
Thank you! I've completed the build and it appears to work. Am I supposed to create some sort of fix or can I close the issue already?

**Comment by QBos07** [comment]
Just close it. Probably won't happen again
