### ISSUE TITLE
Only support latest gcc releases

### ISSUE THREAD

**Issue by bhundven** [crosstool-ng/crosstool-ng#222]
Starting with crosstool-NG-1.23.0, we will only support the latest supported releases of gcc.
For example:

* 4.8.5
* 4.9.3
* 5.2.0

Just as you would find by going to https://gcc.gnu.org

If you really need an older version of gcc, I have nothing against supporting older releases of crosstool-ng that have your compiler version in it. When you open a pull request, just make sure you change the target branch to the correct version of crosstool-ng, and not use master. When that branch functions the way you expect, I will push a branch release (say: 1.20.1).

In the mean time, in 1.22.0 milestone timeline, I will be removing older releases of gcc (I.E. 4.9.0, 4.8.1) and only support the latest of each minor version (I.E. 4.6.4, 4.7.4, 4.8.5, etc..).

This issue is here to track the progress of these changes.

**Comment by bhundven** [comment]
#232 has been merged, which now limits the number of gcc releases in crosstool-ng to the target for 1.22.0.

**Comment by pfalcon** [comment]
From #241:

> Also, as per #222, I am soon to drop older gcc releases (as well as other components, like uclibc, glibc, gdb, binutils, etc...).

My concern here is dropping support for libc versions. The problem is that different versions of libc's are not compatible. This in particularly true for uClibc, which manages to break binary compatibility between micro releases (each of which is spaced few years apart, yeah). Supposed I want to build a cross-toolchain for uClibc 0.9.28, what are my options?

**Comment by bhundven** [comment]
Get the 1.21 branch, and use it. If you have problems with the 1.21 branch, open a bug and we'll fix the problems, but no new features will come to 1.21. Only stability fixes. Same with older branches of crosstool-ng.

At some point I have to stop supporting older ancient releases. It is making the code unmanageable. So there aren't many options, but that is your option.

**Comment by pfalcon** [comment]
Well, that doesn't sound too bad, thanks for reply.
