### ISSUE TITLE
Building error of newlib

### ISSUE THREAD

**Issue by neko-para** [crosstool-ng/crosstool-ng#2228]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

## Crosstool-NG version
trunk commit 558d67ec0df4bcdf495376629639ebaffd8b1fe6

## Host OS
Ubuntu 22.04.5 x86_64

## Config
[config.txt](https://github.com/user-attachments/files/17768256/config.txt)

## Build log
[build.log](https://github.com/user-attachments/files/17768422/build.log)

## Brief
When building newlib, Wreturn-mismatch triggered.
```
[INFO ]  Installing C library
[EXTRA]    Configuring C library
[EXTRA]    Building C library
[ERROR]    /home/ubuntu/data/crosstool/.build/i386-elf/src/newlib/libgloss/i386/cygmon-gmon.c:113:7: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
[ERROR]    /home/ubuntu/data/crosstool/.build/i386-elf/src/newlib/libgloss/i386/cygmon-gmon.c:121:7: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
[ERROR]    /home/ubuntu/data/crosstool/.build/i386-elf/src/newlib/libgloss/i386/cygmon-gmon.c:142:7: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
[ERROR]    /home/ubuntu/data/crosstool/.build/i386-elf/src/newlib/libgloss/i386/cygmon-gmon.c:153:5: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
[ERROR]    /home/ubuntu/data/crosstool/.build/i386-elf/src/newlib/libgloss/i386/cygmon-gmon.c:326:3: error: 'return' with no value, in function returning non-void [-Wreturn-mismatch]
```
I'm not sure if I could use some flags to omit it (e.g. -Wno-return-mismatch). I do notice the option `Extra config for newlib`, but it seems not support adding environment variable like `CFLAGS`.

**Comment by QBos07** [comment]
Newlib is not yet gcc 14 clean and needs some flags. You could add that flag to the top level target cflags.

**Comment by neko-para** [comment]
I've made it work via editting `CT_LIBC_NEWLIB_TARGET_CFLAGS` entry in `.config`, though I havn't found the menu entry fot it. 🤔
