### ISSUE TITLE
Canadian cross between Windows and Linux 

### ISSUE THREAD

**Issue by thanhtam-h** [crosstool-ng/crosstool-ng#2235]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG 1.25
- Report host OS and its version: Windows 10 64-bit

What is the proper way to build canadian cross toolchain like this:
build: x86_64-linux
host: x86_64-windows
target: x86_64-linux (same as build)
or:  x86_64-linux -> x86_64-windows-> x86_64-linux

Thank you!

**Comment by QBos07** [comment]
Build a build -> build -> host toolchain or simply install one and then make a Build -> build -> target toolchain. Both for the last one.

**Comment by thanhtam-h** [comment]
Thanks, I found that the easiest way to do it build on Windows with Cygwin.

**Comment by QBos07** [comment]
May I present Msys2 to you? Or for what you want to archive WSL would be perfect.
