### ISSUE TITLE
Failed to build libgomp for target i686-w64-mingw32 - missing pthreads

### ISSUE THREAD

**Issue by AstralStorm** [crosstool-ng/crosstool-ng#227]
Building libgomp support for gcc fails in the final stage in the configure due to missing pthreads, e.g. pthreads-win32.

Host is x86_64-pc-linux-gnu.

Short snippet:
[ERROR]    checking for feholdexcept in -lm... configure: error: Pthreads are required to build libgomp
[ERROR]    gmake[2]: *** [configure-target-libgomp] Error 1
[ERROR]    gmake[1]: *** [all] Error 2

I can attach config.log, but it just mentions missing pthread.h.

**Comment by mingwandroid** [comment]
We should build and use winpthreads since that's part of mingw-w64.

**Comment by bhundven** [comment]
@mingwandroid is that something that is done in the local environment, or in ct-ng?

**Comment by mingwandroid** [comment]
This should be fixed now. I will wait until the 1.22 release to close.

**Comment by mingwandroid** [comment]
Ensure you are using the latest version mingw-w64 and re-open if this is still an issue.
