### ISSUE TITLE
newlib libgloss fails to build with arm eabihf suffix

### ISSUE THREAD

**Issue by ius** [crosstool-ng/crosstool-ng#23]
Building an armeabi target with newlib and the -hf tuple suffix fails to configure newlib due to `objtype` not being set.

I don't know the right approach to resolve this, though something like the patch below might work (does require autoconf to be run).

````diff
diff -ur newlib-1.20.0.orig/libgloss/arm/configure.in newlib-1.20.0/libgloss/arm/configure.in
--- newlib-1.20.0.orig/libgloss/arm/configure.in	2006-05-10 22:51:40.000000000 +0200
+++ newlib-1.20.0/libgloss/arm/configure.in	2015-01-04 15:27:41.471549917 +0100
@@ -49,7 +49,7 @@
 LIB_AM_PROG_AS
 
 case "${target}" in
-  *-*-elf | *-*-eabi)
+  *-*-elf | *-*-eabi*)
 	objtype=elf-
 	;;
   *-*-coff)
````

**Comment by bhundven** [comment]
I have a patch in the queue somewhere that does exactly this. I'll double check and get back to this. Thanks!

**Comment by bhundven** [comment]
@ius Strange. I looked at the mailing list, patchwork, and history in github and swear I have seen this exact change. Oh well. Would you mind forking crosstool-ng, create a branch ```git checkout -b newlib-1_20_0-eabihf_suffix master```, apply the change and rerun autoconf to make a minimal diff of the configure script to enable this same suffix check, commit ```git commit -s```, ```git push <your_remote>```, and open a pull request. In the change put ```closes #<num>``` where that number is 23 as in this bug number, so the change closes this bug.

I'll review the change by cloning your branch and test the change. So it would probably also be helpful to attach a gist of the .config you use to reproduce the issue.
