### ISSUE TITLE
Canadian Cross Host=MinGW "configure: error: expat is missing or unusable"

### ISSUE THREAD

**Issue by jasmin-j** [crosstool-ng/crosstool-ng#231]
I am building  an arm-none-eabi canadian cross for MinGW.
The configure check for expat.h (-lexpat) fails.

Here is the config.log output:
```
configure:8813: x86_64-host_w64-mingw32-gcc -o conftest.exe -g -O2 -D__USE_MINGW_ACCESS  -static-libstdc++ -static-libgcc -Wl,--    stack,12582912 conftest.c -lm  -lexpat >&5
conftest.c:45:19: fatal error: expat.h: No such file or directory
```

I have installed the libexpat1-dev package and there is an expat.h file available on my system (/usr/include). But x86_64-host_w64-mingw32-gcc (x86_64-w64-mingw32-gcc) does not search in the standard file locations, I guess.
/usr/bin/x86_64-w64-mingw32-cpp -v prints:

```
#include "..." search starts here:
#include <...> search starts here:
 /usr/lib/gcc/x86_64-w64-mingw32/4.8/include
 /usr/lib/gcc/x86_64-w64-mingw32/4.8/include-fixed
 /usr/lib/gcc/x86_64-w64-mingw32/4.8/../../../../x86_64-w64-mingw32/include
End of search list.
```

Can someone point me to the MinGW package I need to install?
Or shall I modify 300-gdb.sh to compile it from source in case of canadian cross?

And I guess the same problem will occur later with the python libraries. I could omit this by disabling python support, but it would be nice to have it for the Windows version of the arm-none-eabi compiler, too.

BR
Jasmin

**Comment by bhundven** [comment]
@jasmin-j See the comments in #225.
The plan currently is to promote libexpat and ncurses to companion-tools. @stilor is currently working on this.

**Comment by jasmin-j** [comment]
> The plan currently is to promote libexpat and ncurses to companion-tools.

Ok, than I will disable this in the meantime.

**Comment by bhundven** [comment]
@mingwandroid I'm not sure about the mingw expat and python development stuff. Can you provide some insight here?

**Comment by mingwandroid** [comment]
Ah I didn't realise someone else was also promoting expat to companion lib status! I wonder if I should stop doing that and just wait? Is there an ETA? I think I will push my cygwin mingw-w64 linux canadian work with gdb disabled for now then?

Python on mingw-w64 is a sorry tale from an upstream, out of the box perspective, but I've hacked on it for years already, most recently on MSYS2 so we can do something with it. One thing I'd like to see beforehand is host/target specific patches as our python patch series is quite extensive and I'd sleep easier if they weren't applied on anything other than mingw-w64.

**Comment by bhundven** [comment]
@mingwandroid I think @stilor is getting close to expat/ncurses promotion, so I would probably focus on mingw/cygwin issues.

**Comment by mingwandroid** [comment]
Sure thing.

**Comment by mingwandroid** [comment]
This should be fixed now. I will wait until the 1.22 release to close.

**Comment by mingwandroid** [comment]
I wanted to assign this to @stilor but it wasn't possible?

**Comment by bhundven** [comment]
@mingwandroid He's not an "official contributor"

**Comment by bhundven** [comment]
@jasmin-j Try the latest master, and let me know if that helps. I'm looking to release 1.22, and need feedback if this works properly.

**Comment by jasmin-j** [comment]
> Try the latest master, and let me know if that helps. I'm looking to release 1.22, and need
> feedback if this works properly.

[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[EXTRA]    Installing cross-gdb
[EXTRA]    Installing '.gdbinit' template
[INFO ]  Installing cross-gdb: done in 153.96s (at 02:56)

THX for fixing!

**Comment by bhundven** [comment]
@stilor Thanks for your work on this!
