### ISSUE TITLE
Fails to build with ncurses when libtinfo is separate; needs to use pkg-config

### ISSUE THREAD

**Issue by marcan** [crosstool-ng/crosstool-ng#241]
/usr/lib/gcc/x86_64-pc-linux-gnu/4.9.3/../../../../x86_64-pc-linux-gnu/bin/ld: lxdialog/util.o: undefined reference to symbol 'nodelay'
    /usr/lib64/libtinfow.so.6: error adding symbols: DSO missing from command line

See this Gentoo bug for some background info:
https://bugs.gentoo.org/show_bug.cgi?id=457530

crosstool-ng should use pkg-config to figure out what libraries are required for ncurses, instead of blindly looking for a given lib.

**Comment by bhundven** [comment]
@marcan I wish it were that simple.
I don't have a mac to verify if ncurses for mac os x has a pkg-config file.
Same issue with *bsd.

**Comment by marcan** [comment]
The right approach then would be to use pkg-config if it is available and fall back to the current mechanism if it isn't.

**Comment by bhundven** [comment]
Sure, So now I need to check for tinfo and ncurses?
I see that bug is not resolved. Is gentoo the only distribution that packages those two separately?

**Comment by bhundven** [comment]
archlinux only provides an AUR package, which is just a symlink from tinfo to ncurses.

**Comment by bhundven** [comment]
Also, what is the config you are using to reproduce this error?

**Comment by marcan** [comment]
I'm trying to build the esp8266 open SDK, which configures crosstool-ng like this: https://github.com/pfalcon/esp-open-sdk/blob/master/Makefile#L272

I don't know how other distros do things. On Gentoo, separate tinfo is a USE flag (user configurable), but (for some reason) having it enabled is a dependency of the NVIDIA CUDA toolkit, which is why I have it enabled.

The bug is not resolved because it's a tracker bug and not all packages with the problem have been fixed yet, but the vast majority have (see the "Depends on" list).

**Comment by bhundven** [comment]
Ok, This is the second time I've seen someone using the esp-open-sdk file a bug here.

I'm going to leave this bug open to track progress of adding a pkgconfig check for tinfo and ncurses (falling back to our normal checks, as suggested), but I have other questions for the xstensa esp-open-sdk folks below.

=========================

(WRT esp-open-sdk and xstensa support)
@pfalcon and @jcmvbkbc To further ask... I see you are using this fork: https://github.com/jcmvbkbc/crosstool-NG

Is it possible for you guys to start working with our upstream?
I'm trying to keep any crosstool-ng support issues here. I'm not keen on having to keep up with forks of this project to understand dependency issues. If we can contain support for xstensa, cuda, et al., here, then everyone profits from that support in one place.

**Comment by pfalcon** [comment]
@bhundven : Working with upstream is the reason why I suggest users who report strange issues which I can't reproduce is to report that to the main project ;-).

I also believe I asked @jcmvbkbc if he submitted xtensa-lx106 patches upstream and he answered yes, so I feel good on that side too.

What remains is that I have in my pet project what works well for me and bunch of other people. I expect that if someone has an issue, they would investigate it, and if it's e.g. fixed upstream, they would submit patch to update my pet project to this fixed. I'd love to do more on my side, but unfortunately, that keeps dangling somewhere in backlog (as an excuse, aforementioned pet project is integration of 4-5 components, including pseudo-opensource stuff from silicon vendor, so keeping track of all those pieces ain't easy even without fuzzing the crosstools-NG part).

So, @bhundven , if you have specific suggestions, I'd love to hear them. Otherwise, I treat @jcmvbkbc as my upstream (and I need to check if I need to update, yeah), and just hope he treats the main project as his and rebases from time to time.

Thanks!

**Comment by bhundven** [comment]
@pfalcon Sure!

I guess the conversation WRT xstensa support is over here: https://github.com/pfalcon/esp-open-sdk/issues/43#issuecomment-155208084

What I would see as acceptable is if patches that are applied to components of crosstool-ng (I.E.: gcc, gdb, binutils, etc...) can be applied without affecting other targets. Architecture specific changes internal to crosstool-ng are confined to scripts/build/arch/xstensa.sh and config/arch/xstensa.in*

Also, as per #222, I am soon to drop older gcc releases (as well as other components, like uclibc, glibc, gdb, binutils, etc...). So the patches applied to them should be rebased to newer releases.

**Comment by jcmvbkbc** [comment]
> maybe we start with the patches you have, and work through the review process to find compromise?

Sure.
So far we have the following patches for xtensa:
- patches to the crosstool-NG itself. Besides adding architecture bits they add hooks to do_{binutils,cc,debug_gdb}_extract functions that allow us to overwrite selected parts of binutils, gcc and gdb with processor-specific files. This is done by unpacking corresponding subtree of the configuration overlay archive. An example of such archive: https://github.com/jcmvbkbc/crosstool-NG/blob/lx106/overlays/xtensa_lx106.tar
- xtensa-specific patches backported from development trees of binutils/gcc/gdb: fixes or improvements that old toolchain components need.
- xtensa-specific patches that haven't got to any toolchain component repository: e.g. call0 ABI support patches for gcc-4.8.2 or xtensa support for newlib-2.0.0.

> What I would see as acceptable is if patches that are applied to components of crosstool-ng (I.E.: gcc, gdb, binutils, etc...) can be applied without affecting other targets.

All changes that we do to binutils, gcc and gdb in extract hook apply to xtensa-specific files only.
Here's the list of files from configuration overlay:

binutils/bfd/xtensa-modules.c
binutils/include/xtensa-config.h
gcc/include/xtensa-config.h
gdb/gdb/gdbserver/xtensa-xtregs.c
gdb/gdb/regformats/reg-xtensa.dat
gdb/gdb/xtensa-config.c
gdb/bfd/xtensa-modules.c
gdb/include/xtensa-config.h

So where do I start?

**Comment by bhundven** [comment]
Sorry to move the discussion again, but lets move to:
https://github.com/crosstool-ng/crosstool-ng/issues/243

That way when I fix the original tinfo/ncurses issue, I can close this issue.

I will add your comment to that issue.

**Comment by marcan** [comment]
Going back to the original issue, you only need a pkg-config check for ncurses. If libtinfo is needed, that will spit it out as part of its LIBS, alongside libncurses.

**Comment by bhundven** [comment]
@marcan Yup. I'm on it.

**Comment by bhundven** [comment]
Ok, so I'm ok with autoconf, but I've never used ```PKG_CHECK_MODULES```.
When we generate configure, we use ```autoconf```, not ```autoreconf```, because we don't need all of the extra aclocal/automake/blahblahblah. But I don't know how to get ```PKG_CHECK_MODULES``` to work with normal autoconf. Do I need to create an ```m4``` directory and add an autoconf module there?

**Comment by marcan** [comment]
Honestly, I have no idea. I'm rather clueless about autotools. I did a quick test myself to get it to build and did indeed need to run aclocal to make it work, but I have no idea what the right way to do it is. Autotools just baffles me in general; I'd rather use CMake myself (or plain Makefiles).

**Comment by bhundven** [comment]
@marcan Using pkg-config right now is much more complex a task then just also searching for libtinfo.
I'm guessing our configure script does find your ncurses library, right?

**Comment by marcan** [comment]
This still fails to build. It seems that kconfig/Makefile hardcodes -lncurses in the rule for nconf, instead of using NCURSES_LDFLAGS.

**Comment by bhundven** [comment]
I don't use gentoo, I use archlinux, debian, and fedora. Is tinfo a symlink to ncurses?

**Comment by marcan** [comment]
It is a separate lib if built with USE=tinfo, which causes ncurses to be configured with --with-termlib. Gentoo is a metadistribution, so multiple configurations are possible.

AFAICT the only thing that needs fixing now is that Makefile, though. LIBS correctly includes -ltinfo after your previous commit. It just isn't being used in that make rule.

**Comment by bhundven** [comment]
@marcan try: https://github.com/crosstool-ng/crosstool-ng/pull/262

**Comment by mingwandroid** [comment]
Ah good old gentoo USE flags.. Because software configuration and dependencies weren't complicated enough already ;-)

Sorry for staying off-topic.

**Comment by bhundven** [comment]
I had not heard back from @marcan. Not sure why this is closed. Or were you able to verify this on gentoo? Are you able to verify #262?

**Comment by mingwandroid** [comment]
Damn, I didn't mean to close this at all .. mobile phone failure; sorry about that. Seems we both worked on alternative solutions, you at https://github.com/bhundven/crosstool-ng/commit/6c49a232a81cf4f4f22a13b13e91af74e7edab32 and me at https://github.com/crosstool-ng/crosstool-ng/pull/266

I'd take mine (a simple reordering) but with a line from yours (the linking with $(LIBS) part), I think, but I don't mind either way.

**Comment by mingwandroid** [comment]
.. I don't run Gentoo anymore; not for 10 years.

**Comment by bhundven** [comment]
@marcan I pushed #262, please check out master and make sure that works for you.
If there is still an issue, we'll revise. I didn't realize that I broke the build with #257.

**Comment by marcan** [comment]
Sorry for the delay, just checked out master. It builds fine. I also cherry picked the two commits onto the branch with esp8266 support and that builds fine too. Thanks for fixing this!

(I see that master here has Xtensa support but apparently not exactly the variant that the esp8266 needs, or maybe it's just some unrelated confusion; either way that's a story for another time).

**Comment by bhundven** [comment]
> I see that master here has Xtensa support but apparently not exactly the variant that the esp8266
> needs, or maybe it's just some unrelated confusion; either way that's a story for another time

@jcmvbkbc added generic support for xtensa and overlay support. I'm not sure how the overlay part works, wrt esp8266. Maybe he can help us document that?

**Comment by jcmvbkbc** [comment]
> I see that master here has Xtensa support but apparently not exactly the variant that the esp8266 needs

@marcan you still need a correct overlay file. And a newlib. I think I'll add a branch xtensa-1.22.x to my tree and will merge the mainline up to 1.22.0 release there to keep it working for the existing projects and tutorials.

> I'm not sure how the overlay part works, wrt esp8266. Maybe he can help us document that?

@bhundven ok, I can write a couple of sentences, where should I put it?

**Comment by bhundven** [comment]
>>I'm not sure how the overlay part works, wrt esp8266. Maybe he can help us document that?
>@bhundven ok, I can write a couple of sentences, where should I put it?

If you could add a section to ```docs/C - Misc. tutorials.txt```.
I plan on rewriting the docs, and I'll put it in architecture specific notes.
