### ISSUE TITLE
Transient build failure while 'Building mingw-w64-crt'

### ISSUE THREAD

**Issue by stilor** [crosstool-ng/crosstool-ng#246]
I am observing the failure below, once in about 3-4 runs. Build host has 8 CPUs, so make is running with -j9:

````
[EXTRA]    Building mingw-w64-crt
[DEBUG]    ==> Executing: 'make' '-j9' '-l'
[ALL  ]    make[2]: Entering directory `/home/avn/work/ctng/crosstool-ng/.build/i686-w64-mingw32/build/build-mingw-w64-crt'
[ALL  ]    echo "static int __attribute__((unused)) __mingw_libm_dummy;" > _libm_dummy.c
[ALL  ]    /usr/bin/make  all-am
[ALL  ]    make[3]: Entering directory `/home/avn/work/ctng/crosstool-ng/.build/i686-w64-mingw32/build/build-mingw-w64-crt'
[ALL  ]    i686-w64-mingw32-gcc -E -x c /home/avn/work/ctng/crosstool-ng/.build/src/mingw-w64-v4.0.2/mingw-w64-crt/lib32/msvcrt.def.in -Wp,-w -I/home/avn/work/ctng/crosstool-ng/.build/src/mingw-w64-v4.0.2/mingw-w64-crt/def-include | /home/avn/work/ctng/crosstool-ng/.build/tools/bin/sed 's/^#/;/' >lib32/msvcrt.def
[ALL  ]    /bin/bash: lib32/msvcrt.def: No such file or directory
````

The problem, as far as I see, is in mingw's Makefile:
````
EXTRA_lib32_libmsvcrt_a_DEPENDENCIES = lib32/msvcrt.def

lib32/libmsvcrt.a: $(lib32_libmsvcrt_a_OBJECTS) $(lib32_libmsvcrt_a_DEPENDENCIES) $(EXTRA_lib32_libmsvcrt_a_DEPENDENCIES) lib32/$(am__dirstamp)
        $(AM_V_at)-rm -f lib32/libmsvcrt.a
        ...

lib32/$(am__dirstamp):
        @$(MKDIR_P) lib32
        @: > lib32/$(am__dirstamp)

%.def: %.def.in
        $(CPP) -x c $< -Wp,-w -I$(top_srcdir)/def-include | $(SED) 's/^#/;/' >$@
````

I do not see a dependency of `lib32/msvcrt.def` on `lib32/$(am__dirstamp)` anywhere in the Makefile.

**Comment by stilor** [comment]
A bit more investigation: the `lib32` directory is created as a dependency to link `*.a` files in it, and all `*.a` libraries are listed as a dependency for the `all-am` target. Since lib32/msvcrt.def is also a dependency for $(LIBRARIES), make runs as many of them as possible and starts new processes as soon as more slots become available. Should mkdir stall for some longer period of time, the rule for lib32/msvcrt.def may get invoked without waiting for that mkdir (since there is no dependency).

This is corroborated by the fact that I observed this while building `i686-w64-mingw32` sample as part of build-all - i.e., in a midst of heavy disk thrashing :)

Verified the issue with 4.0.4 and top of the development tree, still present in both. To test without depending on parallel build randomness, rename /bin/mkdir to /bin/mkdir.orig and place the following script as /bin/mkdir (that will simulate /bin/mkdir taking longer than usual for lib32):

````
#!/bin/bash

[ "$1" = "-p" -a "$2" = "lib32" ] && sleep 3
exec /bin/mkdir.orig "$@"
````

Then try to build the `i686-w64-mingw32` sample.

**Comment by bhundven** [comment]
Merged. Thanks!

@mingwandroid when we figure out why mingw-w64-crt fails under heavy parallel build, we'll want to undo the removal of JOBSFLAGS.

**Comment by mingwandroid** [comment]
Nice idea with the script to force the issue out into the light.
