### ISSUE TITLE
canadian-cross: gettext breaks build under ubuntu

### ISSUE THREAD

**Issue by modbw** [crosstool-ng/crosstool-ng#274]
9e81836 "Add gettext and libiconv as companion libs" breaks a canadian cross build (on Ubuntu) of a arm toolchain to be run on windows. 

config and relevant lines from build.log are here
https://gist.github.com/modbw/697c76224292250aed72

From what I have understand from the patch in question gettext (and libiconv) are only needed when building on windows or osx but always selected when building a toolchain based on glibc.

**Comment by mingwandroid** [comment]
Gettext and icing are essential for the build machine yeah. I want to enable them for the host machine too soon though so that messages are translated. What versions of mingw-w64 and mingw-w64-gcc does Ubuntu come with? Which Ubuntu are you using?

**Comment by modbw** [comment]
I actually build the cross compiler (linux->windows) myself unsing crosstools-ng. The canadian cross build was then instructed to use that crosscompiler. So, the only thing using from ubuntu was the native gcc.

BTW:
From my point of view translating errors and warnings from a compiler is a bad idea. It is really hard to google for translated error messages. So, I personally don't see much need in a toolchain which uses localized error messages.

**Comment by mingwandroid** [comment]
Thanks. I expect people with no grasp of English or limited internet access would have a different opinion on the matter.

**Comment by mingwandroid** [comment]
@modbw I'd still like an answer about what versions Ubuntu runs with, and also the config.log from the /home/mweisser/projects/sd/MCP/Devices/MCPJ/boot/toolchain/win-arm-gs-linux-gnueabihf/.build/linux/none/toolchain/gen/ct-ng/.build/arm-gs-linux-gnueabihf/build/build-gettext-host-i686-host_w64-mingw32 folder if possible.

**Comment by modbw** [comment]
I updated the gist with the config.log. I have Ubuntu 15.10 running. The crosscompiler used for the canadian build is a gcc 5.2 which I build myself. I also added the .config of this crosscompiler as cross.config. Hope this helps. Please tell me if I can help you with more informations.

**Comment by bhundven** [comment]
@modbw Is this still an issue you have on ubuntu 15.10?

**Comment by eldorr** [comment]
I am having a go at building a canadian-cross:
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-w64-mingw32
[EXTRA]      target = arm-cortexa9_neon-linux-gnueabihf

where the host compiler has been built using crosstool-ng. My build fails with identical cause as reported above - i.e.
[ERROR]  >>  Build failed in step 'Installing gettext for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_gettext_backend[scripts/build/companion_libs/330-gettext.sh@131]
[ERROR]  >>        called from: do_gettext_for_host[scripts/build/companion_libs/330-gettext.sh@63]
[ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'

I have tried build environment on Ubuntu 14.04.3 LTS and 15.10 with the same result.
Are there any news on this matter - anyone...?

**Comment by mmarb** [comment]
I don't know if this is the correct approach, but i came up with a solution that seems to fix the build for me: [140-fix-unresolved-symbol.zip](https://github.com/crosstool-ng/crosstool-ng/files/211441/140-fix-unresolved-symbol.zip)

**Comment by stilor** [comment]
I see two errors in gettext build: one for the `end_sentence_spaces` as described above, and one for xmlFree (which was supposed to be satisfied by expat). Will look into it.

**Comment by modbw** [comment]
After a long time I found some time today to dive into the problem again today. I get it to compile by adding CPPFLAGS=-DLIBXML_STATIC to the configure step of gettext. I got this from https://github.com/mlocati/gettext-iconv-windows which contains a shell script cross compiling gettext for windows.

**Comment by modbw** [comment]
I have opend pull request #503 which fixes the issue for me.

**Comment by stilor** [comment]
I think this is fixed on master. If not, feel free to reopen.
