### ISSUE TITLE
Installing C library headers & start files - ElCapitan

### ISSUE THREAD

**Issue by unnamed666** [crosstool-ng/crosstool-ng#280]
hi, 
anyone stumbled upon this problem:

[INFO ]  Installing C library headers & start files
[ERROR]    make[3]: *** [/Volumes/CrosstoolCompile/ctng/.build/armv7-rpi2-linux-gnueabi/build/build-libc-startfiles/csu/libc-start.o] Error 1
[ERROR]    make[2]: *** [csu/subdir_lib] Error 2
[ERROR]    make[1]: *** [csu/subdir_lib] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library headers & start files'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@450]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@153]
[ERROR]  >>        called from: do_libc_start_files[scripts/build/libc/glibc.sh@70]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/Volumes/CrosstoolCompile/cross/share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 10:34.00)
[10:34] / make: *** [build] Error 2

can't figure it out... any help would be appreciated :)

**Comment by bhundven** [comment]
@unnamed666 You did not provide the full build log. The screen log tells us nothing.

**Comment by unnamed666** [comment]
right, sorry for that, here is my build log
http://grid.stronazen.pl/rpi/build.log
and config
http://grid.stronazen.pl/rpi/config.txt

**Comment by bhundven** [comment]
Re-run the build with: CT_PARALLEL_JOBS=1

CT_PARALLEL_JOBS=24 is impossible to figure out where the train went off the rails.

**Comment by bhundven** [comment]
I would also mention that you are in unsupported/uncharted territory.
My mac has been dead for about a year, and I've not had many mac os users available to help out with supporting this as a build host. The more info you can provide me with will greatly help out.

**Comment by unnamed666** [comment]
ok, new build.log with CT_PARALLEL_JOBS=1 rest of config is same as before
http://grid.stronazen.pl/rpi/build_2.log

more info about my setup
Mac Pro 3,5 GHz 6-Core Intel Xeon E5 16 GB 1866 MHz DDR3 ECC
Osx ElCapitan 10.11.1
newsest Xcode
missing libs where installed with brew
what else can be helpful ?

**Comment by bhundven** [comment]
Lots of crazy warnings with the linaro gcc, any chance you can try again with gcc-5.2.0?
Just as a test.

**Comment by unnamed666** [comment]
log with 5.2.0
http://grid.stronazen.pl/rpi/build_3.log

**Comment by bhundven** [comment]
Hrm, I'm not sure. It seems that there is something different with newer clang on mac os 10.11.
I wish my mac worked so I could figure out what it is.

@mingwandroid do you know what is going on here?

**Comment by unnamed666** [comment]
more info, when i add "-mthumb -nostartfiles" (found on google, but i dont know what startfiles are, can i even do that ?) to extra cflags i get past "Installing C library headers & start files"
but next error occur in pass-2
http://grid.stronazen.pl/rpi/build_4.log

**Comment by unnamed666** [comment]
next error fixed for anyone who stumbled upon same error as me, i needed to change 
this -> if ((a = rotate_left (val, i)) <= 0xff)
to
this -> if ((a = (val << i | (i == 0 ? 0:val >> (32 - i)))) <= 0xff)
in encode_arm_immediate function of file ctng/.build/src/binutils-2.25/gas/config/tc_arm.c
now i got error in next step
[INFO ]  Installing C library
[ERROR]    make[2]: *** [iconvdata/others] Error 2
[ERROR]    make[1]: *** [all] Error 2
http://grid.stronazen.pl/rpi/build_4.log

**Comment by mingwandroid** [comment]
@bhundven I'm looking into this now. I have some patches for OS X binutils issues already, testing them now.

**Comment by bhundven** [comment]
:+1:

**Comment by bhundven** [comment]
@unnamed666 Please clone the latest git master branch, and try this again. #283 has been merged.

**Comment by bhundven** [comment]
With the addition of #289, I'm going to consider this issue to be closed.
Please re-open if the issue persists.
