### ISSUE TITLE
build without LLVM on Mac

### ISSUE THREAD

**Issue by karfield** [crosstool-ng/crosstool-ng#285]
Try to build crosstool-ng with LLVM on Mac is painful, does anyone build it successfully with enable '--static' and 'gold' ? Can I try with macport's gcc to build as 'normal' gcc does?

**Comment by bhundven** [comment]
Checkout latest master branch. A pull request was just merged that fixes some "build on llvm" issues.

Static is not possible without a Static library available on mac os x. They do provide the source for their Csu, but we do not recommend that path, so static is just not supported on mac os x.

Again, the latest changes to fix "build on llvm" have been merged, and also include a fix for building gold.

If you have questions about the crosstool-ng project, please do not open an issue.
Post a question to the crossgcc mailing list: crossgcc@sourceware.org
Or join us on irc: irc.freenode.net #crosstool-ng
