### ISSUE TITLE
Location error when custom kernel name linux-custom.tar.gz

### ISSUE THREAD

**Issue by firemiles** [crosstool-ng/crosstool-ng#293]
When I name the custom kernel to linux-custom.tar.gz.
```shell
CT_KERNEL_LINUX_CUSTOM_LOCATION="${HOME}/linux-custom.tar.gz"
```

Then run ct-ng build, I got error like this.
```shell
[INFO ]  Retrieving needed toolchain components' tarballs: done in 77.65s (at 01:22)
[01:22] /
[INFO ]  =================================================================
[01:22] /
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-custom'
[01:22] /home/firemiles/arm-linux-gcc/.build/tarballs/linux-custom.tar.gz: No such file or directory
```
Is there some rules for name kernel tarball?

**Comment by bhundven** [comment]
This is a known issue. Hence the pull request: https://github.com/crosstool-ng/crosstool-ng/pull/288

The new pull request expects the package to extract to <component_name>-<version>/
So if your linux-custom.tar.gz extracts to linux-custom, put 'custom' in the custom version spot in menuconfig.

Please test the pull request and let us know your results.

**Comment by firemiles** [comment]
Thanks. I will have a test.

**Comment by bhundven** [comment]
@firemiles Did everything work as expected?

**Comment by bhundven** [comment]
#288 has been merged.

Re open this bug if you are still having an issue.
