### ISSUE TITLE
Passing LDFLAGS to libtool?

### ISSUE THREAD

**Issue by FreddieChopin** [crosstool-ng/crosstool-ng#297]
Hello!

I'm testing the static toolchain option. As I'm on Arch Linux I don't have any static libraries in the system. The first library that is needed is libfl (flex), so I downloaded the source, compiled it myself and installed into some local prefix. I then added the folder with this library to appropriate options:

```
[DEBUG]    CT_EXTRA_LDFLAGS_FOR_BUILD="-L${CT_TOP_DIR}/libs/lib"
[DEBUG]    CT_EXTRA_LDFLAGS_FOR_HOST="-L${CT_TOP_DIR}/libs/lib"
```

The build of binutils fails, and in build.log I see that these linker flags are not passed to libtool invocations for linking binutils:

```
[ALL  ]    libtool: link: x86_64-build_pc-linux-gnu-gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -I/home/freddie/bleeding-edge-toolchain-ct-ng/.build/src/binutils-2.25.1/binutils/../zlib -O2 -g -pipe -static-libstdc++ -static-libgcc -static -o bfdtest1 bfdtest1.o  ../bfd/.libs/libbfd.a -L/home/freddie/bleeding-edge-toolchain-ct-ng/.build/arm-none-eabi/build/build-binutils-host-x86_64-build_pc-linux-gnu/zlib -lz ../libiberty/libiberty.a -ldl
[ALL  ]    /usr/bin/ld: cannot find -lfl
```

On the other hand I see them used in other places, including some libtool invocations:

```
[ALL  ]    /usr/bin/bash ./libtool --silent --mode=link x86_64-build_pc-linux-gnu-gcc -I/home/freddie/bleeding-edge-toolchain-ct-ng/.build/src/expat-2.1.0/lib -I. -O2 -g -pipe  -Wall -Wmissing-prototypes -Wstrict-prototypes -fexceptions  -DHAVE_EXPAT_CONFIG_H -L/home/freddie/bleeding-edge-toolchain-ct-ng/libs/lib -o xmlwf/xmlwf xmlwf/xmlwf.o xmlwf/xmlfile.o xmlwf/codepage.o xmlwf/unixfilemap.o libexpat.la
```

Any idea how to solve that (if that is at all possible)?

**Comment by bhundven** [comment]
I have abandoned working with archlinux.

I wasted two weeks trying to unravel the same issues you are running into and it comes down to missing static libraries on archlinux. You may as well make a new linux distro (I opt for the name: Snarchlinux) that is archlinux, but with the static libraries added back.

I don't agree with their decision to remove static libraries, as some cross-development tools (like crosstool-ng, buildroot, openembedded/yocto, and more) require static libraries on the build system.

At least be like fedora and provide extra packages with static libraries... (Yes, I can read the emails on their mailing list saying "But adding extra packages is hard *tear* *tear* *snivel* *sobb*")

I refuse to add rpath to crosstool-NG as it would require more external dependencies and more cruft to keep track of maintaining our ability to have relocatable toolchains, which is a major feature... provided you have static libraries on your build system.

So with that, I do not support crosstool-NG on archlinux.

**Comment by bhundven** [comment]
Don't hear me wrong. Personally I like archlinux. I've followed it's progress since CRUX.
I hope they figure out the static-lib issue, otherwise it is unusable for my purposes.

**Comment by FreddieChopin** [comment]
Are you sure that this particular issue I see here is Arch-Linux-related? I'm (probably) quite OK with providing the static libraries myself, but the flags I pass to the compilation don't make any effect for libtool invocations for binutils.

**Comment by bhundven** [comment]
I've tested crosstool-NG on:

* Debian (squeeze to stretch/sid)
* CentOS 6/7
* Fedora (12-23)
* OpenSuse
* OpenBSD/FreeBSD
* Gentoo
* Mac OS X (For static linking, you need the Csu for your installed version. It's an ugly hack but it works)

Archlinux is the only one on the list that fails this way.

**Comment by FreddieChopin** [comment]
I know that the static libraries are not in the system. But why does LDFLAGS get passed to some linking steps and _NOT_ passed to others? If only LDFLAGS was passed to all linking steps then I wouldn't have this problem (I'd probably have some more, but not this particular one).

**Comment by bhundven** [comment]
I'm not sure. I tried to figure that out as well, but I only have that problem on archlinux.

**Comment by bhundven** [comment]
If you figure it out, I'd be happy to help to make it work, but I've given up on it.

**Comment by bhundven** [comment]
One hint I may have on this is that the configure scripts often look for the <pkg>.pc for cflags, and libraries. If you're installing the static libraries, but not installing/updating the .pc files, the build might be acting the way you describe it.

**Comment by FreddieChopin** [comment]
But shouldn't LDFLAGS be passed to the command anyway?

**Comment by bhundven** [comment]
I'm not sure what you're talking about:

https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/build/binutils/binutils.sh#L225

**Comment by bhundven** [comment]
Oh, wait. I see. You're setting: ```CT_EXTRA_LDFLAGS_FOR_BUILD="-L${CT_TOP_DIR}/libs/lib"```
But binutils is setting: ```ldflags=${CT_LDFLAGS_FOR_BUILD}"```

**Comment by bhundven** [comment]
Which shouldn't matter: https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/crosstool-NG.sh.in#L498

**Comment by FreddieChopin** [comment]
Yes, I know that it shouldn't matter, but the LDFLAGS I added are somehow ignored by linking step for binutils. At the same time they are used in some other build steps (I saw them used for companion libs). I can provide you with a full log if you want.

**Comment by bhundven** [comment]
@FreddieChopin try this:

https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/build/binutils/binutils.sh#L238

Change this line to read:

```extra_make_flags+=("LDFLAGS=$LDFLAGS -all-static")```

**Comment by bhundven** [comment]
Or that should be $ldflags not $LDFLAGS, since $LDFLAGS is only set for the configure line.

**Comment by bhundven** [comment]
It's possible that may still fail because of quoting.

**Comment by FreddieChopin** [comment]
Changing to `extra_make_flags+=("LDFLAGS=$ldflags -all-static")` fixes the issue. The first one you proposed (`extra_make_flags+=("LDFLAGS=$LDFLAGS -all-static")`) doesn't work.

**Comment by bhundven** [comment]
> The first one you proposed (extra_make_flags+=("LDFLAGS=$LDFLAGS -all-static")) doesn't work.

Right, I figured that out after looking at that again.
I will fix this issue in master in a minute.

**Comment by FreddieChopin** [comment]
thx for looking into that and thanks for the fix (;

BTW - what Linux distribution are you using right now?

**Comment by bhundven** [comment]
Debian Sid (Sid in toy story was always unstable ;) )

I would assume that fixing this issue might fix other issues with mingw or cross-canadian builds. I'm glad you found this issue!

**Comment by FreddieChopin** [comment]
> I would assume that fixing this issue might fix other issues with mingw or cross-canadian builds. I'm glad you found this issue!

See? Another positive aspect of using Arch (;

**Comment by bhundven** [comment]
I'm still not happy with the fact that you have to do manual work to make crosstoo-ng (and other cross-development tools) to work correctly.
