### ISSUE TITLE
Could you tell me which packages are buildpack-deps and which packages are running ct-ng deps

### ISSUE THREAD

**Issue by firemiles** [crosstool-ng/crosstool-ng#300]
Hi, I want to build crosstool-ng image in docker from debian:wheezy.
Now the image size is 130M.
Is there any packages can be remove after crosstool-ng installed to reduce the image size?
I cant't judge which packages are for building crosstool-ng and which packages are for crosstool-ng to build toolchains. Could you tell me some message for this? Thanks.

This is my current package list:
```shell
    apt-get update && apt-get install -y \
    git \
    autoconf \
    build-essential \
    gperf \
    bison \
    flex \
    texinfo \
    libtool \
    libncurses5-dev \
    wget \
    gawk \
    libc6-dev \
    help2man \
    unzip \
```

**Comment by bhundven** [comment]
If you have a question, please ask on: crossgcc@sourceware.org
