### ISSUE TITLE
binutils for target did not get libiberty installed

### ISSUE THREAD

**Issue by phsung** [crosstool-ng/crosstool-ng#302]
Hi,

I was trying to crossbuild a toolchain with "binutils target install" (libiberty and libbfd) and found that to be not installed (but checking log they were built) after the whole build process is finished.

Upon checking the configure script for binutils (and libiberty inside of it)  libiberty needs --enable-install-libiberty flag to enable the installation.

Thanks.

**Comment by bhundven** [comment]
Thanks! I'll review this and look into a fix!

**Comment by bhundven** [comment]
@phsung try using the commit from #305 to see if that works properly for you.
