### ISSUE TITLE
Build failed in step 'Installing binutils for host'

### ISSUE THREAD

**Issue by MatejKovacic** [crosstool-ng/crosstool-ng#315]
Hi, I am trying to compile C++

I am using Ubuntu 15.04 and want to compile C++ for Raspberry Pi. In ct-ng menuconfig I enabled C++ under C compiler menu.

I run ct-ng build and get this error:

[INFO ]  Installing binutils for host
[ERROR]    make[2]: *** [configure-ld] Error 1
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@240]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@105]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/matej/RaspberryPi/toolchain/local/crosstool-ng/share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 6:29.98)
[06:30] / /home/matej/RaspberryPi/toolchain/local/crosstool-ng/bin/ct-ng:152: recipe for target 'build' failed
make: *** [build] Error 2

Please note, that I already successfully compiled C.

Maybe this info about my config would be useful as well:
- binary utilities ---> binutils version: 2.25.1
- C compiler ---> gcc version (5.2.0) ---> linaro-4.9-2015.06
- target architecture: arm, Endianness: (Little endian), Bitness: (32-bit)
- target OS: linux

Any idea what could be wrong?

**Comment by MatejKovacic** [comment]
BTW, build.log is here: http://matej.owca.info/build.log

**Comment by MatejKovacic** [comment]
Hi, sorry, I figured it out.

For cross-compiling code that uses C++11 futures/promises there needs to be special parameter set: Target options -> Architecture level: armv6.

Now it went just fine.

**Comment by polejo** [comment]
I have this error today， fix it by install zlib-static on host。
FYI

**Comment by Yasser-Jemli** [comment]
Yes , I have the same issue and i fix it by setting Target >> arch_level :  armv6 
Thanks !
