### ISSUE TITLE
[ERROR]    configure: error: C preprocessor "/lib/cpp" fails sanity check

### ISSUE THREAD

**Issue by M2shad0w** [crosstool-ng/crosstool-ng#327]
### when i build crosstools-ng for esp8266, it raises this error, anyone help?

```bash
[ALL  ]    checking for suffix of object files... o
[ALL  ]    checking whether we are using the GNU C compiler... yes
[ALL  ]    checking whether  /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/xgcc -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/bin/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/lib/ -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/include -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/sys-include    accepts -g... yes
[ALL  ]    checking for  /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/xgcc -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/bin/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/lib/ -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/include -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/sys-include    option to accept ISO C89... unsupported
[ALL  ]    checking how to run the C preprocessor... /lib/cpp
[ERROR]    configure: error: in `/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/xtensa-lx106-elf/libgcc':
[ERROR]    configure: error: C preprocessor "/lib/cpp" fails sanity check
[ALL  ]    See `config.log' for more details.
[ERROR]    make[3]: *** [configure-target-libgcc] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-2 core C compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@216]
[ERROR]  >>        called from: do_cc_core_backend[scripts/build/cc/gcc.sh@483]
[ERROR]  >>        called from: do_cc_core_pass_2[scripts/build/cc/gcc.sh@153]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]
```

**Comment by bhundven** [comment]
@jcmvbkbc Maybe you can take a look here?

**Comment by bhundven** [comment]
@M2shad0w You also need to give us more information.

I have a math problem. The answer I got was 4. It's wrong. What is wrong with my math equation?

Can you think about my math problem and your issue and discover what you need to show us to help you?

**Comment by M2shad0w** [comment]
### i do as the article [build ESP8266 dep env](http://www.jollen.org/blog/2016/01/study-freertos-using-esp8266.html)

step by step

but when i run command `$ make STANDALONE=n`

#### the process fails with error

<pre><code>[INFO ]  Installing pass-2 core C compiler
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/cstddef:46:9: error: no member named 'ptrdiff_t' in the global namespace
[ERROR]    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/iterator:402:13: error: unknown type name 'ptrdiff_t'
</code></pre>
<pre><code>[ERROR]    fatal error: too many errors emitted, stopping now [-ferror-limit=]
[ERROR]    make[4]: *** [graphite.o] Error 1
[ERROR]    make[4]: *** [graphite-blocking.o] Error 1
[ERROR]    make[3]: *** [all-gcc] Error 2
[ERROR]   
[ERROR]  &gt;&gt;
[ERROR]  &gt;&gt;  Build failed in step 'Installing pass-2 core C compiler'
[ERROR]  &gt;&gt;        called in step '(top-level)'
[ERROR]  &gt;&gt;
[ERROR]  &gt;&gt;  Error happened in: CT_DoExecLog[scripts/functions@216]
[ERROR]  &gt;&gt;        called from: do_cc_core_backend[scripts/build/cc/gcc.sh@483]
[ERROR]  &gt;&gt;        called from: do_cc_core_pass_2[scripts/build/cc/gcc.sh@153]
[ERROR]  &gt;&gt;        called from: main[scripts/crosstool-NG.sh@638]
</code></pre>

### then do as [this issue](https://github.com/pfalcon/esp-open-sdk/issues/45#ref-issue-67711613)


>  Probably not the best solution, but this makes it compile:

>  In esp-open-sdk/crosstool-NG/.build/src/gcc-4.8.2/gcc, add this line somewhere at the top:

> #include <stddef.h>

> of the following files:
graphite.c 
graphite-blocking.c 
graphite-clast-to-gimple.c
graphite-dependences.c 
graphite-interchange.c 
graphite-optimize-isl.c 
graphite-poly.c 
graphite-scop-detection.c 
graphite-sese-to-poly.c

passed, but failed with above mention

```
[ERROR]    configure: error: in `/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/xtensa-lx106-elf/libgcc':
[ERROR]    configure: error: C preprocessor "/lib/cpp" fails sanity check
```
### here is all the [build log](https://gist.github.com/M2shad0w/9d60944dabc8f378a2ad)  about 4M 

![image](https://cloud.githubusercontent.com/assets/3387446/12697411/40886a42-c7bd-11e5-9e25-e5c0b71a4c02.png)

**Comment by jcmvbkbc** [comment]
@M2shad0w can you also share the file /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/xtensa-lx106-elf/libgcc/config.log ?

**Comment by M2shad0w** [comment]
@jcmvbkbc  thank you for your response

[here is the config.log](https://gist.github.com/M2shad0w/783d5605750e8c09d6fd)

**Comment by jcmvbkbc** [comment]
@M2shad0w thanks.

So...
```
/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/xgcc -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/bin/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/lib/ -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/include -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/sys-include     -c -g -Os  conftest.c >&5
In file included from /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/stdio.h:64:0,
                 from conftest.c:10:
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk/usr/include/sys/cdefs.h:707:2: error: #error Unsupported architecture
 #error Unsupported architecture
```
...for some reason the cross compiler tries to use host's include files through the libgcc configuration process. Let's try to find out why by invoking it with -v option so that it prints details of what it does. Can you do the following and post the output here?:

```
echo '#include <stdio.h>' > conftest.c
/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/xgcc -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/build/build-cc-core-pass-2/./gcc/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/bin/ -B/Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/lib/ -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/include -isystem /Volumes/esp-open-sdk/esp-open-sdk/crosstool-NG/.build/xtensa-lx106-elf/buildtools/xtensa-lx106-elf/sys-include   -v  -c -g -Os  conftest.c
```

**Comment by M2shad0w** [comment]
@jcmvbkbc 
the config test log is here [https://gist.github.com/M2shad0w/3c149613f4295209b508](https://gist.github.com/M2shad0w/3c149613f4295209b508)

**Comment by jcmvbkbc** [comment]
@M2shad0w OK, there are extra include directories. Looks like they are picked from the CPATH environment variable. Can you run your crosstool-NG build with this variable unset? I also suspect that you'd need to unset it to be able to use the built cross-compiler.

**Comment by M2shad0w** [comment]
@jcmvbkbc thanks .
i have ever set the $CPATH in my ~/.zshrc file, it's the reason.
Now, follow your ideas, it's OK!

**Comment by bhundven** [comment]
@jcmvbkbc +1 Thanks for your help with this!

**Comment by bhundven** [comment]
I'm actually going to make this a test or abort in crosstool-NG.sh.in, as setting CPATH for any build could potentially break the build.
