### ISSUE TITLE
configure: error: missing required tool(s)

### ISSUE THREAD

**Issue by skibulk** [crosstool-ng/crosstool-ng#329]
I'm running Ubuntu Trusty Tahr. When I run `./configure`, I receive multiple `missing required tool` errors. I searched the documentation but could not find any such prerequisites or system requirements.

gperf
bison
flex
makeinfo

I installed the first three using `apt-get install` but Ubuntu is `unable to locate package makeinfo`. There may be additional "missing tools", but I can't proceed.

**Comment by bhundven** [comment]
makeinfo is provided by the ```texinfo``` package.

You should be able to install all of these: ```sudo apt-get install gperf bison flex texinfo```

You might run into others. The documentation is way out of date and needs some love. I have it as a todo and plan to update it before the next release.
