### ISSUE TITLE
uClibc-ng: MIPS memcpy() was broken between 1.0.9 - 1.0.10

### ISSUE THREAD

**Issue by ryzhovau** [crosstool-ng/crosstool-ng#343]
memcpy() was broken between 1.0.9 - 1.0.10 which causes some errors/segfaults in 

* [openvpn](http://forums.zyxmon.org/viewtopic.php?p=14378#p14378) (russian thread),
* [transmission](http://mailman.uclibc-ng.org/pipermail/devel/2016-February/000742.html),
* [node.js](http://pastebin.com/RbhvEYiV)

Please, consider adding patch to unroll glibc memcpy/memset implementation

[9000-unroll-glibc-memcpy.patc](https://github.com/Entware-ng/Entware-ng/blob/master/toolchain/uClibc/patches/9000-unroll-glibc-memcpy.patch) plus [9010-unroll-glibc-memset.patch](https://github.com/Entware-ng/Entware-ng/blob/master/toolchain/uClibc/patches/9010-unroll-glibc-memset.patch)

or 

[0000-mips-memset-memcpy-undo-2636b17616.patch](https://github.com/Optware/Optware-ng/blob/master/sources/buildroot-mipsel-ng/uclibc-ng-patches/0000-mips-memset-memcpy-undo-2636b17616.patch)

to fix it.

**Comment by bhundven** [comment]
Without any reference, I would tell you that the master branch uses uClibc-ng 1.0.12.
Did you mean to reference the 1.22 branch?
Since the 1.22 branch is going to be supported for a little while, would it make sense for me to bump uClibc-ng in the 1.22 branch to 1.0.12?

**Comment by ryzhovau** [comment]
> Did you mean to reference the 1.22 branch?

I don't know about branches in this project.

> Since the 1.22 branch is going to be supported for a little while, would it make sense for me to bump uClibc-ng in the 1.22 branch to 1.0.12?

If you going to update uclibc-ng to 1.0.10 or higher, please consider to unroll [this commit](http://uclibc-ng.org/changeset/b778f37b8395a3258925e13a706dbc7d43c7c0ed/uclibc-ng). New MIPS memcpy.S/memset.S implementations are buggy. 

You can get additional info from Waldemar Brodkorb (uClib-ng author) by mail <wbx@uclibc-ng.org> or at #uclibc-ng @ irc.freenode.net.

**Comment by bhundven** [comment]
I was not aware of this issue. I'll wait for Waldemar to respond.

**Comment by bhundven** [comment]
@ryzhovau I'm going to leave this as a known issue. I spoke with Waldemar about this and he is working on a fix. I have no interest in reproducing or reverting this work in crosstool-ng, and when an upstream fix is produced, I will either backport it or update to the newer uClibc-ng version. You're more then welcome to add these patches to a local patch bundle.

**Comment by ryzhovau** [comment]
Please, don't expect me to contribute to `crosstool-ng`at this time, sorry. All I wanted was to let you know about this bug.
