### ISSUE TITLE
Copy/Install headers to ${CT_PREFIX_DIR}/${CT_TARGET}/include/include

### ISSUE THREAD

**Issue by ieei** [crosstool-ng/crosstool-ng#344]
Hi, I'm new to crosstool-ng.

I built a toolchain for `arm-unknown-eabi` today and found that 
`${CT_PREFIX_DIR}/${CT_TARGET}/include` also have a subdir `include` which I belive is wrong. To me this seems like a copy of ${CT_HEADERS_DIR} so it could be related to af731ae90400bac2116d8fa15e3a0edd209ff4b5 ? I'm just guessing. This is by no means a blocker for me. I just found it weird looking through the directory structure of the output.

**Comment by bhundven** [comment]
@ieei Ok, I'm looking into this now. Thanks for the heads up!

**Comment by bhundven** [comment]
BTW, is this on master or 1.22?

**Comment by bhundven** [comment]
I see the same thing, I'm going to do some tests to see if I can sort this out. Thanks!

**Comment by ieei** [comment]
@bhundven yes, I only tested master, but I see you already have confirmed. Thanks! Let me know if there is anything I can do!

**Comment by stilor** [comment]
Should be fixed once https://github.com/crosstool-ng/crosstool-ng/pull/526 is merged.

**Comment by stilor** [comment]
Merged to master.
