### ISSUE TITLE
gccgo error "Unable to recognise the format of the input file"

### ISSUE THREAD

**Issue by enjoydiy** [crosstool-ng/crosstool-ng#347]
273482 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-c++' [elf64-x86-64] to `bin/st05WcIG' [elf64-x86-64]
273483 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-c++filt'
273484 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-c++filt' [elf64-x86-64] to `bin/stmNh8YI' [elf64-x86-64]
273485 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-cpp'
273486 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-cpp' [elf64-x86-64] to `bin/stCQCEUM' [elf64-x86-64]
273487 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-elfedit'
273488 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-elfedit' [elf64-x86-64] to `bin/stb4klBF' [elf64-x86-64]
273489 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-g++'
273490 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-g++' [elf64-x86-64] to `bin/stn5WkdG' [elf64-x86-64]
273491 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcc'
273492 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcc' [elf64-x86-64] to `bin/stsXvCJJ' [elf64-x86-64]
273493 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcc-5.3.0'
273494 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcc-5.3.0' [elf64-x86-64] to `bin/stL6fdCH' [elf64-x86-64]
273495 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcc-ar'
273496 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcc-ar' [elf64-x86-64] to `bin/strOZ5BL' [elf64-x86-64]
273497 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcc-nm'
273498 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcc-nm' [elf64-x86-64] to `bin/stjyOB2L' [elf64-x86-64]
273499 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcc-ranlib'
273500 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcc-ranlib' [elf64-x86-64] to `bin/stY2bN2K' [elf64-x86-64]
273501 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gccgo'
273502 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gccgo' [elf64-x86-64] to `bin/st12AY3N' [elf64-x86-64]
273503 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcov'
273504 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcov' [elf64-x86-64] to `bin/stBZ85RM' [elf64-x86-64]
273505 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gcov-tool'
273506 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gcov-tool' [elf64-x86-64] to `bin/stFQrdfN' [elf64-x86-64]
273507 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-gdb'
273508 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-gdb' [elf64-x86-64] to `bin/stX5rWgQ' [elf64-x86-64]
273509 [DEBUG]    ==> Executing: 'x86_64-build_pc-linux-gnu-strip' '--strip-all' '-v' 'bin/mipsel-netease-linux-gnu-go'
273510 [ALL  ]    copy from `bin/mipsel-netease-linux-gnu-go' [elf32-little] to `bin/stCnw62P' [elf32-little]
273511 [ALL  ]    /usr/bin/strip: Unable to recognise the format of the input file `bin/mipsel-netease-linux-gnu-go'
273512 [ERROR]
273513 [ERROR]  >>
273514 [ERROR]  >>  Build failed in step 'Cleaning-up the toolchain's directory'
273515 [ERROR]  >>        called in step '(top-level)'
273516 [ERROR]  >>
273517 [ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
273518 [ERROR]  >>        called from: do_finish[scripts/build/internals.sh@55]
273519 [ERROR]  >>        called from: main[scripts/crosstool-NG.sh@650]
273520 [ERROR]  >>
273521 [ERROR]  >>  For more info on this error, look at the file: 'build.log'
273522 [ERROR]  >>  There is a list of known issues, some with workarounds, in:
273523 [ERROR]  >>      '/home/wzj/Bin/crosstool_ng/out/share/doc/crosstool-ng/crosstool-ng-1.22.0-92-g6df2abc/B - Known issues.txt'

How to solve the strip error or close the error report?

**Comment by bhundven** [comment]
I haven't figured it out:
https://github.com/crosstool-ng/crosstool-ng/issues/96

I have some work in progress:
https://github.com/crosstool-ng/crosstool-ng/pull/136

But I'm also doing most of this work on crosstool-ng on my own. If you have ideas to help me fix this, do join me on the existing open issue.

This issue is a duplicate, and I am closing it as such.

**Comment by enjoydiy** [comment]
Could you give a temporary way to solve the issue? 
I add the code to scripts/build/cc/100-gcc.sh
     if [ "${CT_CC_LANG_GOLANG}" = "y"  ]; then                                                                                                                                                                                          
        extra_config+=("--disable-werror")
     fi

However, the way is not a good one. Please, I have figure the from this afternoon until now.
