### ISSUE TITLE
Update kernel list to reflect kernel.org

### ISSUE THREAD

**Issue by dajamminyogesh** [crosstool-ng/crosstool-ng#349]
Attached is a patch to update the list of kernels to reflect kernel.org

Update includes removal of 4.2.x kernel (since it was EOL).  Addition of 4.4.x kernel, and marking of 4.3.x as EOL.

[kernel.patch.txt](https://github.com/crosstool-ng/crosstool-ng/files/143424/kernel.patch.txt)

**Comment by bhundven** [comment]
No, do a pull request.
