### ISSUE TITLE
cannot find -lstdc++

### ISSUE THREAD

**Issue by enjoydiy** [crosstool-ng/crosstool-ng#355]
49406 [ALL  ]    echo 'const defaultCXX = "/home/wzj/x-tools/mipsel-netease-linux-gnu/bin/mipsel-netease-linux-gnu-g++"' >> zdefaultcc.go.tmp
49407 [ALL  ]    /bin/bash /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../move-if-change zdefaultcc.go.tmp zdefaultcc.go
49408 [ALL  ]    echo timestamp > s-zdefaultcc
49409 [ALL  ]    /home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final/./gcc/gccgo -B/home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final/./gcc/ -EL -
      march=mips32 -mabi=32    -mhard-float  -minterlink-mips16 -g -Os  -static -lstdc++ -lm -L ../mipsel-netease-linux-gnu/libgo -L ../mipsel-netease-linux-gnu/libgo/.libs -o go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.
      0/gotools/../libgo/go/cmd/go/build.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/clean.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/context.
      go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/discovery.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/env.go /home/wzj/Bin/crosstool_ng/build/
      test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/fix.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/fmt.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/
      go/cmd/go/generate.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/get.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/go11.go /home/wzj/Bin/
      crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/help.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/http.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.
      3.0/gotools/../libgo/go/cmd/go/list.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/main.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/pkg.go /
      home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/run.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/signal.go /home/wzj/Bin/crosstool_ng/build/test/.
      build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/signal_unix.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/test.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../
      libgo/go/cmd/go/testflag.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/tool.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/vcs.go /home/wzj/Bin/
      crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/version.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/go/vet.go ../mipsel-netease-linux-gnu/libgo/zstdpkglist.go
      zdefaultcc.go
49410 [ALL  ]    /home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final/./gcc/gccgo -B/home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final/./gcc/ -EL -
      march=mips32 -mabi=32    -mhard-float  -minterlink-mips16 -g -Os  -static -lstdc++ -lm -L ../mipsel-netease-linux-gnu/libgo -L ../mipsel-netease-linux-gnu/libgo/.libs -o cgo /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.
      3.0/gotools/../libgo/go/cmd/cgo/ast.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/cgo/doc.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/cgo/gcc.go /
      home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/cgo/godefs.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/cgo/main.go /home/wzj/Bin/crosstool_ng/build/test/.
      build/src/gcc-5.3.0/gotools/../libgo/go/cmd/cgo/out.go /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/gotools/../libgo/go/cmd/cgo/util.go zdefaultcc.go
49411 [ALL  ]    /home/wzj/x-tools/mipsel-netease-linux-gnu/mipsel-netease-linux-gnu/bin/ld: cannot find -lstdc++                                                                                                                           
49412 [ERROR]    collect2: error: ld returned 1 exit status
49413 [ERROR]    make[3]: *** [gofmt] Error 1
49414 [ALL  ]    make[3]: *** Waiting for unfinished jobs....
49415 [ALL  ]    /home/wzj/x-tools/mipsel-netease-linux-gnu/mipsel-netease-linux-gnu/bin/ld: cannot find -lstdc++
49416 [ERROR]    collect2: error: ld returned 1 exit status
49417 [ERROR]    make[3]: *** [cgo] Error 1
49418 [ALL  ]    /home/wzj/x-tools/mipsel-netease-linux-gnu/mipsel-netease-linux-gnu/bin/ld: cannot find -lstdc++
49419 [ALL  ]    ../mipsel-netease-linux-gnu/libgo/.libs/libgo.a(net.o): In function `net.LookupPort':
49420 [ALL  ]    /home/wzj/Bin/crosstool_ng/build/test/.build/src/gcc-5.3.0/libgo/go/net/cgo_unix.go:83: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version
      used for linking
49421 [ERROR]    collect2: error: ld returned 1 exit status
49422 [ERROR]    make[3]: *** [go] Error 1
49423 [ALL  ]    make[3]: Leaving directory `/home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final/gotools'
49424 [ERROR]    make[2]: *** [all-gotools] Error 2
49425 [ALL  ]    make[2]: Leaving directory `/home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final'
49426 [ERROR]    make[1]: *** [all] Error 2
49427 [ALL  ]    make[1]: Leaving directory `/home/wzj/Bin/crosstool_ng/build/test/.build/mipsel-netease-linux-gnu/build/build-cc-gcc-final'
49428 [ERROR]
49429 [ERROR]  >>
49430 [ERROR]  >>  Build failed in step 'Installing final gcc compiler'
49431 [ERROR]  >>        called in step '(top-level)'
49432 [ERROR]  >>

**Comment by enjoydiy** [comment]
gcc4.9 pass, gcc5.3 fail. I do not know why notice "cannot find -lstdc++"

**Comment by bhundven** [comment]
Posting a partial log is not helpful. Please drag your build.log here so we can see the full log.
It's also helpful to know what OS/Distribution you are building on.

**Comment by bhundven** [comment]
Also, and again, gccgo is not fully supported here in crosstool-ng.

**Comment by enjoydiy** [comment]
Thanks for replying. I have done it. I modify 100-gcc.sh file:

753     if [ "${CT_STATIC_TOOLCHAIN}" = "y" ]; then          
754     ┊   final_LDFLAGS+=("-static")
755     ┊   host_libstdcxx_flags+=("-static-libgcc")         
756     ┊   host_libstdcxx_flags+=("-Wl,-Bstatic,-lstdc++")  
757     ┊   host_libstdcxx_flags+=("-lm")                    
758     ┊   # Companion libraries are build static (eg !shared), so             
759     ┊   # the libstdc++ is not pulled automatically, although it            
760     ┊   # is needed. Shoe-horn it in our LDFLAGS         
761     ┊   # Ditto libm on some Fedora boxen                
762     ┊  # final_LDFLAGS+=("-lstdc++")
763     ┊  #modiy by wzj                                                                                                                                                                                                                    
764     ┊   final_LDFLAGS+=("-lm")

The line 762 is taken out.

**Comment by bhundven** [comment]
You're doing something wrong. You shouldn't need to modify the code.
