### ISSUE TITLE
ARM64/Aarch64 support

### ISSUE THREAD

**Issue by bhundven** [crosstool-ng/crosstool-ng#361]
I merged #360 without checking the raspberry pi 3 specs. It's a 64-arm, which is not well supported here in crosstool-NG land.

This issue is open to track the progress of aarch64 support.

**Comment by bhundven** [comment]
I was totally wrong. We do have aarch64 support.

**Comment by droidzone** [comment]
It doesnt seem to be an option under the Target architecture menu. How to add this?

**Comment by stilor** [comment]
Select ARM as the architecture and "64" as bitness.
