### ISSUE TITLE
issue when cross-compiling node.js for raspberry pi 2 toolchain

### ISSUE THREAD

**Issue by artynet** [crosstool-ng/crosstool-ng#367]
Hello folks, after generating the cross-toolchain for raspberry pi2 with **crosstools-NG** itself, I get this error when building the latest source of node.js for the **armv7l** platform. To ease the build I have written a simple bash script exporting the necessary ENV variables, please take a look at it :

https://gist.github.com/artynet/f7ba21c27dbe7c0a7095

since I want to make a binary redistributable archive of the sources.

```

armv7-rpi2-linux-gnueabihf-g++ -pthread -rdynamic -B/home/artynet/Scrivania/build_source/node-v5.7.1/ -Wl,-rpath-link /opt/armv7-rpi2-linux-gnueabihf/armv7-rpi2-linux-gnueabihf/sysroot/lib -o /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/mksnapshot -Wl,--start-group /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/mksnapshot/deps/v8/src/snapshot/mksnapshot.o /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_base.a /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_nosnapshot.a /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_libplatform.a /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/deps/v8/tools/gyp/libv8_libbase.a -Wl,--end-group -ldl -lrt
 LD_LIBRARY_PATH=/home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/lib.host:/home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/lib.target:$LD_LIBRARY_PATH; export LD_LIBRARY_PATH; cd ../deps/v8/tools/gyp; mkdir -p /home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/v8_snapshot/geni; "/home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/mksnapshot" --log-snapshot-positions --logfile "/home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/v8_snapshot/geni/snapshot.log" "/home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/v8_snapshot/geni/snapshot.cc" ""
/lib/ld-linux-armhf.so.3: No such file or directory
make[2]: *** [/home/artynet/Scrivania/build_source/node-v5.7.1/out/Release/obj.target/v8_snapshot/geni/snapshot.cc] Errore 255
make[2]: uscita dalla directory "/home/artynet/Scrivania/build_source/node-v5.7.1/out"
make[1]: *** [node] Errore 2
make[1]: uscita dalla directory "/home/artynet/Scrivania/build_source/node-v5.7.1"
make: *** [node-v5.7.1-linux-armv7l.tar] Errore 2
```

I am already well aware that the binaries for the armv7l architecture are already available, but I'd like anyway to solve this error in case I need to build the trunk of node in the next future. What seems strange to me is that the symbolic link `ld-linux-armhf.so.3` is already part of the cross toolchain and it's not detected during the build process. Any thoughts on that ? 

In addition to this, I posted this thread in the 'issues' section of the node.js GitHub repository and I was told that this problem might be related to the **sandbox** of the toolchain itself....any hints on this ?

Best, Arturo

Thanks in advance.

Best, arturo
- **Version**:  5.7.1
- **Platform**: raspberry pi 2 (armv7l)

**Comment by bhundven** [comment]
Have you tried building without setting LD_LIBRARY_PATH?

**Comment by bhundven** [comment]
Oh, that is the node build.
