### ISSUE TITLE
Alpha ld occurs an error. "no .eh_frame_hdr table will be created."

### ISSUE THREAD

**Issue by PAPL-SKKU** [crosstool-ng/crosstool-ng#370]
Hi, 

I'm trying to build Alpha cross compiler with crosstool-ng-1.22.0. I just built it with *alphaev67-unknown-linux-gnu* configuration successfully, but I cannot compile any c code with the built cross compiler. The error message is shown below:

```
$ ~/x-tools/alphaev67-unknown-linux-gnu/bin/alphaev67-unknown-linux-gnu-gcc hello.c
/home/channoh/x-tools/alphaev67-unknown-linux-gnu/lib/gcc/alphaev67-unknown-linux-
gnu/5.2.0/../../../../alphaev67-unknown-linux-gnu/bin/ld: error in /home/channoh/x-tools/alphaev67-
unknown-linux-gnu/lib/gcc/alphaev67-unknown-linux-gnu/5.2.0/crtend.o(.eh_frame); no .eh_frame_hdr 
table will be created.
```

The installation commands and tested c code are below.

```
./configure --prefix=$PWD
make && make install
mkdir alpha && mv alpha
../ct-ng alphaev67-unknonw-linux-gnu
../ct-ng build -j4
```

```cpp
#include <stdio.h>

int main() {
    printf("Hello World\n");
    return 0;
}
```

Did I have something wrong?

**Comment by PAPL-SKKU** [comment]
I success to build a cross compiler for ALPHA with crosstool-ng-1.22.0. Therefore, I close this issue.

**Comment by zhengyangxiaogan** [comment]
I have the same trouble like you, please tell me how could you slove the problem? And my email is :zhengyangxiaogan@gmail.com, thank you very much!
