### ISSUE TITLE
Build fails in step 'Installing binutils for host'

### ISSUE THREAD

**Issue by AliAskari** [crosstool-ng/crosstool-ng#379]
I have been trying to build a cross-compiler to compile on windows for Linux. I've setup Cygwin and installed crosstool-ng from git by following [this](http://crosstool-ng.org/#using_the_latest_development_stuff). I have changed the configurations to match the target specifications but it keeps failing on the binutils step.

The target specs are:
Target Architecture: x86
Bitness: 64 bit
Architecture Level: x86_64
Target OS: LInux
Linux Kernel version: 3.10.98
binutils version: 2.23.2
glibc version: 2.18 (Actually I wanted to have 2.17 but it's not available)
gcc version 4.8.5
gdb version: 7.6.1

The rest are the defaults in the available sample config for x86_64 target system.
[build.txt](https://github.com/crosstool-ng/crosstool-ng/files/222480/build.txt)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/222481/config.txt)

[Custom_build.txt](https://github.com/crosstool-ng/crosstool-ng/files/222485/Custom_build.txt)
[custom_config.txt](https://github.com/crosstool-ng/crosstool-ng/files/222484/custom_config.txt)

**Comment by stilor** [comment]
Would be nice if you pasted the exact .config that was used for the build. From the build log, it looks like you also specified ARCH_SUFFIX as 'x86_64' which resulted in an invalid architecture name 'x86_64x86_64'. If it's the case, leave ARCH_SUFFIX blank (as its help message suggests). Perhaps, config could be made smarter to disallow ARCH_SUFFIX on architectures that do not need it.

**Comment by stilor** [comment]
This configuration builds for me with the changes in https://github.com/crosstool-ng/crosstool-ng/pull/590;  I am also testing older glibc releases and will push once done.

After this is pushed to master, please test and reopen if still fails.
