### ISSUE TITLE
Canadian cross fails with gdb

### ISSUE THREAD

**Issue by AliAskari** [crosstool-ng/crosstool-ng#380]
I'm trying to build a toolchain for windows. This is my current setup:

build  = x86_64-pc-linux-gnu
host   = x86_64-w64-mingw32
target = x86_64-pc-linux-gnu

I tried numerous times to build the toolchain on Windows using Cygwin but it kept failing. That's why I moved to Linux.

I have tried building the default sample `x86_64-w64-mingw32,x86_64-pc-linux-gnu` and it builds fine but it does not have gdb. When I select gdb it fails while building `gettext for host`. I get a bunch of these error:

`libtool:   error: Continuing, but uninstalled executables may not work.`
`[ERROR]    libtool:   error: Could not determine the host path corresponding to`
`[ERROR]    libtool:   error:   '/home/ali/Documents/tc/.build/x86_64-pc-linux-gnu/build/build-gettext-host-x86_64-host_w64-mingw32/gettext-tools/intl/.libs:/home/ali/Documents/tc/.build/`

I also get similar errors when building the sample without adding gdb but somehow it manages to pass these error and finish the whole process. I have also added the build log and configs. 

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/222480/build.txt)
[.config](https://github.com/crosstool-ng/crosstool-ng/files/222481/config.txt)

I also have another problem. My goal is to build the toolchain with the settings mentioned here: https://github.com/crosstool-ng/crosstool-ng/issues/379

When I change the default settings to the desired settings and try to build the toolchain even without gdb it fails with the following errors while building binutils for host

`[ERROR]    /home/ali/Documents/tc/.build/src/binutils-2.23.2/gold/gold-threads.cc:105:68: error: 'pthread_mutextattr_settype' was not declared in this scope`
`[ALL  ]       err = pthread_mutextattr_settype(&attr, PTHREAD_MUTEX_ADAPTIVE_NP);`

These are the config and build log for the desired toolchain

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/222485/Custom_build.txt)
[.config](https://github.com/crosstool-ng/crosstool-ng/files/222484/custom_config.txt)

I would appreciate if some one could help me with either of these problems.

**Comment by mmarb** [comment]
For the first problem, you can try the patch i posted under issue #274.

**Comment by AliAskari** [comment]
@mmarb Thanks for the reply. Yes, the patch solved the issue for the first problem. But I still have the second issue.

After building the toolchain I tried to test it on Windows but I am getting this error:

`libstdc++.so: file not recognized: File format not recognized collect2.exe: error: ld returned 1 exit status`

Why a Linux library is getting called in Windows? Where have I screwed up?

**Comment by stilor** [comment]
The second problem is a typo that went unnoticed for too long in binutils upstream. ct-ng now patches the older binutils releases and newer releases should already have the fix.

Closing, if any of the problems above are still reproducible, please reopen with current .config and build.log.
