### ISSUE TITLE
Building for armv7-a fails in step 'Installing C library headers & start files'

### ISSUE THREAD

**Issue by mickae1** [crosstool-ng/crosstool-ng#384]
Hi,

I have this problem, when I try to create a toolchain for the beaglebone black :

configure:2782: arm-unknown-linux-gnueabihf-gcc     -c
-U_FORTIFY_SOURCE  -mlittle-endian -march=armv7-a   -mtune=cortex-a8
-mhard-float  -O2 armv7-a  conftest.c >&5
arm-unknown-linux-gnueabihf-gcc: error: armv7-a: No such file or directory

[.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/238465/default.config.txt)

**Comment by mickae1** [comment]
the full log : http://www.pastebin.ca/3585871

**Comment by mickae1** [comment]
i need this old glibc because it's the same version used in the beaglebone black

**Comment by mickae1** [comment]
with glibc 2.19 I got the same error :

configure:2725: arm-cortex_a8-linux-gnueabihf-gcc     -V >&5
arm-cortex_a8-linux-gnueabihf-gcc: error: unrecognized command line option '-V'
arm-cortex_a8-linux-gnueabihf-gcc: fatal error: no input files
compilation terminated.
configure:2736: $? = 1
configure:2725: arm-cortex_a8-linux-gnueabihf-gcc     -qversion >&5
arm-cortex_a8-linux-gnueabihf-gcc: error: unrecognized command line option '-qversion'
arm-cortex_a8-linux-gnueabihf-gcc: fatal error: no input files
compilation terminated.

**Comment by enunes** [comment]
You have 
> CT_LIBC_GLIBC_EXTRA_CFLAGS="armv7-a"

in the attached config, that would be a problem, as you should be specifying a valid (dashed) flag there.

You also seem to be using a previous version of crosstool-ng as those component versions in the config are not available anymore in crosstool-ng master, so it would be helpful to specify which version you are on.

The second error also appears to be different than the first one and with different versions, which one is your goal now?
Do you need a cortex-a8 optimized toolchain or any toolchain which will work with a BeagleBone Black ?

**Comment by mickae1** [comment]
Hi,

Finally I moved to debian jessie.

Can you add the gcc 4.9.2 ?

With gcc 4.9.3 the compile work but I would like to have the exact same
version of gcc, is it possible ?

**Comment by stilor** [comment]
@mickae1 We keep tips of each supported branches typically. If you need a specific older release, you can unpack it elsewhere (and if needed, patch/modify as you see fit) and then configure it as a custom location for gcc.
