### ISSUE TITLE
FTP Tarballs not available

### ISSUE THREAD

**Issue by berkutta** [crosstool-ng/crosstool-ng#385]
[DEBUG]    Trying 'ftp://ftp.sunet.se/pub/gnu/gmp/gmp-5.1.3.tar.xz'
[DEBUG]    ==> Executing: 'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/compiler/esp-open-sdk/crosstool-NG/.build/tarballs/gmp-5.1.3.tar.xz.tmp-dl' 'ftp://ftp.sunet.se/pub/gnu/gmp/gmp-5.1.3.tar.xz' 
[ALL  ]    --2016-04-29 10:05:47--  ftp://ftp.sunet.se/pub/gnu/gmp/gmp-5.1.3.tar.xz
[ALL  ]               => '/compiler/esp-open-sdk/crosstool-NG/.build/tarballs/gmp-5.1.3.tar.xz.tmp-dl'
[ALL  ]    Resolving ftp.sunet.se (ftp.sunet.se)... 130.239.18.173, 130.239.18.165, 2001:6b0:e:2018::165, ...
[ALL  ]    Connecting to ftp.sunet.se (ftp.sunet.se)|130.239.18.173|:21... connected.
[ALL  ]    Logging in as anonymous ... Logged in!
[ALL  ]    ==> SYST ... done.    ==> PWD ... done.
[ALL  ]    ==> TYPE I ... done.  ==> CWD (1) /pub/gnu/gmp ... 
[ALL  ]    No such directory 'pub/gnu/gmp'.
[ALL  ]

**Comment by berkutta** [comment]
Was able to build with changing the order of some FTP Hosts in den scripts...

**Comment by bhundven** [comment]
Yea, we need to rework how we handle mirrors.

I will put in a quick fix for gmp and others that use gnu mirrors, but eventually the mirror setup we have needs a better way.

**Comment by stilor** [comment]
Fetchin subsystem reworked and should be more reliable. But if the remote host goes down (or stops mirroring certain project, or changes its directory layout), I don't think there's much we can do.
