### ISSUE TITLE
master branch: glibc 2.13 doesn't exist anymore

### ISSUE THREAD

**Issue by mickae1** [crosstool-ng/crosstool-ng#386]
Hi,
I'm trying to make the toolchain for the beaglebone black ... but the glibc version 2.13 doesn't exist anymore ? why ? Can you put it back ? along with the version of gcc 4.6.3 ?

**Comment by bhundven** [comment]
No. We removed older versions for a reason. Use the 1.22 release.
I plan to release a 1.22.1 release soon, as there are some updates for that branch, but I do not plan to re-add older versions to newer crosstool-ng.

**Comment by mickae1** [comment]
can you add gcc 4.6.3 on the version 1.22 ?

**Comment by mickae1** [comment]
I need your help, with the version 1.22 I got this error :

configure:2744: arm-cortex_a8-linux-gnueabihf-gcc     -V >&5
arm-cortex_a8-linux-gnueabihf-gcc: error: unrecognized option '-V'

what it is it ? how can i fix that ? 

gcc version 4.6.4 (crosstool-NG crosstool-ng-1.22.0)

**Comment by mingwandroid** [comment]
crosstool-ng will not add old versions of GCC, no. It is impractical for us to support a wide version range and makes our scripts both brittle and ugly. To use old compilers, use old crosstool-ngs.

There shouldn't be many reasons to need to do this, unless you are trying to build unsupported or legacy software. Often a modern GCC will work fine despite what some old build instructions say.

Your configure error isn't a fatal error and is completely normal. If configure failed for you then it failed for a different reason. You should upload your full log somewhere, such as a github gist and put a link to it here if you want more assistance.

**Comment by mickae1** [comment]
Ok, I moved to debian  jessie in my device.

Now I've gcc 4.9.2 , is it possible to add suport of this gcc ?

Le lun. 2 mai 2016 à 12:28, Ray Donnelly <notifications@github.com> a
écrit :
