### ISSUE TITLE
populate command not working

### ISSUE THREAD

**Issue by pankajbansal3073** [crosstool-ng/crosstool-ng#394]
hi,

when i build cross-toolchain for arm or arm64 targets (like arm-unknown-linux-gnueabi, aarch64-unknown-linux-gnueabi) and then try to use populate command, i get this error

pankaj@pankaj-desktop:~/Desktop/x-tools/arm-unknown-linux-gnueabi/bin$ ./arm-unknown-linux-gnueabi-populate -v -s ~/Desktop/temp1 -d ~/Desktop/temp2
./arm-unknown-linux-gnueabi-populate: 153: ./arm-unknown-linux-gnueabi-populate: @@CT_awk@@: not found

Thanks & Regards,
Pankaj Bansal

**Comment by jmlemetayer** [comment]
Should be closed as the fix has been merged

**Comment by pankajbansal3073** [comment]
Fixed with commit https://github.com/crosstool-ng/crosstool-ng/commit/11cb2ddd43fd1ff493f4b7cd63f1cf654294165f . Thanks
