### ISSUE TITLE
crosstool-ng-1.22.0.tar.bz2 extracted does not include version suffix

### ISSUE THREAD

**Issue by lundmar** [crosstool-ng/crosstool-ng#398]
I just noticed that the latest release tarball extracted does not include the version suffix in the top level directory.

That is, what should have been crosstool-ng-1.22.0/ is simply crosstool-ng/

I assume this is a mistake?

**Comment by KirillSmirnov** [comment]
I vote for fixing this bug, at least in the next release. It broke our build scripts, sad :-(

**Comment by stilor** [comment]
Added create-release.sh for releasing in a consistent matter. It creates version suffix just fine.
