### ISSUE TITLE
Unable to build Gcc 4.9.3 with Gcc 6.1.1

### ISSUE THREAD

**Issue by ClaymorePT** [crosstool-ng/crosstool-ng#400]
I'm unable to build gcc 4.9.3, using Gcc 6.1.1 due to this error:

`
[INFO ]  Installing final gcc compiler
[ERROR]    cfns.gperf:101:1: error: 'const char\* libc_name_p(const char_, unsigned int)' redeclared inline with 'gnu_inline' attribute
[ERROR]    make[3]: *_\* [cp/except.o] Error 1
[ERROR]    make[2]: **\* [all-gcc] Error 2
[ERROR]    make[1]: **\* [all] Error 2
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@922]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@648]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@652]
[ERROR]  >>

`

This issue is also reported and solved here: https://github.com/jcmvbkbc/crosstool-NG/issues/24

**Comment by peer23peer** [comment]
same here

Running:

Linux up] 4.6.3-1-ARCH #1 SMP PREEMPT Fri Jun 24 21:19:13 CEST 2016 x86_64 GNU/Linux

with GCC 6.1.1 20160707

**Comment by falkTX** [comment]
can we get some attention to this bug please?
fix seems pretty easy, just copy the file into patches/gcc/4.8.5/ folder..

**Comment by dax79** [comment]
Same problem for me on archlinux 64 bit machine: i'm not able to build an arm toolchain
```
[INFO ]  Installing final gcc compiler
[ERROR]    cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute
[ERROR]    make[3]: *** [Makefile:1065: cp/except.o] Error 1
[ERROR]    make[2]: *** [Makefile:4118: all-gcc] Error 2
[ERROR]    make[1]: *** [Makefile:874: all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@944]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@663]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 47:59.39)
[47:59] / make: *** [/home/davide/toolchains/raspberry/bin/ct-ng:152: build] Error 2
```

**Comment by stilor** [comment]
4.9.3 is no longer on master (4.9.4 is, and it already has that fix upstream).
Backported to 4.8.5 (the only currently supported release without this fix) by PR 495.
