### ISSUE TITLE
SH : newlib fails to compile

### ISSUE THREAD

**Issue by fenugrec** [crosstool-ng/crosstool-ng#401]
Trying to compile a toolchain for baremetal SH with newlib.

Here's the .config :
http://pastebin.ca/3616861

compiling newlib fails : some of the errors are

```
[ALL  ]    *** Newlib does not support CPU sh3eb
....
[ERROR]    make[2]: *** [configure-target-newlib] Error 1
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_libc[scripts/build/libc/newlib.sh@128]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@652]
```

I think the " Newlib does not support CPU sh3eb" message is generated in newlib/newlib/configure.host  , which is confusing because the variable "host_cpu" is set to "sh3eb" (different definition for "host", I guess ?)

The build.log is pretty huge (3.8MB) I will have to upload it somewhere, if required.
Any ideas ?

**Comment by fenugrec** [comment]
Very minor update, it seems that newlib handles SH slightly differently than, say, ARM.
in `newlib/configure.host`, there's this bit:
```bash
case "${host_cpu}" in
#snip
  arm*)
	machine_dir=arm
	libm_machine_dir=arm
	;;
#snip
  sh | sh64)
	machine_dir=sh
	;;
```
so, "arm*" has a wildcard to match possible variants, but SH doesn't. So, do we patch newlib, or tweak ct-ng to call newlib with adjusted arguments when the target is SH ?

**Comment by lundmar** [comment]
Yeah - wildcard seems to fix the build.

https://github.com/lundmar/crosstool-ng/commit/8391e763d767db2ef4965aad97dfa5a2ac9f9757 builds fine for latest newlib version in combination with sh4. I expect sh3 will do so also.

However, I don't have any hw to verify runtime behaviour.

**Comment by bhundven** [comment]
@lundmar Do you know anyone with this hw that can test?

**Comment by fenugrec** [comment]
I do (SH7055 car ECU), I could run some simple tests.

**Comment by stilor** [comment]
Crosstool-NG now offers "unspecified" as SH architecture level - this should be sufficient for building newlib. Let me know if this setting should be forced for newlib (e.g. by converting a setting of "sh4" into "sh" + "--with-cpu=sh4" when building a newlib configuration).

**Comment by fenugrec** [comment]
Hi, just retried today with the sample sh-unknown-elf.config but enabling only big-endian instead of both; this time it's binutils complaining about "sheb-unknown-elf" :

```[trimmed a few similar lines]
[ALL  ]    checking whether strnlen is declared... yes
[ALL  ]    checking linker --as-needed support... yes
[ALL  ]    checking for cos in -lm... yes
[ALL  ]    *** BFD does not support target sheb-unknown-elf.
[ALL  ]    *** Look in bfd/config.bfd for supported targets.
[ERROR]    make[2]: *** [Makefile:2641: configure-bfd] Error 1
[ALL  ]    make[2]: Leaving directory '~/ctng/.build/sheb-unknown-elf/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[ERROR]    make[1]: *** [Makefile:849: all] Error 2
[ALL  ]    make[1]: Leaving directory '~/ctng/.build/sheb-unknown-elf/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
```
Closely related to the initial issue, but I can file a new one if preferable.
