### ISSUE TITLE
cross tool build gcc multilib fails on Ubuntu 14.04

### ISSUE THREAD

**Issue by SanfordWen** [crosstool-ng/crosstool-ng#408]
I was building gcc multilib on Ubuntu 14.04 with cross tool 1.22,but it failed.
The following is the error message:
[ALL  ]    objects="unwind-dw2.o unwind-dw2-fde-dip.o unwind-sjlj.o unwind-c.o emutls.o";						if test -z "$objects"; then					  echo 'int __libgcc_eh_dummy;' > eh_dummy.c;			  /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/./gcc/ -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/lib/ -isystem /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/include -isystem /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/sys-include    -g -Os -O2  -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -mlong-double-80 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -mlong-double-80 -I. -I. -I../.././gcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/. -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../gcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../include -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS  -DUSE_TLS -fvisibility=hidden -DHIDE_EXPORTS -c eh_dummy.c			     -o eh_dummy.o;					  objects=eh_dummy.o;					fi;								/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ar  rc libgcc_eh.a $objects
[ALL  ]    objects="_gcov_merge_add.o _gcov_merge_single.o _gcov_merge_delta.o _gcov_merge_ior.o _gcov_merge_time_profile.o _gcov_merge_icall_topn.o _gcov_interval_profiler.o _gcov_pow2_profiler.o _gcov_one_value_profiler.o _gcov_indirect_call_profiler.o _gcov_average_profiler.o _gcov_ior_profiler.o _gcov_indirect_call_profiler_v2.o _gcov_time_profiler.o _gcov_indirect_call_topn_profiler.o _gcov_dump.o _gcov_flush.o _gcov_fork.o _gcov_execl.o _gcov_execlp.o _gcov_execle.o _gcov_execv.o _gcov_execvp.o _gcov_execve.o _gcov_reset.o _gcov.o";						if test -z "$objects"; then					  echo 'int __libgcc_eh_dummy;' > eh_dummy.c;			  /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/./gcc/ -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/lib/ -isystem /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/include -isystem /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/sys-include    -g -Os -O2  -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -mlong-double-80 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -mlong-double-80 -I. -I. -I../.././gcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/. -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../gcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../include -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS  -DUSE_TLS -fvisibility=hidden -DHIDE_EXPORTS -c eh_dummy.c			     -o eh_dummy.o;					  objects=eh_dummy.o;					fi;								/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ar  rc libgcov.a $objects
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ranlib libgcc_eh.a
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ranlib libgcov.a
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ld.bfd: skipping incompatible /home/wen/x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot/usr/lib/../lib32/libc.so when searching for -lc
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ld.bfd: skipping incompatible /home/wen/x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot/usr/lib/libc.so when searching for -lc
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ld.bfd: skipping incompatible /home/wen/x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot/usr/lib32/libc.so when searching for -lc
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ld.bfd: skipping incompatible /home/wen/x-tools/x86_64-unknown-linux-gnu/x86_64-unknown-linux-gnu/sysroot/usr/lib/libc.so when searching for -lc
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ld.bfd: cannot find -lc
[ALL  ]    # Early copyback; see "all" above for the rationale.  The
[ALL  ]    # early copy is necessary so that the gcc -B options find
[ALL  ]    # the right startup files when linking shared libgcc.
[ALL  ]    /bin/bash /work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../mkinstalldirs ../.././gcc
[ALL  ]    parts="crtbegin.o crtbeginS.o crtbeginT.o crtend.o crtendS.o crtprec32.o crtprec64.o crtprec80.o crtfastmath.o";						for file in $parts; do						  rm -f ../.././gcc/$file;			  /work/toolchain/x86/.build/tools/bin/install -c -m 644 $file ../.././gcc/;		  case $file in 						    *.a)							      /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ranlib ../.././gcc/$file ;;		  esac;								done
[ALL  ]    rm -f libgcc.a
[ALL  ]    objects="_muldi3.o _negdi2.o _lshrdi3.o _ashldi3.o _ashrdi3.o _cmpdi2.o _ucmpdi2.o _clear_cache.o _trampoline.o __main.o _absvsi2.o _absvdi2.o _addvsi3.o _addvdi3.o _subvsi3.o _subvdi3.o _mulvsi3.o _mulvdi3.o _negvsi2.o _negvdi2.o _ctors.o _ffssi2.o _ffsdi2.o _clz.o _clzsi2.o _clzdi2.o _ctzsi2.o _ctzdi2.o _popcount_tab.o _popcountsi2.o _popcountdi2.o _paritysi2.o _paritydi2.o _powisf2.o _powidf2.o _powixf2.o _mulsc3.o _muldc3.o _mulxc3.o _divsc3.o _divdc3.o _divxc3.o _bswapsi2.o _bswapdi2.o _clrsbsi2.o _clrsbdi2.o _fixunssfsi.o _fixunsdfsi.o _fixunsxfsi.o _fixsfdi.o _fixdfdi.o _fixxfdi.o _fixunssfdi.o _fixunsdfdi.o _fixunsxfdi.o _floatdisf.o _floatdidf.o _floatdixf.o _floatundisf.o _floatundidf.o _floatundixf.o _eprintf.o __gcc_bcmp.o _divdi3.o _moddi3.o _udivdi3.o _umoddi3.o _udiv_w_sdiv.o _udivmoddi4.o bid_decimal_globals.o bid_decimal_data.o bid_binarydecimal.o bid_convert_data.o _isinfd32.o _isinfd64.o _isinfd128.o bid64_noncomp.o bid128_noncomp.o bid128_fma.o bid_round.o bid_from_int.o bid64_add.o bid128_add.o bid64_div.o bid128_div.o bid64_mul.o bid128_mul.o bid64_compare.o bid128_compare.o bid128.o bid32_to_bid64.o bid32_to_bid128.o bid64_to_bid128.o bid64_to_int32.o bid64_to_int64.o bid64_to_uint32.o bid64_to_uint64.o bid128_to_int32.o bid128_to_int64.o bid128_to_uint32.o bid128_to_uint64.o _addsub_sd.o _div_sd.o _mul_sd.o _eq_sd.o _ne_sd.o _lt_sd.o _gt_sd.o _le_sd.o _ge_sd.o _sd_to_si.o _sd_to_di.o _sd_to_usi.o _sd_to_udi.o _si_to_sd.o _di_to_sd.o _usi_to_sd.o _udi_to_sd.o _sd_to_sf.o _sd_to_df.o _sd_to_xf.o _sd_to_tf.o _sf_to_sd.o _df_to_sd.o _xf_to_sd.o _tf_to_sd.o _sd_to_dd.o _sd_to_td.o _unord_sd.o _addsub_dd.o _div_dd.o _mul_dd.o _eq_dd.o _ne_dd.o _lt_dd.o _gt_dd.o _le_dd.o _ge_dd.o _dd_to_si.o _dd_to_di.o _dd_to_usi.o _dd_to_udi.o _si_to_dd.o _di_to_dd.o _usi_to_dd.o _udi_to_dd.o _dd_to_sf.o _dd_to_df.o _dd_to_xf.o _dd_to_tf.o _sf_to_dd.o _df_to_dd.o _xf_to_dd.o _tf_to_dd.o _dd_to_sd.o _dd_to_td.o _unord_dd.o _addsub_td.o _div_td.o _mul_td.o _eq_td.o _ne_td.o _lt_td.o _gt_td.o _le_td.o _ge_td.o _td_to_si.o _td_to_di.o _td_to_usi.o _td_to_udi.o _si_to_td.o _di_to_td.o _usi_to_td.o _udi_to_td.o _td_to_sf.o _td_to_df.o _td_to_xf.o _td_to_tf.o _sf_to_td.o _df_to_td.o _xf_to_td.o _tf_to_td.o _td_to_sd.o _td_to_dd.o _unord_td.o cpuinfo.o sfp-exceptions.o addtf3.o divtf3.o multf3.o negtf2.o subtf3.o unordtf2.o fixtfsi.o fixunstfsi.o floatsitf.o floatunsitf.o fixtfdi.o fixunstfdi.o floatditf.o floatunditf.o fixtfti.o fixunstfti.o floattitf.o floatuntitf.o extendsftf2.o extenddftf2.o extendxftf2.o trunctfsf2.o trunctfdf2.o trunctfxf2.o getf2.o letf2.o eqtf2.o _divtc3.o _multc3.o _powitf2.o enable-execute-stack.o generic-morestack.o generic-morestack-thread.o morestack.o";						if test -z "$objects"; then					  echo 'int __libgcc_eh_dummy;' > eh_dummy.c;			  /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/./gcc/ -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ -B/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/lib/ -isystem /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/include -isystem /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/sys-include    -g -Os -O2  -DIN_GCC  -DCROSS_DIRECTORY_STRUCTURE  -W -Wall -Wno-narrowing -Wwrite-strings -Wcast-qual -Wstrict-prototypes -Wmissing-prototypes -Wold-style-definition  -isystem ./include   -fpic -mlong-double-80 -g -DIN_LIBGCC2 -fbuilding-libgcc -fno-stack-protector   -fpic -mlong-double-80 -I. -I. -I../.././gcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/. -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../gcc -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/../include -I/work/toolchain/x86/.build/src/gcc-5.3.0/libgcc/config/libbid -DENABLE_DECIMAL_BID_FORMAT -DHAVE_CC_TLS  -DUSE_TLS -fvisibility=hidden -DHIDE_EXPORTS -c eh_dummy.c			     -o eh_dummy.o;					  objects=eh_dummy.o;					fi;								/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ar  rc libgcc.a $objects
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]    make[4]: *** [libgcc_s.so] Error 1
[ALL  ]    make[4]: Leaving directory `/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/x86_64-unknown-linux-gnu/32/libgcc'
[ERROR]    make[3]: *** [multi-do] Error 1
[ALL  ]    make[3]: Leaving directory `/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/x86_64-unknown-linux-gnu/libgcc'
[ERROR]    make[2]: *** [all-multi] Error 2
[ALL  ]    make[2]: *** Waiting for unfinished jobs....
[ALL  ]    /work/toolchain/x86/.build/x86_64-unknown-linux-gnu/buildtools/x86_64-unknown-linux-gnu/bin/ranlib libgcc.a
[ALL  ]    make[2]: Leaving directory `/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2/x86_64-unknown-linux-gnu/libgcc'
[ERROR]    make[1]: *** [all-target-libgcc] Error 2
[ALL  ]    make[1]: Leaving directory `/work/toolchain/x86/.build/x86_64-unknown-linux-gnu/build/build-cc-gcc-core-pass-2'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-2 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@533]
[ERROR]  >>        called from: do_gcc_core_pass_2[scripts/build/cc/100-gcc.sh@154]
[ERROR]  >>        called from: do_cc_core_pass_2[scripts/build/cc.sh@42]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@652]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-159-g6e7c616/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: [16:24.87)](

I opened CT_MULTILIB and set CT_CC_GCC_MULTILIB_LIST to "m64,m32",are there anything I miss?

**Comment by bhundven** [comment]
Multilib support is not fully in crosstool-ng.
See: #383
