### ISSUE TITLE
Multilib does not (really) enable -m64 for SPARC

### ISSUE THREAD

**Issue by stefanct** [crosstool-ng/crosstool-ng#41]
I have used the multilib option to build a mips gcc that does all kinds of binaries as expected (at least it does not complain when doing any combination of little endian, big endian and 32b, 64b), yay! Trying the same for SPARC fails though. It compiles and installs without errors but it fails at compiling a trivial example when using `-m64`:

    $ sparc-unknown-linux-gnu-gcc -m64 .test.c 
    .test.c:1:0: error: -m64 is not supported by this configuration
    int main(int argc, char **argv)
    ^
    .test.c:1:0: error: -mlong-double-64 not allowed with -m64

Calling gcc without an actual c file does not show that error:

    $ sparc-unknown-linux-gnu-gcc -m64
    sparc-unknown-linux-gnu-gcc: fatal error: no input files compilation terminated.

The following seems interesting in this context:

    $ /opt/cross/sparc-unknown-linux-gnu/libexec/gcc/sparc-unknown-linux-gnu/4.9.2/cc1 --help | grep 64
      -m64                        		[disabled]
      -mlong-double-64            		[enabled]
      -mptr64                     		[disabled]

The most important config flags are:

    CT_ARCH="sparc"
    CT_ARCH_SUPPORTS_32=y
    CT_ARCH_SUPPORTS_64=y
    CT_ARCH_SUPPORTS_WITH_CPU=y
    CT_ARCH_SUPPORTS_WITH_TUNE=y
    CT_ARCH_SUPPORTS_WITH_FLOAT=y
    CT_ARCH_DEFAULT_32=y
    CT_ARCH_CPU=""
    CT_ARCH_TUNE=""
    CT_ARCH_32=y
    # CT_ARCH_64 is not set
    CT_ARCH_BITNESS=32
    CT_TARGET_CFLAGS=""
    CT_TARGET_LDFLAGS=""
    CT_ARCH_sparc=y
    CT_MULTILIB=y
    CT_ARCH_FLOAT_AUTO=y
    CT_ARCH_FLOAT="auto"

    CT_CROSS=y

    CT_BINUTILS_LINARO_V_2_25=y
    CT_LIBC_GLIBC_LINARO_V_2_20=y
    CT_CC_V_4_9_2=y

I am happy to supply more information if need be... I just don't know what :)

**Comment by stefanct** [comment]
@bhundven Sure, thank you! Before that I want to tell you another bit though. To test further I tried to build a multilib sparc gcc defaulting to 64bit. Unlike the 32bit default build this fails with incompatible libraries: https://gist.github.com/stefanct/001475efa87ece6d8de5
Here is the respective config: https://gist.github.com/stefanct/692b8d3a06fc0a4925b8

As you requested here is also the 32b multilib .config: https://gist.github.com/stefanct/e0b4d4fa9a8c0d0a750d
Let me know if you need anything else!

**Comment by bhundven** [comment]
@stefanct Great!
When I get off work, I'll start up a build and see what I can find.

**Comment by stefanct** [comment]
And a 64bit-only sparc gcc fails even earlier...

	[ALL  ]    sparc64-unknown-linux-gnu-gcc     ../sysdeps/sparc/sparc64/soft-fp/qp_mul.c -c -std=gnu99 -fgnu89-inline  -O2 -U_FORTIFY_SOURCE -Wall -Winline -Wundef -Wwrite-strings -fmerge-all-constants -frounding-math -Wstrict-prototypes -fcall-used-g6         -I../include -I/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/soft-fp  -I/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final  -I../sysdeps/unix/sysv/linux/sparc/sparc64  -I../sysdeps/unix/sysv/linux/wordsize-64  -I../sysdeps/unix/sysv/linux/sparc  -I../sysdeps/sparc/nptl  -I../sysdeps/unix/sysv/linux  -I../sysdeps/nptl  -I../sysdeps/pthread  -I../sysdeps/gnu  -I../sysdeps/unix/inet  -I../sysdeps/unix/sysv  -I../sysdeps/unix  -I../sysdeps/posix  -I../sysdeps/sparc/sparc64/fpu/multiarch  -I../sysdeps/sparc/sparc64/fpu  -I../sysdeps/sparc/sparc64/multiarch  -I../sysdeps/sparc/sparc64  -I../sysdeps/wordsize-64  -I../sysdeps/ieee754/ldbl-128  -I../sysdeps/ieee754/dbl-64/wordsize-64  -I../sysdeps/ieee754/dbl-64  -I../sysdeps/ieee754/flt-32  -I../sysdeps/sparc/sparc64/soft-fp  -I../sysdeps/sparc/fpu  -I../sysdeps/sparc  -I../sysdeps/ieee754  -I../sysdeps/generic  -I.. -I../libio -I. -nostdinc -isystem /home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/buildtools/lib/gcc/sparc64-unknown-linux-gnu/4.9.2/include -isystem /home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/buildtools/lib/gcc/sparc64-unknown-linux-gnu/4.9.2/include-fixed -isystem /opt/cross/sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/sysroot/usr/include  -D_LIBC_REENTRANT -include ../include/libc-symbols.h       -o /home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/soft-fp/qp_mul.o -MD -MP -MF /home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/soft-fp/qp_mul.o.dt -MT /home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/soft-fp/qp_mul.o
	[ALL  ]    /tmp/ccDScnVt.s: Assembler messages:
	[ALL  ]    /tmp/ccDScnVt.s:60: Error: Architecture mismatch on "fzero".
	[ALL  ]    /tmp/ccDScnVt.s:60:  (Requires v9a|v9b; requested architecture is v9.)
	[ALL  ]    /home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/sysd-rules:2163: recipe for target '/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/soft-fp/qp_itoq.o' failed
	[ERROR]    gmake[3]: *** [/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final/soft-fp/qp_itoq.o] Error 1
	[ALL  ]    gmake[3]: *** Waiting for unfinished jobs....
	[ALL  ]    gmake[3]: Leaving directory '/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/src/glibc-linaro-2.20-2014.11/soft-fp'
	[ALL  ]    Makefile:213: recipe for target 'soft-fp/subdir_lib' failed
	[ERROR]    gmake[2]: *** [soft-fp/subdir_lib] Error 2
	[ALL  ]    gmake[2]: Leaving directory '/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/src/glibc-linaro-2.20-2014.11'
	[ALL  ]    Makefile:9: recipe for target 'all' failed
	[ERROR]    gmake[1]: *** [all] Error 2
	[ALL  ]    gmake[1]: Leaving directory '/home/flashrom/download/gcc/build-sparc64-unknown-linux-gnu/sparc64-unknown-linux-gnu/build/build-libc-final'
	[ERROR]  
	[ERROR]  >>
	[ERROR]  >>  Build failed in step 'Installing C library'
	[ERROR]  >>        called in step '(top-level)'
	[ERROR]  >>
	[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
	[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc-eglibc.sh-common@458]
	[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc-eglibc.sh-common@149]
	[ERROR]  >>        called from: do_libc[scripts/build/libc/glibc-eglibc.sh-common@71]
	[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@638]

**Comment by bhundven** [comment]
@stefanct I was just reminded by mingwandroid on irc that we still haven't merged the multilib patches he and I were working on *last year*. https://github.com/diorcety/crosstool-ng/commits/multilib
Try that branch out.

**Comment by bhundven** [comment]
Multilib will be coming in 1.23.0. I'm changing the milestone to reflect that.

**Comment by bhundven** [comment]
I am now tracking this issue in #218, and will be closing this bug out.
The target milestone is still 1.23.0.
