### ISSUE TITLE
Download of gcc-linaro-5.2-2015.11-2 fails

### ISSUE THREAD

**Issue by rmast** [crosstool-ng/crosstool-ng#421]
All download locations pointing to gcc-linaro-5.2-2015.11-2 fail.
I didn't get it working by altering 100-gcc.sh. Is that cached somewhere?

Finally I just downloaded the needed tarball to .build/tarballs and then it worked

https://releases.linaro.org/components/toolchain/gcc-linaro/5.2-2015.11-2/gcc-linaro-5.2-2015.11-2.tar.xz

**Comment by KirillSmirnov** [comment]
Please try the latest crosstool-ng snapshot. Release 1.22.0 ships with obsolete gcc-linaro download locations.
Fixed in cset: 7c7bcecd2e3bc61f122c9e1ee9fad8105b33ccc9

**Comment by stilor** [comment]
Linaro changed the URLs again. Another fix on master... Anyway, I don't see 1.22 patchlevel release coming, so closing this.
