### ISSUE TITLE
Crosstool fails to use CT_BUILD_PREFIX and CT_BUILD_SUFFIX options

### ISSUE THREAD

**Issue by andyg1001** [crosstool-ng/crosstool-ng#430]
This looks like a straight-forward copy-and-paste bug in crosstool-NG.sh.in.

The issue is that a standard cross-compile build (as opposed to a canadian-cross build) runs through the "Making build system tools available" section twice, first using "BUILD" and then using "HOST", but since you cannot specify the "HOST" prefix/suffix variants in the configuration unless doing a canadian-cross the script simply overrides the custom (correct) prefix/suffix tools of the first pass with the system default (wrong) tools in the second pass.

My suggestion would be to change [scripts/crosstool-NG.sh.in, line 348](https://github.com/crosstool-ng/crosstool-ng/blob/master/scripts/crosstool-NG.sh.in#L348) to

`install_build_tools_for="BUILD"`

alone.  This seems to solve the problem, at least for me.

**Comment by bhundven** [comment]
@andyg1001 Good catch. I'm going to let travis-ci do it's thing. Hoping that this brings build times down a bit, too! :)
