### ISSUE TITLE
Confusing tuple suffix: *-uclibcgnueabi

### ISSUE THREAD

**Issue by KirillSmirnov** [crosstool-ng/crosstool-ng#434]
Toolchain for arm/linux/uclibc is called *-uclibcgnueabi, which looks strange to me. Is this naming a standard or a bug? I believe it should be called *-uclibceabi instead (without 'gnu' in the middle). Toolchain arm-unknown-linux-uclibceabi (gcc-4.9.3, uclibc-1.0.9, binutils-2.22) is successfully built and works without any noticable glitch.

If it is really a bug I'm ready to PR corresponding changes.

**Comment by bhundven** [comment]
You might be right. I need to research this a bit more, but looking at `config.sub` (http://git.savannah.gnu.org/gitweb/?p=config.git;a=blob_plain;f=config.sub;hb=HEAD) the match is:

```
linux-uclibc* | uclinux-uclibc*
```

So I would have to check through each projects autoconf to see if anyone is being picky about the actual name. Might also want to seach 'gnueabi' to see if that is the reason we did that.

If you make a patch with uclibceabi, does that work as expected?

**Comment by KirillSmirnov** [comment]
Yes, uclibceabi variant works like a charm for me, I successfully built full rootfs with ptxdist project.

The problem is, that different projects prefers different suffixes. I'm lost :-(

1) buildroot prefers -uclibcgnueabi:
https://git.busybox.net/buildroot/commit/?id=ece1f4225ce2af0a274943753d9c2e7ced5d3262&context=6
2) openembedded prefers -uclibceabi
http://lists.openembedded.org/pipermail/openembedded-devel/2009-September/058773.html
3) busybox tries to support both:
http://lists.busybox.net/pipermail/buildroot/2014-November/112065.html
4) pengutronix (the tool I use) does not care at all

Just in case the patch:
[no-uclibcgnueabi.patch.gz](https://github.com/crosstool-ng/crosstool-ng/files/488322/no-uclibcgnueabi.patch.gz)

.

**Comment by stilor** [comment]
Hope https://github.com/crosstool-ng/crosstool-ng/pull/587 settles it :)

**Comment by KirillSmirnov** [comment]
> Hope #587 settles it :)
It does :-)

Thanks!
