### ISSUE TITLE
404 not found when build arm compiler on raspberry pi

### ISSUE THREAD

**Issue by burstinair** [crosstool-ng/crosstool-ng#453]
--2016-09-18 19:02:31-- https://www.kernel.org/pub/linux/kernel/v4.x/longterm/linux-4.3
[ALL ] Connecting to www.kernel.org (www.kernel.org)|149.20.4.69|:443... connected.
[ALL ] HTTP request sent, awaiting response... 404 Not Found
[ALL ] 2016-09-18 19:02:31 ERROR 404: Not Found.
[ALL ]

[DEBUG] Not at this location: "http://www.kernel.org/pub/linux/kernel/v4.x/longterm/linux-4.3"

**Comment by KirillSmirnov** [comment]
Please attach full build.log.

**Comment by bhundven** [comment]
@burstinair without full logs, we cannot debug this issue. I've had no issues downloading this kernel version or any other kernel version. Please re-open this issue if it persists, and provide the build.log.
