### ISSUE TITLE
Not at this location: "ftp://gcc.gnu.org/pub/gcc/infrastructure/cloog-0.18.4"

### ISSUE THREAD

**Issue by burstinair** [crosstool-ng/crosstool-ng#456]
sorry for the previous post

this is my 
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/495883/build.log.txt)

i try to build ctng on centos 6.7 to compile something run on raspberry pi 3.

when i build the compiler with default C compiler config (gcc 5.2.0), it works fine
but the problem occurs when i change gcc compiler version to linaro-4.9-2015.06

thanks for your help

**Comment by KirillSmirnov** [comment]
Looks like a temporarily network problem with the site hosting cloog.

**Comment by stilor** [comment]
Indeed.
