### ISSUE TITLE
Missing configure script

### ISSUE THREAD

**Issue by leoheck** [crosstool-ng/crosstool-ng#463]
Autoconf output (config script) should be added to the repository

In README:

> > Now you can unpack and install crosstool-NG:
> > 
> > ```
> > tar xjf crosstool-ng-VERSION.tar.bz2
> > cd crosstool-ng-VERSION
> > ./configure --prefix=/some/place
> > make
> > make install
> > export PATH="${PATH}:/some/place/bin"
> > ```

**Comment by oxoocoffee** [comment]
I think the part that is missing is 
cd crosstool-ng-VERSION
./bootstrap         <- This will generate configure script if you have autoconf installed
./configure --prefix=/some/place

**Comment by leoheck** [comment]
Look, http://stackoverflow.com/questions/3290908/which-files-generated-by-autotools-should-i-keep-in-version-control-repository

Actually, you have to commit the ```configure``` script **OR** add the instruction to (re)generate it. The instructions don't have the command that genarate the ```configure``` and it isn't in the repository.

**Comment by bhundven** [comment]
No, that is done during the release process.

**Comment by bhundven** [comment]
This is not a problem, just an educational mis-understanding.
Closing.

**Comment by leoheck** [comment]
@bhundven Actually you didn't understand what I wanted to say.


The README.md has:
![screenshot from 2016-11-07 21-20-30](https://cloud.githubusercontent.com/assets/1277920/20080288/091363a4-a530-11e6-93e4-42b10465b00a.png)

There is no ``configure`` script in the repository, so please update the instructions to have the line that generated this script.

**Comment by bhundven** [comment]
@leoheck No. I totally got what you said. If you read the instructions, there are one set of instructions for downloading the RELEASE tarball (Using a released version) and another set of instructions for building from git (Using the latest development stuff). You are following the release tarball instructions for git. You are not reading the instructions correctly.

**Comment by leoheck** [comment]
Ok, I then I agree. Thank you @bhundven

**Comment by theronic** [comment]
Got bit by this - crosstool-ng master is missing configure script after running bootstrap. There is a configure.ac script - what do I do with that?
