### ISSUE TITLE
configure option to skip documentation

### ISSUE THREAD

**Issue by karlp** [crosstool-ng/crosstool-ng#464]
the documentation pulls in a pile of dependencies and build time that are rarely even used.  It would be _super_ if you could provide a configure argument to disable them.  like --without-doc or similar.  This should be tied to the AC_CHECK_PROGS macros to stop forcing makeinfo and help2man to be installed.

**Comment by karlp** [comment]
And no, the "CT_BUILD_MANUAL" option isn't enough, because that only seems to kick in _after_ things like newlib docs have already been built, and only applies to converting mans to pdfs and htmls.

**Comment by stilor** [comment]
crosstool-ng is just the glue putting together multiple packages that constitute a toolchain. It won't be possible to implement that behavior without the support for it in all the packages crosstool-ng includes. For example, I don't see a relevant option in GCC's configure script that will prevent makeinfo/pod2man runs.

To some extent, we might be able to trick packages into believing the makeinfo/pod2man are too old. But as far as I see, at least binutiles uses makeinfo unconditionally, without verifying its version.

We can also provide dummy makeinfo/pod2man that won't do anything (i.e. will just create empty files as output)...

Overall, though, I am not sure it is worth the trouble. I doubt the combined time for all makeinfo runs during a single build exceeds a minute - while the rest of the tasks take 20..120 minutes. The benefit, IMO, is negligible.

**Comment by stilor** [comment]
Unless a [maintainable] patch comes in, I don't think this issue is worth the effort.
