### ISSUE TITLE
cross-gdb fails on Mac Sierra

### ISSUE THREAD

**Issue by oxoocoffee** [crosstool-ng/crosstool-ng#469]
Hello,

I am trying to build arm-cortexa9_neon-linux-gnueabihf on Mac OSX Sierra with latest command line tools. So I did checked out master and I was able to build and install crosstool-ng just fine.
After creating config file and running build all did build fine until I got to cross-gdb.

To get to this point I had to first change crosstool-NG.sh and replace -static with -Bstatic.

Then I was able to build all the way to cross-gdb. I am attaching my config file.
The error I got is this

`[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.10.1/libiberty/fibheap.c:220:30: error: use of undeclared identifier 'LONG_MIN'
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.10.1/libiberty/fibheap.c:261:36: error: use of undeclared identifier 'LONG_MIN'
[ERROR]    make[3]: *** [fibheap.o] Error 1
[ERROR]    checking whether build environment is sane... make[2]: *** [all-libiberty] Error 2
[ERROR]    make[1]: *** [all] Error 2
[ERROR]`

Here is top of fib heap.c

`#ifdef HAVE_CONFIG_H`
`#include "config.h"`
`#endif`
`#ifdef HAVE_LIMITS_H`
`#include <limits.h>`
`#endif`
`#ifdef HAVE_STDLIB_H`
`#include <stdlib.h>`
` #endif`
` #ifdef HAVE_STRING_H`
 `#include <string.h>`

I also see this

`215729 [CFG  ]    checking whether <limits.h> defines MIN and MAX... no`
`215730 [CFG  ]    checking whether <sys/param.h> defines MIN and MAX... yes`

Also I am attaching config.log from /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-gdb-cross/

My questions is there a way to add option to just see preprocessor running? My feeling it is picking up wrong file?

[config.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/570471/config.log.zip)

[config.limits.zip](https://github.com/crosstool-ng/crosstool-ng/files/570458/config.limits.zip)

**Comment by KirillSmirnov** [comment]
Hi Robert,

Limits are a pain :-( Please try an attached patch to gdb whether it fixes the problem. The patch uses the same hack as in strtol.c file in the same directory.

[gdb-hack-long-min.patch.zip](https://github.com/crosstool-ng/crosstool-ng/files/572669/gdb-hack-long-min.patch.zip)

**Comment by oxoocoffee** [comment]
Hi Kirill,

Should I have this patch to /opt/local/lib/crosstool-ng-1.22.0-248-gdf5a341/patches/gdb/7.10.1/113-gdb-hack-long-min.patch?

Or untar, patch, tar local tarball that ng would pick up on rebuild?

I am doing it now.

**Comment by KirillSmirnov** [comment]
I'd prefer the first way. But right now everything goes, since we're testing a patch.

**Comment by KirillSmirnov** [comment]
Please, attach full build.log. I cannot understand one thing :-(
We are testing libiberty library shipped with gdb. But the same library is shipped and used in gcc and binutils too! How come that gcc and binutils both are successfully built, but only gdb failed? That's very strange, build.log will clarify.

**Comment by oxoocoffee** [comment]
Hmm Not sure what has change since yesterday when I was trying this but I got different error. Using the same config script.

[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: ''
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing pass-2 core C gcc compiler: done in 316.00s (at 21:12)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      make[2]: *** [iconvdata/others] Error 2
[ERROR]      make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@218]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@377]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1659]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@86]
[ERROR]  >>        called from: do_libc[scripts/build/libc/glibc.sh@53]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@624]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/opt/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-248-gdf5a341/B - Known issues.txt'
[ERROR]
[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/572909/build.log.gz)

**Comment by oxoocoffee** [comment]
Ok So the above errors looks like were produced by different tools used. So I fixed it. The limits error is gone but now we have another in cross-gdb

Here is what I did so fat to get this working in /opt/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-248-gdf5a341

1. I updated crosstool-NG.sh to switch -static to -Bstatic (crosstool-NG.sh.patch)
2. Had to install home-brew tools and update paths.sh (paths.sh.patch)
3. Place your patch 113-gdb-hack-long-min.patch

Also I did try gdb 7.10.1 and 7.11 and they both produce same limits error with out patch and 
with your patch same new error listed below:

[INFO ]  Installing ncurses for target: done in 31.00s (at 30:15)
[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/pex-unix.c:347:22: error: use of undeclared identifier 'O_RDONLY'
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/pex-unix.c:358:22: error: use of undeclared identifier 'O_WRONLY'
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/pex-unix.c:358:33: error: use of undeclared identifier 'O_CREAT'
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/pex-unix.c:359:20: error: use of undeclared identifier 'O_APPEND'
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/pex-unix.c:770:18: error: use of undeclared identifier 'F_SETFD'
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/pex-unix.c:770:27: error: use of undeclared identifier 'FD_CLOEXEC'
[ERROR]    make[3]: *** [pex-unix.o] Error 1
[ERROR]    checking whether build environment is sane... make[2]: *** [all-libiberty] Error 2
[ERROR]    make[1]: *** [all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@218]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@131]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@624]

I am including full build.log. Configuration is the same as initially attached in this issue ticket except in this run I did try gdb-7.11.

Also I am adding config.log from my /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-gdb-cross/


[config.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/573250/config.log.zip)
[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/573248/build.log.zip)
[crosstool-NG.sh.patch.zip](https://github.com/crosstool-ng/crosstool-ng/files/573244/crosstool-NG.sh.patch.zip)
[paths.sh.patch.zip](https://github.com/crosstool-ng/crosstool-ng/files/573245/paths.sh.patch.zip)

**Comment by KirillSmirnov** [comment]
What I saw in build.log is really strange:
1) This command works (binutils variant): x86_64-build_apple-darwin16.1.0-gcc -c -DHAVE_CONFIG_H -O2 -g -pipe  -I/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/include  -I. -I/Volumes/Yocto/crosstool-ng/.build/src/binutils-2.26/libiberty/../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -pedantic  -D_GNU_SOURCE /Volumes/Yocto/crosstool-ng/.build/src/binutils-2.26/libiberty/fibheap.c -o fibheap.o
2) But this command does not work (gdb variant): x86_64-build_apple-darwin16.1.0-gcc -O2 -g -pipe -I/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/include -L/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib -c -DHAVE_CONFIG_H -g -O2  -I. -I/Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/../include  -W -Wall -Wwrite-strings -Wc++-compat -Wstrict-prototypes -pedantic  -D_GNU_SOURCE /Volumes/Yocto/crosstool-ng/.build/src/gdb-7.11/libiberty/fibheap.c -o fibheap.o

But they are nearly the same, cmdline options are almost identical! It seems libiberty configure cannot find limits.h nor fcntl.h for some reason. Main gdb config.log did not help: it does not search for these headers.


Please attach config.log and config.h files found in
/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-gdb-cross/libiberty
and
/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/build/build-cc-gcc-final/libiberty
totally 4 files.

**Comment by oxoocoffee** [comment]
Here they are.

[gdb.config.zip](https://github.com/crosstool-ng/crosstool-ng/files/573658/gdb.config.zip)
[gcc.config.zip](https://github.com/crosstool-ng/crosstool-ng/files/573659/gcc.config.zip)

**Comment by KirillSmirnov** [comment]
Found! Clang for some reason prints warnings in stderr. Configure script detects non-empty stderr and treats the check as a failure.
The attached patch (for crosstool-ng itself) silences this clang verbosity.

[clang-unused-args.patch.zip](https://github.com/crosstool-ng/crosstool-ng/files/573758/clang-unused-args.patch.zip)

**Comment by oxoocoffee** [comment]
Good deal. With your patch I was able to build entire project. I also removed your first gdb patch for limits before rebuilding so this one is not needed. I will try to do few other builds and will report

Also not sure if you did noticed this but there are couple of "errors" . This sounds more like warning.

[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    clang: error: unsupported option '-print-multi-os-directory'
[ERROR]    clang: error: no input files
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]    gcc default flags: ''
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib (os)

Also will this fix be in master anytime soon? How about making the other scripts?

Thank you

**Comment by oxoocoffee** [comment]
So I also did try to build dmalloc and I got this message.

[INFO ]  Installing ncurses for target
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for target: done in 34.00s (at 33:42)
[INFO ]  =================================================================
[INFO ]  Installing dmalloc
[EXTRA]    Configuring dmalloc
[EXTRA]    Building dmalloc
[ERROR]    arm-cortexa9_neon-linux-gnueabihf-g++: error: libdmallocth.dylib: No such file or directory
[ERROR]    arm-cortexa9_neon-linux-gnueabihf-g++: error: 1: No such file or directory
[ERROR]    arm-cortexa9_neon-linux-gnueabihf-g++: error: 1: No such file or directory
[ERROR]    arm-cortexa9_neon-linux-gnueabihf-g++: error: unrecognized command line option '-install_name'
[ERROR]    arm-cortexa9_neon-linux-gnueabihf-g++: error: unrecognized command line option '-compatibility_version'
[ERROR]    arm-cortexa9_neon-linux-gnueabihf-g++: error: unrecognized command line option '-current_version'; did you mean '-Wconversion'?
[ERROR]    make[1]: *** [libdmallocth.dylib] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing dmalloc'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@218]
[ERROR]  >>        called from: do_debug_dmalloc_build[scripts/build/debug/100-dmalloc.sh@50]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@624]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/opt/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-248-gdf5a341/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 33:55.00)
[33:55] / make: *** [build] Error 1

[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/574369/build.log.zip)
[config.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/574370/config.log.zip)

**Comment by KirillSmirnov** [comment]
dmalloc is not cross-compile friendly: as soon as it detects build system is Darwin it assumes host system is Darwin too. With this idea in its mind it passes Darwin-related flags to GNU linker. Fail :-(

This patch is a quick-n-dirty hack: it disables that check. The proper fix should detect for Darwin linker, but I am not familiar with that...

[200-disable-darwin-check.patch.zip](https://github.com/crosstool-ng/crosstool-ng/files/581766/200-disable-darwin-check.patch.zip)

**Comment by stilor** [comment]
I am tempted to suggest dropping dmalloc altogether:
- It has not seen any releases since May 2007 - almost ten years
- It does not have any bug database, patch queue or any publicly accessible version control system to see if there is any activity (and to download "latest" version if it has some fix)
- Its maintainer is not responding. I sent a patch (170-bogus-ppc-assembly.diff) to him about a year ago, haven't heard back since. Heck, he doesn't even list any email - instead, all submissions are accepted via a web-basef form on his website. As far as I understand, that form is routed to /dev/null.

I don't think we (crosstool-ng) should perform development for dmalloc in crosstool-ng tree. If anyone wants to save dmalloc, it must be forked and maintained.

**Comment by oxoocoffee** [comment]
So I was able to build dmalloc with your patch. Thank you
Also building strace-4.10 has issue but latest strace-4.5.18 seems to build fine
Here is strace-4.10 error

[INFO ]  Installing strace
[EXTRA]    Configuring strace
[EXTRA]    Building strace
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/strace-4.10/ioctlsort.c:36:10: fatal error: 'linux/ioctl.h' file not found
[ERROR]    gmake[1]: *** [Makefile:3424: ioctlsort0.o] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing strace'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_debug_strace_build[scripts/build/debug/500-strace.sh@31]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@624]

**Comment by oxoocoffee** [comment]
I just did try to build with latest version and build looks fine

**Comment by oxoocoffee** [comment]
Ok I just did try latest version and trying to use same config file I am getting gcc build errors

[INFO ]  Installing gettext for host: done in 263.00s (at 12:44)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 128.00s (at 14:52)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    gmake[2]: *** [Makefile:224: directives-only.o] Error 1
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    /Volumes/Yocto/crosstool-ng/.build/src/gcc-6.2.0/libcpp/system.h:275:10: fatal error: 'libintl.h' file not found
[ERROR]    gmake[2]: *** [Makefile:224: errors.o] Error 1
[ERROR]    gmake[2]: *** [Makefile:224: identifiers.o] Error 1
[ERROR]    gmake[2]: *** [Makefile:224: files.o] Error 1
[ERROR]    gmake[2]: *** [Makefile:224: expr.o] Error 1
[ERROR]    gmake[2]: *** [Makefile:224: directives.o] Error 1
[ERROR]    gmake[2]: *** [Makefile:224: lex.o] Error 1
[ERROR]    gmake[2]: *** [Makefile:224: charset.o] Error 1
[ERROR]    gmake[1]: *** [Makefile:6522: all-libcpp] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@259]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@697]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@271]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@629]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/opt/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-360-gda3f8c4e-dirty/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 16:02.00)
[16:03] / gmake: *** [/opt/local/bin/ct-ng:152: build] Error 2

**Comment by oxoocoffee** [comment]
[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/646791/build.log.zip)

**Comment by stilor** [comment]
Please leave it open until the above patches are integrated in some form. They might need some massaging though - patch to 300-gdb.sh, for example, supplies clang-specific options that will be rejected by gcc.

**Comment by oxoocoffee** [comment]
Sure, I leave it open :) Also there is another clang issue

[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
**[ERROR]    clang: error: unsupported option '-print-multi-os-directory'**
[ERROR]    clang: error: no input files

**Comment by stilor** [comment]
That error comes from libiberty's Makefile.in, not from crosstool-ng. You'd probably see this error even if you just unpack gcc's tarball and attempt to build it with clang. If it is the case, please file a GCC bug for this.

**Comment by stilor** [comment]
This should be now fixed on master.

**Comment by alfishe** [comment]
[ERROR] clang: error: unsupported option '-print-multi-os-directory'
[ERROR] clang: error: no input files

Still not working on 1.23.0 release. master HEAD has lot's of other issues, so not an option.
I suppose issue can be closed only if it's released and tested. Not when fix committed.
