### ISSUE TITLE
This project is dead

### ISSUE THREAD

**Issue by stilor** [crosstool-ng/crosstool-ng#470]
Let's see how long it takes for the maintainer to respond? :)

**Comment by bhundven** [comment]
This project is not dead.
The current maintainer (me) has ran into the same problem the previous maintainer (Yann E. MORIN) ran into, which is: life

I have a job that is taking up more of my time then I have available to myself (let alone crosstool-NG). I have spoke with others in the past about taking the project over, but they also mentioned that they also do not have the ability to maintain this project full-time.

If you or someone you know would like to take over crosstool-ng, I would be more then happy to interview applicants.

**Comment by stilor** [comment]
I know, life happens. Which is why I suggested a co-maintainership awhile ago, but you declined at the time. I cannot commit to full maintainership now, but I certainly can help with reviewing/merging PRs and testing them (as I also mentioned, I have a private build-test server running crosstool-ng builds overnight).

With two maintainers, it is less likely that "life happens" to both of them at the same time.

**Comment by bhundven** [comment]
You've been added as a developer. PM me on IRC.

**Comment by stilor** [comment]
PRs are piling up and @bhundven responds neither here, nor on IRC, nor via email... Please remove the check for "approval" of the PRs if you cannot find the time to even do the reviews.

**Comment by bhundven** [comment]
@stilor I've added you as an owner now. You are now a co-maintainer. I'm not able to keep up right now. Sorry. Now you can push it forward.

**Comment by stilor** [comment]
Thanks. I'll continue with the policy I suggested previously. I'll wait one day on trivial PRs - 3 days on not-so-trivial - before merging them.

I'd also appreciate some guidance on release management, if this task also falls to me.

**Comment by fidomax** [comment]
Is it dead again?

**Comment by cpackham** [comment]
I do have an interest in keeping crosstool-ng not dead. I might even convince $boss at $dayjob that it's worth spending work time on.

I'll try to triage some of the issues that are building up. Some of them are just a case of taking a look at build.log.

Did anything ever happen w.r.t using gitlab-ci instead of travis. There are some issues that may be -EWORKSFORME if we could point to a working CI.
