### ISSUE TITLE
Missing library after build on Mac Sierra

### ISSUE THREAD

**Issue by oxoocoffee** [crosstool-ng/crosstool-ng#483]
Today I did pull master and after rebuilding and installing crosstool-ng I loaded my config file and started clean build. After successful build I tar/gzip generated folder in x-tools (arm-cortexa9_neon-linux-gnueabihf). Then I tar/unzip it back to /opt/crosstool-ng/arm-cortexa9_neon-linux-gnueabihf/
I added /opt/crosstool-ng/arm-cortexa9_neon-linux-gnueabihf/bin to my PATH and did try to run arm-cortexa9_neon-linux-gnueabihf-g++. So for quick test I did try to build small main.cpp test and "file" on a.out showed correct "ELF 32-bit LSB executable, ARM, EABI5 version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-armhf.so.3, for GNU/Linux 3.2.0, not stripped"

Now the problem is that I still have my external USB drive plugged  in which is mounted as  /Volumes/Yocto where I did build toolchain.

After un mounting USB drive I noticed that cortexa9_neon-linux-gnueabihf-g++ core dumps. Looking in crash report I see that library is missing. So while USB drive is unplugged I did 

otool -L /opt/crosstool-ng/arm-cortexa9_neon-linux-gnueabihf/bin/cortexa9_neon-linux-gnueabihf-g++

I noticed that one of the librarys is at wrong location.

arm-cortexa9_neon-linux-gnueabihf-g++:
	/usr/lib/libc++.1.dylib (compatibility version 1.0.0, current version 307.4.0)
	/usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1238.0.0)
	/Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib/libintl.8.dylib (compatibility version 10.0.0, current version 10.4.0)
	/usr/lib/libiconv.2.dylib (compatibility version 7.0.0, current version 7.0.0

As you can see while I am in /opt/crosstool-ng/arm-cortexa9_neon-linux-gnueabihf/bin/ it ls looking for for libintl.8.dylib which is hardwired to /Volumes/Yocto/crosstool-ng/.build/ which was my unmounted USB drive that I used for building. I did try to search for libintl.8.dylib in /opt/crosstool-ng/arm-cortexa9_neon-linux-gnueabihf/ and I do not see it.

Here is content of my  /opt/crosstool-ng/linux-3-12-67/arm-cortexa9_neon-linux-gnueabihf/lib/

dr-xr-xr-x  28 rob  staff   952B Nov 28 18:15 ldscripts/
dr-xr-xr-x   3 rob  staff   102B Nov 28 18:44 gcc/
lrwxr-xr-x   1 rob  staff    11B Nov 28 18:44 libcc1.so@ -> libcc1.0.so
-r-xr-xr-x   1 rob  staff   114K Nov 28 18:44 libcc1.0.so*

and /Volumes/Yocto/crosstool-ng/.build/arm-cortexa9_neon-linux-gnueabihf/buildtools/lib/

-rw-r--r--  1 rob  staff    85K Nov 28 18:00 libpanel_g.a
-rw-r--r--  1 rob  staff    72K Nov 28 18:00 libpanel.a
-rw-r--r--  1 rob  staff   1.7M Nov 28 18:00 libncurses_g.a
-rw-r--r--  1 rob  staff   1.4M Nov 28 18:00 libncurses.a
-rw-r--r--  1 rob  staff   220K Nov 28 18:00 libmenu_g.a
-rw-r--r--  1 rob  staff   199K Nov 28 18:00 libmenu.a
-rw-r--r--  1 rob  staff   449K Nov 28 18:00 libform_g.a
-rw-r--r--  1 rob  staff   417K Nov 28 18:00 libform.a
lrwxr-xr-x  1 rob  staff    17B Nov 28 18:00 terminfo@ -> ../share/terminfo
-rw-r--r--  1 rob  staff   772K Nov 28 18:06 libgmpxx.a
-rw-r--r--  1 rob  staff   2.9M Nov 28 18:06 libgmp.a
-rw-r--r--  1 rob  staff   1.8M Nov 28 18:06 libmpfr.a
-rw-r--r--  1 rob  staff   5.3M Nov 28 18:07 libisl.a
-rw-r--r--  1 rob  staff   503K Nov 28 18:07 libmpc.a
drwxr-xr-x  2 rob  staff   136B Nov 28 18:07 pkgconfig/
lrwxr-xr-x  1 rob  staff    16B Nov 28 18:07 libexpat.dylib@ -> libexpat.1.dylib
-rw-r--r--  1 rob  staff   465K Nov 28 18:07 libexpat.a
-rwxr-xr-x  1 rob  staff   171K Nov 28 18:07 libexpat.1.dylib*
lrwxr-xr-x  1 rob  staff    19B Nov 28 18:12 libasprintf.dylib@ -> libasprintf.0.dylib
-rw-r--r--  1 rob  staff    54K Nov 28 18:12 libasprintf.a
-rwxr-xr-x  1 rob  staff    11K Nov 28 18:12 libasprintf.0.dylib*
lrwxr-xr-x  1 rob  staff    15B Nov 28 18:12 libintl.dylib@ -> libintl.8.dylib
-rw-r--r--  1 rob  staff   213K Nov 28 18:12 libintl.a
-rw-r--r--  1 rob  staff    62K Nov 28 18:12 libintl.8.dylib
lrwxr-xr-x  1 rob  staff    26B Nov 28 18:12 libgettextsrc.dylib@ -> libgettextsrc-0.19.7.dylib
-rwxr-xr-x  1 rob  staff   355K Nov 28 18:12 libgettextsrc-0.19.7.dylib*
lrwxr-xr-x  1 rob  staff    26B Nov 28 18:12 libgettextlib.dylib@ -> libgettextlib-0.19.7.dylib
-rwxr-xr-x  1 rob  staff   1.2M Nov 28 18:12 libgettextlib-0.19.7.dylib*
lrwxr-xr-x  1 rob  staff    20B Nov 28 18:12 libgettextpo.dylib@ -> libgettextpo.0.dylib
-rw-r--r--  1 rob  staff   1.4M Nov 28 18:12 libgettextpo.a
-rwxr-xr-x  1 rob  staff   423K Nov 28 18:12 libgettextpo.0.dylib*
drwxr-xr-x  2 rob  staff   238B Nov 28 18:12 gettext/
drwxr-xr-x  3 rob  staff   102B Nov 28 18:20 gcc/

Looks to me like some files from .build folder were never moved to output path?

**Comment by oxoocoffee** [comment]
[files.zip](https://github.com/crosstool-ng/crosstool-ng/files/618187/files.zip)

Here is my build log and config file

**Comment by oxoocoffee** [comment]
[EDIT] Initial config file attached to this ticket uses linux-3-12-67. I did altered crosstools-ng and added missing inux-3-14-62. After crosstools-ng rebuild and install I did

ct-ng clear
ct-ng menuconfig #to enable linux-3-14-62
ct-ng build

So below is with linux-3-14-62 but both versions had same problem
[EDIT]

Also to add to this I noticed this which might be all related to above problem
So I exported crosstools to PATH and did try to run arm-cortexa9_neon-linux-gnueabihf-ldd

bash-4.4$ export PATH=/opt/crosstool-ng/linux-3-14-62/arm-cortexa9_neon-linux-gnueabihf/bin:$PATH
bash-4.4$ arm-cortexa9_neon-linux-gnueabihf-ldd
arm-cortexa9_neon-linux-gnueabihf-ldd: no root given

So I exported CT_XLDD_ROOT

bash-4.4$ export CT_XLDD_ROOT=/opt/crosstool-ng/linux-3-14-62/arm-cortexa9_neon-linux-gnueabihf/arm-cortexa9_neon-linux-gnueabihf/sysroot

Now running again I get following errors.

bash-4.4$ arm-cortexa9_neon-linux-gnueabihf-ldd
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
readelf: Error: '': No such file
sed: illegal option -- r
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
readelf: Error: '': No such file

**Comment by oxoocoffee** [comment]
Also I am attaching full "tree" (x-tools.txt.gz) file executed in /Volumes/Yocto/crosstool-ng-output/x-tools/arm-cortexa9_neon-linux-gnueabihf/ to see what was generated

Also build.txt.gz which was generated in /Volumes/Yocto/crosstool-ng/.build/

[x-tools.txt.gz](https://github.com/crosstool-ng/crosstool-ng/files/620750/x-tools.txt.gz)
[build.txt.gz](https://github.com/crosstool-ng/crosstool-ng/files/620757/build.txt.gz)

**Comment by stilor** [comment]
Yes, it seems to be a generic problem, not just MacOS. I am switching companion libs to static linking for now; we may re-enable using them as shared later - but it will require more changes than just installing them into `${CT_PREFIX_DIR}`.

**Comment by oxoocoffee** [comment]
Let me know when I can try it

**Comment by stilor** [comment]
Re xldd: can you check if MacOS's sed is using extended regexps by default? E.g., what does `echo ab | sed -e 's/ab?/match/'` print?

**Comment by oxoocoffee** [comment]
Here it is 

$ echo ab | sed -e 's/ab?/match/'
ab

**Comment by stilor** [comment]
Is `-E` option to sed enabling extending regexp's by chance? Does `echo ab | sed -E -e 's/ab?/match/'` display "match"?

**Comment by stilor** [comment]
And `gsed` is a GNU sed?

**Comment by oxoocoffee** [comment]
yes Gnu.

16:15 $ gsed --version
gsed (GNU sed) 4.2.2

16:13 $ echo ab | sed -E 's/ab?/match/'
match

same output for gsed

**Comment by stilor** [comment]
Created a separate issue https://github.com/crosstool-ng/crosstool-ng/issues/507 for the sed problem.

**Comment by stilor** [comment]
This is now fixed and Mac build is restored by https://github.com/crosstool-ng/crosstool-ng/pull/510; closing.
