### ISSUE TITLE
Cannot link to shared libs with executable cross-compiled for rpi

### ISSUE THREAD

**Issue by marcmunro** [crosstool-ng/crosstool-ng#490]
Using ct-ng 1.22 I have built a cross compiler for rpi from the armv6-rpi-linux-gnueabi sample.  I can create statically linked executables that run fine, but not ones that can access shared libraries.

With an executable called test, I get this:

[root@runeaudio ~]# ./test
./test: error while loading shared libraries: /root/libfoo.so: internal error
[root@runeaudio ~]# ldd test
	not a dynamic executable
[root@runeaudio ~]# 

I have the simplest possible test files, and can successuflly create a shared library and linked executable to run on the host but not a cross-compiled executable for the pi.

Here are the source files:
----------main.c---
#include <stdio.h>
#include "foo.h"
 
int main(void)
{
    puts("This is a shared library test...");
    foo();
    return 0;
}
----------foo.h---
#ifndef foo_h__
#define foo_h__
 
extern void foo(void);
 
#endif  // foo_h__
---------foo.c--
#include <stdio.h>
 
 
void foo(void)
{
    puts("Hello, I'm a shared library");
}
---------end files--

My compilation commands are:

marc:test2$ armv6-rpi-linux-gnueabi-gcc  -c -Wall -Werror -fpic foo.c
marc:test2$ armv6-rpi-linux-gnueabi-gcc -shared -o libfoo.so foo.o
marc:test2$ armv6-rpi-linux-gnueabi-gcc -L`pwd` -Wl,-rpath=`pwd` -Wall -o test main.c -lfoo

The only thing I have done to enable the cross-compilers is to add the appropriate bin directory to my PATH.  Is there anything I am obviously doing wrong?

Oh and my build environment is this:
Linux bloodnok 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

__
Marc

**Comment by bhundven** [comment]
Try the latest git, if it still occurs, lets fix it in master and merge the change to 1.22 branch.

**Comment by marcmunro** [comment]
Righto, I'll give it a go and get back to you.  Thanks.

**Comment by marcmunro** [comment]
I removed all traces of previous efforts and checked out the latest git.  Built and installed, but no change.

Here is what I did:

marc:crosstool-ng$ autoconf 
marc:crosstool-ng$ ./configure --prefix="/home/marc/proj/pi/crosstool"
marc:crosstool-ng$ make -j 4
marc:crosstool-ng$ make install
marc:crosstool-ng$ ct-ng armv6-rpi-linux-gnueabi
marc:crosstool-ng$ ct-ng build

Then I cleared out my old test objects and executables, recompiled and re-ran my tests.  Results were exactly as before.

If there is anything I can do to help debug this let me know.  I am in the PST time zone and can spend quite a bit of time on this during daylight hours and into most evenings.  My C and linux skills are pretty good.  Compiler skills, not so much.

Thanks.

__
Marc

**Comment by stilor** [comment]
I don't have a Raspberry Pi to try it out, so a few random thoughts on what could go wrong:
- Does a simple shared application work? I.e., if you remove the call to foo() from main.c and compile/link it without -lfoo, does it run fine?
- Is the rest of the system (dynamic loader, libc) built using the same toolchain from ct-ng? ARM has many ABI flavors, so ld-linux.so with one ABI may not load a shared library built with another ABI.

If the rest of the system was built with a different toolchain, you can try to put the stuff built by ct-ng (libc.so.6, ld-linux.so.3) into a separate directory (e.g. /newlib); add `-Wl,--dynamic-linker=/newlib/ld.so` to command line for linking "test" and run it with "LD_LIBRARY_PATH=/newlib ./test".

**Comment by stilor** [comment]
Another way to check the ABI compatibility is to run `readelf -h` on your `test` binary and on `/lib/ld-linux.so.3` on the system where you run it. Look for the line similar to this:
````
Flags:                             0x5000200, Version5 EABI, soft-float ABI
````
These lines should be the same in both binaries (as well as any libraries loaded as dependencies)

**Comment by marcmunro** [comment]
Responses to @stilor's questions:

* Does a simple shared application work? I.e., if you remove the call to foo() from main.c and compile/link it without -lfoo, does it run fine?

Yep:
    [root@runeaudio ~]# ./test
    This is a shared library test...

* Is the rest of the system (dynamic loader, libc) built using the same toolchain from ct-ng? ARM has many ABI flavors, so ld-linux.so with one ABI may not load a shared library built with another ABI.

No.  I am trying to build a compiler to match a runeaudio system because I want to hack on it.  I don't really want to have to build the entire thing from scratch.  The reason I am using a stock rpi config rather than a custom one is because I had the same issue with my custom config and wanted to eliminate the chance that I'd done something stupid in my config.  Maybe I should go back to the custom one, but I'd pretty well matched the linux, library and compiler versions and I had the same issue I have now.

* Another way to check the ABI compatibility is to run readelf -h on your test binary and on /lib/ld-linux.so.3 on the system where you run it. Look for the line similar to this...

I'm having to use readelf on my host system as the runeaudio pi distribution is very minimal.  I assume that is ok

    marc:test$ readelf -h ./test | grep Flags
      Flags:                             0x5000200, Version5 EABI, soft-float ABI
    marc:test$ readelf -h ./ld-linux.so.3 | grep Flags
      Flags:                             0x5000402, Version5 EABI, hard-float ABI, <unknown>

Hmmm, interesting.  I'll see if I can figure out how to build for the hard-float ABI.

Any other suggestions or comments are welcomed.

__
Marc

**Comment by marcmunro** [comment]
YAY!

That was it.  Thanks everyone.

The solution was to select the Hardware FPU option under floating point, under target options.

Note that this creates toolchain items with the name armv6-rpi-linux-gnueabihf-xxx, rather than armv6-rpi-linux-gnueabii-xxx

**Comment by stilor** [comment]
Well, as you may guess, this is exactly the reason why this creates a different tuple - soft/hard-float ABIs are not compatible.
