### ISSUE TITLE
Don't -m64 flag supported by armv8-rpi3-linux-gnueabihf-g++?

### ISSUE THREAD

**Issue by liuyan82** [crosstool-ng/crosstool-ng#493]
When compile for Raspberry Pi 3, I add  -m64, but '-m64 flag not supported ' error occurred. I dropped -m64 it can be compiled successfully, but can't link 64 bits so library.

How can I build 64 bits binary ?

**Comment by liuyan82** [comment]
BTW, I'm working on Mac.

**Comment by stilor** [comment]
What is the architecture/bitness in your config? You are probably using arm*-* toolchain, while for 64-bit you need aarch64-* toolchain (AArch64 is the architecture name for 64-bit ARM). Select '64-bit' for bitness when configuring your toolchain.

**Comment by liuyan82** [comment]
OK, I will try the aarch64-rpi3.
Thanks a lot !
