### ISSUE TITLE
Build fails building gcc-4.9.3 with gcc-6.2

### ISSUE THREAD

**Issue by DanDevine** [crosstool-ng/crosstool-ng#497]
I'm currently getting a build fail for armv7-rpi2-linux-gnueabihf with error: 
`cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute`

Branch: origin/master, Dec 4, 2016
Host machine: Fedora w/ gcc (GCC) 6.2.1 20160916 (Red Hat 6.2.1-2)

This issue seems to be similar to https://github.com/crosstool-ng/crosstool-ng/issues/400
Attempted to apply this patch:
https://patchwork.openembedded.org/patch/122469/
No success with this either, as I don't know too much about patch structure :( and cannot be sure I applied correctly.

I've attached a shortened build log with the initial configuration dump and then jumping to the breakage.

[build_annotated.txt](https://github.com/crosstool-ng/crosstool-ng/files/633082/build_annotated.txt)

**Comment by stilor** [comment]
That does not seem to be related to 'master': master has GCC 4.9.4, not 4.9.3; and in 4.9.4 this fix is already integrated. Fix for 4.8.5 has been backported by PR 495.
