### ISSUE TITLE
Need to detect/use sed differently on MacOS

### ISSUE THREAD

**Issue by stilor** [crosstool-ng/crosstool-ng#507]
MacOS sed does not recognize `-r`. One needs to either use `gsed` (GNU sed) or `sed -E` in place of `sed -r`.

**Comment by bhundven** [comment]
Yes, this is why we search for gsed in configure.ac before sed.

**Comment by bhundven** [comment]
https://github.com/crosstool-ng/crosstool-ng/blob/master/configure.ac#L116

**Comment by oxoocoffee** [comment]
Let me know if you want me to run any other config files beside my. Also which output files you interested in.

**Comment by bhundven** [comment]
Nah, I think we get the issue described.

1. We are not checking for `gsed` before `sed`.
2. We are not checking if `sed` supports `-E`, which would not require `gsed` (if sed is not GNU)

This stuff just needs to be fixed.

**Comment by oxoocoffee** [comment]
Great. When fix is in I will give a try :)

**Comment by stilor** [comment]
Should be fixed now.

**Comment by stilor** [comment]
We now require gsed, and the configure detects it.
