### ISSUE TITLE
Recursion detected, bailing out when sub-built

### ISSUE THREAD

**Issue by maxnbk** [crosstool-ng/crosstool-ng#514]
Using a package management tool ( https://github.com/nerdvegas/rez ) and trying to create a crosstool-ng package.

By default it uses CMake to generate makefiles of work to generate the package (which in this case involves bootstrap/config/make/make-installing cross-tools from git or tarball, either way, same problem)

Presumably because cmake+make is implicitly being used to build the package, and because my build process is running ./bootstrap , ./configure --prefix=/some/path , make, make install , I am getting a recursion warning because of line 122 of the bootstrap'd makefile.

Manually patching it to 1 or 2 as others have done is not helping. Setting MAKELEVEL=0 in the make command to try to 'reset' the recursion level for the level of make actually building crosstools causes recursion and my process tree fills up quickly.

How can I handle this situation correctly beyond not using rez to build a crosstool-ng package (ie building / assembling the rez package by hand) ? (And what exactly is recursing and why?)

Let me know if the configure output is helpful in this regard.

Thanks,

**Comment by stilor** [comment]
I know the problem and I plan on revamping the Makefiles. I am hesitant to do major changes right now, though - I hope to have1.23 cut soon; it seems the master is in more or less decent shape.

The hack I've been using is to unset the MAKELEVEL, rather than set it to 0.

**Comment by maxnbk** [comment]
Unfortunately un-set-ing MAKELEVEL did not work in my circumstance, though I'm not clear on why. At what point in the process (prior to the first make?) did you unset?
Thanks for slating this for future milestone.

**Comment by stilor** [comment]
Shouldn't be an issue anymore, the Makefiles have been completely rewritten (for autotools). If it is still an issue, please file a new bug.
