### ISSUE TITLE
Promoting musl from EXPERIMENTAL?

### ISSUE THREAD

**Issue by kozyilmaz** [crosstool-ng/crosstool-ng#518]
musl is still listed under EXPERIMENTAL and I was wondering what should be done in order to promote musl to a first-class libc for crosstool-ng

I checked LEDE and Buildroot and here is how musl is handled:

LEDE has an include overlay (cdefs.h, queue.h etc.) + patches on top of 1.1.16 like:
```
099-Add-format-attribute-to-some-function-declarations.patch
100-add_glob_onlydir.patch
110-read_timezone_from_fs.patch
200-add_libssp_nonshared.patch
300-relative.patch
900-iconv_size_hack.patch
901-crypt_size_hack.patch
```
Buildroot downloads queue.h from NetBSD and provides a custom cdefs.h (by Yann E. Morin)

In short, both projects add at least cdefs.h and queue.h to musl headers, Buildroot seems to be content with vanilla 1.1.16 but LEDE has some additional patches.

Any suggestions?

**Comment by stilor** [comment]
AFAIU, the primary reason musl is marked experimental is not musl itself. Rather, it is the amount of hacking the other tools to recognize this flavor of C library. Both GDB and GCC require some patches to handle it; look through our patches to *other* components to get an idea. I'll give a try to 1.1.16 and see how it goes, but of all the flavors of C libraries, musl is the least recognized.

**Comment by kozyilmaz** [comment]
Alright, as said cdefs.h and queue.h is added both in Buildroot and Lede. You’ll probably need crosstool-ng/crosstool-ng#517 along the way too. Thanks for looking into this.
