### ISSUE TITLE
linaro webpage changed

### ISSUE THREAD

**Issue by petak** [crosstool-ng/crosstool-ng#522]
In the meantime, the web of linaro (linaro.org) has moved to a different structure of internal URL's. As a consequence, ct-ng fails whenever it tries to download any sourcecode from that site.

**Comment by stilor** [comment]
Should be fixed by https://github.com/crosstool-ng/crosstool-ng/pull/525 once it's picked up

**Comment by stilor** [comment]
Fix merged to master.
