### ISSUE TITLE
Obsoleting packages in 1.23

### ISSUE THREAD

**Issue by stilor** [crosstool-ng/crosstool-ng#540]
Since 1.22, many new components had their versions upgraded. What's more important, some older versions have been removed. I wasn't very fond of removing it without a warning, I am more inclined to follow GCC's strategy - where a feature is declared obsolete at least one release before retiring. Resurrecting all removed features would require a lot of effort, but I wanted to play fair and at least give out the list of what has been retired. If you depend on any of these versions - please reply, I'll see if it can be resurrected for one more release. It will still be marked obsolete, and I intend to clean up the obsoleted features right after 1.23 is out.

For the reference, here is what has been removed since 1.22:

- binutils: 2.21.53 2.21.1a 2.20.1a 2.19.1a 2.18a
- gcc: linaro-4.7-2014.06 4.7.4 linaro-4.6-2013.05 4.6.4 linaro-4.5-2012.03 4.5.4 linaro-4.4-2011.02-0 4.4.7 4.3.6 4.2.4
- CLooG: 0.15.11
- PPL: 0.11.2 0.11.1 0.11 0.10.2
- dmalloc: 5.5.2
- linux: 2.6.32.68
- glibc: 2.17 2.16.0 2.15 2.14.1 2.14 2.13 2.12.2 2.12.1 2.11.1 2.11 2.10.1 2.9 2.8
- musl: 1.1.12 1.0.5
- uClibc-ng: 1.0.9

To clarify the policy I suggest going forward, I do not consider "removed" the releases where the patchlevel version was upgraded. E.g., crosstool-ng 1.22 had linux 3.2.72, and current master has 3.2.83. Once new versions of any component are imported, I plan to keep 2-3 most recent minor releases as current, and mark any older releases obsolete.

**Comment by tamird** [comment]
Some of these removals are sad to see; for us, in in [CockroachDB](https://github.com/cockroachdb/cockroach), crosstool-ng is a great help in creating toolchains that allow us to target ancient linux distributions which are extremely common in enterprises like RHEL 6.

For context, here's an excerpt from [distrowatch](http://distrowatch.com/table.php?distribution=redhat):

| Feature/Package | RHEL-7.3 | RHEL-6.8 | RHEL-5.11 |
|------------------|-----------|-----------|-----------|
| End Of Life | 2024-06 | 2020-11 | 2017-03 |
| glibc | 2.17 | 2.12 | 2.5 |
| linux | 3.10 | 2.6.32 | 2.6.18 |

We can certainly get by without RHEL 5 support, but RHEL 6 is going to be with us for a long time, and it would be great (for CockroachDB) to be able to support it on an ongoing basis.

Note that we also use crosstool-ng to target musl-based systems when statically linking, and newer versions of musl don't work with crosstool-ng 1.22.0. At the moment, we're using two different versions of crosstool-ng to build both pairs of toolchains.

Thanks for the great work you're doing here; I hope you'll consider extending support for some of these targets.

**Comment by stilor** [comment]
Ok, after some thought I decided to restore the kernel and glibc versions. I still marked them obsolete, which means I won't be actively improving them. Any fixes specific to those obsolete would have to come from interested parties in form of pull requests.

But I added a few sample configs to make sure they are not accidentally broken.

See https://github.com/crosstool-ng/crosstool-ng/pull/586

**Comment by ymkjp** [comment]
Probably this is wrong place to report but I faced 404 HTTP error during `ct-ng build`.

```
[ALL  ]    HTTP request sent, awaiting response... 404 NOT FOUND
[ALL  ]    2017-03-01 00:18:53 ERROR 404: NOT FOUND.
[ALL  ]
[DEBUG]    Not at this location: "http://cbuild.validation.linaro.org/snapshots/gcc-linaro-4.9-2015.06"
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_gcc_get[scripts/build/cc/100-gcc.sh@741]
[ERROR]  >>        called from: do_cc_get[scripts/build/cc.sh@21]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@593]
```

**Comment by stilor** [comment]
Wrong place indeed. Please don't use unrelated issues to report bugs. In you case, this PR will be fixing it (just merged to master): https://github.com/crosstool-ng/crosstool-ng/pull/620

**Comment by tamird** [comment]
@stilor did you mean to close this issue? It seems that there's still work being tracked here.

**Comment by stilor** [comment]
Yes, I don't plan to resurrect any more old versions in 1.23. It has been open for ~1.5 months which I deem sufficient period for interested parties to voice their concerns. So far, only you commented (and there was a separate issue about libc 2.13 needed by someone else). If there's a problem with the obsoleted versions (like "glibc 2.13 does not build") - please file a separate PR (yes, **PR** - I am not going to debug outdated versions).

I don't want this issue to attract unrelated comments, like it already started to (see above).

**Comment by praveenmuthusamy** [comment]
Hello all,
how can i build dmalloc in crosstool-ng 1.23
