### ISSUE TITLE
crosstool failed building the full libc when --enable-static-nss enabled.

### ISSUE THREAD

**Issue by atarjoe** [crosstool-ng/crosstool-ng#555]
Hello,

When trying to build a cross toolchain for arm all the stages go perfectly if I use the default options.

However, when I try to specify --enable-static-nss in the glibc extra config the build fail in the 'lib' stage.

[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/727112/build.log.gz)

**Comment by stilor** [comment]
This is a glibc bug, reported upstream https://sourceware.org/ml/libc-alpha/2017-01/msg00449.html

**Comment by stilor** [comment]
Will be fixed on master: https://github.com/crosstool-ng/crosstool-ng/pull/556
