### ISSUE TITLE
binutils 2.27 for powerpc-e500v2-linux-gnuspe needs a patch

### ISSUE THREAD

**Issue by Floessie** [crosstool-ng/crosstool-ng#561]
I've built a current `powerpc-e500v2-linux-gnuspe` toolchain with binutils 2.27 and all went fine (BTW: I had no problems with crosstool-ng for a year now, you're doing a great job! :+1:). There is only a small patch missing, without which `strip` will occasionally fail with:

    Not enough room for program headers, try linking with -N

This is issue [20531](https://sourceware.org/bugzilla/show_bug.cgi?id=20531), and the patch is [here](https://sourceware.org/git/gitweb.cgi?p=binutils-gdb.git;a=blobdiff;f=bfd/elf32-ppc.c;h=1dd6d78d6590bf018ce66b97c378d725bc442575;hp=92299bcc3dd1e304b09d57d36f8bc592330c42a1;hb=8941017bc0226b60ce306d5271df15820ce66a53;hpb=57f6d32deafcfec43bef5e963e12aacc0783a1e4).

Best
Flössie

**Comment by stilor** [comment]
https://github.com/crosstool-ng/crosstool-ng/pull/562

**Comment by Floessie** [comment]
@stilor Thanks! In the meantime I have tested the original patch and it really fixes the problem.
