### ISSUE TITLE
Error building ppc-unknown-linux-gnu

### ISSUE THREAD

**Issue by bdemick** [crosstool-ng/crosstool-ng#569]
After building crosstool-ng from the latest git master, and attempting
to build a toolchain for powerpc-unknown-linux-gnu, I'm running into
an error during the "Building gdbserver" step:

[INFO ]  Installing gdbserver
[EXTRA]    Configuring gdbserver
[EXTRA]    Building gdbserver
[ERROR]    /home/callpop/toolchains/ppc32be/.build/src/gdb-7.12/gdb/gdbserver/../nat/ppc-linux.h:22:26:
fatal error: asm/cputable.h: No such file or directory
[ERROR]    make[1]: *** [linux-ppc-low.o] Error 1
[ERROR]    make[1]: *** Waiting for unfinished jobs....

See attached .config file.  Host is Linux Mint 17.
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/748848/config.txt)

**Comment by stilor** [comment]
You didn't have C++ support enabled in your .config. Starting with 7.12, GDB requires C++ - this dependency was recorded for native GDB, but not for gdbserver.

https://github.com/crosstool-ng/crosstool-ng/pull/571

**Comment by bdemick** [comment]
Good to know, but shouldn't the sample toolchain build with no modifications?  I retried building the toolchain but just used the sample powerpc-unknown-linux-gnu config and that also failed with the same error.

**Comment by stilor** [comment]
The sample includes C++ support. Here is samples/powerpc-unknown-linux-gnu/crosstool.config:
````
CT_ARCH_powerpc=y
CT_KERNEL_linux=y
CT_BINUTILS_PLUGINS=y
CT_CC_LANG_CXX=y
CT_DEBUG_duma=y
CT_DEBUG_gdb=y
# CT_GDB_CROSS_PYTHON is not set
CT_GDB_NATIVE=y
CT_DEBUG_strace=y
````
As you see, CT_CC_LANG_CXX is enabled by default.

**Comment by bdemick** [comment]
Ah, I must not have been copying the sample config.  I was just running `ct-ng powerpc-unknown-linux-gnu` followed by `ct-ng build`.  Once I went back in and enabled C++ in that config, the build succeeded.
