### ISSUE TITLE
glibc build fails on macOS with current master

### ISSUE THREAD

**Issue by flyingk** [crosstool-ng/crosstool-ng#591]
I am trying to build the arm-unknown-linux-gnueabi config on macOS Sierra. No changes were made to the config except the build paths and disable the debug tools.

The build fails with

[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Installing C library headers
[ERROR]      gmake[2]: *** [Makefile:215: iconvdata/install-headers] Error 2
[ERROR]      gmake[1]: *** [Makefile:9: install-headers] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library headers & start files'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@290]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@366]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1764]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@150]
[ERROR]  >>        called from: do_libc_start_files[scripts/build/libc/glibc.sh@112]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'ct-ng/share/doc/crosstool-ng/crosstool-ng-1.22.0-566-g57e1e7e/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 21:13.00)
[21:13] / gmake: *** [ct-ng/bin/ct-ng:147: build] Error 1

System config used to build crosstool from today's master:
brew list
autoconf		gawk			libftdi0		        pcre
automake	gmp			        libtool			pkg-config
avrdude		gnu-sed			libusb			readline
binutils		grep		                libusb-compat	stlink
coreutils		help2man		make			wget
cvs			kconfig-frontends	mpfr
dfu-util		libelf			openssl

I can successfully build the newlib and uglibc targets, so the system appears to work in general.

Here's a link to the build log:

https://dl.dropboxusercontent.com/u/14423229/build.log.zip

**Comment by stilor** [comment]
[ALL  ]      extra-module.mk:11: *** Too many open files.  Stop.

Increase your ulimit. The default on macos (I believe, 256) is too low, set it to something like 1024.

**Comment by flyingk** [comment]
Thanks. That worked.

**Comment by cu6apum** [comment]
Same error here. ulimit was 'unlimited', now 4095.
Too many open files.
ulimit 4096 does not work, 4095 is the limit.
Are 4096++ open files really needed?????
