### ISSUE TITLE
Build static host binaries on Linux

### ISSUE THREAD

**Issue by schreibikus** [crosstool-ng/crosstool-ng#597]
Hello. Thanks for high quality tool!
But, I have error while building the latest trunk:

> [ALL  ]    libtool: link: x86_64-build_pc-linux-gnu-gcc -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wwrite-strings -I/home/builder/crosstool-ng-github/output/src/binutils-2.27/gas/../zlib -O2 -g -pipe -I/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/include -static-libstdc++ -static-libgcc -static -o as-new app.o as.o atof-generic.o compress-debug.o cond.o depend.o dwarf2dbg.o dw2gencfi.o ecoff.o ehopt.o expr.o flonum-copy.o flonum-konst.o flonum-mult.o frags.o hash.o input-file.o input-scrub.o listing.o literal.o macro.o messages.o output-file.o read.o remap.o sb.o stabs.o subsegs.o symbols.o write.o tc-arm.o obj-elf.o atof-ieee.o  -L/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib ../opcodes/.libs/libopcodes.a ../bfd/.libs/libbfd.a -L/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu/zlib -lz ../libiberty/libiberty.a /home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib/libintl.a /home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib/libiconv.a -ldl
[ALL  ]    ../bfd/.libs/libbfd.a(plugin.o): In function `try_load_plugin':
[ALL  ]    /home/builder/crosstool-ng-github/output/src/binutils-2.27/bfd/plugin.c:217: warning: Using 'dlopen' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
[ALL  ]    /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.a(dcigettext.o): In function `_nl_find_msg':
[ALL  ]    (.text+0x2b0): multiple definition of `_nl_find_msg'
[ALL  ]    /home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib/libintl.a(dcigettext.o):/home/builder/crosstool-ng-github/output/src/gettext-0.19.8.1/gettext-tools/../gettext-runtime/intl/dcigettext.c:896: first defined here
[ALL  ]    /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.a(dcigettext.o):(.bss+0x0): multiple definition of `_nl_state_lock'
[ALL  ]    /home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib/libintl.a(dcigettext.o):/home/builder/crosstool-ng-github/output/src/gettext-0.19.8.1/gettext-tools/../gettext-runtime/intl/eval-plural.h:26: first defined here
[ALL  ]    /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.a(finddomain.o): In function `_nl_find_domain':
[ALL  ]    (.text+0x0): multiple definition of `_nl_find_domain'
[ALL  ]    /home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib/libintl.a(finddomain.o):/home/builder/crosstool-ng-github/output/src/gettext-0.19.8.1/gettext-tools/../gettext-runtime/intl/finddomain.c:61: first defined here
[ALL  ]    /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libc.a(loadmsgcat.o): In function `_nl_load_domain':
[ALL  ]    (.text+0x0): multiple definition of `_nl_load_domain'
[ALL  ]    /home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/buildtools/lib/libintl.a(loadmsgcat.o):/home/builder/crosstool-ng-github/output/src/gettext-0.19.8.1/gettext-tools/../gettext-runtime/intl/loadmsgcat.c:787: first defined here
[ERROR]    collect2: error: ld returned 1 exit status
[ALL  ]    Makefile:790: recipe for target 'as-new' failed
[ERROR]    make[5]: *** [as-new] Error 1
[ALL  ]    make[5]: Leaving directory '/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu/gas'
[ALL  ]    Makefile:2232: recipe for target 'all-recursive' failed
[ERROR]    make[4]: *** [all-recursive] Error 1
[ALL  ]    make[4]: Leaving directory '/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu/gas'
[ALL  ]    Makefile:721: recipe for target 'all' failed
[ERROR]    make[3]: *** [all] Error 2
[ALL  ]    make[3]: Leaving directory '/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu/gas'
[ALL  ]    Makefile:4899: recipe for target 'all-gas' failed
[ERROR]    make[2]: *** [all-gas] Error 2
[ALL  ]    make[2]: Leaving directory '/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[ALL  ]    Makefile:850: recipe for target 'all' failed
[ERROR]    make[1]: *** [all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/builder/crosstool-ng-github/output/arm-cortex-linux-gnueabi/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@331]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@238]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@98]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]

I found commit that did it. It's [53758f34ef50050a8e75ac87975816d7d328370f](https://github.com/crosstool-ng/crosstool-ng/commit/53758f34ef50050a8e75ac87975816d7d328370f)
After revert this commit all build fine.
See my config file in attach.
[arm_static_nls.zip](https://github.com/crosstool-ng/crosstool-ng/files/771683/arm_static_nls.zip)

**Comment by stilor** [comment]
Should be fixed by https://github.com/crosstool-ng/crosstool-ng/pull/599; according to gettext maintainers, it is not needed in glibc-based configurations.
