### ISSUE TITLE
Build fail while trying to build static toolchain.

### ISSUE THREAD

**Issue by dorimanx** [crosstool-ng/crosstool-ng#600]
Hi.

My linux is BBQ ARCH Linux latest edition with all updates.

there is no problem to build non static toolchain.

But when i make it as STATIC to be able to share it with other people building my kernel, build is failing at same location mo matter what i change in config.

MULTILIB is not selected in config! in both cases. all the rest is default to Arch64 config 
aarch64-unknown-linux-gnueabi

googled that missing __attribute__ ((constructor)) support?? and cant find any solution...

[INFO ]  Installing pass-1 core C gcc compiler: done in 205.15s (at 16:43)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 14.34s (at 16:58)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[ERROR]      checking whether to use .ctors/.dtors header and trailer... configure: error: missing __attribute__ ((constructor)) support??
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library headers & start files'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@331]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@317]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1769]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@150]
[ERROR]  >>        called from: do_libc_start_files[scripts/build/libc/glibc.sh@112]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.22.0-583-gfbc69323/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 17:00.13)
[17:01] / make[1]: *** [/usr/local/bin/ct-ng:147: build] Error 1
make: *** [/usr/local/bin/ct-ng:150: build.32] Error 2
[dorimanx@dorimanx crosstool-ng]$

**Comment by stilor** [comment]
Please attach your .config and build.log

**Comment by dorimanx** [comment]
i have tried with latest crosstool updates and still failing at same place.
here is my config and build.log

http://www.dorimanx.com/temp/.config
http://www.dorimanx.com/temp/build.log

Thanks.

**Comment by stilor** [comment]
Try the current master and see if it fixes it.

**Comment by dorimanx** [comment]
perfect build with STATIC toolchain selected.

Many thanks for your support! you made many happy again.

[dorimanx@dorimanx crosstool-ng]$ ./ct-ng build.32
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170220.153323
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-pc-linux-gnu
[EXTRA]      host   = x86_64-pc-linux-gnu
[EXTRA]      target = aarch64-OP3T-linux-gnueabi
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.08s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 0.18s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[EXTRA]    Extracting 'linux-4.9.8'
[EXTRA]    Patching 'linux-4.9.8'
[EXTRA]    Extracting 'gmp-6.1.2'
[EXTRA]    Patching 'gmp-6.1.2'
[EXTRA]    Extracting 'mpfr-3.1.5'
[EXTRA]    Patching 'mpfr-3.1.5'
[EXTRA]    Extracting 'isl-0.18'
[EXTRA]    Patching 'isl-0.18'
[EXTRA]    Extracting 'mpc-1.0.3'
[EXTRA]    Patching 'mpc-1.0.3'
[EXTRA]    Extracting 'ncurses-6.0'
[EXTRA]    Patching 'ncurses-6.0'
[EXTRA]    Extracting 'libiconv-1.14'
[EXTRA]    Patching 'libiconv-1.14'
[EXTRA]    Extracting 'gettext-0.19.8.1'
[EXTRA]    Patching 'gettext-0.19.8.1'
[EXTRA]    Extracting 'binutils-2.27'
[EXTRA]    Patching 'binutils-2.27'
[EXTRA]    Extracting 'gcc-6.3.0'
[EXTRA]    Patching 'gcc-6.3.0'
[EXTRA]    Extracting 'glibc-2.25'
[EXTRA]    Patching 'glibc-2.25'
[INFO ]  Extracting and patching toolchain components: done in 361.95s (at 06:03)
[INFO ]  =================================================================
[INFO ]  Installing ncurses for build
[EXTRA]    Configuring ncurses
[EXTRA]    Building ncurses
[EXTRA]    Installing ncurses
[INFO ]  Installing ncurses for build: done in 17.50s (at 06:21)
[INFO ]  =================================================================
[INFO ]  Installing GMP for host
[EXTRA]    Configuring GMP
[EXTRA]    Building GMP
[EXTRA]    Installing GMP
[INFO ]  Installing GMP for host: done in 33.20s (at 06:54)
[INFO ]  =================================================================
[INFO ]  Installing MPFR for host
[EXTRA]    Configuring MPFR
[EXTRA]    Building MPFR
[EXTRA]    Installing MPFR
[INFO ]  Installing MPFR for host: done in 12.48s (at 07:07)
[INFO ]  =================================================================
[INFO ]  Installing ISL for host
[EXTRA]    Configuring ISL
[EXTRA]    Building ISL
[EXTRA]    Installing ISL
[INFO ]  Installing ISL for host: done in 6.66s (at 07:13)
[INFO ]  =================================================================
[INFO ]  Installing MPC for host
[EXTRA]    Configuring MPC
[EXTRA]    Building MPC
[EXTRA]    Installing MPC
[INFO ]  Installing MPC for host: done in 7.47s (at 07:21)
[INFO ]  =================================================================
[INFO ]  Installing libiconv for host
[EXTRA]    Skipping (included in GNU C library)
[INFO ]  Installing libiconv for host: done in 0.00s (at 07:21)
[INFO ]  =================================================================
[INFO ]  Installing gettext for host
[EXTRA]    Skipping (included in GNU C library)
[INFO ]  Installing gettext for host: done in 0.00s (at 07:21)
[INFO ]  =================================================================
[INFO ]  Installing binutils for host
[EXTRA]    Configuring binutils
[EXTRA]    Prepare binutils for static build
[EXTRA]    Building binutils
[EXTRA]    Installing binutils
[INFO ]  Installing binutils for host: done in 37.12s (at 07:58)
[INFO ]  =================================================================
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: '-mabi=lp64'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib64 (os)
[INFO ]  Installing pass-1 core C gcc compiler: done in 74.23s (at 09:12)
[INFO ]  =================================================================
[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[EXTRA]    Checking installed headers
[INFO ]  Installing kernel headers: done in 9.66s (at 09:22)
[INFO ]  =================================================================
[INFO ]  Installing C library headers & start files
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Configuring C library
[EXTRA]      Installing C library headers
[EXTRA]      Installing C library start files
[INFO ]    Building for multilib 1/1: '': done in 15.70s (at 09:38)
[INFO ]  Installing C library headers & start files: done in 15.75s (at 09:38)
[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[EXTRA]    Installing gcc
[EXTRA]    Housekeeping for core gcc compiler
[EXTRA]    gcc default flags: '-mabi=lp64'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib64 (os)
[INFO ]  Installing pass-2 core C gcc compiler: done in 117.48s (at 11:35)
[INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[EXTRA]      Installing C library
[INFO ]    Building for multilib 1/1: '': done in 208.72s (at 15:04)
[INFO ]  Installing C library: done in 208.78s (at 15:04)
[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]    gcc default flags: '-mabi=lp64'
[EXTRA]    gcc configured with these multilibs (including the default):
[EXTRA]       '' --> lib (gcc)   lib64 (os)
[INFO ]  Installing final gcc compiler: done in 207.33s (at 18:31)
[INFO ]  =================================================================
[INFO ]  Cleaning-up the toolchain's directory
[INFO ]    Stripping all toolchain executables
[EXTRA]    Installing the populate helper
[EXTRA]    Installing a cross-ldd helper
[EXTRA]    Creating toolchain aliases
[EXTRA]    Removing access to the build system tools
[EXTRA]    Removing installed documentation
[INFO ]  Cleaning-up the toolchain's directory: done in 3.58s (at 18:35)
[INFO ]  Build completed at 20170220.155158
[INFO ]  (elapsed: 18:34.76)
[INFO ]  Finishing installation (may take a few seconds)...
[18:35] / [dorimanx@dorimanx crosstool-ng]$
[dorimanx@dorimanx crosstool-ng]$

**Comment by atheod** [comment]
Hi,
had the same problem trying installing crosstool-ng version 1.22. Actually I found my way by looking at the build.log (tail -f /your/path/to/bin/build.log). Then I could spot which tarballs could not be downloaded (connection time out) and downloaded them manually. Then I had to put it into the "/your/path/to/bin/.build/tarballs" directory and run again the "ct-ng build"
