### ISSUE TITLE
New release or release candidate?

### ISSUE THREAD

**Issue by ollieparanoid** [crosstool-ng/crosstool-ng#606]
Hi there,

`crosstool-ng` seems to be really interesting. However, the last release is pretty old by now (November 2015). Is there an approximate time schedule, when the next release will come up?

If the answer would be: "when it's done™" (which is totally understandable for an open source project maintained by volunteers in their free time!), I'd recommend to make a few RC release in the meantime (starting now).

It would be a lot easier to say: I have build that toolchain with `crosstool-ng 1.22-rc2` instead of the git hash `eff79ab` ([example](https://archlinuxarm.org/wiki/Distcc_Cross-Compiling)).

Furthermore GNU/Linux distributions could already ship the rc-version in their repositories (I might actually package it at some point for a distro).

Have a nice day!

**Comment by stilor** [comment]
I think I can tag an `-rc1` in about two weeks. I have a few remaining issues that I wanted to fix before the release:
- https://github.com/crosstool-ng/crosstool-ng/issues/600
- cygwin: elf2flt fails to link (multiple definitions of `getopt`)
- cygwin: glibc/localedef fails in configure

**Comment by ollieparanoid** [comment]
Cool, thanks!

**Comment by stilor** [comment]
1.23.0 is out :)
