### ISSUE TITLE
Verify downloaded sources

### ISSUE THREAD

**Issue by ollieparanoid** [crosstool-ng/crosstool-ng#611]
I really hope that I am wrong here, but after skimming through the source, it seems that no downloaded sources get verified. Not with hashes, nor with gpg keys (better method of course).

Even worse, there are downloads from HTTP, which really make man-in-the-middle attacks trivial (by that I am not saying that switching to HTTPS would be enough!).

So... are there any plans to fix this? Without that, `crosstool-ng` seems to be completely irresponsible except when one has already downloaded and verified all sources manually.

At least, there's that flag, that disallows downloads. This must become the default in my opinion, with a huge warning message pointing to this issue, until it is fixed.

**Comment by stilor** [comment]
I don't think this will happen in 1.23. I have some plans for revamping the download management system after 1.23, so I'll keep this in mind.
