### ISSUE TITLE
need to do 'ct-ng oldconfig' before 'ct-ng build (was: stat now breaks macOS build)

### ISSUE THREAD

**Issue by flyingk** [crosstool-ng/crosstool-ng#615]
The macOS build from today's master on Sierra fails with

[INFO ]  Building environment variables
[DEBUG]  Testing '! ( -z /Volumes/ct-ng/x-tools/arm-unknown-linux-gnueabihf )'
[DEBUG]  Testing '! ( ! -w /Volumes/ct-ng/x-tools )'
[EXTRA]  Preparing working directories
[ERROR]  Unknown stat format options
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@443]
[ERROR]  >>        called from: CT_DoForceRmdir[scripts/functions@582]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@250]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'ct-ng-testing/share/doc/crosstool-ng/crosstool-ng-1.22.0-612-g1468e99/B - Known issues.txt'
[ERROR]  

This may be related to commit f9bec4ed7c4540de73c82c94053f975c5c7c29e4, since it was working from master the day before (12/2/2017).

This is the configure msg related:

checking for stat... stat
checking whether stat takes GNU or BSD format... BSD

**Comment by stilor** [comment]
Did you regenerate .config from defconfig? Attach your .config to this issue.

**Comment by stilor** [comment]
Or, by the way, `ct-ng oldconfig` should have taken care of this, too.

**Comment by mingwandroid** [comment]
Yeah I ran into this.

Since I run from a non-interactive script I do:

`yes "" | ct-ng oldconfig` to accept defaults.

**Comment by stilor** [comment]
@mingwandroid So you ran into this issue *before* or *after* you did `ct-ng oldconfig`? If it was after, can you attach the `.config` and `config/configure.in` (either from the current directory, if you use `--enable-local`, or from `$prefix/lib` where crosstool-ng was installed)?

**Comment by flyingk** [comment]
OK, thanks. This works fine. I was indeed using my old config from before because I knew that one was working. Maybe it would be good to alert the user after (re-) building the tool that the defconfig options have changed and this oldconfig step or restarting from scratch is required.

**Comment by cpackham** [comment]
Running `ct-ng oldconfig`/`ct-ng defoldconfig` when new options are added is to be expected. We also now have `ct-ng upgradeconfig` to migrate configs between versions of ct-ng so I think this can be closed
