### ISSUE TITLE
Some broken downloads

### ISSUE THREAD

**Issue by bthebaudeau** [crosstool-ng/crosstool-ng#62]
Commit 79422633cf2d0282ed2d637d2ba237cc3f4e6a8e broke the download of some older versions of packages, e.g.:
 - cloog-ppl-0.15.11.tar.gz (found on ftp://gcc.gnu.org/pub/gcc/infrastructure/),
 - mpc-0.9.tar.gz (found on http://www.multiprecision.org/mpc/download/).

**Comment by bhundven** [comment]
Thank you for the report. I will update this soon!
