### ISSUE TITLE
wget failing to fetch expat sources with 404 error

### ISSUE THREAD

**Issue by sockmonkeyws** [crosstool-ng/crosstool-ng#631]
http://downloads.sourceforge.net/project/expat/expat/2.2.0/expat-2.2.0 is broken, please change link in source and direct me how to fix it on my local copy. Thanks!

**Comment by stilor** [comment]
Works ok for me. Either a transient glitch on sourceforge download servers, or a problem in your network. Note that while the link you posted is indeed invalid, ct-ng only resorts to it after failing all the other, valid links, including the valid link http://downloads.sourceforge.net/project/expat/expat/2.2.0/expat-2.2.0.tar.bz2

Reworking package management in ct-ng is one of my todo items after 1.23.
