### ISSUE TITLE
avr+avr-libc 8-bit toolchain not supported

### ISSUE THREAD

**Issue by grant-h** [crosstool-ng/crosstool-ng#66]
I believe this would fall in to the enhancement category, but there isn't a flow for building a plain old, 8-bit AVR toolchain with avr-libc. Only avr32 with newlib seems to be supported.

**Comment by bhundven** [comment]
Ack. I'll see what we can do.

**Comment by pfalcon** [comment]
+1 for supporting little brothers like avr, msp430. Lack of support of these small targets give perception that ct-ng is big and bloated, not suitable for smaller targets at all, thus not that "versatile" at all, and that people who want to build toolchain for small targets would be better off doing that manually, which closes the vicious circle. Breaking it would be very nice.

**Comment by bhundven** [comment]
AFAIK, this is being worked on. Rest assured it will eventually be supported.

**Comment by bhundven** [comment]
Also note, this is in the 1.22 milestone.

**Comment by pfalcon** [comment]
Nice, thanks, just wanted to give +1 that such support certainly will be noticed and appreciated.

**Comment by grant-h** [comment]
:+1: Thanks for taking up the task

**Comment by bhundven** [comment]
I believe it's @enunes that is working on the AVR 8-bit support.

**Comment by enunes** [comment]
Yes I have been working on this.
Currently I am already able to locally build an AVR 8-bit toolchain. I have been using the Arch Linux recipes as reference, such as: https://projects.archlinux.org/svntogit/community.git/plain/trunk/PKGBUILD?h=packages/avr-gcc

My goal is to build some of the existing AVR C programs that I have in my repo (https://github.com/enunes/avr) seamlessly with the ct-ng avr toolchain in the same way that I used to use the distribution toolchain. I am currently able to build them but there are some path issues with avr-libc that I need to resolve. I suspect that they may be related to the sysroot feature, as none of the references that build avr-gcc toolchain use this feature.
Nevertheless, I'm quite close! Hope to publish it soon.

**Comment by bhundven** [comment]
@enunes Thank you for your work on this! Let us know if you need any help.

**Comment by grant-h** [comment]
@enunes Looking forward to testing your code

**Comment by bhundven** [comment]
I'm pushing this issue to the 1.23.0 milestone.

**Comment by bhundven** [comment]
@grant-h and @pfalcon, please test @enunes branch from pull request #124! I don't have an AVR 8-bit board. I would like to know if you have any issues.
