### ISSUE TITLE
x86_64-w64-mingw32-g++ cannot link simplest 32bit executable, but x86_64-w64-mingw32-gcc is OK

### ISSUE THREAD

**Issue by vmurashev** [crosstool-ng/crosstool-ng#663]
Using crosstool-ng from master I started from defconfig:
CT_EXPERIMENTAL=y
CT_CC_GCC_V_5_4_0=y
CT_CC_LANG_CXX=y
CT_ARCH_x86=y
CT_ARCH_64=y
CT_MULTILIB=y
CT_TARGET_VENDOR="w64"
CT_KERNEL_windows=y
CT_MINGW_DIRECTX=y
CT_MINGW_DDK=y
CT_MINGW_TOOLS=y
CT_THREADS_NATIVE=y
CT_STATIC_TOOLCHAIN=y

Build is OK, then I wrote simple file bitness.c:
#include <stdio.h>
int tab[1-2*(sizeof(void*)*8 != BITS)];
int main(int argc, char* argv[])
{
    int b = BITS;
    printf("Bitness: %d\n", b);
    return 0;
}
Link results:
./x86_64-w64-mingw32-gcc bitness.c -m64 -DBITS=64  -o w64.exe
./x86_64-w64-mingw32-gcc bitness.c -m32 -DBITS=32  -o w32.exe
./x86_64-w64-mingw32-g++ bitness.c -m64 -DBITS=64  -o w64xx.exe
./x86_64-w64-mingw32-g++ bitness.c -m32 -DBITS=32  -o w32xx.exe
/home/vet/x-tools/x86_64-w64-mingw32/bin/../lib/gcc/x86_64-w64-mingw32/5.4.0/../../../../x86_64-w64-mingw32/bin/ld: cannot find -lstdc++
collect2: error: ld returned 1 exit status

@stilor Alexey,
Could please point me out what is wrong with my default config ?

**Comment by stilor** [comment]
Your config looks right, it looks like an issue in binutils. Apparently, while GCC is configured for multilibs properly, ld is not and hence ld only searches /lib directory - but for 32-bit mode, libstdc++ resides in /lib32. Ideally, it seems, ld should be fixed to look into /lib32.

Until then, though, crosstool-ng will have to invent some workaround.

We need to move the libraries into the sysroot directory for options -static-libstdc++ to work. It looks like creating symlinks from the old location helps with this test case:

````
avn@mistral:~/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib32$ ll
total 8
drwxr-xr-x 2 avn avn 4096 Mar 28 00:27 ./
drwxr-xr-x 8 avn avn 4096 Mar 27 23:53 ../
lrwxrwxrwx 1 avn avn   28 Mar 28 00:27 libatomic.a -> ../sysroot/lib32/libatomic.a
lrwxrwxrwx 1 avn avn   28 Mar 28 00:27 libstdc++.a -> ../sysroot/lib32/libstdc++.a
lrwxrwxrwx 1 avn avn   28 Mar 28 00:27 libsupc++.a -> ../sysroot/lib32/libsupc++.a
lrwxrwxrwx 1 avn avn   25 Mar 28 00:27 libvtv.a -> ../sysroot/lib32/libvtv.a
lrwxrwxrwx 1 avn avn   31 Mar 28 00:27 libvtv_stubs.a -> ../sysroot/lib32/libvtv_stubs.a
avn@mistral:~/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib$ ll
total 8
drwxr-xr-x 2 avn avn 4096 Mar 28 00:28 ./
drwxr-xr-x 8 avn avn 4096 Mar 27 23:53 ../
lrwxrwxrwx 1 avn avn   26 Mar 28 00:28 libatomic.a -> ../sysroot/lib/libatomic.a
lrwxrwxrwx 1 avn avn   26 Mar 28 00:28 libstdc++.a -> ../sysroot/lib/libstdc++.a
lrwxrwxrwx 1 avn avn   26 Mar 28 00:28 libsupc++.a -> ../sysroot/lib/libsupc++.a
lrwxrwxrwx 1 avn avn   23 Mar 28 00:28 libvtv.a -> ../sysroot/lib/libvtv.a
lrwxrwxrwx 1 avn avn   29 Mar 28 00:28 libvtv_stubs.a -> ../sysroot/lib/libvtv_stubs.a
````
I'll add creation of such symlinks before rc2 and will check if it breaks anything. Meanwhile you can create such symlinks manually and test if it works for you.

**Comment by vmurashev** [comment]
Thanks for details and quick workaround.
Yes, after symlinks creation compiler and linker works well,
and created binaries works on Windows as expected

**Comment by stilor** [comment]
Should be fixed by the devilish PR referenced above.
