### ISSUE TITLE
ct-ng will not cuild anymore - missing files/broken links?

### ISSUE THREAD

**Issue by gearhead** [crosstool-ng/crosstool-ng#664]
I am trying to build an armv6 cross compiler on an Arch VM. I have the VM running and am trying to follow the instructions here:
[](https://archlinuxarm.org/wiki/Distcc_Cross-Compiling)
I get all the way down to:

> ./ct-ng build
and get this:
```
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'make-4.2.1'
[EXTRA]    Saving 'make-4.2.1.tar.bz2' to local storage
[ERROR]    linux: Unable to read /home/alarm/cross/src/linux-4.10.tar.xz, make sure the setting is correct and double check the permissions!
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Retrieving needed toolchain components' tarballs'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@441]
[ERROR]  >>        called from: CT_GetCustom[scripts/functions@756]
[ERROR]  >>        called from: do_kernel_get[scripts/build/kernel/linux.sh@28]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@603]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/alarm/cross/share/doc/crosstool-ng/crosstool-ng-1.23.0-rc1-4-g32909ec6/B - Known issues.txt'
```

The only file in src at this point is: make-4.2.1.tar.bz2. The linux-4.10.tar.gz and others are not downloaded and some of the files are NLA on the internet. I was able to find some of them, but gave up and grabbed the pre-built chains from higher up on the page. could this be fixed? I do not know if the older packaes will work or not, but will try them out.

**Comment by stilor** [comment]
http://crosstool-ng.github.io/support/

**Comment by stilor** [comment]
No build log, no .config. As to files being unavailable - ct-ng attempts to download each component's tarball with all supported extensions (.xz, .bz2, .lzma, .gz). It is not an error if some of them do not exist.

**Comment by gearhead** [comment]
Ok, I am just trying to tell you this does not work 'as is'  for a new install based on the instructions given. I did a fresh install of Arch x64 and followed the instructions and did not complete. I gave up on that and tried the "Pre-built crosstool-ng toolchains" and that also did not work. I ended up using the package from WarheadsSE that is based on this work and linked in the page. I edited his PKGBUILD script to use the current md5sums of the cross compile *.tar.xz packages it downloaded. When I ran it the second time the package built successfully. I installed it and am able to compile using distccd!! (yes, even on a machine running in a VM!)

As for this package, the instructions I was following are here:
https://archlinuxarm.org/wiki/Distcc_Cross-Compiling

I modified nothing and followed the web page exactly. When it gets to the './ct-ng build' Teh instructions fail because 'build' cannot download packages that no longer exist and if those do not exist it cannot build. I started trying to find them individually on the web, but some are versions which do not exist any more. Do with this information as you wish.

**Comment by stilor** [comment]
The packages do exist. For example, Linux 4.10 is here: https://www.kernel.org/pub/linux/kernel/v4.x/linux-4.10.tar.xz
I asked you to submit a bug with all the pertinent information, including a build log that might give me an idea what went wrong. I understand, attaching a file is too complicated, I must somehow provide you with a solution without it.

**Comment by bg172** [comment]
I can reproduce this issue whil trying to build armv8 cross-compiler, see the requested files in the attached archive. Thanks
[bin.zip](https://github.com/crosstool-ng/crosstool-ng/files/949274/bin.zip)

**Comment by stilor** [comment]
Your .config requests a "custom Linux", which, as explained in the help message for KERNEL_LINUX_CUSTOM_LOCATION, is:

````
      Enter the path to the directory or tarball of your source for linux.

      If the path is a tarball, it should extract to: <name>-<version>/
      where the name is this component, linux, and the version is set
      below in the custom version string.
````
It seems that the path in your configuration, `/home/bg/cross/src/linux-4.10.tar.xz`, does not exist.

Custom means "provided by you", not the stock kernel. This is why ct-ng does not even attempt to download it.

**Comment by bg172** [comment]
ok, provided linux-4.10.tar.xz (and others) to the ./src folder, but reported https://github.com/crosstool-ng/crosstool-ng/issues/696 :)
