### ISSUE TITLE
ct-ng build fails with warning and associate errors: "Don't know how to handle 'cloog-0.18.1': unknown extension" 

### ISSUE THREAD

**Issue by electronicsguy** [crosstool-ng/crosstool-ng#67]
Hello,
    I am trying to build an ARM compiler for my raspberry pi. I downloaded crosstool-ng, did all steps till sudo make install, added the bin directory to my path. I am now trying to do build the compiler. However, it fails with this error:

~/Downloads/crosstool-ng$ ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20150417.175054
[INFO ]  Building environment variables
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[INFO ]  Retrieving needed toolchain components' tarballs: done in 0.11s (at 00:02)
[INFO ]  =================================================================
[INFO ]  Extracting and patching toolchain components
[WARN ]    Don't know how to handle 'cloog-0.18.1': unknown extension
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: do_cloog_extract[scripts/build/companion_libs/130-cloog.sh@963]
[ERROR]  >>        called from: do_companion_libs_extract[scripts/build/companion_libs.sh@22]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@606]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/opt/cross-rpi/share/doc/crosstool-ng/ct-ng.1.20.0/B - Known issues.txt'
[ERROR]   
[ERROR]  (elapsed: 0:02.59)
[00:03] / make: *** [build] Error 1

I search online for this problem but couldn't find any solution. I then installed these:
sudo apt-get install libcloog-isl-dev
sudo apt-get install libcloog-ppl-dev 

deleted the partial files in the .build directory and retried, but with the same error. Could someone tell me what the problem is?
(The build.log doesn't have any more information. I was following the steps outlined in this blog: http://www.bootc.net/archives/2012/05/26/how-to-build-a-cross-compiler-for-your-raspberry-pi/)

config:
Linux 3.13.0-22-generic #44-Ubuntu
gcc 4.8.2-19

**Comment by bhundven** [comment]
Well, I don't install crosstool-ng to /opt/cross, I'm sure that's not the problem...

I install to either ~/ct-ng or ~/.local ... regardless, the build.log does have more info that isn't being shared here. Also, we don't care if the host has the libcloog-{isl,ppl}-dev packages, we just build them anyways and reference the directories they live in, forcibly. In the future, I'd like to see a change that checks the host for these libraries before building them, but where obviously not there yet.

Back on topic, post the build.log and .config to a gist (gist.github.com) and post the link here for further review.

Thanks,

-Bryan

**Comment by electronicsguy** [comment]
Thank Bryan. Sorry I didnt' realise the build.log output has more info. I've posted both the files in the gist located at: https://gist.github.com/electronicsguy/22d9c0e8363451ba913c

Please let me know if you need any more info.

**Comment by bhundven** [comment]
One thing I see, is that you are building your toolchain in the crosstool-ng directory.
I've never tried this, and is not how you use crosstool-ng.

Remove your current downloads and try this instead:
```
cd $HOME
git clone https://github.com/crosstool-ng/crosstool-ng
cd crosstool-ng
./bootstrap
./configure --prefix=$HOME/.local
make
make install
cd $HOME
mkdir -p build/arm
cd build/arm
export PATH="$HOME/.local/bin:$PATH"
ct-ng arm-unknown-linux-gnueabi
ct-ng menuconfig
```

At this point, you're in menuconfig, and you can make the config changes you want for your specific target. Now you exit saving your config and do:

```
ct-ng build
```

If you have problems at this point, go ahead and respond here.

Cheers,

-Bryan

**Comment by lundmar** [comment]
FYI - if you do insist on building in the crosstool-ng source directory you can use the --enable-local option like so:
./configure --enable-local
./ct-ng
./ct-ng arm-unknown-linux-gnueabi
./ct-ng menuconfig

**Comment by bhundven** [comment]
On Apr 17, 2015 10:19 PM, "Martin Lund" <notifications@github.com> wrote:
>
> FYI - if you do insist on building in the crosstool-ng source directory
you can use the --enable-local option like so:
> ./configure --enable-local
> ./ct-ng
> ./ct-ng arm-unknown-linux-gnueabi
> ./ct-ng menuconfig

+1

**Comment by electronicsguy** [comment]
Thank you! I don't know exactly how but it worked. I built it in a different directory. (Why should that matter so much by the way?)

Anyways, it generated this executable compiler:
arm-unknown-gnueabi-gcc

On my raspberrypi, it shows this:
arm-linux-gnueabihf-gcc

I think I had asked for "hard float" or something like that in the menu-config. So is the cross-compiler I made compatible with hard float? Or does it need to specify special options while compiling?

I tried out a simple hello world test program and that works when I copy it onto my Pi. But I don't know if that uses any hard-float instructions or no.

Sorry for so many questions. Its the first time I've done this and I'm still trying to learn.

**Comment by bhundven** [comment]
This issue seems to be resolved. Reopen if there are still further issues. Thanks!

**Comment by electronicsguy** [comment]
"I think I had asked for "hard float" or something like that in the menu-config. So is the cross-compiler I made compatible with hard float? Or does it need to specify special options while compiling?"

could you tell me how to check if it support hard float or no?

**Comment by gerrymanley** [comment]
Hi Bryan,
I have followed your instructions above and get stopped at "ct-ng arm-unknown-linux-gnueabi"
I get: gerry@gerry-ESPRIMO-E:/home/build/arm$ sudo -i  ct-ng arm-unknown-linux-gnueabi
-bash: ct-ng: command not found

can't seem to get any further......can you assist please

/Gerry

**Comment by jasmin-j** [comment]
> have followed your instructions above and get stopped at "ct-ng arm-unknown-linux-gnueabi"
> I get: gerry@gerry-ESPRIMO-E:/home/build/arm$ sudo -i ct-ng arm-unknown-linux-gnueabi
> -bash: ct-ng: command not found

First of all, why you use "sudo"?
Please follow the steps from @lundmar. I use this approach also for my cross toolchains.

I guess your problem is the missing "./" before ct-ng. Most Linux distributions doesn't add the "." to the path and thus, ct-ng is not found by bash, when you execute it within the ct-ng build directory.
If you don't use the local build approach (--enable-local) and install ct-ng to your system directory, then you have to have the install directory within the path.

BR
   Jasmin

**Comment by gerrymanley** [comment]
Hi Jasmin,
I am trying this Cross-compiling FFmpeg for Raspbian at link: https://trac.ffmpeg.org/wiki/CompilationGuide/RaspberryPi#no1, unfortunately I failed...not a programmer just hobbyist but drastically need to compile FFmpeg with h.264 support as I will be using it on the rasp2 and compute. I get stuck each time when it comes to running ct-ng.....I have found "solved" stating I should chmod the ct-ng dir.  Basically I have not found a beginners guide to installing crosstool-ng correctly. I'll keep looking..............thanks /Gerry

**Comment by bhundven** [comment]
I would prefer that questions like this go to the crossgcc mailing list (which all of us here watch and respond to!): crossgcc@sourceware.org

This is not an issue as much as it is a conversation/support. The instructions from above and on the ffmpeg site are correct. Please use the mailing list instead!

Thanks!

**Comment by reetikavats** [comment]
Thanks..It helped me too. it is going on. atleast earlier issues resolved...

**Comment by reetikavats** [comment]
[ERROR]    make[5]: *** [Makefile:2561: /home/reetikavats/build/arm/.build/src/gettext-0.19.8.1/gettext-tools/src/Makefile.in] Error 127
[ALL  ]    make[5]: Leaving directory '/home/reetikavats/build/arm/.build/arm-unknown-linux-gnueabi/build/build-gettext-host-x86_64-build_pc-linux-gnu/gettext-tools/src'
[ERROR]    make[4]: *** [Makefile:2026: all-recursive] Error 1
[ALL  ]    make[4]: Leaving directory '/home/reetikavats/build/arm/.build/arm-unknown-linux-gnueabi/build/build-gettext-host-x86_64-build_pc-linux-gnu/gettext-tools'
[ERROR]    make[3]: *** [Makefile:1892: all] Error 2
[ALL  ]    make[3]: Leaving directory '/home/reetikavats/build/arm/.build/arm-unknown-linux-gnueabi/build/build-gettext-host-x86_64-build_pc-linux-gnu/gettext-tools'
[ERROR]    make[2]: *** [Makefile:414: all-recursive] Error 1
[ALL  ]    make[2]: Leaving directory '/home/reetikavats/build/arm/.build/arm-unknown-linux-gnueabi/build/build-gettext-host-x86_64-build_pc-linux-gnu'
[ERROR]    make[1]: *** [Makefile:370: all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/reetikavats/build/arm/.build/arm-unknown-linux-gnueabi/build/build-gettext-host-x86_64-build_pc-linux-gnu'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing gettext for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@331]
[ERROR]  >>        called from: do_gettext_backend[scripts/build/companion_libs/330-gettext.sh@131]
[ERROR]  >>        called from: do_gettext_for_host[scripts/build/companion_libs/330-gettext.sh@53]
[ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@648]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/reetikavats/.local/share/doc/crosstool-ng/crosstool-ng-1.22.0-541-g1877577/B - Known issues.txt'
[ERROR]  
[ERROR]  (elapsed: 7:29.66)   Kindly have a look

**Comment by stilor** [comment]
Please try with ct-ng build.1 (this makes the logs easier to read). Then please attach the .config and build.log files to this issue.

**Comment by xmaze** [comment]
@reetikavats i have same error as your's, have you fix it?
