### ISSUE TITLE
mingw-w64 cannot be built with gold (was: mingw-w64-crt configure failure)

### ISSUE THREAD

**Issue by tamird** [crosstool-ng/crosstool-ng#674]
crosstool-ng-1.23.0-rc2

defconfig:
```
CT_EXPERIMENTAL=y
CT_ALLOW_BUILD_AS_ROOT=y
CT_ALLOW_BUILD_AS_ROOT_SURE=y
CT_LOCAL_TARBALLS_DIR="/src"
CT_PREFIX_DIR="${CT_PREFIX:-/x-tools}/${CT_HOST:+HOST-${CT_HOST}/}${CT_TARGET}"
CT_ARCH_x86=y
CT_ARCH_64=y
CT_KERNEL_windows=y
CT_BINUTILS_LINKER_GOLD=y
CT_BINUTILS_GOLD_THREADS=y
CT_BINUTILS_PLUGINS=y
# CT_MINGW_TOOLS is not set
# CT_CC_GCC_ENABLE_TARGET_OPTSPACE is not set
CT_CC_LANG_CXX=y
# CT_COMP_TOOLS_automake is not set
# CT_COMP_TOOLS_libtool is not set

```

excerpt from build.log:

```
'/build/.build/src/mingw-w64-v5.0.1/mingw-w64-crt/configure' '--with-sysroot=/x-tools/x86_64-unknown-mingw32/x86_64-unknown-mingw32/sysroot' '--prefix=/usr/x86_64-unknown-mingw32' '--build=x86_64-build_pc-linux-gnu' '--host=x86_64-unknown-mingw32'

checking _mingw_mac.h usability... no
checking _mingw_mac.h presence... no
checking for _mingw_mac.h... no
configure: error: Please check if the mingw-w64 header set and the build/host option are set properly.
```

`_mingw_mac.h` is actually located at `${sysroot}${prefix}/include/_mingw_mac.h`:
```
/x-tools/x86_64-unknown-mingw32/x86_64-unknown-mingw32/sysroot/usr/x86_64-unknown-mingw32/include/_mingw_mac.h
```

I'm not really sure where to go from here, or how to debug. Tagging @stilor because you've most recently contributed fixes in this area.

**Comment by stilor** [comment]
You don't have your tuple's vendor string set to 'w64', as in the sample for mingw-w64. I don't know if this is the reason for this failure, but I know that mingw-w64 is picky about it.

FWIW, I don't see any issues with the stock mingw-w64 samples on the machines I tested so far.

**Comment by tamird** [comment]
Same thing with vendor string set to 'w64':
```
CT_EXPERIMENTAL=y
CT_ALLOW_BUILD_AS_ROOT=y
CT_ALLOW_BUILD_AS_ROOT_SURE=y
CT_LOCAL_TARBALLS_DIR="/src"
CT_PREFIX_DIR="${CT_PREFIX:-/x-tools}/${CT_HOST:+HOST-${CT_HOST}/}${CT_TARGET}"
CT_ARCH_x86=y
CT_ARCH_64=y
CT_TARGET_VENDOR="w64"
CT_KERNEL_windows=y
CT_BINUTILS_LINKER_GOLD=y
CT_BINUTILS_GOLD_THREADS=y
CT_BINUTILS_PLUGINS=y
# CT_MINGW_TOOLS is not set
# CT_CC_GCC_ENABLE_TARGET_OPTSPACE is not set
CT_CC_LANG_CXX=y
# CT_COMP_TOOLS_automake is not set
# CT_COMP_TOOLS_libtool is not set
```

[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/902939/build.log.txt)

There's something odd here: https://github.com/crosstool-ng/crosstool-ng/blob/crosstool-ng-1.23.0-rc2/scripts/build/libc/mingw.sh#L72:L83 - this code seems to run only on version 4, but I'm pretty sure the default is now 5.x.

**Comment by tamird** [comment]
OK, I think I figured it out - it looks as though running `CC=gcc CXX=g++ /usr/local/ct-ng/bin/ct-ng build` rather than `/usr/local/ct-ng/bin/ct-ng build` is the culprit. Perhaps that's causing the crt build to use the host's gcc rather than the newly built toolchain's gcc. That would be pretty unfortunate.

However, it turns out that the vendor prefix also matters, because without setting it to `w64`, I ran into https://github.com/crosstool-ng/crosstool-ng/issues/132, where @mingwandroid correctly pointed out that the issue is gcc's [config.cc](https://github.com/gcc-mirror/gcc/blob/gcc-6_3_0-release/gcc/config.gcc#L1723:L1725) which looks for `*-w64-*` in the target triple.

The whole setup here is pretty fragile; it's never possible to build a gcc-based mingw-w64 toolchain. I think w64 should, at least, be the default vendor.

Now that I've removed `CC=gcc CXX=g++`, I get further:
```
[INFO ]  Building mingw-w64
[EXTRA]    Configuring mingw-w64-crt
[EXTRA]    Building mingw-w64-crt
[EXTRA]    Installing mingw-w64-crt
[INFO ]  Building mingw-w64: done in 281.37s (at 08:29)
[08:29] / /usr/local/ct-ng/lib/crosstool-ng-1.23.0-rc2/scripts/build/libc/mingw.sh: line 212: [: =: unary operator expected
[INFO ]  =================================================================
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    configure: error: in `/build/.build/x86_64-w64-mingw32/build/build-cc-gcc-final/x86_64-w64-mingw32/libatomic':
[ERROR]    configure: error: C compiler cannot create executables
[ERROR]    make[2]: *** [configure-target-libatomic] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    checking for sin in -lm... configure: error: Link tests are not allowed after GCC_NO_EXECUTABLES.
[ERROR]    make[2]: *** [configure-target-libstdc++-v3] Error 1
[ERROR]    make[1]: *** [all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@331]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@1145]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@832]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/ct-ng/share/doc/crosstool-ng/crosstool-ng-1.23.0-rc2/B - Known issues.txt'
[ERROR]
[ERROR]  (elapsed: 10:31.49)
[10:32] / /usr/local/ct-ng/bin/ct-ng:147: recipe for target 'build' failed
```

The first bit, a syntax error in a shell script, is fixed in https://github.com/crosstool-ng/crosstool-ng/pull/675.

The next error, a linking issue, or something, seems to be a result of my having not specified `CT_THREADS_POSIX=y`, as the sample does, though I have no idea why.

mingw-builds "fixed" this in an interesting way: https://github.com/niXman/mingw-builds/commit/55b09354619abdcc84c308dbac830c01a9ba4786#diff-7391f7c1e0be7e61124da9a06a8a7a58 but I haven't a clue if this is the right thing to do or not.

**Comment by tamird** [comment]
cc @niXman in case he has some insight.

Also linking the original mingw-builds issue: https://github.com/niXman/mingw-builds/issues/414.

**Comment by tamird** [comment]
Here's [config.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/903905/config.log.txt) for the failing bit (/build/.build/x86_64-w64-mingw32/build/build-cc-gcc-final/x86_64-w64-mingw32/libatomic/config.log).

Interestingly, it contains:
```
configure:3566: checking for C compiler default output file name
configure:3588: /build/.build/x86_64-w64-mingw32/build/build-cc-gcc-final/./gcc/xgcc -B/build/.build/x86_64-w64-mingw32/build/build-cc-gcc-final/./gcc/ -L/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib -L/x-tools/x86_64-w64-mingw32/mingw/lib -isystem /x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/include -isystem /x-tools/x86_64-w64-mingw32/mingw/include -B/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/bin/ -B/x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/lib/ -isystem /x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/include -isystem /x-tools/x86_64-w64-mingw32/x86_64-w64-mingw32/sys-include       conftest.c  >&5
/build/.build/x86_64-w64-mingw32/build/build-cc-gcc-final/./gcc/collect-ld: 106: exec: -m: not found
collect2: error: ld returned 127 exit status
configure:3592: $? = 1
configure:3629: result: 
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU Atomic Library"
| #define PACKAGE_TARNAME "libatomic"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "GNU Atomic Library 1.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL "http://www.gnu.org/software/libatomic/"
| #define PACKAGE "libatomic"
| #define VERSION "1.0"
| /* end confdefs.h.  */
| 
| int
| main ()
| {
| 
|   ;
|   return 0;
| }
configure:3635: error: in `/build/.build/x86_64-w64-mingw32/build/build-cc-gcc-final/x86_64-w64-mingw32/libatomic':
configure:3639: error: C compiler cannot create executables
```

which possibly implicates my use of `CT_BINUTILS_LINKER_GOLD=y`. Trying without `CT_BINUTILS_LINKER_GOLD=y` now.

**Comment by tamird** [comment]
Confirmed, not using gold fixes this.

**Comment by stilor** [comment]
I'll keep it open as a reminder to make a dependency on !LINKER_GOLD after 1.23. Thanks for getting to the bottom of this.

As you might have noticed, it may be a good idea to start off an existing example (which are known to at least build) and tweak one option at a time.
