### ISSUE TITLE
add config option for SSP in glibc (was: ssp always enabled on glibc builds)

### ISSUE THREAD

**Issue by ikv** [crosstool-ng/crosstool-ng#681]
Glibc toolchain supports ssp even if `CT_CC_GCC_LIBSSP=n`

Tested on crosstool-ng-1.23.0-rc2-7-gee7662, Ubuntu 16.04.02

GCC successfully produces ssp binaries, but shouldn't:
```
$ echo 'void main(){}' | ./armv7a-unknown-linux-gnueabihf/bin/armv7a-unknown-linux-gnueabihf-gcc -x c - -o - -fstack-protector-all  | ./armv7a-unknown-linux-gnueabihf/bin/armv7a-unknown-linux-gnueabihf-objdump -t - | grep __stack_chk
00020f08 g     O .data.rel.ro   00000004              __stack_chk_guard@@GLIBC_2.4
00000000       F *UND*  00000000              __stack_chk_fail@@GLIBC_2.4
```
`gcc -v` says libssp disabled:
```
$ ./armv7a-unknown-linux-gnueabihf/bin/armv7a-unknown-linux-gnueabihf-gcc -v 2>&1 | grep -c -- '--disable-libssp'
1
```
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/910369/build.log.zip)
[defconfig](https://github.com/crosstool-ng/crosstool-ng/files/910372/defconfig.zip)
[dotconfig](https://github.com/crosstool-ng/crosstool-ng/files/910396/dotconfig.zip)

**Comment by bembam** [comment]
@ikv I am facing problem in using the crosstool-ng. The build is not successful. I am new in dealing with it. I could not locate the build.log file in my directories. Please help me.

**Comment by stilor** [comment]
@bembam Stop hijacking other issues. Instead, go read the http://crosstool-ng.github.io/support/ and follow the directions.

**Comment by ikv** [comment]
@stilor do you need more info?

**Comment by ikv** [comment]
As as side note, for musl `CT_CC_GCC_LIBSSP=n` does disables ssp.

**Comment by stilor** [comment]
Not a bug. GCC's options `-fstack-protector*` are always enabled. 

libssp is a separate, standalone implementation of stack protection - useful, for example, for freestanding implementations.

At configure time, GCC checks if the target libc provides the implementation of this symbol, `__stack_chk_fail`. GNU libc 2.4+ and musl always do; uClibc-ng has it as an option. If target libc lacks this symbol, GCC will add `-lssp_nonshared -lssp` to the link spec when any stack protector option is in effect; those libraries may or may not use GCC's implementation.

Glibc's configure switch only determines if the stack protector is enabled for the functions in the glibc itself. It doesn't influence whether glibc can support a program compiled/linked with `-fstack-protector-all` or whether the compiler implements that option.

Contrary to what you've said, musl-based toolchain behaves in exactly the same way.

What is wrong with ct-ng is that uClibc's SSP support is controlled by GCC's `CT_CC_GCC_LIBSSP` option - which is the opposite of what one would expect: if libc provides SSP, libssp is not required.

I'll fix that + add an option to control glibc's build wrt the SSP inside the library.
