### ISSUE TITLE
1.23.0-rc2 fail to build newlib 1.20,  HUNK fail due to mismatch in '110-fix-eabihf.patch' tab/whitespace

### ISSUE THREAD

**Issue by ehoffman2** [crosstool-ng/crosstool-ng#684]
Building with newlib-1.20, ct-ng fail to build due to a mismatch in tab/whitespaces between original and patch.

...
[DEBUG]    Entering '/home/ehoffman/share/tmp/crosstool-ng-1.23.0.rc2/.build/src/newlib-1.20.0'
[EXTRA]    Patching 'newlib-1.20.0'
[DEBUG]    Looking for patches in '/usr/local/lib/crosstool-ng-1.23.0-rc2/patches/newlib/1.20.0'...
[DEBUG]    ==> Executing: '/usr/bin/patch' '--no-backup-if-mismatch' '-g0' '-F1' '-p1' '-f' '-i' '/usr/local/lib/crosstool-ng-1.23.0-rc2/patches/newlib/1.20.0/100-fix-unaligned-access-memcpy-m68k.patch' 
[ALL  ]    patching file newlib/libc/machine/m68k/memcpy.S
[DEBUG]    ==> Executing: '/usr/bin/patch' '--no-backup-if-mismatch' '-g0' '-F1' '-p1' '-f' '-i' '/usr/local/lib/crosstool-ng-1.23.0-rc2/patches/newlib/1.20.0/110-fix-eabihf.patch' 
[ALL  ]    patching file libgloss/arm/configure.in
[ALL  ]    Hunk #1 FAILED at 49.
[ALL  ]    1 out of 1 hunk FAILED -- saving rejects to file libgloss/arm/configure.in.rej
...

And the reject is:
```
--- libgloss/arm/configure.in    2006-05-10 22:51:40.000000000 +0200
+++ libgloss/arm/configure.in 2015-01-04 15:27:41.471549917 +0100
@@ -49,7 +49,7 @@
 LIB_AM_PROG_AS
 
 case "${target}" in
-  *-*-elf | *-*-eabi)
+  *-*-elf | *-*-eabi*)
    objtype=elf-
    ;;
   *-*-coff)
```

The original file have some tabs (represented by [tab] here).

```
LIB_AM_PROG_AS

case "${target}" in
  *-*-elf | *-*-eabi)
[tab]objtype=elf-
[tab];;
  *-*-coff)
[tab]objtype=coff-
[tab];;
esac


```

If you add the option '-l' to patch (lower-case l), or have the tabs matching in the patch file, it pass properly.

Regards,
Eric Hoffman

**Comment by stilor** [comment]
https://github.com/crosstool-ng/crosstool-ng/pull/685
