### ISSUE TITLE
fatal error: limits.h: No such file or directory

### ISSUE THREAD

**Issue by CatsMum** [crosstool-ng/crosstool-ng#687]
Using crosstool-ng-1.22.0 to build toolset for x86_64/uclibc.
Using buildroot-2017.02 to build a Linux image.
During compilation of busybox, I get this error:
`x-tools/x86_64-unknown-linux-uclibc/lib/gcc/x86_64-unknown-linux-uclibc/6.3.0/include-fixed/limits.h:168:61: fatal error: limits.h: No such file or directory`

It seems to me that the problem lies with the toolset built by crosstool. The application (busybox) just uses `#include <limits.h>` quite innocently.
[buildroot.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/917806/buildroot.config.txt)
[crosstool.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/917805/crosstool.config.txt)
[linux.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/917807/linux.config.txt)
[uclibc.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/917804/uclibc.config.txt)

**Comment by stilor** [comment]
Your crosstool.config refers to package versions that were not present in 1.22.0. Please post the version as reported by `ct-ng version`. Are you using master?

Also build logs would be helpful.

FWIW, a simple file that does `#include <limits.h>` compiles just fine using the toolchain built with the `x86_64-unknown-linux-uclibc` sample:

````
avn@mistral:~/work/ctng$ cat x.c 
#include <limits.h>

int main(void) { return 0; }
avn@mistral:~/work/ctng$ ~/x-tools/x86_64-unknown-linux-uclibc/bin/x86_64-unknown-linux-uclibc-gcc -o x x.c
````

**Comment by stilor** [comment]
FYI, if you are running a modified crosstool-NG, it would've been mighty nice of you to say that in the very beginning. No version of crosstool-NG had a set of versions like this:

````
CT_LIBC_UCLIBC_NG_V_1_0_22=y
# CT_LIBC_UCLIBC_NG_V_1_0_9 is not set
# CT_LIBC_UCLIBC_V_0_9_33_2 is not set
CT_LIBC_UCLIBC_NG_1_0_9_or_later=y
CT_LIBC_UCLIBC_NG_1_0_0_or_later=y
CT_LIBC_UCLIBC_0_9_33_2_or_later=y
````

or this

````
CT_BINUTILS_V_2_28=y
# CT_BINUTILS_V_2_25_1 is not set
# CT_BINUTILS_V_2_25 is not set
# CT_BINUTILS_V_2_24 is not set
````

That is, if you do your own change, you've got to do your own debugging too. No free cake.

**Comment by stilor** [comment]
And the same trivial example also works with current `master`.

**Comment by CatsMum** [comment]
I don't know if you're more irritated or if I'm more embarrassed. Someone sent me this version. Tried with master (that's to say, I used git clone) which gave me crosstool-ng-1.23.0-rc2-15-gcde8fb08. For information - this version gave me the same error. The crosstool config is attached - I kept the changes to the bare minimum.
[toolkit.plain.vanilla.txt](https://github.com/crosstool-ng/crosstool-ng/files/920348/toolkit.plain.vanilla.txt)

**Comment by stilor** [comment]
Ok, I retried the build with the new config you posted. Yes, the minimal example worked fine with the produced toolchain. So, at the very least, it is not some "innocent inclusion of limits.h" as you claim.

I even went as far as trying to build the buildroot with the config you posted.

Guess what? You also used a hacked buildroot version!!! Last time I checked, buildroot 2017.02 did not have an option `BR2_EXTERNAL_ROUTER_APU2_PATH`. And again, you so conveniently forgot to mention that. Let me guess, it was also *sent to you by somebody*, right?

Now, you did not provide the busybox config, so I took the default `busybox.config` supplied with buildroot 2017.02 and voilà, busybox built just fine. Were the busybox sources also *sent to you by somebody*?

The build stopped in Linux because you had 'GCC Plugins' enabled in Linux config, but not in the crosstool-NG config. With that fixed, it than failed because you didn't provide the custom 'device_table' file that you're using. After substituting default, `make all` in buildroot succeeded.

Well, I'll let that mysterious *somebody* debug this problem further. You can submit a new issue when you have a problem reproducible with stock versions of crosstool-NG/buildroot/busybox. Preferably, the problem should be isolated into a standalone test case that does not require rebuilding the whole buildroot tree.

**Comment by CatsMum** [comment]
Actually, I followed the documentation for buildroot exactly and what 
you object to is described in chapter 9 of the manual, "Project-specific 
customisation".

**Comment by stilor** [comment]
Ok, sorry about "hacked buildroot". This doesn't change that a stock buildroot 2017.02 with stock busybox and stock busybox.config build fine. I don't have your customizations so I cannot vouch for them.

Also, just in case: are you using stock versions of everything that goes into crosstool-NG? uClibc-NG, Linux, GCC, binutils? Nothing *sent by somebody*?

Try to compile the simple example I posted earlier and see if it builds for you. If it fails, we can go from there. If it builds, start with a pristine, unmodified buildroot/busybox sources and apply back your changes one at a time until you see which one makes the build fail. Then isolate the test case, e.g. "#include <limits.h> fails if macro FOO is defined before the inclusion". Most likely it is not an issue with crosstool-NG, but rather with your customizations or with one of the upstream components.

**Comment by CatsMum** [comment]
OK. I'll do this incrementally. Start out with plain vanilla everything. 
Then tweak one thing and see what happens. Rinse and repeat. Talk again 
in about week!

**Comment by CatsMum** [comment]
Created a clean Arch Linux install.
Then executed:
`wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.22.0.tar.bz2`
`wget http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.22.0.tar.bz2.sig`
signatures verified:
`gpg: assuming signed data in 'crosstool-ng-1.22.0.tar.bz2'`
`gpg: Signature made Fri 20 Nov 2015 13:08:45 UTC`
`gpg:                using RSA key CAD7C8FC35B871D1`
`gpg: Good signature from "Bryan Hundven <bryanhundven@gmail.com>" [expired]`
`gpg:                 aka "Bryan Hundven <bryanhundven@live.com>" [expired]`
`gpg:                 aka "Bryan Hundven <bryanhundven@icloud.com>" [expired]`
`gpg:                 aka "Bryan Hundven <bryanhundven@android-x86.org>" [expired]`
`gpg:                 aka "Bryan Hundven <bryan.hundven@zonarsystems.com>" [expired]`
`gpg:                 aka "[jpeg image of size 3080]" [expired]`
`gpg:                 aka "[jpeg image of size 16246]" [expired]`
`gpg: Note: This key has expired!`
`Primary key fingerprint: 561E D9B6 2095 88ED 23C6  8329 CAD7 C8FC 35B8 71D1`
Despite the errors, I think that the signature is valid.
Then:
`tar -jxf downloads/crosstool-ng-1.22.0.tar.bz2`
`cd crosstool-ng/`
`./configure --prefix=/usr` <- no errors

`make` produces the errors below:
`In file included from zconf.tab.c:212:0:`
`zconf.hash.c:167:1: error: conflicting types for ‘kconf_id_lookup’`
` kconf_id_lookup (register const char *str, register size_t len)`
` ^~~~~~~~~~~~~~~`
`zconf.hash.c:34:31: note: previous declaration of ‘kconf_id_lookup’ was here`
` static const struct kconf_id *kconf_id_lookup(register const char *str, register unsigned int len);`
`                               ^~~~~~~~~~~~~~~`

Obtained a patch to fix this from Arch Linux repository:
[gperf-size_t.diff.txt](https://github.com/crosstool-ng/crosstool-ng/files/922346/gperf-size_t.diff.txt)
and then obtained a clean compilation.
`sudo make install` completed without error

`mkdir tools-1.22`
`cd tools-1.22`
`ct-ng x86_64-unknown-linux-uclibc`
`ct-ng build` produces the following output:
`[INFO ]  =================================================================`
`[INFO ]  Installing final gcc compiler`
`[EXTRA]    Configuring final gcc compiler`
`[EXTRA]    Building final gcc compiler`
`[ERROR]    cfns.gperf:101:1: error: 'const char* libc_name_p(const char*, unsigned int)' redeclared inline with 'gnu_inline' attribute`
`[ERROR]    make[3]: *** [Makefile:1065: cp/except.o] Error 1`
`[ERROR]    make[2]: *** [Makefile:4121: all-gcc] Error 2`
`[ERROR]    make[1]: *** [Makefile:876: all] Error 2`
`[ERROR]   `
`[ERROR]  >>`
`[ERROR]  >>  Build failed in step 'Installing final gcc compiler'`
`[ERROR]  >>        called in step '(top-level)'`
`[ERROR]  >>`
`[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]`
`[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@944]`
`[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@663]`
`[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]`
`[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]`
`[ERROR]  >>`
`[ERROR]  >>  For more info on this error, look at the file: 'build.log'`
`[ERROR]  >>  There is a list of known issues, some with workarounds, in:`
`[ERROR]  >>      '/usr/share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt'`
`[ERROR]   `
`[ERROR]  (elapsed: 22:29.26)`

I can find no relevant comment in "/usr/share/doc/crosstool-ng/crosstool-ng-1.22.0/B - Known issues.txt".

Full build log: 
[build.log.1.22.txt](https://github.com/crosstool-ng/crosstool-ng/files/922372/build.log.1.22.txt)


Remove crosstool from system with `sudo make uninstall`
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Next I try 1.23-rc2 following exactly the same steps - I even copy and paste from this document as I write it
`make` completes without error, so the patch mentioned above is not needed.

`mkdir tools-1.23`
`cd tools-1.23`
`ct-ng x86_64-unknown-linux-uclibc`
`ct-ng build` completes without error this time

Now for buildroot:
`wget https://buildroot.org/downloads/buildroot-2017.02.1.tar.gz`
`tar -jxf buildroot-2017.02.1.tar.gz`
`cd buildroot-2017.02.1`
`make pc_x86_64_bios_defconfig`
'make menuconfig` using following changed settings:
Toolchain type (External toolchain)
Toolchain (Custom toolchain)
Toolchain origin (Pre-installed toolchain)
($(HOME)/x-tools/x86_64-unknown-linux-uclibc) Toolchain path
(x86_64-unknown-linux-uclibc) Toolchain prefix
Kernel version (Custom version)
External toolchain gcc version (6.x)
External toolchain kernel headers series (4.9.x) <- doesn't match 4.10.8 in crosstool, but 4.10 not available
(4.10.8) Kernel version

`make` fails with Incorrect selection of kernel headers: expected 4.9.x, got 4.10.x. Buildroot config file here: 
[buildroot.config.1.txt](https://github.com/crosstool-ng/crosstool-ng/files/922549/buildroot.config.1.txt)

At this point I'm not sure how you managed to get a clean compilation with a pristine crosstool-1.22, nor a clean compilation of a pristine buildroot-2017.01.02 using a pristine crosstool-1.23-rc2.

So I go back to crosstool-1.23-rc2 and change the kernel version to 4.9.20 (the only change to the stock x86_64-unknown-linux-uclibc configuration). Config file here: 
[config-1.23.txt](https://github.com/crosstool-ng/crosstool-ng/files/922513/config-1.23.txt)

Now buildroot, again changing the toolset prefix, directory, compiler version and OS version. Config file here:
[buildroot.config.2.txt](https://github.com/crosstool-ng/crosstool-ng/files/922715/buildroot.config.2.txt). This now fails with `IPv6 support not available in C library, toolchain unsuitable for Buildroot`

Back to crosstool and add IPv6 support. Config file here: 
[config-1.23-second-attempt.txt](https://github.com/crosstool-ng/crosstool-ng/files/922718/config-1.23-second-attempt.txt) Still no idea how your plain vanilla installations worked first time.

This time we buildroot fails for this reason:
`Wide char support available in C library, please enable BR2_USE_WCHAR`
change buildroot configuration to include WCHAR support and try again. Buildroot config here: 
[buildroot.config.3.txt](https://github.com/crosstool-ng/crosstool-ng/files/922796/buildroot.config.3.txt)
cd 
This now fails with `configure: error: C++ preprocessor "/lib/cpp" fails sanity check` in building expat. I'm not sure what expat is doing here - I don't need it. Expat config.log here: 
[expat.config.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/922788/expat.config.log.txt)

I've plainly made some silly mistake but all I can do is try again. I wipe out all the directories and try again, without the blind alleys.

download crosstool-ng-1.23.0.rc2
extract to freshly-created directory
menuconfig to enable IPv6 and set kernel version to 4.9.20
build
... with the same result during compiling expat ...
`configure: error: C++ preprocessor "/lib/cpp" fails sanity check`

That's enough for today. I'll try cvs master next.

**Comment by CatsMum** [comment]
I'm tired - meant git latest.

**Comment by stilor** [comment]
0. When pasting a large fragment of preformatted text, you can put \`\`\`\` (4 backticks) before the 1st and after the last line. You don't have to quote each line with backticks.

1. The issue with 1.22.0 is that GCC6 cannot build GCC5 without a patch. Crosstool-NG 1.22.0 was released before GCC6, so it has no such patch.

2. As I said above, I used your config (including your uclibc.config) to test with buildroot (not `x86_64-unknown-linux-uclibc` sample). I used the sample to compile a simple file including <limits.h> (x.c, above).

3. I have an ArchLinux installed in a VM and this `x86_64-unknown-linux-uclibc` sample built fine. Expat is needed to build GDB. The config.log you posted indicates that configure attempted to use `/lib/cpp` which is the last fallback if it failed to use the regular preprocessor (`gcc -E` or `g++ -E`). The log also shows that the CXX variable (compiler for C++) was set to `false`. Crosstool-NG does not set this variable when running expat's configure, so it was probably set in your environment.

**Comment by CatsMum** [comment]
Using git master. Busybox compiles correctly. Fails configuring target expat with exactly the same diagnostic: `configure: error: C++ preprocessor "/lib/cpp" fails sanity check`

change buildroot configuration
'/dev management (Static using device table)'
Remove all target packages.
now buildroot fails with the same diagnostic as above but in configuring gettext for the target.

I give up now.

**Comment by stilor** [comment]
Who fails to configure target expat, crosstool-NG or buildroot?

**Comment by stilor** [comment]
If it is buildroot, then it seems it's because you didn't select `BR2_INSTALL_LIBSTDCPP`:

````
ifneq ($(BR2_INSTALL_LIBSTDCPP),y)
TARGET_CONFIGURE_OPTS += CXX=false
endif
````

If it is the case, report this to buildroot maintainers - looks like a missing dependency for their expat package.

**Comment by CatsMum** [comment]
OK. Thanks for all your help. I've managed to cobble something together from git, and from careful selection of configuration options, that compiles without error.
I'd not object to you closing this issue.
You've been very patient and I've learned to always get my software from the authoritative source,

**Comment by Sub-7** [comment]
try: apt install libc-dev
