### ISSUE TITLE
Linaro 4.9 URL change

### ISSUE THREAD

**Issue by tdelporto** [crosstool-ng/crosstool-ng#695]
- Report crosstool-NG version - 1.22 

The current URL for Linaro 4.9 is:

https://releases.linaro.org/archive/15.06/components/toolchain/gcc-linaro/4.9/gcc-linaro-4.9-2015.06.tar.xz

Build will fail to download linaro. Adding the following line allowed the download to succeed and build to proceed.

 ./lib/crosstool-ng-1.22.0/scripts/build/cc/100-gcc.sh:                       https://releases.linaro.org/${YYMM}/components/toolchain/gcc-linaro/${linaro_series} \
+ ./lib/crosstool-ng-1.22.0/scripts/build/cc/100-gcc.sh:                       https://releases.linaro.org/archive/${YYMM}/components/toolchain/gcc-linaro/${linaro_series} \

**Comment by stilor** [comment]
1.22 is no longer maintained. Use 1.23 or master.
