### ISSUE TITLE
cg-ng build fails on building ncurses

### ISSUE THREAD

**Issue by bg172** [crosstool-ng/crosstool-ng#696]
Build failed in step 'Installing ncurses for build'
[ERROR]    make[2]: *** [Makefile:219: fallback.c] Error 1
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [Makefile:114: all] Error 2
[bin.zip](https://github.com/crosstool-ng/crosstool-ng/files/949313/bin.zip)
- crosstool-NG version: 1.23.0
- host OS and its version: ubuntu 16.04.2

**Comment by stilor** [comment]
Interesting. Somehow `--without-fallbacks` (which is is equivalent to `--with-fallbacks=no`) is interpreted by ncurses configure as using the "no" terminal.

Can you edit `.build/src/ncurses-6.0/configure` and find the line starting with `FALLBACK_LIST`, and add `set -x` before it and `set +x` after it, so that it looks like this:

````
set -x
FALLBACK_LIST=`test "$with_fallback" != no && echo "$with_fallback" | sed -e 's/,/ /g'`
set +x
````

Then run `ct-ng build` (without `ct-ng clean`!) and attach the build.log?

I have a 16.04.2 Ubuntu as well, and on my machine the FALLBACK_LIST is correctly set to empty value. In your case, it somehow ends up with "no" in it.

**Comment by stilor** [comment]
After this configure change, build.log should contain the lines similar to these:

````
[CFG  ]    checking for list of fallback descriptions... no
[CFG  ]    ++ test no '!=' no
[CFG  ]    + FALLBACK_LIST=
[CFG  ]    + set +x
````

**Comment by stilor** [comment]
Also, please find `paths.sh` under the installation directory for crosstool-NG and attach it.

**Comment by bg172** [comment]
here you are (sorry if the log seems a bit different, I cloned and ran everything again), 
btw the build.log has something different although similar to as you mentioned:
[CFG  ]    checking for list of fallback descriptions... no
[CFG  ]    ++ echo no
[CFG  ]    ++ sed -e 's/,/ /g'
[CFG  ]    + FALLBACK_LIST=no
[CFG  ]    + set +x
[bin.zip](https://github.com/crosstool-ng/crosstool-ng/files/949828/bin.zip)
[paths.zip](https://github.com/crosstool-ng/crosstool-ng/files/949829/paths.zip)

**Comment by stilor** [comment]
It detected regular `/bin/bash`... What does you `/bin/bash` say if you run the same command in the command line?

````
with_fallback=no
test "$with_fallback" != no && echo "$with_fallback"
````

Do you have `test`? Does it not work?
Something seems to be wrong with your system if `test no != no` returns 0 (true).

**Comment by bg172** [comment]
normally I use fish instead of bash as my terminal, but the result of "./ct-ng build" is the same.
And if I run these two commands in bash nothing is printed, no errors, nothing as result. And as I understand nothing shall be be printed in this case. 
```test``` looks to be working because ```$with_fallback" != yes && echo "$with_fallback"``` shows
```no```

**Comment by stilor** [comment]
Well, honestly I have no further ideas why the same command in the configure script yields a different result. Unless you missed a line in your pasted output, it's also strange that the output in your case did not contain a `test no '!=' no` line, but again, I have no idea why.

I'm afraid you'd have to debug it on your own - I cannot reproduce this on my ubuntu 16.04.2 installation.

**Comment by stilor** [comment]
as a couple of last straws:
- print the environment (`set`) from the configure script and compare it with the environment in the command line
- print the full value of `$with_fallback` (e.g. `echo "[$with_fallback]"` to see any possible whitespace) and see if there's anything fishy with the value

**Comment by bg172** [comment]
when after running ```./ct-ng build``` I run ```echo "[$with_fallback]"``` then I get ```[]```

**Comment by stilor** [comment]
I meant printing it inside the configure script, of course.

**Comment by bg172** [comment]
I tried to do so, but not sure it is what you meant, see result attached. Could you please be more specific on what to insert where?
[bin.zip](https://github.com/crosstool-ng/crosstool-ng/files/968824/bin.zip)

**Comment by stilor** [comment]
Insert to the same location I pointed you to in the configure: https://github.com/crosstool-ng/crosstool-ng/issues/696#issuecomment-296409012

I don't see any printouts in the build.log; they are, if any, likely in config.log. You may also need to redirect the output to stderr.

**Comment by bg172** [comment]
done, this now looks as you expected in https://github.com/crosstool-ng/crosstool-ng/issues/696#issuecomment-296409047
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/981136/build.zip)
[config.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/981137/config.log.zip)
[configure.zip](https://github.com/crosstool-ng/crosstool-ng/files/981138/configure.zip)

**Comment by stilor** [comment]
Ok, mystery solved. You disabled applying patches, and this error (and likely the other one you encountered) are solved by the patches. You can read patch descriptions at the top of each patch in `patches/ncurses/6.0` - in one of them the error with `--with-fallback` is mentioned explicitly.

If you disable patches shipped with crosstool-ng, you're on your own.

**Comment by bg172** [comment]
well, in the build.log I see the line
_[DEBUG]    Already patched 'ncurses-6.0'_
and I've tried so set all possible patching origins setting via menuconfig, it didn't help. How should I do it better?

**Comment by bhundven** [comment]
`ct-ng clean`, then `ct-ng build` again.

**Comment by tofutim** [comment]
I just ran into this issue. 
```
# Extracting
#
# CT_FORCE_EXTRACT is not set
CT_OVERRIDE_CONFIG_GUESS_SUB=y
# CT_ONLY_EXTRACT is not set
CT_PATCH_BUNDLED=y
# CT_PATCH_LOCAL is not set
# CT_PATCH_BUNDLED_LOCAL is not set
# CT_PATCH_LOCAL_BUNDLED is not set
# CT_PATCH_NONE is not set
CT_PATCH_ORDER="bundled"
```
