### ISSUE TITLE
Add GCC 5.1 support 

### ISSUE THREAD

**Issue by samm-git** [crosstool-ng/crosstool-ng#70]
Hi, GCC 5.1 is just released. ct-ng mostly works with it when i am using "custom cc dir", but it would be good to see gcc5.1 support in ct-ng built-in

**Comment by bhundven** [comment]
No, not yet. See pull request #68
It may work fine for you, but there are other cases where it will break.

**Comment by samm-git** [comment]
Thank you for reply and reference, I am fine with using custom compiler dir for now. Hopefully it will be integrated at some point, because gccgo in 4.9 is full of bugs and cant be used for most of the tasks.

**Comment by bhundven** [comment]
I'm just waiting for pull request #71 to add a signed-off-by... closing this.
