### ISSUE TITLE
gettext-0.19.8.1 fails to (cross) build for mingw

### ISSUE THREAD

**Issue by tvb377** [crosstool-ng/crosstool-ng#702]
Observed during canadian cross build with build=Linux, host=mingw, target=x,
using Linux - mingw cross compiler i686-w64-mingw32-gcc-4.7.2-release-linux64_rubenvb.tar.xz

mingw's stdio.h contains a (static) definition of asprintf.
This conflicts with gettext-0.19.8.1 three implementations of asprintf.

**Comment by tvb377** [comment]
This patch circumvents the problem:

[140-noasprintf-with-mingw32.patch.txt](https://github.com/crosstool-ng/crosstool-ng/files/959529/140-noasprintf-with-mingw32.patch.txt)

**Comment by stilor** [comment]
There is no such error when using i686-w64-mingw32 cross toolchain (built from a sample configuration). Crosstool-NG no longer supports 4.7, so it may be related to an older version of GCC.

If you can reproduce with crosstool-NG's version of i686-w64-mingw32 toolchain, feel free to reopen this issue (and attach .config/build.log).
