### ISSUE TITLE
armv8-rpi3-linux-gnueabihf, glibc-2.25/iconvdata/Makefile, issue

### ISSUE THREAD

**Issue by fluber** [crosstool-ng/crosstool-ng#706]
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-apple-darwin14.5.0
[EXTRA]      host   = x86_64-apple-darwin14.5.0
[EXTRA]      target = armv8-rpi3-linux-gnueabihf
[EXTRA]  Dumping internal crosstool-NG configuration: done in 1.00s (at 00:03)

issue:
modules.so := $(addsuffix .so, $(modules))

should be:
modules.so := $(addsuffix.so, $(modules))

there is a space between $(add suffix and .so, the space should be remove

fix step:
1: ct-ng menuconfig
2.all of these are under the ** Paths ** section, turn on Stop after extracting tarballs,
3.ct-ng build
4.use find . -name 'Makefile' -exec grep -Hn 'IBM1388' {} \; //find the Makefile Path
in my environment like this
./.build/src/glibc-2.25/iconvdata/Makefile:62:	   IBM1364 IBM1371 IBM1388 IBM1390 IBM1399 ISO_11548-1 MIK BRF	 \
5.use vim open the file , find the issue line should be after line 62.
6.remove the space between $(add suffix and .so, and save
7.ct-ng menuconfig , turn off after extracting tarballs,
8.ct-ng build

It's work!

**Comment by stilor** [comment]
Start with describing an error you saw.
Second, your fix for whatever error you saw is invalid, spend some time studying Makefile syntax.
Finally, if you believe there is an error in glibc - submit a bug report to them first.

**Comment by fluber** [comment]
thanks, now, I report the issue in glibc project.

next time, I will following you suggest step to report issue.

thank again
