### ISSUE TITLE
mingw host mingw target link and install error

### ISSUE THREAD

**Issue by djmott** [crosstool-ng/crosstool-ng#707]
First was a few link errors in undefined reference to `rpl_malloc' while building mingw-w64-tools/widl
A quick google revealed autotools gets confused. Breaking out into the command prompt when errors occur I make clean and reconfigure with:
ac_cv_func_malloc_0_nonnull=yes ac_cv_func_realloc_0_nonnull=yes ../../../../../src/mingw-w64-v5.0.1/mingw-w64-tools/widl/configure  --build=x86_64-build_pc-linux-gnu --host=x86_64-host_w64-mingw32 --target=x86_64-w64-mingw32 --program-prefix=x86_64-w64-mingw32- --prefix=/src/toolchains/mingw/mingw 

afterward make was successful but proceeding to the next step failed with permission denied on 'make install -l' 
I noticed the absence of DESTDIR so ran: make DESTDIR=/src/toolchains/mingw/mingw  install and continued. it seems to be okay
$ct-ng
crosstool-NG version crosstool-ng-1.23.0-rc1-2-gde136613 
$uname -a #updated this morning
Linux dm-dev1 4.9.25-1-lts #1 SMP Thu Apr 27 16:42:36 CEST 2017 x86_64 GNU/Linux

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/966508/config.txt)

[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/966510/build.log.txt)

**Comment by stilor** [comment]
You build log is truncated and does not show the link errors you refer to.
