### ISSUE TITLE
make[2]: *** [s-automata] Error 137

### ISSUE THREAD

**Issue by purechaos** [crosstool-ng/crosstool-ng#708]
crosstool-ng throw me the following  error

[ALL  ]    Makefile:2137: recipe for target 's-automata' failed
[ERROR]    make[2]: *** [s-automata] Error 137
[ERROR]    make[2]: *** Waiting for unfinished jobs....

1. crosstool-NG version       : crosstool-ng-1.23.0  , commit : 368a06
2. Host OS and its version   : Ubuntu 16.04.1 LTS (running on VM player)
3. config.log and build.log  is attached below 
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/966583/build.zip)
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/966584/config.zip)

**Comment by stilor** [comment]
From your log:
````
/bin/bash: line 1: 24215 Killed                  build/genautomata
````
Apparently, your VM ran out of memory.
