### ISSUE TITLE
Crosstool-ng freezes when building for any architecture.

### ISSUE THREAD

**Issue by Enginecrafter77** [crosstool-ng/crosstool-ng#710]
Crosstool-ng version: [latest from the github]
-OS Deatils: Debian 8.7 kernel 3.16.0-4-amd64
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/971841/build.log.txt)
[my.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/971842/my.config.txt)

I am trying to setup the toolchain to compile new kernel for some devices (powerPC architecture), but I can't get the crosstool-ng work. It builds normally, until the "Installing GMP for host" appears. There, the "clock" (in the command line of ct-ng build) freezes, but the underline in terminal is still blinking. Got it running over 2 hours, but with no result. Still frozen at 9:06.

**Comment by stilor** [comment]
Your build.log has some zeros (NUL characters) at the end. crosstool-NG does not write that, and neither should the configure script for GMP. Filesystem corruption?

**Comment by Enginecrafter77** [comment]
I had to interrupt the process because the whole system was frozen (nothing was responding, even keyboard) so it is possible, but when rebooted the fsck cleaned the fs so it is ok now.

**Comment by Enginecrafter77** [comment]
I meant the filesystem is ok not the building proccess. It still does that thing. It still can't build the GMP.

**Comment by stilor** [comment]
Then attach a non-corrupted build.log. Also, what is the CPU load (i.e. is the configure script busy doing something or just waiting)? What are the child processes of configure script? Does this set of child processes change? `ps axjf > 1; sleep 5; ps axjf > 2` and compare the process lists before and after.

As you might guess, I don't see such behavior on any of the systems I am using for testing, so you'd need to debug it a bit on your end.

**Comment by stilor** [comment]
As to the progress timer freezing - ct-ng only updates it when it sees any output from the child processes. So if the configure script for GMP freezes for whatever reason and does not produce any new output, the progress timer will not be updated either.

**Comment by Enginecrafter77** [comment]
This time it run to the compiling pass-2 gcc compiler, and then stopped. I suppose it's the behaviour you told about. But I can't give you output of current cpu load, neither output from ps.
The system is COMPLETELY frozen. Not responding on mouse events, keyboards and anything, so it means I can't get to another tty.

**Comment by Enginecrafter77** [comment]
Also, there is no disk activity

**Comment by stilor** [comment]
What is the kernel version? Is it by chance a 4.10? I noticed a similar behavior on my ubuntu 17.04 after I picked the new kernel, see here: https://bugs.launchpad.net/ubuntu/+source/linux/+bug/1674838

The symptom is that first a process on one core becomes a zombie while eating 100% CPU time on that core (yep, it is zombie and it is alive :)) Then eventually other processes threads die too, and the system freezes. I am yet to try if downgrading the kernel as described in that bug helps.

**Comment by stilor** [comment]
Anyway, it seems like a system issue rather than crosstool-ng bug - even if crosstool-ng helps to reproduce  it by stressing the system's resources.

**Comment by Enginecrafter77** [comment]
Ok I will try to run it on ArchLinux, since it has everythimg up-to-date (rolling distribution).

**Comment by stilor** [comment]
I am not sure "everything up to date" is the solution - the problem started when ubuntu cherry-picked some newer changes into its 4.10 branch. I don't know if that issue is fixed upstream on 4.10/4.11 branches.

**Comment by stilor** [comment]
Ok, correction - in the bug discusstion, people seem to agree that newer 4.10.x kernels are not affected.

**Comment by Enginecrafter77** [comment]
I was using 3.16.0 kernel maintained by debian guys. Anyway, what distribution can you recommend to work on? (You are sure it will work)

**Comment by stilor** [comment]
Well, until a few days ago I was using ubuntu pretty reliably - but as I said, it started crashing after picking up the new kernel.

Sorry I missed the kernel version in your first post - it is likely a different issue. But still, hanging at different phases strongly suggests system instability.

**Comment by Enginecrafter77** [comment]
I don't belive it myself, but couldn't my ram size be problem? (1536MB => 1.5GiB)

**Comment by Enginecrafter77** [comment]
UPDATE. I tried to test it on Arch Linux, and it was running fine. It worked until step "Installing final GCC", when it threw an error. It was running for around 1 hour. The issue was simlar to this: https://github.com/crosstool-ng/crosstool-ng/issues/437.

**Comment by stilor** [comment]
Where is the build log?

**Comment by stilor** [comment]
... and the .config, by the way.

**Comment by Enginecrafter77** [comment]
Ok I finally got it running. You were true with the system instability.
I know this question does not belong there, but to another issue, but I don't want to start a new one.
When I want to compile linux 4.11 kernel with generated toolchain, it produces errors simlar to this:

`powerpc-unknown-linux-uclibc-gcc: unrecognized command line option '-mno-sse; did you mean '-mno-spe'?`
This error line is repeating 6 times.
-mno-sse
-mno-mmx
-mno-sse2
-mno-3dnow
-mcmodel=kernel

It fails when compiling the first file, "kernel/bounds.s"

**Comment by Enginecrafter77** [comment]
Sorry, just a stupid mistake. Forgot to pass ARCH=<arch> to menuconfig. Issue solved. (Instable debian system, build suceeded on Arch Linux virtual machine)
