### ISSUE TITLE
Failure building libiconv

### ISSUE THREAD

**Issue by U-007D** [crosstool-ng/crosstool-ng#711]
Here's the failure message I'm getting during `./ct-ng build`:
```
...
[INFO ]  Installing libiconv for host
[EXTRA]    Configuring libiconv
[EXTRA]    Building libiconv
[ERROR]    libtool:   error: specify a tag with '--tag'
[ERROR]    make[3]: *** [iconv.lo] Error 1
[ERROR]    make[2]: *** [all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing libiconv for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@297]
[ERROR]  >>        called from: do_libiconv_backend[scripts/build/companion_libs/320-libiconv.sh@105]
[ERROR]  >>        called from: do_libiconv_for_host[scripts/build/companion_libs/320-libiconv.sh@53]
[ERROR]  >>        called from: do_companion_libs_for_host[scripts/build/companion_libs.sh@36]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
```
Any suggestions?

**Support details:**
- crosstool-NG version: crosstool-ng-1.23.0-13-g129e6d3f
- host/build OS and its version: Mac OS X 10.12.4 (using case-**sensitive** FS) 
- Using Homebrew.  Packages installed: https://gist.github.com/U-007D/18f5792706f2a626823e9f2d7a345dd0
- `.config`: https://gist.github.com/U-007D/07c5dfc13ea58e7bf0aaa7ff01472c4d
- `build.log` (from `./ct-ng build.1`): https://gist.githubusercontent.com/U-007D/20902fbc37bd9f4f673b52023e2e204e/raw/9792eb46aa371bb6e36d3bbab0c6c33205b9a74f/build.log
- Main compilers installed: `Clang 4.0.0` and `GCC 7.1.0`, both built from source.
- `/Volumes/CrossToolCompile` and `/Volumes/CrossTool` are `Mac OS Extended (Case Sensitive, Journaled)` filesystems.

**Comment by stilor** [comment]
Thanks for a detailed report, I'll try to reproduce it later with your config. Just in case, where are the clang 4.0.0 and gcc 7.1.0 installed to?

**Comment by U-007D** [comment]
FYI, I figured out a fix for this issue, and am working on a patch for this.

**Comment by stilor** [comment]
Good, as the build is already progressed past libiconv on my 10.12 (albeit without extra clang/gcc installed). Looking forward to see what the problem was.

**Comment by U-007D** [comment]
I've no idea how to send a patch for files that are generated, so I'll try to describe the changes I made.

FYI, I configured using `./configure --enable-local` for case-sensitive filesystem reasons.
I appended `--tag=CC` to the `LIBTOOL = ...` line in the following (presumably) generated `Makefiles`:
```
./.build/armv7-rpi2-linux-gnueabihf/build/build-libiconv-host-x86_64-build_apple-darwin16.5.0/lib
./.build/armv7-rpi2-linux-gnueabihf/build/build-libiconv-host-x86_64-build_apple-darwin16.5.0/preload
./.build/armv7-rpi2-linux-gnueabihf/build/build-libiconv-host-x86_64-build_apple-darwin16.5.0/src
```

For example, l. 28 in ./.build/.../lib/Makefile now reads:
```
LIBTOOL = /bin/bash $(top_builddir)/libtool --tag=CC
```

(Incidentally, I'm now getting a gcc core pass 1 failure.  :(  I'll open a new issue for that.)

**Comment by U-007D** [comment]
Re: where are the compilers installed:  My compilers are in `/usr/local/bin/clang-4.0` and `/usr/local/bin/gcc-7.1.0`, with `/usr/local/bin/gcc` and `/usr/local/bin/g++` softlinked to `/usr/local/bin/gcc-7.1.0/bin/gcc` and `.../g++` respectively.  `clang` and `clang++` are softlinks to the corresponding `clang` binaries.  `CC` and `CXX` environment variables are set to `gcc` and `g++`, respectively.

`/usr/local/bin` is on my `$PATH`.

**Comment by stilor** [comment]
> CC and CXX environment variables are set to gcc and g++, respectively.

I think this is what may be breaking the build. We've had reports about it in the past, e.g. #467.

>  If you could either make the fix in the repo or tell me how to fix my local copy such that the .build makefiles are generated with libtool --tag=CC I'd appreciate it.

Well, it is not the fix. The issue is that libtool is supposed to infer the setting of `--tag=CC` option from the command line arguments provided by matching them to `$CC`. Which is why your setting of CC environment variable probably breaks the build.

Selecting the compiler via CC environment variable is something I have in the plans (see TODO) but haven't done yet. Meanwhile, you'd have to select it via "Build prefix" and "Build suffix" options (and even that is not very reliable, AFAIU - there were some bugs filed for this feature recently).

**Comment by stilor** [comment]
You may also try creating a directory with symlink named just 'gcc' (pointing to the compiler you want to select) and add that directory to `$PATH`.

Then unset CC/CXX and see if it helps.

**Comment by U-007D** [comment]
Ok, thank you--I'll try that.

**Comment by U-007D** [comment]
This resolved the issue.  I've created a fix and tested with a clean install so others won't run into this.  https://github.com/crosstool-ng/crosstool-ng/pull/713
