### ISSUE TITLE
Failure Installing pass-1 core C gcc compiler

### ISSUE THREAD

**Issue by U-007D** [crosstool-ng/crosstool-ng#712]
Here's the failure message I'm getting during `./ct-ng build`:
```
...
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]    make[3]: *** [liblto_plugin.la] Error 1
[ERROR]    make[2]: *** [all] Error 2
[ERROR]    make[1]: *** [all-lto-plugin] Error 2
[ERROR]    make[1]: *** Waiting for unfinished jobs....
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@297]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@674]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@227]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]

Current command:
  'make' '-j8' '-l' 'all-gcc'
exited with error code: 2
Please fix it up and finish by exiting the shell with one of these values:
    1  fixed, continue with next build command
    2  repeat this build command
    3  abort build

ct-ng:/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/build/build-cc-gcc-core-pass-1>  'make' '-j1' '-l' 'all-gcc'
make[3]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/bash ./libtool --tag=CC --tag=disable-static  --mode=link /usr/local/bin/gcc -Wall -O2 -g -I/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/include -fno-common -Wc,-static-libgcc  -module -bindir /Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/libexec/gcc/armv7-rpi2-linux-gnueabihf/7.1.0    -Xcompiler '-static-libstdc++' -Xcompiler '-static-libgcc' '-Wl,-no_pie' '-L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib' -Xcompiler '-framework' 'CoreFoundation' '-lstdc++' '-lm' -o liblto_plugin.la -rpath /Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/libexec/gcc/armv7-rpi2-linux-gnueabihf/7.1.0 lto-plugin.lo  -Wc,../libiberty/pic/libiberty.a
libtool: link: /usr/local/bin/gcc -Wl,-undefined -Wl,dynamic_lookup -o .libs/liblto_plugin.0.so -bundle  .libs/lto-plugin.o   -L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib /usr/local/bin/gcc-7.1.0/lib/libstdc++.dylib -L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/src -L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/src/.libs -L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/libsupc++/.libs -lm  -static-libgcc -static-libstdc++ -static-libgcc -Wl,-no_pie -framework ../libiberty/pic/libiberty.a
ld: warning: directory not found for option '-L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/src'
ld: warning: directory not found for option '-L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/src/.libs'
ld: warning: directory not found for option '-L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/libsupc++/.libs'
ld: framework not found ../libiberty/pic/libiberty.a
collect2: error: ld returned 1 exit status
make[3]: *** [liblto_plugin.la] Error 1
make[2]: *** [all] Error 2
make[1]: *** [all-lto-plugin] Error 2
```
Any suggestions?

**Support details:**
- crosstool-NG version: crosstool-ng-1.23.0-13-g129e6d3f
- host/build OS and its version: Mac OS X 10.12.4 (using case-**sensitive** FS) 
- Using Homebrew.  Packages installed: https://gist.github.com/U-007D/18f5792706f2a626823e9f2d7a345dd0
- `.config`: https://gist.github.com/U-007D/07c5dfc13ea58e7bf0aaa7ff01472c4d
- `build.log`: https://gist.github.com/U-007D/20902fbc37bd9f4f673b52023e2e204e#file-build-log
- Main compilers installed: `Clang 4.0.0` and `GCC 7.1.0`, both built from source.
- `/Volumes/CrossToolCompile` and `/Volumes/CrossTool` are `Mac OS Extended (Case Sensitive, Journaled)` filesystems.

**Comment by stilor** [comment]
You are using "custom GCC" sources. You should have looked through the patches that ct-ng normally applies and see if any of them are applicable to your sources.

**Comment by U-007D** [comment]
I'm sorry, @stilor, I gave you the wrong report.  This was an older issue that was all me.

The current problem is that crosstool is reporting `ld: framework not found ../libiberty/pic/libiberty.a`.  Interestingly, this path is not valid.  `./libiberty/pick/libiberty.a` is valid, though.  I'll open the correct issue if I cannot figure out the resolution for this.

Thanks for all your help.  Much appreciated!

**Comment by stilor** [comment]
It is handled by one of the patches. The problem is that `-framework` is not handled properly by the `libtool-ldflags` wrapper script that gcc build system uses, it assumes this to be yet another one `-fxxxx` options by gcc that does not have any arguments. As a result, it shuffles the compile flags breaking up the `-framework` and the argument that follows it.

**Comment by U-007D** [comment]
Ah, that's good to know.  Even looking at the patch list for gcc-6.3.0, without the context you've just provided, I wouldn't have made the connection.  I'll take a closer look at `1000-libtool-leave-framework-alone.patch`.

**Comment by U-007D** [comment]
It took me a while to fully grok what you were saying, but you were absolutely right, and I can see what was going on now--I was processing the args the same way libtool-ldflags was and was barking up the wrong tree.  :)

Any thoughts as to why the patch isn't being applied?

**Comment by stilor** [comment]
Because you selected a custom location for GCC. When you select a custom location, it is expected to contain exactly the sources that you want compiled - ct-ng does not apply any patches to that.

**Comment by U-007D** [comment]
Ah.  Thank you again for the context.

Ok, I've made it to the installation of cross-gdb (almost there!), and it's reporting:
```
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[ERROR]    configure: error: in `/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/build/build-gdb-cross':
[ERROR]    configure: error: C compiler cannot create executables
[ERROR]  -
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@297]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@142]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
         /

Current command:
  'CC_FOR_BUILD=x86_64-build_apple-darwin16.5.0-gcc' 'CFLAGS_FOR_BUILD=' 'CPP=x86_64-build_apple-darwin16.5.0-cpp -O2 -g -pipe -I/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/include -fno-common' 'CC=x86_64-build_apple-darwin16.5.0-gcc -O2 -g -pipe -I/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/include -fno-common -L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib -framework CoreFoundation -Qunused-arguments' 'CXX=x86_64-build_apple-darwin16.5.0-g++ -O2 -g -pipe -I/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/include -fno-common -L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib -framework CoreFoundation -Qunused-arguments' 'LD=x86_64-build_apple-darwin16.5.0-ld -L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib -framework CoreFoundation' '/bin/bash' '/Volumes/CrossToolCompile/crosstool-ng/.build/src/gdb-7.12.1/configure' '--build=x86_64-build_apple-darwin16.5.0' '--host=x86_64-build_apple-darwin16.5.0' '--target=armv7-rpi2-linux-gnueabihf' '--prefix=/Volumes/CrossTool/armv7-rpi2-linux-gnueabihf' '--with-build-sysroot=/Volumes/CrossTool/armv7-rpi2-linux-gnueabihf/armv7-rpi2-linux-gnueabihf/sysroot' '--with-sysroot=/Volumes/CrossTool/armv7-rpi2-linux-gnueabihf/armv7-rpi2-linux-gnueabihf/sysroot' '--disable-werror' '--with-pkgversion=crosstool-NG crosstool-ng-1.23.0-13-g129e6d3f' '--with-expat' '--without-libexpat-prefix' '--enable-threads' '--with-python=/usr/local/bin/python' '--disable-sim' '--disable-nls' '--enable-build-warnings=,-Wno-format-nonliteral,-Wno-format-security' '--disable-binutils' '--disable-ld' '--disable-gas'
exited with error code: 77
Please fix it up and finish by exiting the shell with one of these values:
    1  fixed, continue with next build command
    2  repeat this build command
    3  abort build
```
`config.log` contains many errors referencing `gcc: error: unrecognized command line option '-Qunused-arguments'; did you mean '-Wunused-parameter'?`.

I've read through all the gcc and gdb patches.  No references at all to `-Qunused-arguments`.  This is a `clang` compiler switch.  `clang` is on my `$PATH` as `clang` and `clang++`, but should there be  `clang` switches in the build of gdb?

**Comment by stilor** [comment]
That's because the gdb build script assumes macos==clang, and throws in clang's -Qunused switch. Configure in GDB is paranoid and interprets warnings as errors.

It is a bug in ct-ng (it should check the compiler type rather than OS), but I haven't got to fixing it yet.

**Comment by U-007D** [comment]
I see--I saw the TODO in the comments.  Is it something I could contribute as a PR?  I wouldn't mind fixing it if it's fairly straightforward.

There are some checks done in the ncurses patches-- I can follow that pattern.  Is there anything else I should be aware of?

**Comment by stilor** [comment]
First, this workaround needs to be moved into crosstool-NG.sh.in (it already modifies CFLAGS_FOR_BUILD). That check is, again, based on OS type rather than compiler type - so it needs to switch to check for clang. Finally, this check needs to be done for both CFLAGS_FOR_BUILD and CFLAGS_FOR_HOST.

**Comment by U-007D** [comment]
Ok, I'll give it a shot.
