### ISSUE TITLE
Failure Installing pass-1 core C gcc compiler

### ISSUE THREAD

**Issue by U-007D** [crosstool-ng/crosstool-ng#714]
Here's the failure message I'm getting during `./ct-ng build`:
```
...
[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    collect2: error: ld returned 1 exit status
[ERROR]    make[4]: *** [liblto_plugin.la] Error 1
[ERROR]    make[3]: *** [all] Error 2
[ERROR]    make[2]: *** [all-lto-plugin] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@297]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@674]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@227]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]


Current command:
  'make' '-j1' '-l' 'all-gcc'
exited with error code: 2
Please fix it up and finish by exiting the shell with one of these values:
    1  fixed, continue with next build command
    2  repeat this build command
    3  abort build

ct-ng:/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/build/build-cc-gcc-core-pass-1> 'make' '-j1' '-l' 'all-gcc'
make[4]: Nothing to be done for `all'.
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
/bin/bash ./libtool --tag=CC --tag=disable-static  --mode=link x86_64-build_apple-darwin16.5.0-gcc -Wall -O2 -g -I/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/include -fno-common -Wc,-static-libgcc  -module -bindir /Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/libexec/gcc/armv7-rpi2-linux-gnueabihf/7.1.0    -Xcompiler '-static-libstdc++' -Xcompiler '-static-libgcc' '-Wl,-no_pie' '-L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib' -Xcompiler '-framework' 'CoreFoundation' '-lstdc++' '-lm' -o liblto_plugin.la -rpath /Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/libexec/gcc/armv7-rpi2-linux-gnueabihf/7.1.0 lto-plugin.lo  -Wc,../libiberty/pic/libiberty.a
libtool: link: x86_64-build_apple-darwin16.5.0-gcc -Wl,-undefined -Wl,dynamic_lookup -o .libs/liblto_plugin.0.so -bundle  .libs/lto-plugin.o   -L/Volumes/CrossToolCompile/crosstool-ng/.build/armv7-rpi2-linux-gnueabihf/buildtools/lib /usr/local/bin/gcc-7.1.0/lib/libstdc++.dylib -L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/src -L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/src/.libs -L/Users/bRad/Development/toolchains/gcc-tools/build-gcc-7.1.0_build2/x86_64-apple-darwin16.5.0/libstdc++-v3/libsupc++/.libs -lm  -static-libgcc -static-libstdc++ -static-libgcc -Wl,-no_pie -framework ../libiberty/pic/libiberty.a
ld: framework not found ../libiberty/pic/libiberty.a
collect2: error: ld returned 1 exit status
make[4]: *** [liblto_plugin.la] Error 1
make[3]: *** [all] Error 2
make[2]: *** [all-lto-plugin] Error 2
```
I wiped my ct-ng install, cloned it from github, deep-copied the `patches/gcc/6.3.0` folder to `./patches/gcc/7.1.0` and ensured `C compiler | Custom GCC Veersion was set to 7.1.0` via `./ct-ng menuconfig`, but the `ld: framework not found` error persisted.

Of note, while `../libiberty/pic/libiberty.a` is indeed an invalid path (at least from where the ct-ng debug shell drops me, `./libiberty/pic/libiberty.a` is valid.  The build seems to be off by one folder level.

I looked specifically at `1000-libtool-leave-framework-alone.patch` which seems to address the `-framework` issue, but I cannot seem to get it to apply (I've done a `distclean` and even re-cloned the repo from scratch setting up the `./patches/gcc/7.1.0` patches before `./bootstrap`ping, but it doesn't seem to apply.)

`gcc-7.1.0` has not modified `libtool-ldflags` (the file that `1000-libtool-leave-framework-alone.patch` is patching), so it should apply without a problem.

I have verified that `.build/src/gcc-7.1.0/libtool-ldflags` is indeed unpatched from the original version in the source tree.  Applying the patch to `.build/src/gcc-7.1.0/libtool-ldflags` by hand does seem to address  the problem.

Any suggestions or pointers to docs on how to get the patches to apply?

**Support details:**
- crosstool-NG version: crosstool-ng-1.23.0-13-g129e6d3f
- host/build OS and its version: Mac OS X 10.12.4 (using case-**sensitive** FS) 
- Using Homebrew.  Packages installed: https://gist.github.com/U-007D/18f5792706f2a626823e9f2d7a345dd0
- `.config`: https://gist.github.com/U-007D/07c5dfc13ea58e7bf0aaa7ff01472c4ds
- `build.log` (from `./ct-ng build.1`): https://gist.githubusercontent.com/U-007D/20902fbc37bd9f4f673b52023e2e204e/raw/e8ba398948bff6e25274fcf3f503c81aa92d0b52/build.log
- Main compilers installed: `Clang 4.0.0` and `GCC 7.1.0`, both built from source.
- `/Volumes/CrossToolCompile` and `/Volumes/CrossTool` are `Mac OS Extended (Case Sensitive, Journaled)` filesystems.

**Comment by U-007D** [comment]
Looks like crosstool-ng doesn't apply patches to custom gcc locations, if specified.  crosstool-ng expects the sources to be pre-patched in this scenario.  Closing this issue as it seems to be the behavior by design.  (A warning in the UI might be of value, though).  Thanks, @stilor.

**Comment by tofutim** [comment]
@U007D did you ever figure out how to apply the patch? I wonder why mine is a custom gcc location.

**Comment by U007D** [comment]
It's been a while now, but IIRC, I pre-patched the sources to get this to work.  Much has changed since I did this, so I can't be certain of the best approach today...
