### ISSUE TITLE
Building crosstool-ng on msys2 fails 

### ISSUE THREAD

**Issue by Smasherr** [crosstool-ng/crosstool-ng#715]
I am trying to build crosstool-ng-1.23.0 on msys2-mingw-w64.

The first error I saw was at configure stage: cannot determine stat(1) format option. I could fix it by myself by changing `642` to `644` here https://github.com/crosstool-ng/crosstool-ng/blob/master/configure.ac#L243 The reason is `stat -c '%a' conftest` outputs `644` even though `chmod 642 conftest` was executed.

The next error was
```
confdata.c:932:28: error: too many arguments to function 'mkdir'
     if (stat(path, &sb) && mkdir(path, 0755)) {
                            ^~~~~
```

This one I could fix too. It's the same story with the filemode. For mingw we just can call `mkdir(path)` here.

Then came:
```
symbol.c:10:25: fatal error: sys/utsname.h: No such file or directory
 #include <sys/utsname.h>
```

I tried to replace it with `#include "utsname.h"` and add the following header into `kconfig`: https://sourceforge.net/p/mingw/msys2-runtime/ci/2c9b49d614f5be26a2334c4e98d6f7c29878fc37/tree/winsup/cygwin/include/sys/utsname.h

But then the linking failed:
```  LD     'conf'
zconf.tab.o:zconf.tab.c:(.text+0xb106): undefined reference to `uname'
zconf.tab.o:zconf.tab.c:(.text+0xd23f): undefined reference to `regcomp'
zconf.tab.o:zconf.tab.c:(.text+0xd2cf): undefined reference to `regexec'
zconf.tab.o:zconf.tab.c:(.text+0xd472): undefined reference to `regfree'
```

I already tried to install crosstool from msys2 package repository, it it runs weil but includes gcc 5.1.0 which is too old for me. Please help me to resolve this.

**Comment by Smasherr** [comment]
I created a workaround for the issue with the function `uname`. The only used attribute is `uts.release` so I looked up what `uname -r` outputs in my msys2-console and hardcoded it into `symbol.c`
```
$ diff -u kconfig/symbol.c kconfig/symbol.c.old
--- kconfig/symbol.c    2017-05-11 13:28:01.015179400 +0200
+++ kconfig/symbol.c.old        2017-05-11 13:29:10.706529000 +0200
@@ -7,7 +7,7 @@
 #include <stdlib.h>
 #include <string.h>
 #include <regex.h>
-//#include <sys/utsname.h>
+#include <sys/utsname.h>

 #include "lkc.h"

@@ -45,19 +45,19 @@
 void sym_init(void)
 {
        struct symbol *sym;
-//     struct utsname uts;
+       struct utsname uts;
        static bool inited = false;

        if (inited)
                return;
        inited = true;

-//     uname(&uts);
+       uname(&uts);

        sym = sym_lookup("UNAME_RELEASE", 0);
        sym->type = S_STRING;
        sym->flags |= SYMBOL_AUTO;
-       sym_add_default(sym, "2.7.0(0.306/5/3)");
+       sym_add_default(sym, uts.release);
 }

 enum symbol_type sym_get_type(struct symbol *sym)
```

**Comment by Smasherr** [comment]
And to workaround missing regex references I tried to re-run configure:
```
./configure LDFLAGS="-lregex"
```
But that flag seems not to be passed to the compiler:
```
$ make --trace
...skipped...
make -C kconfig
Makefile:102: Ziel „conf“ wird aktualisiert wegen: zconf.tab.o conf.o
echo "  LD     'conf'"
  LD     'conf'
gcc -o conf zconf.tab.o conf.o -lintl
zconf.tab.o:zconf.tab.c:(.text+0xd22c): undefined reference to `regcomp'
zconf.tab.o:zconf.tab.c:(.text+0xd2bc): undefined reference to `regexec'
zconf.tab.o:zconf.tab.c:(.text+0xd45f): undefined reference to `regfree'
```
So I just ran `gcc -o conf zconf.tab.o conf.o -lintl -lregex` for now.

**Comment by Smasherr** [comment]
The next error i bumped in were missing linker flags:
```
$ make --trace
Makefile:98: Ziel „nconf“ wird aktualisiert wegen: zconf.tab.o nconf.o nconf.gui.o
echo "  LD     'nconf'"
  LD     'nconf'
cc -o nconf zconf.tab.o nconf.o nconf.gui.o -lmenu -lpanel
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lmenu
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/6.3.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lpanel
```

**Comment by Smasherr** [comment]
I have found the implementation of `bzero` in `libiberty` which is in `/mingw64/lib/binutils`. However `bzero` is actually deprecated and `memset(ptr, 0, sizeof *ptr);` should be used instead.
The declaration and the implementation of `strcasestr` seems to be completely missing, so I had to modify the source again:
```
DannyLo@DannyLo-PC MINGW64 /d/Development/builds/crosstool-ng-1.23.0/kconfig
$ diff -u nconf.c nconf.c.new
--- nconf.c     2017-05-11 18:35:09.448293200 +0200
+++ nconf.c.new 2017-05-11 18:34:49.204722600 +0200
@@ -13,6 +13,9 @@
 #include "nconf.h"
 #include <ctype.h>

+// Added for support in mingw. This ought to be checked and enabled with autotools.
+const char *strcasestr(const char *s1, const char *s2);
+
 static const char nconf_global_help[] = N_(
 "Help windows\n"
 "------------\n"
@@ -1562,3 +1565,13 @@
        endwin();
        return 0;
 }
+
+const char *strcasestr(const char *s1, const char *s2) {
+       if (s1 == 0 || s2 == 0)
+               return 0;
+       size_t n = strlen(s2);
+       while(*s1)
+               if(!strncmp(s1++,s2,n))
+                       return (s1-1);
+       return 0;
+}
```
Recompiling `nconf.o`, calling `gcc -o nconf zconf.tab.o nconf.o nconf.gui.o -L/mingw64/lib/binutils -lintl -lmenuw -lpanelw -lncursesw -lregex -liberty` and `make` after that finished the building process.

But after I tried so start `ct-ng menuconf` it throwed another bunch of messages:
```
$ ct-ng --trace menuconfig
/mingw64/lib/crosstool-ng-1.23.0/kconfig/kconfig.mk:24: Ziel „menuconfig“ wird aktualisiert wegen: config_files
echo "  CONF  config/config.in"
  CONF  config/config.in
/mingw64/lib/crosstool-ng-1.23.0/kconfig/mconf config/config.in
config/backend.in:3:warning: environment variable CT_IS_A_BACKEND undefined
config/backend.in:14:warning: environment variable CT_BACKEND_ARCH undefined
config/backend.in:18:warning: environment variable CT_BACKEND_KERNEL undefined
config/backend.in:22:warning: environment variable CT_BACKEND_LIBC undefined
Error opening terminal: xterm.
make: *** [/mingw64/lib/crosstool-ng-1.23.0/kconfig/kconfig.mk:25: menuconfig] Fehler 1
```

**Comment by Smasherr** [comment]
To temporarily workaround that `menuconfig` issue I used already existing [`.config`](https://github.com/crosstool-ng/crosstool-ng/files/993932/rpi-arm.config.txt) (from a run with ct-ng from msys2 package repository) and went for a build run. This one is already a known one:
```
[INFO ] Performing some trivial sanity checks
[ERROR] Your file system in '/.../.build' is not case-sensitive!
```
Fixed by changing a registry key as described [here](https://github.com/pfalcon/esp-open-sdk/issues/252#issuecomment-292769250).

Currently stuck at the error which can be seen in the [build.log](https://github.com/crosstool-ng/crosstool-ng/files/993934/build.log.txt) ('http://www.kernel.org/pub/linux/kernel/v4.x/linux-4.0.4.tar.xz' is reachable from here)

**Comment by stilor** [comment]
This last error is exactly because you used an outdated `.config` which does not select the download agent (wget or curl), so ct-ng thinks you have none at all. You were supposed to do `ct-ng oldconfig` but obviously cannot do that because of a failure compiling kconfig binaries.

The warnings from `backend.in` are because you somehow mixed the ct-ng from current master with released (1.23.0) kconfig files. BACKEND stuff has been retired in master.

Your implementation of `strcasestr` is incorrect, it won't find "OO" in "foot".

I don't have a msys environment to try it myself. A pointer to a guide on setting it up would be helpful.

Different library names & headers is something that can be detected by configure. But rejecting `mkdir()` with two arguments (rather than just ignoring the 2nd argument) is so decidedly non-POSIX that I expect a lot more issues down the road. I don't want to end up maintaing that cruft in our kconfig files; you can try to get your changes accepted into upstream kconfig sources. I suspect they'll receive a less than warm welcome, though.

**Comment by stilor** [comment]
As msys is not currently supported as build machine, closing the issue. If you want it supported, post a PR with the changes needed.

**Comment by Smasherr** [comment]
Could you please give me at least a hint where to look to finde something about that `menuconfig` error?
```
Error opening terminal: xterm.
```
I grepped through the source files and couldn't find anything.

**Comment by stilor** [comment]
It is not in kconfig, it comes from ncurses. Your ncurses library cannot find the terminal definitions for the 'xterm' terminal. Sorry, I know nothing about "lncursesw" on msys and where it expects the terminfo/termcap files to be.
