### ISSUE TITLE
gdb fails to build against guile 2.2 (was: arm-unknown-linux-gnueabi cross-gdb fails to build)

### ISSUE THREAD

**Issue by Nucleoprotein** [crosstool-ng/crosstool-ng#718]
Hello,

- Report crosstool-NG version:
`This is crosstool-NG version crosstool-ng-1.23.0`

- Report host OS and its version:
```
Arch Linux

$ uname -a
Linux L 4.10.13-1-ARCH #1 SMP PREEMPT Thu Apr 27 12:15:09 CEST 2017 x86_64 GNU/Linux
```
Build fails here:
http://vpaste.net/BORpx
http://vpaste.net/OlZRs

I think it's missing correct version/arch of libguile because `scm_new_port_table_entry` is not defined anywhere in gdb code.
I have installed two versions:
```

$ pacman -Ss guile
extra/aisleriot 3.22.2-1 (gnome-extra)
    A collection of patience games written in guile scheme
extra/guile 2.2.2-1 [installed]
    Portable, embeddable Scheme implementation written in C
extra/guile1.8 1.8.8-5
    Portable, embeddable Scheme implementation written in C. Legacy branch.
extra/guile2.0 2.0.14-1 [installed]
    Portable, embeddable Scheme implementation written in C

```
native-gdb builds fine.

**Comment by stilor** [comment]
Upstream bug: https://sourceware.org/bugzilla/show_bug.cgi?id=21104

**Comment by flannelhead** [comment]
Meanwhile, this crosstool config line serves as a workaround:
```
CT_GDB_CROSS_EXTRA_CONFIG_ARRAY="--with-guile=guile-2.0"
```

**Comment by MarkoSan** [comment]
Which file did you put this setting in?

**Comment by SpotlightKid** [comment]
Apparently this has been fixed upstream: https://sourceware.org/bugzilla/show_bug.cgi?id=21104#c7

**Comment by cpackham** [comment]
Allegedly fixed upstream. We've updated gdb many times since this issue was first raised. Feel free to raise a new issue if this still happens on master.
