### ISSUE TITLE
Build failed in step 'Building for multilib 1/1: '

### ISSUE THREAD

**Issue by BlackDuck888** [crosstool-ng/crosstool-ng#723]
Hi there,

i am new in crosstools, and i try my first steps, but i didn't get it compiled.

```
[ERROR]      make[2]: *** [iconvdata/others] Error 2
[ERROR]      make[1]: *** [all] Error 2
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@297]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@454]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1760]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@150]
[ERROR]  >>        called from: do_libc[scripts/build/libc/glibc.sh@117]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
```

### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
`crosstool-ng-1.23.0` i downloaded the tar.xz
- Report host OS and its version
`macOS Sierra 10.12.5`with following brew packages
```
brew list
autoconf		gobject-introspection	node
automake		harfbuzz		openexr
binutils		help2man		openssl
cairo			icu4c			pango
cmake			ilmbase			pcre
eigen			jpeg			pixman
fontconfig		json-c			pkg-config
fontforge		libffi			pyqt
freetype		libmicrohttpd		python
gawk			libpng			python3
gdbm			libtiff			qt
gettext			libtool			readline
glib			libuv			sip
gmp			mpfr			sqlite
gnu-sed			neon			tbb
go			nettle			xz
```
- Attach `.config` (unless the issue is not related to any configuration)
i tried `x86_64-ubuntu16.04-linux-gnu` and `i686-ubuntu16.04-linux-gnu` samples without any modification

- Attach `build.log` (unless crosstool-NG fails before the build starts)

i did following these steps
```
download and unzip the archive
./configure --enable-local
make
./ct-ng list-samples
./ct-ng x86_64-ubuntu16.04-linux-gnu
./ct-ng build
```
after that i got the output above

maybe someone has a hint for me

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1031219/config.txt)

[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/1031223/build.log.zip)

**Comment by stilor** [comment]
I haven't seen this error before.
Just in case, what does `ulimit -n` say?

**Comment by BlackDuck888** [comment]
```
ulimit -a
core file size          (blocks, -c) 0
data seg size           (kbytes, -d) unlimited
file size               (blocks, -f) unlimited
max locked memory       (kbytes, -l) unlimited
max memory size         (kbytes, -m) unlimited
open files                      (-n) 256
pipe size            (512 bytes, -p) 1
stack size              (kbytes, -s) 8192
cpu time               (seconds, -t) unlimited
max user processes              (-u) 709
virtual memory          (kbytes, -v) unlimited

**Comment by stilor** [comment]
Try with `ulimit -n 1024`. I saw this value being too law cause a failure during glibc build in 10.13, but it was a different failure.

**Comment by BlackDuck888** [comment]
That did it! Thank you a lot!

**Comment by gansm255** [comment]
> I haven't seen this error before.
> Just in case, what does `ulimit -n` say?

I have this error, i build with crosstool-ng 2.4. what is ulimit -n? How and where to change it? Please help me. Regards, Ganesh

**Comment by BlackDuck888** [comment]
Hey Ganesh, if you scroll up you could see that `ulimit -n` the open file limit under unix systems. You can check your current limits with `ulimit -a` and set a limit with for example `ulimit -n 1024`. This change is temporary and will be gone after reboot or relogin.

**Comment by BlackDuck888** [comment]
> 
> 
> > I haven't seen this error before.
> > Just in case, what does `ulimit -n` say?
> 
> I have this error, i build with crosstool-ng 1.2.4 what is ulimit -n? How and where to change it? Please help me. Regards, Ganesh

Hey Ganesh, if you scroll up you could see that `ulimit -n` the open file limit under unix systems. You can check your current limits with `ulimit -a` and set a limit with for example `ulimit -n 1024`. This change is temporary and will be gone after reboot or relogin.
