### ISSUE TITLE
Failed to compile gcc-6.3.0 with gcc-7.1

### ISSUE THREAD

**Issue by Ventto** [crosstool-ng/crosstool-ng#735]
System:
* crosstool-ng: release-v1.23.0 (2017-04-20)
* OS:  4.11.3-1-ARCH x86_64 GNU/Linux
* gcc: 7.1.1 (2017-05-16)

Since gcc-7.1, an error occurs while compiling gcc-6.3.0 for any toolchain:

```
[ALL  ]    /home/ventto/.xtools/arm-unknown-eabi/.build/src/gcc-6.3.0/gcc/ubsan.c: 
              In function 'bool ubsan_use_new_style_p(location_t)':
[ERROR]    /home/ventto/.xtools/arm-unknown-eabi/.build/src/gcc-6.3.0/gcc/ubsan.c:
                      1474:23: error: ISO C++ forbids comparison between pointer and integer 
                      [-fpermissive]
[ALL  ]           || xloc.file == '0' || xloc.file[0] == 'xff'
[ALL  ]                           ^~~~
```

Except this, it compiles like a charm.

This was fixed 4 months ago:
https://github.com/gcc-mirror/gcc/blame/gcc-6-branch/gcc/ubsan.c#L1476 
The release 6.3.0 kept unupdated.

I am not very familiar enough with crosstool-ng to integrate the fix into the installation process. 

Thanks for your time.

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1052054/config.txt)
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1052085/build.log.txt)

**Comment by stilor** [comment]
GCC7 was released after crosstool-ng 1.23.0, so no wonder crosstool-NG 1.23.0 does not have a fix for that. It is already fixed in Git (and will be fixed in the next release of crosstool-NG).

**Comment by alfishe** [comment]
Compatibility matrix needs to come into scene =)
Spending several hours in a row to go from clang to gcc7.1 and now discovering that need to install gcc6.x

**Comment by arduinomaltster** [comment]
So was there a solution to the problem or is it wait for the next version? I have the same problem.
