### ISSUE TITLE
 recipe for target 'menuconfig' failed

### ISSUE THREAD

**Issue by 0user1** [crosstool-ng/crosstool-ng#737]
I am using the crosstool-ng master and I have built configure using autoconf:
$ autoconf configure.ac
$ /bin/bash ./configure --prefix=/home/iiitd/local/crosstool-ng-alpha
$ make
$ make install
$ sudo cp ct-ng.comp /etc/bash_completion.d
$ export PATH=$PATH:/home/iiitd/local/crosstool-ng-alpha/bin/

Using ct-ng gives me error:
$ ct-ng menuconfig
  CONF  menuconfig
config/target.in:8: can't open file "config/gen/arch.in"
/home/iiitd/local/crosstool-ng-alpha/lib//kconfig/kconfig.mk:20: recipe for target 'menuconfig' failed
make: *** [menuconfig] Error 1

**Comment by stilor** [comment]
Read http://crosstool-ng.github.io/docs/install/
