### ISSUE TITLE
Failure Building binutils for Bare Metal AArch64

### ISSUE THREAD

**Issue by sbosnick** [crosstool-ng/crosstool-ng#745]
Here is the message I am getting when I am running `ct-ng build` for a 64 bit arm target (AArch64) with the OS selected as bare-metal:

```
[ALL  ]    *** BFD does not support target aarch64-unknown-eabi.
[ALL  ]    *** Look in bfd/config.bfd for supported targets.
[ALL  ]    Makefile:2676: recipe for target 'configure-bfd' failed
[ERROR]    make[3]: *** [configure-bfd] Error 1
[ALL  ]    make[3]: Leaving directory '/home/steven/src/cross/.build/aarch64-unknown-eabi/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[ALL  ]    Makefile:849: recipe for target 'all' failed
[ERROR]    make[2]: *** [all] Error 2
[ALL  ]    make[2]: Leaving directory '/home/steven/src/cross/.build/aarch64-unknown-eabi/build/build-binutils-host-x86_64-build_pc-linux-gnu'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
```

crosstool-NG uses a tuple of `aarch64-unknown-eabi` with this configuration. I get the same error when I manually build binutils configured with `--target=aarch64-unknown-eabi`. It appears from looking in `bfd/config.bfd`(as the error message suggests) that the appropriate tuple should be `aarch64-unknown-elf`. It does work when I manually build binutils configured with `--target=aarch64-unknown-elf`. Linaro uses a similar tuple when describing the aarch64, bare-metal tools on their download page: see [downloads](https://www.linaro.org/downloads/) at the bottom of the page.

### Support Details
crosstool-NG version: crosstool-ng-1.23.0
host OS and its version: Ubuntu 17.04
.config: [.config](https://gist.github.com/sbosnick/15167655e7213474724eb5462623e032)
build.log: [build.log](https://gist.github.com/sbosnick/f41afa39dd4aa909dcef6d8609814c67)

**Comment by DrewSingletary** [comment]
I am having this issue as well, attempting to build an arm64 bare-metal toolchain.  How was this resolved?  I attempted to build with the binutils extra config of --target=aarch64-unknown-elf, and this was the resulting config and log.

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2292143/build.log)

[failedConfig.txt](https://github.com/crosstool-ng/crosstool-ng/files/2292145/failedConfig.txt)

Host Mac OS X High Sierra, with ct-ng-1.23.0.  

I have successfully built aarch64-unknown-linux-gnueabi
