### ISSUE TITLE
undefined reference to `__divdi3_internal` compile error in MacOS Sierra

### ISSUE THREAD

**Issue by MarcinSkoczylasSH** [crosstool-ng/crosstool-ng#746]
I try to compile a tool chain for Raspberry Pi 3 on MacOS Sierra, based on this tutorial:
https://www.jaredwolff.com/blog/cross-compiling-on-mac-osx-for-raspberry-pi/

Compile is stopped with undefined reference to `__divdi3_internal`, ... error

`
[ALL  ]      /Volumes/xtools-build-env/.build/armv8-rpi3-linux-gnueabihf/build/build-libc-final/multilib/libc.so.6: undefined reference to '__divdi3_internal'
[ALL  ]      /Volumes/xtools-build-env/.build/armv8-rpi3-linux-gnueabihf/build/build-libc-final/multilib/libc.so.6: undefined reference to '__moddi3_internal'
[ALL  ]      /Volumes/xtools-build-env/.build/armv8-rpi3-linux-gnueabihf/build/build-libc-final/multilib/libc.so.6: undefined reference to '__udivdi3_internal'
[ALL  ]      /Volumes/xtools-build-env/.build/armv8-rpi3-linux-gnueabihf/build/build-libc-final/multilib/libc.so.6: undefined reference to '__umoddi3_internal'
[ERROR]      collect2: error: ld returned 1 exit status
`

Not sure how to proceed...

crosstool-NG version crosstool-ng-1.23.0-36-g1dbb06f2-dirty
MacOS Sierra 10.12.5 (16F73)

Included config & build.log

[error.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1067907/error.tar.gz)

**Comment by stilor** [comment]
Before anything else, what does `ulimit -n` say on this system? If it is less than 1024, do `ulimit -n 1024` and retry. If it doesn't help, please report and I'll look further.

**Comment by MarcinSkoczylasSH** [comment]
I tried this before submitting, I have even set it to 2048 but did not help. Thanks for quick reply.

**Comment by stilor** [comment]
FWIW it just build fine on my macos. I am rerunning the build after installing all updates (haven't used this VM for a couple of months)...

**Comment by stilor** [comment]
Ok, I think I know what happened: you have an older version of GNU patch installed and at some point we had a patch for glibc 2.25 generated with renames - older patch versions just skip such files.

Do a `ct-ng clean` and pull a new version from master, then retry. This should have been fixed by #727 .

**Comment by MarcinSkoczylasSH** [comment]
Thanks, it seems that was the problem. I've tested on Stable 1.23 and it compiles, will try the unstable soon. Thanks for quick reply on this.
