### ISSUE TITLE
Test for BSD/GNU stat command broken.   Method used not valid for all possible use cases.

### ISSUE THREAD

**Issue by madscientist42** [crosstool-ng/crosstool-ng#749]
checking whether stat takes GNU or BSD format... configure: error: cannot determine stat(1) format option

     attr_bsd=`stat -f '%Lp' conftest 2>/dev/null`
     attr_gnu=`stat -c '%a' conftest 2>/dev/null`

Not all filesystems are fully POSIX, but can be used to build cross-compile chains on.  The test in question will produce no results on several differing network type shares at the least.

Suggest that you check for success/fail on the above commands instead.

e.g.

frank@frank-laptop ~ $ stat -f '%Lp' conftest > /dev/null
stat: cannot read file system information for '%Lp': No such file or directory
frank@frank-laptop ~ $ echo $? 
1
frank@frank-laptop ~ $ stat -c '%a' conftest 2>/dev/null
642
frank@frank-laptop ~ $ echo $?
0

In this case (Different config @ home...), the check used works.  But if you have a filesystem that doesn't do POSIX permissions, this test will utterly fail because there are some filesystems that're valid, but won't let you set "642" on the test file.  However, the BSD/GNU variants will fail with a non-zero return value for the command as shown in the example.  I question the need to use stat as it will fail for at least some conditions and cases on Cygwin/MSYS2 builds and for things like SMB shares.

**Comment by cpackham** [comment]
@madscientist42 Have GNU changed the behaviour of stat in a newer coreutils version?

Looking at the code on a GNU/Linux system "$attr_bsd" will be junk and "$attr_gnu" will have the expected "642". Unless all of a sudden GNU or Mint have started shipping something that takes the BSD args.

Could you post your confg.log.

**Comment by stilor** [comment]
> The BSD entry doesn't work for GNU.

Indeed, the purpose of the test is to find which one of these two works.
Post `config.log`.

**Comment by stilor** [comment]
Actually, `config.log` won't help as it does not output raw data.
So please do a `touch /tmp/foo && chmod 642 /tmp/foo && stat -c '%a' /tmp/foo` and post the output.

**Comment by madscientist42** [comment]
1) Guess it's not quite as reported.  That's what happens when you're trying to get out the door for the day at work.

2) It produces the expected behaviors as far as the values in the test lines in the description.

3) It still doesn't know from adam which works which doesn't.

Let me figure out what actually gives and I'll update the issue.

**Comment by madscientist42** [comment]
That and a raftload of Network filesystem choices...

**Comment by madscientist42** [comment]
Suggested patch...

@@ -232,17 +232,18 @@ AC_SUBST([curl])
 
 ACX_CHECK_PROGS_REQ([stat], [stat])
 AC_CACHE_CHECK([whether stat takes GNU or BSD format],
     [acx_cv_stat_flavor],
     [touch conftest
-     chmod 642 conftest
-     attr_bsd=`stat -f '%Lp' conftest 2>/dev/null`
-     attr_gnu=`stat -c '%a' conftest 2>/dev/null`
+     stat -f '%Lp' conftest > /dev/null 2>&1
+	 stat_bsd=$?
+     stat -c '%a' conftest > /dev/null 2>&1
+	 stat_gnu=$?
      rm -f conftest
-     AS_IF([test "$attr_bsd" = "642"],
+     AS_IF([test "$stat_bsd" = "0"],
        [acx_cv_stat_flavor=BSD],
-       [test "$attr_gnu" = "642"],
+       [test "$stat_gnu" = "0"],
        [acx_cv_stat_flavor=GNU],
        [AC_MSG_ERROR([cannot determine stat(1) format option])])])
 
 # FIXME: support SET_KCONFIG_OPTION with string values? But then
 # again, these checks may be moved into ct-ng script.

**Comment by madscientist42** [comment]
Proposed patch for the test...

[stat_check.patch.txt](https://github.com/crosstool-ng/crosstool-ng/files/1077821/stat_check.patch.txt)

**Comment by madscientist42** [comment]
With that patch, it builds, but then I get this when I try to make a cross-compiler set.

[ERROR]  Unknown stat format options

Guys, this **USED** to build with Cygwin.  While I'm pretty sure I can make a case for my client's using a Linux VM to build with for their production system...this is not acceptable.

**Comment by stilor** [comment]
1. Your patch is bogus.
2. I must have missed your check in the mail. When did you pay me to make demands like that.

Go away.

**Comment by stilor** [comment]
And yes, I tested 1.23.0 (which contains this change) and it does work on Cygwin.

**Comment by Nadav-Ruskin** [comment]
I don't know about whatever drama occurred in this issue, but I'm experiencing this on WSL.

From the log:
```
configure:6918: found /usr/bin/stat
configure:6929: result: stat
configure:6944: checking whether stat takes GNU or BSD format
configure:6954: stat -f output:
|   File: "conftest"
|     ID: 100000000 Namelen: 255     Type: wslfs
| Block size: 4096       Fundamental block size: 4096
| Blocks: Total: 117071615  Free: 74035835   Available: 74035835
| Inodes: Total: 999        Free: 1000000
configure:6976: contents of conftest.stderr.bsd:
| stat: cannot read file system information for '%Lp': No such file or directory
configure:6985: stat -c output:
| 777
configure:7007: contents of conftest.stderr.gnu:
configure:7022: result: unknown
configure:7059: error: cannot determine stat(1) format option
```

**Comment by stilor** [comment]
What is WSL and why does it show permissions on a file as '777' even after it has been chmod'ed to 642? Does it support permissions on the file system?

**Comment by kesor** [comment]
I got this while compiling on OS X when I have GNU utils installed using brew and at the start of my PATH. Once I changed the path using "export PATH=/usr/bin:$PATH" it started working.

```
[30:51] / stat: cannot read file system information for '%Lp': No such file or directory
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Finalizing the toolchain's directory'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoForceRmdir[scripts/functions@577]
[ERROR]  >>        called from: do_finish[scripts/build/internals.sh@141]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/Cellar/crosstool-ng/1.23.0_1/share/doc/crosstool-ng/crosstool-ng-1.23.0/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 30:49.35)
[30:51] / make: *** [build] Error 1
```

**Comment by abcfy2** [comment]
I have the same issue on Cygwin with the latest master branch crosstool-ng:

```
./configure --enable-local
...SNIP...
checking for stat... stat
checking whether stat takes GNU or BSD format... unknown
configure: error: cannot determine stat(1) format option
```

```
$ touch /tmp/foo && chmod 642 /tmp/foo && stat -c '%a' /tmp/foo
642
```

**Comment by ljelen** [comment]
This faliure shows up when you try build crosstol-ng on pratition with filesystems e.g. ntfs.
