### ISSUE TITLE
binutils configure does not set CFLAGS_FOR_BUILD properly (even though CXXFLAGS_FOR_BUILD is set)

### ISSUE THREAD

**Issue by nyetwurk** [crosstool-ng/crosstool-ng#752]
As of f7c9ab33cf02a4e31c713dc02aeb135bea70ca97

x86_64 host, x86_64 -m32 build, arm target

running
```
$ ABI=32 ./ct=ng build
```

from binutils config.log:
```
ac_cv_env_CFLAGS_value='-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32'
ac_cv_env_CXXFLAGS_value='-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32'
```
BUT
```
CFLAGS='-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32'
CFLAGS_FOR_BUILD=''
CXXFLAGS='-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32'
CXXFLAGS_FOR_BUILD='-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32'
```
which is causing this:
```
[ALL  ]    if [ -r sysinfo.c ]; then   x86_64-build_pc-linux-gnu-gcc -c -I. -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/binutils/../zlib   sysinfo.c ; else   x86_64-build_pc-linux-gnu-gcc -c -I. -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -I/local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/binutils/../zlib   /local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/binutils/sysinfo.c ; fi
```

```
[ALL  ]    x86_64-build_pc-linux-gnu-gcc -DHAVE_CONFIG_H -I. -I/local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/gprof  -DDEBUG -I../bfd -I/local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/gprof/../include -I/local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/gprof/../bfd  -I. -DLOCALEDIR=""/local/crosstool/i686/gcc-6.3.0-glibc-2.25/arm-unknown-linux-gnueabi/share/locale""  -W -Wall -Wstrict-prototypes -Wmissing-prototypes -Wshadow -Wstack-usage=262144 -O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32 -MT cg_arcs.o -MD -MP -MF .deps/cg_arcs.Tpo -c -o cg_arcs.o /local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/gprof/cg_arcs.c
[ALL  ]    x86_64-build_pc-linux-gnu-gcc  -L/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/lib -m32 -m32 -o sysinfo sysinfo.o syslex_wrap.o
[ALL  ]    /usr/bin/ld: i386:x86-64 architecture of input file `sysinfo.o' is incompatible with i386 output
[ALL  ]    /usr/bin/ld: i386:x86-64 architecture of input file `syslex_wrap.o' is incompatible with i386 output
[ALL  ]    /usr/bin/ld: sysinfo.o: file class ELFCLASS64 incompatible with ELFCLASS32
```
[config.zip](https://github.com/crosstool-ng/crosstool-ng/files/1078994/config.zip)

**Comment by stilor** [comment]
1. By 'x86_64 host', do you mean that you run 32-bit GCC on an otherwise 64-bit machine, or you are configuring a canadian cross built on i686 to run on x86_64?
2. What is ABI=32 environment variable for? Crosstool-NG does not use that, AFAIK.
3. What is your host OS?

**Comment by nyetwurk** [comment]
1+3) linux x86_64 host with 64 bit gcc, trying to pass it -m32 to make i686 toolchain with arm target.

2) GMP requires ABI=32 to compile with -m32; see https://sourceware.org/ml/crossgcc/2009-01/msg00134.html

**Comment by nyetwurk** [comment]
From build.log, CFLAGS_FOR_BUILD is empty:
```
Executing: 'CC_FOR_BUILD=x86_64-build_pc-linux-gnu-gcc' 'CFLAGS_FOR_BUILD=' 'CFLAGS=-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32' 'CXXFLAGS=-O2 -g -pipe -I/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/include -m32 -m32' 'LDFLAGS=-L/local/nyeth-build/crosstool-ng-i686/targets/arm-unknown-linux-gnueabi/buildtools/lib -m32 -m32' '/bin/bash' '/local/nyeth-build/crosstool-ng-i686/targets/src/binutils-2.28/configure' '--build=x86_64-build_pc-linux-gnu' '--host=x86_64-build_pc-linux-gnu' '--target=arm-unknown-linux-gnueabi' '--prefix=/local/crosstool/i686/gcc-6.3.0-glibc-2.25/arm-unknown-linux-gnueabi' '--disable-werror' '--enable-ld=yes' '--enable-gold=no' '--with-pkgversion=crosstool-NG crosstool-ng-1.23.0-80-g5650c366' '--enable-multilib' '--disable-sim' '--disable-gdb' '--disable-nls' '--with-sysroot=/local/crosstool/i686/gcc-6.3.0-glibc-2.25/arm-unknown-linux-gnueabi/arm-unknown-linux-gnueabi/sysroot'
```

**Comment by nyetwurk** [comment]
In build/cc/100-gcc.sh i see
```
    cflags_for_build="${cflags}"
```
but that does not exist in build/binutils/binutils.sh

Also, should it be bh_cflags?

**Comment by stilor** [comment]
No, it shouldn't be bh_cflags, it is a temporary variable in crosstool-NG.sh to combine extra host/build CFLAGS if build==host. It should be `CT_CFLAGS_FOR_BUILD`. It looks like I missed initializing this local variable in a few other places too, e.g. 300-gdb.sh.

Thanks for the link and an explanation, I will fix as time permits. But it may be more reliable to treat i686 as a completely different host from x86_64 and run a canadian build with B=x86_64-unknown-linux-gnu H=i686-unknown-linux-gnu T=arm-*.

**Comment by nyetwurk** [comment]
Yes, I tried a canadian build but I cannot get i686-unknown to co-exist with x86_64-unknown for some reason. 

I think I can fix those issues for you. If I get it working I will issue a PR

**Comment by stilor** [comment]
Thanks.

As to ABI=32, I think it is not a good idea, as it is going to be passed to both build's and host's variants of GMP. What if it **is** a canadian build with one being 32-bit and the other 64-bit? I think gmp.sh needs to figure it out from the tuple and set that variable locally, rather than require it in the environment. Better yet, have upstream GMP fix their configure.

**Comment by nyetwurk** [comment]
I agree about ABI=32, but I was unable to find a clean way to fix that without a lot of other work.

**Comment by nyetwurk** [comment]
f36f61faf46013036f62e0ccc852645591081850 seems to be working. I can build -m32 i686 executables just fine without a canadian cross.

Thank you!

As an aside: I do not know the appropriate place to put ABI=32 yet... I welcome any advice and would be glad to test it.

**Comment by nyetwurk** [comment]
Incidentally, gmp.sh CAN'T figure it out from the tuple in a non-canadian cross for the reasons you cite above: both build and host are still x86_64!

The only obvious way around it is a specific "build 686 on x86_64" top level option which automatically sets -m32 and ABI=32

Not sure the crosstool maintainers would want this though.

I'd be more than glad to add it in if so (and test it).

**Comment by nyetwurk** [comment]
In order for gmp configure to autodetect it, it would need to build a test executable (or object file) using cflags_for_build and test the resulting executable (or object) file for ABI. I would be glad to work on that also but I do not know what people would consider the proper way to detect ABI.

I assume when adding a configure patch to ct-ng patches, they should be paired with one for configure.in as well?

**Comment by stilor** [comment]
I had a brief look at GMP's configure yesterday, and it is not as easy: most other architectures have different ABI names, not just "32" vs "64". But the good news is that the configure, from what I saw, attempts to set that ABI list based on the host tuple - so in cases where a tuple corresponds to a single ABI, it should be ok already.

As to configure patches:
- First and foremost, if possible, the patches should be submitted upstream - and if they're accepted, we'll just pick up a revision from the upstream repository. This is especially true for configure patches - since configure is autogenerated and prone to big changes between releases, they are harder to maintain.
- If that is not possible/feasible, then yes, both configure/configure.{ac,in} should be changed.

**Comment by stilor** [comment]
As to the option (if we come to that), I think it should be something under GMP and be described like "GMP ABI for the host" (and maybe, also a separate option "GMP ABI for the build"), with help capturing the gist of this issue :)

Don't do that yet, though. I am currently working on streamlining the package management code in ct-ng, hopefully will post it some time next week. This will change the config files for companion libs considerably.

**Comment by nyetwurk** [comment]
Send me an offline email (or github pm) if you would like when you are ready. I am in the middle of building a few toolchains for ARM so I can test some of that stuff for you.

**Comment by nyetwurk** [comment]
It looks like GMP automatically knows to add -m32 if ABI=32 on x86_64 hosts.

There is no way of doing this cleanly without adding some sort of top level "build 32-bit tools in non-canadian cross x86_64 bit host".

My current use of 
```
CT_EXTRA_CFLAGS_FOR_BUILD="-m32"
CT_EXTRA_LDFLAGS_FOR_BUILD="-m32"
CT_EXTRA_CFLAGS_FOR_HOST="-m32"
CT_EXTRA_LDFLAGS_FOR_HOST="-m32"
```
short circuits that and is probably not the right way to do things.

The other question is if there are other (non-canadian cross) builds that can do this, and if so, if it should be supported.
