### ISSUE TITLE
Failed to build arm-unknown-eabi toolchain with multilib "rmprofile"

### ISSUE THREAD

**Issue by blkf2016** [crosstool-ng/crosstool-ng#765]
-  crosstool-NG version:
    crosstool-ng-1.23.0-90-g81327dd9
  
- Report host OS and its version
    gentoo linux. Up to date.
Linux gentoo 4.9.34-gentoo #1 SMP Thu Jun 29 08:55:47 CST 2017 x86_64 Intel(R) Core(TM) i7-4770 CPU @ 3.40GHz GenuineIntel GNU/Linux

- Attach `.config`
https://drive.google.com/open?id=0B0-5yV9_rtB4Umt3X0tlcTBBS28

- Attach `build.log`
https://drive.google.com/open?id=0B0-5yV9_rtB4MFJ2Vk9lMENQSEE

BTW: No such error when building with multilib "aprofile"

**Comment by stilor** [comment]
I reproduced the error, but 'aprofile' multilib didn't build for me either - failing in the next step, while building newlib for `-mthumb` multilib. ARM multilibs are notorious in that there are only two "profiles" (one cannot selectively enable certain variants) and at least some of these variants are not supported by any of the libc choices we have in ct-ng.

I don't think I can do anything about it in ct-ng until the projects upstream support it better.
