### ISSUE TITLE
Failing to build gdb 8.0 because of missing header file.

### ISSUE THREAD

**Issue by austinr1028** [crosstool-ng/crosstool-ng#768]
- crosstool-NG version: crosstool-ng-1.23.0-94-gab5f883
- Linux Mint 17.1
- .config:  [ct-ng-config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1126305/ct-ng-config.txt)
- uclibc_config (if needed): [uclibc_config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1126313/uclibc_config.txt)
- build.log:  [build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1126307/build.log.txt)

crosstool-ng fails while building gdb 8.0 (can't find utmp.h). Seems like maybe a gdb bug but I couldn't find any issues that looked just like mine so maybe it is crosstool. Thanks!

**Comment by stilor** [comment]
Not very surprising given that your uClibc config does not select `UCLIBC_HAS_UTMP`.

**Comment by austinr1028** [comment]
Indeed it does not. Thanks for the help.
