### ISSUE TITLE
"isl"'s download location, "isl.gforge.inria.fr", seems to be down.

### ISSUE THREAD

**Issue by danjacques** [crosstool-ng/crosstool-ng#769]
- Version 1.23.0
- Linux: Debian Jessie (probably irrelevant)
- [build.log](https://github.com/crosstool-ng/crosstool-ng/files/1126703/build.log.txt)

The `isl.gforge.inria.fr` mirror appears to be down, preventing the downloading of `isl-0.16.1` during `build`.

Relevant download logs are in the attached `build.log`. I tried this on two different machines, both failing similarly. It's possible that this is a temporary flake, but it's also worth noting that [121-isl.sh](https://github.com/crosstool-ng/crosstool-ng/blob/c31ed45a65e9e30fe2000bf1704583038522646e/scripts/build/companion_libs/121-isl.sh) only supports that one site (no mirrors), so even a flake here disables `ct-ng`.

**Comment by stilor** [comment]
Do you know any other mirrors of ISL? The "infrastructure" area of GCC's website does not have any releases newer than 0.16.1 (same for other packages from INRIA, gcc "mirror" doesn't have the most recent packages).

**Comment by stilor** [comment]
Closing. Please re-open if you find some official mirrors of INRIA, I'll add them to the list.

**Comment by marc-hb** [comment]
isl.gforge.inria.fr is down again, has been for some time: https://github.com/pfalcon/esp-open-sdk/issues/237

More recent gcc versions stopped downloading from isl.gforge.inria.fr, they now mirror the library on their own server which is how every project should isolate itself from external downtimes like this one:
https://gcc.gnu.org/install/prerequisites.html
https://gcc.gnu.org/pub/gcc/infrastructure/

**Comment by cpackham** [comment]
Already fixed in master https://github.com/crosstool-ng/crosstool-ng/pull/1614

If you're operating a mirror feel free to open a PR to add it.
