### ISSUE TITLE
Problem installing gettext for host: automake version mismatch.

### ISSUE THREAD

**Issue by zeebo** [crosstool-ng/crosstool-ng#770]
- crosstool-NG version:
  This is crosstool-NG version crosstool-ng-1.23.0

- host OS and its version:
   MacOS 10.12.5 using Homebrew
   brew list --full-name --versions: https://drive.google.com/open?id=0B2SHkzgbL0-tdmxlUEF0N2p0WVE

- Attach `.config`
   https://drive.google.com/open?id=0B2SHkzgbL0-tSjE2QndZeTVEejg

- Attach `build.log`
   from running `CT_PREFIX=$(pwd) ct-ng build.1` inside of `/Volumes/tucker/armhf` where `/Volumes/tucker` is a case-sensitive disk image:
   https://drive.google.com/open?id=0B2SHkzgbL0-tNlM4VnlIYzN4WjQ

- Error output

```
[ALL  ]    WARNING: 'automake-1.15' is probably too old.
[ALL  ]             You should only need it if you modified 'Makefile.am' or
[ALL  ]             'configure.ac' or m4 files included by 'configure.ac'.
[ALL  ]             The 'automake' program is part of the GNU Automake package:
[ALL  ]             <http://www.gnu.org/software/automake>
[ALL  ]             It also requires GNU Autoconf, GNU m4 and Perl in order to run:
[ALL  ]             <http://www.gnu.org/software/autoconf>
[ALL  ]             <http://www.gnu.org/software/m4/>
[ALL  ]             <http://www.perl.org/>
```

**Comment by Zi0P4tch0** [comment]
I had the same issue whilst installing gettext (I'm using crosstool-ng 1.23.0).

I solved it by going into the gettext source directory and running `autoreconf`.

Start the build again after that.

**Comment by zeebo** [comment]
Indeed, that does cause the compilation to proceed.

I'm hoping for a more automated solution, though, and I don't know where to begin looking to help get there.

**Comment by KirillSmirnov** [comment]
120-Fix-Woe32-link-errors-when-compiling-with-O0.patch for gettext 0.19.8.1 modifies Makefile.am and does not update Makefile.in, therefore configure tried to update it itself and we get complains and errors. The twin patch for gettext 0.19.7 does update Makefile.in, so it should not be any errors.

@zeebo, please try selecting gettext 0.19.7 to see whether it works on your system without any intervention.

**Comment by zeebo** [comment]
I don't see 0.19.7 as an option in my menuconfig. Do I have to downgrade my version of ct-ng or pass some flag when building it or something else?

**Comment by KirillSmirnov** [comment]
Just enable "Path and misc options"  -> "Use obsolete features" option, and 0.19.7 will appear in the list.

**Comment by zeebo** [comment]
That caused it to finish without intervention and everything seems to be working. I did see these apparently innocuous errors in the logs, though:

```
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    clang: error: unsupported option '-print-multi-os-directory'
[ERROR]    clang: error: no input files
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
```

**Comment by zeebo** [comment]
The error lines are already called out in the [os setup](https://crosstool-ng.github.io/docs/os-setup/) page as being harmless.

**Comment by alfishe** [comment]
highly annoying bug in 1.23 + MacOS :(

**Comment by pdinc-oss** [comment]
dito on commit 2ebbd3e3183ed18d13884ba6d30df09d16078fd0 
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-unknown-cygwin
[EXTRA]      host   = x86_64-unknown-cygwin
[EXTRA]      target = i686-centos7-linux-gnu

**Comment by akappel** [comment]
So if I understand correctly, this is not so much an issue in crosstool-NG, as it is an issue in gettext 0.19.8.1, which is what 1.23.0 is using. The `autoreconf` command fixes the issue (haven't tested the obsolete options fix) for me.

I'm guessing we'll need to drop a bug report at bug-gettext @ gnu.org to correctly patch 0.19.8.1's `Makefile.in` @KirillSmirnov? Will crosstool-NG automatically pull the latest version if they released a new one?

**Comment by stilor** [comment]
There are two facets of this problem:

First, the patch in question should, of course, modify both Makefile.am and Makefile.in. I will post a PR shortly.

Second, I want to get rid of the need to modify Makefile.in - many projects have bootstrap-like scripts that generate it, so it does not come as a part of `git show` (i.e. when we backport certain changes). But for that, we need to know which version of autoconf/automake was used by a each given release - some  packages may need versions "not older than X" and others may require "not younger than Y".

Which, in turn, means that for certain configurations it could be possible no single version of autoconf/automake would work for all packages. So, crosstool-NG should be able to build multiple versions of companion tools. It is possible, but currently not done.

**Comment by stilor** [comment]
Works now with my macos installation (10.12.x). Please give it a try.

**Comment by axos88** [comment]
I'm still having problems with 1.23.0, but asking for automake and autoconf in the companion tools seems to have worked around it.

**Comment by motters** [comment]
I was having the same issue, but adding automake and autoconf into the companion tools solved the issues like axos88 said.

**Comment by petemoore** [comment]
I worked around it with `brew switch automake 1.15`, but then hit a different issue (`ccQjTtXI.s:34: Error: selected processor does not support `vrintp.f64 d0,d0' in ARM mode`) but that may be an unrelated issue...
