### ISSUE TITLE
Build failed in step 'Building for multilib 1/1

### ISSUE THREAD

**Issue by Juanvmont** [crosstool-ng/crosstool-ng#771]
Hi, I am having this same error building for Multilib 1/1 with older versions of crosstool-NG. So I tried with other releases of glibc and recently with the current master but this is not solving the error. How can I avoid this while building?

- Report crosstool-NG version
crosstool-ng-1.23.0-90-g81327dd
- Report host OS and its version
Ubuntu 14.04 LTS 64-bits
- Attach `.config` (unless the issue is not related to any configuration)
[config.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1129234/config.log.tar.gz)

- Attach `build.log` (unless crosstool-NG fails before the build starts)
attached
[build.log.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1129236/build.log.tar.gz)

Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      collect2: error: ld returned 1 exit status
[ERROR]      make[3]: *** [/home/.../linux-embedded-labs/toolchain/crosstool-ng/.build/arm-mse-linux-gnueabihf/build/build-libc-final/multilib/elf/sln] Error 1
[ERROR]      make[3]: *** Waiting for unfinished jobs....
[ERROR]      make[2]: *** [elf/others] Error 2
[ERROR]      make[1]: *** [all] Error 2
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@454]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1761]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@150]
[ERROR]  >>        called from: do_libc[scripts/build/libc/glibc.sh@117]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@655]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      'docs/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 29:50.52)
[29:51] / make: *** [build] Error 2

**Comment by stilor** [comment]
````
/home/juanv/linux-embedded-labs/toolchain/crosstool-ng/.build/arm-mse-linux-gnueabihf/buildtools/lib/gcc/arm-mse-linux-gnueabihf/7.1.0/../../../../arm-mse-linux-gnueabihf/bin/ld.bfd: final link failed: No space left on device
````
This should give some hints, I think.
