### ISSUE TITLE
Bundled patches are not installed ?!?

### ISSUE THREAD

**Issue by artynet** [crosstool-ng/crosstool-ng#777]
- crosstool-NG @c609be17
- Ubuntu Linux 14.04 LTS x64

Is just my impression or with the new framework the bundled patches (which now are contained under the **packages/\<component\>** folder) are not installed ? In fact, **make install** returns a 'stat' error indicating that the **patches** folder has not been found. Can you give some hints about this, please ?

Best, Arturo

**Comment by sphawk** [comment]
I had same problem, and I copied packages folder to lib/crosstool-ng-1.23.0-XXXX/packages
and problem solved.

I think #696 is same problem

**Comment by stilor** [comment]
#696 has nothing to do with it

This is indeed an omission in the rework of the generated kconfig fragments for packages - I tested with `./configure --enable-local`.
