### ISSUE TITLE
There is no the file scripts/addToolVersion.sh in the latest version 1.23.0 . Why?

### ISSUE THREAD

**Issue by BNBullish** [crosstool-ng/crosstool-ng#783]
How could I do to achieve the purpose of adding other version of component(old version, can't find in the configuration given) with the latest 1.23.0 version ?

Could I install the old version, for example, 1.22.0.

*This is the first issue I submit. If I am wrong in expression, please understand.*

**Comment by cpackham** [comment]
It was moved to maintainer/addToolVersion.sh in commit 3906acc007 ("Move some scripts to a new directory, maintainer").

Has been removed from master in commit ff0a1a3da6 ("Switch gen-kconfig to new framework") and will likely be absent in the next release.

**Comment by BNBullish** [comment]
Thank you.
