### ISSUE TITLE
Support for building androideabi? 

### ISSUE THREAD

**Issue by Sudokamikaze** [crosstool-ng/crosstool-ng#787]
Planing support to compile androideabi toolchains?

I've finded some flags for this, it can be helpful
```
--target=arm-linux-androideabi --program-transform-name='s&^&arm-linux-androideabi-&'
```

**Comment by KirillSmirnov** [comment]
The target arm-unknown-linux-androideabi is supported, just not presented in the list of samples.
The quickest way to configure it is to select "aarch64-unknown-linux-android" sample and change bitness to 32.

**Comment by Sudokamikaze** [comment]
@KirillSmirnov Thanks a lot!
