### ISSUE TITLE
mismatch of libelf file type: downloaded as .tar.xz but in fact .tar.gz

### ISSUE THREAD

**Issue by ivosh** [crosstool-ng/crosstool-ng#789]
The default .config for my crosstool-ng specifies libelf mirror as http://www.mr511.de/software/
Then it tries to download libelf-0.8.13.* from it, starting with libelf-0.8.13.tar.xz.
The website responds successfully however the downloaded archive is in fact in .tar.gz format.
crosstool-ng then fails to unpack the downloaded archive with:

[EXTRA]    Extracting libelf-0.8.13
[DEBUG]    ==> Executing: 'touch' '/var/tmp/arm/cross/.build/src/.libelf-0.8.13.extracting' 
[DEBUG]    ==> Executing: 'mkdir' '-p' '/var/tmp/arm/cross/.build/src' 
[DEBUG]    ==> Executing: 'tar' 'x' '-v' '-f' '-' '-C' '/var/tmp/arm/cross/.build/src' 
[FILE ]    tar: Archive is compressed. Use -z option
[FILE ]    tar: Error is not recoverable: exiting now

$ ct-ng version
This is crosstool-NG version crosstool-ng-1.23.0-146-gbcaec4d8

$ uname -a
Linux 4.10.0-28-generic #32-Ubuntu SMP Fri Jun 30 05:32:18 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ivosh** [comment]
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1190318/build.log.txt)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1190320/config.txt)

**Comment by ivosh** [comment]
The problem is that http://www.mr511.de/software redirects crosstool-ng but it does not honour the redirected filename:

[EXTRA]    Retrieving 'libelf-0.8.13'
[DEBUG]    Trying 'http://www.mr511.de/software/libelf-0.8.13.tar.xz'
[DEBUG]    ==> Executing: 'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/var/tmp/arm/cross/.build/tarballs/libelf-0.8.13.tar.xz.tmp-dl' 'http://www.mr511.de/software/libelf-0.8.13.tar.xz' 
[ALL  ]    --2017-08-01 12:44:32--  http://www.mr511.de/software/libelf-0.8.13.tar.xz
[ALL  ]    Resolving www.mr511.de (www.mr511.de)... 217.160.231.164
[ALL  ]    Connecting to www.mr511.de (www.mr511.de)|217.160.231.164|:80... connected.
[ALL  ]    HTTP request sent, awaiting response... 301 Moved Permanently
[ALL  ]    Location: http://www.mr511.de/software/libelf-0.8.13.tar.gz [following]
[ALL  ]    --2017-08-01 12:44:33--  http://www.mr511.de/software/libelf-0.8.13.tar.gz
[ALL  ]    Reusing existing connection to www.mr511.de:80.
[ALL  ]    HTTP request sent, awaiting response... 200 OK
[ALL  ]    Length: 148529 (145K) [application/gzip]
[ALL  ]    Saving to: '/var/tmp/arm/cross/.build/tarballs/libelf-0.8.13.tar.xz.tmp-dl'
[ALL  ]    
[ALL  ]         0K ................ ..                               100%  462K=0.3s
[ALL  ]    
[ALL  ]    2017-08-01 12:44:33 (462 KB/s) - '/var/tmp/arm/cross/.build/tarballs/libelf-0.8.13.tar.xz.tmp-dl' saved [148529/148529]
[ALL  ]    
[DEBUG]    Got it from: "http://www.mr511.de/software/libelf-0.8.13.tar.xz"
[DEBUG]    Got 'libelf-0.8.13' from the Internet
[EXTRA]    Saving 'libelf-0.8.13.tar.xz' to local storage


However later on crosstool-ng tries to extract libelf as it was downloaded in .tar.xz format.

**Comment by flak3** [comment]
Same issue here

**Comment by fredbriand** [comment]
Hi. Had the same issue. I patched crosstool-ng/scripts/functions file in the sources to change the preferred archive formats order, and set tar.gz, tgz, bz2 top of the list. It solved the download issue.
I join the patch.

Now it's:
CT_DoListTarballExt()
{
    printf ".tar.gz\n.tgz\n"
    printf ".tar.bz2\n"
    printf ".tar.xz\n"
    printf ".tar.lzma\n"
    printf ".tar\n"
    printf ".zip\n"
}

you can also change: DIR/lib/crosstool-ng-1.23*/scripts/functions
[change_archive_formats_order.patch.txt](https://github.com/crosstool-ng/crosstool-ng/files/1232046/change_archive_formats_order.patch.txt)

**Comment by ileathan** [comment]
Im not sure how the above worked since the problem is that the tar command is executing without the `z` options. I went in to `crosstool-ng/scripts/functions` and directly made the tar command try with the -z option first and it worked.

*File edited:* `~/lib/crosstool-ng-1.23*/scripts/functions`

*Line changed:* `xz -fdc "${file}" | CT_DoExecLog FILE tar x -v -f - -C "${dir}" ${components}`

*Result:* `xz -fdc "${file}" | CT_DoExecLog FILE tar xz -v -f - -C "${dir}" ${components} ||  xz -fdc "${file}" | CT_DoExecLog FILE tar x -v -f - -C "${dir}" ${components}`

I just added `z` option for the case `*.tar.xz` and then or'd it in case the file isnt compressed.

**Comment by stilor** [comment]
What do you think the `xz -fdc` command is doing?

**Comment by fredbriand** [comment]
The problem was not related to a decompression flag, but is related to the download command:
http://www.mr511.de/software/libelf-0.8.13.tar.xz 
is actually a redirection to 
http://www.mr511.de/software/libelf-0.8.13.tar.gz

But the curl command writes the content of file to libelf-0.8.13.tar.xz

So you end up with a tar.gz file with a tar.xz  extension.
That's the reason why I preferred to try to download tar.gz first.

**Comment by stilor** [comment]
@fredbriand This is a workaround. Another is renaming the tarball to `.tar.gz` (or downloading the `.tar.gz` manually).

As a I will add a per-package list of tarball formats (this will also avoid attempting to download tarballs that don't exist) with libelf's list set to `.tar.gz`. Hopefully, tonight.

**Comment by fredbriand** [comment]
@stilor That's good!
I know it's just a workaround, that's why I didn't create a PR ;)
have fun! and thanks too!
