### ISSUE TITLE
Unable to build automake during cross compiler build process for PowerPc

### ISSUE THREAD

**Issue by sgosavi1** [crosstool-ng/crosstool-ng#794]
Hi,

I am trying to build cross compiler for a PowerPC target using crosstool-NG. The process is failing during the build process for automake. I spent some time going through the errors but not sure what is causing this error. I am building a cross compiler for the first time and hence would request anyone of you who have encountered a similar problem to help me get past this problem. The build log and config file is attached for reference.
[build.txt](https://github.com/crosstool-ng/crosstool-ng/files/1204609/build.txt)

[.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1204610/default.config.txt)

Version Details.
crosstool-NG version : 1.23.0
Host OS and its version: Fedora 25 - 32bit

Thanks,
Sachin

**Comment by KirillSmirnov** [comment]
Looks like https://bugzilla.redhat.com/show_bug.cgi?id=919810

The quick fix is:
yum install perl-Thread-Queue.noarch

Try this fix and report back, please.

**Comment by sgosavi1** [comment]
Hi KirillSmirnov,

Thanks for your response. I did the required perl  thread updated and performed a rebuild. But now getting different set of errors. Build log attached for your reference.
[build.txt](https://github.com/crosstool-ng/crosstool-ng/files/1206839/build.txt)

**Comment by sgosavi1** [comment]
Checked the build log for the last reported failure and identified that the below issue resulted in building the autoconf.

"Errno architecture (i386-linux-thread-multi-4.6.4-301.fc24.x86_64) does not match executable architecture"

Further checking on the web came across "https://bugzilla.redhat.com/show_bug.cgi?id=1393421" which suggested to update the perl-Errno on my Fedora 25 version. I did the yum update successfully and then again ran a rebuild of crosstool. This time both autoconf and automake were build and installed successfully.

**Comment by sgosavi1** [comment]
I made more progress on the build process and currently unable to process further as the build process exits due to error encountered while building binutils for the host. I spent some time looking at the build log and checked that the failure occurs while building the assembler in "gas" folder. 

Has anybody encountered similar problem? Can anybody suggest a possible fix for this issue? The build log is attached for reference.
[build.txt](https://github.com/crosstool-ng/crosstool-ng/files/1207535/build.txt)

**Comment by KirillSmirnov** [comment]
This option is the culprit:
CT_ARCH_SUFFIX="ppc_6xx"

This option is not an arch part of toolchain but just a suffix. With this option the toolchain tuple is called powerpcleppc_6xx-unknown-linux-gnu, which is unknown to BFD linker.

**Comment by sgosavi1** [comment]
Do I need to recreate the .config file for crosstool-ng and replace ppc_6xx- with PowePc instead?

**Comment by KirillSmirnov** [comment]
Leave this option empty:
CT_ARCH_SUFFIX=""

Just curious, why not use as-is well-tested sample powerpc-unknown-linux-gnu, shipping with crosstool-ng package?

**Comment by sgosavi1** [comment]
I can try as suggested by leaving this option empty. The reason I need "ppc_6xx-" string is currently we invoke our cross-compiler for the power PC target using this string. I need to upgrade our existing toolchain with new glibc library version support. Hence eventually I do need this string in order to ensure the developers continue using the newly build toolchain by invoking in the older way. 

Can this be done using crosstool or we need to switch to the new "powerpc-unknown-linux-gnu"?

**Comment by KirillSmirnov** [comment]
There is CT_TARGET_ALIAS option just for your case.
Set
CT_TARGET_ALIAS="ppc_6xx"
or whatever target you need. You will get GNU standard powerpc-unknown-linux-gnu toolchain, but it will happily act as ppc_6xx.

**Comment by sgosavi1** [comment]
Hi Kirill Smirnov,

Thanks for pointing this issue. It fixed my problem.

I got to a point when the pass 1 core GCC compiler installation was successful after setting the CT_ARCH_SUFFIX config option to blank. Now I got the below error suggesting failure in installing kernel headers.

[INFO ]  Installing kernel headers
[EXTRA]    Installing kernel headers
[ERROR]    gmake[2]: *** No rule to make target 'headers_install'.  Stop.
[ERROR]    gmake[1]: *** [headers_install] Error 2

The kernel version that I am using is 2.6.17.6 which we need to use on our target hardware and do not wish to upgrade yet to the newer version. After searching for help I found out that the "headers_install" target, required to install headers, is not supported by the older version of kernel that we use and hence the build is failing. I checked on the web on how to install headers for this older kernel version but did not get any concrete information. I

Is there a way out to fix this problem? 

Thanks for your support.

**Comment by KirillSmirnov** [comment]
You may try previous releases (<= 1.22.0) and KERNEL_LINUX_USE_CUSTOM_HEADERS option. It option is designed exactly for old kernels which does not support headers_install make target.

But I don't think you'll get any luck here, even if the new toolchain will be successfully built. Old kernel, bootloaders, and userspace will suffer under new gcc/binutils. More pain than gain, sad :-(

**Comment by sgosavi1** [comment]
Switched to kernel version 2.6.37.6 to address the install header issue. This version is supported by crosstool & hence the kernel headers were successfully installed but the build failed while installing C library headers and start files. The build log below suggests we need to further install headers from kernel version 3.2.0 for configuring libc.  

[ERROR]      configure: error: GNU libc requires kernel header files from
[CFG  ]      Linux 3.2.0 or later to be installed before configuring.
[CFG  ]      The kernel header files are found usually in /usr/include/asm and
[CFG  ]      /usr/include/linux; make sure these directories use files from
[CFG  ]      Linux 3.2.0 or later.  This check uses <linux/version.h>, so
[CFG  ]      make sure that file was built correctly when installing the kernel header
[CFG  ]      files.  To use kernel headers not from /usr/include/linux, use the
[CFG  ]      configure option --with-headers.

Not sure why can't the 2.6.37.6 for this purpose.

**Comment by KirillSmirnov** [comment]
glibc starting from 2.24 requires fresh kernel headers, at least 3.2. Moreover, I had troubles compiling old kernels (2.6.32) with gcc >= 5.

**Comment by sgosavi1** [comment]
Downgraded to glibc-2.23 version as it also suffice my requirement. The build proceeded successfully till the point where it tried to install cross-gdb. But it fails at this point due to the errors described below. 

[EXTRA]    Building cross-gdb
[ERROR]    configure: error: no usable python found at /usr/bin/python3
[ERROR]    gmake[2]: *** [configure-gdb] Error 1
[ERROR]    gmake[1]: *** [all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@162]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]

Python version 3.5 is available on my set up at /usr/bin but not sure why the script fails to locate it.
Commented the two lines below in file gdb/python/python-config.py as suggested on one of the forum but still faced the same issue.

#            if getvar('LINKFORSHARED') is not None:
#                libs.extend(getvar('LINKFORSHARED').split())

Can you suggest the possible reason and fix for this issue?

**Comment by KirillSmirnov** [comment]
Examine cross-gdb config.log for more details why python3 cannot be found.

**Comment by sgosavi1** [comment]
Installed the python3 headers to resolve the issue.  But now the build fails while building native gdb as it is unable to locate the expat library. Checked one of your earlier posts which suggests to pass "--without-libexpat-prefix" to the gdb configure script to fix the problem. I checked the build log and it is indeed passing this additional configuration parameter to gdb. But not sure why I am still facing the issue. The "libexpat.so" shared library is present at /usr/lib on my build machine. I also tried a rebuild after removing this shared library but not luck yet.

Is there anything else I need to do to fix this problem?

**Comment by KirillSmirnov** [comment]
That's very strange, libexpat issue has been fixed long ago.
Attach your latests config, build.log, and native-gdb/config.log

**Comment by KirillSmirnov** [comment]
There might be another issue with expat/gdb, unrelated to old one.

**Comment by sgosavi1** [comment]
Here are the requested files.

[crosstool_config.zip](https://github.com/crosstool-ng/crosstool-ng/files/1217271/crosstool_config.zip)

**Comment by KirillSmirnov** [comment]
Oops, I asked for wrong config.log for gdb. Not the main gdb-7.12.1/config.log needed, but gdb-7.12.1/gdb/config.log instead.

**Comment by sgosavi1** [comment]
Here is the required log file.
[gdb_config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1217387/gdb_config.txt)

**Comment by KirillSmirnov** [comment]
According to build.txt, CT_EXPAT_TARGET=y is disabled, therefore libexpat has not been installed at all, and gdb has no chance to find it.
According to crosstool_config, CT_EXPAT_TARGET is enabled.

build log and config file do not match! Something must be wrong. Let's track from the start. How did you configure, install and invoke ct-ng?

**Comment by sgosavi1** [comment]
Well I only configured the options of my interest such as CPU architecture, kernel version and glibc library version keeping most of the other parameters to the default values selected by the crosstool configuration. Followed the exact same instructions mentioned in the crosstool documentation section to build and install.

Not sure why the library appears disabled in the build and enabled in config file. Meanwhile I did a rebuild from the start, unlike the last time when I started from gdb-debug step, and this time the gdb-native installation was successful. Checked the log and could see that the expat library too was installed successfully. So as you rightly mentioned, the absence of expat library failed gdb in the previous case. Facing some issue to install ltrace but spend more time to identify and address the problem

Thanks once again for debugging and providing inputs to me. They have been immensely useful in the progress I have made till now. I will update you once I finish building the toolchain successfully.

**Comment by KirillSmirnov** [comment]
Good to hear that you passed that stage!

Consider disabling "Save intermediate steps" options, it brings more pain than gain to end-users.  Especially if config is constantly changing.

**Comment by sgosavi1** [comment]
Ltrace build is failing as it is not able to find powerpcle directory in build/build-ltrace/sysdeps/linux-gnu folder. I checked the this folder and it has ppc directory but not powerpcle. Please check the error messages below.

[ALL  ]    Making all in powerpcle
[ALL  ]    /usr/bin/bash: line 17: cd: powerpcle: No such file or directory
[ALL  ]    Makefile:382: recipe for target 'all-recursive' failed
[ERROR]    gmake[4]: *** [all-recursive] Error 1
[ALL  ]    gmake[4]: Leaving directory '/home/osboxes/GHOST_VULNERABILITY_FIX/source/crosstool-ng-1.23.0/.build/powerpcle-unknown-linux-gnu/build/build-ltrace/sysdeps/linux-gnu'
[ALL  ]    Makefile:299: recipe for target 'all-recursive' failed
[ERROR]    gmake[3]: *** [all-recursive] Error 1
[ALL  ]    gmake[3]: Leaving directory '/home/osboxes/GHOST_VULNERABILITY_FIX/source/crosstool-ng-1.23.0/.build/powerpcle-unknown-linux-gnu/build/build-ltrace/sysdeps'
[ALL  ]    Makefile:741: recipe for target 'all-recursive' failed
[ERROR]    gmake[2]: *** [all-recursive] Error 1
[ALL  ]    gmake[2]: Leaving directory '/home/osboxes/GHOST_VULNERABILITY_FIX/source/crosstool-ng-1.23.0/.build/powerpcle-unknown-linux-gnu/build/build-ltrace'
[ALL  ]    Makefile:447: recipe for target 'all' failed
[ERROR]    gmake[1]: *** [all] Error 2
[ALL  ]    gmake[1]: Leaving directory '/home/osboxes/GHOST_VULNERABILITY_FIX/source/crosstool-ng-1.23.0/.build/powerpcle-unknown-linux-gnu/build/build-ltrace

Who creates this directory and why is it not being created on my build machine?

**Comment by KirillSmirnov** [comment]
ltrace does not officially support powerpcle-* targets. Only these are supported:
        powerpc-*-linux-gnu
        powerpc64-*-linux-gnu
        powerpc64le-*-linux-gnu (current master only)

**Comment by sgosavi1** [comment]
I rebuilt without ltrace support and the build was completed successfully. Now I will actually build my kernel, root file system and application firmware for our target power PC board with this new toolchain to conduct some tests. 

Thanks for your support.

**Comment by stilor** [comment]
The need to install perl-Thread-Queue is documented in crosstool-NGs manual: http://crosstool-ng.github.io/docs/os-setup/

I'll add a dependency check for glibc/linux.
