### ISSUE TITLE
Adding MMU support for NIOS2

### ISSUE THREAD

**Issue by makoehr** [crosstool-ng/crosstool-ng#795]
Hi all,

with crosstool-NG version 1.23, the CPU NIOS2 is supported.
However, this CPU has an optional MMU which is not supported yet.
Please see the attached patch to enable the option to chose the MMU for NIOS2.
Also a tiny patch is provided that allows to use the NIOS2 to build the
toolchain for OS Linux.

Regards

Mathias

[nios2-enable-mmu.patch.txt](https://github.com/crosstool-ng/crosstool-ng/files/1210522/nios2-enable-mmu.patch.txt)

**Comment by KirillSmirnov** [comment]
This patch is generated against released version 1.23.0. There already are some nios2-related fixes in current master.

Have you succeeded building a _working_ toolchain for nios2/linux ? In the past I only managed to obtain nios2-unknown-linux-uclibc and it does not work as expected.

**Comment by makoehr** [comment]
I have been successful in buiilding a toolchain for Linux using the released version 1.23.0 + my patch.
However I used the glibc and not uclibc!
Also I set the CT_TARGET_VENDOR to "altera" to get a nios2-altera-linux-gnu- prefix for all the tools....

**Comment by stilor** [comment]
@makoehr Can you create a PR with the sample configuration that you used?

**Comment by stilor** [comment]
Have a look at #818 if I made that configuration right.

I didn't apply the CT_TARGET_SYS portion of your patch - I see that you refer to the target tuple as nios2-altera-linux-**gnu**, so apparently, leaving the "system" part as-is is not a problem.
