### ISSUE TITLE
powerpc64-multilib-linux-gnu failure

### ISSUE THREAD

**Issue by vk496** [crosstool-ng/crosstool-ng#798]
```bash
$ ct-ng powerpc64-multilib-linux-gnu
$ ct-ng build.1
```

Crosstool-NG version: **crosstool-ng-1.23.0-148-gf555602f**
Host OS : **Manjaro Linux 17 XFCE**
Kernel: **Linux vk496-pc 4.11.9-1-rt7-MANJARO SMP PREEMPT RT Tue Jul 11 23:23:30 UTC 2017 x86_64 GNU/Linux**
Attach: [**build.log.zip**](https://github.com/crosstool-ng/crosstool-ng/files/1227817/build.log.zip)

**Comment by vk496** [comment]
[https://sourceware.org/bugzilla/show_bug.cgi?id=21104](https://sourceware.org/bugzilla/show_bug.cgi?id=21104)

Seems that using `--with-guile=no` when compiling gdb make it work

**Comment by stilor** [comment]
Dup of #718
