### ISSUE TITLE
Missing RPC headers

### ISSUE THREAD

**Issue by nkumar15** [crosstool-ng/crosstool-ng#802]
Hello,

I have cross compiled GCC 4.9.4 toolchain. I believe from CT-NG-1.19 onwards enable-obsolete-rpc is by default included in glibc. However RPC headers are not still present in my generated toolchain.

Does it need to pass any flag explicitly?
Could somebody please help me to solve this problem?

Below are the details
---------
CT-NG version : 1.23.0
Host system    :  Ubuntu 16.04 x86_64

Attached is config and build log files.

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1230705/config.txt)
[build.log](https://drive.google.com/file/d/0BwUhq61FA9KfNDFPV0Fwa0ZrTDA/view?usp=sharing)

**Comment by stilor** [comment]
CT-NG still throws in this option to glibc's configure. But you're using glibc 2.15 and that option only appeared in 2.16, quote:
````

    New configure option --enable-obsolete-rpc makes the deprecated RPC

headers and functions available at compile time as they were before
version 2.14. This option will be removed at some time in the future
after the TI-RPC library becomes fully sufficient for the needs of
existing applications.
````
Linux-from-scratch [1] recommends copying the RPC headers from the glibc 2.15 sources manually:
````
cp -v ../glibc-2.15/sunrpc/rpc/*.h /usr/include/rpc
cp -v ../glibc-2.15/sunrpc/rpcsvc/*.h /usr/include/rpcsvc
cp -v ../glibc-2.15/nis/rpcsvc/*.h /usr/include/rpcsvc
````
I guess I'll add this for glibc versions <2.16.

[1] http://www.linuxfromscratch.org/lfs/view/jh/chapter06/glibc.html

**Comment by nkumar15** [comment]
Thanks Stilor,

Yes as mentioned in linux from scratch, copying the headers file explicitly. I did it, but when I tried to compile my program it failed with below error.

```
nfs_core.obj: In function `xdr_name':
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:66: undefined reference to `xdr_string'
nfs_core.obj: In function `xdr_dirpath':
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:73: undefined reference to `xdr_string'
nfs_core.obj: In function `xdr_groups':
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:84: undefined reference to `xdr_pointer'
nfs_core.obj: In function `xdr_exports':
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:101: undefined reference to `xdr_pointer'
nfs_core.obj: In function `NfsDetails::EnumHosts(std::list<NfsDetails::HostEnumInfo, std::allocator<NfsDetails::HostEnumInfo> >&)':
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:403: undefined reference to `clnt_broadcast'
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:405: undefined reference to `xdr_void'
nfs_core.obj: In function `NfsDetails::EnumShares(std::string const&, std::list<std::string, std::allocator<std::string> >&)':
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:427: undefined reference to `clnttcp_create'
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:435: undefined reference to `clntudp_create'
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:441: undefined reference to `authunix_create_default'
/home/neeraj/myprog/linex/nfs_supp/impl/nfs_core.cpp:466: undefined reference to `xdr_void'
```

I believe headers are copied, but still during glibc compilation, some of the libraries are not compiled which supports these symbols.

**Comment by stilor** [comment]
Well, it turned out they made these symbols unavailable for linking, not just disabled the installation of the header files. I backported the patch from 2.16 to support `--enable-obsolete-rpc`; posting the PR shortly.

You might want to try master once that PR is merged.
