### ISSUE TITLE
Two-pass build for GLIBC

### ISSUE THREAD

**Issue by stilor** [crosstool-ng/crosstool-ng#808]
In [1], Joseph Myers described how GLIBC should be built with only one bootstrap pass.

Highlights:
- pass-1 (which does not build libgcc at all) should not be needed; instead, pass-2 should build a static libgcc which should suffice for glibc build
- use `--with-glibc-version`
- current GLIBC requires GCC4.9 or newer - verify and record as a dependency
- if GLIBC test suite is to be run (currently not supported by ct-ng), need to rebuild glibc with a final compiler with C++ support; perhaps, a good thing to be offered as an option anyway.

[1] https://sourceware.org/ml/libc-alpha/2017-08/msg01026.html

**Comment by patrakov** [comment]
This bug also affects human-readable text at http://crosstool-ng.github.io/docs/toolchain-construction/
