### ISSUE TITLE
Build failed in step 'Installing ncurses for build'

### ISSUE THREAD

**Issue by morteryler** [crosstool-ng/crosstool-ng#815]
1) crosstool-ng-1.23.0-rc2
2) arch linux, 4.12.4-1-ARCH
3) Appended
[.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1253949/default.config.txt)
4) Appended
[build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1253950/build.log.txt)

Note: I added a flag to "Companion libraries> Extra configure arguments for target ncurses": --without-gpm, but it still does not help.

**Comment by stilor** [comment]
First, please attach `/home/user/compile-wget/.build/arm-unknown-linux-gnueabi/build/build-ncurses-build-x86_64-build_pc-linux-gnu/config.log` file. I'd like to see what the failing configure test does. I'll need this to fix it properly.

As to `--without-gpm`, you added it to *target* configure options. Currently, there is no way to supply it for *build*, only for *host* and for *target*. So as a workaround, you can add "--without-gpm" to the configure options in `do_ncurses_for_build` in `scripts/build/companion_libs/220-ncurses.sh`. I'll add the build configure arguments specification to config.

**Comment by morteryler** [comment]
> First, please attach /home/user/compile-wget/.build/arm-unknown-linux-gnueabi/build/build-ncurses-build-x86_64-build_pc-linux-gnu/config.log file. I'd like to see what the failing configure test does. I'll >need this to fix it properly.
>
> As to --without-gpm, you added it to target configure options. Currently, there is no way to supply it >for build, only for host and for target. So as a workaround, you can add "--without-gpm" to the >configure options in do_ncurses_for_build in scripts/build/companion_libs/220-ncurses.sh. I'll add the >build configure arguments specification to config.

I edited the file /usr/local/lib/crosstool-ng-1.23.0-rc2/scripts/build/companion_libs/220-ncurses.sh and I got this file, I added the necessary option:
[220-ncurses.sh.txt](https://github.com/crosstool-ng/crosstool-ng/files/1254303/220-ncurses.sh.txt)
But I had some other mistake, here are the logs:
/home/user/compile-wget/.build/arm-unknown-linux-gnueabi/build/build-ncurses-build-x86_64-build_pc-linux-gnu/config.log [config.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1254305/config.log.txt)
/home/user/compile-wget/build.log [build.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1254307/build.log.txt)

**Comment by stilor** [comment]
I asked for `config.log` **without** adding any options to 220-ncurses.sh.

**Comment by morteryler** [comment]
> I asked for config.log without adding any options to 220-ncurses.sh.

So you wrote that I should add the key there.
Here is the file you requested 
[config.log.txt](https://github.com/crosstool-ng/crosstool-ng/files/1256581/config.log.txt)

**Comment by stilor** [comment]
Quote:

> **First**, please attach /home/user/compile-wget/.build/arm-unknown-linux-gnueabi/build/build-ncurses-build-x86_64-build_pc-linux-gnu/config.log file. I'd like to see what **the failing configure test** does.

You again attached a `config.log` which already has `--without-gpm`. Please roll back this change, run `ct-ng build` and attach `config.log` from that run.

**Comment by morteryler** [comment]
I forgot to remove this key, but now deleted and here is my log> 
[bzip2.zip](https://github.com/crosstool-ng/crosstool-ng/files/1259906/bzip2.zip)

**Comment by stilor** [comment]
config.log, not build.log!

**Comment by morteryler** [comment]
> config.log, not build.log!

The find command. -iname config.log does not print anything, there is no such file

**Comment by stilor** [comment]
You did attach it previously. I even gave you a full path to it above.
Sorry, I am not wasting my time on this anymore.
