### ISSUE TITLE
The gcc of the crosstool-ng does not consider `$SYSROOT/usr/local/include` as an include path by default.It only consider `$SYSROOT/usr/include.

### ISSUE THREAD

**Issue by Farazata** [crosstool-ng/crosstool-ng#819]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by stilor** [comment]
From `info gccint`:
````
 -- Macro: LOCAL_INCLUDE_DIR
     Define this macro as a C string constant if you wish to override
     the standard choice of '/usr/local/include' as the default prefix
     to try when searching for local header files.  'LOCAL_INCLUDE_DIR'
     comes before 'NATIVE_SYSTEM_HEADER_DIR' (set in 'config.gcc',
     normally '/usr/include') in the search order.

     Cross compilers do not search either '/usr/local/include' or its
     replacement.
````

It is not a bug in ct-ng. If you want this changed, you'd better take this to GCC mailing list.

**Comment by stilor** [comment]
But look at `--with-local-prefix` in https://gcc.gnu.org/install/configure.html if that is what you need.

**Comment by Farazata** [comment]
No that will not work.
Because crosstool-ng is not create sysroot/usr/**local**/include folder at all it only creating sysroot/usr/include.

How will I get /usr/local/include foder under sysroot installation path.
