### ISSUE TITLE
How to change sysroot of toolchain from <ct-ng install path>/<host tuple>/sysroot/usr/include to <ct-ng install path>/<host tuple>/sysroot/usr/local/include

### ISSUE THREAD

**Issue by Farazata** [crosstool-ng/crosstool-ng#820]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by stilor** [comment]
Read about sysroot in GCC docs. Sysroot contains everything, not just headers - your question does not make sense.

**Comment by Farazata** [comment]
By default (i.e., if you don’t pass any arguments to the tools which would change this behaviour) the toolchain that is built by crosstool-NG will only look in its toolchain directories for system header and library files: 

#include "..." search starts here:
#include <...> search starts here:
<ct-ng install path>/lib/gcc/<host tuple>/4.5.2/include
<ct-ng install path>/lib/gcc/<host tuple>/4.5.2/include-fixed
<ct-ng install path>/lib/gcc/<host tuple>/4.5.2/../../../../<host tuple>/include
<ct-ng install path>/<host tuple>/sysroot/usr/include
 **In addition to this i want** 
<ct-ng install path>/<host tuple>/sysroot/usr/local/include

**Comment by buzzy** [comment]
@Farazata How/Where can I specify additional paths that the toolchain will search by default? When I do a canadian-build, even the basic "/usr/lib" and "/lib" is missing in my search paths.
