### ISSUE TITLE
Can't build unmodified sample 'x86_64-w64-mingw32,x86_64-pc-linux-gnu'

### ISSUE THREAD

**Issue by vmurashev** [crosstool-ng/crosstool-ng#821]
crosstool-NG version: crosstool-ng-1.23.0-202-g98b6a5a4 (today master)
host OS: Linux x86_64
I did defconfig/build.1 on the sample and got the error:
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20170831.153136
[INFO ]  Building environment variables
[WARN ]  Directory '/home/cislave/src' does not exist.
[WARN ]  Will not save downloaded tarballs to local storage.
[EXTRA]  Preparing working directories
[ERROR]  Missing: 'x86_64-w64-mingw32-ar' or 'x86_64-w64-mingw32-ar' or 'ar' : either needed!
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_Abort[scripts/functions@468]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@436]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >> NOTE: Your configuration includes features marked EXPERIMENTAL.
[ERROR]  >> Before submitting a bug report, try to reproduce it without enabling
[ERROR]  >> any experimental features. Otherwise, you'll need to debug it
[ERROR]  >> and present an explanation why it is a bug in crosstool-NG - or
[ERROR]  >> preferably, a fix.
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 0:00.81)
[00:01] / gmake[1]: *** [build] Error 1
gmake: *** [build.1] Error 2

**Comment by vmurashev** [comment]
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/1267104/build.zip)

**Comment by vmurashev** [comment]
Maybe I just did something wrong ?
@stilor could you please give me a hint ?
I expected to get mingw-w64 toolchain which I can use on windows to build target binaries for windows
Is this sample designed exactly for this purpose ?

**Comment by vmurashev** [comment]
The same error happens if I try released version of crosstool-ng-1.23.0

**Comment by stilor** [comment]
You need to build the `x86_64-w64-mingw32` toolchain first (it is also in the samples). See this chapter in the docs: http://crosstool-ng.github.io/docs/toolchain-types/
