### ISSUE TITLE
Endianness selection is disappeared from "Target options"

### ISSUE THREAD

**Issue by artynet** [crosstool-ng/crosstool-ng#825]
Host Setup :

- crosstool-NG @67d16f7
- Ubuntu 14.04 LTS 32-bit

Hello @stilor, it seems that Endianness selection from "**Target options**" is broken after your latest pushed commits, some of them concerning the support for both BE/LE when building a peculiar architecture. Could you double check please ?

Best, Arturo

**Comment by artynet** [comment]
maybe this might be the fix @stilor :

```patch
diff --git a/config/target.in b/config/target.in
index d3b5f083..677c67e3 100644
--- a/config/target.in
+++ b/config/target.in
@@ -121,7 +121,7 @@ config ARCH_DEFAULT_LE_BE
 choice
     bool
     prompt "Endianness:"
-    depends on ARCH_SUPPORTS_BOTH_ENDIAN
+    depends on ARCH_SUPPORTS_EITHER_ENDIAN
     default ARCH_BE if ARCH_DEFAULT_BE
     default ARCH_LE if ARCH_DEFAULT_LE
     default ARCH_BE_LE if ARCH_DEFAULT_BE_LE
```
please let me now while i test it with a simple build. Best, Arturo

**Comment by stilor** [comment]
Yes, that's the correct fix. Thanks.

**Comment by stilor** [comment]
Should be fixed now.
