### ISSUE TITLE
Build failed in step 'Installing final gcc compiler'

### ISSUE THREAD

**Issue by 172478394** [crosstool-ng/crosstool-ng#828]
I run crosstool-ng on ubuntu64. I want to build the cross-compiler on mipsel. CT_EXPERIMENTAL and CT_CC_SUPPORT_GOLANG was enabled. When installing final gcc compiler, i got these error:

[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[ERROR]    make[5]: *** [src/mips/o32.lo] Error 1
[ERROR]    make[5]: *** Waiting for unfinished jobs....
[ERROR]    make[4]: *** [all-recursive] Error 1
[ERROR]    make[3]: *** [all] Error 2
[ERROR]    make[2]: *** [all-target-libffi] Error 2
[ERROR]    make[2]: *** Waiting for unfinished jobs....
[ERROR]    make[1]: *** [all] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing final gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_gcc_backend[scripts/build/cc/100-gcc.sh@1145]
[ERROR]  >>        called from: do_gcc_for_host[scripts/build/cc/100-gcc.sh@832]
[ERROR]  >>        called from: do_cc_for_host[scripts/build/cc.sh@56]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@655]

**Comment by stilor** [comment]
First, read bug submission rules before hitting submit.
Second, Go support is known to be broken at this time.
