### ISSUE TITLE
/.build/tarballs/expat-2.2.0.tar.gz: not in gzip format

### ISSUE THREAD

**Issue by SpoTian** [crosstool-ng/crosstool-ng#829]
When compiling a toolchain using crosstool-NG-1.23.0 at Ubuntu 16.04.3 64-bit, I encounter the following error:
![image](https://user-images.githubusercontent.com/30916153/30147361-87f0bb4c-93d0-11e7-967a-3634c88707ec.png)

**Comment by stilor** [comment]
Looks like it downloaded some junk. I don't know what is at fault - your proxy, website being down, or what - but I just checked and 1.23.0 downloaded/extracted/patched expat just fine.
