### ISSUE TITLE
Can't build final compiler stage with experemental Ada support (undefined reference to `__gnat_runtime_finalize')

### ISSUE THREAD

**Issue by AnimusPEXUS** [crosstool-ng/crosstool-ng#83]
using crosstool-ng-1.20.0
Building 
   build  = i686-pc-linux-gnu 
   host   = i686-pc-linux-gnu 
   target = x86_64-pc-linux-gnu .

without gnat everything is working well and crosscompiler building finishes ok. But trying add experimental ada support - fails on final compiler building stage with undefined reference to `__gnat_runtime_finalize' . all downloaded tarballs are latest supported by crosstool-ng-1.20.0 .

few final lines from log:
https://gist.github.com/AnimusPEXUS/2d7a1366a261a29f2b68

**Comment by bhundven** [comment]
Are you using the 1.20.0 tarball or the latest git checkout?
Also, do you have the ada development packages for your distribution installed?

**Comment by AnimusPEXUS** [comment]
using checked out and bootstrapped 1.20.0 - not a tarball. latest checkout - crashed on some early stages so I didn't played with it.

build first native ada compiler year ago with official adacore.com compiler, so using only raw GCC tarballs for building with ada support since then.

>distribution installed
not a usual distribution. have an LFS like self made system - building all from tarballs. so all ada needed code shipped with gcc all-in-one tarball I guess.

**Comment by bhundven** [comment]
Yea, I'm getting a build error with ada enabled as well. I need to build with only one build job so I can understand what is happening. I'll look into that this weekend.

**Comment by bhundven** [comment]
What version is your build system's gnat?

**Comment by AnimusPEXUS** [comment]
~> gnat --version
GNAT 5.1.0

**Comment by bhundven** [comment]
Thanks. I'm running into the other issue where on Debian and Ubuntu, gnat is 4.9.2. (anyone know a ppa?)

**Comment by bhundven** [comment]
I have an arch-linux box I'm going to try next.

**Comment by AnimusPEXUS** [comment]
I have no this bug with crosstool-ng 1.21.0 + gcc 5.1.0 and crosscompiler gnat is built ok :)

**Comment by bhundven** [comment]
Ok, so this issue can be closed?

**Comment by AnimusPEXUS** [comment]
It's solved for Me. 
Thank You.
