### ISSUE TITLE
Android TLS problem

### ISSUE THREAD

**Issue by bog-dan-ro** [crosstool-ng/crosstool-ng#830]
I'm using crosstool-NG (42cb9694) to compile a toochain for android
Everything works fine but the problem is that when I'm trying to compile any C++11 apps which are using TLS e.g.:
 ` static thread_local int local = 0;`
I'm getting this:
`undefined reference to '__tls_get_addr'`
error.

For Android gcc should use EmuTLS instead.

**Comment by stilor** [comment]
I cannot reproduce. Using aarch64-unknown-linux-android sample, a small program like this
````
static thread_local int local __attribute__((used)) = 0;

int main() { return 0; }
````
compiles and links fine. Post your full .config and a test case.

**Comment by stilor** [comment]
Not reproduced and no response from OP.
