### ISSUE TITLE
arm samples : can select just one release of binutils-linaro

### ISSUE THREAD

**Issue by artynet** [crosstool-ng/crosstool-ng#831]
Host Setup :

- crosstool-NG @42cb969
- Ubuntu 14.04 LTS 32-bit

It seems that for certain samples (i.e for ARM for **raspberryPI**), I can select just one version of binutils linaro, specifically this one :

**2.25.0-2015.01-2**

while I would like to build the toolchain with a previous release to run my customised build tests. Any idea on this ?

Thanks in advance

**Comment by stilor** [comment]
You need to enable OBSOLETE option to select 2.23/2.24 based releases. Releases older than 2.23 are not currently supported.

**Comment by artynet** [comment]
of course I have already selected that but it's not working as it should....what am I missing ?

**Comment by stilor** [comment]
Then some other selections (GLIBC 2.26) you made in the configuration prevent these versions from being selected. For this kind of issues, you can press '/' in menuconfig, search for the symbol name and see what it depends upon. In this case, you would've seen that it depends on `!BINUTILS_REQUIRE_2_25_or_later`, which in turn is selected by GLIBC 2.26.

**Comment by artynet** [comment]
I'm working with the embedded libraries **musl** and **uClibc** and maybe I missed something....I'll double check and then report to you again.

Thanks
