### ISSUE TITLE
Cannot cross compile cramfs utiilty due to absence of shared zlib library.

### ISSUE THREAD

**Issue by sgosavi1** [crosstool-ng/crosstool-ng#835]
Hi All,

I recently successfully built the cross compiler for my target PowerPC board using crosstool-NG version 1.23.0. Since then I have been trying to build our existing code base with the new cross compiler.  I am currently facing issue while building "cramfs-1.1" application which we use to create our board firmware and root file system in cramfs format. The linker complains about missing zlib shared library. I searched for the shared library inside the location where the cross compiler was installed and it has a static version of zlib library but not the shared version. 

I installed zlib on my host Fedora 25 OS version which successfully created shared version of zlib library and hence I can successfully build the cramfs utility using the native GCC compiler.

I can also build this utility with our older cross compiler version which has the shared zlib library available in the installed location.

Can anyone tell me, how to force crosstool to build shared zlib library while building the cross compiler? 

Crosstool-NG Version - 1.23.0
Host OS - Fedora 25

Thanks,
Sachin

**Comment by stilor** [comment]
You need to build the required libraries with your cross-compiler first and either install them into sysroot. See how buildroot project does it, for example.

**Comment by sgosavi1** [comment]
Thanks for your response. I actually tried this already but faced issues while compiling the library. Hence just wanted to know the possibility to get this done through crosstool. 

I will debug and the compilation errors and install in sysroot manually as suggested.

Thanks.
