### ISSUE TITLE
Failed check: stat takes GNU or BSD format

### ISSUE THREAD

**Issue by karma0** [crosstool-ng/crosstool-ng#836]
Building the `github` version of crosstool-ng, or either of the `crosstool-ng` and `crosstool-ng-git` AUR packages under Arch Linux, I seem to run into this same issue on my machine.  This machine is a recently updated Arch Linux installation under VirtualBox.

Running the following:

    $ ./bootstrap
    $ ./configure --prefix=$HOME/local

Failure from:

    checking for stat... stat
    checking whether stat takes GNU or BSD format... configure: error: cannot determine stat(1) format option

Executing tests by hand:

    $ touch conftest
    $ chmod 642 conftest

BSD:

    $ stat -f '%Lp' conftest 2>/dev/null
      File: "conftest"
        ID: 2b42b60264bf7858 Namelen: 255     Type: ext2/ext3
    Block size: 4096       Fundamental block size: 4096
    Blocks: Total: 25671662   Free: 5788090    Available: 4473287
    Inodes: Total: 6553600    Free: 3513242

GNU:

    $ stat -c '%a' conftest 2>/dev/null
    642

Relevant section of the configure.ac:

    AC_CACHE_CHECK([whether stat takes GNU or BSD format],                        
         [acx_cv_stat_flavor],                                                     
         [touch conftest                                                           
          chmod 642 conftest                                                       
          attr_bsd=`stat -f '%Lp' conftest 2>/dev/null`                            
          attr_gnu=`stat -c '%a' conftest 2>/dev/null`                             
          rm -f conftest                                                           
          AS_IF([test "$attr_bsd" = "642"],                                        
            [acx_cv_stat_flavor=BSD],                                              
            [test "$attr_gnu" = "642"],                                            
            [acx_cv_stat_flavor=GNU],                                              
            [AC_MSG_ERROR([cannot determine stat(1) format option])])])

**Comment by cpackham** [comment]
@karma0 can you attach your config.log

**Comment by karma0** [comment]
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/1338037/config.log)

**Comment by stilor** [comment]
Cannot reproduce: I just ran my ArchLinux through `pacman -Syu`, and `configure` worked fine. I noticed however that your `config.log` mentions using `/usr/lib/cw/stat` and I do not have that directory. What is this `/usr/lib/cw/stat`? Does the error happen when you exclude `/usr/lib/cw` from your `$PATH`?

**Comment by karma0** [comment]
There's the problem.  Good eye!

CW is a set of wrapper scripts to colorize output ("color wrapper").  `./configure` works perfectly.

Thanks!
