### ISSUE TITLE
libexpat not being built for target

### ISSUE THREAD

**Issue by axay00** [crosstool-ng/crosstool-ng#840]
[.config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1357199/default.config.txt)

- Report crosstool-NG version: 1.23
- Report host OS and its version: Debian 9
- Attach `.config` (unless the issue is not related to any configuration)

- Attach `build.log` (unless crosstool-NG fails before the build starts)
[nolibexpat.zip](https://github.com/crosstool-ng/crosstool-ng/files/1357207/nolibexpat.zip)

With crosstool 1.21, libexpat was properly linking, with 1.23, it does not seem to be built. I have enabled companion tools.

error message: /opt/x-tools-006/x86_64-vss-linux-gnu/lib/gcc/x86_64-vss-linux-gnu/4.9.4/../../../../x86_64-vss-linux-gnu/bin/ld.bfd: cannot find -lexpat

**Comment by stilor** [comment]
The .config file you attached does not enable native GDB, so libexpat for target is not built. The build.log you attached shows a successful completion (except for GDB manuals build) and it does not contain the error message you quoted.

**Comment by stilor** [comment]
And, if I enable 'native GDB' in your config, expat for target is built and used for linking of the native GDB.

**Comment by axay00** [comment]
Thank you, that fixed it! (as an aside, is this the right forum for such
questions?)

-Akshay

**Comment by stilor** [comment]
Yes, it is the right place. I am still not sure how your native GDB was getting built if it was not enabled in the configuration, but if it works for you now, fine.
