### ISSUE TITLE
Build process fails during automake

### ISSUE THREAD

**Issue by funnypancakes** [crosstool-ng/crosstool-ng#843]
- Crosstool 1.23.0
- Host OS is Kali Linux. 4.12.0-kali2-amd64 running on Mac Book Pro (Dual Boot)

Using demo _mips-unknown-elf_ config with no modifications. (note that build process fails on other configs as well at the same step).

Error occurs during the make process process. Specifically : **`[ALL  ]    Makefile:3687: recipe for target 'doc/automake-1.15.1' failed
[ERROR]    make[1]: *** [doc/automake-1.15.1] Error 255`**

Please refer to attached build logs. 
[build1.log](https://github.com/crosstool-ng/crosstool-ng/files/1367215/build1.log)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1367216/build.log)

**Comment by funnypancakes** [comment]
Solved.

**Comment by stilor** [comment]
So what was the issue?

**Comment by funnypancakes** [comment]
Sorry - I would have posted it earlier but needed the compiler asap for a university assignment. 

From memory, i think I was lacking a dependency. After configuring again, the build failed on the 'installing final gcc' stage but I assumed this was just due to using gcc 7. The build failed, but I modified the ubsan.c file and re-ran it and it built fine. 

Compiler appears to be ok, but haven't tested it yet.
