### ISSUE TITLE
Is there a release planned that includes glibc-1.26?

### ISSUE THREAD

**Issue by tsdunc** [crosstool-ng/crosstool-ng#845]
I am using ct-ng version 1.23 for build a toolchain for ARM-1176jzf-s. This version supports only up to glibc-1.25.

I see that glibc-1.26 is available in the source repo. Is there a release planned soon to include the latest glibc?

Thanks!

**Comment by stilor** [comment]
It is already included in master and will thus be available in the next release. Or, you can use the bleeding edge and check out the current version from Git.
