### ISSUE TITLE
SVN errors at svn://svn.eglibc.org/

### ISSUE THREAD

**Issue by abelbeck** [crosstool-ng/crosstool-ng#85]
Hi,

When using crosstool-ng 1.20.0 and eglibc-2_18, the command
```
[DEBUG]    ==> Executing: 'svn' 'export' '-r' 'HEAD' 'svn://svn.eglibc.org/branches/eglibc-2_18/libc' 'eglibc-2_18'
```
Returns
```
svn: E020014: Can't find a temporary directory: Internal error
```

It seems the svn.eglibc.org server needs to be restarted. I know eglibc has ended, but many of us still want to use the eglibc goodness.  I tried to email the eglibc.org folks with no luck... does anyone know how to get the svn.eglibc.org server restarted ?

**Comment by bhundven** [comment]
eglibc is dead. in the latest git of crosstool-ng, it no longer exists.

**Comment by abelbeck** [comment]
Update:

The read-only eglibc SVN repository is now working again, 
having been moved to Linux Foundation systems, thanks to Michael Halstead.
