### ISSUE TITLE
Build failed in step 'Installing pass-1 core C gcc compiler'

### ISSUE THREAD

**Issue by iyop45** [crosstool-ng/crosstool-ng#854]
I'm attempting to build the cross-compiler toolchain for a linux kernel on a xilinx board I have. 
I'm running into the following error "Build failed in step 'Installing pass-1 core C gcc compiler'" and I'm not sure how to fix it. Any help would be greatly appreciated as I could not find much information online.

**Crosstool-NG**
This is crosstool-NG version crosstool-ng-1.23.0-240-gaec73d9-dirty

**Host:**
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.3 LTS
Release:	16.04
Codename:	xenial

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1430312/config.txt)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1430306/build.log)

### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by stilor** [comment]
Your config somehow has CPU variant "ev4" - which, I think, is a CPU variant for Alpha, not ARM. Not sure how it ended up there - did you take one of the `alpha-*` samples and edit it?

**Comment by 8ohmh** [comment]
Got the same eror in "back"-compiling the toolchain (Host: armv9, Build: i386, Target: i386) Due that I can't compile/use crossttools-ng on the arm host I have to do it on i386 and get the problem.

**Comment by 8ohmh** [comment]
Did you make 'ct-ng clean' before?

**Comment by minertom** [comment]
iyop45, did you find a fix for this issue? Build failed in step 'Installing pass-1 core C gcc compiler'

**Comment by stilor** [comment]
The fix is to remove the options not applicable to the selected architecture. This apparently started with either a configuration for alpha platform, or from an empty config (which selects alpha, as it is the first one alphabetically).

Either start from one of the samples for the architecture you're targeting, or go through all options and edit them as appropriate.

@minertom Check if you have the same message at the end of your build.log as the one attached here:
````
[ALL  ]    Unknown target in --with-cpu=ev4
[ALL  ]    Makefile:4152: recipe for target 'configure-gcc' failed
````
If you don't, you may have a different issue.

**Comment by minertom** [comment]
Thank you for the reply,

I am sure that I have a different issue.

Here is what is at the end of my build log.

ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from:
do_gcc_core_backend[scripts/build/cc/100-gcc.sh@537]
[ERROR]  >>        called from:
do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@112]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]


I used a "stock" configuration (made no changes to config with
menuconfig).  I had originally made some slight changes but did a make
clean and started over. Still the same error.

Should I create a new issue?

Regards
Tom

**Comment by magictomagic** [comment]
#992
