### ISSUE TITLE
collect2: error: ld returned 1 exit status

### ISSUE THREAD

**Issue by adekmaulana** [crosstool-ng/crosstool-ng#861]
### make[3]: *** [Makefile:982: libgcc_s.so] Error 1
- crosstool-NG version 1.23.0-246-ga266fea6
- Linux Mint 18.2 Sonya
- My config
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1463978/config.txt)
- some of build.log
`[ALL  ]    /home/adek/toolchain/out/aarch64-cortex_a53-linux-android/aarch64-cortex_a53-linux-android/bin/ld: cannot find crti.o: No such file or directory`
`[ALL  ]    /home/adek/toolchain/out/aarch64-cortex_a53-linux-android/aarch64-cortex_a53-linux-android/bin/ld: cannot find crtn.o: No such file or directory`
`[ERROR]    collect2: error: ld returned 1 exit status`
`[ERROR]    make[3]: *** [Makefile:982: libgcc_s.so] Error 1`
`[ALL  ]    make[3]: Leaving directory '/home/adek/toolchain/.build/aarch64-cortex_a53-linux-android/build/build-cc-gcc-final/aarch64-cortex_a53-linux-android/libgcc'`
`[ERROR]    make[2]: *** [Makefile:11193: all-target-libgcc] Error 2`
`[ALL  ]    make[2]: Leaving directory '/home/adek/toolchain/.build/aarch64-cortex_a53-linux-android/build/build-cc-gcc-final'`
`[ERROR]    make[1]: *** [Makefile:878: all] Error 2`
`[ALL  ]    make[1]: Leaving directory '/home/adek/toolchain/.build/aarch64-cortex_a53-linux-android/build/build-cc-gcc-final'`
[build.txt](https://github.com/crosstool-ng/crosstool-ng/files/1463984/build.txt)

Hello sir, i'm noob about toolchain, and i wanted to make my own personal toolchain for optimized my cpu for kernel compiling, but i always gets this error, i've tried everything, change sysroot or use prefix and i have that file on
`/usr/lib/x86_64-linux-gnu`
`/usr/lib32`
`/usr/libx32`
and i already tried to symlink on /usr/lib64
i'm stuck here for 3 days, and i already install all depencies that need, and i have GCC installed on my Mint version `gcc (Ubuntu 7.2.0-1ubuntu1~16.04) 7.2.0`
sorry for this noob question, but i don't know where else to go, any help would be so appreciate !
again sorry and thank you!

**Comment by stilor** [comment]
You are using unreleased version of gcc-linaro (that, and some other components as well). Because of this crosstool-NG does not apply the patches it has for various components (look into `packages/gcc-linaro/7.1-2017.08`, for example).

Try with a supplied android sample first. If it works, change the components one by one until you see the one failing. You might need to apply at least some of the patches.

**Comment by adekmaulana** [comment]
using NDK supplied still falling, will look into another thank you!

**Comment by adekmaulana** [comment]
ok it seems the problems is on GCC snapshots i use supplied it's builded, thank you sir! will look into patches to use snapshots
