### ISSUE TITLE
build fails at debug step ltrace

### ISSUE THREAD

**Issue by ph4r** [crosstool-ng/crosstool-ng#865]
Using crosstool-ng 1.23.0
Running on Ubuntu Linux 4.10.0-38-generic #42~16.04.1-Ubuntu SMP Tue Oct 10 16:32:20 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
Config and build log included in tarball attached.

Final reported Error: 
[EXTRA]    Building ltrace [ERROR]    ../../../libtool: 1: eval: base_compile+= -Werror: not found

[ctng.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1471270/ctng.tar.gz)

**Comment by stilor** [comment]
For some reason, `configure` in ltrace decided to pick `/bin/sh` as the shell to use (which on Ubuntu points to `dash`, not `bash`) - which then confused `libtool`. I cannot reproduce this issue though - just ran your config on Ubuntu 17.04 and it built fine.

Can you attach these files from the build tree:
- `targets/arm-arm9-linux-gnueabi/build/build-ltrace/config.log`
- `targets/arm-arm9-linux-gnueabi/build/build-ltrace/sysdeps/linux-gnu/arm/Makefile`
?

**Comment by ph4r** [comment]
Here are the requested files  
[Ltrace-error.zip](https://github.com/crosstool-ng/crosstool-ng/files/1473225/Ltrace-error.zip)

**Comment by stilor** [comment]
So, I did reproduce it. It only happens if you restart the build at the `debug` step. I'll see if this issue exists in master.

**Comment by ph4r** [comment]
To be clear, this happened on the initial build as well.  Thank you for the attention, I understand that you want to correct the bug, but is there a quick win for me as I really need to test a build that I am trying to upgrade from an older crosstool [not ctng] cygwin install?  I tried manually changing the path in the makefile you requested to /bin/bash and restarting from debug and it overwrote the makefile back to /bin/sh and failed in the same manner.

**Comment by stilor** [comment]
First, the issue with ltrace after build restart has been fixed in master. See #760 and the continued discussion in #762.

However, I don't see how this can happen without restarting the build: as explained in #760, crosstool-NG does set `CONFIG_SHELL` and `SHELL` environment variables, which should've prevented ltrace from using `/bin/sh`.

The build.log file you attached does show the build been restarted. If the build fails in the same way without restarting (and note, doing build step-by-step is also considered restarting) - please attach the build log from a build invoked as a single run (i.e. `ct-ng build`).

**Comment by ph4r** [comment]
I am working from the [1.23.0 bz2 file](http://crosstool-ng.org/download/crosstool-ng/) from April and not from the github code.  That commit is from August it appears.  I will try updating to the repo; however, I'm confused now which to use: [stilor/crosstool-ng](https://github.com/stilor/crosstool-ng) [where that commit occurs] or [crosstool-ng/crosstool-ng](https://github.com/crosstool-ng/crosstool-ng)?  After that I can restart the build.

**Comment by stilor** [comment]
I asked you to confirm the issue with 1.23.0 - if it happens without restarting build or doing it one step at a time, attach the log of that build.

But if you want to try out master, crosstool-ng/crosstool-ng is the official repo. stilor/crosstool-ng is the fork where I do dev work before posting it as PRs.

**Comment by ph4r** [comment]
OK, I did a ct-ng clean and started a ct-ng build.  I'll try and check in after a couple hours, or I will update in the morning.  If it fails again, I will upload the log and clone the repo to re-execute.

**Comment by ph4r** [comment]
Still on 1.23.0 and it did complete this time!  Not sure why it stopped the first time, but I'll take it.  I can't wait to test my build in the morning.
