### ISSUE TITLE
arm-cortex_a8-linux-gnueabi fail

### ISSUE THREAD

**Issue by Dr-ohZ** [crosstool-ng/crosstool-ng#866]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
crosstool-ng-1.23.0 - Report crosstool-NG version
Ubuntu 16.10 - Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

i need help!

joao@joao-Aspire-E5-574:/opt/toolchain/crosstool-ng-1.23.0$ ct-ng build
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20171116.113848
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@268]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/local/share/doc/crosstool-ng/crosstool-ng-1.23.0/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 0:00.21)
[00:01] / /usr/local/bin/ct-ng:147: recipe for target 'build' failed
make: *** [build] Error 1

i tried many times, but nothing works.

**Comment by stilor** [comment]
You didn't attach the build log and .config. If you looked into build.lg, you'll immediately see that the ct-ng does not have the permission to create the path you configured for CT_PREFIX_DIR.
