### ISSUE TITLE
No usable python found... with Python v2.7.12

### ISSUE THREAD

**Issue by robiwano** [crosstool-ng/crosstool-ng#872]
- Report crosstool-NG version
crosstool-ng-1.23.0-250-g8c581c2

- Report host OS and its version
Ubuntu 16.04.1 LTS 
Linux 4.4.0-43-Microsoft #1-Microsoft Wed Dec 31 14:42:53 PST 2014 x86_64 x86_64 x86_64 GNU/Linux

- Attach `.config` (unless the issue is not related to any configuration)
Using Raspberry Pi 3 example

- Attach `build.log` (unless crosstool-NG fails before the build starts)
[INFO ]  Installing final gcc compiler
[EXTRA]    Configuring final gcc compiler
[EXTRA]    Building final gcc compiler
[EXTRA]    Installing final gcc compiler
[EXTRA]    Housekeeping for final gcc compiler
[EXTRA]       '' --> lib (gcc)   lib (os)
[INFO ]  Installing final gcc compiler: done in 1872.84s (at 111:58)
[INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[ERROR]    configure: error: no usable python found at /usr/bin/python
[ERROR]    make[2]: *** [configure-gdb] Error 1
[ERROR]    make[1]: *** [all] Error 2
[ERROR]  /
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@372]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@135]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@675]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/

The result of:
host:~/tools/crosstool-ng$ /usr/bin/python --version
Python 2.7.12

**Comment by robiwano** [comment]
Tried with Python v3.5.2, same problem. During building of cross-gdb, I get:
INFO ]  =================================================================
[INFO ]  Installing cross-gdb
[EXTRA]    Configuring cross-gdb
[EXTRA]    Building cross-gdb
[ERROR]    configure: error: no usable python found at /usr/bin/python
[ERROR]    make[2]: *** [configure-gdb] Error 1
[ERROR]    make[1]: *** [all] Error 2

/usr/bin/python exists AND is working quite fine!

**Comment by stilor** [comment]
You need to install python header files (python-dev package on Ubuntu, IIRC).

**Comment by stilor** [comment]
See here: http://crosstool-ng.github.io/docs/os-setup/

**Comment by robiwano** [comment]
Doh! Thanx. Of course.

**Comment by saloalexey** [comment]
The same ERROR but i try with CT_GDB_CROSS_STATIC=y option.
I've done all recomendation below. I've installed python-dev package.

From config.log : 
/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libpython2.7.a(socketmodule.o): In function `socket_getservbyport':
(.text.unlikely+0x2c2e): warning: Using 'getservbyport' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking

/usr/bin/ld: dynamic STT_GNU_IFUNC symbol `strcmp' with pointer equality in `/usr/lib/gcc/x86_64-linux-gnu/5/../../../x86_64-linux-gnu/libc.a(strcmp.o)' can not be used when making an executable; recompile with -fPIE and relink with -pie

From build.log: 
[ALL  ]    checking whether to use python... /usr/bin/python
[ALL  ]    checking for python2.7... no
[ERROR]    configure: error: no usable python found at /usr/bin/python
[ALL  ]    Makefile:8797: recipe for target 'configure-gdb' failed
[ERROR]    make[2]: *** [configure-gdb] Error 1
[ALL  ]    make[2]: Leaving directory '/home/.../.build-toolchain/.build/armv5t-iotecha-linux-gnueabi/build/build-gdb-cross'
[ALL  ]    Makefile:850: recipe for target 'all' failed
[ERROR]    make[1]: *** [all] Error 2
[ALL  ]    make[1]: Leaving directory '/home/.../.build-toolchain/.build/armv5t-iotecha-linux-gnueabi/build/build-gdb-cross'
[ERROR]  
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing cross-gdb'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_debug_gdb_build[scripts/build/debug/300-gdb.sh@165]
[ERROR]  >>        called from: do_debug[scripts/build/debug.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/home/.../crosstool-ng/share/doc/crosstool-ng/crosstool-ng-1.23.0/B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]  
[ERROR]  (elapsed: 41:40.82)
