### ISSUE TITLE
PPC build errors

### ISSUE THREAD

**Issue by SergeyDjam** [crosstool-ng/crosstool-ng#873]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
1.23.0 release

- Report host OS and its version
cat /etc/release 
ROSA Desktop Fresh R8.1 release 2014.1 for x86_64

uname -a
Linux nb 4.9.41-nrj-desktop-1rosa-x86_64 #1 SMP PREEMPT Fri Aug 11 11:00:08 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

- Attach `.config` (unless the issue is not related to any configuration)
This config is sample config powerpc-405-linux-gnu

[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1517739/config.txt)

- Attach `build.log` (unless crosstool-NG fails before the build starts)

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1517742/build.log)

[EXTRA]    Patching 'ncurses-6.0'
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Extracting and patching toolchain components'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: CT_Patch[scripts/functions@1271]
[ERROR]  >>        called from: do_ncurses_extract[scripts/build/companion_libs/220-ncurses.sh@20]
[ERROR]  >>        called from: do_companion_libs_extract[scripts/build/companion_libs.sh@22]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@621]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      '/usr/share/doc/crosstool-ng//B - Known issues.txt'
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]   
[ERROR]  (elapsed: 15:24.66)
[15:25] / gmake: *** [/usr/bin/ct-ng:147: build] Ошибка 1

**Comment by stilor** [comment]
You already submitted exactly the same issue, #605, and we determined there that the problem was not in the crosstool-ng, but rather that the packaging (RPM) mangles the patches, converting windows-style line endings.

**Comment by SergeyDjam** [comment]
Oh, sorry. 
Yes i fix it
