### ISSUE TITLE
Multilib for ARMv5T-E and ARMv7E-M with bi-endian

### ISSUE THREAD

**Issue by klimentyev** [crosstool-ng/crosstool-ng#880]
Can I build the toolchain with multilib for ARMv5T-E big endian and ARMv7E-M little endian targets (or bi-endian for both architectures) with softfp/hard by Crosstool? Should I patch the t-arm-elf file in GCC sources? And how do I set this list in the Crosstool settings? Only by 'aprofile' value?

**Comment by stilor** [comment]
Yes, AFAIU there is no way for A-profile to select the multilib variants when configuring the GCC. You'd have to patch the t-arm-elf and/or config.gcc.

**Comment by klimentyev** [comment]
Thank you for your quick response.
