### ISSUE TITLE
macOS 10.13: fatal error: bits/range_access.h: No such file or directory

### ISSUE THREAD

**Issue by TimothyKlim** [crosstool-ng/crosstool-ng#883]
- crosstool-NG version: master@4088f4852ce853115092834c49c1cad6aafe492d
- host OS and its version: macOS 10.13.2
[build.log.gz](https://github.com/crosstool-ng/crosstool-ng/files/1565130/build.log.gz)
[config.gz](https://github.com/crosstool-ng/crosstool-ng/files/1565131/config.gz)

**Comment by KirillSmirnov** [comment]
Try disabling pre-compiled headers (C compiler -> Do not build PCH), they are broken in some configurations.

**Comment by TimothyKlim** [comment]
Yeah, that's works! Thanks!
