### ISSUE TITLE
Python error building cross-compiler for armv7-rpi2-linux-gnueabihf

### ISSUE THREAD

**Issue by tardis4500** [crosstool-ng/crosstool-ng#886]
[build.zip](https://github.com/crosstool-ng/crosstool-ng/files/1566397/build.zip)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/1566398/config.txt)

I am using the latest crosstool-NG cloned from GitHub 
The host OS is Ubuntu 16.04.3 LTS
I have successfully built the cross compiler for arm-unknown-linux-gnueabi but when I try to build for armv7-rpi2-linux-gnueabihf, I get an error during the "Installing cross-gdb" that "configure: error: no usable python found at /usr/bin/python3". The build log, attached, says

[ALL  ]    checking whether to use python... /usr/bin/python3
[ALL  ]    checking for python3.5... no
[ERROR]    configure: error: no usable python found at /usr/bin/python3

Even though both /usr/bin/python3 and /usr/bin/python3.5 are there and python3 -V reports 3.5.2.

**Comment by stilor** [comment]
Reading the docs (http://crosstool-ng.github.io/docs/os-setup/) or searching the issues before posting (#872) usually helps/
