### ISSUE TITLE
For some combinations of build and host gcc versions, host toolchain is not stripped

### ISSUE THREAD

**Issue by igrr** [crosstool-ng/crosstool-ng#887]
- crosstool-NG version: crosstool-ng-1.23.0-288-gadaa3a5d (latest master as of today)
- host OS and its version: Debian Stretch 9.2
- [.config](https://gist.github.com/igrr/13749ba9fa8653841747e50dbec04059): arm-unknown-eabi sample, with GCC version set to 5.5.0. Also a few other options might have been changed w.r.t. the sample while debugging this issue.
- [build.log](http://download.igrr.me/ct-ng-build-20171218.log)

When build GCC, compiled with `--enabled-default-pie`, is used to compile GCC version which is older than https://github.com/gcc-mirror/gcc/commit/e9abca4f4a48fa8b1fd9778f6a3cd748e099e3bb, resulting toolchain executables are position-independent. This is because versions older than that commit do not add `NO_PIE_FLAG` to `LDFLAGS`.

The issue can be reproduced, for example, using debian:stretch docker image. Its `gcc -v` output is as below.
<details>
<summary> gcc -v </summary>

```
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/6/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 6.3.0-18' --with-bugurl=file:///usr/share/doc/gcc-6/README.Bugs --enable-languages=c,ada,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-6 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-6-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-6-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-6-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 6.3.0 20170516 (Debian 6.3.0-18)
```
</details>
<br><br>

One side effect of this is that PIE results in a different output of `file` command, compared to non-PIE.

E.g. non-PIE:
```
xgcc: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=cb345b04c3b429eb6c2084d47d5bb6bea016754d, not stripped
```

PIE:
```
xgcc: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 2.6.32, BuildID[sha1]=ef39ca60f0cdfba04064d8d59c709bf108b28fb7, not stripped
```

When `CT_STRIP_HOST_TOOLCHAIN_EXECUTABLES` option is enabled, `do_finish` [checks `file` output](https://github.com/crosstool-ng/crosstool-ng/blob/adaa3a5d8b4e2834a8c2c79efcdd3c718236ba5a/scripts/build/internals.sh#L96) to decide whether the file needs to be stripped or not. Since `*executable*` pattern is not matched, host toolchain does not get stripped.

I suppose that this can be fixed by adding -no-pie to `CT_EXTRA_LDFLAGS_FOR_HOST` if GCC version is less than the one where `NO_PIE_FLAG` was introduced. Making the check in `do_finish` more robust, in case someone actually wants to build a PIE toolchain, might also make sense.

Edit: due to the check for `executable` file type, LTO library (liblto_plugin.so) is never stripped (unrelated to PIE).

Edit 2: it looks like `CT_EXTRA_LDFLAGS_FOR_HOST` is not applied when building GDB, so host GDB also ends up being PIE and not stripped.

**Comment by antmak** [comment]
@stilor  I run into the same issue . Any ideas how to fix it most correctly?

**Comment by stilor** [comment]
One could test for `interpreter` being reported - some shared library (e.g. glibc) request interpreter from a shared library, but presumably we don't build glibc for *host*.

That said, I have very limited time to spend on ct-ng at this time - and whatever I have, I might need to spend on fixing the issues after bringing in GCC8. I'd be happy to review a PR should you submit one :)

**Comment by bhundven** [comment]
@stilor I might be able to help out more soon.

**Comment by cpackham** [comment]
I can't seem to reproduce this (debian buster). None of the output binaries identify as shared object for me.

I get `ELF 64-bit LSB executable` and `ELF 64-bit LSB pie executable`. I wonder if `file` has been updated to identify these.

The following should fix the reported issue

```
diff --git a/scripts/build/internals.sh b/scripts/build/internals.sh
index 5d359979..821761c2 100644
--- a/scripts/build/internals.sh
+++ b/scripts/build/internals.sh
@@ -83,7 +83,7 @@ do_finish() {
                 case "${_type}" in
                     *script*executable*)
                         ;;
-                    *executable*)
+                    *executable*|*shared*object*)
                         CT_DoExecLog ALL ${CT_HOST}-strip ${strip_args} "${_t}"
                         ;;
                 esac
```

**Comment by cpackham** [comment]
I made a debain-stretch container and can reproduce it.
