### ISSUE TITLE
Problem with ltrace which building aarch64-none-linux-gnueabi toolchain

### ISSUE THREAD

**Issue by Farazata** [crosstool-ng/crosstool-ng#888]
Hii

Crosstool-ng is throwing error which building ltrace for arm toolcahin.

logs-

[EXTRA]    Building ltrace
[DEBUG]    ==> Executing: 'make'
[ALL  ]    make[1]: Entering directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace'
[ALL  ]    /usr/bin/make  all-recursive
[ALL  ]    make[2]: Entering directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace'
[ALL  ]    Making all in sysdeps
[ALL  ]    make[3]: Entering directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace/sysdeps'
[ALL  ]    Making all in linux-gnu
[ALL  ]    make[4]: Entering directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace/sysdeps/linux-gnu'
[ALL  ]    Making all in aarch64
**# [ALL  **]    /bin/bash: line 17: cd: aarch64: No such file or directory****
[ERROR]    make[4]: *** [all-recursive] Error 1
[ALL  ]    make[4]: Leaving directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace/sysdeps/linux-gnu'
[ERROR]    make[3]: *** [all-recursive] Error 1
[ALL  ]    make[3]: Leaving directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace/sysdeps'
[ERROR]    make[2]: *** [all-recursive] Error 1
[ALL  ]    make[2]: Leaving directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace'
[ERROR]    make[1]: *** [all] Error 2
[ALL  ]    make[1]: Leaving directory `/home/an91kor/Downloads/crosstool-ng-1.23.0/.build/aarch64-none-linux-gnueabi/build/build-ltrace'

**Comment by lmxx1234567** [comment]
I meet the same error in building ltrace 😢

**Comment by stilor** [comment]
This is a wrong place to complain: that project does not implement aarch64 support (and from what I see, is essentially unmaintained). Adopt it and start maintaining it if it matters to you :)

**Comment by nivpgir** [comment]
but shouldn't ct-ng at least prevent you from trying to use it with aarch64?
remove it from the config when compiling aarch64?
print a warning?
put a warning in the ltrace help section?
