### ISSUE TITLE
error when building xtensa-esp32-elf on armv7l environment

### ISSUE THREAD

**Issue by sepplfromvienna** [crosstool-ng/crosstool-ng#889]
I'am using crosstool-NG version crosstool-ng-1.22.0-75-gbaf03c2,
trying to compile on an Ubuntu 16.04.3 LTS running on ARMv7 Processor rev 10 (v7l)

My first issue was that it didn't compile GMP for host.
build.log:

[ALL  ]    /bin/bash ../libtool --tag=CC   --mode=compile gcc -DHAVE_CONFIG_H -I. -I/home/esp32/crosstool-NG/.build/src/gmp-6.0.0a/mpn -I.. -D__GMP_WITHIN_GMP -I/home/esp32/crosstool-NG/.build/src/gmp-6.0.0a -DOPERATION_`echo div_qr_2n_pi1 | sed 's/_$//'`    -O2 -g -pipe  -fexceptions -c -o div_qr_2n_pi1.lo div_qr_2n_pi1.c
[ALL  ]    {standard input}: Assembler messages:
[ALL  ]    {standard input}:202: Error: thumb conditional instruction should be in IT block -- `movcc r9,#0'
[ALL  ]    {standard input}:203: Error: thumb conditional instruction should be in IT block -- `movcs r9,#-1'
[ALL  ]    {standard input}:222: Error: thumb conditional instruction should be in IT block -- `movcc r9,#0'
[ALL  ]    {standard input}:223: Error: thumb conditional instruction should be in IT block -- `movcs r9,#-1'
[ALL  ]    Makefile:409: recipe for target 'div_qr_1n_pi1.lo' failed
[ERROR]    make[3]: *** [div_qr_1n_pi1.lo] Error 1

After a little searching with google i found a working solution:

--- ./.build/src/gmp-6.0.0a/mpn/generic/div_qr_1n_pi1.c.orig    2017-12-26 12:53:29.072948122 +0100
+++ ./.build/src/gmp-6.0.0a/mpn/generic/div_qr_1n_pi1.c 2017-12-26 12:52:02.628508303 +0100
@@ -130,7 +130,7 @@
             "%2" ((UDItype)(a0)), "r" ((UDItype)(b0)) __CLOBBER_CC)
 #endif

-#if defined (__arm__) && W_TYPE_SIZE == 32
+#if defined (__arm__) && !defined (__thumb__) && W_TYPE_SIZE == 32
 #define add_mssaaaa(m, sh, sl, ah, al, bh, bl)                         \
   __asm__ (  "adds     %2, %5, %6\n\t"                                 \
             "adcs      %1, %3, %4\n\t"                                 \

after I patched this file I could compile GMP for host, but than I was running in the next issue:

[INFO ]  =================================================================
[INFO ]  Installing pass-2 core C gcc compiler
[ERROR]    checking for suffix of object files... configure: error: in `/home/esp32/crosstool-NG/.build/xtensa-esp32-elf/build/build-cc-gcc-core-pass-2/xtensa-esp32-elf/libgcc':
[ERROR]    configure: error: cannot compute suffix of object files: cannot compile
[ERROR]    make[1]: *** [configure-target-libgcc] Error 1
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-2 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@257]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@545]
[ERROR]  >>        called from: do_gcc_core_pass_2[scripts/build/cc/100-gcc.sh@160]
[ERROR]  >>        called from: do_cc_core_pass_2[scripts/build/cc.sh@42]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@646]

config.log tells me:

configure:3682:  /home/esp32/crosstool-NG/.build/xtensa-esp32-elf/build/build-cc-gcc-core-pass-2/./gcc/xgcc -B/home/esp32/crosstool-NG/.build/xtensa-esp32-elf/build/build-cc-gcc-core-pass-2/./gcc/ -B/home/esp32/crosstool-NG/.build/xtensa-esp32-elf/buildtools/xtensa-esp32-elf/bin/ -B/home/esp32/crosstool-NG/.build/xtensa-esp32-elf/buildtools/xtensa-esp32-elf/lib/ -isystem /home/esp32/crosstool-NG/.build/xtensa-esp32-elf/buildtools/xtensa-esp32-elf/include -isystem /home/esp32/crosstool-NG/.build/xtensa-esp32-elf/buildtools/xtensa-esp32-elf/sys-include    -c -mlongcalls -g -Os  conftest.c >&5
/tmp/ccaI0PfZ.s: Assembler messages:
/tmp/ccaI0PfZ.s:12: Error: operand 3 of 'entry' has invalid value '33'
configure:3686: $? = 1
configure: failed program was:
| /* confdefs.h */
| #define PACKAGE_NAME "GNU C Runtime Library"
| #define PACKAGE_TARNAME "libgcc"
| #define PACKAGE_VERSION "1.0"
| #define PACKAGE_STRING "GNU C Runtime Library 1.0"
| #define PACKAGE_BUGREPORT ""
| #define PACKAGE_URL "http://www.gnu.org/software/libgcc/"
| /* end confdefs.h.  */
|
| int
| main ()
| {
|
|   ;
|   return 0;
| }
configure:3700: error: in `/home/esp32/crosstool-NG/.build/xtensa-esp32-elf/build/build-cc-gcc-core-pass-2/xtensa-esp32-elf/libgcc':
configure:3703: error: cannot compute suffix of object files: cannot compile

I would really like to compile esp32 programms on this machine ... I hope somebody can help me!!

BR,
Josef

**Comment by DSysoletin** [comment]
Have same problem too!

**Comment by bhundven** [comment]
@jcmvbkbc Have you seen this issue before?

**Comment by jcmvbkbc** [comment]
Saw the same build failure at a different project. Here's the fix for it: https://github.com/crosstool-ng/crosstool-ng/commit/314aed56b3f1044086bcad61f0064a6fc39e9d0d

**Comment by bhundven** [comment]
Ah, so we probably just need to do a new release? @stilor

**Comment by jcmvbkbc** [comment]
> I'am using crosstool-NG version crosstool-ng-1.22.0-75-gbaf03c2,

More likely that branch (from esp-idf?) just needs that fix.

**Comment by stilor** [comment]
I want to make a new release after glibc 2.27 comes out in Feb. I was also waiting for gcc 7.3/8 release schedule; 7.3 came out today and 8 is not until April, I think.

Then again, I now have much less time to devote to ct-ng than I had a year ago.

**Comment by jcmvbkbc** [comment]
BTW, the fix for the above issue is in the gcc-5.5, so instead of backporting the fix maybe crosstool-ng-1.22.0-75-gbaf03c2 could be switched to use gcc-5.5

**Comment by stilor** [comment]
`master` already has gcc 5.5

**Comment by panarom** [comment]
Is there a workaround for this? I tried cherry-picking `314aed5` & I also tried a --recursive checkout and then switching crosstool-ng branches to `master`; but I still got the same error

**Comment by stilor** [comment]
master has the version with the fix, we don't have the manpower to maintain 1.22 unfortunately
