### ISSUE TITLE
arm64-v8a architectual level

### ISSUE THREAD

**Issue by pentahydrate** [crosstool-ng/crosstool-ng#891]
crosstool-NG version : crosstool-ng-1.23.0-288-gadaa3a5d
hostOS : Ubuntu Bionic Beaver (development branch) x86_64 
.config : https://hastebin.com/aruvozuxaz.ini
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1596249/build.log)

I am using experimental features and somehow i can't target arch level arm64-v8a.
```
[CFG  ]    For cortex-a53 real value is cortexa53
[CFG  ]    Unknown target in --with-arch=arm64-v8a
[CFG  ]    Makefile:4149: recipe for target 'configure-gcc' failed
[ERROR]    make[1]: *** [configure-gcc] Error 1
```

**Comment by krasCGQ** [comment]
You're trying to build arm64 (aarch64) toolchain, right?
Use `CT_ARCH_64` instead of `CT_ARCH_32`.

**Comment by alamo18** [comment]
I got the derp i sent on tg
```
/home/alamo18/Desktop/crosstool/lib/crosstool-ng-1.23.0/scripts/build/arch.sh: line 78: /home/alamo18/Desktop/crosstool/lib/crosstool-ng-1.23.0/scripts/build/arch/.sh: No such file or directory
```

**Comment by stilor** [comment]
Config expired. From the last response, I couldn't understand if it was a bug in the configuration or ct-ng bug. If this is still an issue, submit a new bug.
