### ISSUE TITLE
What is proper way to have "sizeof(long double) == 8" for x86_64-w64-mingw32 ?

### ISSUE THREAD

**Issue by vmurashev** [crosstool-ng/crosstool-ng#893]
My .config is generated by DEFCONFIG:
CT_EXPERIMENTAL=y
CT_CC_GCC_V_5_4_0=y
CT_CC_LANG_CXX=y
CT_ARCH_x86=y
CT_ARCH_64=y
CT_MULTILIB=y
CT_TARGET_VENDOR="w64"
CT_KERNEL_windows=y
CT_MINGW_DIRECTX=y
CT_MINGW_DDK=y
CT_MINGW_TOOLS=y
CT_THREADS_NATIVE=y
CT_STATIC_TOOLCHAIN=y

Toolchain produced by this config generates executables where: 
sizeof(long double) == 12 for 32bit windows binaries,
sizeof(long double) == 16 for 64bit windows binaries

My question - Is there any appropriate option which prescribes that x86_64-w64-mingw32 toolchain has to generate binaries where "sizeof(long double) == 8" ?

The only mention of it in ct-ng sources is 100-gcc.sh

    case "${CT_CC_GCC_LDBL_128}" in
        y)  extra_config+=("--with-long-double-128");;
        m)  ;;
        "") extra_config+=("--without-long-double-128");;
    esac

So I tried to add
CT_CC_GCC_LDBL_128=""
and then do DEFCONFIG but without success - while toolchain being built I got the warning:
warning: symbol value '""' invalid for CC_GCC_LDBL_128
and final toolchain still have option in config:
./x86_64-w64-mingw32-ct-ng.config | grep LDBL
CT_CC_GCC_LDBL_128=m

**Comment by vmurashev** [comment]
[build.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1605532/build.tar.gz)
[config.tar.gz](https://github.com/crosstool-ng/crosstool-ng/files/1605533/config.tar.gz)

**Comment by stilor** [comment]
In the config file, the empty value for a certain option is encoded in strings like `# CT_FOO is not set` (rather than setting it to empty string, which as you saw makes kconfig complain). Try that, or better yet, use `ct-ng menuconfig` to select the options unless you're familiar with kconfig file syntax.
