### ISSUE TITLE
build error  

### ISSUE THREAD

**Issue by jenGast** [crosstool-ng/crosstool-ng#898]
Hi!
I tried to build after configuring and it complains about a space in my path, and I got the error 'build failed in step '(top level)'. The error looks like this: 
CT_LOCAL_TARBALLS_DIR'='/home/jenny/src Downloads/Installs/crosstool-ng-1.23.0

There is a space in 'src Downloads', but how do I get around that, since the path is already laid at that level?

I have:
Oracle VirtualBox 5.1.32 
Ubuntu 16.04 
Linux Mint 18.3 
Cinnamon 64-bit
crosstool-ng-1.23.0

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1645707/build.log)

[config.log](https://github.com/crosstool-ng/crosstool-ng/files/1645708/config.log)
(couldn't find config.txt, hope this will do)

Best regards/Jenny

**Comment by stilor** [comment]
Start the build from a directory that does not contain a space.
