### ISSUE TITLE
macOS documentation suggestion - use APFS instead of a disk image.

### ISSUE THREAD

**Issue by John-Titor** [crosstool-ng/crosstool-ng#903]
For macOS 13 (High Sierra) and up, on systems using APFS, it is possible (and easier vs. adding another disk or disk image) to create a case-sensitive APFS volume that shares space with the system volume.

Detailed steps:
 - Open Disk Utility
 - Select the container that holds the system volume (usually "Container disk1")
 - Select the 'add volume' button in the toolbar
 - Give the volume a useful name and make sure to select 'APFS (case-sensitive)
 - Set the Prefix Directory (in menuconfig / nconfig) to /Volumes/<new volume name>.

**Comment by stilor** [comment]
It looks like building on APFS results in some sort of concurrency issue (see #906) and the jury is still out on whether this is APFS fault, or a defect in gcc makefile that's exposed by APFS. I'll add a note with a caveat.

**Comment by kozyilmaz** [comment]
There is known gcc compilation issue if underlying filesystem is APFS but I am not sure if that is the problem here. In any case you can find the adapted patch [here](https://github.com/kozyilmaz/tools/blob/master/gnugcc/patches/000-gcc-apfs-compile.patch)

**Comment by John-Titor** [comment]
No, actually just the opposite; my experience was that it was easier (and faster) to build using an APFS volume rather than making a disk image.

The GCC vs. APFS compilation issue is a GCC build system bug; my guess is that it's manifesting on APFS due to different timing vs. the usual filesystems, but I didn't hit it on my (low core count) test system...

**Comment by stilor** [comment]
At least in the upstream bug [1], they seem to have arrived to the opposite conclusion that this is APFS issue. Therefore, I shall abstain from recommending APFS.

[1] https://gcc.gnu.org/bugzilla/show_bug.cgi?id=81797
