### ISSUE TITLE
Issue on building a cross compiler

### ISSUE THREAD

**Issue by remyGrandry** [crosstool-ng/crosstool-ng#916]
Hello,

This is the first issue I open so I hope it will be in right from.
I had a problem on compiling cross compiler, we looked with a friend and it seems that is a bug of cross tool-ng.
I use version : crosstool-ng-1.23.0-317-g85b86d82.
I run it on macOS 10.13.3 (17D47).

My build.log here : https://mega.nz/#!uUhQlBTD!gc8Xv-pWUpaj6CQYiqVtBx7rvtuW-ZtMQVJ_f1S-Vtg

Sorry it is 29 Mo so I couldn't upload it here

Thanks and I hope it can help.

**Comment by stilor** [comment]
Are you using APFS by chance?

**Comment by stilor** [comment]
See #906 - APFS seems to have some issues with compiling complex projects. It is not clear yet whether it is a bug in APFS or GCC's makefiles, but until that is resolved, avoid APFS for building complex projects (or if you must, disable parallel make by running `ct-ng build.1` - but that would be much slower).

**Comment by stilor** [comment]
If there's anything substantial to add, let's discuss in the #906 issue.
