### ISSUE TITLE
reuse build-env for multiple toolchains?

### ISSUE THREAD

**Issue by tofutim** [crosstool-ng/crosstool-ng#918]
Hi, if I want to reuse my build-env for multiple toolchains is this possible or advisable? It seems many of the steps are setup for host. Just curious if it is advisable to skip steps when building for say armv6 and armv7 for rpi.

I see items like `gettext` for host, which seems like a one time thing regardless of toolchain...

**Update.** Just found
> 
> ct-ng build-all
> Note that it is very time consuming (depending on your machine configuration and host OS, it takes from 24 hours to a full week). **_By default_**, this removes each build tree after a successful build, but leaves the unpacked/patched sources so that they can be re-used by the samples that follow). However, even that consumes considerable amount of disk space given the variety of component versions represented in samples.

Is there an option to not keep building host tools that aren't toolchain specific?

Surely some of these can be reused across toolchains?

> Available build steps, in order:
>   - companion_tools_for_build
>   - companion_libs_for_build
>   - binutils_for_build
>   - companion_tools_for_host
>   - companion_libs_for_host
>   - binutils_for_host
>   - cc_core_pass_1
>   - kernel_headers
>   - libc_start_files
>   - cc_core_pass_2
>   - libc
>   - cc_for_build
>   - cc_for_host
>   - libc_post_cc
>   - companion_libs_for_target
>   - binutils_for_target
>   - debug
>   - test_suite
>   - finish

Though I guess the first set before cc_core_pass_1 doesn't really take that long... maybe 20 min?

**Comment by stilor** [comment]
Even though the same steps are done for host/for build, they may be configured with different `--target` settings. I don't think anything other than companion_tools/companion_libs, for both build and host, can be shared.

And even those may have different configurable settings.

Given that the build of companion tools/libs takes probably about 10% of the whole build time, I don't think the savings are worth the added complexity.

**Comment by tofutim** [comment]
Thank you for that excellent answer. I concur with your analysis.
