### ISSUE TITLE
Build failed at "Final GCC" stage

### ISSUE THREAD

**Issue by huming2207** [crosstool-ng/crosstool-ng#919]
Hi,

I've got an issue in the "building final GCC" stage when I building my cross compiler for android platform (using bionic as C library). Here's the log:

```
[ERROR]    ./md-unwind-support.h:94:21: error: 'struct sigcontext' has no member named 'regs'
[ERROR]    ./md-unwind-support.h:103:54: error: 'struct sigcontext' has no member named '__reserved'
[ERROR]    ./md-unwind-support.h:104:24: error: dereferencing pointer to incomplete type 'struct _aarch64_ctx'
[ERROR]    ./md-unwind-support.h:108:38: error: 'FPSIMD_MAGIC' undeclared (first use in this function)
[ERROR]    ./md-unwind-support.h:128:37: error: dereferencing pointer to incomplete type 'struct fpsimd_context'
[ERROR]    ./md-unwind-support.h:146:52: error: 'struct sigcontext' has no member named 'sp'
[ERROR]    ./md-unwind-support.h:153:22: error: 'struct sigcontext' has no member named 'pc'

```

Basically my configuration is:

- GCC Linaro 7.2 2017.11
- Bionic r16b
- Custom kernel header (linux 4.4.78)

The full log is attached below. Thanks for your help and your great works.
[issue.zip](https://github.com/crosstool-ng/crosstool-ng/files/1760722/issue.zip)

Regards,
Jackson

**Comment by huming2207** [comment]
Problem solved, just switch to official linux kernel header and it works.

**Comment by rupansh** [comment]
thanks vro
