### ISSUE TITLE
Does not compile g++?!

### ISSUE THREAD

**Issue by Zibri** [crosstool-ng/crosstool-ng#920]
I enabled c++ but it does not compile g++ why?
(probably is my mistake but I don't know which one)

$ ls arm-unknown-linux-gnueabi/buildtools/bin/
arm-unknown-linux-gnueabi-addr2line     arm-unknown-linux-gnueabi-ld       reset
arm-unknown-linux-gnueabi-ar            arm-unknown-linux-gnueabi-ld.bfd   tabs
arm-unknown-linux-gnueabi-as            arm-unknown-linux-gnueabi-nm       tic
arm-unknown-linux-gnueabi-cc            arm-unknown-linux-gnueabi-objcopy  toe
arm-unknown-linux-gnueabi-c++filt       arm-unknown-linux-gnueabi-objdump  tput
arm-unknown-linux-gnueabi-cpp           arm-unknown-linux-gnueabi-ranlib   tset
arm-unknown-linux-gnueabi-ct-ng.config  arm-unknown-linux-gnueabi-readelf  x86_64-build_pc-linux-gnu-ar
arm-unknown-linux-gnueabi-elfedit       arm-unknown-linux-gnueabi-size     x86_64-build_pc-linux-gnu-as
arm-unknown-linux-gnueabi-gcc           arm-unknown-linux-gnueabi-strings  x86_64-build_pc-linux-gnu-g++
arm-unknown-linux-gnueabi-gcc-5.4.1     arm-unknown-linux-gnueabi-strip    x86_64-build_pc-linux-gnu-gcc
arm-unknown-linux-gnueabi-gcc-ar        captoinfo                          x86_64-build_pc-linux-gnu-ld
arm-unknown-linux-gnueabi-gcc-nm        clear                              x86_64-build_pc-linux-gnu-nm
arm-unknown-linux-gnueabi-gcc-ranlib    infocmp                            x86_64-build_pc-linux-gnu-objcopy
arm-unknown-linux-gnueabi-gcov          infotocap                          x86_64-build_pc-linux-gnu-objdump
arm-unknown-linux-gnueabi-gcov-tool     makeinfo                           x86_64-build_pc-linux-gnu-ranlib
arm-unknown-linux-gnueabi-gprof         ncurses5-config                    x86_64-build_pc-linux-gnu-strip

**Comment by Zibri** [comment]
I selected GCC 4.9.4 in menuconfig with C++ flag
it creates cpp but not g++   what shall I do?

**Comment by stilor** [comment]
Works for me:
````
avn@mistral:~/work/ctng/crosstool-ng$ ll ~/x-tools/arm-unknown-linux-gnueabi/bin/
total 300608
dr-xr-xr-x 2 avn avn     4096 Apr 11 01:27 ./
dr-xr-xr-x 8 avn avn     4096 Apr 11 01:27 ../
-r-xr-xr-x 1 avn avn  5140304 Apr 11 00:06 arm-unknown-linux-gnueabi-addr2line*
-r-xr-xr-x 2 avn avn  5369056 Apr 11 00:06 arm-unknown-linux-gnueabi-ar*
-r-xr-xr-x 2 avn avn  8195456 Apr 11 00:06 arm-unknown-linux-gnueabi-as*
-r-xr-xr-x 2 avn avn  3196064 Apr 11 01:07 arm-unknown-linux-gnueabi-c++*
lrwxrwxrwx 1 avn avn       29 Apr 11 01:07 arm-unknown-linux-gnueabi-cc -> arm-unknown-linux-gnueabi-gcc*
-r-xr-xr-x 1 avn avn  5092704 Apr 11 00:06 arm-unknown-linux-gnueabi-c++filt*
-r-xr-xr-x 1 avn avn  3193872 Apr 11 01:07 arm-unknown-linux-gnueabi-cpp*
-r-xr-xr-x 1 avn avn     4981 Apr 10 23:48 arm-unknown-linux-gnueabi-ct-ng.config*
-r-xr-xr-x 1 avn avn 51915776 Apr 11 00:06 arm-unknown-linux-gnueabi-dwp*
-r-xr-xr-x 1 avn avn   250280 Apr 11 00:06 arm-unknown-linux-gnueabi-elfedit*
-r-xr-xr-x 2 avn avn  3196064 Apr 11 01:07 arm-unknown-linux-gnueabi-g++*
-r-xr-xr-x 2 avn avn  3186488 Apr 11 01:07 arm-unknown-linux-gnueabi-gcc*
-r-xr-xr-x 2 avn avn  3186488 Apr 11 01:07 arm-unknown-linux-gnueabi-gcc-4.9.4*
-r-xr-xr-x 1 avn avn   154912 Apr 11 01:07 arm-unknown-linux-gnueabi-gcc-ar*
-r-xr-xr-x 1 avn avn   154736 Apr 11 01:07 arm-unknown-linux-gnueabi-gcc-nm*
-r-xr-xr-x 1 avn avn   154752 Apr 11 01:07 arm-unknown-linux-gnueabi-gcc-ranlib*
-r-xr-xr-x 1 avn avn  2089896 Apr 11 01:07 arm-unknown-linux-gnueabi-gcov*
-r-xr-xr-x 1 avn avn 69980832 Apr 11 01:18 arm-unknown-linux-gnueabi-gdb*
-r-xr-xr-x 1 avn avn  5850952 Apr 11 00:06 arm-unknown-linux-gnueabi-gprof*
-r-xr-xr-x 1 avn avn      143 Apr 11 00:06 arm-unknown-linux-gnueabi-ld*
-r-xr-xr-x 2 avn avn  7024272 Apr 11 00:06 arm-unknown-linux-gnueabi-ld.bfd*
-r-xr-xr-x 1 avn avn    15075 Apr 11 01:27 arm-unknown-linux-gnueabi-ldd*
-r-xr-xr-x 2 avn avn 87558608 Apr 11 00:06 arm-unknown-linux-gnueabi-ld.gold*
-r-xr-xr-x 2 avn avn  5185712 Apr 11 00:06 arm-unknown-linux-gnueabi-nm*
-r-xr-xr-x 2 avn avn  6270064 Apr 11 00:06 arm-unknown-linux-gnueabi-objcopy*
-r-xr-xr-x 2 avn avn  7390464 Apr 11 00:06 arm-unknown-linux-gnueabi-objdump*
-r-xr-xr-x 1 avn avn    10448 Apr 11 01:27 arm-unknown-linux-gnueabi-populate*
-r-xr-xr-x 2 avn avn  5369080 Apr 11 00:06 arm-unknown-linux-gnueabi-ranlib*
-r-xr-xr-x 2 avn avn  2087008 Apr 11 00:06 arm-unknown-linux-gnueabi-readelf*
-r-xr-xr-x 1 avn avn  5128512 Apr 11 00:06 arm-unknown-linux-gnueabi-size*
-r-xr-xr-x 1 avn avn  5126136 Apr 11 00:06 arm-unknown-linux-gnueabi-strings*
-r-xr-xr-x 2 avn avn  6270056 Apr 11 00:06 arm-unknown-linux-gnueabi-strip*
````
No config, no host information. Closing.
