### ISSUE TITLE
ct-ng build fails: bad sha digest

### ISSUE THREAD

**Issue by Marco-vW** [crosstool-ng/crosstool-ng#927]
- Report crosstool-NG version: **1.23.0 (current)**
- Report host OS and its version: **Oracle VM running Debian 8.1 x86_64** (2Gb RAM/20 Gb diskspace assigned to Virtualbox)

I'm following the guide at https://www.schwabenlan.de/en/post/2016/02/upgrade-to-debian-jessie-on-mybook-live-nas/ but get stuck when running 

`ct-ng build`

It starts, but fails retrieving after receiving the first few tarballs, saying 'Bad sha digest for expat-2.2.5.tar.bz2','Digest verification failed; removing the download';'expat:  download failed'.

I'm unable to attach a log (don't know how to export it from the console-only virtualbox to my Windows desktop, but I've attached a screenshot showing the issue.

ct-ng build exits with '/usr/local/bin/ct-ng/:142: recipe for target 'build' has failed' (translated from dutch)

Your help is much appreciated!

![2018-03-02 08_31_16-debian 8 1 draaiend - oracle vm virtualbox](https://user-images.githubusercontent.com/22148344/36888860-a37bfcbc-1df7-11e8-9396-31311c486d06.png)

**Comment by cingers** [comment]
I get this error on version 1.22.0.

`gzip: /home/user/x-tools/.build/tarballs/expat-2.1.0.tar.gz: not in gzip format`

When I checked the the downloaded file with the `file` command I got this.

`../src/expat-2.1.0.tar.gz: HTML document, ASCII text`

Seems like it is not being downloaded correctly.

I worked around this issue by disabling a few debug facilities.

- duma
- gdb
- strace

**Comment by Marco-vW** [comment]
Thanks for your quick reply @cingers. How can I disable these debug facilities to work around it? Never worked with ct-ng before, so it's mostly abracadabra to me...

**Comment by cingers** [comment]
You should run `ct-ng menuconfig` and then enter the `Debug facilities` menu.

Under that menu you can disable duma, gdb, and strace by selecting them and pressing `n`.

After that you should be able to just run `ct-ng build` again

**Comment by Marco-vW** [comment]
That seems to have fixed it. Only gdb was active btw, which I unselected, save the new config, and ran ct-ng build again. Thanks for your assistance.

**Comment by cingers** [comment]
You're welcome :)

**Comment by cirosantilli** [comment]
For any Googlers, today I got an error:

```
[EXTRA]    Retrieving 'expat-2.2.6'
[ERROR]    expat: download failed
```

and `build.log` contained:

```
[DEBUG]    ==> Executing:  'wget' '--passive-ftp' '--tries=3' '-nc' '--progress=dot:binary' '-T' '10' '-O' '/home/ciro/bak/git/linux-kernel-module-cheat/out/crosstool-ng/build/default/build/tarballs/expat-2.2.6.tar.bz2.tmp-dl' 'http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2'
[ALL  ]    --2019-05-27 11:00:37--  http://downloads.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2
[ALL  ]    Resolving downloads.sourceforge.net (downloads.sourceforge.net)... 216.105.38.13
[ALL  ]    Connecting to downloads.sourceforge.net (downloads.sourceforge.net)|216.105.38.13|:80... connected.
[ALL  ]    HTTP request sent, awaiting response... 302 Found
[ALL  ]    Location: https://vorboss.dl.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2 [following]
[ALL  ]    --2019-05-27 11:00:38--  https://vorboss.dl.sourceforge.net/project/expat/expat/2.2.6/expat-2.2.6.tar.bz2
[ALL  ]    Resolving vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)... 5.10.152.194
[ALL  ]    Connecting to vorboss.dl.sourceforge.net (vorboss.dl.sourceforge.net)|5.10.152.194|:443... connected.
[ALL  ]    Unable to establish SSL connection.
```

But then I tried again after a few minutes and it worked, to it was just SourceForge being... SourceForge I guess.

**Comment by maartenjd** [comment]
Change http to https in line 221 of expat.in ~/crosstool-ng-1.24.0/config/versions. Is safer than disabling security mechanisms.

**Comment by skochinsky** [comment]
I've got the same error but the log showed eror 404. If you [go to sf.net](https://sourceforge.net/projects/expat/files/expat/2.2.6/) you'll see that 2.2.6 has been renamed, apparently because of some vulnerability. Replacing 2.2.6 with 2.3.0 in the config allowed the build to proceed.

**Comment by nyckmaia** [comment]
> Replacing 2.2.6 with 2.3.0 in the config allowed the build to proceed.

How can I replace it? could you help me?
I tried to modify the `expat.in`, but in ct-ng build tries to get the old 2.2.6 version yet.

**Comment by skochinsky** [comment]
I  think I edited CT_EXPAT_VERSION in the generated `.config` before building. maybe not the best solution but it worked for me
