### ISSUE TITLE
crosstool-ng-1.23.0.tar.bz2 is corrupt

### ISSUE THREAD

**Issue by ztalbot2000** [crosstool-ng/crosstool-ng#931]
The archive http://crosstool-ng.org/download/crosstool-ng/crosstool-ng-1.23.0.tar.bz2 is incorrect. The script 'function' is missing the method CT_Mirror while GitHub tag cross tool-ng-1.23.0 does.

Either this is not a release or just a bad archive

**Comment by stilor** [comment]
`CT_Mirror` appeared after the 1.23 release. The 1.23.0 tag does not have it.
