### ISSUE TITLE
Building failed in step 'Retrieving need toolchain components' tarballs

### ISSUE THREAD

**Issue by nguyenanhgiau** [crosstool-ng/crosstool-ng#932]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Building failed in step 'Retrieving need toolchain components' tarballs 
- crosstool-NG 1.23.0-391-gaca85cbb
- Ubuntu 17.10

**Comment by stilor** [comment]
1.9 is a very old release and not supported anymore.
