### ISSUE TITLE
ct-ng menuconfig fails, macos high sierra

### ISSUE THREAD

**Issue by mumme74** [crosstool-ng/crosstool-ng#934]
I can't get **_ct-ng menuconfig_** to work on current master.
 commit fd9fe523b22cb6281f26081232a3f8f3aee7fda1 and newer gives:
`  CONF  menuconfig
config/configure.in:48:warning: ignoring unsupported character '@'
config/configure.in:49:warning: ignoring unsupported character '@'
config/configure.in:50: syntax error
config/configure.in:49: unknown option "KCONFIG_install_with_strip_program"
make: *** [menuconfig] Error 1`

previous commit 59b08f8d06700770cf1105269acb2ec2460e2a34 works fine

host: macos High Sierra 10.13.3
[config.log](https://github.com/crosstool-ng/crosstool-ng/files/1858069/config.log)

**Comment by cpackham** [comment]
Did you re-run bootstrap before building? 1c329c33bf4 added KCONFIG_install_with_strip_program and it's possible if configure wasn't re-generated it wouldn't know to do the AC_SUBST. Either that or the macOS version of install doesn't support the --strip-program option and there's some problem in ACX_INSTALL_STRIP_PROGRAM.

**Comment by cpackham** [comment]
> Either that or the macOS version of install doesn't support the --strip-program option and there's some problem in ACX_INSTALL_STRIP_PROGRAM.

Actually I think that's exactly the problem. The no case of ACX_INSTALL_STRIP_PROGRAM doesn't set install_with_strip_program. I'll post a patch shortly

**Comment by cpackham** [comment]
I think it's the bootstrap thing. I can reproduce your failure with

    git clean -fxd
    sed -i '/^ACX_INSTALL_STRIP_PROGRAM/d' configure.ac
    ./bootstrap; ./configure --enable-local
    git checkout configure.ac
    ./configure --enable-local
    make
    ./ct-ng menuconfig

Running the following fixes the problem

    ./bootstrap
    ./configure --enable-local
    make
    ./ct-ng menuconfig

It's one of the annoying quirks of autotools that the dependency between configure.ac and configure isn't captured. Some people say that the solution is to store configure in version control, some people say that those first people are wrong.

**Comment by stilor** [comment]
It may be that we're using the autoconf but not automake. I am (slowly) working on automakization - hope I can finalize it and post a PR this weekend.

**Comment by mumme74** [comment]
>Running the following fixes the problem
```
./bootstrap
./configure --enable-local
make
./ct-ng menuconfig
```

Confirmed, It works for me too.

Thanks!
