### ISSUE TITLE
Error when build arm-unknown-linux- gnueabi

### ISSUE THREAD

**Issue by LewieYang** [crosstool-ng/crosstool-ng#936]
# crosstool-NG version : crosstool-ng-1.23.0
# Host OS : Debian 9.10.3-P4

# config file
.config similar as arm-unknown-linux- gnueabi configuration sample file

# Error info
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing binutils for host'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_binutils_backend[scripts/build/binutils/binutils.sh@226]
[ERROR]  >>        called from: do_binutils_for_host[scripts/build/binutils/binutils.sh@97]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]

When I install "binutils" as a nonprivileged user respectively ,  error still exist because i have limit on some files or folders;
# Error when make install (binutils)
make[1]: Entering directory '/opt/arm-linux-gcc/.build/src/binutils-2.28'
/bin/bash ./mkinstalldirs /usr/local /usr/local
make[2]: Entering directory '/opt/arm-linux-gcc/.build/src/binutils-2.28/bfd'
make  install-recursive
make[3]: Entering directory '/opt/arm-linux-gcc/.build/src/binutils-2.28/bfd'
Making install in doc
make[4]: Entering directory '/opt/arm-linux-gcc/.build/src/binutils-2.28/bfd/doc'
 /bin/mkdir -p '/usr/local/share/info'
 /usr/bin/install -c -m 644 ./bfd.info '/usr/local/share/info'
/usr/bin/install: cannot remove '/usr/local/share/info/bfd.info': Permission denied
Makefile:722: recipe for target 'install-info-am' failed
make[4]: *** [install-info-am] Error 1
make[4]: Leaving directory '/opt/arm-linux-gcc/.build/src/binutils-2.28/bfd/doc'
Makefile:1725: recipe for target 'install-recursive' failed
make[3]: *** [install-recursive] Error 1
make[3]: Leaving directory '/opt/arm-linux-gcc/.build/src/binutils-2.28/bfd'
Makefile:1862: recipe for target 'install' failed
make[2]: *** [install] Error 2
make[2]: Leaving directory '/opt/arm-linux-gcc/.build/src/binutils-2.28/bfd'
Makefile:2792: recipe for target 'install-bfd' failed
make[1]: *** [install-bfd] Error 2
make[1]: Leaving directory '/opt/arm-linux-gcc/.build/src/binutils-2.28'
Makefile:2255: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by stilor** [comment]
Well, configure the target directory where you have write permission, perhaps?
