### ISSUE TITLE
Compiling crosstool-ng on Arch Linux

### ISSUE THREAD

**Issue by xavloose** [crosstool-ng/crosstool-ng#942]
I was attempting to build the current development version against the latest arch libraries. I expect this affects all arch users.

crosstool-ng ./configure expects ncurses wide char support in an ncursesw directory but arch doesn't distribute ncurses with non wide char support headers at all.

current master:
bb9a11ae4fe44c22968941edb22264d6f0216dee
[configure.log](https://github.com/crosstool-ng/crosstool-ng/files/1910047/configure.log)

**Comment by stilor** [comment]
Yes, I just saw that too. I took the curses detection macros from autoconf-archive, assuming they would be more portable than I could write/test... apparently, not. Will try to fix this tomorrow.
