### ISSUE TITLE
Recipe for target 'menuconfig' failed - error running config menu from the terminal

### ISSUE THREAD

**Issue by andrewstockwell** [crosstool-ng/crosstool-ng#944]
I've followed the instructions to build crosstool-NG from source via cloning the repo:
```
git clone https://path.to.repo
sudo apt-get install autoconf and dependencies found [here](https://crosstool-ng.github.io/docs/os-setup/)
./bootstrap
./configure
make
sudo make install
```
the `ct-ng help`, `ct-ng version`, and `ct-ng list-steps` etc. commands work just fine, but the tool fails when trying to run `ct-ng menuconfig` and i get this error:

```
CONF  menuconfig
/bin/bash: /usr/local/libexec/crosstool-ng/mconf: No such file or directory
/usr/local/bin/ct-ng:107: recipe for target 'menuconfig' failed
make: *** [menuconfig] Error 127
```
I looked in the /usr/local/libexec/crosstool-ng/ directory and it's completely empty. For that reason, `ct-nconfig` also fails with a similar error message. I have not deleted the source directory although I should be able to because I make installed the tool. I tried the IRC channel and got no response.

crosstool-NG version: 1.23.0-360-g5472517
Host OS: Ubuntu (MATE flavor) 16.04.4 running as a VM inside VMware Workstation Player
Output of uname -a: 
Linux ubuntu 4.13.0-38-generic # 43~16.04.1-Ubuntu SMP Wed Mar 14 17:48:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by andrewstockwell** [comment]
Edit: I looked a little deeper through the issues in the repo and found #934 and #935. I'll use the temporary workaround for now and then reinstall when "automakization" is complete.

**Comment by stilor** [comment]
Please attach the log from `make install`. The same commands do install the conf/mconf/nconf into /usr/local/libexec/crosstool-ng on my system (ubuntu 17.10)

**Comment by stilor** [comment]
To underline, it works for me in the current state of automakization (which is pretty much complete by now and works on my machine, but I am now testing on various OSes).

**Comment by andrewstockwell** [comment]
The output is rather long so I've stuck it in pastebin: https://pastebin.com/GgzeyvBW

**Comment by andrewstockwell** [comment]
Also one other thing to note: `./bootstrap` did not generate the `configure` script until I installed `autoconf`, maybe that should be added as a dependency in the installation process

**Comment by andrewstockwell** [comment]
Libtool was not installed on my system it seems. I ran `which libtool` and it came up with nothing, so I just apt-get installed it.

AS for the autoconf thing, I wasn't aware of that, I'm just getting into this area (and out of college soon I hope) so I'm less familiar with the norms and standards of these more advanced tools

**Comment by andrewstockwell** [comment]
Going through the bootstrap/configure/make/make install process with libtool installed hasn't stopped the error, here's the new output if you're interested: https://pastebin.com/D2JuEK1X

**Comment by andrewstockwell** [comment]
I just tried starting from a new repo clone and noticed an error in `make`: https://pastebin.com/2gUkVkUd

```
tag CC  --mode=link gcc  -g -O2   -o mconf mconf.o zconf.o lxdialog/checklist.o lxdialog/inputbox.o lxdialog/menubox.o lxdialog/textbox.o lxdialog/util.o lxdialog/yesno.o -lncurses 
/bin/bash: tag: command not found
Makefile:519: recipe for target 'mconf' failed
make[3]: [mconf] Error 127 (ignored)
```

**Comment by stilor** [comment]
It still doesn't invoke libtool.

What does `configure` print when detecting libtool? It should be something like:
````
checking for libtool... /usr/bin/libtool
checking for GNU libtool >= 2.4... yes
````

Also check what `LIBTOOL` is defined to in `kconfig/Makefile` after you run configure. It should be set to `/usr/bin/libtool`.

**Comment by cdgraff** [comment]
I got the same issue, and the fix was install: 
`apt install libtool-bin `

I has previously installed only "libtool" package not the BIN.

After this all works well!

**Comment by andrewstockwell** [comment]
As soon as I installed libtool-bin everything worked great and it detected it! So it's all fixed.

**Comment by stilor** [comment]
Should be fixed now - configure will fail if it doesn't find libtool.
