### ISSUE TITLE
Picking up packages from VCS

### ISSUE THREAD

**Issue by antmak** [crosstool-ng/crosstool-ng#950]
crosstool-NG, master branch, host Linux

Could you tell me, how to use own git repos for packages like newlib or gcc? I noticed the mention of it (http://crosstool-ng.github.io/2017/07/04/packages.html , `git grep _git`) but I cannot found how to do that. I don't have corresponds items in `./ct-ng menuconfig` (such as 'Vendor/custom repository'). What do I need to switch on?

**Comment by stilor** [comment]
Enable 'EXPERIMENTAL' in 'Paths & misc options'. Then in each package, you should have 'Source of PACKAGE', with default being a release tarball - but there's also a 'Vendor/custom repository'. I think you'll figure it out from there :)
