### ISSUE TITLE
Hi  i am facing the below issue ..relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC

### ISSUE THREAD

**Issue by nandhu875** [crosstool-ng/crosstool-ng#955]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
- Report host OS and its version
- Attach `.config` (unless the issue is not related to any configuration)
- Attach `build.log` (unless crosstool-NG fails before the build starts)

**Comment by stilor** [comment]
For starters, try using -fPIC as the error message suggests.

No config, no build log. Closing.
