### ISSUE TITLE
Build fails for arm-cortex_a8-linux-gnueabi pass-1 core C gcc compiler

### ISSUE THREAD

**Issue by JohnBabrick** [crosstool-ng/crosstool-ng#957]
I am trying to build the toolchain from git cloned 1.23.0 for arm-cortex_a8-linux-gnueabi on the Ubuntu 18.04 host. It fails trying to compile the gcc compiler. 

[INFO ]  Installing pass-1 core C gcc compiler
[EXTRA]    Configuring core C gcc compiler
[EXTRA]    Building gcc
[ERROR]    /home/johann/toolchain/crosstool-ng/.build/src/gcc-6.3.0/gcc/ubsan.c:1474:23: error: ISO C++ forbids comparison between pointer and integer [-fpermissive]
[ERROR]    make[3]: *** [ubsan.o] Error 1
[ERROR]    make[2]: *** [all-gcc] Error 2
[ERROR]   
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Installing pass-1 core C gcc compiler'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@338]
[ERROR]  >>        called from: do_gcc_core_backend[scripts/build/cc/100-gcc.sh@674]
[ERROR]  >>        called from: do_gcc_core_pass_1[scripts/build/cc/100-gcc.sh@227]
[ERROR]  >>        called from: do_cc_core_pass_1[scripts/build/cc.sh@35]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@653]
[ERROR]  >>

Attached are the files you requested in a zip:

[build-fails-gcc-pass-one.zip](https://github.com/crosstool-ng/crosstool-ng/files/1977767/build-fails-gcc-pass-one.zip)

And thanks in advance for your help and for making this tool.

**Comment by stilor** [comment]
This is fixed upstream in GCC 6.4.0; try using master.

**Comment by stilor** [comment]
I mean `master` in crosstool-NG, which has GCC 6.4.0

**Comment by JohnBabrick** [comment]
OK, I now get errors when I try to make after the ./configure step, it didn't do this before. Here is the terminal output, would you take a look?

[terminal.txt.zip](https://github.com/crosstool-ng/crosstool-ng/files/1977821/terminal.txt.zip)
