### ISSUE TITLE
error: macro expands to multiple statements when build samples/i686-ubuntu16.04-linux-gnu

### ISSUE THREAD

**Issue by SeanCode** [crosstool-ng/crosstool-ng#961]
there is a issue when build samples/i686-ubuntu16.04-linux-gnu
- crosstool-NG: version 1.23.0-385-g7d3d4d9e
- host OS and its version: x86_64-apple-darwin17.4.0

INFO ]  =================================================================
[INFO ]  Installing C library
[INFO ]    =================================================================
[INFO ]    Building for multilib 1/1: ''
[EXTRA]      Cleaning up start files
[EXTRA]      Configuring C library
[EXTRA]      Building C library
[ERROR]      strftime_l.c:719:4: error: macro expands to multiple statements [-Werror=multistatement-macros]
[ERROR]      make[3]: *** [../o-iterator.mk:9: /Volumes/crosstool-ng/.build/i686-ubuntu16.04-linux-gnu/build/build-libc-final/multilib/time/strftime_l.o] Error 1
[ERROR]      make[2]: *** [Makefile:214: time/subdir_lib] Error 2
[ERROR]      make[1]: *** [Makefile:9: all] Error 2
[ERROR]
[ERROR]  >>
[ERROR]  >>  Build failed in step 'Building for multilib 1/1: '''
[ERROR]  >>        called in step 'Installing C library'
[ERROR]  >>        called in step '(top-level)'
[ERROR]  >>
[ERROR]  >>  Error happened in: CT_DoExecLog[scripts/functions@373]
[ERROR]  >>        called from: do_libc_backend_once[scripts/build/libc/glibc.sh@380]
[ERROR]  >>        called from: CT_IterateMultilibs[scripts/functions@1498]
[ERROR]  >>        called from: do_libc_backend[scripts/build/libc/glibc.sh@74]
[ERROR]  >>        called from: do_libc[scripts/build/libc/glibc.sh@41]
[ERROR]  >>        called from: main[scripts/crosstool-NG.sh@679]
[ERROR]  >>
[ERROR]  >>  For more info on this error, look at the file: 'build.log'
[ERROR]  >>  There is a list of known issues, some with workarounds, in:
[ERROR]  >>      https://crosstool-ng.github.io/docs/known-issues/
[ERROR]  >>
[ERROR]  >>  If you feel this is a bug in crosstool-NG, report it at:
[ERROR]  >>      https://github.com/crosstool-ng/crosstool-ng/issues/
[ERROR]  >>
[ERROR]  >>  Make sure your report includes all the information pertinent to this issue.
[ERROR]  >>  Read the bug reporting guidelines here:
[ERROR]  >>      http://crosstool-ng.github.io/support/
[ERROR]
[ERROR]  (elapsed: 46:26.00)
[46:27] / gmake: *** [/Volumes/crosstool-ng/bin/ct-ng:232: build] Error 2

here are .config file and build.log
[.config](https://github.com/crosstool-ng/crosstool-ng/files/1986347/i686-ubuntu16.04-linux-gnu.config.txt)

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/1986357/build.log.txt)

**Comment by stilor** [comment]
Should be fixed now. Unfortunately, it is not the only error during glibc build with GCC8, and some of them are not trivial to backport to older releases. I just disabled `-Werror` when building glibc releases older than 2.27 with GCC8.
