### ISSUE TITLE
"Installing make for build" fails with host glibc2.27

### ISSUE THREAD

**Issue by Salamandar** [crosstool-ng/crosstool-ng#965]
This is a known issue for Make, the new glibc2.27 breaks the Make build.

The best way to fix it is to apply to Make sources two small patches from upstream. Everything is noted here : 
https://www.linuxquestions.org/questions/slackware-14/strange-behavior-with-rebuilt-make-for-glibc-2-27-a-4175623857/#post5820795

**Comment by stilor** [comment]
Fixed by #1038
