### ISSUE TITLE
Solution: infinite recursion during the make step in older CT-NG versions

### ISSUE THREAD

**Issue by MIPSCT39** [crosstool-ng/crosstool-ng#972]
On newer Linux distributions and older versions of crosstool-NG, you might run into an infinite recursion during the _make_ step.
Example error:
> Makefile:115: *** Recursion detected, bailing out....  Stop.
> Makefile:120: recipe for target 'build' failed
> make: *** [build] Error 2
(Even older versions simply step into the recursion and hang your machine.)

To solve this, replace the section that starts with "# Use neither builtin rules, nor builtin variables" in the file Makefile.in with the following:
```
# Use neither builtin rules, nor builtin variables
# Note: dual test, because if -R and -r are given on the command line
# (who knows?), MAKEFLAGS contains 'Rr' instead of '-Rr', while adding
# '-Rr' to MAKEFLAGS adds it literaly ( and does not add 'Rr' )
# Further: quad test because the flags 'rR' and '-rR' can be reordered.
ifeq ($(filter Rr,$(MAKEFLAGS)),)
ifeq ($(filter -Rr,$(MAKEFLAGS)),)
ifeq ($(filter rR,$(MAKEFLAGS)),)
ifeq ($(filter -rR,$(MAKEFLAGS)),)
CT_MAKEFLAGS += -Rr
endif # No -rR
endif # No rR
endif # No -Rr
endif # No Rr
```
Afterwards, rerun the _configure_ step.

**Comment by stilor** [comment]
Thanks for describing the workaround. But these older versions are not maintained anymore (heck, I don't have enough time to even maintain the latest release).
