### ISSUE TITLE
Build failed in step 'Installing automake for build'

### ISSUE THREAD

**Issue by DatTurban** [crosstool-ng/crosstool-ng#973]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:
- Report crosstool-NG version
Relased 1.23.0 http://crosstool-ng.github.io/2017/04/19/release-1.23.0.html
- Report host OS and its version
Xubuntu 18.04, uname -a returns this: Linux DragonEnergy 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Attach `.config` (unless the issue is not related to any configuration)
[confignothidden.txt](https://github.com/crosstool-ng/crosstool-ng/files/2018799/confignothidden.txt)
- Attach `build.log` (unless crosstool-NG fails before the build starts)
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2018795/build.log)

I am trying to compile C code on my x86 laptop that I can port to my raspberry pi zero w

**Comment by nitkul** [comment]
Hi,
I'm facing issues with on ct-ng v1.9.3 with my OS as Mint 18.1
This is for 'arm-cortex_a8-linux-gnueabi'
When I run the './ct-ng build' command, it fails:
`
[INFO ]  Performing some trivial sanity checks
[INFO ]  Build started 20180627.171656
[INFO ]  Building environment variables
[EXTRA]  Preparing working directories
[EXTRA]  Installing user-supplied crosstool-NG configuration
[EXTRA]  =================================================================
[EXTRA]  Dumping internal crosstool-NG configuration
[EXTRA]    Building a toolchain for:
[EXTRA]      build  = x86_64-unknown-linux-gnu
[EXTRA]      host   = x86_64-unknown-linux-gnu
[EXTRA]      target = arm-cortex_a8-linux-gnueabi
[EXTRA]  Dumping internal crosstool-NG configuration: done in 0.07s (at 00:01)
[INFO ]  =================================================================
[INFO ]  Retrieving needed toolchain components' tarballs
[EXTRA]    Retrieving 'gmp-4.3.2'
[EXTRA]    Saving 'gmp-4.3.2.tar.bz2' to local storage
[EXTRA]    Retrieving 'mpfr-2.4.2'
[EXTRA]    Saving 'mpfr-2.4.2.tar.bz2' to local storage
[EXTRA]    Retrieving 'ppl-0.10.2'
[EXTRA]    Saving 'ppl-0.10.2.tar.bz2' to local storage
[EXTRA]    Retrieving 'cloog-ppl-0.15.9'
[ERROR]    Could not retrieve 'cloog-ppl-0.15.9'.
[02:32] / ct-ng:143: recipe for target 'build' failed
make: *** [build] Error 1
`
I checked the log, and realized that the web URLs for downloading many of the tarballs are outdated. How to overcome this problem? TIA.
[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2141125/build.log)

**Comment by stilor** [comment]
1.9.3 is ancient and not supported.
