### ISSUE TITLE
Fails at extracting binutils

### ISSUE THREAD

**Issue by newclem** [crosstool-ng/crosstool-ng#975]
- crosstool-NG version: 1.23.0
- host OS: Linux ghost 4.16.10-1-ARCH #1 SMP PREEMPT Mon May 21 07:57:23 UTC 2018 x86_64 GNU/Linux
- Config file used for building : [configfile.txt](https://github.com/crosstool-ng/crosstool-ng/files/2039573/configfile.txt)
- Log file of the building: [build.log](https://github.com/crosstool-ng/crosstool-ng/files/2039548/build.log)

The error appears when crosstool-ng tries to extract binutils. I tried with binutils 2.28 and 2.27 but I always have the same issue.

**Comment by MIPSCT39** [comment]
Remove the binutils tarball from the sources directory and try again.
Perhaps download the tarball manually from https://ftp.gnu.org/gnu/binutils/ and put it in your sources directory.

**Comment by newclem** [comment]
It works again perfectly. I don't know what changed, but now everything is fine !
