### ISSUE TITLE
bootstrap invoke can generate a series of git-based warnings

### ISSUE THREAD

**Issue by jdknight** [crosstool-ng/crosstool-ng#976]
When invoking `./bootstrap` with sources outside of a Git repository, a series of Git-based errors can output:
```
$ ./bootstrap 
Running autoconf...
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Done. You may now run:
    ./configure
```
Observed using the v1.23.0 package and using sources from ab3c204aee88f08481f1f63825d0e94b082ef84e.

Can be reproduced with the following steps (Arch Linux 4.16.11-1-ARCH; git 2.17.0):
```
cd /tmp/ctng/
wget https://github.com/crosstool-ng/crosstool-ng/archive/crosstool-ng-1.23.0.tar.gz
tar -vxf crosstool-ng-1.23.0.tar.gz
cd crosstool-ng-crosstool-ng-1.23.0/
./bootstrap
```
This is a result from changes introduced in 0e45cdf62422fbcc69c10d4287c7f8a2f96c149d. Unfortunately, I don't have a recommendation to address this at this time.

**Comment by jdknight** [comment]
@cpackham, from what I see now in the documentation (and based on what you have just mentioned) is that the `./bootstrap` script appears to be only needed when using a development version.

I used the released tarball as a quick way to easily show the issue, but it is not the original scenario which made me want to spawn this issue. I am currently using a series of scripts to invoke stages on a crosstool-ng package (fetching, extracting, configuring, etc.). The framework currently being used will clone crosstool-ng into an area where the Git directory and working tree directory are separated/controlled. For example:

```
./workdir/cache/crosstool-ng/<git-dir>
./workdir/output/build/crosstool-ng-ab3c204aee88f08481f1f63825d0e94b082ef84e/<work-dir>
```

When the configuration stage is reached, the autoconf will not have a Git directory to query (or worse, could use an independent parent Git tree to get a version value). While this specific example may be a corner case, I would imagine anyone pulling a development-version archive from GitHub (from a hash) would experience the same issue when needing to invoke `./bootstrap`.

From my limited knowledge on this package, I would lean towards your suggestion in excluding the `./bootstrap` script from an official release tarball. That being said, I would love to see another option which could allow the bootstrapping request to accept a forced version value (if that's even possible).

**Comment by jdknight** [comment]
Applying the `git-version-gen` patch (cpackham/git-patch@e1bbca2) gets me closer to overriding the version value. If I have a configuration stage with the following:

```
echo "<detected-version>" >.tarball-version
./bootstrap
```

I'm able to pass the expected crosstool-ng version in my "git-dir-detached" environment. Only two comments related to this:

 1. Might be nicer to use the name `.package-version` instead of `.tarball-version` for a more generic name.
 2. When the script parses the version file, it requires to be leading with a numerical value or the "is missing or damaged" message is shown. I'm not sure that all scenarios an invoke of `git describe ...` will result in a leading numerical value (if a forced version value is interpreted from a previous `git describe ...` call).

**Comment by stilor** [comment]
Thanks guys, I don't have time for ct-ng until after the next weekend. I hope I can get to integrating all that afterwards.

**Comment by stilor** [comment]
The patch needs a bit of adjustment. Our tags don't start with `v`, so one needs to pass `--prefix crosstool-ng-` when invoking it in configure.ac. Also, I decided to forgo the `.version` altogether; the time savings are negligible in a checked out copy, so there is no point in risking a stale version info in some bugreports.

It also uncovered a few other missing things needed for one to be able to run bootstrap from a distribution tarball.

**Comment by stilor** [comment]
#981 should be fixing it.
