### ISSUE TITLE
ncurses does not compile with 5.1

### ISSUE THREAD

**Issue by kybu** [crosstool-ng/crosstool-ng#98]
Hi,

let me first thank you for this tool, it saved me a lot of time building my own toolchain. Good work!

I was building my custom toolchain for armv5te and I was able to do that using gcc 4.9.2. Out of curiosity, I tried to create the toolchain with gcc 5.1.0 but the build failed.

In particular, ncurses does not compile with the most recent gcc. There is already a patch for it at: http://git.sagemath.org/sage.git/commit/?id=2201c9cedee5a935dae2c24fdc54a5aa09201bda
It seems like a preprocessor needs additional parameter on command-line '-P'.

Thanks,
  Peter

**Comment by bhundven** [comment]
Hah, I was just talking about this on irc yesterday.
http://crosstool-ng.org/download/ibot-logs/2015-05-28.html#quick-22:57:11

Thanks for opening this bug!

**Comment by bhundven** [comment]
Try this branch and confirm the fix:
https://github.com/bhundven/crosstool-ng/tree/ncurses_gcc5_fix

**Comment by kybu** [comment]
It compiles, thanks for a quick fix.
