### ISSUE TITLE
IBM1399 missing in Mac build

### ISSUE THREAD

**Issue by jimschm** [crosstool-ng/crosstool-ng#982]
Am trying to build x86_64-unknown-linux-gnu. After 45 minutes into the build, I hit a build error - no rule to build IBM1399.sh.

I presume I need to do something else to my configuration, but can't find any detail.

CrossToolNG - 83582f4f
MacBook Pro High Sierra 10.13.4
[build copy.log](https://github.com/crosstool-ng/crosstool-ng/files/2081238/build.copy.log)
[config.txt](https://github.com/crosstool-ng/crosstool-ng/files/2081247/config.txt)

**Comment by stilor** [comment]
Hard to say since you deleted most of the log. But looks like ulimit issue; read the docs.

**Comment by jimschm** [comment]
Outside docs recommended 8G for case sensitive fs on the mac. It had some space left but not much. Trying again with 30G.

Sorry for creating the issue. I see now the right forum is crossgcc list.

________________________________

**Comment by stilor** [comment]
ulimit issue on macos x is that the max number of file descriptors is too low. again, read the docs:
http://crosstool-ng.github.io/docs/os-setup/
