### ISSUE TITLE
when will the support for GCC 7.3/8 that supports RETPOLINE added

### ISSUE THREAD

**Issue by KTalinki** [crosstool-ng/crosstool-ng#991]
Thank you in advance.

What is the plan for adding support for GCC 7.3/8 that supports RETPOLINE( -mindirect-branch=thunk-extern) ??

**Comment by stilor** [comment]
On master already.

**Comment by KTalinki** [comment]
Can you please elaborate on "On master already."
how can I get access to Crosstool-NG that supports GCC 7.3/8 that supports RETPOLINE( -mindirect-branch=thunk-extern ?
Help is appreciated !!
--Kumar

**Comment by stilor** [comment]
It means GCC7.3 and 8 are on master branch. To get them you need to check out crosstool-NG from its git repository (there is no release yet that contains these changes).

**Comment by KTalinki** [comment]
Any plans of including those in Crosstool-NG release in the near future?

**Comment by stilor** [comment]
As soon as I have enough time to catch up on pending issues, do a test run on supported build machines (and it passes), I'd roll out the release.
