### ISSUE TITLE
iconvdata/IBM1390.so - no rule to make target [MacOs]

### ISSUE THREAD

**Issue by SirFerdek** [crosstool-ng/crosstool-ng#996]
`No rule to make target /Users/xxx/casesafe/buildroot/crosstool-ng/.build/x86_64-unknown-linux-gnu/build/build-libc-final/multilib/iconvdata/IBM1390.so needed by others.  Stop.
`

This error comes up after having pass-2 core C compiler done. What can be wrong? Please tell me what more information can I provide. I have necessary GNU tools installed via homebrew, visible in PATH.
- crosstool-NG version 1.23.0.418-d590
- host OS: MacOS 10.13.5 (17F77)
[build.log.zip](https://github.com/crosstool-ng/crosstool-ng/files/2157059/build.log.zip)
[.config](https://github.com/crosstool-ng/crosstool-ng/files/2157062/dotconfig.txt)

**Comment by stilor** [comment]
Try doing `ulimit -n 1024` before the build. It is a long-standing issue on MacOS X that, as I just found, I never documented.

**Comment by stilor** [comment]
http://crosstool-ng.github.io/docs/os-setup/
Documented now.

**Comment by SirFerdek** [comment]
Thanks! That worked. I wonder now how many other issues I had due to this setting...
