### ISSUE TITLE
macOS: WARNING: 'automake-1.15' is missing on your system.

### ISSUE THREAD

**Issue by petemoore** [crosstool-ng/crosstool-ng#997]
### Issue submission guidelines
See [detaled guidelines](http://crosstool-ng.github.io/support/). In short:

- Report crosstool-NG version

```
$ ct-ng version
This is crosstool-NG version crosstool-ng-1.23.0

Copyright (C) 2008  Yann E. MORIN <yann.morin.1998@free.fr>
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.
```

- Report host OS and its version

```
$ uname -a
Darwin Petes-iMac.local 17.6.0 Darwin Kernel Version 17.6.0: Tue May  8 15:22:16 PDT 2018; root:xnu-4570.61.1~1/RELEASE_X86_64 x86_64
$ brew list --versions
adns 1.5.1
allegro 5.2.1.1_1 5.2.2 5.2.1.1 5.2.4.0
android-platform-tools 25.0.3 24
arm-none-eabi 4.8.3-cs170e
audiofile 0.3.6_1
autoconf 2.69
autoconf213 2.13
automake 1.15 1.16.1
bash 4.4.23
bazaar 2.7.0 2.6.0_2 2.7.0_1
binutils 2.28 2.30
cmake 3.3.1 3.11.4 3.6.2 3.7.2 3.5.1 3.6.1
coreutils 8.27 8.30 8.25
curl 7.50.3 7.60.0 7.50.1 7.53.1
cvs 1.12.13_1 1.12.13
dep 0.4.1_1 0.3.2
dirmngr 1.1.1_3 1.1.1_2
flac 1.3.2_1 1.3.1 1.3.2
freetype 2.9.1 2.7.1 2.7 2.6.5
fuse-emulator 1.5.5 1.3.4
gawk 4.2.1
gdbm 1.12 1.16 1.11
gettext 0.19.8.1
git 2.5.2 2.12.0 2.18.0 2.9.3 2.10.2 2.8.0
glib 2.52.2 2.56.1
gmp 6.1.2 6.1.2_1 6.1.1 6.1.2_2
gnu-getopt 1.1.6
gnu-sed 4.5
gnu-tar 1.30 1.29_1 1.29 1.28
gnupg 1.4.20 1.4.21 1.4.19 2.0.30_3 2.2.8 2.0.30_2
gnutls 3.4.14 3.5.12_2 3.4.16 3.5.17 3.5.10 3.5.18
go 1.7 1.6 1.8 1.10.3 1.5.1 1.9.2 1.7.3 1.10 1.4.2
go-swagger 0.5.0 0.7.3 0.8.0 0.14.0
gpg-agent 2.0.31 2.0.30_1
help2man 1.47.6
icu4c 58.2 62.1
jpeg 9c 8d
jq 1.5_2 1.5_3 1.5_1
libassuan 2.4.3_1 2.5.1
libelf 0.8.13_1
libffi 3.0.13 3.2.1
libgcrypt 1.7.6 1.7.7 1.8.3 1.7.2 1.7.3
libgpg-error 1.31 1.23 1.24 1.27
libidn2 2.0.5
libksba 1.3.4_1 1.3.5
libogg 1.3.3 1.3.2
libpng 1.6.31 1.6.25 1.6.24 1.6.34 1.6.28 1.6.29
libspectrum 1.3.2 1.4.4
libssh2 1.8.0
libtasn1 4.12 4.13 4.8 4.9 4.10
libtool 2.4.6_1
libunistring 0.9.7 0.9.8 0.9.10
libusb 1.0.21 1.0.20 1.0.22
libusb-compat 0.1.5_1 0.1.5
libvorbis 1.3.6 1.3.5
libxmlsec1 1.2.20_1 1.2.26
libyaml 0.1.6_1 0.1.7 0.2.1
lua 5.2.4_3 5.2.4_4 5.3.4_4 5.2.4_1
makedepend 1.0.5
md5sha1sum 0.9.5
mercurial 3.9_1 3.4.1 4.1.1 3.7.3 3.9.2 3.5.1 4.6.1
mpfr 4.0.1
mysql 5.6.26 5.7.17 5.7.11 5.7.16 8.0.11 5.7.14
ncurses 6.1
nettle 3.3 3.4 3.2
node 5.9.1 10.5.0_1 7.0.0 6.4.0 7.7.2 0.12.7_1 8.1.4 0.12.4
npth 1.5
oath-toolkit 2.6.2 2.6.1
oniguruma 6.1.3 6.1.1_1 6.0.0 6.8.2
openssl 1.0.2g 1.0.2a-1 1.0.2h_1 1.0.2k 1.0.2l 1.0.2o_2 1.0.2j 1.0.2d_1
opus 1.1.3 1.1.4 1.2.1
opusfile 0.10 0.8
p11-kit 0.23.7 0.23.9 0.23.12 0.23.5
p7zip 16.02_1 15.09 9.20.1 16.02
pass 1.7.1 1.7.2
pcre 8.42 8.38 8.39 8.40
perl 5.28.0
physfs 3.0.1 2.0.3
pinentry 0.9.7 1.0.0 1.1.0_1
pixman 0.34.0 0.34.0_1
pkg-config 0.29.1 0.29.1_1 0.29.2 0.29.1_2 0.28
postgresql 9.6.3 10.4
pth 2.0.7
python 2.7.11 3.7.0 3.5.2_1 2.7.10_2 3.6.5_1 3.4.3_2 2.7.13 2.7.12 3.5.0 3.6.0_1 3.5.2_3 3.5.1 2.7.12_2
python@2 2.7.15_1
qemu 2.9.0 2.12.0
qrencode 4.0.2 3.4.4
rbenv 1.0.0 0.4.0 1.1.0 1.1.1
readline 6.3.8 7.0 7.0.3 7.0.3_1
redis 4.0.1 4.0.10
ruby 2.3.1 2.3.0 2.2.2 2.4.0 2.2.3 2.3.1_2 2.5.1
ruby-build 20170201 20180618 20160913 20150803 20160602 20150818 20160228
rust 1.26.2 1.27.0
sdl 1.2.15
sphinx-doc 1.7.5_1 1.5.1 1.4.5
sqlite 3.14.1 3.11.0_1 3.17.0 3.8.11.1 3.15.0 3.24.0
task 2.5.1
theora 1.1.1
tree 1.7.0
vim 8.1.0100_2 8.0.0055 7.4.865 7.4.2235 7.4.1655 8.0.0433
watchman 4.7.0 4.9.0 4.4.0 4.6.0
webp 1.0.0
wget 1.19.5 1.19.1 1.18
xz 5.2.2 5.2.4 5.2.3 5.2.1
yarn 1.7.0 0.27.5
yasm 1.3.0 1.3.0_1
$ brew cask list
$ 
```

- Attach `.config` (unless the issue is not related to any configuration)

[.config](https://github.com/crosstool-ng/crosstool-ng/files/2162807/dotconfig.txt)

- Attach `build.log` (unless crosstool-NG fails before the build starts)

[build.log](https://github.com/crosstool-ng/crosstool-ng/files/2162750/build.log)

Many thanks!

**Comment by tosone** [comment]
This is a normal bug about macos and ct-ng 1.23.0. I have no idea what to do. See here #770, hope useful.

But no more newest version, so sad.

**Comment by petemoore** [comment]
Thanks @tosone 

I took a look at [travis](https://travis-ci.org/crosstool-ng/crosstool-ng/builds) saw that the CI is not really actively maintained. I suspect having a comprehensive CI across macOS/Linux/Windows would really help to discover these types of issues at the moment they get introduced, although of course is quite a lot of effort to set up, especially if working across multiple release versions of each platform. However, I think it could be a wise investment.

**Comment by roolebo** [comment]
@petemoore Do you see the issue on master branch?

**Comment by stilor** [comment]
@petemoore The issue with Travis CI is that it is no longer suitable for this project: the time constraints on the tasks they introduced some time ago are insufficient to build most configurations - especially with the CPU sharing that comes with executing in a VM environment.

See #999 - or wait, you submitted that issue, so you know all that already.

**Comment by stilor** [comment]
It should be less of an issue on master indeed, now that crosstool-NG updates the timestamps after patching configure & friends.

Anyway, macOS is no longer supported unless somebody steps up and starts maintaining crosstool-NG on macOS.

**Comment by roolebo** [comment]
@stilor please don’t drop macOS support 👏🏻 if you keep macOS in mind it’ll be just fine. Meanwhile, until 1.24 is released I added a way to install crosstool-ng from master branch on macOS:
brew install crosstool-ng --HEAD

Indeed I was able to cross compile Linux kernel on macOS (though I had to build elfutils first) and mock some host headers.

**Comment by stilor** [comment]
I am not explicitly removing the support; I am just declaring that I am unable to test/investigate any issues reported on macOS - so either an issue is filed along with a PR to fix it, or it just gets closed.

**Comment by roolebo** [comment]
@stilor Thank you! If macOS-related issues come, could you please tag them with "help needed" "macos"? That'll let drive-by contributors who're interested in macOS support to take the issues over.

And I wonder are there any particular plans to release 1.24?

**Comment by stilor** [comment]
Re macOS issues: I will, but unfortunately github doesn't have very good UI for the issues database - unless help actually comes, these issues are going to be lingering at the top of the list of all the issues - not very convenient when you're looking for the next issue to tackle.

Re 1.24 - I tried to pick some low-hanging fruit from the issues over the weekend and just finished triaging the rest. This whittled it down to 8 issues and 2 PRs I wanted to pick up for 1.24.
