### ISSUE TITLE
CI is horribly broken and unmaintained

### ISSUE THREAD

**Issue by petemoore** [crosstool-ng/crosstool-ng#999]
See [crosstool-ng CI](https://travis-ci.org/crosstool-ng/crosstool-ng/builds).

I feel it would be worth investing in a cross platform CI (macOS/Linux/Windows) that first dereferenced toolchains that exist on the host, explicitly install any required dependencies, and then invoke a few toolchain builds. Travis CI supports Linux and macOS, appveyor supports Windows.

With a couple of CI badges in README.md to highlight the state of the latest CI runs, there is a good chance problems will be identified and rectified sooner. It should also help a great deal when reviewing Pull Requests.

**Comment by stilor** [comment]
Travis no longer works for us once they've placed time limits on jobs. I'll keep it open to research alternatives (someone has suggested gitlab before).

**Comment by bhundven** [comment]
I'm going to investigate gitlab-ci, as I've started using it at work. I'll have some updates tomorrow.

**Comment by bhundven** [comment]
I've imported crosstool-ng to: https://gitlab.com/crosstool-ng/crosstool-ng

**Comment by abrodkin** [comment]
@bhundven I'm wondering if you were able to enable CI for CT-NG in GitLab? There's just bare repository by the link you posted above.

**Comment by stilor** [comment]
I've disconnected Travis (sorry @bhundven I had to delete it - an attempt to mark it inactive produced a weird error about "membership event not handled by travis service"; and there is no setting to select the events; I assume it is broken as GitHub started to deprecate GitHub Services, including Travis and expects people to migrate to webhooks).

I also inactivated the waffle.io hook - it had disconnected, apparently, a few months ago with tasks not being updated and the hook status showing failed-to-notify icons. If you want it you can reactivate it after fixing the configuration.

**Comment by bhundven** [comment]
No worries @stilor! Do you want me to keep on with investigating gitlab?

**Comment by stilor** [comment]
If it yields a working CI, I'm all for it!

**Comment by bhundven** [comment]
@stilor email me your gitlab login, and I'll add you to the new project.
I think I have CI/CD working in the gitlab-ci branch.

**Comment by antmak** [comment]
@bhundven Great job!

I wonder is it possible to put a status icon to REAMDE.md ? Also I wonder is there a way to automatic synchronize the gitlab repository?
